### ISSUE TITLE
 Use proper HTTP codes (4**, 5**, etc.) in RPC

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1002]
Hello,

I believe we could improve our RPC by using the correct HTTP status in our responses.
https://www.restapitutorial.com/httpstatuscodes.html

This helps people who will use the API, since most of SDK and frameworks are already adapted to work with those HTTP codes.

EDIT: As Erik mentioned below, we are following the standard for JSON-RPC endpoints, which differs from HTTP endpoints.

**Comment by shargon** [comment]
Also we should improve the error verbosity, now is hard to know why something was wrong

**Comment by erikzhang** [comment]
https://www.simple-is-better.org/json-rpc/transport_http.html#response

**Comment by lock9** [comment]
@erikzhang  Hi Erik, I didn't understand what you mean.
I think this is the most updated version from IETF:
https://www.ietf.org/assignments/http-status-codes/http-status-codes.xml

**Comment by rodoufu** [comment]
We can also use the HTTP method (GET, POST, DELETE...) for each operation, I don't think we need much of them but this may make a better experience for using rpc tools.

**Comment by lock9** [comment]
Hi @erikzhang, is it ok for you if we follow this latest document instead of the one you provided? It is from a more reliable source and it was updated more recently.

**Comment by erikzhang** [comment]
No. I don't think so.

Your document is for HTTP, and the meaning of these status codes is for HTTP response, they belong to the HTTP layer.

JSON-RPC over HTTP, it is a higher level protocol. All JSON response for the HTTP layer is a normal response, and should use a 200 status code.

> 200 OK
for responses (both for Response and Error objects)

We can't use HTTP status code for higher level protocol. And this document is the standard for how to use HTTP status code in JSON-RPC correctly.

**Comment by lock9** [comment]
@erikzhang  you are correct. I have to confess I didn't know there was a protocol called "Json RPC", I thought this was just a fancy word for API over Json.

So we can keep the same codes in JSON-RPC, but I think we need an API based on HTTP, because all main frameworks are expecting to work with HTTP (different return codes).

My suggestion:
- Keep the way it is for JSON-RPC
- When we add Restful endpoints (#1004), we can use these new codes. This way JSON-RPC is compatible with JSON-RPC protocol, and REST is compatible with REST protocol.

I have updated the issue to inform the difference.
Is it ok for you if we use this return codes when we add the Rest endpoints? Now it is clear to me that they are different

**Comment by lock9** [comment]
I`m closing this because RPC won`t be changed. New REST implementation will have this configured instead.
