### ISSUE TITLE
Use swagger.io to document our API

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1003]
Hi,

I think we should add a swagger.json (swagger support) in our Ret endpoints. This way it is much easier for developers to interact with it.
Here is an example:
https://petstore.swagger.io/

**Comment by shargon** [comment]
Agree

**Comment by Tommo-L** [comment]
Close? it moved into neo-ngd project.

**Comment by shargon** [comment]
Could you write the link? it could be useful for people that find this issue @Tommo-L

**Comment by Tommo-L** [comment]
Here https://github.com/neo-ngd/neo-common-plugins
