### ISSUE TITLE
Transaction failed when multi addresses in one wallet.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1007]
It's a bit odd, but it's true. When multi addresses are generated in a wallet, no need too many, two or three addresses is enough, and then send a bit gas to each one. Then if you make a transaction and if the ```from``` address has more than double of your transfer value, the tx will be made successfully. Else, it will return ```Failed execution```. My example is like this:
![image](https://user-images.githubusercontent.com/38493437/62601417-e6484280-b923-11e9-805f-c1b36ecce6c2.png)
For example, when ```value``` is 150 or 140, it will choose the 5th or the 7th address. They have balance of 150, and 150 and 140 is more than 150/2, then execution failed.

**Comment by shargon** [comment]
So it fail when need to split the amount, right?

**Comment by superboyiii** [comment]
Not for all, but seems 1/2 of the ```from``` address balance is a watershed. And I also find when making a transaction, it'll look for the least balance(except ```from``` address) to pay for ```net_fee + sys_fee```. If this address doesn't have enough fee, then execution fails.

**Comment by shargon** [comment]
I send 10 to one, 5 to other, and send back 15 to the original, and all works as expected, could you provide me a small sample ?

**Comment by nicolegys** [comment]
@shargon here is a small sample
![image](https://user-images.githubusercontent.com/43694095/62616024-20740d00-b941-11e9-8ad3-472faa51d6cb.png)

**Comment by shargon** [comment]
With gas could be different, because maybe it need more gas for the fee. Could you provide me a small example with neo? i think that is easier to test with neo

**Comment by superboyiii** [comment]
> With gas could be different, because maybe it need more gas for the fee. Could you provide me a small example with neo? i think that is easier to test with neo
![image](https://user-images.githubusercontent.com/38493437/62672803-a2f6de00-b9ce-11e9-99b8-8ad295d5bd23.png)
@shargon  Got it? When the transfer value is more than ```fromAddress.balance/2````, it always look for the least balance address to pay for ```Fee```. If the gas balance in that address is not enough to pay for fee, transaction execution will fail. But if the transfer value is less than ```fromAddress.balance/2```, transaction can be made successfully.

**Comment by shargon** [comment]
Step 1

![image](https://user-images.githubusercontent.com/3167973/62678213-1e499700-b9b1-11e9-91dc-e83447300398.png)

Step 2

![image](https://user-images.githubusercontent.com/3167973/62678282-5f41ab80-b9b1-11e9-9abd-6e40ce0455f3.png)

Error:
![image](https://user-images.githubusercontent.com/3167973/62678511-0292c080-b9b2-11e9-8036-a33ace2bc559.png)

There is not enough gas in the wallet one for send this to wallet two

**Comment by nicolegys** [comment]
We change snapshot to snapshot.Clone(), then this issue is fixed.
![image](https://user-images.githubusercontent.com/43694095/62679111-0c361b80-b9e6-11e9-83be-279cf206443c.png)

**Comment by shargon** [comment]
This code

https://github.com/neo-project/neo/blob/68271a961972c1acbc603f360b8dea3c58472af0/neo/Wallets/Wallet.cs#L306-L320

Should be executed outside the loop, and the loop, shoud be only for find the gas account

**Comment by shargon** [comment]
Yes, it works. Do you want to apply the patch, or i do?
![image](https://user-images.githubusercontent.com/3167973/62679547-1ab80f00-b9b5-11e9-90f5-9883492a3727.png)

**Comment by shargon** [comment]
Nice catch team 😉 ! @superboyiii @nicolegys

**Comment by nicolegys** [comment]
You apply the patch 😉

**Comment by superboyiii** [comment]
@shargon Thanks for your investigation.
