### ISSUE TITLE
Testnet balance issue

### ISSUE THREAD

**Issue by cryptodeveloperin** [neo-project/neo#1015]
I have created neo Testnet wallet node (not private) using 2.9.4 version.. I have create some address and get testnet coin from neowish.ngd.network site.
Example transaction:
https://neoscan-testnet.io/address/AGx6F5rdqUtbg4ijV3joDZAehhMLMkWQiv

But my transaction revert in 60 second. I have checked the same issue with neowish testnet as well. I have already allow port 20332 only from my local pc ip. not allowed for all IP's, but still same issue.

Can you tell me what can be cause? please share sample config settings as well protocol json changes. Is it issue for magic number of protocol json?

**Comment by lock9** [comment]
Hi @cryptodeveloperin,
I believe you are using a very old version, we are currently in version 2.10.3. Could you try again?
I will close this but feel free to create a new issue if the problem persists.
Thanks.
