### ISSUE TITLE
Isolate unit tests

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1019]
Currently, we have many problems with unit tests, for example: if we create a contract, we must eliminate it after the unit test; otherwise, some tests may fail. If you want to test the consensus, you will have many problems, because there are some tests with 4 validators, and if you change these static variables, you will break these tests.

This is because `Blockchain` is static and is shared among all unit tests. We must isolate all unit tests,  this could allow parallel execution.

Original idea comes from: https://github.com/neo-project/neo/issues/922#issuecomment-526072756 @eryeer

**Comment by lock9** [comment]
Definitely, tests should be totally independent. I thought that the tests were independent 😢

**Comment by rodoufu** [comment]
If we use DI (https://github.com/neo-project/neo/issues/1042) we can let the container handle the scopes for the tests, or even if we need to implement the scope on the DI container we will have a way to do it that works for all the cases we need and not just in one place.

**Comment by igormcoelho** [comment]
@shargon I'm very sad of your behavior, this is not good for Neo community or anything else. Last time I was working on this topic, you simply closed my issue, when I was nearly fixing it. @lock9 just accepted a temporary fix and everything was dropped.

Now you restart the issue, not even mentioning past discussions. 

Ethics is a minimum requirement for things to evolve, as this way is getting unpleasent and impossible to contribute here.

**Comment by shargon** [comment]
@igormcoelho Could you explain more what issue I closed? if was as you said I apologize for it.

**Comment by igormcoelho** [comment]
https://github.com/neo-project/neo/issues/922#issuecomment-513252869

**Comment by vncoelho** [comment]
@shargon, I also believe that this has also already happened before, sometimes with noticing.
Another recent example is what happened at Scooped Signatures.
This is not the way we work and contribute.

**Comment by igormcoelho** [comment]
Let's remove these, and focus back on issues.

**Comment by igormcoelho** [comment]
> Definitely, tests should be totally independent. I thought that the tests were independent cry

@lock9 we talked about that already, tests are not independent. When you merged this one: https://github.com/neo-project/neo/pull/936 it was actually partially solving a side-effect of these things.

We need to find a way to properly isolate bigger components of Neo... it will help testing, but also making the platform safer.

**Comment by shargon** [comment]
I did some test with NUnit, it paralellizes the Unit test, and was faster!

![image](https://user-images.githubusercontent.com/3167973/65963697-9b4a3780-e45b-11e9-8c0a-dd64307aa8dc.png)

The problem, that it require the complete isolation of the UT.

But is easy to port

https://xunit.net/docs/comparisons
