### ISSUE TITLE
Release v2.10.3

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1021]
@erikzhang, maybe it is a good time to release `v2.10.3` or better to wait for releasing it together with `3.0.0-preview-1`?

**Comment by superboyiii** [comment]
Agree. For ```v2.10.3```, the sooner the better since mainnet need it to prevent from restarting frequently . I think there's no need together with ```3.0.0-preview-1```.

**Comment by shargon** [comment]
Agree, it contains some important fixes

**Comment by erikzhang** [comment]
Released.
