### ISSUE TITLE
Standard Byte Serialization for NEP3 stack items

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#1027]
I propose a standard serialization for NEP3 based stack items (and virtual types like String), so that we can easily convert in and out (except by Void and Interop).

The scheme would prefix by type and allow recursive behavior, however putting readability over performance

**Comment by igormcoelho** [comment]
Useful for https://github.com/neo-project/neo/issues/1025#issuecomment-521059454

**Comment by lock9** [comment]
Can't we use JSON as the default serialization model? We need some 'smart-services' to make this serialization and deserialization. This call is completely stateless, it can be done concurrently.

**Comment by igormcoelho** [comment]
in fact, I mean, byte serialization. Example:
String "HelloWorld" => 48656c6c6f576f726c64 in bytes. However, it doesn't differentiate between a pure bytearray, or a biginteger.
So, I propose to encode it as 0x07 (string code) + varsize + data. So it would become: `071048656c6c6f576f726c64`.

This preserves type information, and everything we need on bytearray level.

Currently, we have the following codes:
```
0x00 - signature
0x01 - bool
0x02 - int
0x03 - hash160
0x04 - hash256
0x05 - bytearray
0x06 - pubkey 
0x07 - string
0x10 - array
0xf0 - interop
0xff - void
```
We need to add a new one for Map (already proposed on NEP3 ammendment), and leave space for others in the future.

To enhance serialization, I propose another encoding standard for empty types (empty array, empty map, empty string, ..., etc), and specific encoding for pubkey and signature types.
Example: 0x06 + 0x00 (compressed secp256r1) + 0x03...pubkey

For empty "stuff" we can just add 32 (0x20), so empty array would be 0x10 + 0x20 = 0x30.

An array with two empty arrays and two empty strings could be: `0x100430302727`, very concise and clear.

All prefix over 0xf0 would have disabled serialization (void and interops). This can become the standard for contract deploy parameters, lambda typed parameters, hardcoded syscall parameters, etc.

**Comment by rodoufu** [comment]
I was just about to ask about using protobuf (https://developers.google.com/protocol-buffers/) for serialization/deserialization, have you found about that?
With that, no one else will need to implement our serialization schema, they just use our protobuf project and they can do the serialization.

**Comment by igormcoelho** [comment]
Some guys have proposed this many months ago @rodoufu , but in this case it's complicated... we need to embed it in internal structures of neo-vm, mostly for internal usage, so at this point it's not an advantage to adopt protobuf, as it would overcomplicate internal stuff. For external stuff, RPC, P2P messages, that's far more reasonable to think about it, since it's about communication with the external world. 
Yet, I don't think we will gain much from, besides a RPC point of view, like we have discussed these days... this is the biggest advantage, in my opinion.

**Comment by rodoufu** [comment]
@igormcoelho we can generate the POCO classes from the proto templates (https://github.com/protocolbuffers/protobuf/tree/master/csharp) to use in our projects, but you're right, it can complicate things.

**Comment by igormcoelho** [comment]
I like the "legible" format of Neo serialization, what is the opposite of protobuf. Blockchain requires transparency, and its very useful sometimes, to just "crack" chain byte info in few second, with any available hex editor. Performance is not worth the cost in this case, for me. But for rpc its perfect application, we can follow that.

**Comment by lock9** [comment]
@igormcoelho  is this going to be transparent for the user or are we expecting the user to create their own deserializer?

**Comment by igormcoelho** [comment]
Serialize is a Runtime function.. this is a compile-time serialization for the items (that can also become the standard for runtime on Neo3, it would be nice to have a standard).

**Comment by devhawk** [comment]
As part of this effort, can we specify a serialization format for big integers that is not dependent on the internals of C#'s implementation? I'd like to get away from having to build language specific libraries for parsing  big integers

**Comment by erikzhang** [comment]
Serialization format for big integers:

1. Signed
2. Little-endian
3. No extra leading `0`s

Examples:

```
0 => (empty byte array)
```

```
1 => 01
```

```
255 => ff00
```

```
-1 => ff
```

```
1000000000000000000000 => 0000a0dec5adc93536
```

```
3000000000000000000000 => 0000e09b51095da1a200
```

**Comment by lock9** [comment]
Is this in progress?

**Comment by lock9** [comment]
Hi @neo-project/core 
This is blocking some important issues. We have decided to have a standard, now we just need to define the standard, is that correct?
