### ISSUE TITLE
[Neo3] Witnesses should deny access to Verification and Invocation script onchain

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#1029]
I think we shouldn't give access to Verification or Invocation script on Neo3.
InvocationScript is already non-deterministic, and cut-off on Neo2, but Verification can also be not good to access, if we follow a "Neo SegWit" logic... If we use it on script, we need it to execute the script, so this ties us forever to maintaining that witness on blockchain.
If user really wants to handle VerificationScript, it should pass it manually on Entry (Script) to the contract, that takes the Hash160 and matches against a known witness.
It's much better for network optimizations (we can easily drop all Witnesses in short time periods).

**Comment by igormcoelho** [comment]
Related to: https://github.com/neo-project/neo/issues/906 (this allows us to safely name a onchain feature as "Witness", and it would be corresponding to a Verification ScriptHash)

Related to: #840 (Witness price is just instantaneous price, not future prices).

**Comment by igormcoelho** [comment]
Ok, we got the blessing of master yoda here... so I'll put it ready-to-implement xD

This is an easy task, good to invite new souls to interact :) 

Here's the specification:

* Remove `Neo.Witness.GetVerificationScript` interop call
* Remove `Neo.Transaction.GetWitnesses` interop call (since `Neo.Witness.*` prefix will cease to exist).

**Comment by lock9** [comment]
Easy to do? 😂 
Please, let's leave at least 2 days in the design phase so are sure this is implemented correctly.
Thanks

**Comment by shargon** [comment]
Pros and cons of this feature?

**Comment by igormcoelho** [comment]
I only see pros.
Cons would exist on neo2, as a breaking change
 On neo3 thats fine, people can still implement same stuff by explicitly passing verifscript, so no cons to me.

**Comment by lock9** [comment]
but what are the pros @igormcoelho? I also didn't understand the design.
@neo-project/core if you guys are in agreement, I think we can put this into ready-to-implement, I'm not doing it because I can't really understand the changes required.

**Comment by igormcoelho** [comment]
> According to Erik's comment #1081 (comment) I think this will be resolved with these refactors

Thanks for informing @shargon . It's a good place to fix this :+1:
