### ISSUE TITLE
Claim Problem

### ISSUE THREAD

**Issue by zhjjj** [neo-project/neo#103]
Hi
I've got some problems about claim.
1、Is there any other way to get the claimed and unclaimed gas amount of an address except the client command 'show gas'?  Can I get that through some JSON-RPC api or I have to calculate them by myself?
2、Can I send a Claim Transaction by JSON-RPC 'sendrawtransaction'? I tried that but it returned error 'Error: broad tx not correct'. I've try some way to confirm that the transaction hex is correct but still got that error. Do you have any ideas what can be wrong?

Thanks in advance,
Regards

**Comment by AshRolls** [comment]
@zhjjj Please join the #develop channel in slack where we will be able to assist you.

**Comment by zhjjj** [comment]
@AshRolls So how to join the slack channel? It seems that the invite link not work any more. https://www.reddit.com/r/NEO/comments/6u99ci/slack_channel/  tells me "invite_limit_reached"
