### ISSUE TITLE
[NEO3] RPC method invokeScript will fail when directly calling native contract interop service

### ISSUE THREAD

**Issue by MorganDream** [neo-project/neo#1035]
I learn in NEO3, there are 2 ways to construct script to use rpc method to invoke native contracts:
- A: args + operation + systemCall + native_contract_interopservice
- B: args + operation + scripthash + systemCall + System.Contract.Call

Method A will always fail.
Example: Invoke `name` method of NEO contract:
Method A: 00c1046e616d656845c49284 - FAULT
Method B: 00c1046e616d651415caa04214310670d5e5a398e147e0dbed98cf4368627d5b52 - HALT

**Comment by igormcoelho** [comment]
#12 bytes
00 0: PUSH0  #An empty array of bytes is pushed onto the stack
c1 1: PACK  #
04 2: PUSHBYTES4 6e616d65 # name
68 7: SYSCALL 45c49284

#33 bytes
00 0: PUSH0  #An empty array of bytes is pushed onto the stack
c1 1: PACK  #
04 2: PUSHBYTES4 6e616d65 # name
14 7: PUSHBYTES20 15caa04214310670d5e5a398e147e0dbed98cf43 # B1pGC
68 28: SYSCALL 627d5b52


Need to see why... other situation is standard entry point (string, object[] args), do we have it? If so, it may require two params (empty array) , did you test that?

**Comment by MorganDream** [comment]
The scripthash is NEO, and it's definitely correct, cause Method B is using it, and it succeeds.

**Comment by shargon** [comment]
You cannot call neo native methods directly, you will get the error at:

https://github.com/neo-project/neo/blob/a705b43ca9a62b3a951898ba1b9550aa461160e9/neo/SmartContract/Native/NativeContract.cs#L89

**Comment by KickSeason** [comment]
@shargon Why we register interop services? The cann't be used.

**Comment by Tommo-L** [comment]
why not support? or for security consideration?

**Comment by Tommo-L** [comment]
If we don't support, then we can't also use NEO and GAS in contract directly, which like the following:
![image](https://user-images.githubusercontent.com/43396869/63325742-5495f780-c35d-11e9-856e-03751377adea.png)

**Comment by Tommo-L** [comment]
I understand, the context is different, the native contract execution context must be themselves.

**Comment by KickSeason** [comment]
I see. Only here:
https://github.com/neo-project/neo/blob/e7928986c7f724c857c194cd68c6263b135b75c1/neo/SmartContract/Native/NativeContract.cs#L38

**Comment by MorganDream** [comment]
@shargon What do you think? Shall we keep it like this or change it?

**Comment by igormcoelho** [comment]
> Why we register interop services? They cann't be used.

@kickseason this was the proposed design, by actually performing an "internal/private" syscall.
we discussed on it, and concluded that supporting both invocation ways (syscall and call) wouldnt be good.

@tommo-l described correctly: "I understand, the context is different, the native contract execution context must be themselves."

In fact, if you do a syscall on native contract, you wouldnt be able to protect the stack with only intended parameters (appcall does this now, considering standard entrypoint format); isolate the actual idea of a regular call.

Finally, @morgandream, if we remove this, we lose ScopedSig protector for native NEP-5. If we allow syscall, we allow script to run on same context level as invoker, and we would never be able to describe specific situations where we want or not the intended witness (unless we redesign Scoped witnesses too).

**Comment by KickSeason** [comment]
Thanks @igormcoelho  @shargon . We can close this.
