### ISSUE TITLE
Translating the website into german language

### ISSUE THREAD

**Issue by Badeindi** [neo-project/neo#104]
Being a German native speaker I'd like to propose the translation of the website into my language. If NEO want's to penetrate German markets as well information about it needs to be translated.

**Comment by erikzhang** [comment]
You can contribute to NEO website at https://github.com/neo-project/neo.org/tree/develop
Or contribute to NEO documentations at https://github.com/neo-project/docs

**Comment by Badeindi** [comment]
Thanks a lot for replying Erik! I'll try to give it my best! Regards MichaelAm 17.11.2017 7:51 vorm. schrieb Erik Zhang <notifications@github.com>:You can contribute to NEO website at https://github.com/neo-project/neo.org/tree/develop
Or contribute to NEO documentations at https://github.com/neo-project/docs
