### ISSUE TITLE
[NEO3] Discussion: Can we add `ContractMethodAttribute` into `ContractManifest`

### ISSUE THREAD

**Issue by MorganDream** [neo-project/neo#1050]
Now class `ContractMethodAttribute` is out of Manifest, and it looks like an extension to `ContractMethodDescriptor` with additional props:  Price & SafeMethod. I guess the reason may be that a contract owner should not(and can not) decide price and safemethod of its methods. So how about generate the price when contract is deployed.
* Benefits of doing this:
All contracts(not just the native ones) methods (expect for some special case, e.g. dynamic invoke) can have a price which enable sdk users to know how much their transaction would cost without having to invoke it on node in advance. 
This would save time for sdk user, it would also alleviate stress for seed node, which may be used as sdk query node.

**Comment by shargon** [comment]
Is used only for native contracts

**Comment by lock9** [comment]
Morgan is here and decided to close this.
Thanks
