### ISSUE TITLE
Give net_fee decimals to avoid unreasonable fee cost

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1051]
Now the net_fee is using ceil() for calculation to ensure NEO holders can get inspire of each NEO.  (1 ```NEO``` get 1/100_000_000 ```GAS``` if  total ```net_fee``` is 1 in a block). But it causes a high cost of ```Fee``` payment. For example, transfering 0.01 GAS to B address could cost 1GAS as ```net_fee```. I think it's necessary to design a new scheme to avoid both of these two issues. For example, turn gas-decimals to 16.

**Comment by shargon** [comment]
We should decrease the GAS cost, because 1 is very expensive

**Comment by igormcoelho** [comment]
This is a pricing problem.. I agree 1 GAS is too expensive, we can reduce it.

**Comment by lock9** [comment]
How can we make this change without increasing the amount of space required for Gas? 
In my understanding, we need to double the space used for GAS, or is there another viable option?

**Comment by shargon** [comment]
And is not possible to reduce the prices /10? The current price for regular transfer is too high

**Comment by lock9** [comment]
Would it be possible to increase the total amount of GAS? instead of 100.000.000, make it 1.000.000.000? Would this help?

**Comment by lock9** [comment]
@shargon  haha calm down Shargon, it would be the same total amount if we increase the decimals 😂  Don't punish me for my bad ideas haha
