### ISSUE TITLE
Multi-node consensus doesn't create block

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1059]
Although single node mode works well. However, seems multi nodes don't achieve consensus, still need to fix.
![image](https://user-images.githubusercontent.com/38493437/63675669-e7320d00-c81b-11e9-9982-b017cdddaa2f.png)
![image](https://user-images.githubusercontent.com/38493437/63675674-e9946700-c81b-11e9-8c42-0ddc4eacd162.png)

**Comment by erikzhang** [comment]
Does the PR fix this issue? #1053

**Comment by superboyiii** [comment]
Let me have a try.

**Comment by shargon** [comment]
I think that these tests was without the patch #1053

**Comment by superboyiii** [comment]
@erikzhang @shargon  https://github.com/neo-project/neo/pull/1053 this PR has truely fixed this issue.
I'll close this issue.
