### ISSUE TITLE
Wallet shows 0 balance

### ISSUE THREAD

**Issue by dgcpamd** [neo-project/neo#106]
Hello-  I purchased 2 NEO about a week ago and have also claimed some GAS.  However, when I opened my Neon Wallet a few minutes ago it shows a 0 balance.  I've tried refreshing, but nothing changes.    Is there anything else I can do?

**Comment by erikzhang** [comment]
You can get help for neon-wallet from https://github.com/CityOfZion/neon-wallet/issues
