### ISSUE TITLE
Run NEO Blockchain in local memory (RAM) and make DB a flexible choice

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1064]
Has connection with #1063 and #966 

@devhawk has already commented that NGD Seattle was working on tools for running the NEO blockchain only using local memory (if client is killed everything needs to be resynced), which is also an direction we have for micro-controllers and the IoT applications we used to work on here in Brazil.

I believe that this is a good direction for designing the use of storage with basic functions.
Then, instead of switching from LevelDB to RocksDB we would make it more flexible for just running on the local memory and then try to design a flexible scheme for switching DBs upon nodes runner choices.

**Comment by shargon** [comment]
Is something easy to do now, i like it.

**Comment by shargon** [comment]
We can move this idea to ready to implement? @lock9 @vncoelho I want this feature for save the live of my SSD 😊

**Comment by shargon** [comment]
We can move this idea to ready to implement? @lock9 @vncoelho I want this feature for save the live of my SSD 😊

**Comment by shargon** [comment]
Wrong bottom, sorry 😅

**Comment by devhawk** [comment]
I was able to do this in neo express with the current store abstraction. However I thi k that abstraction could be improved so that it's easier to implement new storage implementations

**Comment by erikzhang** [comment]
I consider using `Dictionary` as the underlying container for storage. But the difficulty is how to implement efficient search?

**Comment by lock9** [comment]
@erikzhang  maybe we shouldn't care about search efficiency since we won't handle a lot of data. Even if the search is not very efficient (we can use Linq), it will still work. What do you think?

**Comment by devhawk** [comment]
There's no reason to give up on search efficiency. For example, today's data cache classes have a dictionary like interface, but with additional features like Find and Commit. I'd like to see these abstract classes be changed to interfaces. That way, different storage providers can have different implementations for the methods. Maybe the production store uses B+ trees while the neo-express store has an simple linear search since development chains tend to be shorter so efficiency isn't as critical.

**Comment by lock9** [comment]
But are we going to spend our time and energy optimizing something that is just for us? I'm not saying we have to "never optimize it", however, we have 124 issues open and I don't see why we should spend energy with this subject now. Can't we do this later?
