### ISSUE TITLE
Make fee format be unified.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1069]
In ```getblocksysfee```, ```fee``` returns full decimals. However, in ```getrawtransaction```, ```fee``` has decimal point. I think it's necessary to make fee format be unified in ```RPC```, otherwise, it'll make a lot of users be comfused.
![image](https://user-images.githubusercontent.com/38493437/63661844-b8517200-c7ee-11e9-99bf-c0595c5af7e9.png)
![image](https://user-images.githubusercontent.com/38493437/63661816-9bb53a00-c7ee-11e9-898a-aeef966752e7.png)

**Comment by erikzhang** [comment]
> getapplicationlog--->value(full decimals)

> invokefunction, invokescript--->gas_consumed, value(full decimals)

What `value`? I didn't see it.

**Comment by erikzhang** [comment]
@superboyiii Please check the fixes.

**Comment by superboyiii** [comment]
@erikzhang OK

**Comment by superboyiii** [comment]
> > getapplicationlog--->value(full decimals)
> 
> > invokefunction, invokescript--->gas_consumed, value(full decimals)
> 
> What `value`? I didn't see it.

I mean the invocation return value. Such like this:
![image](https://user-images.githubusercontent.com/38493437/63847156-c86c7b80-c9bf-11e9-8862-0566ccc2144d.png)

**Comment by erikzhang** [comment]
These are `StackItem`s and I don't think they have any problems.
