### ISSUE TITLE
GetValidators return same value as GetNextBlockValidators

### ISSUE THREAD

**Issue by KickSeason** [neo-project/neo#1075]
When `OnPersist`, NeoToken use `GetValidators` to set storage `NextValidators`.
And `getNextBlockValidators` just read the storage.
But `getValidtors` also call `GetValidators` return the same value.

This is confusing.
https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/SmartContract/Native/Tokens/NeoToken.cs#L111-L117
https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/SmartContract/Native/Tokens/NeoToken.cs#L238-L248

https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/SmartContract/Native/Tokens/NeoToken.cs#L213-L216

**Comment by shargon** [comment]
This is because after `OnPersist`, next validators are copied to the current validators, isn't it?

**Comment by KickSeason** [comment]
@shargon `GetValidators` and `GetNextBlockValidators` returning same value is by design?
We can get validators of last block and current block. We can't get next block in the middle of persist process. Do we need `BeforePersist` and `AfterPersist`?

**Comment by shargon** [comment]
I will review it deeper

**Comment by KickSeason** [comment]
@shargon Thanks Shargon.

**Comment by KickSeason** [comment]
@shargon Did you review?

**Comment by KickSeason** [comment]
@erikzhang  Am I right?

**Comment by shargon** [comment]
I have this in my TO DO list, not reviewed yet, sorry 🙏

**Comment by KickSeason** [comment]
@shargon Thank you.

**Comment by erikzhang** [comment]
> Am I right?

I don't think so. 😂

**Comment by KickSeason** [comment]
I will review again.

**Comment by KickSeason** [comment]
Not  same.  Snapshot will commit after run every tx.
But `GetValidators` may be different in different tx of new block. Is this acceptable?

**Comment by lock9** [comment]
@shargon 😆

**Comment by shargon** [comment]
> But GetValidators may be different in different tx of new block. Is this acceptable?

I think that this is the expected behavior

**Comment by lock9** [comment]
@shargon @KickSeason are you guys saying that GetValidators can return different results in the same block?
Tx1 = validators1
TxN = validators2?

**Comment by shargon** [comment]
Yes, if tx1 change the validators

**Comment by KickSeason** [comment]
Then I will close this.
