### ISSUE TITLE
Consensus optimization during transaction request

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1077]
When reviewing https://github.com/neo-project/neo/issues/1040 an issue was discovered and a possible optimization.

The first thing we can see is in the following lines

https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/Consensus/ConsensusService.cs#L465-L468

We are creating an inventory of the pending transaction hashes, but calling the wrong method, we should call 

https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/Network/P2P/Payloads/InvPayload.cs#L27-L35

Because it control the limits by `MaxHashesCount` and the other doesn't.

This is the first issue, the next one is an improve.

As you know, in P2P was added a compression mechanism (https://github.com/neo-project/neo/pull/710), compression is ver useful for improve the TPS, but is better on bigger messages than smaller. So if a node is asking about 500 TX, why we should send it one by one? We should pack all of this tx, and send in a bulk message. Is more optimal and can save resources.

https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/Network/P2P/ProtocolHandler.cs#L180-L211

**Comment by shargon** [comment]
Please take a look @eryeer and @Tommo-L

**Comment by Tommo-L** [comment]
Good idea, we have seen

**Comment by eryeer** [comment]
> When reviewing #1040 an issue was discovered and a possible optimization.
> 
> The first thing we can see is in the following lines
> 
> https://github.com/neo-project/neo/blob/919cc804de99b299c1f79f9c4cb14d3411e588c0/neo/Consensus/ConsensusService.cs#L465-L468
> 
Thanks for your great idea, but I found the function `OnRestartTasks` in `TaskManager` recreate the payload into group,  and then broadcast the payload.
https://github.com/neo-project/neo/blob/1a392037f23a767a943c7f05adb0ce0d6916297f/neo/Network/P2P/TaskManager.cs#L123-L124
Do we need to create payload into group twice? @shargon

**Comment by shargon** [comment]
Thanks @eryeer I will focus on the second part then, because as you said, the first one is already good.
