### ISSUE TITLE
SupportedStandards returning VMArray with ByteArray items instead of string items

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1079]
**Describe the bug**
When I call supportedStandards, the resulting VM Array contains 2 items, both of them of type "ByteArray" and not "string"

**To Reproduce**
1. Invoke "supportedStandards" using ApplicationEngine
2. Iterate through the StackItems in the resulting array
3. Check the type

**Expected behavior**
Since the SmartContract declares a string[], the items in the VMArray should be an String and not a byte array

**Screenshots**
![image](https://user-images.githubusercontent.com/38396062/64071541-a8081f80-cc52-11e9-8e1f-d451ca4dd36c.png)
![image](https://user-images.githubusercontent.com/38396062/64071556-03d2a880-cc53-11e9-9dd2-1d43e3bda6e9.png)
![image](https://user-images.githubusercontent.com/38396062/64071562-2ebcfc80-cc53-11e9-9c41-4a0e938f6cf0.png)

**Platform:**
 - OS: Windows x64
 - Version: Latest master branch with latest neo-cli master branch (with additional utilitary methods)

**Comment by shargon** [comment]
The String represenation inside the vm is as ByteArray, you need to call the method `GetString` https://github.com/neo-project/neo-vm/blob/3b9fc1390f5d69da8e179de6af08e93cd9fdd2e4/src/neo-vm/StackItem.cs#L59 in order to get your desired value

**Comment by lock9** [comment]
@shargon  but why I can get the correct type when I return just a String? The type is "string" and not "ByteArray"

**Comment by shargon** [comment]
But there are no strings in the VM. You need to know the expected value from the abi, and converting according to it

**Comment by shargon** [comment]
But the expected value is an array, not an string 😅

**Comment by lock9** [comment]
@shargon  an array of strings! hahaha
I know that there is no string in the VM, I just want to understand why when we return a "string"  the VMStackItem is of type string, but when we use it inside an array, it is not seen as a string

**Comment by igormcoelho** [comment]
@lock9 what do you mean by "return a string"... you mean, return in a method? And then RPC tells you this is a string, not a bytearray?
Theoretically, we could do that, because we have NEP-3 type String, but I don't really see how we could do that... I remember seeing a similar stuff, someday, guess it was on Notify. I don't know how it could decide between both types in a reliable way.

**Comment by lock9** [comment]
Hi guys.
I will close this issue, not because I don't think it is important, but because I don't want you guys spending any energy. Things work today, this is merely a small enhancement.
I appreciate all the attention.
