### ISSUE TITLE
Simplify interop services

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1082]
**Summary**
Currently, our interop service API is very complicated. For example, to get a transaction, we need to call `System.Blockchain.GetTransaction` and then call `Neo.Transaction.GetScript` to get the fields of the transaction. Maybe we can simplify them.

**Solution**
In fact, we have an API that is very simple, that is `System.Runtime.GetNotifications`.

https://github.com/neo-project/neo/blob/2da4fb16b0e15b988e75cea072ae7e7bcad129b3/neo/SmartContract/InteropService.cs#L237-L252

We can change all the APIs that get the data into this way. This way we can remove a lot of redundant APIs.

**Where in software does this update applies to?**
- SDK
- Other: NeoContract

**Comment by shargon** [comment]
Totally agree, we should follow this way

**Comment by shargon** [comment]
I will change this https://github.com/neo-project/neo/pull/1081 in order to fit your pattern, it could save a lot of opcodes

**Comment by igormcoelho** [comment]
Fully agree Erik, as long as Array behaves as Object, this will be fine.
