### ISSUE TITLE
Return generated notifications when using `invokescript` endpoint

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1095]
**Summary**
When we use *invokescript* to test a nep-5 transfer, we can't see the resulting notifications, meaning we can't really assure that our execution was the way we expected.

**Do you have any solution you want to propose?**
We should return the list of notifications generated when we run invokescript (or equivalent)

**Where in the software does this update applies to?**
- RPC

**Comment by Tommo-L** [comment]
Sine RPC has become a plugin, could help us move this issue to neo-modules, and we'll fix it.
