### ISSUE TITLE
Integer overflow on GetTransactionHeight

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1096]
**Describe the bug**

In a very far future an integer overflow could be produced on GetTransactionHeight
https://github.com/neo-project/neo/blob/661b80e62309433af1d39199e5e003b20a0d3116/neo/SmartContract/InteropService.cs#L335

**To Reproduce**
When we call `System.Blockchain.GetTransactionHeight` the BlockIndex (uint) is converted to int in order to return -1 if is not present.

**Expected behavior**
Should maintain the same type, uint or converted to BigInteger.

**Sample**
![image](https://user-images.githubusercontent.com/3167973/64712363-5dd93680-d4bb-11e9-8142-10bfefccf1dd.png)

**Comment by erikzhang** [comment]
Yes, it will overflow after a thousand years. But can we give this problem to future humans to solve it? Maybe they will be smarter than us.

**Comment by lock9** [comment]
@shargon closeable?

**Comment by shargon** [comment]
The fix was included in https://github.com/neo-project/neo/issues/1081
