### ISSUE TITLE
Unify version between payloads

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1102]
**Summary**
Currently we have different types for versions, `byte` for `Transaction`, `uint` for `Block`. We should unify them.

**Do you have any solution you want to propose?**

Using `WriteVarInt()` and `ReadVarInt()` we can save 3 bytes in all blocks (currently is `uint` for store 0x00000000) 

Another option is use `byte` and if in the future we need to pass to `VarInt` is easy

**Where in software does this update applies to?**
- Consensus
- Ledger

**Comment by erikzhang** [comment]
We need the header size be fixed. I think 3 bytes is not a big problem.

**Comment by shargon** [comment]
The maybe we can use `byte` in all of them, now Block and Consensus is an integer.

**Comment by erikzhang** [comment]
If in the future we use `Version` as a flag, it is better to be an integer value.

**Comment by shargon** [comment]
A flag for what? as a byte we have 256 available changes, i think that this is too much, and if we need more we can start using `VarInt` backward compatible.

**Comment by erikzhang** [comment]
If it is used as a flag, we only have 8 bits. Each bit can represent a function.

**Comment by igormcoelho** [comment]
> If it is used as a flag, we only have 8 bits. Each bit can represent a function.

I like this idea for NeoVM version, it's in the same direction of the bit mask on NeoVM extensions proposal: https://github.com/neo-project/neo-vm/issues/176 (also proposed 4 bytes there, to have 31+x options).

In the versions here, what could possibly be the options on flags Erik? New Interops? This is very good to enable/disable features in a transparent way.

**Comment by igormcoelho** [comment]
Great discussion today @belane @shargon. So, we agree in keeping version 3 for the payloads? What component version does this Issue refers to?

**Comment by shargon** [comment]
If this is the expected behaviour we can close it

**Comment by igormcoelho** [comment]
> If this is the expected behaviour we can close it

Well, I think that's what we decided...... v3 for neo3.

But Erik's comments are reasonable, if we want the version to represent internal features. Problem is: which feature each component has?
Example: if we are referring to each Syscall as a feature, we would need several bits to represent every syscall, and the chance that we disable/enable any syscall is very small in the future. Better just evolve version number (to v4) on payloads and change what we want.

**Comment by shargon** [comment]
for me `byte` is enough too

**Comment by shargon** [comment]
So the agreement is change it or close it?

**Comment by lock9** [comment]
I think byte with value 3 is good.
