### ISSUE TITLE
Add 'mandatory' integration tests using neo-resilience

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1105]
**Summary**
We need an automated way to know if a PR is broken or not. We could integrate this check on GitHub.

**Do you have any solution you want to propose?**
Just like we have travis, we should run a test using the PR code in a private network to ensure it is working. 
Travis already takes 25 minutes to finish, if we could start this test after it is compiled (~5 minutes), we could use additional minutes to run the code in a private network to ensure it is working.

"In practice":
![image](https://user-images.githubusercontent.com/38396062/65298060-717e4000-db40-11e9-81ef-b9e9a14e10f5.png)
 

**Where in the software does this update applies to?**
- Other: Q.A.

**Comment by shargon** [comment]
I like it, but to be honest, only installing dotnet core spend 2.5 minutes, is possible to start with a build image with dotnetcore already installed?

**Comment by shargon** [comment]
miss click, sorry 😅

**Comment by shargon** [comment]
> Travis already takes 25 minutes to finish, if we could start this test after it is compiled

We can start in parallel

**Comment by lock9** [comment]
I will implement this in my repo, if it works, I'll send the config steps here
