### ISSUE TITLE
JSON's syscalls can't deal with NULL values

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1112]
**Describe the bug**

In Red4sec we are preparing a fuzzing process for different neo areas. We find a issue with null values.

**To Reproduce**
```csharp
using (var script = new ScriptBuilder())
            using (var engine = new ApplicationEngine(TriggerType.Application, null, null, 0, true))
            {
                script.EmitPush("{\"a\":1,\"b\":null}");
                script.EmitSysCall(InteropService.Neo_Json_Deserialize);
                script.EmitSysCall(InteropService.Neo_Json_Serialize);
                engine.LoadScript(script.ToArray());
                engine.Execute();
                var ret = engine.ResultStack.Peek().GetString();
            }
```

**Expected behavior**

The expected result should be `{"a":1,"b":null}`

**Screenshots**
![image](https://user-images.githubusercontent.com/3167973/65503994-63287f00-dec6-11e9-8118-0a8d19bf41b7.png)

Source Reference:
https://github.com/neo-project/neo/blob/0a4f7806eb41552c733beb2cfda5c59c12eb095b/neo/SmartContract/JsonSerializer.cs#L101

**Platform:**
 - Version [e.g. neo 3x]

**Additional context**
In addition, it should be possible to reverse a null value, to a null json value, and the VM will treat null values ​​as a byte [0], how will it be possible to distinguish between an empty byte array and a null?

**Comment by erikzhang** [comment]
Should we add new opcodes `PUSHNULL` and `ISNULL`?

**Comment by shargon** [comment]
I think that we can use ByteArray, but a special one, we have a null item.

https://github.com/neo-project/neo-vm/blob/6676592b667cd39c26f46af41d7484cd054e4da1/src/neo-vm/StackItem.cs#L13

Maybe we can check with `ReferenceEqual` on `PUSHNULL` and `ISNULL`?

**Comment by erikzhang** [comment]
How to distinguish between `null` and `byte[0]`?

**Comment by shargon** [comment]
```
var item=stack.Pop();
if (Object.ReferenceEquals(item ,StackItem.Null)
```

**Comment by erikzhang** [comment]
Please check #208

**Comment by igormcoelho** [comment]
> How to distinguish between null and byte[0]?

`new ByteArray(null)` could have a constructor that receives null and indicates this in a local flag.
