### ISSUE TITLE
Could we add `VMState` field in RPC getrawtransaction method result

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1114]
**Summary**
Even though we have added `VMState` in `TransactionState`, but it never used in outside, could we add this field in the RPC `getrawtransaction` method, which will be useful for contract invocation confirmation.

**Where in the software does this update applies to?**
- RPC (HTTP)
- SDK

**Comment by shargon** [comment]
We should do it

**Comment by Tommo-L** [comment]
Done by PR [1117](https://github.com/neo-project/neo/pull/1117)
