### ISSUE TITLE
Node getting stuck during sync

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1125]
**Describe the bug**
When I run neo, it often stops syncing before it reaches the current network height.
In my machine, it gets stuck for around 10 minutes, syncs more headers, and then get stuck again. 
It happens when syncing both headers or transactions.

Note: I found this bug in neo-cli but I believe the problem is in the neo library.

**To Reproduce**
1. Clear your chain files
2. Start neo-cli
3. Wait for it to sync, it eventually gets stuck

**Expected behavior**
It should sync the whole network without having to restart the application

**Screenshots**
![Anotação 2019-09-29 032833](https://user-images.githubusercontent.com/38396062/65827696-4e067400-e269-11e9-9ba1-5a82135e1366.png)

**Platform:**
 - OS: Windows 10 x64
 - Version: Neo 3 preview 1

**Comment by Tommo-L** [comment]
It works fine in my env:

node1
- OS: Windows10
- Version: Neo3 preview1

node2
- OS: Centos 7.0 
- Version: Neo3 preview 1

![image](https://user-images.githubusercontent.com/43396869/65830799-64eaac00-e2e5-11e9-8aec-5e8a97c01456.png)

**Comment by lock9** [comment]
Hi @Tommo-L, did you syncing it from block 0? Here it happens all the time

**Comment by Tommo-L** [comment]
😂, yes, start from block 0.  You try `show state` later, when it stuck.   When nodes sync blocks, it use batching process about 2000 blocks once.

**Comment by superboyiii** [comment]
It works well on mine. Take 21 minutes to the latest height.
[Sync_2019-09-30_143548.zip](https://github.com/neo-project/neo/files/3669173/Sync_2019-09-30_143548.zip)

**Comment by shargon** [comment]
what network did you use? @lock9

**Comment by lock9** [comment]
@shargon  I'm testing using both testnet and devnet. The problem appears in both of them 🤔

**Comment by lock9** [comment]
I tried several times today, and it didn't get stuck, I will try for two more days and if it doesn't get stuck I will close this issue.
