### ISSUE TITLE
dBFT 3.0 proposal: active backups strategy

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#1126]
**Summary**
We want to propose a dBFT 3.0 proposal, named Active Backups

**Do you have any solution you want to propose?**
We believe that dBFT 2.0 , with ensure block finality, is a major achievement for Neo and worldwide blockchain communities: Neo manages to be efficient, byzantine-proof, and to definitely preserve block finality. We want to extend this a little bit more.

Currently, dBFT 2.0 is strongly based on PBFT, where Speaker plays a very important role in algorithm. We want to make things even more efficient, and make the role of Speaker even more challenging. Right now, if speaker fails, we loose T seconds (T=2 x 15 = 30 seconds), at minimum. We want to be resilient to Speaker failures, not just with ChangeView protocol (that ensure liveness over infinite time), we want to do that in 15 seconds (MAXIMUM).

Active Backups proposal will allow up to `f+1` nodes to propose blocks simultaneously, coordinated in a backup time window starting from T/(f+1)... This means that, if we coordinate things efficiently, and `2f+1` nodes follow the protocol, we will likely having Speakers to have their blocks proposed every 15 seconds (now, perfect 15 seconds). But if Speaker is slow down by any reason, first backup will assume block proposal, and if it fails, second backup... the idea is to guarantee that block is finished every 15 seconds, regardless of primary failures.

Another interesting point of Active Backups proposal, is that it allows backups to actively participate on block proposal, and we want to extend that to random external p2p candidate nodes... meaning that, if you are a Candidate, and you are online, you have the chance to participate in any dBFT 3.0 consensus. By having this, we incentive people to keep good nodes up, 100% of the time, and while elected nodes can have temporary failures, we can have network p2p nodes replacing them, and keeping network stable. 

This is a major achievement for Neo, from a Governance perspective, where more people can actively participate on block generation (ensuring network block time flowing, regardless of primary failures), achieving a much more stable network.

We believe this proposal is divided into two proposals:
- Precise/Practical Byzantine Time Protocol (PBTP). We need to propose and design a protocol which is resilient to time changes on nodes clocks, up to few seconds (current limit goes up to minutes scale).
- Active Backups. This is the proposal where `f+1` elected nodes participate on every consensus block proposal. We will define a precise time scale where proposals begin (to avoid block collisions in early phases... meaning that, if all nodes are non-byzantine, usually only efficient speakers will keep blocks flowing).
- Active Backups for Candidate Nodes. This proposal allows external p2p nodes to eventually participate on consensus, due to primary failures, or regular opportunities. This is good to have third-party nodes operating on behalf of Neo network all the time, even if they are not 100% necessary. The previous Active Backups proposal guarantees that, even if a non-trusted backup is on stage, it won't be able to delay block generation (as long as most active nodes are non-byzantine). This is a good, and strongly enough guarantee, to incentive people to run nodes and to hope for adoption in mainnet.

Governance still depends on Neo holders to elect stable/official nodes, and node count. Neo holders could also determine the slots where "community nodes" or "p2p nodes" can participate on consensus.

**Where in the software does this update applies to?**
- Consensus
- Ledger
- Governance

**Comment by shargon** [comment]
I proposed something like this one year ago.
But with time we thought that backups only can help when is not primary. On primary they can produce forks.

**Comment by igormcoelho** [comment]
Exactly, I remember you talking something like this on Chile hackathon, for one backup to propose block simultaneously. At that time we couldnt deal with forks efficiently,thats true...
Now we are extending this even more, to 'f+1' nodes, so fork probability increases even more! Yet, we were working on the mathematics, Vitor and I,and we believe it's feasible, with an extra phase,to prevent forks. We took some time to model it,what we are calling a "Cancel Phase".
We intend to model it, and perhaps simulate it quickly on libbft for practical feasibility (lets do it @rodoufu ), and if it works, we implement it on Neo core.
