### ISSUE TITLE
Attach source to nuget packages

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1131]
**Summary**
When an exception occurs in neo-cli or neo-gui, we can't see the real exception, because it usually happens at neo library level. We should be able to see the exact error when it happens.

**Do you have any solution you want to propose?**
*I'm not sure*, but I think it is possible to associate the source code to a nuget package, so when an exception occurs, we know the line that caused the exception.

**Where in the software does this update applies to?**
- Other: House-keeping

**Comment by erikzhang** [comment]
Solved by #1267
