### ISSUE TITLE
Make changelog update mandatory on PR submission

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1135]
**Summary**
We need to inform community developers what has changed in our code as we add and change features. I got this idea from neo-python repository.

**Do you have any solution you want to propose?**
Developers should add an entry to the `changelog` file to submit a valid PR.
Changes are grouped by month and by release (`preview2` should have its own `changelog` from `preview1`)

- [ ] Update PR template
- [ ] Enforce this rule using bot or travis check

**Where in the software does this update applies to?**
- Other: House-keeping

**Comment by shargon** [comment]
Good idea

**Comment by shargon** [comment]
Where is the changelog? xD

**Comment by lock9** [comment]
@shargon  please check #1137, but first we need to merge #1121

**Comment by lock9** [comment]
@neo-project/core Should this be done? Should I close this? Can you please vote? (👍 / 👎)
Thanks.
