### ISSUE TITLE
more APIs for smart contract

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#114]
We need more APIs for smart contract:

- [x] Neo.Runtime.GetTime
Use this API to get the block timestamp that is being persisted, or latest block timestamp + 15s.

- [x] Neo.Runtime.Serialize, Neo.Runtime.Deserialize
Serialize the top item on the evaluation stack into a byte array, or deserialize a byte array into a stack item. This is very helpful for storing items into contract storages.

- [x] Neo.Header.GetIndex
Add missing API `Neo.Header.GetIndex` for getting index of a header/block.

- [x] Neo.Transaction.GetUnspentCoins
Through this API, we can get all unspent coins from a transaction.

**Comment by localhuman** [comment]
Could we also add:

4. Neo.TransactionOutput.ContainsUnspent
- Through this API, we can determine if a Transaction Output contains unspent coins ( uses https://github.com/neo-project/neo/blob/master/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.cs#L166)

**Comment by erikzhang** [comment]
@localhuman What about `Neo.Transaction.GetUnspentCoins`? Is it better?

**Comment by localhuman** [comment]
That would be perfect 👍

**Comment by localhuman** [comment]
There is also no current way to get the height/Index of a `Block` or `Header`.  Shall we add `Neo.Header.GetIndex`?

**Comment by erikzhang** [comment]
> There is also no current way to get the height/Index of a `Block` or `Header`. Shall we add `Neo.Header.GetIndex`?

It's very strange why it's not there.

**Comment by saltyskip** [comment]
Is there a plan for Get Unspent Coins to be added as an RPC call? Currently light wallets are relying on the COZ API https://github.com/CityOfZion/neon-wallet-db to serve this data.

I think it would be more efficient for the UTXO's to be added to either the getAccountState or its own seperate RPC. This would make light wallet reliability much more consistent. Thoughts?

**Comment by localhuman** [comment]
@saltyskip This issue is for additional smart contract API, please open in a separate issue.
