### ISSUE TITLE
Mempool Reverification Model (MRM): Optimizing our nodes

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1140]
**Summary**
Currently, mempool reverification model for NEO3 is not completely finished.

Imagine the scenario that you have 5 GAS in your address:
* You send 5 valid txs (`tx_1`, `...`, `tx_2`) that uses 1 GAS each (`sysfees` + `netfees`)
* all 5 `txs` enter in the mempool
* `tx_1` enter in the next block

*Current implementation of NEO3:*
1. all 4 remaining `txs` are revalidated and kept on the mempool 

This may lead nodes to keep, in their mempool, `txs` that do not have GAS to be anymore spent. Thus, `txs` that can not pay its sysfee and netfees.

Edited:
This description has been updated since currently we move all `txs` to unverified and slowly `reverify` in batches.

*Possibilities:*

2. `tx_ 1` uses 4 GAS in its Application (transferring to other address), thus all 4 remaining `txs` shall be discarded
3. `tx_ 1` uses 3 GAS in its Application (transferring to other address), thus, 1 out of 4 of the  remaining `txs` shall be discarded

**Do you have any solution you want to propose?**
With @igormcoelho, we were addressing this design https://github.com/neo-project/specification/pull/3 some months ago.

* add a new field to `payable` transactions, in which it says the limit of `GAS` it can spend on Application
* with such field, we would design a mechanism that tracks GAS pre-balance of `senders` in the current mempool

**Where in the software does this update applies to?**
- MemPool
- Ledger
- Transaction

**Comment by lock9** [comment]
Hi @vncoelho, I think we should wait for at least 2 approvals before adding something to the neo 3 milestone. If everyone start adding or removing issues to Neo 3 milestone we are surely going into conflicts.
I will leave this added to the milestone, but next time please wait for more approvals.

**Comment by vncoelho** [comment]
I see, @lock9, makes sense. I added this one because the current implementation for mempool is not completed. Thus, in any case, we need to pass though this.

**Comment by vncoelho** [comment]
@igormcoelho, how are the current possibilities for an invocation to spend GAS of other address, if the Witness is passed as a parameter of the call?

@lock9, this is not really related to `network-policy`. It is a cached mechanism for mempool to reverify  transactions after block persists (ledger) and also a new field to transactions, which would guide the limit of GAS to be spent.

**Comment by lock9** [comment]
@vncoelho  this is related to how the network will process the transactions, right? For me, this is a network policy issue. 
Note that the network policy does not relate only to the native network contract, it also refers to the way node process transactions, how we prioritize and revalidate them in the memory pool seems to be a network policy for me

**Comment by vncoelho** [comment]
Makes sense, @lock9, however, just be aware that the logic does not change. It just would just add  new field to payable txs themselves.

**Comment by lock9** [comment]
Sorry, @vncoelho  I had forgotten to add the ledger tag too.
Do you think it is an enhancement or a new feature?

**Comment by vncoelho** [comment]
I think it is a basic functionality, but it is a feature because it would need a new field on tx....ahauaha

The current mempool reverification is not yet fully completed, thus, it is already expected to be part of the development.

**Comment by lock9** [comment]
Maybe it only relates to the ledger, if this is the default way and doesn't change

**Comment by vncoelho** [comment]
The only point would be an extra field of allowance of GAS, which is really a negative point.

However, we still did not see another way to quick revalidate. 
In long term, this might also be good for users, which could sign different txs in parallel if limits are respected. 

Currently, we can do that, but it costs more for our revalidation, which is a critical thing, because all seed nodes do that all the time.
In addition, this is a possibility for us that have block dBFT and block finality. Other paragdims would not have such lucky.

In this, in favor of scalability, I keep this as a priority.

**Comment by shargon** [comment]
Completely necessary

**Comment by vncoelho** [comment]
@shargon, I am going to start a draft of this PR as soon as possible.
However, if you fell that you are with the design in your mind, fell free to open it when you can.

**Comment by vncoelho** [comment]
@shargon @igormcoelho, should the field on the transaction be an independent one or an `TransactionAttribute` ?

**Comment by vncoelho** [comment]
@erikzhang, I started the implementation as a new field, such as `Sender`, `NetworkFee`, `SystemFee`, etc...
The field was:

```cs
        /// <summary>
        /// Max allowed amount of GAS that the transaction is allowing to be transfered from Sender
        /// If null, not passed, no parallel transactions will be accepted on the mempool since all remaining GAS would be allowed
        /// </summary>
        public long MaxTransferableGAS;
```

However, as a field like this I am finding it hard to make it optional.
The idea of being optional is good, because it allows compability with wallet, since they do not need to add an extra field if they do not want.

* However, if they do so, during Transaction Deserialization we would set `MaxTransferableGAS = Sender_Balance - (SystemFee + NetworkFee)`. By doing so, the `Sender` parallel transaction will be rejected by the mempool.

Maybe the best way is like a `TransactionAttribute`

**Comment by erikzhang** [comment]
I'm not sure it is needed.

**Comment by vncoelho** [comment]
It would be good if we could manage without this additional field.

What is your idea, @erikzhang? How could we quickly `Reverify` the mempool without waiting for all transactions to be persistance and `balances` updated?

PS: However, this additional field will be optional, as described. Just for those that want to the `Sender` to send multiple transactions.

**Comment by vncoelho** [comment]
Another pending question is:

@igormcoelho @shargon @erikzhang, will it be possible for a transaction call to transfer `GAS` of another address? Let`s say that a cosigner or an witness is attached to the transaction?
If that is the case we are going to reach an even more complex scenario.

**Comment by vncoelho** [comment]
@erikzhang, I just talked to @igormcoelho and he explained me that currently only `Sender` can spend GAS during an execution of a transaction. 

In this sense, this proposed solution is quite suitable and should be implemented, it looks like to be a good path for scalability.

Since it is only the `Sender` that may spend GAS during the `Application` the solution will not be so complex and the gains are honorable. Imagine a mempool with 50k,30k or more txs?

**Comment by erikzhang** [comment]
I think a cosigner can send GAS also.

**Comment by vncoelho** [comment]
@erikzhang, perhaps send for systemfee and netfee, right? Igor mentioned that not spent cosigners GAS during Application.

**Comment by doubiliu** [comment]
@vncoelho I think "payable" attribute is very useful attribute. Currently we move all txs to unverified and slowly reverify after block persisted.We @eryeer  have done a test that this process takes up 40% of the entire block persist process.If we add  "payable" attribute,we will not reverify txs,this will save a lot of time. Tps will increase significantly.

**Comment by vncoelho** [comment]
It is great to hear that @doubiliu fro you and @eryeer, as well as that you are already investigating that.
Nice job.

After we merge #1183 it might be good time to push this one.

@doubiliu, I believe that we can do the "payable" attribute as optional, thus, light wallets/clients implementation do not need necessarily to change.

When the "payable" is `null` we can block all parallel transactions of that `sender`, since he may spend all GAS during `execution`.
On the other hand, for those interested in using that flag "payable" and define a `limitExecutionGas`, mempool would accept parallel transactions until `balance` is reached.

**Comment by vncoelho** [comment]
@doubiliu @Qiao-Jin @eryeer, can you help implementing this field "payable" (`limitExecutionGas`)?
Otherwise, I may try to start the PR.

**Comment by eryeer** [comment]
@vncoelho  Sure. We can help implementing this.

**Comment by eryeer** [comment]
I think we can discuss the detail implementation scheme before implement this. Maybe there are some detail issue we need to take care of, such as how to solve cosigner's transfer.

**Comment by vncoelho** [comment]
@eryeer, last time I talked to @igormcoelho he mentioned that `cosigners` were not allowed to spend GAS during `Application`.
Maybe let's double check.

**Comment by eryeer** [comment]
Is there such a constraint? I'm not quite sure about this, where is this GAS spending limitation?
In addition, after our tests, `Reverify` is a lightweight call. Even under high-pressure tests, `Reverify` of transactions after block persistence is not very time-consuming. 😂
