### ISSUE TITLE
Add NEO2-style contract metadata to NEO3 ContractManifest

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#1143]
**Summary**
In NEO2 all contracts had the following (optional) fields as part of `ContractState`:
* Name
* CodeVersion
* Author
* Email
* Description

NEO3 has removed most fields of `ContractState` and added the more comprehensive `ContractManifest` object. However, the manifest does not seem to contain or store any of the above fields.

**Do you have any solution you want to propose?**

Add Name, CodeVersion, Author, Email and Description to the `ContractManifest` class so that explorers/dApp trackers can obtain human-readable context for the contracts deployed on NEO3.

**Where in the software does this update applies to?**
- Other: Core/Storage

**Comment by shargon** [comment]
Maybe we can add some specific dynamic data for the project in manifest?

**Comment by doubiliu** [comment]
Interesting.This can help user fully understand the intention of contract.I think we should keep these attributes in NEO3

**Comment by shargon** [comment]
Ready to implement?
