### ISSUE TITLE
Contract sponsored nodes

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#1147]
**Summary**
This is an "ingredient" of governance incentive strategy for projects to host their own participative consensus nodes. With this, nodes could whitelist contracts for free tx execution.

**Do you have any solution you want to propose?**
Transaction could have an optional field on Sender, that could inform that an specific contract will be executed, and it will execute for free as long as it is whitelisted by speaker node.

Idea is simple: we want more nodes on Neo; nodes require maintainance; projects can do such thing and get free tx for their projects.

If a project is big enough, or visionary enough, it will host a CN, and whitelist its contract for this CN.
The whole network will know that this contract is whitelisted on native policy (this operation may cost a little bit, to avoid useless registrations). When CN proposes a block, it wont receive network fee for this tx (since there's none), so other CN may prefer to select other tx on their turn, if its not whitelisted there. This may cause free tx to take more time to be processed, but this the "price" for being free.

Nodes could vote a maximum sponsorship gas amount per tx, allowing for example, for basic nep5 to execute for free (on sponsored nodes only).
IMPORTANT: this will work very well with dBFT 3 Active Backups proposal, as this will allow good nodes to collaborate on CN,even without voting tenure.

Simple: create a dapp; host a node; stake Neo.to be candidate node; work well to "push" your customers tx when an opportunity arises (dBFT 3 backup round).

Community gets good operating nodes; clients get cheap operations.

**Where in the software does this update applies to?**
- Transaction
- Consensus
- Network Policy

**Comment by igormcoelho** [comment]
Any thoughts @canesin?

**Comment by canesin** [comment]
Could you do a flow diagram of this ? I am a bit confused on the possible feedbacks on this.

**Comment by igormcoelho** [comment]
Ok @canesin, this is the proposal diagram.
Part 1: interested people will get some node ellected (or participate via some other "dbft 3" mechanism)
![image](https://user-images.githubusercontent.com/290989/66977099-e3cc3c80-f07a-11e9-80de-7f52ade02cec.png)

Part 2: since elected node has proposed a valid Policy to whitelist specific contract (up to X GAS), now users may benefit of this
![image](https://user-images.githubusercontent.com/290989/66977129-03fbfb80-f07b-11e9-92dc-d58510bc9a77.png)

**Analysis**
What happens is: network benefits from interested nodes being run and maintained. These nodes may benefit sponsored dapp applications, by allowing zero network fee and zero system fee (up to X GAS, limited by protocol, but also adaptive in time).  Since network fee is zero, other CN won't be interested in putting that into a block (very low priority), but they can eventually do. At least the sponsored node will be interested in proposing this free tx, on its own round, and if that takes too much, tx will just expire. **Network benefits from more nodes; and dapps benefit from free execution (but slower than usual).**

If contract is allowing spam; this will damage network; NEO holders won't keep malfunction node (it will be downvoted and replaced.. or most likely, "contract sponsorship" revoked).
