### ISSUE TITLE
change TX network/system fee to be unsigned

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1151]
**Summary**
I'm going through the new Transaction implementation and noticed this construct for network_fee and system_fee
https://github.com/neo-project/neo/blob/982e69090f27c1415872536ce39aea22f0873467/neo/Network/P2P/Payloads/Transaction.cs#L93-L94

If they're not allowed to be negative, should we then change the type (see below) to `ulong` instead (same for network fee)?
https://github.com/neo-project/neo/blob/982e69090f27c1415872536ce39aea22f0873467/neo/Network/P2P/Payloads/Transaction.cs#L35

**Do you have any solution you want to propose?**
change network and system fee to be `ulong`. 

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by shargon** [comment]
i think that it could be better, but it require to change the gas from ApplicationEngine to ulong too

**Comment by igormcoelho** [comment]
Some time ago I was planning to reuse negatives here to allow fraction gas sysfees :joy: this was a plan if sysfees were integral (not satoshis...). But if they are satoshis already,better to ulong them,sure.

**Comment by doubiliu** [comment]
Could you describe the benefits and usage scenarios of such modifications? @ixje

**Comment by ixje** [comment]
@doubiliu it's cleaner and less chance of missing a signed related security issue. You don't need these kind of checks anymore because they are implicitly enforced by the type
https://github.com/neo-project/neo/blob/982e69090f27c1415872536ce39aea22f0873467/neo/Network/P2P/Payloads/Transaction.cs#L94
https://github.com/neo-project/neo/blob/982e69090f27c1415872536ce39aea22f0873467/neo/Network/P2P/Payloads/Transaction.cs#L97-L98

**Comment by doubiliu** [comment]
I have a question : Eg, ulong data1=1,and data1-(ulong)2,it will overflow and not throw exception.So how we check this?And if it appear in  a similar situation of fee(SystemFee、NetworkFee),how we check?

**Comment by ixje** [comment]
@doubiliu You're right. I made a wrong assumption about the overflow behaviour (not a C# guy here).
