### ISSUE TITLE
Block with 0 transactions?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1152]
Should it be possible to deserialize a `Block` containing 0 transactions, or should that be a format error? 

Currently, you only have to make sure a block has `ConsensusData`
https://github.com/neo-project/neo/blob/982e69090f27c1415872536ce39aea22f0873467/neo/Network/P2P/Payloads/Block.cs#L55-L59

**Comment by shargon** [comment]
if you take a look

https://github.com/neo-project/neo/blob/982e69090f27c1415872536ce39aea22f0873467/neo/Network/P2P/Payloads/Block.cs#L61

This number is txCount+1, not the transaction count, so yes, it's possible

**Comment by ixje** [comment]
@shargon that's exactly what I noticed. It is possible, now my question is if this is correct or if we should protect against it? Is there ever a use case where a Block with 0 transactions is valid?

**Comment by shargon** [comment]
Yes a block with 0 transaction is valid, because now we don't have the minner transaction, so is valid.

**Comment by ixje** [comment]
ok, then I'll leave it with that. Thanks!
