### ISSUE TITLE
Calling ToLower() method two times

### ISSUE THREAD

**Issue by janus** [neo-project/neo#1153]
```
string resp = Encoding.ASCII.GetString(buffer, 0, length).ToLower();
                        if (resp.Contains("upnp:rootdevice"))
                        {
                            resp = resp.Substring(resp.ToLower().IndexOf("location:") + 9);
                            resp = resp.Substring(0, resp.IndexOf("\r")).Trim();
                            if (!string.IsNullOrEmpty(_serviceUrl = GetServiceUrl(resp)))
                            {
                                return true;
                            }
```
The above code is from UPnP file, resp is made lowercase during its creation. However, inside the first Substring call resp is made to be lowercase again. This is not bug in the real sense but it would affect speed if resp is a huge value

**Comment by shargon** [comment]
Yes, you are agree, we will fix it.

**Comment by janus** [comment]
Feel like hanging out with devs if there is a forum

**Comment by shargon** [comment]
You can vote for a forum here https://github.com/neo-project/neo/issues/735

Meanwhile you can use your discord to keep in touch

https://discord.io/neo

**Comment by vncoelho** [comment]
Thanks for the investigation and insight, @janus.
