### ISSUE TITLE
Should we move RPC to be a plugin?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1159]
**Summary**
RPC is not mandatory for the core functionality, however, it is embedded in the official neo library.
If this is not core functionality, shouldn't it be moved to a plugin?
Or, should be have a more complete version with the plugins embedded and a different one for consensus? 

**Do you have any solution you want to propose?**
In my particular opinion, I think we have too many things as plugins, I feel like the releases are focused in consensus nodes, while this is not the most used scenario. 
I think we could have a 'complete release' with plugins included ('Ubuntu') and a reduced one, for consensus ('Alpine Linux').

**Where in the software does this update applies to?**
- Other: GitHub / Releases

**Comment by doubiliu** [comment]
Good idea.I like it.In Oracle design,I want to achieve "Different Group,Different Plugin,and Different Logic"

**Comment by Tommo-L** [comment]
I see there a lot of plugins dependent on RPC, like RpcWallets, RpcNep5Tracker and RpcSecurity. Should we integrated all in one?

**Comment by vncoelho** [comment]
It looks good to me, @Tommo-L!

**Comment by shargon** [comment]
How will be the procedure for a new plugin to interact with RPC?

**Comment by lock9** [comment]
@shargon  we keep the plugin interface. The problem will be a plugin depending on another plugin, because we need the basic RPC features stored somewhere we can reuse.

**Comment by shargon** [comment]
@lock9 precisely this is my concern

**Comment by shargon** [comment]
@lock9 I think that it's on design until we decide how to solve this issue

**Comment by lock9** [comment]
@shargon  Erik will migrate the RPC first so we can see what he expects. For him, it is ok to a plugin to depend on another plugin, so the solution will be a little different than what I expected.
