### ISSUE TITLE
Improve Signature Verification Performance

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#116]
Rewrite the algorithm of signature verification to replace the default implementation of the system. This will improve the performance of signature verification.

**Comment by shargon** [comment]
But i think that the default implementation can't generate a Public Key from your random private key. This implementation, generate both, private and public key.

**Comment by shargon** [comment]
```

**Comment by shargon** [comment]
In fact, in the last release with Net47, use the native version
![image](https://user-images.githubusercontent.com/3167973/33723610-6866732c-db6d-11e7-8859-4d0216903882.png)

This issue still open?

**Comment by lock9** [comment]
@neo-project/core  hello friends.
Can we close this? If not, what are the next steps? Is this issue blocked?
Thanks.

**Comment by shargon** [comment]
I think that we can close it, @erikzhang reopen it if is necessary
