### ISSUE TITLE
Improve Gas OnPersist in case of VM behavior change that affects payable GAS transactions

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1161]
**Summary**
Talking to @vang1ong7ang, during Ethereum Devcon, he suggested that GAS balance might be negative in case we have VM changes that after GAS transfers.

In fact, it looks like that it mainly affects `System+NetworkFee `, which could be redistributed. However, those GAS may not exist in case that the VM behavior had change for a specific contract.

https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/SmartContract/Native/Tokens/GasToken.cs#L37-L53

**Do you have any solution you want to propose?**

The solution is not clear yet, but maybe we could still fail that transaction and avoid its GAS redistribution. That would surely cause an avalanche effect on future transactions, however, at least, the protocol would be followed.

**Where in the software does this update applies to?**
- Ledger
- Network Policy
- VM

**Comment by doubiliu** [comment]
Historical issues 😭
