### ISSUE TITLE
Additional VM OpCodes

### ISSUE THREAD

**Issue by localhuman** [neo-project/neo#117]
For programming Smart Contracts, it would be beneficial to have the following OpCodes:

**ARRAY_REVERSE**
- Reverses the current array on the stack

**ARRAY_APPEND**
- Adds an item to the end of an array

**Comment by shargon** [comment]
ARRAY_APPEND must grow the array (length +1) or how is defined the last position?

**Comment by localhuman** [comment]
🎉
