### ISSUE TITLE
Why does DataCache.Add() not check the real backend?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1173]
The `DataCache` class has methods like `Add`, `Delete`,  `Find` etc. 
`Delete()`, `Find`, `TryGet` all do the following steps
1. check internal cache
2. if not found internally -> check real backend

`Add()` does not check the real backend. Why?

https://github.com/neo-project/neo/blob/4112df22fa5c5080dc0c39469e298db7fa4f85ef/neo/IO/Caching/DataCache.cs#L46-L59

`Add()` throws an exception (see line 51) if we try to add something that already exists in the cache. It is a design choice to not allow overwriting values, that's fine. However, if it does not find it in the cache then it happily adds it to the cache and a call to `commit()` will overwrite the value in the real backend. This is inconsistent behaviour. I think there should be 1 of 2 options

1. `Add()` always allows overriding data. This means removing the exception.
2. `Add()` never allows overriding data. This means adding logic to check if a value exists in the real backend before adding it to the internal cache and throwing an exception if it exists.

Now depending if `TryGet()` or `GetAndChange()` is called before an `Add()` it will throw an exception or not.

**Comment by erikzhang** [comment]
I think option 2 is good.

**Comment by vncoelho** [comment]
@ixje, nice findings!
I just had time to understand it now after dedicating some time to #1318.

I think that I agree with option 2. Which one do you personally prefer?

**Comment by ixje** [comment]
I PR'ed for option 2. 

Personally I made everything writable in `neo3-python` unless explicitly setting a `read_only` param to `True`. This is because I wanted to avoid the problem I described in https://github.com/neo-project/neo/issues/1186 and it allowed me to remove the (to me personally) confusing named `GetAndChange`.
