### ISSUE TITLE
Discrepancies between neo2 and neo3

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1181]
While doing https://github.com/neo-project/neo-devpack-dotnet/pull/106 I found some discrepancies between syscalls

### 1 - Migrate vs Update

In neo2 this syscall return the Interop of the new contract, in neo 3 don't, maybe is good to return it

https://github.com/neo-project/neo/blob/f147946b9c3e7229f90e40e7dbc6a14c84d88fc5/neo/SmartContract/NeoService.cs#L754

https://github.com/neo-project/neo-devpack-dotnet/pull/106/files#diff-6d7ce32ea1b68e3052da2fff01f9f8ecL20-R27

### 2 - Crypto

The order of the arguments are different between Neo 2 and neo 3

in neo2 https://github.com/neo-project/neo-devpack-dotnet/pull/106/files#diff-fb0b3efccf8528424965b0c98c8b5486L5-L18 is signature/pubHash
in neo 3 https://github.com/neo-project/neo-devpack-dotnet/pull/106/files#diff-59bb4ef3dd2a2cdb820b29d2c55a8c04R6 is pubHash/signature

### 3 - Namespace mismatch

In neo3 `Call` and `Destroy` are in `System` but `Create` and `Update` in `Neo`
https://github.com/neo-project/neo-devpack-dotnet/pull/106/files#diff-6d7ce32ea1b68e3052da2fff01f9f8ecR30

The same with `System.Crypto.Verify` all are under `Neo` except this one

https://github.com/neo-project/neo-devpack-dotnet/pull/106/files/d999c8e4a32aaa6039f244a8fd8268b76e0a7a0b#r335384816

**Comment by erikzhang** [comment]
> In neo2 this syscall return the Interop of the new contract, in neo 3 don't, maybe is good to return it

There is no SYSCALL accepts this interface as parameter in NEO3. So we don't need to return it.

> The order of the arguments are different between Neo 2 and neo 3

I think the order are the same. In NEO2, `VerifySignature` is an OpCode, and parameters are pushed onto the stack from left to right. In NEO3, it is an SYSCALL, and parameters are pushed onto the stack from right to left.
