### ISSUE TITLE
Shall we move `header_index` to Snapshot?

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1182]
I think that it's not good that we have a list in memory with all the block hashes https://github.com/neo-project/neo/blob/f147946b9c3e7229f90e40e7dbc6a14c84d88fc5/neo/Ledger/Blockchain.cs#L119

I think that this can be more optimal if we store it on disk, in addition, it would help with decoupling `Blockchain.Singleton` from the` InteropServices` something that favors the unit testing and I also believe that it follows the right way, extract all the information from the `Snapshot` blockchain.

My proposal:

- Move `GetBlockHash` from `Blockchain` to `Snapshot`

**Comment by erikzhang** [comment]
The hashes of the headers do not take up too much memory, I think there is no problem.

**Comment by lock9** [comment]
Hi @erikzhang, what do you think now that we are going to have memory storage? I think that it would be good to have this encapsulated with other blockchain persistence logic. Like @shargon mentioned, it will make it easier for us to decouple the Blockchain class.
