### ISSUE TITLE
Cross platform development - configure Visual Studio for Mac

### ISSUE THREAD

**Issue by rywem** [neo-project/neo#119]
Configure the project to be multi-platform compatible.

**Comment by shargon** [comment]
I don't have mac, but is not compatible now?
https://visualstudio.microsoft.com/es/vs/mac

**Comment by lock9** [comment]
Done, here is the URL:
https://github.com/simplitech/neo-macos-smart-contract-template

It is a template for VS Studio for Mac. It includes a copy of the compiler, so this is all you need.

**Comment by shargon** [comment]
@rywem  I close the issue, if you have any problem, please reopen it
