### ISSUE TITLE
Confusion about Neo.Json.Serialize

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1191]
In InteropService, there are two SYSCALLs about JSON, `Neo.Json.Serialize` and `Neo.Json.Deserialize`.

`Neo.Json.Serialize` converts `StackItem`s to JSON objects. Everything looks great, the only problem is how to convert `ByteArray`.

We know in NeoVM, there is no differece between byte array and string. They are both stored in a `ByteArray`. Currently we use `ByteArray.GetString()`, and convert it to a `JString`. That means we have the following conversion:

```
"test" => "test"
0x1234 => "\u00124"
```

The first conversion is what we need, but we prefer the second one to be:

```
0x1234 => "1234"
```

If we use `ByteArray.GetByteArray()` and then use `ToHexString()`, we get the following conversion:

```
"test" => "74657374"
0x1234 => "1234"
```

This time, we are pleased with the second conversion, but the first conversion for `test` is not good.

We need to decide which way to use.

**Option 1: `ByteArray.GetString()`**
**Option 2: `ByteArray.GetByteArray()` and then `ToHexString()`**
**Option 3: Create new JSON APIs. Such as `Neo.Json.NewJArray`, `Neo.Json.AddItem`, `Neo.Json.NewJObject`, `Neo.Json.AddProperty`.**

**Comment by ixje** [comment]
I prefer option 2
```
"test" => "74657374"
0x1234 => "1234"
```
My reasoning is that byte arrays should be represented as byte arrays, not with some strange encoding in front of it. If the byte array data happens to be decodable to a human readable strings that's an extra and up to the user.

**Comment by lock9** [comment]
I'm in favor of option 2 too.

**Comment by shargon** [comment]
I prefer option 2 too

**Comment by igormcoelho** [comment]
Looks like option 2 is better indeed, since string will be representing a bytearray as an explicit hexstring... it takes more space, but it's much more readable. And we cannot affort to have crazy chars inside json anyway. Good idea.

**Comment by shargon** [comment]
Usually in json is used base64 instead of Hex, did you consider the use of base64?

**Comment by erikzhang** [comment]
Base64 has a higher compression ratio. I like it.

**Comment by ixje** [comment]
> Base64 has a higher compression ratio. I like it.

Base64 adds overhead both on processing and size ([ref](https://stackoverflow.com/questions/1443158/binary-data-in-json-string-something-better-than-base64))

> An obvious method to escape binary data is to use Base64. However, Base64 has a high processing overhead. Also it expands 3 bytes into 4 characters which leads to an increased data size by around 33%.

```python
In [1]: import base64

In [2]: array = b'\x11'*64

In [3]: array
Out[3]: b'\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11'

In [4]: base64.b64encode(array)
Out[5]: b'EREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREQ=='

In [5]: len(base64.b64encode(array))
Out[5]: 88

In [6]: len(array)
Out[6]: 64
```

**Comment by erikzhang** [comment]
Base64 encodes 6bit into one char. Hex encodes 4 bits into one char.

**Comment by ixje** [comment]
oh right forgot the output has to be a string, still early morning 😅 
base64 sounds good as well
