### ISSUE TITLE
Should we make code documentation mandatory?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#1196]
**Summary**
Some parts of the code are a little obscure for 'new' developers. It would be good to have documentation added to the code using the "default" documentation syntax. This will also improve the usage of neo as a library.

**Do you have any solution you want to propose?**
Maybe we should demand developers to document new methods using "///". This documentation is very useful because it can be seen inside VS, when we are developing (inside the auto-complete help).
Example, after I type "///", VS will automatically generate this:
```CSharp
/// <summary>
/// This is a documentation sample
/// </summary>
/// <param name="w"></param>
/// <returns></returns>
private static int BitLen(int w) 
{
...
```
Result:
![image](https://user-images.githubusercontent.com/38396062/67693867-2e09c380-f981-11e9-9e68-af1e6e9bf174.png)

**Where in the software does this update applies to?**
- Other: Documentation, UX

**Comment by shargon** [comment]
Yes, please
