### ISSUE TITLE
Auto-reconnect seed node when all seed nodes crash

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1198]
**Summary**
with NEO2.x network, all consensus nodes communicate with each other with seed nodes, in the worst case, all seed nodes crash, this would happen in a very low possibility, then all seed nodes loss connection with consensus nodes, when they are brought back online again, they can not reconnect to the consensus nodes, because consensus nodes can't build a new connection with the seed nodes.
To rebuild the connection, it will requires all consensus nodes to restart.

Reproduction steps:
1. prepare 4 consensus nodes.
2. prepare 2 seed nodes.
3. start seed nodes
4. start 4 consensus nodes.
5. start two normal neo-cli clients.
6. shut down all seed nodes.
7. start seed nodes again.

![屏幕快照 2019-10-29 下午7 04 12](https://user-images.githubusercontent.com/34291844/67761777-f1bc8d00-fa7e-11e9-9d03-d2b91fbc2588.png)

**Do you have any solution you want to propose?**
We should add a policy to auto reconnect to the seed nodes when they are all down and back again, and then there is no need to restart all consensus nodes.

**Where in the software does this update applies to?**
- Network Policy
- P2P (TCP)

**Comment by Tommo-L** [comment]
how a this solution: A node can maintain a connected peers file. When restart again, it can try to connect seed nodes, and also the peers in the file.

**Comment by ShawnYun** [comment]
Maybe we can close it.
