### ISSUE TITLE
Dependency of neo and neo-vm isn't compatble on master branch. (.NetStandard 2.0 & 2.1)

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1200]
**Describe the bug**
Dependency of neo, neo-vm and neo-cli isn't compatble on master branch. (.NetStandard 2.0 & 2.1)

**To Reproduce**
1. git clone neo project and neo-vm project.
2. make neo quote neo-vm & build.
3. make neo-cli quote neo & build.

**Expected behavior**
Incompatible error (NU1201, NETSDK1405)

**Screenshots**
![image](https://user-images.githubusercontent.com/38493437/68196634-d4923c00-fff3-11e9-8a64-f84c8dee6126.png)

**Platform:**
 - OS: [Windows 10 x64]
 - Version [The latest master branch]

**Comment by erikzhang** [comment]
We do not guarantee that the master branches of neo and neo-vm are compatible. Please use nuget.
