### ISSUE TITLE
Avoid adding Peers to both connected/unconnected peers

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1209]
**Summary**
PR https://github.com/neo-project/neo/pull/1160 improved the filter for unconnected peers. However, we are filtering it on the `AddPeers` event.

In principle, they should not be added to both lists are the same time: `ConnectedPeers` and `UnconnectedPeers`

**Do you have any solution you want to propose?**
We should improve the mechanism that adds the `Peers` and check both lists before adding instead of filtering it later.

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by vncoelho** [comment]
@Tommo-L, take a look here, it was our discussion.
I think it is still important a take a further look into that.

**Comment by Tommo-L** [comment]
It's true, how about adding a function in `Peer`, like `FilterNeverConnectedPeers`?

```csharp
protected void FilterNeverConnectedPeers(IEnumerable<IPEndPoint> peers)
{
    return peers.Where(p => !ConnectedPeers.Keys.Contains(p) && !UnconnectedPeers.Contains(p) && !ConnectingPeers.Contains(p));
}
```

**Comment by vncoelho** [comment]
I will check @Tommo-L, ahueahuea interesting name `FilterNeverConnectedPeers`.

Do you know if both are happening:
1. A node is already on `ConnectedPeers` and it is added to `UnconnectedPeers`
2. A node is already on `UnconnectedPeers` and it is added to `ConnectedPeers`, it should be removed from `UnconnectedPeers`

**Comment by vncoelho** [comment]
@Tommo-L, I double checked.

It looks like that the only way `UnconnectedPeers` is added is here:

```cs
ImmutableInterlocked.Update(ref UnconnectedPeers, p => p.Union(peers));
```

In this sense, the fix of PR #1160 completely solved the problem.
Congratulations and sorry for the delay in understanding the flow.

**Comment by vncoelho** [comment]
I just checked and it is updated here as well:
```cs
        private void OnTimer()
        {
            if (ConnectedPeers.Count >= MinDesiredConnections) return;
            if (UnconnectedPeers.Count == 0)
                NeedMorePeers(MinDesiredConnections - ConnectedPeers.Count);
            IPEndPoint[] endpoints = UnconnectedPeers.Take(MinDesiredConnections - ConnectedPeers.Count).ToArray();
            ImmutableInterlocked.Update(ref UnconnectedPeers, p => p.Except(endpoints));
            foreach (IPEndPoint endpoint in endpoints)
            {
                ConnectToPeer(endpoint);
            }
        }
```

Aheuaheuaea
Let me double check again before closing.

**Comment by vncoelho** [comment]
Double checked...aheauhuea
That is just an `Except`. In this sense, just deleting.
