### ISSUE TITLE
Never unFAULT

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#1210]
**Summary**
Transactions should never unFAULT, since this may cause double-spending on Neo3, when one thinks tx has failed, and then by a rare event it becomes a good execution state (and a second payment is also valid). The opposite is not too problematic, and probably necessary when bugfixing requires invalidation of some bad tx execution.

**Do you have any solution you want to propose?**
Store FAULTed txs block indexes on next block header (as a bit array, only extra 500 bits more max), meaning that they should never be considered valid. These tx could also be skipped during blockchain load (when future blocks are known in advance), thus accelerating the process. Other tx may be considered faulted or non-faulted, depending on contract state execution.

**Where in the software does this update applies to?**
- Consensus
- Ledger

**Comment by shargon** [comment]
Fault in verification or in Application?

**Comment by vncoelho** [comment]
`Application`

**Comment by igormcoelho** [comment]
Yep, FAULT only applies to Application... if it faults verification, transaction is invalid, and never included on a block (I hope so!! xD). Mutable states should also never transform a valid tx to invalid, from a verification perspective.

**Comment by lock9** [comment]
How can a transaction "unfault"?
