### ISSUE TITLE
Dynamic nonce

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1211]
**Summary**

Currently we store 4 bytes for the transacion's nonce, this could be optimized to be a dynamic number, and save some bytes for the first transactions of every address. The wallet could store his last nonce and use it as an incremental value, if he don't want to, he can send a regular random int as now.

**Do you have any solution you want to propose?**

Use VarInt for nonce.

**Where in the software does this update applies to?**

- Other: Transaction

**Comment by erikzhang** [comment]
I prefer fixed length.

**Comment by shargon** [comment]
Was only a brainstorm, usually I prefer fixed lengths too
