### ISSUE TITLE
Improve OnHeaderTaskCompleted Or Pass to the next step of using only Index

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1217]
@erikzhang @ixje @shargon,

I found that we may improve `OnHeaderTaskCompleted` event by checking if the pending headers tasks are of lower Height that where the Singleton currently is.
That would clean the `pendingheaderhashes` and allow concurrent header tasks of the current height.
That could be useful for `master2x`.

However, on master3x we are moving on the way to remove it.
Thus, I do not know if it is worth the effort.
I think it is quite simple and may slightly help master2x. What is your opnion?

**Comment by ixje** [comment]
Your description makes sense and if it's low effort, then I see no reason not to do it.

**Comment by shargon** [comment]
We can do it, and do some benchmarks
