### ISSUE TITLE
Cache Known globalTasks of InvType.Block

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1218]
**Summary**
If dealing with `InvType.Block`, we add all Hashes that are on `globalTsaks` to the pending `AvailableTasks` (`InvBlockPendingTasks`), and, then, later, we remove them.

**Do you have any solution you want to propose?**
Cache `https://github.com/neo-project/neo/blob/f1d643430966b9cc13f66ecb4ef2cfb462ccee85/neo/Network/P2P/TaskManager.cs#L63` into an `IEnumerable` or some other structure.

Add a new `Remove` on Helper for removing those from HashSet:
https://github.com/neo-project/neo/blob/f1d643430966b9cc13f66ecb4ef2cfb462ccee85/neo/Network/P2P/TaskManager.cs#L65

**Where in the software does this update applies to?**
- `TaskManager`

@Qiao-Jin, can you help us to take a look?
@shargon @erikzhang

**Comment by vncoelho** [comment]
It may be something like:

```cs
            var hashesOnGlobalTasks = null;
            if (payload.Type == InventoryType.Block)
            {
                hashesOnGlobalTasks = hashes.Where(p => globalTasks.ContainsKey(p));
                session.AvailableTasks.UnionWith(hashesOnGlobalTasks);
            }
            if(hashesOnGlobalTasks!=null)
               hashes.Remove(hashesOnGlobalTasks);
            else
               hashes.Remove(globalTasks);
```

**Comment by Qiao-Jin** [comment]
> It may be something like:
> 
> ```cs
>             var hashesOnGlobalTasks = null;
>             if (payload.Type == InventoryType.Block)
>             {
>                 hashesOnGlobalTasks = hashes.Where(p => globalTasks.ContainsKey(p));
>                 session.AvailableTasks.UnionWith(hashesOnGlobalTasks);
>             }
>             if(hashesOnGlobalTasks!=null)
>                hashes.Remove(hashesOnGlobalTasks);
>             else
>                hashes.Remove(globalTasks);
> ```

I think the last 'else' should be deleted. Because if `hashesOnGlobalTasks == null`, it means there is  not intersects between `hashes` and `globalTasks`, so no removing is needed.

**Comment by Tommo-L** [comment]
No, we should keep this code, as `InvType.TX` will also be stored in `globalTasks`.

```csharp
hashes.Remove(globalTasks);
```

**Comment by Tommo-L** [comment]
how about this way
```csharp
if (payload.Type == InventoryType.Block)
{
      var hashesOnGlobalTasks= hashes.Where(p => globalTasks.ContainsKey(p));
      session.AvailableTasks.UnionWith(hashesOnGlobalTasks);
      hashes.Remove(hashesOnGlobalTasks);
}
else
{
     hashes.Remove(globalTasks);
}
```

**Comment by Tommo-L** [comment]
And Can we fast to merge PR #899
