### ISSUE TITLE
Object reference not set to an instance of an object error [NEO3]

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1219]
**Describe the bug**
"Object reference not set to an instance of an object" error showed during consensus node running.

**To Reproduce**
1. Start a seed node.
2. Start a single consensus node.

**Expected behavior**
this error should not show and consensus node works well.

**Screenshots**
![微信图片_20191108170302](https://user-images.githubusercontent.com/34291844/68463791-5f6c7400-024a-11ea-8599-2cbcaee9bbaa.jpg)

**Platform:**
 - OS: [e.g. Ubuntu 18.04 x64]
 - Version [e.g. neo-cli 3.0]
neo-cli: master (#470)
neo: master (#1201)

**(Optional) Additional context**
Massive transaction frequently sent to an normal node.

[consensus_SingleNode.zip](https://github.com/neo-project/neo/files/3830935/consensus_SingleNode.zip)

**Comment by shargon** [comment]
Thanks @cloud8little for your tests!
could you provide the wallet password?
