### ISSUE TITLE
Decrease block time threshold

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1232]
**Summary**
Currently the threshold for PrepareRequest is 10 minutes, if a malicious CN propuse a block that come from the near future (10 minutes more), it will be accepted. Next blocks will be proposed by the others trusted CN from the future too
https://github.com/neo-project/neo/blob/f1d643430966b9cc13f66ecb4ef2cfb462ccee85/neo/Consensus/ConsensusContext.cs#L286

So next round, this malicious CN could propose another block, and step by step move the chain to the future

For 7 CN this should be the scenario (CN1 malicious one):

First round:

- CN-1 (Real Time 00:00:00 , BlockTime 00:10:00)
- CN-2 (Real Time 00:00:15 , BlockTime 00:10:01) 
- CN-3 (Real Time 00:00:30 , BlockTime 00:10:02) 
- CN-4 (Real Time 00:00:45 , BlockTime 00:10:03) 
- CN-5 (Real Time 00:01:00 , BlockTime 00:10:04) 
- CN-6 (Real Time 00:01:15 , BlockTime 00:10:05) 
- CN-7 (Real Time 00:01:30 , BlockTime 00:10:06) 

Second round

- CN-1 (Real Time 00:01:45 , BlockTime 00:20:06) 

**Do you have any solution you want to propose?**
Reduce the threshold to 1 or 2 minutes.

**Where in the software does this update applies to?**
- Consensus

**Comment by shargon** [comment]
Maybe the formula should be related to the number of verificators and the time per block, what do you think? @neo-project/core @neo-project/ngd-shanghai @erikzhang

**Comment by vncoelho** [comment]
@shargon, for me this is expected. Not a bug.

If this happens, NEO holders should vote against.

**Comment by shargon** [comment]
A malicious CN can send the chain to 2020 in 2019, this is not expected.

**Comment by lock9** [comment]
Isn't this one kind of metric that we can ensure node health? 
This can be one metric, time that he was the speaker and did not submited a block on time can also be a metric. What do you guys think?

I agree that we should not let nodes create blocks too much in the future.

**Comment by shargon** [comment]
But what do you propose, watch and monitoring the CN in order to force a vote if this happens?
