### ISSUE TITLE
Transactions with insufficient funds can be on-chain and lead to consensus service stuck

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1244]
**Describe the bug**
Transactions with insufficient funds can be on-chain and lead to consensus service stuck.

**To Reproduce**
1. Run one seed node.
2. Run a single consensus node, connect to the seed node
3. Run an external node.
4. Withdraw the initial NEO/GAS and send 100k GAS to a sender wallet.
5. Open the sender wallet, use (sendfrom)rpc request to send about 800k requests, 0.00000001 GAS/request to another account.
6. Around 1hour later, consensus service stuck, not generating blocks anymore.

when the consensus service stuck, there is only 459+GAS with the account.

**Expected behavior**
Those transactions with not enough gas check should be discarded.
Consensus service should not stuck.

**Screenshots**
![3171573801636_ pic_hd](https://user-images.githubusercontent.com/34291844/68926400-6d794200-07c0-11ea-85d2-febc06c890cd.jpg)
![4281573804642_ pic_hd](https://user-images.githubusercontent.com/34291844/68926504-a5808500-07c0-11ea-91f5-463b7c14b23e.jpg)
![4291573804681_ pic](https://user-images.githubusercontent.com/34291844/68926538-b7622800-07c0-11ea-9841-940ed1e3c4cd.jpg)

**Platform:**
 - OS: Ubuntu18.04
 - Version
neo-cli: master #470 
neo: master #1150 + pr1220

**Comment by Tommo-L** [comment]
This problem related to #1140 @vncoelho 

I think we can allow this situation happen but change the calculation of sys_fee.

https://github.com/neo-project/neo/blob/72be7f6a26f3ed222f1ad5dc1b4391c62fa4f67d/neo/SmartContract/Native/Tokens/GasToken.cs#L37-L53
