### ISSUE TITLE
[Enhancement] Exception message about consensus logs can be written into error.log

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1245]
**Summary or problem description**
Exception message about consensus logs can be written into error.log

**Do you have any solution you want to propose?**
Recently i've run several tests about consensus service, and found that the exception logs are not written to the file error.log, and fortunately I use screen to recover the session so the error logs can be found out. Even though you can use "> xx.log" to log this, this requires you add it when you start the service. 

**Where in the software does this update applies to?**
- CLI

neo-cli: #470 
neo: ##1150

Exception like this, currently wallet format error will be logged, but consensus service error won't .
![4281573804642_ pic_hd](https://user-images.githubusercontent.com/34291844/68928093-3d33a280-07c4-11ea-8233-862200c3d838.jpg)
![4301573806271_ pic_hd](https://user-images.githubusercontent.com/34291844/68928179-6f450480-07c4-11ea-96f0-95b0af5487c2.jpg)

**Comment by shargon** [comment]
Now the exceptions are captured by akka

https://github.com/neo-project/neo-cli/blob/8c6de106094a8894c7be2c19768697f9afef774f/neo-cli/Program.cs#L13

So... I think that we need to call this method when akka print the log.

**Comment by shargon** [comment]
@neo-project/ngd-shanghai do you know if we can merge `AppDomain.CurrentDomain.UnhandledException` and akka logging in the same method?
