### ISSUE TITLE
Autoclaim Gas on Gas transfers too

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1253]
In neo3 there is automatic GAS claim, but only when a NEO transfer is made, maybe we should also do that with GAS transfers

**Comment by i359** [comment]
if remain gas <0.01, then autoclaim gas on all NEP5 transfer,why not?

**Comment by erikzhang** [comment]
I originally had 2 GAS, after I transferred 1, there are 2 left, oh my god.

**Comment by igormcoelho** [comment]
It can be worse,you had two, transfer one and have three now 😂 but its useful, in current context.
I'm starting to believe that only holding Neo (locked/staked) should generate GAS. 
Thos simplifies operations on exchanges, as they wont necessarily stake for their customers, and it becomes a reward system more focused on consensus and longterm investments. Regular customers could convert Neo to Gas by a system gateway rate, agreed by consensus.

**Comment by shargon** [comment]
> I originally had 2 GAS, after I transferred 1, there are 2 left, oh my god.

Sounds weird, but nothing bad is there. It's the same with neo. I want to send all my money to another wallet, i sent my neo, and GAS appear

**Comment by vncoelho** [comment]
HEAUheuaea, I think it is a good feature, @shargon. I also do not see a problem on this.

We also still need to solve how to Welcome a first transaction.
It is quite bad to need GAS for a first claim or voting. as emphasized by @vang1ong7ang.

**Comment by shargon** [comment]
> We also still need to solve how to Welcome a first transaction.

Also, we should be able to take this GAS and using it as a fee as you proposed @vncoelho , but this is another issue :P

**Comment by erikzhang** [comment]
I think this is a disaster for some companies that need to book, and they will have a hard time figuring out how their accounts are changing.

**Comment by shargon** [comment]
It's only a brainstorm :P Maybe is a shit hahaha

**Comment by lock9** [comment]
Closing the issue as requested by Shargon
