### ISSUE TITLE
NeoFS URI Standard

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1256]
We should have a NeoFS URI standard.

Specification
--------------

```
<schema>:<ContainerID>/<ObjectID>
<schema>:<ContainerID>/<ObjectID>/metadata
```

The URI allows us to easily download an object or its metadata.

Examples
-----------

```
neofs:8hBvn8VwYbP4BLPANZoYgiMhBEiwLmmpbbPfG53mxhyP/839fd203-9f98-4f69-8f4f-0cd2a6a671cb
```

This URI allows us to download an object by giving its *ContainerID* and *ObjectID*.

```
neofs:8hBvn8VwYbP4BLPANZoYgiMhBEiwLmmpbbPfG53mxhyP/839fd203-9f98-4f69-8f4f-0cd2a6a671cb/metadata
```

This URI allows us to download the metadata in JSON format.

**Comment by realloc** [comment]
There also must be the container ID part. So the NeoFS address would look like this:
``neofs://<ContainerID>/<ObjectID>``

``neofs://8hBvn8VwYbP4BLPANZoYgiMhBEiwLmmpbbPfG53mxhyP/839fd203-9f98-4f69-8f4f-0cd2a6a671cb``

Where ObjectId is UUID and ContainerID is SHA256 hash of the container structure.

More detailed description can be found in [NeoFS API documentation](https://github.com/nspcc-dev/neofs-proto/tree/master/docs).

**Comment by erikzhang** [comment]
Can't we find the object by `ObjectID`? Do you mean that objects with the same `ObjectID` may exist in different containers?

**Comment by realloc** [comment]
ObjectID id not enough. Container defines storage policy, so it's required to find and object.

There is a tutorial [video](https://www.youtube.com/watch?v=0NDF3QqHpjk) explaining this.

**Comment by erikzhang** [comment]
Waiting for #1261

**Comment by realloc** [comment]
Maybe URL discussion form #1270 should be moved here.

**Comment by erikzhang** [comment]
```c#
Oracle.Get($"neofs://{ContainerID}/{ObjectID}"); //Object.Get
Oracle.Get($"neofs://{ContainerID}/{ObjectID}/range/{Offset}|{Length}"); //Object.GetRange
Oracle.Get($"neofs://{ContainerID}/{ObjectID}/hash/{Offset}|{Length}"); //Object.GetRangeHash
Oracle.Get($"neofs://{ContainerID}/{ObjectID}/header"); //Object.Head
```
