### ISSUE TITLE
NeoFS API List (gRPC)

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1257]
[NeoFS Protocol documentation](https://github.com/nspcc-dev/neofs-proto/tree/master/docs).

**Comment by shargon** [comment]
- Track (For know in which servers are stored or some information about the replication status).
- Remove.

**Comment by erikzhang** [comment]
I think `Remove` should be provided in the native contract.

**Comment by realloc** [comment]
NeoFS node API description can be found in [NeoFS Protocol documentation](https://github.com/nspcc-dev/neofs-proto/tree/master/docs).

There is no difference between client or node API, all NeoFS nodes talk the same protocol. gRPC calls are grouped by services. For example to operate with objects you call Object service.

**Comment by erikzhang** [comment]
@realloc 

https://github.com/nspcc-dev/neofs-proto/blob/master/docs/object.md#object.DeleteRequest

If metadata are stored in native contract, we can simplify the neofs protocol. Objects can be deleted from native contract. And the neofs nodes can trace the metadata changes by reading the blockchain storage.

**Comment by realloc** [comment]
@erikzhang Having object's metadata onchain will bloat the storage size and quickly become the bottleneck. One of key architectural benefits of NeoFS is absence of centralized metadata storage, which allows it to scale.

Please see the [webinar video](https://www.youtube.com/watch?v=2o44JvXyy0o) explaining the overall NeoFS architecture.
