### ISSUE TITLE
neo uses protocol.json file binary folder instead of current working folder

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1258]
neo should be loading the protocol.json file from the current working folder, not the folder where the neo binary is located. This would allow multiple nodes to run on a single machine (such as in a privatenet scenario) without needing multiple folders with neo binaries.

If desired, we can fallback to the protocol.json from the binary folder if there is no protocol.json file in the current working folder.

**Comment by shargon** [comment]
Ready to implement?

**Comment by shargon** [comment]
@devhawk Is not better to use a `--config` parameter and use this https://github.com/neo-project/neo/pull/845

**Comment by devhawk** [comment]
That's not how other command line tools work by default. Think of how git works. Git looks for the .git folder based off the current working folder. You don't set information about the repo you are working with in the git binary directory. You can override git's default behavior with [-C](https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt) and [--git-dir](https://git-scm.com/docs/git#Documentation/git.txt---git-dirltpathgt) but it uses current working directory by default.
