### ISSUE TITLE
Containers in NeoFS

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1261]
Please describe in detail the role and necessity of Container in NeoFS.

**Comment by AlexVanin** [comment]
NeoFS network map is a multigraph where vertexes are the properties of storage nodes (location of storage nodes or type of hardware they use). Leaves of the multigraph represent storage nodes themselves.

This multigraph can grow infinitely with the growth of the NeoFS network. It is inefficient to parse big complex graph to find placement locations for the data. To solve this issue we work with the smaller subgraphs, that defined by user's storage policy. This gives:
- low graph traversal complexity, almost independent of the size of the multigraph
- possibility for the user to define the exact storage conditions (e.g. to store data only in desired country)

Container - is the representation of the subraph. It contains user's [placement rules](https://github.com/nspcc-dev/neofs-proto/blob/master/docs/container.md#container.Container). Placement rules are [applied](https://github.com/nspcc-dev/netmap/blob/51e333aa88550b512a9236d277fe8169ca6f76e7/policy.go#L247) to the multigraph to obtain subgraph structure.

From user's prespective you can think about container as a namespace for the objects or folder in terms of filesystem.

**Comment by erikzhang** [comment]
I have two questions:

1. Can storage policy be applied to object directly?
2. Is it possible to get the container of an object by giving the `objectid`?

**Comment by realloc** [comment]
> Can storage policy be applied to object directly?

No. At fist step storage policy must be used to calculate the subcluster of nodes that may host the object.

> Is it possible to get the container of an object by giving the objectid?

No. Practically no. In theory it may be done by doing full-scan search over all nodes in the network, which is almost impossible in real world.
