### ISSUE TITLE
[Oracles] Accepted responses

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1263]
What response we should be able to handle?

- JSON?
- XML?
- TEXT?
- HTML?

(Main topic discussion **Syscall and ApplicationEngine** https://github.com/neo-project/neo/issues/1275)

**Comment by erikzhang** [comment]
I prefer JSON only.

**Comment by shargon** [comment]
Json only is good for me too

**Comment by realloc** [comment]
@shargon Could you please clarify what response do you mean here? Is that just about the format to store responses in ResultCache?

**Comment by igormcoelho** [comment]
Do we want to build web crawlers on oracles? 😂 
there are two approaches, consuming a standard service, perhaps json as @erikzhang mentioned,or global data dump,including html,and parse it to get information,not quite from an API,but from anything. I see benefits in both, but I prefer a global approach, as long as response type is identified (application/json for example, and user may reject others).

**Comment by shargon** [comment]
> Could you please clarify what response do you mean here? Is that just about the format to store responses in ResultCache?

We have filters, but you need a filter for every format, the filter for XML is different than JSON. So first, we need to know which kind of responses we will allow. 

But my question is more about. If we decided that the filter is OK for us (i hope so xD) we need to know wich filters we will implement. If your download return a raw text file, and you don't use a filter is good to me, expensive but good. Maybe the question is more about wich kind of filters we want?

**Comment by erikzhang** [comment]
We should recognize the format of the object based on its `Content-Type`. The user should clearly indicate what `Content-Type` he accepts. We can only support `application/json` first. In the future we can support more `Content-Type`.

**Comment by lock9** [comment]
I agree with JSON and I also agree that we should support additional responses in the future. I think that there will be occasions where the smart-contract developer won't have access to an API.

**Comment by belane** [comment]
Perfect, the first accepted response to be implemented is **JSON** and the `Content-Type` response should match this.

**Comment by shargon** [comment]
The current version doesn't care about the `Accepted-Response` I think that the filter should be used for parse the json, the xml or other formats.

👍 Thumb Up if you are agree, we should accept any response .
👎 Thumb Down if you think that we need accept only `json`.

@neo-project/core @neo-project/ngd-seattle @neo-project/ngd-shanghai @realloc @roman-khimov

**Comment by shargon** [comment]
I think that it will be easier and safer with a whitelist control https://github.com/neo-project/neo/pull/1591

**Comment by Tommo-L** [comment]
Close? It's moved to neo-modules/OracleService.
