### ISSUE TITLE
Oracle: ProxyPlugin

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1264]
**Summary or problem description**
Oracle nodes could expose its IP address. In fact this is not a problem, but maybe it could be beneficial allow from other nodes to act like a Socks5 proxy. Also they could help with some firewalls or problems with ISP.

**Do you have any solution you want to propose?**
Create an official Socks5 proxy plugin, and allow it to be used for the oracle nodes (authenticated with the oracle signature)

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Plugins

**Comment by erikzhang** [comment]
Maybe we should allow https only?

**Comment by shargon** [comment]
> Maybe we should allow https only?

 I think so

**Comment by igormcoelho** [comment]
https is good, but it would be better to have integrity checking also... some time ago Wang commented the possibility of proposing a new certificate standard, or following some public discussions on it. It would be nice to be able to verify integrity of response from distant server,specially via some proxy.
Question,how it would be used this plugin? Is it to request access to tunnelvor provide access to others?

**Comment by lock9** [comment]
@igormcoelho https already ensures integrity.  About the certificate, I don't think that proposing a new standard can help the platform, we should support 'market standards'. Is there a reason why we should create a new standard?

**Comment by Tommo-L** [comment]
Fixed by https://github.com/neo-project/neo/pull/2090
