### ISSUE TITLE
Content-Type in NeoFS

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1266]
Is there a `Content-Type` field in the metadata of an object?

**Comment by AlexVanin** [comment]
It is possible to define `Content-Type` or any Key-Value string pair as a [User Header](https://github.com/nspcc-dev/neofs-proto/blob/master/docs/object.md#object.UserHeader) in object's metadata. But `Content-Type` header itself is not a part of the object.

**Comment by erikzhang** [comment]
Can it be a system header?

**Comment by realloc** [comment]
No, system headers refer to object itself, not the content.

For NeoFS user's data is just a blob. It's fully user's area of responsibility to know what's there, so Content-Type headers and things like that are in user headers.
