### ISSUE TITLE
lock witness

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#1301]
**Summary or problem description**
Recent events again made me realize security can be improved a lot for holders, if they stake for a while, and by controlling behavior after unstakong (slowing down operations for example). The easiest way to do it compatible to all existing tokens snd assets is via witness system. I propose interop Runtime.LockWitness.

**Do you have any solution you want to propose?**
If you execute Runtime.LockWitness, it will lock your witness for a given number of blocks (max 3 months or so). Witness will be unusable during this period, and user can specify a temporary unlock time, where it still cannot be used, but can be locked again. This allows continuous locking of funds, and even if privkey gets stolen,funds will never be usable (if continuosly locked).
example
```
push 10   # blocks unlock-alias time
push 100  # blocks for locking
push 001122334455... # scripthash
Runtime.LockWitness
```
(User attaches this witness to tx)

Locks witness for 100 blocks and 10 extra blocks for re-locking or aliasing (recovery). Time (extra) only counts after next command. Example:

After 150 blocks:
```
push 0011223344.. # alias to same witness (could be different)
push 0011223344..  # scripthash for unlocking
Runtime.Unlock
```
(only really unlocked after 10 more blocks, while it can be re-locked again)

After this command, user can set an alias to itself (less safe) or alias to other new key (safer). If some attacker changes alias before owner, the owner could still issue a new lock command... this way, funds are locked forever, at least until attacker gives up, and no coins would be spent. This extra time could be used to devise more elaborate strategies connected to offchain governance, as recovery, or at least keep funds locked forever, yielding no gains to attacker.

Valid for neo2 and 3.

**Neo Version**
- Neo 2
- Neo 3

**Where in the software does this update applies to?**
- Ledger
- Network Policy
- Interop System
- Other:

**Comment by shargon** [comment]
I understand the problem that you want to solve, but I think that is possible to do with a bank contract, The smart contract can do this without specific syscall

**Comment by igormcoelho** [comment]
You can solve with smart contract, it's true, but thos way you can solve while not affecting an existing account with values. You can even partially lock some keys of a multisig, without affecting the whole.
 It also has the advantage of providing a global way to determine if some witness is actually locked, which cannot be done if everyone design its own locking system. This allows future concepts of: voting only if staking; claim gas only if staking; and a global secure staking with recovery mechanism.

**Comment by igormcoelho** [comment]
Another simple benefit of this proposal: wallets may require destination to unlock their witness before transfering, as it ensures witness is operational. If not unlocked, wallets may issue a warning, that destination may not be able to receive funds (but users can proceed anyway).
