### ISSUE TITLE
Prevent lost funds because Destroy

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1302]
**Summary or problem description**

Smart Contract can hold neo, also gas. But if the user destroy by a mistake the contract, we will lost all of these coins. Also it could happend with other NEP5 tokens. We have cases in the past in ethereum ( https://www.cnbc.com/2017/11/08/accidental-bug-may-have-frozen-280-worth-of-ether-on-parity-wallet.html) 

**Do you have any solution you want to propose?**

- Store the creator of the contract, and if the contract doesn't exists he will have access to the funds. 
- Prevent to destroy a contract if it have neo or gas (not useful for other nep5 tokens) 
- Distribute the neo and gas around the neo holders
- Destroy/Disable. The first time that you call Destroy, the contract will be disabled, the next time, will be destroyed (nlt very useful) 

And my favorite :
- Store funds with a specific flag, **important** And the contract will be impossible to be destroyed if there are information with this flag stored. 

*Any possible solution with only neo and gas, is a partial fix.*

**Neo Version**

- Neo 2
- Neo 3

**Where in the software does this update applies to?**

- Other: It depends

**Comment by erikzhang** [comment]
> But if the user destroy by a mistake the contract, we will lost all of these coins.

I think we won't lose all the coins. Just re-deploy it and the coins be back.

**Comment by shargon** [comment]
But maybe the contract set the owner after the creation, and is not hardcoded, you have a chance of loose the tokens if someone else do that before you.

**Comment by doubiliu** [comment]
Maybe we can do a check in 'Destory' method to prevent to destroy a contract if it have neo or gas .
And i think double destory is not necessary.

**Comment by shargon** [comment]
This check is usually made by the smart contract, so I think that at least do this, it's needed

**Comment by doubiliu** [comment]
yeah,I know.I think add in this part is well.
```
        private static bool Contract_Destroy(ApplicationEngine engine)
        {
            UInt160 hash = engine.CurrentScriptHash;
            ContractState contract = engine.Snapshot.Contracts.TryGet(hash);
            if (contract == null) return true;
            //add code
            engine.Snapshot.Contracts.Delete(hash);
            if (contract.HasStorage)
                foreach (var pair in engine.Snapshot.Storages.Find(hash.ToArray()))
                    engine.Snapshot.Storages.Delete(pair.Key);
            return true;
        }
```

**Comment by lock9** [comment]
We can return the funds to the Sender of the transaction that deployed the contract. Not sure if possible or if it is a good solution 😅 .
We can add a 'termination protection', but this won't solve the real issue that is creating a blackhole.

I think that blocking contract destruction or making an automatic withdraw may be the best solution. I don't agree to distribute NEO/GAS to holders, this assets have an owner already.

The problem is similar when the user lose their private keys, there isn't much we can do.

**Comment by Tommo-L** [comment]
Close?
