### ISSUE TITLE
Design of SeraphID

### ISSUE THREAD

**Issue by SueNEO** [neo-project/neo#1305]
This issue describes the overview of SeraphID solution, please see [whitepaper](https://www.seraphid.io/assets/files/white_paper.pdf) for details.

## 1. Introduction

SeraphID is a Self-Sovereign identity framework built on the NEO blockchain which enable your dApps to support decentralized identity system. Self-Sovereign identity allows users to be in control of their own data and decide what to share and to whom. This solution relies on the W3C standards providing DID and verifiable claims functionalities. 

## 2. SeraphID actors

Within the SeraphID model there are four roles available：

Role | Definition
-- | --
Issuer | A role an entity performs by asserting claims about one or more subjects, creating a verifiable credential from these claims, and transmitting the verifiable credential to a holder
Verifier | A role an entity performs by receiving one or more verifiable presentations for processing. Other specifications might refer to this concept as a relying party
Holder | A role an entity performs by possessing one or more verifiable credentials. A holder is usually, but not always, the subject of the verifiable credentials they are holding. Holders store their credentials in credential repositories
ROT-Manager (Root-of-trust) | A role an entity performs by governing an SSI-network. A ROT-manager defines a set of business, legal, and technical rules that any participant should adhere to in order to be onboarded and participate in the specific SSI-network

## 3. SeraphID System

SeraphID aims to introduce generic SSI capabilities on the NEO blockchain which solve the issue in real world by avoiding the centralization of identities and allowing the owner to store and manage their identity. The end user is then equipped to decide if, when, and what data to share with a third party that is requesting access to specific information about the user. This third party (verifier), once in possession of the piece of digital information shared by the user, should then be capable of validating it. The validation process involves verifying that the claim is still valid (it has not been revoked), that it has not been tampered with (it is authentic), and who the issuer was. 

![image](https://user-images.githubusercontent.com/43411424/69796225-9958e680-1208-11ea-885f-f46f4f19517e.png)

Everyone is free to spin-up their own distributed “SSI-network” and decide the rules that are governing it, it makes sense to grow and leverage the network of trust by implementing ROT-managers. They can onboard other parties, and since the network trusts the ROT-manager, it also trusts the parties it is onboarding. Once an entity takes on the role of ROT-manager, it represents a repository of whitelisted entities that can be indirectly trusted by verifiers. A ROT-manager has the goal to onboard other entities offline and through the business agreements that govern the SSI-network. As a verifier, once you trust a ROTManager, you then can benefit immediately from the subsequent trust of all the issuers that the ROT-Manager whitelisted within the SSI-network. Having a ROT-Manager in an SSI-network is optional and can be decided based on the specific business case.

SeraphID offers three different levels of verification. Each developer can choose which one to use based on his use case and the performance he wants to achieve.

Method | Description | Type of validation Reference
-- | -- | --
verifyOffline | It will validate the claim just using the contained information. ”Offline” because it does not connect to the blockchain | Lightweight validation which helps to verify if the claim has been signed correctly by the issuer at the time of generation
verify | It will connect to the blockchain in order to validate the current public identity of the issuer | This type of validation connects to the blockchain in order to check the identity of the issuer in real time
validateClaim | It will connect to the blockchain, check the issuer public identity but also the revocation registry | This validation is the most complete one as integrates the previous and checks the revocation registry

SeraphID follows the privacy-bydesign principle. That is why most of the components provided within the SeraphID ecosystem are meant to be handled off-chain. The amount of data stored in the ledger is quite small, related either to public information (issuer identity, revocation registry) or private information that is hashed (hash of credential ID). And, the system supports selective disclosure, even if a claim takes the form of a set of attributes, the verifier should be able to request to read just a single specific attribute, providing a more precise authorization request to the subject.

**Comment by vncoelho** [comment]
@SueNEO, perhaps this should be reopened as well.
SeraphID has an innovative simplicity that possible accomplishes our needs. 

However, in my opinion, not so complete as Athena, which would provide a variety of possibilities for extensions.
