### ISSUE TITLE
Design of AthenaID

### ISSUE THREAD

**Issue by SueNEO** [neo-project/neo#1306]
This issue describes the overview of AthenaID solution, pelease see [whitepaper](https://drive.google.com/file/d/1hBUVqZfYWc19q3212YqpIgRaygUpCZzy/view?usp=sharing) for details.

## 1. Introduction

AthenaID aims at providing a compliant solution built on NEO blockchain that can return data rights to users. It is a highly scalable system that transforms “trust or not” into “how much trust” with the newly proposed rating mechanism which allows users to customize trust evaluation models flexibly.

## 2. List of Terms and Roles

Role | Definition
-- | --
trustor | an entity that may trust or distrust the other entity (the trustee) or evaluate the rating of the identity document of the other entity for making a decision
trustee | an entity that may prove its identity to the trustor
recommender | an entity that recommend the trustee to the trustor through claims

Term | Definition
-- | --
entity | a thing with distinct and independent existence or a resource of any kind that can be uniquely and independently identified.
identifier | name that identifies an identity document. Each identifier is unique
proposal | an expression to describe the set of attributes of the entity or the authorization limit scope of the entity
identity document | digital document which may be used to prove an entity's identity which contains a proposal of the entity
rating | rating is a scalar to measure trust. It is expressed as a floating-point number between 0 and 1 inclusive
claim | a directed connection that describes a rating to an identity document issued by another identity document's holder
trust graph | a weighted directed graph about trust or authorization relations among the identities consists of a set of identity documents and a set of claims
IDnet | an online subgraph of trust graph stored on NEO blockchain 
trust profile | an offline subgraph of trust graph about a trustor that consists of the set of recommenders that the trustor trust and the claims from the trustor to each recommenders
trust proof | an offline subgraph of trust graph about a trustee that consists of the set of recommenders that trusts the trustee and the claims from each recommenders to the trustee
rating evaluation function | a function to solve an overall rating metric from a trustor to a trustee on the trust graph

## 3. AthenaID System

As the core concept of the AthenaID system, trust is the basis of function implementation. It has the following three attributes:

- Subjectiveness: For the same trustee, different trustors may have different evaluation results under the same conditions.

- Context Dependency: For the same trustee, a trustor may have different evaluation results for different contexts, such as working, sociability, learning, etc..

- Dynamism: Trust network is changeable. Improper behavior, joining/exiting of a recommender, time elapsing and other factors can cause the change in the network.

AthenaID system consists of four main models: Trust Model, Game Model, Privacy Model, and Proposal Model.

### Trust Model

Trust model is the most important model in AthenaID. It provides the tools needed to build a decentralized PKI for the trustor to evaluate trust to a trustee. AthenaID achieves subjectiveness using the Trust Model by having each trustor build a local trust graph according to their trust profile to evaluate trust. The trust model describes the relationship between entities, identity documents, claims, ratings, and trust profiles. In the AthenaID system, each entity can have multiple identity documents corresponding to different identities (e.g., academic, employment, personal) and different roles (e.g., trustor, recommender/CA, trustee). These identity documents can issue declarations to each other and build local trust graphs which can be used to evaluate the trust relationship between any two identity documents and provide a basis for traceable trust evaluation via its rating evaluation function. Each application trustor of the AthenaID is able to determine their own rating evaluation function to satisfy their needs.

![image](https://user-images.githubusercontent.com/43411424/69868205-0a210100-12e4-11ea-85b8-0bad01d963f2.png)

Identity documents are connected by claims to assert a value(rating) which means an indication of how much the party agrees with the proposal being included in another idetity document. In this work, we have chosen to represent rating as a continuous variable over a specific range [0, 1]. Here is a possible stratification of rating:

rating | label
-- | --
1 | Blind Trust
[0.9, 1) | Very High Trust
[0.75, 0.9) | High Trust
[0.5, 0.75) | High Medium Trust
[0.25, 0.5) | Low Medium Trust
(0, 0.25) | Low Trust
0 | No Trust or Support

### Game Model

The game model describes the framework of incentives and penalties in a trusted network. With the economic model and the governance model, entities will have reason to engage in trustworthy behavior and be deterred from malicious activities, to establish a true trust network.

### Privacy Model

The privacy model provides the scheme for privacy protection of user data. It ensures data security through techniques such as off-chain private data, zero-knowledge proofs, and end-to-end encryption for off-chain communication.

### Proposal Model

The proposal model outlines the design for identity documents, which incorporates expressions describing the set of entity attributes and the authorization of the entity. The model implements the context-dependency of the authorization by limiting the authorization scope to only capable verifiers and allows the use of rich expressions to describe any attribute or ability with the support for symbolic calculation.

There are two types of proposals:

- Attribute Proposal is used to describe attribute information of the entity and is kept offchain. 

- Scope Proposal specifies the authorization scope of the entity to issue a trust claim to other entities, and the scope information is exposed on the blockchain. The proposal model allows identity documents to issue claims only within the authorization scope using scopes that restrict the authorization abilities. As shown in the following figure, the solid line box indicates the authorization scope of identity documents, the solid arrow indicates the valid claim, while the dotted arrow indicates the invalidity of claims.

![image](https://user-images.githubusercontent.com/43411424/69775578-1ae25180-11d4-11ea-923c-24cd5d188c94.png)

**Comment by erikzhang** [comment]
Can you give it a code name before naming it as NeoID?

**Comment by SueNEO** [comment]
OK. For the convenience of discussion, the name of NGD design has been changed to "AthenaID" as a code name.

**Comment by vncoelho** [comment]
@SueNEO, I think this should be opened again such as the other NeoID thread.

It has an interesting and innovative Trust Graph system, which provides scalability and different levels of trust. There is also a novel game theory model for governance.
