### ISSUE TITLE
NEO team, please help

### ISSUE THREAD

**Issue by lansana** [neo-project/neo#131]
Hey guys, I know this is slightly off topic, but can't find any other means to contact NEO team directly.

There is a coin called DeepBrain Chain (DBC) that just ICO'd a couple of days ago. They are advertising that NEO invested $1m into them.

Is this true?

Please answer this, thanks. Lots of people may be getting scammed by this ICO...

**Comment by localhuman** [comment]
This is not an issue for Github.
