### ISSUE TITLE
Maybe this cause NEP5 token transfer failed

### ISSUE THREAD

**Issue by fl0wjacky** [neo-project/neo#132]
I make transactions to transfer a NEP5 token from address A to B,when the value(Fixed8 form)'s length less of 8 bytes, sometime the transfer failed.
But when I fixed the value's length to 8 bytes, the transfer always success.

**Comment by erikzhang** [comment]
How do you make the transactions?

**Comment by fl0wjacky** [comment]
Like this
Transfer 0.1 RPX From AUHPEE3L3BoLdfsVfJrZ7hmHJAkYPw1pDi to AHZDq78w1ERcDYVBWjU5owWcbFZKLvhg7X

Failed:
d101
58
03 809698
14 138bb1207f869b6c08a6fbd911251fcbf8194aa9
14 893644048d69c0329720a1283eaaab6f1d2ed2dc
53c1
08 7472616e73666572
67 f91d6b7085db7c5aaf09f19eeec1ca3c0db2c6ec f1 66 0fccd92f5517d982
0000000000000000
02 20 893644048d69c0329720a1283eaaab6f1d2ed2dc
f1 05 4f5443474f
0000

Success:
d101
5d
08 8096980000000000
14 138bb1207f869b6c08a6fbd911251fcbf8194aa9
14 893644048d69c0329720a1283eaaab6f1d2ed2dc
53c1
08 7472616e73666572
67 f91d6b7085db7c5aaf09f19eeec1ca3c0db2c6ec f1 66 0fccd92f5517d982
0000000000000000
02 20 893644048d69c0329720a1283eaaab6f1d2ed2dc
f1 05 4f5443474f
0000

**Comment by erikzhang** [comment]
809698 is a negative number. So it failed.

**Comment by fl0wjacky** [comment]
So what's the difference between negative number and positive number?

**Comment by erikzhang** [comment]
809698 => -6777216
80969800 => 10000000

**Comment by fl0wjacky** [comment]
Positive numbers in NeoVM end up with byte '\x00', is that right?

**Comment by erikzhang** [comment]
Do you know what is "sign bit"?
