### ISSUE TITLE
Due to current master branch, two nodes aren't able to run at the same time.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1327]
**Describe the bug**
After making intergration test via current master branch of neo-vm, neo, neo-cli, neo-plugins, found the second node wasn't able to ```startnode``` when the first node was running.
**To Reproduce**
1. Build the latest neo-cli within leveldb plugin
2. run a node and then run another

**Expected behavior**
The second node will run but can't go to neo-cli menu.

**Screenshots**
Found it stopped here. Is it possibly related to leveldb plugin? Path conflict?
![image](https://user-images.githubusercontent.com/38493437/70201854-c8181500-1752-11ea-8773-7ebd6e3942b5.png)
![image](https://user-images.githubusercontent.com/38493437/70201872-d36b4080-1752-11ea-8a91-7d08f60d67db.png)

**Platform:**
 - OS: Windows 10 x64
 - Version: latest master

**Comment by erikzhang** [comment]
Please test neo-project/neo-plugins#153. It should fix this issue.
