### ISSUE TITLE
离线签名的交易调用sendrawtransaction返回一个错误

### ISSUE THREAD

**Issue by leor-w** [neo-project/neo#1339]
我使用离线签名构建原始交易,现在单个输入的交易可以正常的通过节点打包到区块内,但是在做多个交易输入的时候调用sendrawtransaction却返回了一个错误给我,我不知道我的问题出在那.
这是在我搭建的私有链上,通过我的程序创建的一个交易:
```
{
  Transaction: {
    Type: 80,
    version: 0,
    Attribute: [
      
    ],
    Vout: [
      {
        asset: 9b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5,
        value: 0012c2e801000000,
        address: e7082a5ca5f673a1c4210b3c69ef29c04f8a25cc
      }
    ],
    Vins: [
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0900
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0600
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0000
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0700
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0800
      }
    ],
    Scripts: [
      {
        invocationScript: 40ffdde2369cc8802e9cc0db3ba1d1e2d6bd3d161eaf0443f821b470e1597456c161d6ea6082ee80c2be809618288371b0ce7263bfbc4a015eec828119d5df34c7,
        verificationScript: 210284461cd448237a0c814590e1254497e0ea94af494345ec33ea43488f841869a2ac
      },
      {
        invocationScript: 40be74958d8a1a7f94a6efe63ea0b2414063ba0055768cd87d30574b7c276700b192857b06df9628bc6d645d9369c5e046d87e025f7c81380bc61b2fb431512d02,
        verificationScript: 2102b38872a74b5e1dc743f6da7c2cced255549790f7674bc7e46497954160f8247eac
      },
      {
        invocationScript: 40a7f6ad2d8fb99eed087a0638322c9c9a0cedf211c75fd8c3b89af3d027a1aa7384230ff0f3460028c7491c40e5cae8319ab1f847eb4fd445fc4eabf6f794dd2c,
        verificationScript: 210281c10f9e42a8c7f2e49b8b24403a519a6094afd3da6a38ee50ee7b0cc834d51aac
      },
      {
        invocationScript: 4073e7b738a3db7a6878385ec039258ff13896d0e9dfa7114f4539f6fd2f52fe36a60802a86e7a131c9300bb122fa836b5df38586d5b9c927d4d428ca0bf6f19a5,
        verificationScript: 210248eb66f6d029d3fda42d894d19098cbde32fc7017f1dd7a95972e6aa87c544a0ac
      },
      {
        invocationScript: 40bc072a6b47436999dffc5f7ae3b566ffac38a9c579a041bef6b0ceed0b1c1200ce4d8e949d0b35ae1c7f36ac894e0104e65de485532047ac828c9c92e78fc8b4,
        verificationScript: 2103e931de58e28b4e431a30e3e1f5258d7a7879065aa589b0357e80905fac07f0cfac
      }
    ]
  }
```
序列化后的交易:
```
800000055d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca09005d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca06005d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca00005d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca07005d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca0800019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc50012c2e801000000e7082a5ca5f673a1c4210b3c69ef29c04f8a25cc054140d3d775ed1f68a6a7609ee6bc270d9b7799815729841d2855647769b81b4a48ccd9477f4f67a65220a9c2abee7e6584f0dc9573e83332669c5b220d273b102aca23210284461cd448237a0c814590e1254497e0ea94af494345ec33ea43488f841869a2ac41407bea3cd966a230860f435fe2521ac69c270a6a7eac476715052a8b5a33ab96b28db2f4a2b9654529d4fb64d01a4d6d860c86e4343ec2acb57e11d2bca63ca2cb232102b38872a74b5e1dc743f6da7c2cced255549790f7674bc7e46497954160f8247eac4140ee6556f7bdc3bc989abcdac5984f04e1086642099c54eeeb4211a2b13ada10dbb1a72aba85619187f21b2a5cfa5513ccf83b98f8b457d7bc63a00bb99aa4a81223210281c10f9e42a8c7f2e49b8b24403a519a6094afd3da6a38ee50ee7b0cc834d51aac4140ab0f4f5fb1d97db3572571ee0355eb7512191393bfb7212e23096600f02925579331de6f37018b5bace764abeffe918122b2ef09a3aacc93ff76df7ed5841d1923210248eb66f6d029d3fda42d894d19098cbde32fc7017f1dd7a95972e6aa87c544a0ac4140c02e349cb045b0782247c53cf39f8db435547395bb89de5f601ce6441f9d96f71f2fb175519458bd5df6814d98e18d3a8122adadd2a939a280c4ff3582853755232103e931de58e28b4e431a30e3e1f5258d7a7879065aa589b0357e80905fac07f0cfac
```
调用返回结果:
```
{
    "jsonrpc": "2.0",
    "id": "1",
    "error": {
        "code": -504,
        "message": "Block or transaction validation failed."
    }
}
```

**Comment by steven1227** [comment]
Describe the question in english preferred. How do you generate this Signature/verificationScript?

**Comment by LeorCao** [comment]
> Describe the question in english preferred. How do you generate this Signature/verificationScript?

I refer to the documentation for use 0x21+public key+0xac

**Comment by Tommo-L** [comment]
Hi @LeorCao How did you generate the signature?  You'd better to use the five addresses to sign the the following transaction.

```
{
  Transaction: {
    Type: 80,
    version: 0,
    Attribute: [
      
    ],
    Vout: [
      {
        asset: 9b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5,
        value: 0012c2e801000000,
        address: e7082a5ca5f673a1c4210b3c69ef29c04f8a25cc
      }
    ],
    Vins: [
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0900
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0600
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0000
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0700
      },
      {
        txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
        vout: 0800
      }
    ]
  }
```

**Comment by LeorCao** [comment]
> Hi @LeorCao How did you generate the signature? You'd better to use the five addresses to sign the following transaction.
> 
> ```
> {
>   Transaction: {
>     Type: 80,
>     version: 0,
>     Attribute: [
>       
>     ],
>     Vout: [
>       {
>         asset: 9b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5,
>         value: 0012c2e801000000,
>         address: e7082a5ca5f673a1c4210b3c69ef29c04f8a25cc
>       }
>     ],
>     Vins: [
>       {
>         txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
>         vout: 0900
>       },
>       {
>         txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
>         vout: 0600
>       },
>       {
>         txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
>         vout: 0000
>       },
>       {
>         txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
>         vout: 0700
>       },
>       {
>         txId: 5d159e9503f61ef14ab466351cad14f6e55588c6ac9143f177698aa4bad040ca,
>         vout: 0800
>       }
>     ]
>   }
> ```

**Comment by LeorCao** [comment]
Hi @Tommo-L , I am sure that I signed the transactions using the private keys corresponding to these five public keys, and then generated one-to-one verification script pairs. My signature process is: Sha256 the transaction subject information once, and then use the private key to sign the result with ECC_CURVE_SECP256R1

**Comment by LeorCao** [comment]
@Tommo-L  Serialization assembly process for multiple transaction inputs
tx type +
version +
attribute count + attribute content +
tx input count + [txid + vout + repeat every one] +
tx output count + [asset + address + value + repeat every one] +
script count + [invocation = ((signture length + 1) + PUSHBYTES64 + sigenture) + verification = ((public key length + 2) + PUSHBYTES33 + publick key + CHECKSIG) + repeat every one]

like this : 80000005be78dfcebb6b9c9a181102ac38f55360dbf96b2da1c384167cdcb9da843175050300be78dfcebb6b9c9a181102ac38f55360dbf96b2da1c384167cdcb9da843175050000be78dfcebb6b9c9a181102ac38f55360dbf96b2da1c384167cdcb9da843175050100be78dfcebb6b9c9a181102ac38f55360dbf96b2da1c384167cdcb9da843175050200be78dfcebb6b9c9a181102ac38f55360dbf96b2da1c384167cdcb9da843175050400019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc500a6f75f02000000cafedfa47d885786f24808352544807231cb0e29054140853cb0f792ef8a4b6dc271550fbfdf0107d0c3ebb2ee8d0693ac21f5f33f1ae2744dd0f4695c79310ef8b5f8dbfddc3e30bf1746b0cc4301c08de3643de1ebca23210219f555af4ef5d17f342377d1734e5fdca3ff1051c78e50b2dde6bc3861202d10ac4140f103c472bca4cabbf5fd7f21e36c9048ac685fcc331ff9bb3391230c2d4ad4b036b789d8fed6637eaf2804bcea5854300bd7d9659459e2cbca0f24ed41e8beb7232102a8f9dbdf77141f3758f03b7c8907ac326c31b838a60ea402b4c5b78f14f628f7ac414028caf22f86f69e8b206f60709b00f1070e9b2eabbb2f65071fb96edcad526aa00287b259cbd96481cbe75880f2bd3ad9e1a3d2265460ff97f30ee5287ac1af12232103918a778cb157c3f18db22e60fc12282b35be924350e7d41ecaafd9bad55e8bccac4140f8b0631411a15772407be632c11c0f8c34caa86b6588c19da6c8fd3ada7ffd07b1f1689ea6d576e2a4298079c7abe7fc05f5805ad1a8ad807d55a1c61e773e6d232102004aa904d2273b4f9b8ebcf74399f65bf3cb61925b1779107fdfcd5b7aae3302ac414026df9e22018877745286be3345a0a1d9eec44c80d45708fe1d46690464dd3873ca3fde6cfeab3e9c09a9bea36c23f234c17ae41cf3c00604e9692d62f9d469d2232102d94fb99493d0e1cef18d0758be2db32abf90d5892878f25c890f9b07af5ae7d7ac

**Comment by Tommo-L** [comment]
> tx type +
version +
attribute count + attribute content +
tx input count + [txid + vout + repeat every one] +
tx output count + [asset + address + value + repeat every one] +
script count + [invocation = ((signture length + 1) + PUSHBYTES64 + sigenture) + verification = ((public key length + 2) + PUSHBYTES33 + publick key + CHECKSIG) + repeat every one]

This is right, I'll have a try in my local.

**Comment by Tommo-L** [comment]
@LeorCao It seems that there is no payment fee. By default, it is necessary to pay the fee when tx.s length more than 1024 bytes.

**Comment by LeorCao** [comment]
@Tommo-L Thanks, let my try.

**Comment by Tommo-L** [comment]
Hi @leor-w  How is going now? If it has been solved, could we close this issue?

**Comment by shargon** [comment]
It can be closed?

**Comment by Tommo-L** [comment]
hi, @leor-w we'll close this issue, if you encounter a new problem, you can reopen or open a new issue.

**Comment by leor-w** [comment]
@Tommo-L Sorry， i forgot. yes it's no problem, thanks
