### ISSUE TITLE
How do nodes communicate RPC server support

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1342]
I thought the idea of node [capabilities](https://github.com/neo-project/neo/blob/af2d82133c6f56cb5494187de660a8355bb0a9c4/src/neo/Network/P2P/Capabilities) was to be able to share with other nodes what services are available. When I look at the [NodeCapabilityType](https://github.com/neo-project/neo/blob/af2d82133c6f56cb5494187de660a8355bb0a9c4/src/neo/Network/P2P/Capabilities/NodeCapabilityType.cs) I don't see the often used RPC Server as a capability. 

Should this be added as a service type? I think sharing that through P2P would be beneficial for applications like network monitoring. They can then discover the information and list it on a website for easy consumption.

If it shouldn't be added, please explain not?

**Comment by Tommo-L** [comment]
I think this is not a very safe practice by exposing RPC ports at the p2p layer.

**Comment by ixje** [comment]
Sharing of the RPC configuration can be made configurable and also the RPC server itself could use authentication if we are worried about unauthorized use. 

For NEO 2.x a common practice is;
- get node ip + port, commonly ip:10333
- do P2P.Port - 1 to get RPC port (10332) as most nodes don't change the default scheme

Right now https://github.com/neo-project/neo/issues/548 is actually _not_ solved. The base structure to solve it is there, but the actual solution is not.

**Comment by erikzhang** [comment]
> I thought the idea of node capabilities was to be able to share with other nodes what services are available.

It is for p2p protocol only.

**Comment by ixje** [comment]
then we should reopen #548 because that was closed with the argument that capabilities solves the issue.

**Comment by ShawnYun** [comment]
Maybe we can let the user choose whether to expose the RPC service

**Comment by ixje** [comment]
If using capabilities is not the right way, what would be the way to discover "non-p2p" services?

**Comment by Tommo-L** [comment]
@ixje  You are right, if we really need to add it, `capabilities` should be the most suitable place.  I hope it can become a configuration item, and the default is false -- not exposing those services. If possible, we will help implement the function. 
Anyway, thanks for your suggestion.

**Comment by ixje** [comment]
Anyone else got an opinion on the subject?

**Comment by shargon** [comment]
I think that we should implement it

**Comment by ixje** [comment]
Thanks shargon. @vncoelho @lock9 could you please share your views on this?

**Comment by ixje** [comment]
Why close? It is still a terrible developer experience in terms of finding a public RPC server and addressing this issue could solve that.

**Comment by ixje** [comment]
Thank you.
@shargon you previously (https://github.com/neo-project/neo/issues/1342#issuecomment-569402789) expressed we should implement this. Any chance you could look into it? The closer we get to TestNet release, the more relevant this gets as developers will want to find RPC nodes.

**Comment by erikzhang** [comment]
I think that exposing RPC service is an uncommon scenario. Most people open RPC services for their own use. And this may cause security issues. So I think if someone needs to open a public RPC server, they should do it through other channels.

**Comment by ixje** [comment]
I do not know of a single light wallet/SDK that does not rely on public RPC servers to get the data they need.

What security issues are you referring to? I'm only aware of the `openwallet` call, which nowadays is disabled by default.
