### ISSUE TITLE
Coveralls has been often failing

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1346]
![image](https://user-images.githubusercontent.com/17395762/70519138-3590c080-1b1a-11ea-9dae-57ce6fe2dc1c.png)

![image](https://user-images.githubusercontent.com/17395762/70519170-42adaf80-1b1a-11ea-9726-c58b2d1e9bd0.png)

**Comment by shargon** [comment]
It's possible to relaunch the test?

**Comment by vncoelho** [comment]
Usually, yes, @shargon, however, sometimes, it is with low probability of success.

**Comment by eryeer** [comment]
Seems the server is not stable at first look.

**Comment by vncoelho** [comment]
```yml
Run coverallsapp/github-action@master
Using lcov file: ./coverage/lcov.info
[error] "2020-01-09T10:42:37.082Z"  'error from getOptions'
##[error]Error: Command failed: git cat-file -p fcb65c3ef9887e78cb55a4c889acd7064d3ec04c
fatal: Not a valid object name fcb65c3ef9887e78cb55a4c889acd7064d3ec04c

##[error]Node run failed with exit code 1
```

**Comment by shargon** [comment]
I think that the github action is a little unstable

**Comment by Tommo-L** [comment]
Close?

**Comment by shargon** [comment]
I will close it, @vncoelho feel free to open it again if you have any trouble
