### ISSUE TITLE
where is  'libleveldb.dll' and 'sqlite3.dll '? 

### ISSUE THREAD

**Issue by Tiny-zhongwen** [neo-project/neo#135]
where is  'libleveldb.dll' and 'sqlite3.dll '? I can't find them.Please give me a complete link.thx!

**Comment by notatestuser** [comment]
They can be found in the neo-cli release package here: https://github.com/neo-project/neo-cli/releases

**Comment by Tiny-zhongwen** [comment]
I downloaded 'neo-cli-centos.7-x64.zip', but I still can't find them. Can I download it on the Internet? What version of it?

**Comment by erikzhang** [comment]
Use yum to install leveldb on centos:

```
yum install leveldb-devel
```

More instructions for installing neo-cli, see https://github.com/neo-project/neo-cli/issues/42
