### ISSUE TITLE
I was not able to generate blocks

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1359]
With only one CN and Memory store, I never received the Block in LocalNode

![image](https://user-images.githubusercontent.com/3167973/70528200-ec5a6400-1b4d-11ea-8379-aa4ba0dddc78.png)

I was able to ensure that the block was relayed here

![image](https://user-images.githubusercontent.com/3167973/70528232-04ca7e80-1b4e-11ea-8ae6-5da0131e0515.png)

But in  `LocalNode` I never receive the blocks here

![image](https://user-images.githubusercontent.com/3167973/70528253-101daa00-1b4e-11ea-972d-f4a343464f8d.png)

Could @superboyiii tell me if you have any problem with this?

**Comment by erikzhang** [comment]
Maybe DNS queries can consume a lot of time? We should set a timeout.
