### ISSUE TITLE
'CheckWitness'  executes failed during Nep5 Token transfer in Neo3

### ISSUE THREAD

**Issue by doubiliu** [neo-project/neo#1370]
**Describe the bug**
NGD try to complete the NEP5 Template contract in NEO3.In this process,we found the `transfer` method will execute failed when we try to transfer a Nep5 asset by invoking RPC method `sendtoaddress`.By testing, we found that the problem is in 'CheckWitness' method.

`CheckWitness` is a InteropService method.It provides protection for asset transfers
```c#
internal static bool CheckWitness(ApplicationEngine engine, UInt160 hash)
        {
            if (engine.ScriptContainer is Transaction tx)
            {
                Cosigner usage = tx.Cosigners.FirstOrDefault(p => p.Account.Equals(hash));
                if (usage is null) return false;
                if (usage.Scopes == WitnessScope.Global) return true;
                if (usage.Scopes.HasFlag(WitnessScope.CalledByEntry))
                {
                    if (engine.CallingScriptHash == engine.EntryScriptHash)
                        return true;
                }
                if (usage.Scopes.HasFlag(WitnessScope.CustomContracts))
                {
                    if (usage.AllowedContracts.Contains(engine.CurrentScriptHash))
                        return true;
                }
                if (usage.Scopes.HasFlag(WitnessScope.CustomGroups))
                {
                    var contract = engine.Snapshot.Contracts[engine.CallingScriptHash];
                    // check if current group is the required one
                    if (contract.Manifest.Groups.Select(p => p.PubKey).Intersect(usage.AllowedGroups).Any())
                        return true;
                }
                return false;
            }
            // only for non-Transaction types (Block, etc)
            var hashes_for_verifying = engine.ScriptContainer.GetScriptHashesForVerifying(engine.Snapshot);
            return hashes_for_verifying.Contains(hash);
        }
```

But when we try to transfer a Nep5 asset,we found it will execute failed.The bug logic happens in this part:
```c#
                if (usage.Scopes.HasFlag(WitnessScope.CalledByEntry))
                {
                    if (engine.CallingScriptHash == engine.EntryScriptHash)
                        return true;
                }
```
We found that if the asset is a global asset(NEO,GAS),`CallingScriptHash` is equal to `EntryScriptHash`.
But if the asset is a NEP5 asset,`CallingScriptHash` is not equal to `EntryScriptHash`.

The reason of this phenomenon is :
 When we transfer a NEP5 asset,there exists at least 3  invoke contexts  in  InvocationStack .So the value of `EntryScriptHash` is script hash of Tx script,but the value of `EntryScriptHash` is script hash of contract.And if the scope of tx is `CalledByEntry`,it will return false.

**Solution**
1. A simple way is change the code in `MakeTransaction` in Wallet.
   We can change the scope of tx to `Global`. Maybe it will have some security problem.
2. Another way is that we can create a new scope type for Nep5 asset.

**Comment by erikzhang** [comment]
It has been fixed by #1357.
