### ISSUE TITLE
neo is incompatible with latest neo-vm

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1373]
**Describe the bug**
Build fail for latest neo-cli and neo.

```
root@jessicaaliyun:~/Github/neo-node/neo-cli# dotnet publish -c Release
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 49.87 ms for /root/Github/neo/src/neo/neo.csproj.
  Restore completed in 49.98 ms for /root/Github/neo-node/neo-cli/neo-cli.csproj.
  neo -> /root/Github/neo/src/neo/bin/Release/netstandard2.1/Neo.dll
CLI/MainService.cs(394,72): error CS1061: 'IEnumerable<InteropDescriptor>' does not contain a definition for 'ContainsKey' and no accessible extension method 'ContainsKey' accepting a first argument of type 'IEnumerable<InteropDescriptor>' could be found (are you missing a using directive or an assembly reference?) [/root/Github/neo-node/neo-cli/neo-cli.csproj]
CLI/MainService.cs(411,47): error CS0117: 'InteropService' does not contain a definition for 'Neo_Contract_Create' [/root/Github/neo-node/neo-cli/neo-cli.csproj]
```
**To Reproduce**
1. Open the neo-node/neo-cli project
2. Add neo project
3. Add reference with neo.
4. Build. 

**Expected behavior**
Build success and publish success.

**Screenshots**
![4801576579142_ pic_hd](https://user-images.githubusercontent.com/34291844/70988333-9ad94880-20fc-11ea-9995-2df57cf5543c.jpg)

**Platform:**
 - OS:  Windows 10 x64
 - Version: neo #1362 (using Neo.VM.3.0.0-CI00190)
neo-cli (https://github.com/neo-project/neo-node/commit/689814ae245d4e6232b0a6905062fb124934a0a5)

**Comment by erikzhang** [comment]
Please do not post such issues. I have reiterated many times that the master branches of the projects are not mutually compatible.
