### ISSUE TITLE
Unable to apply for NEO&GAS on the TestNet

### ISSUE THREAD

**Issue by lovery** [neo-project/neo#138]
I'm not able to find how should I create a NEO Public key. I've created a wallet with your app for Linux and I get an address, encrypted key and private key, unfortunately non of those keys didn't match the form validation which is `data-val-regex-pattern="0[0-9|abcdef]{65}"`.
How should I generate a public key, which match the form validation?

**Comment by jonatanblockchain** [comment]
Did you try the command `list key` to get the pub key?
 http://docs.neo.org/en-us/node/cli.html

**Comment by lovery** [comment]
Thank you, this worked.

**Comment by Hunghus** [comment]
I want to get public key. I tried using the "list key" command, I got them. However, I want to find ways to get them from the program not with the command.
Help me!!
