### ISSUE TITLE
Code review on UInt256

### ISSUE THREAD

**Issue by MithrilMan** [neo-project/neo#1386]
I've a question about your UInt256 implementation
https://github.com/neo-project/neo/blob/c5a0f07e14465d8be3afbfc506db4b064899edd4/src/neo/UInt256.cs#L15-L33

how can you be sure that value2, value3 and value4 are always pinned and have always the same contiguous memory ?
From what I see you create a pointer to cover 32byte of memory starting from the address of value1 that's the only pinned value. Do you have any documentation that ensure that the memory will be allocated sequentially for your 4 allocated ulong variables on every platform?
I've tried different UInt256 implementation and this is one of the most performant constructor but I've doubts about the correctness, can you enlighten me?
thanks

**Comment by john-h-k** [comment]
Yeah, just add on `[StructLayout(LayoutKind.Sequential)]` to the class and this is immediately fixed. Also yes, the `[..Length]` is meaningless here
