### ISSUE TITLE
Problems with smart contracts

### ISSUE THREAD

**Issue by qcjxberin** [neo-project/neo#1398]
I am using version 2.10. The Domain contract was used for deployment and the deployment was successful, but when I called the method using neo-gui or rpc, I found that the stored data could not be obtained. Selective storage when the contract is deployed.

**Comment by shargon** [comment]
Hi @qcjxberin, How do you create the contract, with which flags?

**Comment by qcjxberin** [comment]
The official Domain Demo can enter the method when debugging the register using the Rpc test method, but the execution has no results

![image](https://user-images.githubusercontent.com/5792218/71766933-b3d95a80-2f40-11ea-8af1-a3cc48623923.png)

![image](https://user-images.githubusercontent.com/5792218/71766934-b76ce180-2f40-11ea-95f4-7c18e88162e0.png)

![image](https://user-images.githubusercontent.com/5792218/71766936-c5226700-2f40-11ea-9dc3-2ae413cd5497.png)

**Comment by qcjxberin** [comment]
I found the reason, it needs to be deployed, otherwise the data cannot be stored. In addition, I would like to ask if the contract is called directly in C #

**Comment by qcjxberin** [comment]
@shargon

**Comment by qcjxberin** [comment]
I have tested if there is a line of if (! Runtime.CheckWitness (owner)) return false;

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/71767285-c0ac7d00-2f45-11ea-827d-ee1b99bb48ec.png)
Is the public key of the specified wallet called in the circle above?

**Comment by Tommo-L** [comment]
> In addition, I would like to ask if the contract is called directly in C #

No, the contract will be executed by NeoVM.

> Is the public key of the specified wallet called in the circle above?

No, it'll not be called, but will check whether the transaction is signed by the specified address, when executed.

**Comment by qcjxberin** [comment]
@Tommo-L  Is there any demo code in C # for implementing contract methods through NeoVM? You can refer to this step. I really don't know how to proceed.

**Comment by Tommo-L** [comment]
I may not get your point.  Do you mean, you write a C# contract, and want to invoke the contract directly?
The current process like the following: 
1. write the contract and compile it to avm code,
2. store the contract on the chain through transaction, which will attach with the avm code. If the transaction was packaged in the block, it'll be executed and storage the contract.
3. and then send a new InvokeTransaction to call the contract, then go to step 2, it will execute the tx.sript, which contains the invoke script.

more details about transaction: https://docs.neo.org/docs/zh-cn/tooldev/transaction/tx_execution.html

**Comment by qcjxberin** [comment]
Your understanding is correct, this will help me

**Comment by Tommo-L** [comment]
@qcjxberin thanks, if this have solved it, could you close the issue.  
And if you encounter some new problems when use neo, you can open a new issue at any time.
