### ISSUE TITLE
Successfully deploy nep5 contract based on latest master branch, but fail on Neo.Wallet.MakeTransaction()

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1409]
**Describe the bug**
Successfully deploy nep5 contract based on latest master branch, but transaction fail on Neo.Wallet.MakeTransaction().

**To Reproduce**
1. Deploy an nep-5 contract based on [lightszero' PR](https://github.com/neo-project/neo-devpack-dotnet/pull/182).
2. Invoke `deploy` method on neo-cli.
3. Make transaction of this Nep-5 from owner address to another address.

**Expected behavior**
`error: Value does not fall within the expected range.`

**Screenshots**
Invoke totalSupply returns the current value.
![image](https://user-images.githubusercontent.com/38493437/72242049-5ff70180-3623-11ea-8028-74d8941cffe8.png)
You can find both `invoke function(balance)` and `getapplicationlog` executed successfully.
![image](https://user-images.githubusercontent.com/38493437/72242086-769d5880-3623-11ea-9b59-11bd7dd3af98.png)
![image](https://user-images.githubusercontent.com/38493437/72242277-fa574500-3623-11ea-8f43-4c449de8b4c6.png)
But making transaction failed here.
![image](https://user-images.githubusercontent.com/38493437/72242289-017e5300-3624-11ea-8932-7ef885ba0131.png)

Data converted:
![image](https://user-images.githubusercontent.com/38493437/72242514-a0a34a80-3624-11ea-8180-0b839e75a644.png)

**Platform:**
 - OS: [Windows 10 x64, ubuntu 16.04]
 - Version [All latest master & lightszero's PR]

**Comment by vncoelho** [comment]
Such a supper job, @superboyiii.
Nice advances.

**Comment by Tommo-L** [comment]
Linked to this https://github.com/neo-project/neo-vm/pull/279#issuecomment-573603050
