### ISSUE TITLE
Smart contract new feature needed: should enable transforming public key to address/script hash, transforming between address and scripthash in smart contract

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1411]
When writing smart contract I found a feature transforming public key to address in need. This is not hard to develop, and might be widely needed.

Futhermore, we should also add functions into smart contract like transforming between address & scripthash, public key to script hash, etc.

**Comment by shargon** [comment]
Maybe it's better with syscalls, what do you think @erikzhang?

**Comment by Tommo-L** [comment]
Agree, I think we can add this `Neo.Helper.Converter`.

**Comment by erikzhang** [comment]
Why do you need to do it in a contract?

**Comment by Qiao-Jin** [comment]
> Why do you need to do it in a contract?

In yy case it is due to a matter of verification. Given public key, corresponding signature and address, I need to check whether this signature is produced by the public key corresponding to the given address.
