### ISSUE TITLE
Как включить оперативную(JIT)отладку

### ISSUE THREAD

**Issue by denniss-mishchuk** [neo-project/neo#143]
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Neo.Implementations.Wallets.NEP6.NEP6Wallet..ctor(String path, String name)
   в Neo.UI.MainForm.打开钱包数据库OToolStripMenuItem_Click(Object sender, EventArgs e)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
neo-gui
    Версия сборки: 2.5.6557.29435
    Версия Win32: 2.5.6557.29435
    CodeBase: file:///E:/neo/NEO-GUI/neo-gui.exe
----------------------------------------
System.Xml.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Neo
    Версия сборки: 2.5.2.0
    Версия Win32: 2.5.2.0
    CodeBase: file:///E:/neo/NEO-GUI/Neo.DLL
----------------------------------------
Neo.VM
    Версия сборки: 2.0.4.0
    Версия Win32: 2.0.4.0
    CodeBase: file:///E:/neo/NEO-GUI/Neo.VM.DLL
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Configuration.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Configuration.DLL
----------------------------------------
netstandard
    Версия сборки: 2.0.0.0
    Версия Win32: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Configuration.Json.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.FileProviders.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Configuration.FileExtensions.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.FileProviders.Physical.DLL
----------------------------------------
Microsoft.Extensions.Primitives
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Primitives.DLL
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.FileSystemGlobbing.DLL
----------------------------------------
Newtonsoft.Json
    Версия сборки: 10.0.0.0
    Версия Win32: 10.0.1.20720
    CodeBase: file:///E:/neo/NEO-GUI/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.IO.Compression
    Версия сборки: 4.2.0.0
    Версия Win32: 4.6.25908.02
    CodeBase: file:///E:/neo/NEO-GUI/System.IO.Compression.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Http.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Hosting.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Hosting.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.DependencyInjection.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.DLL
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Configuration.EnvironmentVariables.DLL
----------------------------------------
System.Net.Sockets
    Версия сборки: 4.2.0.0
    Версия Win32: 4.6.25908.02
    CodeBase: file:///E:/neo/NEO-GUI/System.Net.Sockets.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.DependencyInjection.DLL
----------------------------------------
Microsoft.AspNetCore.Http.Features
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Http.Features.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Версия сборки: 4.0.2.1
    Версия Win32: 4.6.25519.03
    CodeBase: file:///E:/neo/NEO-GUI/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
Microsoft.AspNetCore.Http
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Http.DLL
----------------------------------------
Microsoft.Extensions.Options
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Options.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.ObjectPool
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.ObjectPool.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.DLL
----------------------------------------
Microsoft.AspNetCore.Server.Kestrel.Core
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Server.Kestrel.Core.DLL
----------------------------------------
Microsoft.AspNetCore.Hosting.Server.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.Hosting.Server.Abstractions.DLL
----------------------------------------
Microsoft.Net.Http.Headers
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Net.Http.Headers.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Версия сборки: 4.0.3.0
    Версия Win32: 
    CodeBase: file:///E:/neo/NEO-GUI/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Версия сборки: 4.1.2.0
    Версия Win32: 4.6.25714.01
    CodeBase: file:///E:/neo/NEO-GUI/System.Runtime.DLL
----------------------------------------
Microsoft.AspNetCore.WebSockets
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.AspNetCore.WebSockets.DLL
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.17205
    CodeBase: file:///E:/neo/NEO-GUI/Microsoft.Extensions.Hosting.Abstractions.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Security
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Replicon.Cryptography.SCrypt
    Версия сборки: 1.1.6.13
    Версия Win32: 1.1.6.13
    CodeBase: file:///E:/neo/NEO-GUI/Replicon.Cryptography.SCrypt.DLL
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by almarax** [comment]
Неплохо бы вопрос по-английски сформулировать. А то даже мне непонятно в чем он.
К тому же в конце текста написано по-русски как это сделать:

> Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.
