### ISSUE TITLE
Allow to obtain the current tx

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1431]
**Summary or problem description**

Currently is not possible for the smart contract to know which TX is the invoker, in order to know (for example) the sender in `Mint` function.

**Do you have any solution you want to propose?**

`GetTransaction(null)` should return the current tx.

**Neo Version**
- Neo 3

**Comment by erikzhang** [comment]
`GetScriptContainer`?

**Comment by Tommo-L** [comment]
Close?
