### ISSUE TITLE
Pay transaction fee by unclaimed GAS

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1434]
**Summary or problem description**

Although in the latest Neo3 we have support for triggering Claim GAS operations automatically. However, when users only hold NEO, they still face the embarrassing scenario that they cannot transfer, as any transaction need GAS in Neo3.

**Do you have any solution you want to propose?**

After we have discussed( @dahongfei @vang1ong7ang @wangjiachao), we recommend adopting the consumption in advance, in the case of holding NEO, GAS that has not yet been claimed can be used to pay transaction fees when the GAS balance is insufficient. **However, this part of GAS cannot be transferred directly, it's needed to perform Claim operation**.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- SmartContract
- Wallets
- Mempool
- Transaction

**Comment by shargon** [comment]
It's a very good idea, maybe it's enough if verification take into account the unclaimed gas, and we distribute before burn.

**Comment by erikzhang** [comment]
It's meaningless if "no voting no GAS" is decided.

**Comment by Tommo-L** [comment]
I think it's impossible for "no voting no GAS". Maybe we should open a governance issue, could you @vang1ong7ang help open this issue.

**Comment by vncoelho** [comment]
This is an important feature and surely needed for a better usability of the system.
People should not really need GAS for performing a first transfer or some transfer sporadically.

We have been discussing that in some previous issue (@igormcoelho) and also here in Brazil with @vang1ong7ang.

I hope we can move to that.

@erikzhang, we also discussed about the need of those who vote to stake. @vang1ong7ang explained several game theories which we mostly agree with him, NEO holders should be responsible for their indication of CN.

**Comment by Tommo-L** [comment]
Since we have free transaction for NEO and voting, which will fix this issue.
