### ISSUE TITLE
GAS Not Sending out of NEON Wallet ** regardless of fees selected **

### ISSUE THREAD

**Issue by TechMagy** [neo-project/neo#1435]
Hello Team!

I've encountered what sounds like a similar issue with the Neon Wallet (v2.4.0) which sends NEO fine, however, GAS won't send. This is with all fee options tested. 

Test 1 - sending 10 GAS from NEON to Binance without a fee
![Test 1](https://user-images.githubusercontent.com/38993528/73581611-d9289c80-44dd-11ea-9827-8bf58284f46f.JPG)

Test 2 - sending 10 GAS from NEON to Binance with a 0.001 GAS fee (Fast)
![Test 2](https://user-images.githubusercontent.com/38993528/73581688-2a389080-44de-11ea-87d3-0969f1fd220c.JPG)

Test 3 - sending 10 GAS from NEON to Binance with a 0.05 GAS fee (Faster)
![Test 3](https://user-images.githubusercontent.com/38993528/73581775-84d1ec80-44de-11ea-943c-1a728fb2f5dd.JPG)

Test 4 - sending 10 GAS from NEON to Binance with a 0.1 GAS fee (Fastest)
![Test 4](https://user-images.githubusercontent.com/38993528/73581879-db3f2b00-44de-11ea-903e-458b8972021a.JPG)

In all cases there is the yellow banner to sign the transaction in the Neon Wallet (on Ledger Nano S with current firmware - v 1.6.0) which disappears before a message is shown on the Ledger device. This is the replaced by the error messages shown above.

The highest GAS amount that can be selected in the Neon Wallet is 0.1 GAS but the error is claiming that 0.18687 GAS is required. How do we overcome this blockage?

No records of attempted transactions show in the Activity section of the Neon Wallet. I've changed from 'automatic' network selection to manually selecting nodes.

On my Ledger Nano S I currently have ETH, NEO and BTC apps installed.

**Comment by steven1227** [comment]
@TechMagy Hi, looks like this is a question related to the Neon wallet. For the Neon wallet related issue, please post it in [Neon wallet](https://github.com/CityOfZion/neon-wallet/issues).

**Comment by TechMagy** [comment]
Posted to Neon Wallet thread as requested under https://github.com/CityOfZion/neon-wallet/issues/1937

Thank you @steven1227
