### ISSUE TITLE
[Governance] Design, Discussion and Implementation

### ISSUE THREAD

**Issue by SueNEO** [neo-project/neo#1436]
This issue describes the design of the governance mechanism on Neo3. The different tasks and sub-discussions will be moved to new issues for a better organization.

# 1. Intro

With Neo3 preview 1 released on 2019-09-16, we are one step further towards Neo3. Governance is important for blockchains especially for BFT based and PoS based blockchains because of the assumption of maximum byzantine failures. Governance is the mechanism to maintain such blockchains running sustainably. 

Neo is a BFT based blockchain. Some issues and problems are found through past few years’practice and it is the time to have a optimized governance model on Neo3. Actually governance model is highly related to consensus algorithm and economic model. We call them fundamental mechanism because they need to be discussed together. The design of new fundamental mechanism is proposed here. 

**Fundamental mechanism is redesigned to make it more secure and sustainable.**

It is a very dangerous signal that voting rate is pretty low in Neo2. Actually almost no one vote except Neo Foundation. Imagine if the voting rate drops to 5%, attackers can easily control the entire network with only 5% token at any time, and then break the fault assumptions, fork the blockchain and short Neo. Vitalik Buterin metioned the following on Devcon 5 of Ethereum.

> Whatever the cost of breaking a chain, you can just make a corresponding hedge on financial markets and get the money back by profiting from making the token price drop.

Why people don’t vote? Voting is a consumption activity. Benefits of becoming an informed voter often outweighed by the costs. Many believe that becoming informed is simply not worth the effort. Why spend the time to be informed when your single vote counts so little? More reasonable mechanism is designed in the new fundamental mechanism to avoid people falling into such dilemmas. 

There are three basic layers in the fundamental mechanism.   

- consensus

the mechanism based on BFT consensus algorithm to achieve overall system reliability in the presence of a number of faulty processes 

- governance

the mechanism to make group decisions on key parameters of consensus layer in a decentralized way

- incentive 

the mechanism to incentive good behaviors of Neo governance participants

It is recommended to separate the three layers into modules for better updating and optimization while implementing. We will not go into detail about the consensus mechanism here, and some optional optimizations will be listed while they are all unnecessary changes but may help Neo network run better.

# 2. Governance

[#1437](https://github.com/neo-project/neo/issues/1437)

# 3. Incentive 

[#1438](https://github.com/neo-project/neo/issues/1438)

# 4. Optional Optimizations

[#1439](https://github.com/neo-project/neo/issues/1439)

**Comment by JustinR1** [comment]
If gas becomes inflationary, and voting ends up locking up in native contracts, it may be possible not to close a voting round until a certain number of voting has occurred. Also, it’s probably possible to incentivize users who vote to reward a small amount of gas since it will indeed be inflationary. This would come from inflationary gas, rather than the original 100m gas. (If that makes sense or even possible mathematically)

**Comment by JustinR1** [comment]
Also, not quite surely how if a small number of people vote it would break anything? I guess I could see them having control over which consensus nodes will become the speaker but I’m not sure how that’s would break anything?

What will voting consist of? Will it be more than just consensus that neo holders vote for or will it also be policy? Or is that more off chain governance topics?
