### ISSUE TITLE
[Governance] Incentive

### ISSUE THREAD

**Issue by SueNEO** [neo-project/neo#1438]
Public permission-less blockchains are open and distributed systems with diverse groups of participants. A well-designed crypto-economics model is to provide incentives so that participants' pursuit of own economic interests leads to desired emergent behaviors in alignment with the protocol, to contribute to the blockchain network's success.

More specifically, the design of a crypto-economic system must provide answers to the following questions:

- How can the economic model ensure the security of the protocol?
- How can the economic model ensure long term sustainability of the protocol?
- How can the economic model align the objectives of different actors to grow the value of the protocol network?

Incentive layer is to solve such problems with a robust economic model.

## Incentive Abstraction

We can only use the token on neo to incentive participants because it is on-chain incentive. The input of incentive process are the balances of all accounts and a sequence of governance transactions while the output of incentive process are the new balances of all accounts. The changes of each balance reflect what we incentive for.

![image](https://user-images.githubusercontent.com/43411424/73907835-b7b32080-48e2-11ea-9246-db81453b662c.png)

## Incentive Metrics

The following metrics are used to make comparasions between incentive solutions.

1. correctness on rational assumption
2. complexity

## Incentive Solution

The solution of incentive layer will be proposed in the following sections.

Incentive layer consists of two parts:

1. income
   
   where the system income and how to get the income

2. redistribution

   how to redistribute the system income to incentive good behaviour and make the network sustainable

### Token Model

The dual token model (a.k.a NEO and GAS) is one of the distinctive features of Neo. Divisible NEO is proposed as an optional optimization in [#1439](https://github.com/neo-project/neo/issues/1439).

> NEO is governing token. NEO holders can take part in Neo network management, including voting for consensus nodes, network parameter modification, etc. NEO's total amount is 100 million. Its minimum unit is 1 and can not be divided. It's registered in Genesis block, and stored in standby validators' muti-signature addresses.

> GAS is utility token, or network fuel token. Operation costs and incentive for consensus node in Neo network are paid in GAS. GAS's total amount is also 100 million and can be divided to 0.00000001 unit. Gas is registered in Genesis block and issued afterwards as block incentive for NEO holders.

> Some transactions on the Neo network require fees. The network uses a fee structure with two types of fees; system fees and network fees. All fees are paid in the native utility token GAS

> | Type        | Description                                          |
> | ----------- | ---------------------------------------------------- |
> | Network Fee | Fee to pay the validator for including the transaction in the block       |
> | System Fee  | Fixed fee to pay the network for operations |

It is hard to say the dual token model of Neo is totally better than single token models like Ethereum and EOS, but we believe the dual token model has its unique advantages.

Actually mixing utility token and governance token is a dangerous way and it limits the maximum activity of the network. There is a competition of occupancy rate between utility token and governance token in single token model and governance token is related to security and utility token is related to activity. In other words, the network will be in danger and easily to be attacked if the network is popular enough because the more utility token, the less governance token.

### Inflation

We recommend to keep the way of GAS inflation (we treat the GAS release is actually a kind of inflation) on Neo2 as a respect to supply model of NEO and GAS because it would works well in the foreseeable short term (There is no inflation for NEO in our dual token model). 

> 100 million GAS is issued gradually in 22 years according to a attenuation algorithm. No GAS is issued afterwards.

### System Income

System income comes from GAS inflation and transaction fees on Neo network.

![image](https://user-images.githubusercontent.com/43411424/73907920-ffd24300-48e2-11ea-8fb1-7090841edfdb.png)

Transaction fee consists of system fee and network fee.

![image](https://user-images.githubusercontent.com/43411424/73907971-255f4c80-48e3-11ea-8039-8f72a9157a2a.png)

### Redistribution

*Before reading this section, you need to know how Neo2 distribute the GAS while consensus per block. Actually in Neo2, system fee is distributed to all NEO holders, and network fee is given to the current speaker (one of the consensus nodes who propose the block).*

The system income will be redistributed to different roles on Neo network. We have the following equation to describe the rule of redistribution.

![image](https://user-images.githubusercontent.com/43411424/73908040-622b4380-48e3-11ea-8229-2e15be85e7a1.png)

We define the earning vector as the vector of earning expectations of all the roles in Neo network and we consider 3 roles in Neo network, which is, consensus nodes, voters and NEO holders. One can play multiple roles at the same time.

*Note that we are using earning expections instead of earnings because it is average earnings. We keep the mechanism in Neo2 to give a part of the transaction fee to the current speaker in each block instead of all the consensus nodes. So here we just calculate the earning expections because such part of transaction fee will be distributed to each consensus nodes almost equally in long run..*

![image](https://user-images.githubusercontent.com/43411424/73908066-71aa8c80-48e3-11ea-9e6b-849e074fc0dc.png)

We define the income vector as the vector of inflation and transaction fee.

![image](https://user-images.githubusercontent.com/43411424/73908077-7d964e80-48e3-11ea-996e-a5d3200edd22.png)

The redistribution matrix shows in the following in our solution.

![image](https://user-images.githubusercontent.com/43411424/73908098-8a1aa700-48e3-11ea-8689-20dee5344083.png)

We use the reserve rate to adjust the distributed GAS to the NEO holders. It is a number between 0 and 1. r = 0 means NEO holders never get GAS unless they participate in governance process while r = 1 means NEO holders never get additional GAS in governance process.

We recommend to choose the reserve rate as small as possile to incentive the voters, but better to make all NEO holders be able to vote or transfer their NEO in `90` days. In other words, if I have `1` NEO without GAS, I can have enough GAS for me to vote or transfer my NEO `90` days later. Then NEO holders don't need to buy additional GAS from elsewhere to participate in the governance process of Neo network.

We define a weight vector as following:

![image](https://user-images.githubusercontent.com/43411424/73908109-956dd280-48e3-11ea-87bd-d660ab632be4.png)

The following equation is satisfied.

![image](https://user-images.githubusercontent.com/43411424/73908120-9d2d7700-48e3-11ea-8b00-75bd471b867b.png)

**Comment by vncoelho** [comment]
Sounds good idea and reasoning, I remember this draws with @vang1ong7ang.

We just need to be aware about the current PR opened about burning system_fees, better to discus this first before merging. Otherwise we would need to revert that. #1430

**Comment by vang1ong7ang** [comment]
@vncoelho 

Do you remember we discussed the redistribution matrix in Ouro Preto? The matrix is used here to make the analysis of redistribution problem much easier.

**Comment by vncoelho** [comment]
I remember, @vang1ong7ang, very good job.
What are the plans for discussing this here and reaching a conclusion for guiding the next steps?

**Comment by Tommo-L** [comment]
> We just need to be aware about the current PR opened about burning system_fees, better to discus this first before merging. Otherwise we would need to revert that. #1430

@vncoelho  Agree.  We look forward to reaching a conclusion on incentives. Especially how we deal with network fee and system fee.
