### ISSUE TITLE
My Neo Tracker Wallet cannot claim GAS and send NEO to binance

### ISSUE THREAD

**Issue by juventusfc27** [neo-project/neo#144]
i posted my problem on reddit/NEO and NEO's telegram group but nobody could help me.
my apologies if this is the wrong place to ask.

my Neo Tracker Wallet cannot claim GAS and send NEO to binance, no matter how many times i tried and waited. i have 1 NEO and i understand that all transactions involving NEO are free.

my wallet address: AHgt5zqNwAFuZRs43pTE9wY94Ttf8KRmLs
Unclaimed: 0.00020436 GAS

**Comment by csggene3** [comment]
I checked your account on neotracker.io and saw that you had a claim go
through about 15 hours ago, it also looks like your 1 NEO is safe there and
your claimed GAS from today is there as well. The unclaimed GAS you are
attempting to retrieve now is also safe and tied to your wallet ID, so it
won't be lost or not received. GAS can be claimed every 5 minutes, but does
not have to be. You will not lose any of what you would have received.
There is wallet development going on right now as far as I can tell; there
was a similar issue yesterday or the day before but not to worry. Your
funds are safe. You may want to try and see if an updated version of the
wallet is available on github and try again. Hope this helps. Cheers. =)

**Comment by localhuman** [comment]
If you have not solved this problem yet, please open a ticket in the #support channel in discord:

https://discord.gg/CCFA7c

**Comment by logan99** [comment]
I am also having the same issue. Not able to claim GAS or send NEO. Anyone know what to do to solve the issue?

**Comment by markbasser** [comment]
NEO Tracker can not send money or request gas. Why do I get an unknown error many times? Please tell me.
