### ISSUE TITLE
Add Slack app for neo-project/neo, neo-project/neo-vm, and neo-project/docs

### ISSUE THREAD

**Issue by spencercorwin** [neo-project/neo#1440]
**Summary or problem description**
My colleagues and I at [`neo-one`](https://github.com/neo-one-suite/neo-one) are working hard to be ready for NEO 3.0. We would like to subscribe to what's happening in `neo-project` repos so we can be updated to all changes. But the only way to do that now is to "watch" the repo and get emails. We would prefer to get updates in a Slack channel, but can't right now without a maintainer adding the Slack app to each repository. This would be very helpful for us (@afragapane @danwbyrne @dicarlo2)

**Do you have any solution you want to propose?**
Please add the Slack app to these repositories: `neo-project/neo`, `neo-project/neo-vm`, `neo-project/docs`. I belive this link should take you to the correct page to install Slack: https://github.com/apps/slack/installations/new

You should see a screen like this:
<img width="571" alt="Screen Shot 2020-02-07 at 10 32 36 AM" src="https://user-images.githubusercontent.com/29364457/74055674-41bbc180-4995-11ea-8c5f-f2e5dce4915e.png">

Then click on "neo-project" and see a screen like this, where you can add the Slack app:
<img width="572" alt="Screen Shot 2020-02-07 at 10 32 55 AM" src="https://user-images.githubusercontent.com/29364457/74055697-539d6480-4995-11ea-8ca9-a7f19f707159.png">

Once you do this, anybody will be able to get updates for those repositories in Slack.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: GitHub

**Comment by Tommo-L** [comment]
@spencercorwin Good suggestion, this may need @erikzhang  to install it.

**Comment by shargon** [comment]
There are the same for discord?

**Comment by spencercorwin** [comment]
Thank you @Tommo-L. We would really appreciate it. It would be very helpful for us and possibly for many others. @shargon We use Slack internally for team communication and to keep up with notifications from our own repos.

**Comment by steven1227** [comment]
@spencercorwin I think the slackapp is good. But it has to be set to one specific Slack workspace, right? For instance, if you want to let NEO-ONE slack access the updates, there should be a person who has both operation authorities of github/neo-project and NEO-ONE slack to configure it.

**Comment by spencercorwin** [comment]
@steven1227 That's a valid point. But I believe that all that needs to be done is for the Slack app to be installed on a given GitHub repo. Then anyone can subscribe to it in their Slack workspace. You can test this by trying to subscribe to the `neo-one` repo. Just go to your Slack workspace, install the GitHub app (if it is not already installed), then type `/github subscribe neo-one-suite/neo-one` in a channel. It should then subscribe you to our repo and you'll know that it works.

**Comment by steven1227** [comment]
@spencercorwin Hi, Yep, just tried in my workspace and it works. Looks like I am still in the old school ..

**Comment by erikzhang** [comment]
Done.
