### ISSUE TITLE
Add Alias Service

### ISSUE THREAD

**Issue by doubiliu** [neo-project/neo#1450]
Thanks to @lock9 for speaking in issue #1179. I think we need to add a lightweight alias service in NEO3.It has been implemented in some other public chains and received by users.​ 

## What is alias service

Alias ​​service, which aims to replace random strings that are difficult for humans to remember, such as wallet addresses and smart contract hash, with short phrases, etc.

People no longer need to memorize addresses and hashes, as long as they know a word or a phrase or a custom alias such as an email address or domain name address, they can perform operations such as transferring money and calling contracts.

For example, use `doubi.wallet.huobi` instead of an account address of doubi.

## Advantage

   In NEO3, we also need the alias service, which is a basic service. Unlike the domain name resolution services provided by various DAPP project parties, the alias service has many additional advantages:

   1. Easy to use: You can call the interoperable API directly in the contract, without the need              
   to call the    smart contract interface of a third-party project.
   2. Low-level support: Low-level logic can be added, and the transfer address is     
   automatically mapped.
   3. Increase system income: increase the income of NEO holders.
   4. Lightweight: No additional domain name management logic and complex economic 
   model

## Application scenario

1) Account address alias

2) Contract address alias

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other:

**Comment by shargon** [comment]
This is not a Dapps?

**Comment by doubiliu** [comment]
It is not a Dapp.It is a servie or native contract.

**Comment by Tommo-L** [comment]
Could we add this service? @neo-project/core

**Comment by erikzhang** [comment]
I think this feature can be replaced by a native name service.

**Comment by Tommo-L** [comment]
We've considered NNS, but it's a little complicated, including domain trading(with domain-level) and economic models, and it's not recommended to implement them in native contracts. 

If we don't consider these, then the name service is the alias service and we can implement it quickly.

In addition, we can set up some naming conventions for users.

For dapp:
```
neo://xxx
xxx.xxxx.dapp
...
```

For account:
```
xxx.neo.wallet
xxx@xxx.xxx // email address
....
```

**Comment by shargon** [comment]
How do you will prevent the impersonation?

**Comment by Tommo-L** [comment]
Bind with NeoID later? 😄

**Comment by shargon** [comment]
Then we should finish neo ID first :P or be able to claim a created alias as yours

**Comment by doubiliu** [comment]
Well. Although the ID solution will take some time to discuss, I don't think it affects the implementation of the alias service too much. NGD designed a rough function definition and process implementation.The overall implementation can be divided into two processes. The basic functions are implemented first, and the extended functions are implemented after the ID is determined.

The scheme is as follows:

## Design goals
1. Provide address alias service
2. Provide contract alias service

## Detail

### Data Structure

Each alias in the system corresponds to an address (account address / contract address), and one address can correspond to multiple aliases.

Use <String alias, <UInt160 / UInt256 address, UInt256 owner>> to store the mapping between the alias and the account

![image](https://user-images.githubusercontent.com/42929757/78319778-75ccf080-759a-11ea-8e5a-f89e7db73c0d.png)

To prevent impersonation, an ID can be introduced to authenticate the alias.ID does not have a strong relationship with the alias, you need to use the address as an intermediate bridge

Use <UInt160 / UInt256 address, <String alias, byte [] [] id >> to store the authentication relationship of the alias

### Function Define

Name | Return type | Description
-- | -- | --
**Base Function** |   |  
findAliasByAddress（UInt160/UInt256 address） | List< string > | Find all aliases corresponding to the specified address
findAddressByAlias（String alias） | UInt160/UInt256 | Find address corresponding to the specified alias.
registerAlias（UInt160/UInt256 address，String alias） | true/false | Register a alias.
modifyAlias（UInt160/UInt256 address，String alias） | true/false | Modify the address of the alias (callable by the alias registrant)
deleteAlias（String alias） | true/false | Delete alias.(callable by the alias registrant)
**Extension function TBD** |   |  
isApproved（String alias） | true/false | Whether the alias is approved.
approveAlias（String alias，byte[] id） | true/false | Approve alias.(callable by the alias registrant)
getApproveInfo（String alias） | byte[ ] [ ] id | Get alias authentication information
removeApprove(String alias，byte[] id) | true/false | Remove alias authentication information.(callable by the alias registrant)

**Comment by erikzhang** [comment]
We plan to build a native domain name system in neo. I think the alias service conflicts with it.

**Comment by doubiliu** [comment]
Got it, we will design the domain name service directly
