### ISSUE TITLE
Make NEO transfers free

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#1452]
**Abstract**
Currently, if an address wants to obtain GAS, it must first make a NEO transfer. However, you must have GAS in the address before you can transfer NEO. This creates a contradiction. Although there are other ways to solve this problem, I think the most advantageous way is to make NEO's transfers free.

**Can it be attacked?**
It will not be attacked. The total amount of NEO is 100 million, and the smallest unit is 1. So there are at most 100 million NEO addresses in the network at the same time. The amount of data occupied by these addresses is only a few gigabyte at most, and I think this is acceptable.
The only problem may be GAS. Because GAS is generated after the transfer, and the minimum unit of GAS is 0.00000001. This may cause an attack. Therefore, we must stipulate that only voting NEO can get GAS rewards, and voting needs to lock NEO for a period of time.

**Advantages**
- Users do not need to purchase GAS before the first transfer, which improves convenience.
- It's easy to implement.

**Other improvements**
In addition, voting can be free too. Because the amount of data is similar. Moreover, since NEO will be locked for a period of time after voting, this makes it more difficult to be attacked.

**Comment by shargon** [comment]
I like it, but how do you want to do it? recycling gas or detecting the script pattern?

**Comment by Tommo-L** [comment]
> but how do you want to do it? recycling gas or detecting the script pattern?

Different transaction type like the oracle tx?


I think we can also set a `MaxFreeNeoTransferPerBlock` property in `PolicyContract`, and user can choose to pay a little fee for fast onchain.

**Comment by erikzhang** [comment]
It is very easy. Just modify this line.

https://github.com/neo-project/neo/blob/4ddca3eaea0ac039f349dcf2b782aa52253c9e72/src/neo/SmartContract/Native/Tokens/Nep5Token.cs#L163

**Comment by shargon** [comment]
But we need gas for the `Transaction.Size` and for the opcodes required to hit this native contract.

**Comment by erikzhang** [comment]
Another way is to create a new SYSCALL. `Neo.Native.Tokens.NEO.Transfer`.

**Comment by Tommo-L** [comment]
I recommend we can add `from`, `to` and `amount` fields for NEO free transfer.

**Comment by shargon** [comment]
> I recommend we can add from, to and amount fields for NEO free transfer.

In transactions?

For me the problem is that there are more checks before the execution, we need to ensure that he pay for the transaction.size, if we want to make free NEO transfers (i want) we need to identify that this is a NEO transfer.

**Comment by Tommo-L** [comment]
>In transactions?

Yes

I suggest he pay for the transaction.size( `= attrs.length + script.length + witnesses.length(except sender's)`)

**Comment by Tommo-L** [comment]
If possible, I hope we can add a constraint that each account has up to 10 free NEO transfer transactions. 

For voting, I suggest that there should still have a fee if we use governance committee mechanism.

**Comment by shargon** [comment]
I would like to have free tx independent of the execution. Maybe requiring a lock of your NEO of the amount of GAS it could be beneficial for users.

You want a free tx? then lock X neo during Y time

**Comment by erikzhang** [comment]
> You want a free tx? then lock X neo during Y time

That's why we have GAS.

**Comment by Tommo-L** [comment]
Another way, we can just create a FreeCallContract, and also use it as the `Tx.Sender`.  Then we don't have to nothing with transaction structure or syscall.

```c#
class FreeCallContract{
    verification(){
       // limit the number of free transactions per account.
    }
     transferNEO(from, to, amount){
         NEO.Contract.transfer(from, to, amount);
         NEO.Contract.Mint(fixedTransferFee, self)
     }
     vote(from, list){
         //....
         NEO.Contract.Mint(fixedVotingFee, self)
     }
}
```
And we can also limit the number of free transactions per account in this way.

**Comment by shargon** [comment]
You can call other contracts after this call
`
FreCallContract [args]
MyContract [method] [args]
`

**Comment by Tommo-L** [comment]
Don't worry, we will check whether the script is legal in `Verification` method,  and it can't be packaged in block unless this script is legal.

**Comment by shargon** [comment]
Like `IsMultiSigContract`?

https://github.com/neo-project/neo/blob/f26ac1be3b7ab421e8c88d03a72a42deacae3a05/src/neo/SmartContract/Helper.cs#L41

**Comment by Tommo-L** [comment]
Yes

**Comment by Tommo-L** [comment]
I hope we can keep the free transaction. When the user only has NEO without GAS, he can apply for the free transaction. We can limit one account to 3 free transactions.  And this approach will not affect our system revenue or increase network congestion, but it has greatly improved our user friendliness.

**Comment by shargon** [comment]
If the problem of free transactions is the spam, we will have this problem with any kind of free transactions, so for me, limit free tx only for transfer neo, only bring us problems, no benefits (Excepts the first transaction).

**Comment by Tommo-L** [comment]
Why spam? We can limit the GAS amount in `FreeContractCall` to limit the number of free transactions.

**Comment by Tommo-L** [comment]
Got your point, one can create a lot of new address to create  a lot of free txs.

**Comment by Tommo-L** [comment]
Maybe it's better to be solved at business layer, like [Uniswap](https://uniswap.io/) swaping NEO for GAS.

**Comment by erikzhang** [comment]
Currently, the transfer of neo will automatically modify the storage of the gas contract (to generate gas for the account). If we require users to explicitly claim gas, it can significantly reduce neo transfer fees.

**Comment by vncoelho** [comment]
In https://github.com/neo-project/neo/issues/1468 @igormcoelho talks about discounts when this automatically claim happens, then, we could allow cheap  transactions for NEP5 and others

**Comment by Tommo-L** [comment]
> only locked neo can generate gas

In a sense, hold is lock, but lock has one more display action.

**Comment by shargon** [comment]
What do you think in allow free tx for all kind of transactions.

- We currently order the mempool by fee, so if there are spam, they spam only affect free txs.
- We currently order the mempool by hash, so with a little pow, you can avoid this spam.
- We could configure the polic of the consensus, if they want to mine free transaction they can do it, if they don't want, it doesn't care, we will remove the free later, when other transactions bring to the mempool
- If a consensus node want to include X free transactions, it's ok, it will be ordered again by gas, so it will take the remaining space of the block, paid transactions are not affected.

So the idea is, create a local configuration for CN where they can choose if they want to serve or not free tx. If it's only one, free tx will be delayed, but I think that it's not a problem.

In fact, bitcoin and ethereum works like that, but with other consensus mechanism.

**Comment by Tommo-L** [comment]
> We could configure the polic of the consensus, if they want to mine free transaction they can do it, if they don't want, it doesn't care, we will remove the free later, when other transactions bring to the mempool

I think it's not good enough, it'll affect the performance of consensus nodes.

**Comment by Tommo-L** [comment]
> If the problem of free transactions is the spam, we will have this problem with any kind of free transactions

@shargon  I think we can solve this issue for `FreeCallContract`.  As we can set two limitations for the contract:
- limit the number of free transactions per account.
- limit the total GAS of this `FreeCallContract`, which is equivalent to limiting free transactions per block. (_Therefore, there will not be a large number of free transactions in the network, only a limited number of free transactions._)


Personally, I still hope we can support free transaction, and the solution is decoupled. We can disable the contract when we don't need free transaction.

**Comment by shargon** [comment]
Maybe the max fee for tree tx should be configured in the policy native contract in order to be able to disable it if there are spam :)

Limit the free tx to a syscall require the execution of this script in order to know the priority.

**Comment by Tommo-L** [comment]
> Maybe the max fee for tree tx should be configured in the policy native contract in order to be able to disable it if there are spam :)

Agree

> Limit the free tx to a syscall require the execution of this script in order to know the priority.

I think it's not necessary as it's already the low priority without extra network fee?  
Or don't need to execute the script, we'll have a special transaction version? Or identify the Sender?

**Comment by Tommo-L** [comment]
For me, maybe we need special transction version/type, which will also be used in oracle.

**Comment by Tommo-L** [comment]
> In #1468 @igormcoelho talks about discounts when this automatically claim happens, then, we could allow cheap transactions for NEP5 and others

For me, I like this proposal, as it makes business sense.
