### ISSUE TITLE
Add node health and security mechanism

### ISSUE THREAD

**Issue by ShawnYun** [neo-project/neo#1457]
**Summary or problem description**

Thanks to @Tommo-L @lock9 @shargon @vncoelho for the discussion in #1316 . Now we need to talk about adding node health and security mechanisms.

**Do you have any solution you want to propose?**

#### Node health

1. RTT(Request round trip time), indicating the time required from the Request to get the data. We can record the time each time you request a block and calculate the value of RTT after you receive the block.
Update RTT method: old RTT * old RTT coefficient (e.g. 0.9) + new RTT * new RTT coefficient (e.g. 0.1)

2. The number of Invalid blocks sent. It will be recorded every time the Invalid block is received. Set the maximum number to 3. Less than 3 times to reduce the weight. More than 3 direct disconnections.

3. The number of Timeout. It will be recorded after the timer detects Timeout. Set the maximum number to 5, Less than 5 times to reduce the weight. More than 5 direct disconnections.

4. The number of assigned tasks, 10 at most. And the more tasks, the lower the weight. Keep not sending too many tasks to the same node.

5. Weight calculation method:
![](https://user-images.githubusercontent.com/42930111/75526790-631c4480-5a4d-11ea-9b90-67fbb538e936.png)
Each time the node with the largest weight is selected from the nodes to assign a task.

#### Prevent sending large amounts of spam
To prevent malicious nodes from sending large amounts of spam to local node, we can add detection at RemoteNode. For example, every 1000 transactions received, the average speed of sending the transaction is calculated and the connection is disconnected if the threshold is exceeded.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by shargon** [comment]
I like it.

> To prevent malicious nodes from sending large amounts of spam to local node

Messages, not tx, right?

**Comment by ShawnYun** [comment]
@shargon In this issue, I mean tx. But maybe we can consider all the messages.

**Comment by shargon** [comment]
I think that you can spam not only with tx, requesting blocks or something like that.
