### ISSUE TITLE
Reduce the fee to a maximum of 20 GAS

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1459]
As we commented here https://github.com/neo-project/neo/pull/1430#issuecomment-593069755

If we reduce the Max fee to 20 of GAS, we can use integer instead of long.

Taking into account: 

- We can save 8 bytes in all transactions, 4 if we decide to join the fees.
- If we have plans to increate the decimals in the future, we should increase to long again

What do you think?

Draft: https://github.com/neo-project/neo/pull/1460

**Comment by vncoelho** [comment]
I agree with both.

**Comment by erikzhang** [comment]
I agree to reduce the max fee to 20 of GAS and use `int` instead of `long`.

**Comment by Tommo-L** [comment]
Agree.


> 4 if we decide to join the fees.

I think we can wait until the economic model is decided.

**Comment by shargon** [comment]
@Tommo-L do you think that it's a good change after study the cost of Defi?

**Comment by erikzhang** [comment]
I think it's good because the price of each opcode is much lower in neo3 then neo2.

**Comment by erikzhang** [comment]
I think it's good because the price of each opcode is much lower in neo3 then neo2.
