### ISSUE TITLE
Neo transaction stuck in block chain

### ISSUE THREAD

**Issue by ravi6098** [neo-project/neo#146]
Sir, I sent noe from binance to neo Wallet but didn't receive..
I have made two transactions details of which are given below.
1st..
Address - AbJ31CWbf1cGCrc919LMPiRgRLHC3oLCL3
Txid - e7e170c0be413f0412f3d51708b29cbd2b6fd78102f5a8a4520e22bb3be7e956
2nd
Address - AWqjfCDcVRFqAJM8BZPpxaUJZmdVjGf29q
Txid - 48051c3ae9085df54b974f8c92d848d150d48d966f98fe5e9e08e17969d2cdd1

**Comment by ravi6098** [comment]
Please do sumthing

**Comment by ravi6098** [comment]
Why nobody is replying?

**Comment by canesin** [comment]
1 - has 10 NEO: https://neoscan.io/address/AbJ31CWbf1cGCrc919LMPiRgRLHC3oLCL3
2 - has 5 NEO: https://neoscan.io/address/AWqjfCDcVRFqAJM8BZPpxaUJZmdVjGf29q ..

**Comment by localhuman** [comment]
Please use the NEO discord #support channel for requests such as this:

https://discord.gg/CCFA7c
