### ISSUE TITLE
Maybe one node is down

### ISSUE THREAD

**Issue by i359** [neo-project/neo#1462]
![捕获](https://user-images.githubusercontent.com/43022140/75935624-b31a6180-5eba-11ea-9fae-ea1aff8b16c5.JPG)

**Comment by Tommo-L** [comment]
Fixed?

**Comment by i359** [comment]
Now it is OK, thanks!

![捕获](https://user-images.githubusercontent.com/43022140/76046971-51322880-5f9c-11ea-9b1a-9fff5d6f51c5.JPG)

**Comment by i359** [comment]
Now  maybe one node is down for testnet neo 3.0, block time is abnormal every 7 blocks.

![111](https://user-images.githubusercontent.com/43022140/76143005-1c15fb00-60ae-11ea-9d59-b19e0a9cc782.JPG)

Data from https://neoscan-testnet.io/blocks/1

**Comment by i359** [comment]
There are problems again，block time is abnormal every 7 blocks.
![捕获](https://user-images.githubusercontent.com/43022140/76275183-9b2d4e00-62bd-11ea-87a9-8431e30f73f6.JPG)

**Comment by Tommo-L** [comment]
Thanks, @i359 
We're investigating.

**Comment by shargon** [comment]
Missclick, sorry

**Comment by Tommo-L** [comment]
@i359  Fixed, one cn node offline, and now it has been restarted. Thank you for your discovery.

**Comment by i359** [comment]
![捕获](https://user-images.githubusercontent.com/43022140/76739825-bf9a9600-67a7-11ea-93b0-ef24b9f08a59.JPG)

**Comment by Tommo-L** [comment]
OMG!

**Comment by Tommo-L** [comment]
It was repaired last night.

**Comment by i359** [comment]
![捕获](https://user-images.githubusercontent.com/43022140/76858617-c225ea00-6892-11ea-85f0-f1fbdad7e538.JPG)

**Comment by Tommo-L** [comment]
Got, we'll fix it.

**Comment by shargon** [comment]
@Tommo-L Always it's the same ?

**Comment by Tommo-L** [comment]
No, different nodes.

**Comment by Tommo-L** [comment]
Maybe we need more detial log and better monitor, we'll do it in Q2.

**Comment by i359** [comment]
It looks like March blocks is unstable.

![捕获](https://user-images.githubusercontent.com/43022140/76862960-cdc8df00-6899-11ea-94f3-e8ca5d24634c.JPG)

**Comment by Tommo-L** [comment]
Yes. Several nodes' memory are full, all restart now.

**Comment by shargon** [comment]
Please feel free to reopen if you consider it
