### ISSUE TITLE
Ship Neo 3 Preview 2

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1467]
As per discussion among core developers, we should focus on shipping the next preview of Neo3 to unblock neo3 developers.

cc @vncoelho @belane to add a list of PRs needed to merge before the preview release

**Comment by vncoelho** [comment]
https://github.com/neo-project/neo-node/pull/545

**Comment by vncoelho** [comment]
@shargon, can we merge https://github.com/neo-project/neo-node/pull/536 and implement the other features later?

**Comment by superboyiii** [comment]
@vncoelho https://github.com/neo-project/neo-node/pull/545 and https://github.com/neo-project/neo-node/pull/536 both contains checkwitness support, since https://github.com/neo-project/neo-node/pull/536 will be applied on cli, https://github.com/neo-project/neo-node/pull/536 is enough.

**Comment by Tommo-L** [comment]
https://github.com/neo-project/neo-modules/pull/181

**Comment by Tommo-L** [comment]
https://github.com/neo-project/neo-devpack-dotnet/pull/187

**Comment by Tommo-L** [comment]
I think the following PRs are need.
- [ ] Refactor node commands https://github.com/neo-project/neo-node/pull/536
- [ ] fix balance not change for non-transfer tx  https://github.com/neo-project/neo-modules/pull/181
- [ ] NEP5 Template for NEO3 https://github.com/neo-project/neo-devpack-dotnet/pull/187
- [ ] Add Type Convert(it can fix null problem) https://github.com/neo-project/neo-devpack-dotnet/pull/196

These are optional
- [ ] Add try catch  https://github.com/neo-project/neo-vm/pull/294
- [ ] add trycatch support https://github.com/neo-project/neo-devpack-dotnet/pull/186
- [ ] Completion of Storage Payback https://github.com/neo-project/neo/pull/1441
- [ ] GetBlocks by block index https://github.com/neo-project/neo/pull/1397

**Comment by shargon** [comment]
Agree with @Tommo-L

**Comment by belane** [comment]
> * [ ] Refactor node commands [neo-project/neo-node#536](https://github.com/neo-project/neo-node/pull/536)
> * [ ]  Add try catch  [neo-project/neo-vm#294](https://github.com/neo-project/neo-vm/pull/294)
> * [ ]  add trycatch support [neo-project/neo-devpack-dotnet#186](https://github.com/neo-project/neo-devpack-dotnet/pull/186)
> * [ ]  Completion of Storage Payback #1441
> * [ ]  GetBlocks by block index #1397

I think these are not really needed, we should keep the minimal changes to publish release. If we wait for changes like "Completion of Storage Payback" it will take much longer.

**Comment by Tommo-L** [comment]
We need neo-project/neo-node#536, as we need to support cosigner for contract invocation.

**Comment by Tommo-L** [comment]
Could help tag preview-2 for neo, neo-vm repositories, since they are ready, then we can push the lastest PRs in these repositories.

**Comment by devhawk** [comment]
FYI, I think [neo-modules issue 216](https://github.com/neo-project/neo-modules/issues/216) MUST be fixed for preview 2. As far as I can tell, sendRawTransaction is completely broken (though maybe there's a usage pattern that has changed).

**Comment by Tommo-L** [comment]
Close? as we have released neo3-preview2 successfully.
