### ISSUE TITLE
Func StorageMap.Put(string, byte[]) does not support long keys

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1472]
**Describe the bug**
Smart contract func StorageMap.Put(string, byte[]) does not support long keys.

**To Reproduce**
StorageMap issuerTrustList = Storage.CurrentContext.CreateMap("did:neoid:priv:fcf80c479b47b55aaf6383aaa2382ae9d9a67603");
Then call func StorageMap.Put with string "TestSchema-1584086402483" as input key. VM will end up with fault state.

**Comment by shargon** [comment]
We limit the Key to 64 bytes

https://github.com/neo-project/neo/blob/154ef25397fa9081d8a31d0a30ff2fb8a79637ac/src/neo/SmartContract/InteropService.Storage.cs#L15

https://github.com/neo-project/neo/blob/154ef25397fa9081d8a31d0a30ff2fb8a79637ac/src/neo/SmartContract/InteropService.Storage.cs#L34

And your sample has 65

![image](https://user-images.githubusercontent.com/3167973/76606065-e8096280-6511-11ea-86bd-86bb15a17ee9.png)

**Comment by Tommo-L** [comment]
64 is too small, change to 128 or 256?

**Comment by shargon** [comment]
I think that 256 it's reasonable. Please check this

https://github.com/neo-project/neo/compare/master...shargon-patch-1?quick_pull=1
