### ISSUE TITLE
dual token model enhancement

### ISSUE THREAD

**Issue by vang1ong7ang** [neo-project/neo#1477]
> However, the problem is that, the low demand of GAS makes GAS valueless, and easily been controlled in the market and exchanges by attackers. Currently there are not enough on-chain transactions which need a lot of GAS. Almost the only thing that a governance participant can to when it obtains a GAS is to sell it. Then, more want to sell it but less want to buy it. GAS becomes valueless. As a result, governance participants can not get enough reward if the price of GAS is too low.
> 
> In [this](https://github.com/vang1ong7ang/DualTokenModel) article, solution will be proposed to solve the GAS dilemma.

<https://github.com/vang1ong7ang/DualTokenModel>

-----

**NOTICE**

**Such dual token model enhancement never introduce any real benefit or performance improvement to neo network. It is only a game to make GAS holders benefit more and make the value of GAS sustainable.**

-----

**Comment by wulalablalbalba** [comment]
Very delicate tokeneconoy module

**Comment by Tommo-L** [comment]
Maybe let Caesar's be Caesar's, and god's be god's. GAS is just used as a payment token, NEO's gains come from the increased transaction volume.  🤣

**Comment by erikzhang** [comment]
It makes no sense that introducing a complex mechanism into the system but not produced any practical value. In my opinion this is more like a trick.

**Comment by vncoelho** [comment]
@erikzhang one of the points @vang1ong7ang  mentions is to incentive those who hold GAS. In fact, these are interesting things to consider.

We should improve the model in my opnion.
https://github.com/neo-project/neo/issues/1468

Lets merge the good points and move to a promissing model.

**Comment by erikzhang** [comment]
> to incentive those who hold GAS.

#1430 is going to incentive those who hold GAS.
