### ISSUE TITLE
Move transaction verification to RemoteNode

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1479]
**Summary or problem description**

Since we have removed parallel verification, after that it degrades our performance. As discussed earlier, we need to move transaction verification to RemoteNode for improving performance.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by shargon** [comment]
I think that we can have the same issues using different nodes.

**Comment by Tommo-L** [comment]
Maybe we should have a try?
