### ISSUE TITLE
Found bug in Contract_Update/Contract_Destroy

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1482]
**Describe the bug**
https://github.com/neo-project/neo/blob/be8ff9916a03eac81f0d40285cc3b19f0bb6dfcd/src/neo/SmartContract/InteropService.Contract.cs#L83-L84

https://github.com/neo-project/neo/blob/be8ff9916a03eac81f0d40285cc3b19f0bb6dfcd/src/neo/SmartContract/InteropService.Contract.cs#L95-L98

Since we use contract.id as prefix key, it should replace here in contract.update and contract.destory.

**Comment by Tommo-L** [comment]
@doubiliu will help fix it.

**Comment by doubiliu** [comment]
Got it
