### ISSUE TITLE
Found bug in UT_ProtocolSettings

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1484]
**Describe the bug**

UT_ProtocolSettings is not reliable and often executes failure on github action.

![image](https://user-images.githubusercontent.com/43396869/76832411-3ac18200-6864-11ea-8530-745e843ee8f1.png)

Here is [an example](https://github.com/neo-project/neo/pull/1483/checks?check_run_id=513067880)

**Platform:**
 - Github Action

**Comment by Tommo-L** [comment]
Still exists 

![image](https://user-images.githubusercontent.com/43396869/80050369-f2bf0a80-8547-11ea-97d2-f92da0b7c990.png)

 https://github.com/neo-project/neo/pull/1593/checks?check_run_id=607609321

**Comment by devhawk** [comment]
ProtocolSettings.Initialize tests cannot be run in parallel w/ tests that implicitly initialize ProtocolSettings.Default. More details here: https://github.com/neo-project/neo/pull/1616#issuecomment-620060574
