### ISSUE TITLE
RPC Command For GetClaims

### ISSUE THREAD

**Issue by saltyskip** [neo-project/neo#149]
Problem: Currently light wallets are relying on CoZ API in order to make claims and transactions.

https://github.com/CityOfZion/neon-wallet-db

The two methods in particular are getBalance and claims. Although this API works well, it's does not have as good as availability as necessary. Many issues related showing zero balance, being unable to make a claim, or being unable to send are related to this.

Solution: Have dedicated RPC command for getclaims and add the the UTXO set into the getaccountstate RPC command. Offloading this onto NEO nodes as opposed to hosting a central API should drastically decrease the number of issues related to light wallet syncs.

This issue describes the specification for getclaims

getclaims specification request body
```
{
  "jsonrpc": "2.0",
  "method": "getclaims",
  "params": ["AdWDaCmhPmxgksr2iTVuGcLcncSouV6XGv"],
  "id": 1
}
```

getclaims response body
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "claims": [
             {
                 "claim": 23488,
                 "end": 285098,
                 "index": 0,
                 "start": 283630,
                 "sysfee": 0,
                 "txid": "f07c0e6a867c7545dd8afdb49c287b368dec8056414dc0eea43c79fa7451bd49",
                "value": 2
        },
        {
            "claim": 192,
            "end": 285116,
            "index": 0,
            "start": 285104,
           "sysfee": 0,
           "txid": "c18bc2f861645f17eeb1adac441b22b354fe9967745da90eb86247226e553ab2",
           "value": 2
        },
        {
            "claim": 1200,
            "end": 285229,
            "index": 0,
            "start": 285154,
            "sysfee": 0,
           "txid": "26512df25fd21c0b491c01de6e7f07f801230a7e8357f249618f2f92c9e9691a",
           "value": 2
        },
        {
            "claim": 48,
            "end": 285239,
            "index": 0,
            "start": 285236,
            "sysfee": 0,
            "txid": "fc5c7bd07e80d45f1bc48a4bbeac54f46d89cfb3b4c1c670122eb41a9b0e80e6",
            "value": 2
        }
    ],
    "past_claims": [],
    "total_claim": 24928
  }
}
```

**Comment by saltyskip** [comment]
@erikzhang can you confirm or deny whether 149 and 150 with those data structures would be accepted into NEO if built. Our team can build out these adjustments to the RPC calls if that is the case

**Comment by erikzhang** [comment]
I will build a set of plugin APIs to make it be a CLI plugin. #164

**Comment by erikzhang** [comment]
This can be implemented in a plugin now.
