### ISSUE TITLE
Do we still need to add native vote contract?

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1492]
**Q1: Do we need a vote contract as a service?**
For me, I think we need.

**Q2: Do we need to add a native vote contract?**
I don't think it is necessary to add. One reason is that the committee's voting doesn't use it, but rather other dapps.

**Q3: If we need to vote on the contract, how to implement it?**
Since we already have PR #1089 , we can complete it later. However, it contains two methods: single vote model and sequence vote model(schulze method), and the [schulze method](https://en.wikipedia.org/wiki/Schulze_method) is too time consuming(time complexity is O(n^3)) and  not commonly used, so I hope we can remove the schulze method.

What do you think?

**Comment by shargon** [comment]
I vote for **Q1**. It could be used as a library for other SC in order to delegate the voting process.

**Comment by Tommo-L** [comment]
Okay, I think we'd better move to contract, we'll close #1089
