### ISSUE TITLE
Support changing password for Nep6 wallet

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo#1497]
**Summary or problem description**
Currently, neo does not support changing password for nep6 wallet. So wallets or other projects do not have any options other than implementing it by themselves. 

**Do you have any solution you want to propose?**
Considering change password is a common use case, could we add this feature to neo ?

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Wallets

**Comment by Tommo-L** [comment]
the same as #1489
