### ISSUE TITLE
Add UTXO set to getAccountState RPC

### ISSUE THREAD

**Issue by saltyskip** [neo-project/neo#150]
This is a follow up to #149, in order to easily build out a transaction a UTXO set should be included in the getaccountstate. An alternative solution is to have a separate RPC command for the UTXO set. I propose adding the set to getaccountstate RPC below

getaccountState is updated with the UTXO set

```
{
  "jsonrpc": "2.0",
  "method": "getaccountstate",
  "params": ["AJBENSwajTzQtwyJFkiJSv7MAaaMc7DsRz"],
  "id": 1
}
```

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "version": 0,
        "script_hash": "1179716da2e9523d153a35fb3ad10c561b1e5b1a",
        "frozen": false,
        "votes": [],
        "balances": [
            {
                "asset": "c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
                "value": "94",
                "unspent": [
                    {
                        "index": 1,
                        "txid": "9d3658842eb6e61f0913f28689f7977d48e931005c92fde4664dcdde8ea5a745",
                        "value": 7
                    },
                    {
                        "index": 1,
                        "txid": "d999592d08d6059da23f9ec743574e9cf00d1411c187c96869dfd32decf79a2f",
                        "value": 46
                   },
                   {
                        "index": 0,
                         "txid": "e391f7bb82a746abb93232d260926fff45c6ade4975dcae2dbd0002f302bdb77",
                         "value": 1
                  },
                  ...
                 ]
            }
        ]
    }
}
```

**Comment by saltyskip** [comment]
If the majority of the network is using light clients to interact with the network isn't this important enough to add to the general seed RPC API?

There's a huge centralized bottle neck right now with everyone hitting neo-scan, or neon-wallet db in order to make transactions. 

I would suspect the vast majority of transactions are NEO require this  API in order to process. 

```
sendrawtransaction
```

via RPC is completely unuseable right now without relying on a third party service. This will certainly up the memory requirements of each node, but I would assume the majority of people are running on cloud providers anyway

**Comment by erikzhang** [comment]
This can be implemented in a plugin now.
