### ISSUE TITLE
Compare mempools and exchange the pending transactions between two nodes 

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1500]
**Summary or problem description**
If at any time the node disconnects 1 from the network (intentionally or not), and receives a transaction, it will remain in its memory pool permanently without being distributed to the network and consequently without being included in the chain. The node will never forward that transaction to new connections or reconnections from previous nodes. And it may lead that the user does not receive any alert either and cannot send the transaction again since it is already in the Memory Pool and the node will reject it and will not broadcast it to the network.

**Do you have any solution you want to propose?**
Nodes must periodically compare their mempools and exchange the pending transactions
they do not have in their pool.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Mempool

_original posted by @red4sec_

**Comment by shargon** [comment]
I think that we should use bloom filters in order to exchange the current mempool with new connections.

**Comment by roman-khimov** [comment]
Why a simple rebroadcast of old mempooled transactions (`BlocksTillRebroadcast`) doesn't solve this problem?
