### ISSUE TITLE
Add owner in Abi

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1501]
**Summary or problem description**

If we add the `owner` of the contract in the Abi, we can send all the neo and the contract gas to this address before updating or destroying.

**Neo Version**
- Neo 3

**Comment by erikzhang** [comment]
Can this be an argument of `Destroy`?

```c#
var owner;
Destroy(owner);
```

Or even we don't need to do that. The contract can transfer the assets to an address manually.

```c#
Neo.Transfer(amount, this.hash, owner);
this.Destroy();
```

**Comment by Tommo-L** [comment]
`Owner` can be used in other methods for developers, like NEP-5.

**Comment by erikzhang** [comment]
I think it should be implemented in contracts, not in the system layer.

**Comment by doubiliu** [comment]
`Destroyed ` service  is overloaded, and the user decides which one to use when using interoper service.If not set, the default owner is `sender`

**Comment by shargon** [comment]
Maybe we can add a parameter in destroy, for the account where i want to receive my NEO and GAS?

**Comment by doubiliu** [comment]
Ok, but it must have a default value, otherwise it will cause permanent loss of neo and gas

**Comment by shargon** [comment]
> Ok, but it must have a default value, otherwise it will cause permanent loss of neo and gas

It could be mandatory
