### ISSUE TITLE
When contract included code like var a = 12.AsSbyte(); it will throw exceptions when deploy contract:

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo#1505]
When contract included code like var a = 12.AsSbyte(); it will throw exceptions when deploy contract:

![image](https://user-images.githubusercontent.com/12728872/77383017-d69b4280-6dbc-11ea-8a50-aa34fb245a7e.png)

Same exceptions:
```
.AsByte() => OpCode:241 => System.FormatException: 'OpCode not found at 1804-f1'
.ToByte() => OpCode:57 => System.FormatException: 'OpCode not found at 3379-39'
.ToSbyte() => OpCode:57 => System.FormatException: 'OpCode not found at 3403-39'
```

_Originally posted by @ProDog in https://github.com/neo-project/neo-devpack-dotnet/issues/217#issuecomment-602983780_

**Comment by Tommo-L** [comment]
It's compiler bug, not neo-core, we should solve it in neo-devpack-dotnet.

**Comment by ProDog** [comment]
> It's compiler bug, not neo-core, we should solve it in neo-devpack-dotnet.

OK,I just thought that related to the OpCode.
