### ISSUE TITLE
GasLeft syscall

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1508]
**Summary or problem description**
Sometimes the project need to know how much gas left in order to do more things or not. Imagine that you need to fund a lot of addres, you can calculate how many address you can fund according to the gas provided.

**Do you have any solution you want to propose?**
Add `GasLeft` syscall

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- InteropServices

**Comment by vncoelho** [comment]
Makes sense.

**Comment by igormcoelho** [comment]
Very good idea @shargon ! Useful stuff. I think its important to return the value already deducing the GasLeft operation itself, otherwise we would never exactly know the value (every calculation counts!). Looking forward to see this implemented :+1:
