### ISSUE TITLE
What is the overview structure of those projects here

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#1510]
I am sorry to say this, but Neo is really too hard to get started. Too many projects and too less description on the relationship between them.  What is Neo, Neo-node, Neo-express, Neo-vm, Neo-modules, Neo-compiler? Ok, I can guess their functions by names, but how do they interact with each other? If I want to setup a Neo node, which one should I run? I mean, you might need an overview structure of your projects to tell developers where to start.

Just a suggestion from someone who has searched for few hours and still has no clue.

**Comment by Tommo-L** [comment]
Hi @Liaojinghui , more of our documents are on the official website:

[How to write a smart contract](https://docs.neo.org/docs/en-us/sc/gettingstarted/introduction.html)
[How to deploy a neo node](https://docs.neo.org/docs/en-us/node/gui/install.html)

Thanks for your suggestion, we will organize the documents on github.

**Comment by Liaojinghui** [comment]
> Hi @Liaojinghui , more of our documents are on the official website:
> 
> [How to write a smart contract](https://docs.neo.org/docs/en-us/sc/gettingstarted/introduction.html)
> [How to deploy a neo node](https://docs.neo.org/docs/en-us/node/gui/install.html)
> 
> Thanks for your suggestion, we will organize the documents on github.

Thanks for your replying. However, I am not talking about how to set up a Neo node, what I want to be clear is the relationship between projects here under this neo-project group. How they work together from the term of source code.

**Comment by Tommo-L** [comment]
@Liaojinghui I've drawn a diagram, plz have a look.

![image](https://user-images.githubusercontent.com/43396869/77544344-d9dd1e00-6ee3-11ea-9400-540213b25497.png)


I'll update the github document later.

**Comment by Liaojinghui** [comment]
> @Liaojinghui I've drawn a diagram, plz have a look.
> 
> ![image](https://user-images.githubusercontent.com/43396869/77546109-5a048300-6ee6-11ea-9312-21378fe52b0d.png)
> 
> I'll update the github document later.

Thank you very much, this is exactly what i wanted.
