### ISSUE TITLE
Add onchain condition timer

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1518]
Some conceptual definitions:

- **Object**: Specify the transaction that can trigger the condition timer (specify Sender or transaction hash). Unlike traditional timers, on the blockchain, any execution on-chain requires a transaction to trigger.
- **Condition**: In the contract called by the object's transaction, the satisfaction conditions for the trigger task can be customized, such as the approval threshold condition of oracle contract.
- **Task**: A task is actually a transaction which registered in the condition timer contract, will be executed, when the condition is satisfied.

The task(or transaction) should call the condition timer contract to register the timer by adding the hash of condition timer contract as a cosigner.  Then the task will be packaged just like a normal transaction, and will be also be charges(advance payment), but it'll not be executed at once. Only when the trigger condition is met, the task will be automatically executed at the end of block execution.

some constraints:

- A object can only trigger one task
- A task can only be triggered once
- During the task execution, no other task can be triggered
- Need to pay certain fee to register the timer.

In summary, the condition timer is a transaction on the blockchain. When the execution meets a certain condition, it will trigger the timer(another transaction) that is registered in advance.

There is a condition timer contract demo:

```cs
class ConditionTimerContract: NativeOnctract
{
    private Map<Task, Object> timers;
    private List<Task> triggeredTasks;
    
    public bool verify(){
        // verify the tx.fee >= basic fee
    }
    
    protected registerTimer(task, object){
        // Only can use native transaction to register or other native contract
    }
    
    public bool activeTimer(task.hash){
        // check object
    }
    
    @override
    public list<tx> PreExecuteBlock(blockTxs){
        // register condition timer...
        registerTimer(task, object)
    }
    
    @override
    public void PostExecuteBlock(blockTxs){
        // execute tasks which be triggered
    }
}
```

**Comment by Tommo-L** [comment]
I have added the definition of condition contract timer, not sure if there is some risk. Plz have a look.

**Comment by erikzhang** [comment]
I think this kind of services should be build off-chain.
