### ISSUE TITLE
Oracle use condition timer

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1525]
**Native Contract**

A type of system built-in contract, has some relatively special permissions, can be before and after the block execution, to perform some special tasks.

**Native Transaction**

 A type of special transaction. The Sender or Cosigner of the transaction contains the native contract address, which is the native transaction. 

Then, we'll enhance the current oracle by using `OracleContract` and the [condition timer](https://github.com/neo-project/neo/issues/1518).

**The work flow of oracle**

![image](https://user-images.githubusercontent.com/43396869/78114458-e4dc0500-7433-11ea-9505-e561ce985c3d.png)

1. User send the oracle request transaction and add `OracleContract.hash` as a cosigner. It's actually a native transaction.
2. The request transaction will be packaged on blockchain.
3. As it's a native contract, it'll active the `OracleContract`.  When oracle contract execute `PreExecuteBlock` method, it'll invoke the `registerTimer` method of `ConditionTimerContract` to register the oracle request as a condition timer. Then remove the request transaction from the execute transaction list, which means the script of request transaction will be executed.
4. When oracle nodes received a new block which contains oracle request transaction, it'll request data by `https` or `neofs`, then send oracle response transaction.
5. After the response transaction packaged, it'll invoke the `AddResponse` method of `OracleContract`.
6. When the approval threshold condition is met , it'll trigger the timer registered by advance. Then, the oracle request transaction will be executed in `PostExecuteBlock` of `ConditionTimerContract`.

**Aggregate data onchain**

As no matter which way we choose, the oracle node's signature must be onchain. We'll make oracle response as a normal transaction to invoke the `AddRespnose` method of `OracleContract`.

`OracleContract` will make a consensus/agreement onchain by using the method discussed at https://github.com/neo-project/neo/issues/1273 

**Differences**
- use condition timer
- move aggregation from cn to contract

**Comment by erikzhang** [comment]
I think this kind of service should be built off-chain.

**Comment by realloc** [comment]
This mechanism seems to be quite complicated and even if implemented correctly it will significantly affect state calculations and tracking. As for the Oracle case, it would slow down Oracle invocations to be at least two (2) blocks time. Initial idea, as I remember it, was to use Neo's unique properties and provide a way to have one Oracle TX per Oracle call and, in most cases, have them in one block time frame.

I'd propose to think once again about one Oracle TX per Oracle call model with TX attributes used to order transactions. It's less complicated to understand and implement and should work faster with less impact on TPS and blockchain size.

**Comment by doubiliu** [comment]
@realloc I think this method will be more secure.One Oracle Tx  exist the risk of malicious attack.
I have described the method of spam attack in #1527 . On-chain Condition Timer can resolve it.
In addition, I think this change in the transaction order is acceptable. Instead of intentionally changing the execution order, we **record the actual transaction process on the chain**.And this mechanism is not complicated, only a native contract is needed, and an execution process is added after the block is persisted.This will not have much impact on TPS, because the number of transactions that can be executed additionally is limited, and the maximum is equal to the number of transactions in one block.You can understand it as a one-to-one replacement

**Comment by doubiliu** [comment]
And this is still a transaction to a certain extent, we just separate the record and execution of the transaction.In some traditional Oracle solutions, they use only two real transactions. First, send a transaction to the contract, let the node write the result to the contract, and then send a transaction to get data from the contract.There are callback methods, but also the problem of calling permissions
