### ISSUE TITLE
Failed to add json file when calling GetConfiguration()

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo#1531]
**Describe the bug**
I tried to update the config file of `RpcServer` while neo-cli was running, but sometimes the neo-cli would throw exception and crash.
![image](https://user-images.githubusercontent.com/43694095/78320796-ebd25700-759c-11ea-8ebc-f067f44db7cc.png)

**To Reproduce**
1. start neo-cli.
2. change some settings in the config file of `RpcServer`, such as `DisabledMethods`, then save it.
3. most of the time, neo-cli will throw the exception and crash.

**Platform:**
 - OS: [e.g. Windows 10 x64]
 - Version
    neo-cli:               5a46401b3635b0f2f6a6b09141c20ea5ab361623
    neo:                    6eba2ee12d12b70d27181ff88f4ebf81550fe3ca 
    neo-vm:              f292fed3e9add32a2746e2c4cbb569d8dce6f25a
    neo-modules:     bbcfa56171a931c1c6f2b50f9289350dd7c052c0

**(Optional) Additional context**
It seems that the json file wasn't added successfully.
![image](https://user-images.githubusercontent.com/43694095/78321695-45d41c00-759f-11ea-94fe-207bdf3ce2b6.png)
When debugging, if I set a breakpoint, then continue, the file can be added successfully and not throw an excepiton.
![image](https://user-images.githubusercontent.com/43694095/78322036-31dcea00-75a0-11ea-8f6c-251940c781d0.png)

The issue was found when testing https://github.com/neo-project/neo-modules/pull/206

**Comment by Qiao-Jin** [comment]
I will have a look at this one.

**Comment by erikzhang** [comment]
I think the real reason is that `WatcherChangeTypes.Changed` will be triggered multiple times. Maybe we can just catch the exception and ignore it in the plugins.

**Comment by nicolegys** [comment]
> I think the real reason is that `WatcherChangeTypes.Changed` will be triggered multiple times. Maybe we can just catch the exception and ignore it in the plugins.

You're right. When the config file is modified by editors like Notepad, the `WatcherChangeTypes.Changed` will be triggered once, but when modified by editors like VS code, the `WatcherChangeTypes.Changed` will be triggered twice, and `GetConfiguration()` will fail at the first time.

**Comment by erikzhang** [comment]
Then the fixes should be in the plugins.

**Comment by Qiao-Jin** [comment]
> Then the fixes should be in the plugins.

Then we would need duplicate logic added everywhere func GetConfiguration called in plugins (config file changed, initialization)?

**Comment by shargon** [comment]
Agree with @Qiao-Jin , I think that it's better to fix it in the core and avoid duplicate code in modules.

**Comment by erikzhang** [comment]
Look at this:

https://github.com/neo-project/neo/blob/2fad68aa08919e1c066e1bbe7c65f9e6eea3b50e/src/neo/Plugins/Plugin.cs#L64-L81

The event is triggered when file is changed. Then it invokes the method `Plugin.Configure()`. Be careful, it is `Configure()`, not the `GetConfiguration()`.

And the default `Configure()` is:

https://github.com/neo-project/neo/blob/2fad68aa08919e1c066e1bbe7c65f9e6eea3b50e/src/neo/Plugins/Plugin.cs#L60-L62

As you can see, it does nothing. So you didn't fix anything if you catch the exception in `GetConfiguration()`.

The most logical way is to call the `GetConfiguration()` in the plugin's overriding `Configure()`, which has already been done. And we just add some code around it to catch the exception.

**Comment by Qiao-Jin** [comment]
@nicolegys please have a test of the new PR:)
