### ISSUE TITLE
Payback the remaining system fee

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo#1536]
**Summary or problem description**

Sometimes we may  worry about whether the system fee is sufficient to execute the transaction. For example, for some settlement contracts, when a new block is added every time, the system fee may change.

**Do you have any solution you want to propose?**

If we can payback the remaining system fee, I think it will be very convenient for the user.

**Neo Version**1
- Neo 3

**Where in the software does this update applies to?**
- Blockchain

**Comment by shargon** [comment]
If we pay the remaining fee it could be used for prioritize the TX without pay more than other users

**Comment by vncoelho** [comment]
I think it is also complex to have a non-deterministic knowledge of how much will be given.
This can be a mode of operation but, perhaps, not the default for now.

**Comment by erikzhang** [comment]
I think there is no need to payback too.
