### ISSUE TITLE
NFT assets in NNS scenarios

### ISSUE THREAD

**Issue by doubiliu** [neo-project/neo#1545]
**Summary or problem description**

NGD is designing the NNS system. In NNS, domain names have ownership and independence, which is in line with [NFT](https://github.com/neo-project/proposals/pull/41) application scenarios.

**Need to discuss** ：

1. Whether it is necessary to design according to the NFT standard in NNS?
2. Whether the existing NFT standard is enough? 

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other:NNS

**Comment by erikzhang** [comment]
I think the domain names should not be permanent. You need to renew them.

**Comment by doubiliu** [comment]
I have considered this.In our design, the root domain name is perpetual and is controlled by the committee or administrator. Subdomains are all leased.

**Comment by doubiliu** [comment]
Well.We will upload a draft design plan for NNS．

# NNS Design

In NEO, the contract address and account address is a Hex string which is difficult for humans to remember, and it is not very convenient to use. For ease of use, we introduced the domain name system, using easy-to-remember domain names as a replacement for difficult-to-remember strings. Eg. Users can initiate a transaction directly to a certain domain name, the effect is the same as transferring money to a certain address.



## Design Goal

【1】Provide domain name services for contract addresses / wallet addresses / other complex strings.

【2】Self-service domain name management.

【3】Self-service domain name transfer.

【4】 Create NFT usage scenarios



## Define

### Domain Name

Use an simple string to replace account address / contract address / other complex strings. Use a format similar to traditional DNS as the domain name format.

Format：`third-level domain.second-level domain.top-level domain.root domain`   

Using "." As a delimiter, the domain name level increases from right to left, the low-level domain name is the parent domain name of the high-level domain name, and the high-level domain name is the sub-domain name of the low-level domain name. The parent domain name initially owns all the subdomains under it.

NNS supports up to third-level domain names.



### Domain lifecycle

In order to avoid long-term occupation of domain name resources by invalid or malicious acts, the root domain name is held by the administrator for a long time. The first-level domain name will adopt the lease model, and the validity period of other domain names is equivalent to the validity period of its first-level domain name.

If the domain name holder still wants to continue to hold the domain name, it needs to renew the first-level domain name.



## System Structure

![NNS结构](https://user-images.githubusercontent.com/42929757/78986054-efe21400-7b5c-11ea-8747-0bcc5266de51.jpg)

The overall system is composed of five parts, `RegistryCenter` contract, `Registry`  contract, `TradingHall` contract, `Resolver`  contract,and `Policy` contract.

### Registry Center

It is responsible for managing the registration, renewal, and transfer of domain names. And it complies with NFT standards.

It supports the following functions:

- Root domain registration

  ```
  function bool registerRootName(String name)
  ```

  Register a new root domain name, only the administrator can call this interface.

- Domain transfer

  ```
  function bool transfer(UInt160 from,UInt160 to,String name)
  ```

  Transfer ownership of a domain name to another person, only the current owner or trading hall has the right to call it. This interface is one of NFT's standard interfaces.

- Domain renew

  ```
  function bool renewName(String name,int time)
  ```

  Renew the lease of the first-level domain name. The initial domain name is valid for one year. After expiration, the validity period can be extended through this interface, but an additional fee is required. Anyone can call this interface.

- Other NFT interfaces




### Registry

Maintain a list of domain names and store their ownership, resolver, TTL (validity period) and other information

**Storage Structure**

 <NameHash,<owner,resolver,admin,TTL>>  DomainList

<owner,List< NameHash>>  OwnershipReverseMapping

It mainly supports the following functions:

- Add new domain

  ```
  function bool registerNewName(String name,UInt160 owner,UInt160 admin,int TTL)
  ```

  Add a new domain name to the registry and mark its owner and expiration date. Only the registry can call this interface.

- Update domain ownership

  ```
  function bool setOwner(String name,UInt160 owner)
  ```

  Set the domain name owner, only the current owner of the domain name can call it.

- Configure resolver address

  ```
  function bool setResolver(String name,UInt160 address,UInt160 admin)
  ```

  Configure the domain name owner, only the current owner of the domain name can call it.

- Configure TTL

  ```
  function bool setTTL(String name,int TTL)
  ```

  Set the validity period of the domain name. Can only be called by the registry center.

- Resolve domain

  ```
  function string resolve(String name)
  ```

  Find its corresponding resolver based on the domain name, and call related methods to obtain the corresponding parsed text.

  If no resolver is found or parsing error is returned `null`.



### Trading Hall

It is responsible for constructing buy / sell orders for the domain name and matching the two transactions. In addition to the root domain name, other domain names can be bought and sold on this platform for a fee.

**Storage Structure**

<NameHash,<name,price,address>> batchOrderPool

<NameHash,<name,price,address>> singleOrderPool

It mainly supports the following functions:

- Create Domain Sell Order

  ```
  function bool createNameSellOrder(String name,long price,UInt160 address)
  ```

  When the domain name holder decides to sell the domain name or one of its sub-domain names, it can call this interface to generate a domain name transfer agreement.

- Create Domain Bulk Sell Order

  ```
  function bool createNameSellBatchOrder(String name,long price,UInt160 address)
  ```

  When the domain name holder decides to sell all the sub-domains under it, he can call this interface to generate a domain name transfer agreement, which will set the transfer price of the domain name \ receipt address

- Create Domain Buy Order

  ```
  function bool createNameBuyOrder(String name,UInt160 owner)
  ```

  The buyer calls this method to create a buy order. When the buy order matches the sell order, the transaction is established, and the trading hall will call the registry center to change its ownership.

  

### Resolver Contract

It stores resolver instances for each domain name, and each resolver instance provides a series of methods to resolve the domain name to the corresponding text.

**Necessary interface**

```
function string resolve(String name)
```

Return parsed text.

The NNS system will provide a default resolver. Users can also implement the resolver according to the interface standard.

**Default Resolver**

**Storage Structure**

 <NameHash,<Text,FuzzyFlag>> resolverList

It mainly supports the following functions:

- set text

  ```
  function bool setText(String name,String text,bool fuzzyflag)
  ```

  The administrator of the resolver can set the text corresponding to the domain name and determine whether to enable the fuzzy matching function

- resolve domain

  ```
  function string resolve(String name)
  ```

  Returns the text corresponding to the domain name.

  If you do not query a domain name by wildcard, the text corresponding to the domain name is returned, or null if it does not exist. Eg. `AAA.test.neo`

  If a domain name is queried by wildcard, and the parent domain name has fuzzy matching enabled, the subdomain name text set by the domain name's parent domain name is returned.

  Eg. `* .Test.neo`



### Policy Contract

It is responsible for setting the current unit price, rental price, and administrator list.

It Mainly contains the following functions:

- set administrator

  ```
  function bool setAdmin(UInt160 address)
  ```

  Committee set administrator (multi-signature address)

- Set the rental price of domain name

  ```
  function bool setRentalPrice(long price)
  ```

  Set unit price for renewal per cycle

- Set domain name transaction fee

  ```
  function bool setTransactionFee(long price)
  ```

  Set domain name transaction fee



## Principle

### Root domain registration

All root domain names are managed by the administrator, and the validity period is perpetual.

When a new root domain name is needed in NEO, administrators initiate a multi-signature transaction to call the `registerRootName` method of the registry contract to complete the registration.

Execution logic

1. Check the legality of the administrator's multi-signature

2. Check the legality of the root domain name format

3. Check if the root domain name is duplicate

4. Call the `registerNewName` method of the registry contract, the parameters are <root domain name, holder (UInt160.Zero), TTL (-1, forever))



### Domain transfer

The ownership of the root domain name cannot be transferred, and the ownership of other domain names can be transferred.

- **By setting**

  The current domain name holder calls the registry center contract `transfer` method to complete the transfer.

  Execution logic:

  1. Check the legality of the domain name holder's signature

  2. Check the validity of the domain name TTL (recursively query the parent domain name TTL)

  3. Change the domain name holder

- **By sales**
  1. The current domain name holder invokes the trading hall to initiate a sell order, and it is necessary to set <transfer price, payment address>.

  2. The trading center invokes the registry to obtain ownership information and conduct qualification and validity period checks. After the inspection is passed, the sell order is established.

  3. The buyer calls the trading hall to initiate a buy order transaction, which requires qualification and validity period inspection. After the inspection is passed, the purchase order is established.

  4. The trading hall will match buy and sell orders.

  5. After a successful match, the trading hall calls the registry center contract to transfer the domain name. Buy orders and sell orders will be removed.

![image](https://user-images.githubusercontent.com/42929757/78986233-63842100-7b5d-11ea-8ee4-4de11ee4dd3e.png)




### Assign Subdomain

In the initial state, the parent domain name holder owns the ownership of all subdomains under this domain name. The parent domain name holder can assign these sub-domain names to others.

- **By setting**

  The current domain name holder calls the register center contract `transfer` method to complete the transfer.

  Execution logic:

  1. Check the legality of the domain name holder's signature

  2. Check the validity of the domain name TTL (recursively query the parent domain name TTL)

  3. Check if the subdomain ownership has been assigned

  4. Register a new domain name with a subdomain name

- **By sales**
  1. The current domain name holder calls the trading hall contract to sell the domain name and needs to set <subdomain name, transfer price, payment address>.
  2. The trading hall contract invokes the registry contract to obtain ownership information and conduct qualification and validity period checks. After the inspection is passed, the sell order is established.

  3. The buyer calls the trading hall contract to initiate a buy order transaction, which requires qualification and validity period inspection. After the inspection is passed, the purchase order is established.

  4. The trading hall contract will match buy and sell orders.

  5. After a successful match, the transaction hall contract calls the registry center contract to transfer the domain name. If the specified subdomain is transferred, both the buy and sell orders will be removed. If all subdomains are transferred, the buy order will be removed and the sell order will still be resident in the trading center contract.

![image](https://user-images.githubusercontent.com/42929757/78986163-36377300-7b5d-11ea-9267-602121d580d8.png)



### Domain resolve

The user calls the registry to resolve the domain name. The registry will calculate the corresponding NameHash and find the corresponding resolver according to the NameHash. The resolver will return the corresponding value.

Note: The wildcard domain name, Eg. `* .Test.com`, will use the resolver of its upper-level domain name during the parsing process. If the resolver turns on fuzzy matching, it will return the parsed text, otherwise it returns ` null`.

**Comment by doubiliu** [comment]
@erikzhang Hi,da lao. Whether  the proposal meets expectations,？If OK, NGD will begin to implement it.

**Comment by erikzhang** [comment]
1. We need to support multiple resolution record types.
2. The trading hall should not be a built-in function.
3. There should be only one contract.

**Comment by doubiliu** [comment]
OK.We will remove trading hall.Can you explain what the resolution record types mean?We don't understand

**Comment by erikzhang** [comment]
https://en.wikipedia.org/wiki/Category:DNS_record_types

**Comment by doubiliu** [comment]
I have modified the design. @erikzhang

**Comment by erikzhang** [comment]
What is a resolver?

**Comment by doubiliu** [comment]
The Resolver is responsible for completing the process of parsing the domain name to the actual string.Because domain name resolution is not only as simple as obtaining an address, many complex resolution logics should be abstracted into this component, such as domain name redirection, format checking, and fuzzy matching.At the same time, the advantage of this kind of component design is to separate the ownership and management of the domain name.This is a reasonable requirement because the holder of the purchased domain name is not necessarily the actual administrator of the domain name.

**Comment by erikzhang** [comment]
So the resolvers are contract?

**Comment by doubiliu** [comment]
I can write the default resolver in the NNS contract, and the user can also configure a custom one.Of course, I suggest that it is better to split into two contracts, so that the structure is relatively clear.

**Comment by erikzhang** [comment]
I don't think we need custom resolvers. All we need is the default one.

**Comment by doubiliu** [comment]
OK. This modification is very easy, forcing the configuration to use the default resolver.Is there anything else that needs to be modified?

**Comment by erikzhang** [comment]
If you're going to support NFT standard, the `transfer` method is not correct.

**Comment by doubiliu** [comment]
Piece of cake.:)

**Comment by doubiliu** [comment]
We will do a method format check

**Comment by doubiliu** [comment]
Are there other deficiencies?

**Comment by doubiliu** [comment]
I have modified the design.
Some little change,mainly:
1. Adjust the `transfer `method parameter format
2. Remove a `resolver `method
3. Remove a `setResolver `method
4. Add a `setResolverAdmin `method
