### ISSUE TITLE
How to prevent the same transaction from being submitted multiple times

### ISSUE THREAD

**Issue by i359** [neo-project/neo#1546]
How to prevent the same transaction from being submitted multiple times due to account and no nonce in NEO? 

In Bitcoin, utxo model can prevent the same transaction from being submitted multiple times.

In Ethereum, each account has a public visible random number. Each time a transaction is made, the random number increases by 1. This mechanism can prevent the same transaction from being submitted multiple times.

**Comment by Tommo-L** [comment]
@i359  we have `Transaction.Nonce`

**Comment by i359** [comment]
Transaction.Nonce display in blockchain ? thanks!

**Comment by Tommo-L** [comment]
> Transaction.Nonce display in blockchain ?

Yes.   And If the question has been solved, could you please close the issue.
