### ISSUE TITLE
`BlockHeader.NextConsensus` could be confuse

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1568]
In the next line you can see that the `NextConsensus` is the current one, in fact it's the previous one related to the new block, because this block was not persisted yet.

https://github.com/neo-project/neo/blob/bf16df9d5a090dfcaff90d7c9d5454cf5ad09101/src/neo/Consensus/ConsensusContext.cs#L349

So, I think that it should be renamed to `ConsensusAddress` in order to avoid mistakes.

**Comment by vncoelho** [comment]
Sounds good, @shargon.

**Comment by erikzhang** [comment]
It is the consensus address of the next block.

**Comment by shargon** [comment]
We don't know it, it could be changed in this block after persist

**Comment by erikzhang** [comment]
No, you can't. You can change the NextConsensus of the next block.
