### ISSUE TITLE
Help Get started C#

### ISSUE THREAD

**Issue by superbmilkyway** [neo-project/neo#165]
I am following Get Started C#

When I publish neon project, it shows the following error
```
Publish has encountered an error.
Publishing failed.

A diagnostic log has been written to the following location:
c:\UserFolder\AppData\Local\Temp\tmp1F3D.tmp
```
The log file is not text. I cannot read the content.
Even with the error I can find the file neon.exe and I copied neon.dll upper folder from neon.exe
Seems like none.exe working correctly.
```
> neon
Neo.Compiler.MSIL console app v2.0.3.1
need one param for DLL filename.
```

After that, I create a .net core 2.0 library project and then install Neo.SmartContract.Framework 2.5.4 pacakge using nuget. (I tried core 1.1 and 1.0 but all same)

I wrote a test contract.
```
namespace ExrNeo.Contract
{
    public class TestContract : SmartContract
    {
        public static void Main()
        {
            
        }
    }
}
```

When I run the dll with neon works fine.
```
>neon ExrNeo.Contract.dll
Neo.Compiler.MSIL console app v2.0.3.1
Find entrypoint:System.Void ExrNeo.Contract.TestContract::Main()
convert succ
gen abi succ
write:ExrNeo.Contract.avm
write:ExrNeo.Contract.abi.json
SUCC
```

However, when I put the Storage, neon cannot run the dll.
```
namespace ExrNeo.Contract
{
    public class TestContract : SmartContract
    {
        public static void Main()
        {
            Storage.Put(Storage.CurrentContext, "Hello", "World");
        }
    }
}
```

Error
```
>neon ExrNeo.Contract.dll
Neo.Compiler.MSIL console app v2.0.3.1
Convert Error:System.Exception: error:System.Void ExrNeo.Contract.TestContract::Main()::IL_0001 Call Neo.SmartContract.Framework.Services.Neo.StorageContext Neo.SmartContract.Framework.Services.Neo.Storage::get_CurrentContext() ---> System.Exception: unknown call: Neo.SmartContract.Framework.Services.Neo.StorageContext Neo.SmartContract.Framework.Services.Neo.Storage::get_CurrentContext()
   in: System.Void ExrNeo.Contract.TestContract::Main()

   at Neo.Compiler.MSIL.ModuleConverter._ConvertCall(OpCode src, NeoMethod to)
   at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to)
   at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to)
   --- End of inner exception stack trace ---
   at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to)
   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in)
   at Neo.Compiler.Program.Main(String[] args)
```

What did I wrong? Why get current context failed?
How can I go further?

Could anyone help me to solve this problem?

**Comment by nakov** [comment]
Just copy the `Neo.SmartContract.Framework.dll` library in your current folder, where your smart contract's DLL file is located.

**Comment by facadev** [comment]
After the dll was copies, the neon.dll asked for mscorlib.dll, which is not available on macOS. So I copied one from Windows, it then prompted System.BadImageFormatException. Any comment on that?

**Comment by Frankie34** [comment]
Error CS0433: The type 'OpCode' exists in both 'Neo.SmartContract.Framework, Version=2.7.3.0, Culture=neutral, PublicKeyToken=null' and 'Neo.VM, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null' (CS0433) (neon)
