### ISSUE TITLE
Decouple 'trusts/safemethods' from manifest?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1664]
From https://github.com/neo-project/neo/issues/287#issuecomment-494075858 I get that 
> trusts is an array of contract that can call "me" without UI warnings display.

and from the [NEP itself](https://github.com/neo-project/proposals/blob/3e492ad05d9de97abb6524fb9a73714e2cdc5461/nep-15.mediawiki#safemethods)
> If a method is marked as safe, the user interface will not give any warnings when it is called by any other contract.

This seems presentation logic, not manifest business logic. Why must it be hardcoded in the manifest? 

The manifest creator should not determine for a client what a client finds worthy to be notified about. Instead I think an event notification that a contract method is called by entity X is what is needed. A client can subscribe to such an event and let the user decide what methods it wants to listen to for what contracts.

**Problem scenario**
Take a contract with 2 methods `contract_update` and `say_hooray`. The manifest states `contract_update` is trusted because they might want to hide flaws or have actual malicious intentions and try to do a silent update. So now the client will not be notified when `contract_update` is called. This is the exact opposite of what I'd like as a client. As a client I'd like to select exactly `contract_update` as the method I want to be notified about and I don't care about `say_hooray` being called.

@RavenXce you rightfully [pointed out](https://github.com/neo-project/neo/issues/287#issuecomment-423723363) that it currently would be hard for a client to detect who calls who. What's your thoughts on the above?

**Comment by Tommo-L** [comment]
> Instead I think an event notification that a contract method is called by entity X is what is needed.

We need Event type?

**Comment by shargon** [comment]
I think that the idea of safe methods is prevent relay a TX when you call it, you can execute it in local an get the same results. Usually for state-less or readonly methods. Also wallet can call the method without write access using `CallEx` if it want to enforce this behavior.

**Comment by ixje** [comment]
> > Instead I think an event notification that a contract method is called by entity X is what is needed.
> 
> We need Event type?

@Tommo-L I don't know what the best event solution for C# is, but the current approach seems to be a mismatch with the purpose of a `manifest`. Even the documentation says
https://github.com/neo-project/neo/blob/77cee2453aa42a7f30b380b159b3dd36a98dafc8/src/neo/SmartContract/Manifest/ContractManifest.cs#L10-L11

In other words; a manifest describes the execution permissions and limitations of a smart contract. That makes perfect sense. However, client notification isn't (and shouldn't in my opinion) be part of this. Now, if `trusts` would actually mean `a list of permissions that indicate which external contracts are allowed to call which methods on the contract` (in other words the inverse of the `permissions` field) then it would make sense to be part of the manifest.

It is very confusing that everywhere in the system the team is trying to prevent as little as single unnecessary bytes to be stored on the chain, and here we add at the bare minimum 28 bytes for storing `trusts` and `safeMethods` (because the contract is serialised after conversion to JSON format) which is actually client presentation logic.

**Comment by ixje** [comment]
> I think that the idea of safe methods is prevent relay a TX when you call it, you can execute it in local an get the same results. Usually for state-less or readonly methods. Also wallet can call the method without write access using `CallEx` if it want to enforce this behavior.
> 
> https://github.com/neo-project/neo/blob/1451f849d98915775f794684a9dd073cececa6d0/src/neo/SmartContract/CallFlags.cs#L11

I understand what you're saying, but local execution is a feature that doesn't need to be described in the manifest. `neo-python` for `NEO 2.x` has had local execution without relaying the TX as long as I can remember, and there is no manifest there.

**Comment by ixje** [comment]
bump

**Comment by shargon** [comment]
> A client can subscribe to such an event and let the user decide what methods it wants to listen to for what contracts.

How do you think that this can be done? a notification doesn't allow you to handle the execution, only tell you that something happened, but you are not able to cancel it.

**Comment by ixje** [comment]
> How do you think that this can be done? a notification doesn't allow you to handle the execution, only tell you that something happened, but you are not able to cancel it.

Nowhere in the NEP, issue (#287) or code does it currently state that you should be able to control execution on notification. It only states that you get _notified_ via a UI warning, or in other words "informed something happened". 

If you want to prevent relaying, then have a listener that adds the TX to a block list in LocalNode or something like that. If you want to cancel execution, then do the same as plugins and make something you can override and have the interop layer call it whenever a non-safe function is called.  

The point remains that the smart contract should not decide for a client what the client should be notified about or not. See **problem scenario** in the first post.

**Comment by shargon** [comment]
Maybe we can `Log` if the ApplicationEngine it's under `test Mode` all the syscalls, it could be enough for the wallet to know what's happend.

**Comment by ixje** [comment]
Why close? The issue is still a valid concern

**Comment by erikzhang** [comment]
Because it is marked as a `question`.
