### ISSUE TITLE
Can we support Runtime.Notify (Enumerator)?

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo#1669]
False returned while use `Runtime.Notify(InteropInterface)`, so contract's invoke result is `FAULT`.

Can we support `Runtime.Notify (InteropInterface)` like `Runtime.Notify (Map)`?

**Comment by shargon** [comment]
`InteropInterface` it's only for share information between syscalls, we should not be able to use it outside.

**Comment by Tommo-L** [comment]
> `InteropInterface` it's only for share information between syscalls, we should not be able to use it outside.

But ABI have allowed `InteropInterface` to be the return type.

_returntype indicates the return type of the method. It can be one of the following values: Signature, Boolean, Integer, Hash160, Hash256, ByteArray, PublicKey, String, Array, Map, InteropInterface, Void._

**Comment by shargon** [comment]
I think that we should not be able to return a Interop type, what do you think @erikzhang ?

**Comment by erikzhang** [comment]
We need it to have the ability to share `StorageContext` between contracts.

**Comment by erikzhang** [comment]
But we shouldn't allow it in `Runtime.Notify()` I think.

**Comment by Tommo-L** [comment]
> But we shouldn't allow it in `Runtime.Notify()` I think.

If so, we'd better add comments in `Runtime.Notify` method.

https://github.com/neo-project/neo/blob/5c7197f6b54de6eeee322f9c3343cd9758fe040e/src/neo/SmartContract/InteropService.Runtime.cs#L197-L199
