### ISSUE TITLE
Memory usage problem of offline synchronization 

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#167]
Memory usage without offline synchronization packets:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/6295602/35849603-28fafe2c-0b5d-11e8-98f4-5c1d1960388f.png">

Memory usage in offline synchronization:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/6295602/35850181-eb2bcc28-0b5e-11e8-8308-99d13c092c91.png">

Memory usage after offline synchronization end:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/6295602/35851529-400a9bda-0b63-11e8-93ab-2c1415684f68.png">
There is already a number of connections, and the Chain.acc.zip has disappeared, and the speed of synchronization has slowed down, about 20~40 blocks/s, so I can judged that offline sync is over.

After 10 minutes, memory usage remains high
<img width="730" alt="image" src="https://user-images.githubusercontent.com/6295602/35850357-7c19efee-0b5f-11e8-8304-161997892d27.png">

After 20 minutes, memory usage remains high
<img width="706" alt="image" src="https://user-images.githubusercontent.com/6295602/35851303-9a388cc6-0b62-11e8-8816-a464c2a954a5.png">

So I guess it's possible that the memory was not released in time after offline synchronization end.

**Comment by erikzhang** [comment]
fixed in 363038aa8d13f4c56cd514a2628c48abd9c7e14b
