### ISSUE TITLE
Storage.Find behaves incorrectly if cache is changed after iterator is received

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#1672]
linux dotnet 3.10.2
neo master branch

**Describe the bug**
`DataCache.Find` saves cached items in an array during the call.
However when items from the underlying storage iterator are used, current state of cache is used.
This can lead to a situation when:
- item is not in cache (it was in persistent storage when `Find()` was called)
- item will not be in the results of `uncached` iterator (because it will be in cache when a check will occur)
Thus an item will be missing from `Storage.Find` result.

**To Reproduce**
Run this test (in `UT_DataCache.cs`)
```
[TestMethod]
public void TestFindInvalid()
{
    var myDataCache = new MyDataCache<MyKey, MyValue>();
    myDataCache.Add(new MyKey("key1"), new MyValue("value1"));

    myDataCache.InnerDict.Add(new MyKey("key2"), new MyValue("value2"));
    myDataCache.InnerDict.Add(new MyKey("key3"), new MyValue("value3"));
    myDataCache.InnerDict.Add(new MyKey("key4"), new MyValue("value3"));

    var items = myDataCache.Find().GetEnumerator();
    items.MoveNext().Should().Be(true);
    items.Current.Key.Should().Be(new MyKey("key1"));

    myDataCache.TryGet(new MyKey("key3")); // GETLINE

    items.MoveNext().Should().Be(true);
    items.Current.Key.Should().Be(new MyKey("key2"));
    items.MoveNext().Should().Be(true);
    items.Current.Key.Should().Be(new MyKey("key3"));
    items.MoveNext().Should().Be(true);
    items.Current.Key.Should().Be(new MyKey("key4"));
    items.MoveNext().Should().Be(false);
}
```

**Expected behavior**
1. Storage.Find will either every item that was in storage at the moment of `Find()` call.
2. Items will be returned in correct order.

**Comment by vncoelho** [comment]
Nice example. Time to fix this, we have discussed similar behavior before on DataCache.
