### ISSUE TITLE
Rename AES256Encrypt

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#1681]
Looking at the test https://github.com/neo-project/neo/blob/eb3c1134b3dfa0739ec0348513bdca48f4560329/tests/neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs#L18-L20
we can see we use a key for 128Encrypt.

Perhaps this method should be renamed to `AesEcbEncrypt` since it is able to handle different keys size.

**Comment by shargon** [comment]
Yes, or just AesEncrypt

**Comment by vncoelho** [comment]
We already have this one,Shargon,but it is CBC mode default I think.

**Comment by vncoelho** [comment]
Hi @erikzhang, you closed the PR but, in my opinion, the names needs to be renamed or we need comments explaining that.

**Comment by erikzhang** [comment]
I will review it again.

**Comment by vncoelho** [comment]
Sounds good, @erikzhang.

Maybe the PR is wrong, I do not remember it very well. But at the time we opened that we were porting those function to C++ and I can remember that we study a lot about crypto libraries and etc in order to make a good porting of it.
In this sense, we probably investigated the names correctly.
