### ISSUE TITLE
How to use "CallContractEx" in a Native contract?

### ISSUE THREAD

**Issue by doubiliu** [neo-project/neo#1699]
Description:
I want to implement a new function of a native contract, and need to call an external contract in the native contract method.When I use "engine.CallContractEx", I find that the return value of the original method is pushed into the evaluation stack  of the new context, occupying the position of the contract method, and the call fails.

**Comment by shargon** [comment]
What it's the use case?

**Comment by shargon** [comment]
Ping @doubiliu

**Comment by doubiliu** [comment]
We are trying to implement an asynchronous Oracle implementation.After the implementation is completed, the two programs need to be compared and evaluated.The implementation process is quite complicated, and there are many issues to consider. 😄

**Comment by shargon** [comment]
> We are trying to implement an asynchronous Oracle implementation

I think that this still under discussion.

**Comment by erikzhang** [comment]
Imagine a decentralized exchange with various assets in it. When users withdraw, the exchange contract needs to dynamically call the asset contract. If the exchange is a native contract, then this feature is needed.
