### ISSUE TITLE
Json.Serialize map key encoding

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#1704]
Right now in `System.Json.Serialize` map keys are expected to be `utf-8` encoded strings. https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/JsonSerializer.cs#L118
This can be unexpected because _some_ integers and bytestrings are marshaled without loss and some are not. For example, result for `Map(byte[]{0xC0}: 2)` is `{"\uFFFD":2}` (`\uFFFD` is a unicode replacement character).
I suggest checking that map key is a `ByteString` and it's span is a valid `utf-8` sequence of bytes. Otherwise user has probably made an error and failing immediately is a way to go.

**Comment by shargon** [comment]
`ByteString` or `Buffer` maybe
