### ISSUE TITLE
when deserialize for Map, value is re-serialized

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1714]
**Describe the bug**
when deserialize the type Map, value is re-serialized.
https://github.com/neo-project/neo/blob/5e96011c33ddbb444e006c9a8582a73570581a96/src/neo/SmartContract/JsonSerializer.cs#L45-L56

when serialize the type Map, keep the original key and  value.
https://github.com/neo-project/neo/blob/5e96011c33ddbb444e006c9a8582a73570581a96/src/neo/SmartContract/JsonSerializer.cs#L106-L115

**To Reproduce**
1. deploy the following contract.
```cs
        public static object testdeserialize(string a )
        {
            Map<string, string> some = new Map<string, string>();
            some[a] = "testbool";
            string sea = Json.Serialize(some);
            return Json.Deserialize(sea);
        }
```
2. invoke method.

**Expected behavior**
Serialize and deserialize should be consistent.

**Screenshots**
![a875b97190c0006c234d0f87a6385ee](https://user-images.githubusercontent.com/34291844/85156921-55edc480-b28d-11ea-9a9a-e8bac23dc37d.png)

**Platform:**
 - OS:Windows 10 x64

**Comment by erikzhang** [comment]
L54 is in `Serialize()` not `Deserialize()`.

**Comment by erikzhang** [comment]
The issue is in L155.
