### ISSUE TITLE
Akka remote proved to be much more faster than current tcp protocol 

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1718]
**Summary or problem description**
Currently tcp protocol is used for message transmission between nodes, and the transmission throughput between nodes are very limited.

**Do you have any solution you want to propose?**
After replacing current tcp protocol by [akka.remote](https://getakka.net/articles/remoting/index.html) in Neo, experiment results show network transmission becomes much more faster than previous status, i.e. 5,000,000 transactions (or 1.22 GB data) can be transmitted within 7 block period between two nodes located on a same machine, after proper configuration of akka remote, dispatcher, serializer, etc. This enhancement in transmission speed can potentially increase Neo node performance.

**Neo Version**
- Neo 3

**Comment by roman-khimov** [comment]
> much more faster than previous status

But what's the current status, really? I mean it'd be nice to compare these values with something for the current protocol. And it'd be even better to have some tools to reproduce them.

**Comment by Qiao-Jin** [comment]
> > much more faster than previous status
> 
> But what's the current status, really? I mean it'd be nice to compare these values with something for the current protocol. And it'd be even better to have some tools to reproduce them.

If we only send raw transactions by tcp protocol the transmission speed is also very fast (almost as fast as akka.remote in our case after testing, if we directly call Func EnqueueMessage and neglect this judgement: https://github.com/neo-project/neo/blob/801ac7f82331adf7d0f1b9a6d421d13eb12bb504/src/neo/Network/P2P/RemoteNode.cs#L49)

However, in current code there are some limits, i.e.

(1) Sending each transaction message would requiring ACK from the message receiver for the last message. In case of a huge transaction stream, a lot of transaction messages would fail to be sent because ACK messages are not received in time. Thus transaction transmission speed is drastically weakened ( tens to hundreds of times ).

(2) Akka remote can send transactions in batches where  while current tcp protocol will send them one by one. In TPS tests the former acts better.

**Comment by Qiao-Jin** [comment]
After testing TPS will be between 5000 - 7000 when akka-remote used.

**Comment by roman-khimov** [comment]
>  Sending each transaction message would requiring ACK from the message receiver for the last message

I'm not sure what it actually means. Is that about TCP ACKs or something? Because transactions are being exchanged with inv-getdata-tx sequence and there is no acknowledgement for `tx`.

> Akka remote can send transactions in batches while current tcp protocol will send them one by one

Well, returning to inv-getdata-tx sequence we have arrays being used for `inv` and `getdata` and the only place where this is a problem is `tx`. I think it's quite easy to fix that and try it out.

> After testing TPS will be between 5000 - 7000 (5000 - 6000 without #1734, 6000 - 7000 with #1734) when akka-remote used 

But what are the values for non-akka-remote case?

**Comment by Qiao-Jin** [comment]
> I'm not sure what it actually means

https://github.com/neo-project/neo/blob/e91abdcd476a6cf112d87a6998d9177679011ea0/src/neo/Network/P2P/Connection.cs#L13

> But what are the values for non-akka-remote case?

I'm still doing experiments on this and researching on other factors that can influence TPS, so I cannot give a certain answer on how much akka remote can improve TPS (though currently non-akka-remote is about 1000 lower). Please refer to my later posted issues.

**Comment by imanov** [comment]
@Qiao-Jin Do you still have the version with Akka.Remote? Is it up to date and can we run some benchmarks on TPS performance with Akka.Remote?
