### ISSUE TITLE
Drop array wrapper from witnesses for block and consensus payloads

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#1742]
## Quick summary

Both block and consensus payloads at the moment pretend like they can have multiple witnesses attached, but in fact only work with a single witness. While this is true it makes little sense for wire format to waste one byte per payload for witness count so this proposal is about removing it.

## Current state

Here is a part of deserialization code for both payloads:

BlockBase.cs:
```
            Witness[] witnesses = reader.ReadSerializableArray<Witness>(1);
            if (witnesses.Length != 1) throw new FormatException();
            Witness = witnesses[0];
```

ConsensusPayload.cs:
```
            if (reader.ReadByte() != 1) throw new FormatException();
            Witness = reader.ReadSerializable<Witness>();
```

Serialization is quite symmetric, creates an array with one element in the case of BlockBase and just writes `1` in the case of ConsensusPayload.

Any other value but `1` is not accepted as an array length for both structures.

## Background

These magic bytes/array wrappers were added with #791 (note that we lived without these bytes before #791 and it wasn't a problem). It extended IVerifiable to work with arrays of witnesses and the rest resulted from this change.

The question about BlockBase in fact was already raised in #1128  (and there also is a relevant discussion in #1129), but I'd like to extend it with ConsensusPayload and put some additional light on it given that we all have a bit more experience with Neo 3 now.

## Protocol level changes

I think it's quite obvious that it's redundant protocol-wise. And it's not that we're to lose any functionality if we're to change this. There were some concerns raised in previous discussions about the possibility of future extensions to include multiple witnesses, but we're mid-2020 now and it didn't happen, so probably YAGNI is applicable here and if we're ever to need this,
we'll need to raise version number anyway as this extension is not compatible with version 0.

Of course it's not that big of an overhead, but still these bytes add up and there also is some associated processing penalty for every block and for every consensus payload, so to be efficient I think we should minimize even these overheads especially when it costs nothing to do that. It should also be noted that BlockBase affects Header as much as Block, and headers are especially sensitive to any size changes.

There also is JSON format change involved into this, I think we should use 'witness' for single-witness cases and 'witnesses' for multiple witnesses as it naturally follows structures being represented. Adding arrays where they don't really exist doesn't seem to be a good choice.

## Implementation level changes

If we're to look more carefuly at how IVerifiable is being used we may find that it's implemented by BlockBase, ConsensusPayload and Transaction. Two out of these three actually never have more than one witness, so IMO it shows that
the abstraction itself is not quite right and what probably needed is IVerifiable (single witness) and IMultiVerifiable (multiple
witnesses). IVerifiable can be easily converted to IMultiVerifiable by a separate (generic for both BlockBase and ConsensusPaylod!) proxy helper if there is a need to. And this split also allows for different JSONization.

Of course IVerifiable interface is directly tied to VerifyWitnesses helper that is made to be generic for all of these IVerifiable things. It at the same time can be easily split into VerifyWitness and VerifyWitnesses as it's only being called from BlockBase/ConsensusPayload/Transaction themselves, so they can choose an appropriate helper. It would also improve efficiency a bit as there would be no need to create wrapper witness array for Block and ConsensusPayload when verifying them.

The other user of this interface is ContractParametersContext which could either make use of IVerifiable->IMultiVerifiable conversion or be refactored in some other fashion (it also has some Transaction-specific code inside). All the other IVerifiable usage cases are even simpler to adjust, we might even move `GetHashData` into an interface of its own and use it where appropriate.

This is just a rough suggestion on how a protocol-level change could be handled by the current C# code. There are probably some better ways to do that, but the main thing is to make our protocol a little more efficient which would benefit all implementations.

**Neo Version**
- Neo 3

**Where in the software does this update apply to?**
- P2P (TCP)

**Comment by erikzhang** [comment]
This has been discussed before, but it was rejected.

**Comment by erikzhang** [comment]
This is to maintain the consistency of the structure of `IVerifiable`. Both `Block` and `Transaction` implement the `IVerifiable` interface, and both have an array of `Witness`.

**Comment by roman-khimov** [comment]
> This is to maintain the consistency of the structure of IVerifiable

I know (there are references above and yes I've read them all), but it prioritizes implementation details over the protocol and I don't think it's a good choice. We should make the protocol as efficient as possible and then implementations can do whatever they want to on top of that. Also, IVerifiable is just an interface, nothing prevents implementing it with better wire-level encoding.

> Both Block and Transaction implement the IVerifiable interface

And ConsensusPayload.

> and both have an array of Witness

As written above, two out of three IVerifiable implementations always have exactly one witness and will never have more. And again, you can keep it as is, but still make serialized representation a bit more efficient.
