### ISSUE TITLE
Smart contracts in F# tutorials

### ISSUE THREAD

**Issue by pavsh** [neo-project/neo#175]
Hi, there is no examples for how to create F# smart contracts for NEO. Is there any documentation?

**Comment by vncoelho** [comment]
NeoResearch team is currently studying a conversion to the F# compiler.

@igormcoelho recently created some drafts for the conversion in this repository here: https://github.com/NeoResearch/neof

**Comment by igormcoelho** [comment]
Interesting question! As soon as we launch a beta we will let you know @pavsh (almost there ;) )
