### ISSUE TITLE
Plugins need an UnloadPlugin method

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1757]
**Summary or problem description**
Plugins have no mechanism to indicate they can't be unloaded or to programmatically clean them selves up when unloading

**Do you have any solution you want to propose?**
Add an Unload virtual method that returns a boolean. If the plugin can't be unloaded for whatever reason, it returns false. If the plugin needs to do any cleanup work before unloading, it does so and returns true.

Neo Nodes that can dynamically unload plugins will need to be updated to call this new method during unload. neo-cli work tracked by [neo-node issue 619](https://github.com/neo-project/neo-node/issues/619)

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- nodes
- Plugins

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/5952ad22e3d405bed14d51669a2b1e04151724ec/src/neo/Plugins/Plugin.cs#L12

`Plugin` implements the `IDisposable` interface. It's not enough?

**Comment by shargon** [comment]
`Appdomains` doesn't work in dotnet core, so we can't unload an assembly (https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable), we can remove the plugin, and unload the plugin, but the object can persist in memory doing things.

**Comment by devhawk** [comment]
> Plugin implements the IDisposable interface. It's not enough?

IDisposable would be perfect, but as far as I can tell we aren't calling it nor are we removing the plugin from the list of loaded plugins. I guess the expectation is simply that neo-cli needs to be restarted after plugin uninstall?

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/791355c58bdc1fc5d7c1b42a6ab247cbf69cf6d5/src/neo/NeoSystem.cs#L53-L57

**Comment by devhawk** [comment]
@erikzhang We should also be calling dispose on plugins that are unloaded while running.
