### ISSUE TITLE
Abnormal block time per 7 height

### ISSUE THREAD

**Issue by i359** [neo-project/neo#1772]
![image](https://user-images.githubusercontent.com/43022140/87652699-209e9e80-c787-11ea-9f11-e5ce87de285f.png)

**Comment by i359** [comment]
Abnormal block time per 7 height，similar problems have occurred many times before，what‘s happen？

![image](https://user-images.githubusercontent.com/43022140/87653383-07e2b880-c788-11ea-8898-e18a8cce35cb.png)

**Comment by Tommo-L** [comment]
Thanks, we're also waiting for the consensus node to restart.

**Comment by shargon** [comment]
One cn it's down

**Comment by i359** [comment]
How to avoid similar things caused by node failure that greatly extend the block time? thanks！

1. How to monitor the node status and repair in time?

2. If there is a fault node, can it be identified and skipped?

**Comment by i359** [comment]
Abnormal block time per 7 height as below，thanks！

![image](https://user-images.githubusercontent.com/43022140/87864997-e5c48280-c9a1-11ea-881e-9f2bd8ff31a4.png)

**Comment by EdgeDLT** [comment]
This is expected behaviour of dBFT when one of the consensus nodes has failed. There is an exponential backoff on block times to ensure liveness when a node fails to get a block produced and signed within the time limit for a consensus round. It was the failed node's turn to produce a block, it did not, so the next node had to produce it (in the next round, i.e. doubling the block time).

I recommend reading this [paper prerelease](https://github.com/NeoResearch/dbft-report/blob/master/docs/dBFT3_0-Report-NeoResearch-prerelease-20-04-04.pdf), it explains the inner workings and history of dBFT, then goes into current research directions for a "dBFT 3.0" which aims to improve on several aspects, including block time consistency.

**Comment by i359** [comment]
Abnormal block time:

![image](https://user-images.githubusercontent.com/43022140/89113998-6c9d5300-d4aa-11ea-9153-9ca1f9ac2b51.png)

**Comment by i359** [comment]
Abnormal block time，what's happen？

![image](https://user-images.githubusercontent.com/43022140/89117492-cdd81d00-d4d0-11ea-933b-f8e5ccbde755.png)

**Comment by Tommo-L** [comment]
There have been some attacks.

**Comment by i359** [comment]
TPS < 2, is it attack?

**Comment by Tommo-L** [comment]
And also, some of the consensus nodes have timeouts. But they have already been restarted now.

**Comment by i359** [comment]
Hope to see that each block has 1000 + data, and the block is still stable, thanks！

**Comment by i359** [comment]
Abnormal block time，what's happen？

![image](https://user-images.githubusercontent.com/43022140/90117197-289f2d80-dd89-11ea-8316-7d2b44bd1757.png)

**Comment by i359** [comment]
Abnormal block time per 7 height

![image](https://user-images.githubusercontent.com/43022140/90451274-05c0a080-e11e-11ea-9869-2d014180b942.png)

**Comment by vncoelho** [comment]
We plan to solve that with dBFT 3.0.

https://www.mdpi.com/1999-5903/12/8/129
If you have some time to take a look at this paper.
We are polishing the description with some more precise specification for @neo-project/core to move forward with it.

**Comment by i359** [comment]
@vncoelho ，It is ok for long term solution，but now maybe 1 node down some days，need to fix，thanks！

**Comment by Tommo-L** [comment]
> but now maybe 1 node down some days，need to fix

Yes, it'll be restored in next week, one cn node need to update to the latest version.

**Comment by i359** [comment]
Maybe 1 node down，need to fix，thanks！

![image](https://user-images.githubusercontent.com/43022140/92388040-2b532f80-f149-11ea-944a-5a7174fcf27d.png)

**Comment by ProDog** [comment]
Can you describe how you do it? the time shown here is normal:
https://neotube.io/block/6130882/page/1
https://neotube.io/block/6130875/page/1

**Comment by i359** [comment]
Blocktime show as below for your reference, thanks!

https://neoscan.io/blocks/1

**Comment by ProDog** [comment]
This may be a bug of neoscan.

**Comment by i359** [comment]
No, neoscan is OK

![image](https://user-images.githubusercontent.com/43022140/92425716-a4d73600-f1ba-11ea-8556-b054393d8fd8.png)

**Comment by ProDog** [comment]
This is normal😅:
https://dora.coz.io/blocks

**Comment by i359** [comment]
@Tommo-L  ,@shargon ，Maybe 1 node down some days，need to fix, thanks！

![image](https://user-images.githubusercontent.com/43022140/92913383-47164880-f45d-11ea-8287-d1d1a7d1abae.png)

**Comment by Tommo-L** [comment]
Yes, one consensus node lost. 😂  We need to vote for a new consensus node.

**Comment by i359** [comment]
Maybe one consensus node lost，pls dev check and fix， thanks！

![image](https://user-images.githubusercontent.com/43022140/94690475-c3b48c80-0362-11eb-872b-e2f38f265edc.png)
