### ISSUE TITLE
[neox] Old version node won't relay state root, if state root changed beacuse neo upgraded

### ISSUE THREAD

**Issue by KickSeason** [neo-project/neo#1777]
**Summary or problem description**
If state root changed because neo-vm or `mpt` is upgraded, the nodes of the old version will not broadcast the new state root, resulting in messages not reaching some new version nodes.

**Do you have any solution you want to propose?**
Relay after verify successfully, no matter state root is equal with local state root or not.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Ledger
- P2P (TCP)

**Comment by shargon** [comment]
Did you upgraded all the nodes? the compression protocol was changed

**Comment by KickSeason** [comment]
Close this because #1778
