### ISSUE TITLE
Need help. 

### ISSUE THREAD

**Issue by LeonardoDarkVinchi** [neo-project/neo#179]
I`ve tried to find your ports in sourse files, but I faild. Can you give me some advice in my research?

**Comment by LeonardoDarkVinchi** [comment]
Ok I`ve found ports, "thanks for help". Now I stuck at finding genesis hash at your code.

**Comment by shargon** [comment]
https://github.com/neo-project/neo/blob/d8b1b1537e330316e4a6bd2264dcbb7dc1f7e9c5/neo/Core/Blockchain.cs#L74

`GenesisBlock.Hash`

**Comment by LeonardoDarkVinchi** [comment]
Where is Genesis Block take value? In code I mean.
