### ISSUE TITLE
Vote without Register the candidate, then the Account is not able to Transfer NEO

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1790]
**Describe the bug**
When the account vote for an account which is not candidate yet, then relay the vote transaction, then try to send some neo to other accounts. it fails.

**To Reproduce**
1. Open a wallet, send 100 neo(to vote)/100 gas (ensure it has enough fee to pay)
![58f2d080a469c1e08075280cd3c7d4b](https://user-images.githubusercontent.com/34291844/88250332-dca51f80-ccd9-11ea-8976-e0db21bdcb00.png)

2. Then vote, choose the wallet default address and default pubkey
3. Then relay the transaction.
![6bccfcb396e1505783cc7b2db565332](https://user-images.githubusercontent.com/34291844/88250346-ed559580-ccd9-11ea-8d4c-e323a8fed118.png)

4. send neo to other account(not the default address)
![bef33d1569da4fa43072971feeec808](https://user-images.githubusercontent.com/34291844/88250349-efb7ef80-ccd9-11ea-80c8-c1999cb74c58.png)

**Expected behavior**
send neo successful.

**Platform:**
 - OS: [Windows 10 x64
 - Version master 

Root Cause Analysis:

https://github.com/neo-project/neo/blob/5406085af441bdf916a735b676bfbc67cf10cdc9/src/neo/SmartContract/Native/Tokens/NeoToken.cs#L40-L49

because CreateStorageKey(Prefix_Candidate).Add(state.VoteTo) is null.

debug version: 
```cs
        protected override void OnBalanceChanging(ApplicationEngine engine, UInt160 account, NeoAccountState state, BigInteger amount)
        {
            Console.WriteLine(account.ToString());
            Console.WriteLine(state.ToString());
            DistributeGas(engine, account, state);
            if (amount.IsZero) return;
            if (state.VoteTo != null)
            {
                Console.WriteLine(state.VoteTo.ToString());
                if (CreateStorageKey(Prefix_Candidate) is null)
                    Console.WriteLine("create storage key is null");
                if (CreateStorageKey(Prefix_Candidate).Add(state.VoteTo) is null)
                    Console.WriteLine("add state.voto is null");
                if (engine.Snapshot.Storages.GetAndChange(CreateStorageKey(Prefix_Candidate).Add(state.VoteTo)) is null)
                    Console.WriteLine("can not find state.voteTo Storage");
                engine.Snapshot.Storages.GetAndChange(CreateStorageKey(Prefix_Candidate).Add(state.VoteTo)).GetInteroperable<CandidateState>().Votes += amount;
                engine.Snapshot.Storages.GetAndChange(CreateStorageKey(Prefix_VotersCount)).Add(amount);
            }
        }
```

https://github.com/neo-project/neo/blob/5406085af441bdf916a735b676bfbc67cf10cdc9/src/neo/SmartContract/Native/Tokens/NeoToken.cs#L165-L172

**Comment by cloud8little** [comment]
@shargon @Tommo-L could you help review it?

**Comment by Tommo-L** [comment]
Wait for me, I'll help fix it.

**Comment by Qiao-Jin** [comment]
This is caused by the follows:
When an account votes, it's AccountState.VoteTo in storage is changed, but as it votes to a non candidate, we don't record this voting:

https://github.com/neo-project/neo/blob/daa6e7a3b95524534107cfb6e174d9a52f3cd617/src/neo/SmartContract/Native/Tokens/NeoToken.cs#L169

But afterwords when func OnBalanceChanging is called, we assume that this voting is recorded:

https://github.com/neo-project/neo/blob/daa6e7a3b95524534107cfb6e174d9a52f3cd617/src/neo/SmartContract/Native/Tokens/NeoToken.cs#L46

which gives rise to problems.
