### ISSUE TITLE
Should enable setting more current hard-coded figures in PolicyContract

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1794]
**Summary or problem description**
There are still many hard-coded figures such as Transaction.MaxTransactionSize, Transaction.MaxTransactionAttributes, etc. If we want to change these values in the future when neo3 is online, there will be not better method other than hard fork.

**Do you have any solution you want to propose?**
Maybe we can include figures that will be possibly modified in the future into PolicyContract, so that price to change these values would be much lower.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Consensus
- CLI
- Plugins
- Ledger
- Network Policy

**Comment by shargon** [comment]
I agree to move these values ​​to the Policy.
