### ISSUE TITLE
Default type of AnalogSignal units is WRONG

### ISSUE THREAD

**Issue by Christian-B** [neo-project/neo#1797]
**Describe the bug**
AnalogSignal init has units=None
However Quantity has units=''

**To Reproduce**
import neo
import numpy
import quantities

signal = numpy.asarray([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
a = neo.AnalogSignal(signal, sampling_period =1 * quantities.ms)

**Comment by igormcoelho** [comment]
Dear @Christian-B , this question is likely related to another repository, the Neural Ensemble: http://neuralensemble.org/neo

It looks like their repository on Python is: https://github.com/NeuralEnsemble/python-neo

This is Neo Blockchain repository, not quite data science ;)

Good luck!
