### ISSUE TITLE
Extend 4 consensus to 7 consensus via voting will make 6 consensus and 1 watchOnly [2.x, neox-2.x]

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1799]
**Describe the bug**
When I'm making stability test , I found extending 4 consensus to 7 consensus via voting will only make 6 consensus. And when switching this, consensus nodes will display  `Index was outside the bounds of the array` but will be normal after restarting.

**To Reproduce**
1. Create a private of 4 consensus nodes. (The protocol.json contains 4 pubkeys)
2. Create another 3 candidates' wallet and enroll the 7 addresses as candiadte addresses with 1000 gas paid. (via neo-gui)
3. Vote for these 7 addresses.
![image](https://user-images.githubusercontent.com/38493437/88614051-78ab9e00-d0c1-11ea-8216-dbab608f49cb.png)
4. Make sure the 7 addresses already have ballots via RPC- getvalidators. 

**Expected behavior**
You can see only 6 nodes became validators and the other is watchOnly.
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "publickey": "0213b7cfbfabe6a9df59fd365f8454e8d48c2f5b907f1c8b8e5653df1cca28ad73",
            "votes": "99998999",
            "active": true
        },
        {
            "publickey": "0252f604a8aa512b4a012256e7e7e46fa1ccc15c3f351545bd91ca2e8fe54a6ddf",
            "votes": "99998999",
            "active": true
        },
        {
            "publickey": "0266b915a3c770f8aaeac3dbc40fb9c98f60cd7d03ca40984484323d2d648a1498",
            "votes": "99998999",
            "active": true
        },
        {
            "publickey": "02b4713b2080515cb40f893c88e50dbcd8ac8e5ab81350595ca6c4c92af12328d6",
            "votes": "99998999",
            "active": true
        },
        {
            "publickey": "02bcd3f2a5429f566d0833f817374abd2513785b1e95e2a1002e1642ba8194eee3",
            "votes": "99998999",
            "active": true
        },
        {
            "publickey": "02eb3940d866075d4b6e5cebf3ff92d629f866eac4d6d587ca7a96b7270d0cbaee",
            "votes": "99998999",
            "active": true
        },
        {
            "publickey": "02f650e4f311384304ae9b1299408e5974707014bf5fca42ae34cf2827d9f4d9de",
            "votes": "99998999",
            "active": false
        }
    ]
}
```
And `Index was outside the bounds of the array` was displayed on nodes.
![image](https://user-images.githubusercontent.com/38493437/88614891-4d29b300-d0c3-11ea-9c9e-81d7866b5b1d.png)

**Comment by KickSeason** [comment]
The cause of the exception is here:
https://github.com/neo-project/neo/blob/75df7cdaeffc84cd116d907ceda11054be696af3/neo/Consensus/ConsensusContext.cs#L279-L284

If validators count changed after vote, `LastSeenMessage` won't be re-new. This will cause the `ValidatorIndex` outside the bounds of `LastSeenMessage `.

**Comment by vncoelho** [comment]
Nice catch, guys!

**Comment by KickSeason** [comment]
@superboyiii Close?

**Comment by superboyiii** [comment]
> @superboyiii Close?

Sure.
