### ISSUE TITLE
Stable connection can make node stop sync (master-2.x, neox-2.x)

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1806]
**Describe the bug**
In stable network, if the connected peers are always there, peers' height will not often refresh which makes the node can't ask for the latest height and stop sync. Although we have ping pang mechanism, it needs at least one peer disconnected.

**To Reproduce**
1. Prepare a stable network, docker is better and connect stable peers.
2. Run a node on testnet (v2.10.3)
3. Wait for several hours, will reproduce in one day.

**Expected behavior**
Not sync anymore but restarting node is OK.

**Comment by shargon** [comment]
Did you tested if it's reproducible in neo3?

**Comment by superboyiii** [comment]
> Did you tested if it's reproducible in neo3?

I can't reproduce it even in neo2, but someone reflect it to me.

**Comment by vncoelho** [comment]
Probably this is related to https://github.com/neo-project/neo/issues/2059
