### ISSUE TITLE
Inconsistent GetBlockByIndexPayload limit 

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1813]
**Summary or problem description**
The P2P protocol handler uses a lower valid limit for the `count` field of `GetBlocksByIndexPayload` then when deserializing the payload. Specifically 500 vs 2000. 

This means that network deserialization allows requesting 2000 blocks, but will only return 500. This is both inconsistent and a waste of resources as we could abort early during deserialization. Caused by https://github.com/ShawnYun/neo/commit/d17dd27b84b8594f6f6cb9844b913d8b42518c4d#diff-08dcfdb6c144e3ff0a4a26f39acb8040 

https://github.com/neo-project/neo/blob/3da56f0e91f852423c75c5d9b99cd4c70b9f3c6a/src/neo/Network/P2P/Payloads/GetBlockByIndexPayload.cs#L27

whereas the protocol handler looks at `InvPayload.MaxHashesCount`
https://github.com/neo-project/neo/blob/3da56f0e91f852423c75c5d9b99cd4c70b9f3c6a/src/neo/Network/P2P/RemoteNode.ProtocolHandler.cs#L192

The former is set to 2000
https://github.com/neo-project/neo/blob/3da56f0e91f852423c75c5d9b99cd4c70b9f3c6a/src/neo/Network/P2P/Payloads/HeadersPayload.cs#L8

whereas the latter is set to 500
https://github.com/neo-project/neo/blob/3da56f0e91f852423c75c5d9b99cd4c70b9f3c6a/src/neo/Network/P2P/Payloads/InvPayload.cs#L10

**Do you have any solution you want to propose?**
Set the deserialization limit to `InvPayload.MaxHashesCount` similar to the protocol handler. 500 blocks was the old behaviour and should be enough for 1 request.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Network Policy
- P2P (TCP)

**Comment by erikzhang** [comment]
For headers, the value is `2000`. For blocks, the value is `500`.

**Comment by ixje** [comment]
I didn't realise `OnGetHeadersMessageReceived()` changed its payload.
