### ISSUE TITLE
TX deserialization - validate first signer is FeeOnly?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1817]
**Summary or problem description**
I'm not entirely sure what the docstring on `WitnessScope.FeeOnly` means, but the following suggests we expect the first signer to always be the sender.
https://github.com/neo-project/neo/blob/3da56f0e91f852423c75c5d9b99cd4c70b9f3c6a/src/neo/Network/P2P/Payloads/Transaction.cs#L94-L97
 During deserialization we validate that signers with indices `> 0` can't be `FeeOnly`, but we don't actually validate that the first signer _is_ `FeeOnly`. Should we check this? @shargon 

https://github.com/neo-project/neo/blob/3da56f0e91f852423c75c5d9b99cd4c70b9f3c6a/src/neo/Network/P2P/Payloads/Transaction.cs#L178-L185

**Do you have any solution you want to propose?**
add first signer is sender check e.g.
```C#
                if (i == 0 && signer.Scopes != WitnessScope.FeeOnly)
                    throw FormatException();
``` 

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by shargon** [comment]
The first signer could be feeOnly or don't, but fee only it's only allowed in the first signer. Other scope like global can be used for senders

**Comment by ixje** [comment]
ah I see. Thanks for explaining
