### ISSUE TITLE
Add test-mode for benchmark log & testing

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1840]
**Summary or problem description**
Current system log is too simple for tester & benchmark. Besides changeview, it's hard to know the real situation of a node / transports between nodes. A tester / benchmark report would need logs about something as follows:

Has this node receives INV / GetData / raw data messages of specified blocks?
Has this node receives specified consensus messages (Prepare request / response, commit, changview, etc)?
Is this node persisting a block? Which persisting step is it at?
Is it establishing / closing a connection between some node?
What's the TPS of this block?
How many transaction inv / transaction getdata / transaction data messages has the node received / verified in this block period / totally?
How many transactions are in mempool?
......

**Do you have any solution you want to propose?**
We need to add a test mode which will log info described above. Such info will ONLY occur in test mode. We can specify whether to use test mode in NeoSystem constructor.

Besides, we might need to some plugin for the convenience of TPS testing as decribed [here](https://github.com/neo-project/neo-modules/issues/320).

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Plugins
- Ledger

**Comment by shargon** [comment]
We use a plugin for this purpose in neo-resilience https://github.com/Red4Sec/neo-resilience/tree/master/src/NeoStatsPlugin
