### ISSUE TITLE
Sort BlockedAccounts

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#1841]
**Summary or problem description**
There is a check for blocked accounts in `VerifyForEachBlock()`:

```c#
            if (NativeContract.Policy.GetBlockedAccounts(snapshot).Intersect(hashes).Any())
                return VerifyResult.PolicyFail;
```

It's being made for every transaction, so it's in the hot path for transaction processing. This check gets blocked accounts from the native policy contract which in turn just deserializes the array got from the storage. This array is modified by `BlockAccount()/UnblockAccount()` that append/remove a hash to/from the array. I wouldn't expect these to be called a lot, so we have a case of rarely modified, but frequently used array.

The check itself is probably unnoticeable with any kind of profiling because we don't usually have any blocked accounts. But if we're to have them that would mean that we'll need to check for presence of a list of hashes in another list of hashes with `Intersect().Any()`. In most of the cases we can expect it to be a "big" list of blocked accounts and one sender/signer account.

If we're to look into [how `Intersect()` works](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/Intersect.cs), it creates a hash set for the second argument and iterates over the first one to try to find if it's in the set (and return an element if it's there for `Any()` to catch). Given how it's implemented it'd probably be better to swap the arguments to create a hash set for bigger array, but even if we're to do that the set would be created and populated for each verified transaction, which I think is a bit more overhead than we want.

**Do you have any solution you want to propose?**
We can improve blocked accounts handling by sorting them in `BlockAccount()/UnblockAccount()` and using binary search in `VerifyForEachBlock()` (probably there is some nice LINQ incantation for that too). This avoids all `Set` maintenance cost in the hot path while adding some overhead to blocking/unblocking functions (but those are not expected to be called frequently).

In fact, that's what we already do in neo-go, but the problem is that it makes `StorageItem` value technically different from C# node's one even though the accounts stored there would be the same.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: Native Policy Contract

**Comment by shargon** [comment]
Please take a look to https://github.com/neo-project/neo/pull/1843
