### ISSUE TITLE
Some message cause NullReferenceException which make mainnet nodes stop syncing (2.10.3)

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1842]
**Describe the bug**
Some message cause NullReferenceException which makes mainnet nodes stop syncing (2.10.3), but restart is OK.

**To Reproduce**
Run a node on mainnet 

**Expected behavior**
Display the exception(not frequently), block won't be synced anymore but restart can fix this.

**Screenshots**
![image](https://user-images.githubusercontent.com/38493437/90207049-dc4efe80-de17-11ea-81fa-4ff714457f41.png)

**Platform:**
 - OS: [centOS 7.4, ubuntu 16.04]
 - Version [2.10.3]

**Comment by shargon** [comment]
This doesn't happend in testnet?

**Comment by superboyiii** [comment]
> This doesn't happend in testnet?

Not meet yet, maybe testnet doesn't have enough variety of P2P messages. Mainnet has more diversification.

**Comment by Tommo-L** [comment]
It's same with https://github.com/neo-project/neo/issues/2088
