### ISSUE TITLE
What are the intended rules for checking multi-signatures (SYSCALLs)?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1849]
I'm talking specifically about this code

https://github.com/neo-project/neo/blob/b4daa6d7dc00b228e8851b0198d7222d5248d1e4/src/neo/SmartContract/ApplicationEngine.Crypto.cs#L81-L102

At first I thought the rules are
- the public key count must be equal or bigger than the signature count
- for each signature, try verifying with public keys until 1 match is found

However, there is some strange behaviour depending on what is supplied to the function

Let's assume sig1 is created with key1 and sig2 with key2

**1. OK - 1 to 1 match**
signatures = (sig1, sig2)
public_keys = (key1, key2) 
verification result = True
This tries `sig1 + key1` and `sig2 + key2`

**2. OK - 1 sig, 2 keys supplied out of order**
signatures = (sig1, )
public_keys = (key2, key1)
verification result = True
This cycles over all available public keys and tries to verify `sig1` with it. (this matches the check in Line 90, where more public keys than signatures are allowed, but not the other way around)

**3. Strange  - 2 signatures, 2 keys (keys again out of order)**
signatures = (sig1, sig2)
public_keys = (key2, key1)
verification result = False
This only does 1 verification try with `sig1 + key2` and aborts if failed, instead of trying `sig1 + key1` next

This last example is strange, because if we supply an equal amount of keys  as signatures, suddenly the pairs _must_ be in order, where in example `2.` this wasn't the case.

So what should be the actual rules?
- for each signature try all available public keys?
- or the signatures and keys must be supplied in the correct order (as pairs) and try exactly one time e.g. `verifysignature(message, signatures[i], keys[i])`

**Comment by ixje** [comment]
Some code to play around
```C#
            var priv_key1 = new byte[]
            {
                0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1,
                0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1,
                0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1,
                0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1,
            };
            var priv_key2 = new byte[]
            {
                0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2,
                0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2,
                0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2,
                0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2, 0x2,
            };
            var kp1 = new KeyPair(priv_key1);
            var kp2 = new KeyPair(priv_key2);
            
            var message = new ByteString(Encoding.UTF8.GetBytes("hello"));
            
            var sig1 = Crypto.Sign(message.GetSpan().ToArray(), kp1.PrivateKey, kp1.PublicKey.EncodePoint(false).Skip(1).ToArray());
            var sig2 = Crypto.Sign(message.GetSpan().ToArray(), kp2.PrivateKey, kp1.PublicKey.EncodePoint(false).Skip(1).ToArray());

            var r1 = Crypto.VerifySignature(message.GetSpan().ToArray(), sig1, kp1.PublicKey.EncodePoint(false), ECCurve.Secp256r1);
            Console.WriteLine($"Verifying sig1 with key1: {r1}");
            var r2 = Crypto.VerifySignature(message.GetSpan().ToArray(), sig2, kp2.PublicKey.EncodePoint(false), ECCurve.Secp256r1);
            Console.WriteLine($"Verifying sig2 with key2: {r2}");

            var public_keys = new byte[][] { kp1.PublicKey.EncodePoint(false), kp2.PublicKey.EncodePoint(false) };
            var signatures = new byte[][] { sig1, sig2 };
            var r3 = CheckMultiSigWithECDsa(message, public_keys, signatures, ECCurve.Secp256r1);
            Console.WriteLine($"Verifying sig1 -> pub1, sig2 -> pub2: {r3}");
            
            // more public keys than signatures
            // note how we swapped public key order, such the first check (sig1 + pub_key2) fails
            public_keys = new byte[][] { kp2.PublicKey.EncodePoint(false), kp1.PublicKey.EncodePoint(false) };
            signatures = new byte[][] { sig1 };
            var r4 = CheckMultiSigWithECDsa(message, public_keys, signatures, ECCurve.Secp256r1);
            Console.WriteLine($"Verifying sig1 -> pub2, pub1: {r4}");
            
            // same public key count as signatures, but out of order
            public_keys = new byte[][] { kp2.PublicKey.EncodePoint(false),  kp1.PublicKey.EncodePoint(false) };
            signatures = new byte[][] { sig1, sig2 };
            var r5 = CheckMultiSigWithECDsa(message, public_keys, signatures, ECCurve.Secp256r1);
            Console.WriteLine($"Verifying sig1, sig2 -> pub2, pub1: {r5}");
```

```
Verifying sig1 with key1: True
Verifying sig2 with key2: True
Verifying sig1 -> pub1, sig2 -> pub2: True
Verifying sig1 -> pub2, pub1: True
Verifying sig1, sig2 -> pub2, pub1: False <-- ???
```

**Comment by roman-khimov** [comment]
> or the signatures and keys must be supplied in the correct order (as pairs) and try exactly one time e.g. 

They have to be ordered, I think it's the same as the old `CHECKMULTISIG` VM instruction in Neo 2 VM. That's why `CreateMultiSigRedeemScript()` orders public keys and `ContractParametersContext.AddSignature()` orders signatures. And the end result is that there are no less than `m` and no more than `n` signature checks done.

**Comment by ixje** [comment]
Yeah I kind of remember the those parts. Now that you mention it, it's probably for 1-of-2, 2-of-3 etc contracts. So if signatures.length == pubkeys.length, then it must require all signatures and the pairs must be provided in order. Otherwise, find if there is _a_ key matching the signature.

**Comment by Tommo-L** [comment]
> So if signatures.length == pubkeys.length, then it must require all signatures and the pairs must be provided in order. Otherwise, find if there is a key matching the signature.

Yes.
