### ISSUE TITLE
Why does ApplicationEngine.Run default to test mode?

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1851]
Prior to #1819, `ApplicationEngine.Run` testMode parameter defaulted to false. Now, the gas parameter defaults to TestModeGas. 

Wouldn't it make more sense to default gas parameter to zero? Or remove the default entirely?

**Comment by Tommo-L** [comment]
>  Or remove the default entirely?

Agree.

**Comment by shargon** [comment]
Yes, I think that we can remove the default value.

**Comment by Tommo-L** [comment]
As this method, how about renaming `TestModeGas` to `DefaultGas` or setting it zero?

https://github.com/neo-project/neo/blob/b4daa6d7dc00b228e8851b0198d7222d5248d1e4/src/neo/SmartContract/ApplicationEngine.cs#L290

**Comment by erikzhang** [comment]
Because in most cases we use test mode.

**Comment by Qiao-Jin** [comment]
I think we should use wallet balance instead of testmodegas, as in common sense the one who tests executing script locally will send corresponding transaction. Furthermore, a 20 gas testmodegas might be not enough for some cases.

**Comment by superboyiii** [comment]
> I think we should use wallet balance instead of testmodegas, as in common sense the one who tests executing script locally will send corresponding transaction. Furthermore, a 20 gas testmodegas might not be enough for some cases.

But this means you'll always return fault if you don't open your wallet when execution. It doesn't make sense.
