### ISSUE TITLE
Should redefine price of OpCode.EQUAL 

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1855]
**Summary or problem description**

OpCode.EQUAL can be a system vulnerability due to current fee model.

This is because of the definition of func [ByteString.Equals:](https://github.com/neo-project/neo-vm/blob/8e1c3b8525cba101eaa1154f11b4fb064aba8eb2/src/neo-vm/Types/ByteString.cs#L21)
![image](https://user-images.githubusercontent.com/43407364/90619680-19662700-e244-11ea-90f1-22f2047bc52d.png)

After testing it shows that 900,000 execution of opcode sequence { LDARG0, LDARG1, EQUAL, DROP } between 2 1048,576-sized ByteStrings will exhaust 100 seconds while cost only 3.44 GAS.

**Do you have any solution you want to propose?**

We should redefine the price of OpCode.EQUAL depending on the size of compared objects.

Or, maybe we should run the sequenceEqual in parallel?

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- OpCode & price model
- VM

**Comment by erikzhang** [comment]
I tested it on my laptop. It took 4 seconds to run `EQUAL` 100,000 times.

**Comment by shargon** [comment]
We can increase the gasPrice 1.5 times when the steps are greater than `x`

**Comment by Qiao-Jin** [comment]
> I tested it on my laptop. It took 4 seconds to run `EQUAL` 100,000 times.

That's still a long time period for 0.2 Gas's cost
