### ISSUE TITLE
tag 95596f93a604f48d0a962b092b143cbdf0769bf5 as v2.11

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1856]
Based on a decompile of the 2.11 neo package on Nuget.org, it appears that 95596f93a604f48d0a962b092b143cbdf0769bf5 is the corresponding source commit for the released package. Can we please tag that commit and/or create a 2.11 release on github?

**Comment by superboyiii** [comment]
@erikzhang Could you add the tag? The last commit of v2.11.0 is [95596f9](https://github.com/neo-project/neo/commit/95596f93a604f48d0a962b092b143cbdf0769bf5) as Harry said.

**Comment by Tommo-L** [comment]
Close?

**Comment by devhawk** [comment]
We should also tag b036def762e5a9751015f3e90e358615fd542304 as v2.12.1 and e18d431760aaa103de5200cbfe3f45aa693361e6 as v2.12.2
