### ISSUE TITLE
Add a check for payload.Count

### ISSUE THREAD

**Issue by ShawnYun** [neo-project/neo#1858]
**Summary or problem description**

In RemoteNode.ProtocolHandler.cs, `OnGetHeadersMessageReceived` Will be triggered when a `MessageCommand.GetHeaders` message is received. 
```
270         private void OnGetHeadersMessageReceived(GetBlockByIndexPayload payload)
271         {
272             uint index = payload.IndexStart;
273             uint count = payload.Count == -1 ? HeadersPayload.MaxHeadersCount : (uint)payload.Count;
274             if (index > Blockchain.Singleton.HeaderHeight)
275                 return;
276             List<Header> headers = new List<Header>();
277             for (uint i = 0; i < count; i++)
278             {
279                 var header = Blockchain.Singleton.GetHeader(index + i);
280                 if (header == null) break;
281                 headers.Add(header);
282             }       
283             if (headers.Count == 0) return;
284             EnqueueMessage(Message.Create(MessageCommand.Headers, HeadersPayload.Create(headers.ToArray())));
285         }
```

It will return the specified number of blocks' headers starting with the requested IndexStart to RemoteNode actor. A limit set by HeadersPayload.MaxHeadersCount is also applied to the number of requested Headers, namely payload.Count.

However, the sanity check only examine whether payload.Count (a short) equals to -1 (default value) and set it to MaxHeadersCount (2000) if so.

Specifically, if we set the payload.Count to -2, which is 4294967294 if converted to a `uint` and bypass the limitation. Every time a node receives the malicious request, it has to look up the requested block headers, which could consumes lots of memories, and cause the victim nodes Out-of-Memory.

**Do you have any solution you want to propose?**

Add a check for payload.Count, make count not greater than 2000.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by erikzhang** [comment]
It is limited here:

https://github.com/neo-project/neo/blob/b4daa6d7dc00b228e8851b0198d7222d5248d1e4/src/neo/Network/P2P/Payloads/GetBlockByIndexPayload.cs#L27-L28
