### ISSUE TITLE
Why are some opcodes with price 0?

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1860]
**Summary or problem description**
It seems that there are some unreasonable price definition in `ApplicationEngine.OpcodePrice`, i.e.

https://github.com/neo-project/neo/blob/b4daa6d7dc00b228e8851b0198d7222d5248d1e4/src/neo/SmartContract/ApplicationEngine.OpCodePrices.cs#L69

Why are some opcodes with price 0 (RET, SYSCALL)? This might be used by malefactors in case of DoS attack, i.e. creating a script manually as follows:

RET
RET
...
RET
JMP (to first RET)

**Do you have any solution you want to propose?**

Set the price to some value higher than 0 while not change normal price logic, say, current price of CALL is 22000, so we can set price of CALL to 20800 and RET to 200, etc.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- SDK
- VM

**Comment by erikzhang** [comment]
The context will be popped when the first `RET` is executed.
