### ISSUE TITLE
Can we support get notify by txid in contract

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo#1861]
**Summary or problem description**
Sometimes we need to get the asset's transfer information in the contract, like a nep5 transfer, we need to get its amount, from and to, but now there seems no way to get it.

**Do you have any solution you want to propose?**
Can we support get notify by txid in contract? or other way to parse the transfer's script in contract.

**Neo Version**
- Neo 3

**Comment by ProDog** [comment]
@roman-khimov Sometimes we need to get a transfer information of asset A in the contract B, transfer information include from, to, value; 

We might even need to get more details about the contract invocation transaction in another contract, where the `System.Blockchain.GetTransaction` method only gets the script of the transaction, but no specific information of contract execution.

Is there an easier method for this scenario?

**Comment by shargon** [comment]
We can store the logs and notifications in https://github.com/neo-project/neo/blob/d9e16e36afcc3a05914591d0d94ea97793e153a4/src/neo/Ledger/TransactionState.cs#L11 , what do you think @erikzhang ?

**Comment by roman-khimov** [comment]
Well, that would be like moving `ApplicationLogs` plugin into the core. Which is absolutely fine for me (we don't have plugins in NeoGo), but it obviously doesn't fit current model of core/plugins split in C# node.

That's why I'm trying to understand what real-world scenario may need this. Contracts can cooperate on-chain calling each other, if they do, there is no such problem. If they don't, then something needs to watch for events off-chain and react on them. Probably this reaction would be invoking another contract, but that's a transaction and any data from notification that triggered it can be passed via invocation parameters. So do we really have a problem here?

**Comment by ProDog** [comment]
I think it would be better to have an api for this, no matter how to implement it.😅

**Comment by devhawk** [comment]
I've been doing some thinking about the real-world scenarios that @roman-khimov brings up, using Nep-5 tokens and the RpcNep5Tracker as a guide. RpcNep5Tracker provides two capabilities:

1. Provide a list of tokens owned by a given account
2. Provide a history of transfers for a given token and account 

These capabilities are absolutely required for any real-world wallet. No real-world user would use a wallet that didn't provide historical transfer data or required them to remember the list of tokens they owned. Yet, this data is not stored in the chain directly. Instead, we use a plugin to listen to contract notifications and store the data needed to provide these capabilities off chain. That seems like the wrong approach.

We could make this data available on chain purely via contracts. For transfer history, it would be possible for a token contract like NEP-5 to store transfer history per account. For a list of owned tokens, we could build a token registry contract that a token contract could invoke when an account balance was updated.

On the other hand, storing log/notification information on chain in a programmatically available manner (i.e. what @ProDog is asking for) is also an interesting idea. That might be more generalizable and having that data off chain might enable usage scenarios like wallets.

**Comment by erikzhang** [comment]
> We can store the logs and notifications in

The logs and notifications are cheaper then storages. That's why they are not stored in the database and can't be accessed by smart contracts.

**Comment by ProDog** [comment]
The actual demand is: in the contract, can we provide a way to get the script details of another invoke contract tx?
So it doesn't have to be get notify.
