### ISSUE TITLE
Should adjust some opcode price

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1863]
**Summary or problem description**

Price of some opcodes should be adjusted to prevent DoS attack as shown below:

(1) EQUAL

Opcode EQUAL can be severely time exhausting for ByteString. Detailed info can be seen in #1855 .

(2) REVERSEN & REVERSEITEMS

Currently price of Opcode.REVERSEN is 400 GasFactor. After testing, it shows running `EvaluationStack.Reverse(2048)` on a 2048-sized context for 250,000 times (which means 1 GAS) will assume 1 second, which is somehow too long for 1 Gas.

(3) NEWBUFFER

Currently the maximum size of a buffer is defined to be 1Mb. As the MaxStackSize = 2048, that means by NEWBUFFER as much as 2GB's RAM can be exhausted with merely 1.64 GAS.

(4) NEWARRAY & NEWARRAY_T

Similiar with NEWBUFFER, here as much as 2GB's RAM can be exhausted with merely 0.3 GAS.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- SDK
- VM

**Comment by Qiao-Jin** [comment]
Is 1 second per GAS price standard by design? Maybe this is somehow too cheap to prevent attack by malfactors.

**Comment by erikzhang** [comment]
> Is 1 second per GAS price standard by design?

Yes.

**Comment by Qiao-Jin** [comment]
Closed as these are by design

**Comment by roman-khimov** [comment]
> > Is 1 second per GAS price standard by design?
> 
> Yes.

Then 1 GAS should cost something close to 0.0000166667 USD?
