### ISSUE TITLE
Modify Domain Model representation for Best Debugger Experience

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1864]
## Objective

To enable the Neo 3 Debugger to provide a developer experience for domain model
instances that is on par with the existing Neo 2 debugger developer experience.

## Problem

In Neo 2, domain model instances such as Block and Transaction were stored in
Neo.VM as InteropInterface StackItems. Because the full domain model instance
was stored in the VM, the debugger could determine the underlying domain model type
for a given stack item and provide a rich name/value pair list of the domain model's
properties in the debugger variable window.

In Neo 3, domain model instances are now converted into a Neo.VM array StackItem for use
in Neo.VM. Because of this, the debugger can no longer determine that a given stack item
is a domain model instance at runtime. As such, we lose both the field names as well as
optimal representation of the field values in the debugger variable window. 

While there will be cases where the variable type will be available via debug info, a more robust
solution would enable the debugger to identify specific domain objects at runtime.

## Proposal

If the debugger can identify the specific domain type a given stack item Struct represents
at runtime, it can provide the better developer experience in the variables window.

If we update Stuct StackItem to carry an optional type information string, we can update 
IInteroperable.ToStackItem implementations to convert domain objects to a Struct rather 
than an array + associate the correct domain type information needed by the debugger.

Struct StackItem type needs to be updated to carry an optional type information 
string. This change to NeoVM is tracked by https://github.com/neo-project/neo-vm/issues/366.

## Neo Version
- Neo 3

## Software Area
- SDK
- VM

**Comment by erikzhang** [comment]
Making `StackItem` carry type information is only useful for debugging purpose and will degrade performance in most cases. I have a solution that can get these type information without modifying the system. By implementing the `PreExecuteInstruction()` and `PostExecuteInstruction()` methods of the `Neo.SmartContract.IDiagnostic` interface, the debugger can determine the type information of the `StackItem`s on the stack according to which SYSCALL or native contract is currently being executed.

**Comment by devhawk** [comment]
This is not really needed any more. [Storage Schema](https://github.com/neo-project/neo-debugger/blob/master/docs/storage-schema-overview.md) version of debugger + compiler makes this pretty unnecessary

**Comment by erikzhang** [comment]
Closed because it is no longer needed.
