### ISSUE TITLE
But with the swap tool: swap.effect.ai

### ISSUE THREAD

**Issue by Smeilz** [neo-project/neo#1868]
**Describe the bug**
The project developers say that it is impossible to make a swap due to problems on the Neo side.

**To Reproduce**
Neo tokens cannot be burned, because the NEO node is not syncing.

**Expected behavior**
Burning the NEO token and simultaneously creating an EOS token

**Additional information
Could you explain why the neo/eos swap doesn't work? And when can this problem be solved?
adresse swap: https://swap.effect.ai

**Comment by superboyiii** [comment]
@Smeilz They need resync a node based on v2.11.0

**Comment by Smeilz** [comment]
In v2.11.0 sync is working?

**Comment by EdgeDLT** [comment]
Yes, I have done so myself.

**Comment by superboyiii** [comment]
> In v2.11.0 sync is working?

Must be working.

**Comment by shargon** [comment]
It's solved?

**Comment by EdgeDLT** [comment]
No issue on Neo side, I think it can be closed.
