### ISSUE TITLE
Isn't the price of voting too high?

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1877]
**Summary or problem description**

Current voting price is 5 GAS, no matter how much NEO the voter holds. So what is the voting incentive of NEO holders with only a few NEO? What they will get after voting can be far more less than what they need to pay for voting.

**Do you have any solution you want to propose?**

We should redefine the voting fee.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Governance

**Comment by shargon** [comment]
I think that all prices should be recalculated

**Comment by diskooooo** [comment]
Also think about what happens if GAS goes back to $100 at one point? In that case casting a vote will be $500, surely way too much. Will prices/fees be made adjustable based on market conditions?

**Comment by Qiao-Jin** [comment]
> I think that all prices should be recalculated

Any plan about redefining price of interops?
