### ISSUE TITLE
Incorrect GasConsumed returned by InvokeScript for template NEP-5 Mint operation

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1882]
I'm attempting to invoke the [Mint operation](https://github.com/neo-project/neo-devpack-dotnet/blob/master/templates/Template.NEP5.CSharp/NEP5.Crowdsale.cs#L26) if the NEP-5 template contract. My transaction script transfers 10 NEO and 10 GAS to the NEP-5 script hash before invoking the Mint operation. TransactionManager.MakeTransaction calls InvokeScript to retrieve the GasConsumed value. However, when the transaction is then submitted via SendRawTransaction, the transaction fails due to insufficient gas. Manually increasing the SystemFee resolves the issue. 

GAS consumed returned by InvokeScript was 27416520. GAS consumed by SendRawTransaction was 36563580.

**Comment by wanglongfei88** [comment]
@devhawk Harry, is this for Neo3 ？

**Comment by devhawk** [comment]
Yes, neo 3

**Comment by wanglongfei88** [comment]
Maybe @ProDog & @superboyiii can help to double check this issue and identify the exact problem ?

**Comment by cloud8little** [comment]
I will have a check.

**Comment by cloud8little** [comment]
@devhawk  do you use RPCClient or just invokescript for rpc call? I got the same gasconsumed, which equals to sysfee of the transaction, but I change the function of RpcServer a bit. because they are different execution if not change.

RpcServer: 

https://github.com/cloud8little/neo-modules/blob/4ea9602fd1757f326a1d36ef2a39ed34df95b97b/src/RpcServer/RpcServer.SmartContract.cs#L66-L75

 ```cs
private JObject GetInvokeResult(byte[] script, Signers signers = null)
        {
            Transaction tx = new Transaction
            {
                Signers = signers.GetSigners(),
                Witnesses = System.Array.Empty<Witness>(),
                Attributes = System.Array.Empty<TransactionAttribute>(),
                Version = 0,
                Script = script
            };
            //using ApplicationEngine engine = ApplicationEngine.Run(script, container: signers, gas: settings.MaxGasInvoke);
            using ApplicationEngine engine = ApplicationEngine.Run(script, container: tx, gas: settings.MaxGasInvoke);
```
Mint: 
https://github.com/ProDog/neo-node/blob/all_commands/neo-cli/CLI/MainService.Other.cs#L16

```cs
            byte[] script;
            using (ScriptBuilder scriptBuilder = new ScriptBuilder())
            {
                //scriptBuilder.EmitAppCall(NativeContract.NEO.Hash, "transfer", sender, to, (BigInteger)10);
                scriptBuilder.EmitAppCall(asset, "transfer", sender, to, (BigInteger)(decimal.Parse(amount) * (decimal)Math.Pow(10, descriptor.Decimals)));               
                scriptBuilder.EmitAppCall(scriptHash, "mint");
                script = scriptBuilder.ToArray();
                Console.WriteLine($"Invoking script with: '{script.ToHexString()}'");
            }

            Transaction tx = new Transaction
            {
                Signers = signers,
                Witnesses = Array.Empty<Witness>(),
                Attributes = Array.Empty<TransactionAttribute>(),
                Version = 0,
                Script = script
            };

            using ApplicationEngine engine = ApplicationEngine.Run(script, Blockchain.Singleton.GetSnapshot(), container: tx);
            PrintExecutionOutput(engine, true);
```

Result:
![c457766f15d5b91024c3bae8c63d6b8](https://user-images.githubusercontent.com/34291844/91972679-9bc70e80-ed4d-11ea-8ac9-77833c5aa857.png)
![c15d12c8a38d2ae92b7aafe4f0f8161](https://user-images.githubusercontent.com/34291844/91972695-9ff32c00-ed4d-11ea-83f7-55ea013ae691.png)

**Comment by shargon** [comment]
It could be related to https://github.com/neo-project/neo-modules/issues/311

**Comment by devhawk** [comment]
@cloud8little I am generating the script via custom code in neo-express, but then creating/signing the tx with TransactionManager and submitting via RpcClient

``` csharp
var tm = new TransactionManager(rpcClient)
    .MakeTransaction(script, signers)
    .AddSignatures(chain, account)
    .Sign();

return rpcClient.SendRawTransaction(tm.Tx);
```

> Note, the AddSignatures extension method is specific to neo-express. It takes neo-express chain object and calls the AddSignature/AddMultiSig as appropriate for the operation.

**Comment by shargon** [comment]
It was fixed?

**Comment by devhawk** [comment]
> It was fixed?

I'm on vacation until Oct 26th. Someone else is going to have to check

**Comment by cloud8little** [comment]
> > It was fixed?
> 
> I'm on vacation until Oct 26th. Someone else is going to have to check

@devhawk did you check if the issue still exist?
