### ISSUE TITLE
When is Neo3.0 going to be released?

### ISSUE THREAD

**Issue by hzccc** [neo-project/neo#1894]
We are ready to support NEO in the wallet

**Comment by little-fish-foundation** [comment]
neo 开发者技术交流 有微信或者QQ群吗？

**Comment by Tommo-L** [comment]
@little-fish-foundation   

wechat: neochain

**Comment by luchotrapani** [comment]
hi guys... some of you maybe can help me. I can not transfer my assets from my neowallet.

**Comment by Tommo-L** [comment]
@luchotrapani It's recommend to use neoline, o3, neon wallet. Did you succeed?
