### ISSUE TITLE
GAS incentive

### ISSUE THREAD

**Issue by JoaoPLGomes** [neo-project/neo#1899]
Hello, I'm just a community member and would like to know if there are any plans to incentive holding GAS in Neo 3.0 ?

From what I can see there are none since the plan at the moment is to make it inflationary so there's incentive to spend it.

Thank you and keep up the good work :)

**Comment by vncoelho** [comment]
Hi @JoaoPLGomes,

    You are right, as it is agreed until right now it is going to still be inflationary (just notice that it is also inflationary on Neo2, the only change until right now is on the fixed rate of generation. On the other hand, some GAS from system fees will be burn). 
    The main incentive is for holding NEO and voting, being active in the governance of the Ecosystem.
    In addition, there will be extra GAS reward for Consensus Committee, including node Validators and the Decision-Making Committee.
  
    But as you may see, it is still on final stages of development and the code and discussions are reaching master right now.

Best regards,

**Comment by JoaoPLGomes** [comment]
@vncoelho Thank you for responding, yes that makes sense.

Another question about GAS inflation, I'm not sure if I'm saying something wrong but from what I read the number of GAS generated will always be bigger than the GAS burned ?

I know this is not totally decided yet, just trying to check what is being planned :)

**Comment by vncoelho** [comment]
I am not sure about this balance, perhaps it depends on the use of the Blockchain.
There still missing points the community is trying to improve within these next weeks.

**Comment by JoaoPLGomes** [comment]
It would be interesting to see if there is a possibility of deflation if enough transactions are made.

**Comment by Tommo-L** [comment]
>  if there are any plans to incentive holding GAS in Neo 3.0 ?
  
@JoaoPLGomes  You can deposit GAS/NEO in some DeFi farm projects, like [Flamingo](https://flamingo.finance/), [YFI](https://yearn.finance/) etc.

**Comment by LG55** [comment]
hello i got a question, is it better for 3.0 that gas price is low? After all GAS is the main thing in NEO ecosystem, if the GAS price is low holders wont want to hold it anymore, tx can still be cheap and gas price high as it is dividible? tnx
