### ISSUE TITLE
help！，Private chain consensus failed, 

### ISSUE THREAD

**Issue by hunjixin** [neo-project/neo#191]
4 container run in docker 

neo01   172.17.0.2
neo02    172.17.0.4
neo03    172.17.0.5
neo04    172.17.0.6

protocol.json

![2018-03-12 00-10-32](https://user-images.githubusercontent.com/13759392/37255627-e55d3788-2589-11e8-9189-9ee9928acd6c.png)

result：

![2018-03-11 23-52-46](https://user-images.githubusercontent.com/13759392/37255581-4bcef408-2589-11e8-819f-7d37d88b56cb.png)

**Comment by goktugyil** [comment]
Got the same

**Comment by goktugyil** [comment]
I got something similar, how can we solve this?

**Comment by hunjixin** [comment]
delete Chain folder in the run directory
