### ISSUE TITLE
OnPersist semantics for native contracts

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#1913]
**Summary or problem description**
#751 has brought with it a new method for native contracts, `OnPersist`, and added a call to it into persisting logic. It did so with an explicit whitelist of contracts to call this method for, back then it included all existing contracts. Later (with #758) a Policy contract was added, but it wasn't included in this list as it has no actions required to do when persisting a block.

Policy contract technically still has an `OnPersist` method inherited from `NativeContract` that is visible in its manifest. And supposedly any new native contract will have it too, but at the same time it won't automatically be called when persisting a block which makes it a little unclear what was the real intention here.

**Do you have any solution you want to propose?**
If we want all native contracts to have `OnPersist` that would be called when persisting a block then this method should be called for all of them (iterating over `NativeContract.Contracts` probably, instead of explicit whitelist).

If we don't expect all contracts to have `OnPersist`, then it shouldn't be present in the `NativeContract` class, this way Policy won't have it in the manifest and we can actually make a decision on whether to call `OnPersist` for a contract or not based on its manifest (which either will have it or not).

In any event, I expect all native contracts to be treated the same way wrt this method, whitelisting shouldn't be used if it's a generic native contract feature.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Native contracts

**Comment by roman-khimov** [comment]
Also relevant for `postPersist`, btw.

**Comment by fyrchik** [comment]
I am up for the first solution (calling it for all contracts). In `postPersist` we may also want to update some cached values for all contracts. Right now in `neo-go` we do this in a separate method which updates cache for `Policy`, `Neo` and `Oracle` contracts, but is reasonable to assume, every contract may want to do similar things after block has been persisted.

**Comment by roman-khimov** [comment]
Solved by #2119.
