### ISSUE TITLE
We should include Transaction.Witness when calculating hash

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1914]
**Summary or problem description**

Currently when we calculate the hash of a transaction, we don't include its witnesses:

https://github.com/neo-project/neo/blob/4066a4f3986a71612dcdeca33a4ecf8934511247/src/neo/Network/P2P/Payloads/Transaction.cs#L65

https://github.com/neo-project/neo/blob/4066a4f3986a71612dcdeca33a4ecf8934511247/src/neo/Network/P2P/Helper.cs#L28

https://github.com/neo-project/neo/blob/4066a4f3986a71612dcdeca33a4ecf8934511247/src/neo/Network/P2P/Helper.cs#L20

https://github.com/neo-project/neo/blob/4066a4f3986a71612dcdeca33a4ecf8934511247/src/neo/Network/P2P/Payloads/Transaction.cs#L249

With such logic 2 transactions which are same except witnesses, will share the same hash. Even though at least one of them will be verified as false, this can be used to play some tricks.

Let's suppose there are a transaction T which is a legal one. We create another one, T1, by only changing the value of T's witnesses and apparently T1 will not pass verification. Suppose we have some validator neighbors. We keep watching the `PrepareRequest` from the speaker, and upon receiving we will send fake transactions whose hash is also contained in the `PrepareRequest`, to validator neightbors. These transactions will not pass verification as expected by these validators, and **they will try to change view so that consensus is compromised**.

**Do you have any solution you want to propose?**

We should include Transaction.Witness when calculating hash

**Neo Version**

- Neo 3

**Where in the software does this update applies to?**
- Consensus

**Comment by erikzhang** [comment]
This is the expected result. You can only attack a single node in this way, not the entire network. Because transactions that cannot be verified will not be broadcast. There are many ways to attack a single node, and most of them are preventable. We only need to add nodes that frequently send illegal transactions to the blacklist.

**Comment by Qiao-Jin** [comment]
But it is still weird not including witness when computing transaction hash...

**Comment by erikzhang** [comment]
This is to prevent malleability attacks.

**Comment by Qiao-Jin** [comment]
Close due to design
