### ISSUE TITLE
Consensus Defect: Malicious speaker can halt consensus

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1916]
**Describe the bug**
Malicious speaker can halt consensus progress.

**To Reproduce**
Suppose there are 7 validators, A, B, C, D, E, F and G. A is current speaker. Steps for A to halt consensus:

(1) A makes 2 prepare request, P1 and P2, with hashes of 2 different sets of transactions.

(2) A sends P1 to B, C, D and E, P2 to F and G.

(3) All non-speaker validators will validate the prepare request they received respectively and send out prepare response.

(4) The prepare responses of B, C, D, E will not be accepted by F, G and vice versa. However, B, C, D and E will proceed to commit stage while F, G will request change view due to unenough prepare response received.

(5) **A will not send commit message**. By doing so B, C, D, E will be in commit stage forever while F, G keeps trying to change view. Consensus will halt.

**Comment by erikzhang** [comment]
The consensus can be restored by restarting F and G. A sending two different `PrepareRequest`s in the same view will leave cryptographic evidence, which can be punished in the future.
