### ISSUE TITLE
Should we consider defending possible network attacks by validators?

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#1919]
I.e. some attacks including but not limited to ones listed below:

(1) Some validators keep sending `RecoveryRequest `messages with different timestamps, to force other validators to send recovery responses over and over again.

(2) Some validators keep sending many fake consensus payloads with high `BlockIndex ` and it will be relayed by everyone so that network will fail.

... etc.

**Comment by shargon** [comment]
we should log it in order to punish them
