### ISSUE TITLE
new validator fail to start consensus

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#1929]
**Describe the bug**
when total votes is more than 2000,0000; and the new validator should be able to start a new-round consensus. 

**To Reproduce**
1. Run a consensus node. and initialized with 4 committee members(include CN)
2. create c1.json, c2.json, c3.json; vote c1.json with 99890000;  vote c2.json with 100000; vote c3.json 10000, and the initial validator with 0.
```
026a59b03f981a5dfded185472f4f19409cd229b5cfd11721e70f2b1d16079376a      0
0301088961847b4a684a4b0303eebf4fac76f5605349e8550df1c207c245dfdb78      100000
0352d917d618a42acd3299d08724444d7ba43afddc542752d71835691c654040f9      99890000
03f82a13a0cbf4c553765025a11557f67ad0443813d8ce7d28009d446bbff15c82      10000
```
3. open c1.json wallet and start consensus.

**Expected behavior**

1. get next validators shows the initial validator public key.
2. start consensus fail because its role is still WatchOnly.

**Screenshots**

![df38bbf59ceb7cbce07183424b5f25b](https://user-images.githubusercontent.com/34291844/92916556-34e9d980-f460-11ea-8e69-73d0d78a7d5d.png)

**Comment by shargon** [comment]
It should be reconfigured on View=0  :S

**Comment by erikzhang** [comment]
@cloud8little Has it been fixed?

**Comment by roman-khimov** [comment]
Outdated, we're running fine for years already with validators elected.
