### ISSUE TITLE
Remove exception throwing from System.Runtime.GetInvocationCounter

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1930]
**Summary or problem description**
We throw an error if the invocation counter is basically 0. It seems excessive to halt the contract execution for just asking for a counter value.

https://github.com/neo-project/neo/blob/0208a15b8d0f2aef7b8d9e283fa1590cddefb847/src/neo/SmartContract/ApplicationEngine.Runtime.cs#L159-L164

**Do you have any solution you want to propose?**
remove the exception and return 0 instead

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: smart contracts / interop

**Comment by roman-khimov** [comment]
I guess it's more for the case when there is no `CurrentScriptHash` in the `invocationCounter` dictionary, which technically could only happen because of `ApplicationEngine` bug. And this case should be handled somehow, either by returning zero to the script (but it's not supposed to ever get zero for this call) or by halting the execution in some way (and that's what we have).

**Comment by shargon** [comment]
exactly it should never happen because we add it during the call

**Comment by ixje** [comment]
It is only added during a `System.Contract.Call`, but the entry script could arguably call `System.Runtime.GetInvocationCounter` on itself if it expects something like contract A.func1 call -> contract B.func1 call -> A.func2. Anyway, we'll see if that ever happens :)

**Comment by roman-khimov** [comment]
> only happen because of ApplicationEngine bug

> the entry script

Hmmm, maybe that's one of them, it's "called" implicitly, but still it's being run so it should be accounted for by `invocationCounter`. Especially for cases like verification with #1800 where a real contract is being loaded and it might use `GetInvocationCounter` for its purposes (which is not exactly expected from a simple transaction's entry script).

**Comment by ixje** [comment]
@roman-khimov should I re-open it?

**Comment by roman-khimov** [comment]
I think so. At least in my interpretation of this API the entry script (whatever that is) counts too.
