### ISSUE TITLE
OnDeploy operation

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#1932]
**Summary or problem description**
Contacts often have a deploy method the owner has to invoke after deployment

**Do you have any solution you want to propose?**
Contacts should be able to specify an on deploy operation that is invoked automatically by the system on deployment (including update scenarios)

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- SDK
- VM

**Comment by shargon** [comment]
Maybe we can call `_initialize`

**Comment by devhawk** [comment]
As I understand it, _initialize is runtime initialization, so that won't accomplish what I'm suggesting.

The NEP-5 template contract has a [Deploy method](https://github.com/neo-project/neo-devpack-dotnet/blob/eea7a9df9659d023f47baee06bb2b0f2f80d9152/templates/Template.NEP5.CSharp/NEP5.Owner.cs#L10-L20) that the contract owner is expected to invoke  after deployment. I'm suggesting there should be a mechanism to optionally invoke this operation during deployment

**Comment by shargon** [comment]
I thought that it was easier to do it in the constructor, but it won't be faster, please take a look again.
