### ISSUE TITLE
MPT Questions

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#1949]
I have some doubts according to mpt, maybe @KickSeason can help me :)

`ExtensionNode.Next` it's always decoded as `HashNode`

https://github.com/neo-project/neo/blob/b256992c19317341aa13c98e9a38e40d6261e5cd/src/neo/Cryptography/MPT/ExtensionNode.cs#L26

But as you can see it could take other values

![image](https://user-images.githubusercontent.com/3167973/93815205-e5708e00-fc55-11ea-9b52-887e630e7009.png)

Also, could you tell me why the values of `MaxKeyLength` and `MaxValueLength` ?

**Comment by shargon** [comment]
The same happend with the `BranchNode` 

https://github.com/neo-project/neo/blob/b256992c19317341aa13c98e9a38e40d6261e5cd/src/neo/Cryptography/MPT/BranchNode.cs#L30

![image](https://user-images.githubusercontent.com/3167973/93815788-d807d380-fc56-11ea-8e7c-ba13a261633e.png)

**Comment by roman-khimov** [comment]
> ExtensionNode.Next it's always decoded as HashNode
> The same happend with the BranchNode

Serialized extension and branch nodes can't store anything but hashes inside (consider the opposite scenario, serializing root node would go through the whole tree), but these `HashNode`s are "unwrapped" on access via `Resolve(HashNode n)`, that's where you'd get some other type of node for `Next` or `Children[i]` (but their `Hash` matches the `HashNode`).

**Comment by shargon** [comment]
Thanks @roman-khimov!
