### ISSUE TITLE
[master-2.x] Memory pool crash in unknown situation

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#1953]
**Describe the bug**
As we've run v2.12.1 on mainnet for several days, there's a sudden crash which makes some CNs and seed nodes be killed by system because the memory risen suddenly and sharply.

**To Reproduce**
Still need deep investigation.

**Expected behavior**
Mempool had risen suddenly and sharply (Might be from unknown p2p message issue).

**Screenshots**
Memory cost, can see memory cost suddenly rose from 3:00 AM to 9:00 AM(China time) and made crash, then after restart, they returned normally.
![image](https://user-images.githubusercontent.com/38493437/94009057-7d958100-fdd6-11ea-89af-59f2002a849c.png)

**Platform:**
 - OS: [ubuntu 16.04]
 - Version [neo-cli v2.12.1]

@neo-project/core @neo-project/developers Need your help.

**Comment by shargon** [comment]
Do you have the crash error log?

**Comment by superboyiii** [comment]
> Do you have the crash error log?

No exception throwed, but just `killed`. I've saw leveldb log but no anything abormal there but just suddenly not recorded and recover again when restart.
LOG.old
![image](https://user-images.githubusercontent.com/38493437/94012746-c996f480-fddb-11ea-8020-b42089774d37.png)
LOG
![image](https://user-images.githubusercontent.com/38493437/94012865-e7fcf000-fddb-11ea-8cb1-99c1ab9f80c8.png)

**Comment by vncoelho** [comment]
Taking a look here, @superboyiii, trying to understand if it is a solely `mempool` error or related to `stateroot` new commands.

**Comment by vncoelho** [comment]
Maybe we also need to set a limit when responding https://github.com/neo-project/neo/blob/b036def762e5a9751015f3e90e358615fd542304/neo/Network/P2P/ProtocolHandler.cs#L338-L342

**Comment by superboyiii** [comment]
> Do you have the crash error log?

![image](https://user-images.githubusercontent.com/38493437/94092982-a8232080-fe4e-11ea-886f-33a3429aab84.png)
Last night's CN log. It's a suddenly increasement on memory.
![image](https://user-images.githubusercontent.com/38493437/94094254-998a3880-fe51-11ea-8376-108fb6520c19.png)
And I think the mempool is OK since some not crashed seeds are still running but has much more memory cost. However, not much Txs in their mempool. Look, the Txs in the crash time are not too many.
![image](https://user-images.githubusercontent.com/38493437/94094371-e8d06900-fe51-11ea-8259-49347b936ac5.png)
Due to our investigation, we think the issue might be from `GetStateRoots`. Too many `Getstateroot` are currently in p2p messages, if one node not at the latest height, it will send `GetStateRoots` message to get next 2000 roots. But if its root mismatch the received, it will send `GetStateRoots` frequently. And the other nodes will also response frequently. That might be the reason.
