### ISSUE TITLE
[Feature Request] charge by the byte for transactions.

### ISSUE THREAD

**Issue by coranos** [neo-project/neo#196]
Charge 1 satoshi of gas per byte of a transaction, to submit a transaction.

Currently there are ~7500 accounts claiming gas every day. 
https://coranos.github.io/neo/charts/neo-java-chain-stats.html

the top 50 gas claimers all have less than 1200 neo, and claim between 10 and 30 times a day.
https://coranos.github.io/neo/charts/neo-account-data.html
(sort by gas claims)

The top one, this guy:
https://neoscan.io/address/ASr2NQ7QBnTESigbT3jw42VbFPfEsTvBFz
he claims 1.26e-5 gas, 40 times today, 80 transactions per day just for him.

if he ever consolidates his ~1000 gas transactions, his consolidation transaction will be 300kb, with 1 output, and 1000 inputs, to consolidate 0.0244367 gas.

If you charge 1 satoshi per byte, it would cost him 0.0300000 gas to consolidate 0.0244367 gas, so maybe he wouldn't spam so much.

**Comment by erikzhang** [comment]
If the number of transactions reaches the maximum number of transactions per block, the transactions are queued for confirmation by fee per kb.
https://github.com/neo-project/neo/blob/master/neo/Consensus/ConsensusService.cs#L121

**Comment by coranos** [comment]
I see a problem with that implementation, I'm not sure if it's intentional. (If you agree this is a problem, and you think I should make a different issue, I will. )

The problem is that the System Fees can never be changed, as they are only in the config file. Gas costs can never be lowered. If it was lowered, some transactions that are currently in the blockchain would get rejected for having too low a fee.
