### ISSUE TITLE
Stuck transaction. What to do?

### ISSUE THREAD

**Issue by IgoresVer** [neo-project/neo#1969]
Hash 78b8622436e76978f0ae2871af2edcafb96521828adae20e18f6f9e9d47e167c
and it is not visible on NeoTube

**Comment by Tommo-L** [comment]
@IgoresVer   https://neoscan.io/transaction/FD74958B6732A82A1A893274A84C68904D9A8128996AE4C2347697FBED238E88

Plz, you'd better add some network fee, as free transaction has the lowest priority

**Comment by IgoresVer** [comment]
How can I do it? Can I do it with NeoLine?

**Comment by Tommo-L** [comment]
>  Can I do it with NeoLine?

Yes. If you have no GAS, you can buy some GAS from exchange to your Neoline wallet.

**Comment by IgoresVer** [comment]
I have GAS. How to add it to my transaction?

**Comment by Tommo-L** [comment]
When you transfer, it'll automatically  add network fee.

![image](https://user-images.githubusercontent.com/43396869/94229287-b5650b80-ff31-11ea-9bc5-5b73d9b5ecf7.png)

**Comment by Tommo-L** [comment]
And this transaction(hash = 78b8622436e76978f0ae2871af2edcafb96521828adae20e18f6f9e9d47e167c) has already been packaged onchain.

**Comment by IgoresVer** [comment]
So, if it is packaged onchain I can do nothing with it but wait? No way to add gas to this trx?

**Comment by Tommo-L** [comment]
I mean this tx has already transfered successfully at `24-07-2020 | 01:16:10:000`
https://neotube.io/transaction/0xfd74958b6732a82a1a893274a84c68904d9a8128996ae4c2347697fbed238e88
https://neoscan.io/transaction/FD74958B6732A82A1A893274A84C68904D9A8128996AE4C2347697FBED238E88

**Comment by IgoresVer** [comment]
This is not 78b8622436e76978f0ae2871af2edcafb96521828adae20e18f6f9e9d47e167c

**Comment by Tommo-L** [comment]
O.M.G.  The tx should be stuck at the wallet node, it's not in the mempool of seed node and block.

![image](https://user-images.githubusercontent.com/43396869/94235524-4e9a1f00-ff3e-11ea-9269-e848341c2043.png)

Can you contact Neoline's customer service?

**Comment by IgoresVer** [comment]
I'll try, thank you
