### ISSUE TITLE
maybe node fault

### ISSUE THREAD

**Issue by i359** [neo-project/neo#1974]
It seems that some nodes do not package data.

![AAA](https://user-images.githubusercontent.com/43022140/94337107-84acd100-001a-11eb-9c55-2b131b738485.jpg)

**Comment by i359** [comment]
Many blocks only 1 tx, but other blocks many tx, maybe node fault, suggest dev to check and fix,thanks!

![image](https://user-images.githubusercontent.com/43022140/94337228-89be5000-001b-11eb-8929-e8272d57da7e.png)

**Comment by Tommo-L** [comment]
Thanks, we're investigating. It may be related to `StateRoot`.

**Comment by Tommo-L** [comment]
It's already fixed by https://github.com/neo-project/neo/pull/1957
