### ISSUE TITLE
REQ: RPC call with Verification trigger type

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#1977]
**Summary or problem description**
#1800 introduced smart contract verification. Light wallets or light wallet SDK's like [neon-js](https://github.com/CityOfZion/neon-js) need to be able to calculate the required gas. The gas consumption for system fee can be obtained via RPC using `invokescript`, however gas consumption for the network fee when using a smart contract for verification cannot be obtained via `invokescript`. This is because `invokescript` always runs the engine with the `Application` trigger. I found no existing RPC calls that can run the Application engine with the verification trigger, therefore it is impossible for light wallets to obtain the required network fee.

**Do you have any solution you want to propose?**
One solution is to expand an existing RPC call (e.g. `invokescript`) to accept a trigger type parameter to allow using a Verification trigger. Alternatively a whole new RPC call can be introduced. I have no preference for either solution.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by ixje** [comment]
I gave it some more thoughts and I think extending both `invokefunction` and `invokescript` should allow for most flexibility in the future. 

I gave the implementation some thoughts; 
1. add a mandatory trigger field
   pro: clean and easy to implement by indexing a fixed location in the array
   con: forces everybody to add a trigger type field while the `verification` trigger is a special case which is expected to not used too often

2. add an option trigger field
   pro: no extra input field required for the most common use-case
   con: either you have to add a JObect in the form of e.g. `{"triggertype": "Verification"}` to the `params` list, or search through all parameters to see if one is "VerificationTrigger" or some similar name.

What route is preferred? or perhaps another solution?

**Comment by chenzhitong** [comment]
Can't the `invokefunction` call the `Verify` method?

**Comment by Tommo-L** [comment]
Both `invokefunction` and `invokescript`  will use `application` trigger to execute the `verify` method.

**Comment by chenzhitong** [comment]
Is it no longer necessary to determine triggers in the contract in the Neo3 contract?
```c#
public static bool Verify() 
{
    if (Runtime.Trigger == TriggerType.Verification)
    {
    }
    else if (Runtime.Trigger == TriggerType.Application)
    { 
    }
    return IsOwner();
}
```
So the `Verify` method with the `application trigger` or `verification trigger` has the same result, right?

**Comment by ixje** [comment]
> Is it no longer necessary to determine triggers in the contract in the Neo3 contract?
> 
> ```cs
> public static bool Verify() 
> {
>     if (Runtime.Trigger == TriggerType.Verification)
>     {
>     }
>     else if (Runtime.Trigger == TriggerType.Application)
>     { 
>     }
>     return IsOwner();
> }
> ```
> 
> So the `Verify` method with the `application trigger` or `verification trigger` has the same result, right?

Where does this code snippet come from? As far as I know there is still no specification for the `verify()` method (pointed by @Tommo-L  [here](https://github.com/neo-project/proposals/pull/119#issuecomment-607229443)). So I based my issue on what NEO is doing here
https://github.com/neo-project/neo/blob/22f80a7ccfb00af15006569921ed87536cf3f857/src/neo/Wallets/Wallet.cs#L401 together with some historical NEO2 assumptions for trigger types.

**Comment by chenzhitong** [comment]
I wrote a draft of a pull request.
But I think, perhaps a light wallet constructing the transaction and executing the `Verify` method via `tx.Verify();` in the SDK would be a better choice.

**Comment by Tommo-L** [comment]
> Is it no longer necessary to determine triggers in the contract in the Neo3 contract?

No, it still will check the triggger type. 

> So the Verify method with the application trigger or verification trigger has the same result, right?

No, it may have two different results.
