### ISSUE TITLE
Incorrect GAS calculation in System.Contract.Update.

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#1989]
**Describe the bug**
Incorrect GAS calculation in `System.Contract.Update` syscall. Manifest is not taken into account if script it non-null.

**To Reproduce**
Call `ApplicationEngine.UpdateContract` with non-empty script and manifest. Set GAS limit to `StoragePrice * len(script)`.

**Expected behavior**
Error because of insufficient GAS.

This line `AddGas(StoragePrice * (script?.Length ?? 0 + manifest?.Length ?? 0));` should probably be written as
`AddGas(StoragePrice * ((script?.Length ?? 0) + (manifest?.Length ?? 0)));`

**Comment by shargon** [comment]
If it's not null and it's 0 it will fault here https://github.com/neo-project/neo/blob/d1b1887fec01340f20c6a6449264dd92ba5955d5/src/neo/SmartContract/ApplicationEngine.Contract.cs#L76

**Comment by roman-khimov** [comment]
See nspcc-dev/neo-go#1456 for an example of this.
