### ISSUE TITLE
StorageIterator does not work

### ISSUE THREAD

**Issue by RavenXce** [neo-project/neo#199]
Please see https://github.com/neo-project/neo-devpack-dotnet/issues/19#issuecomment-373934451 for example reproduction.

The issue is that when doing the prefix building in `Storage.Find`, the contract script hash and storage prefix are simply concatenated. 
https://github.com/neo-project/neo/blob/f49f26604717579455691396adc301778c02d865/neo/SmartContract/StateReader.cs#L951

However, for Storage.Put/Get, I believe that serialization uses WriteVarBytes for the key portion:
https://github.com/neo-project/neo/blob/07dd1f5c9ca25ad3d2e91e97c55608d1cf938cbf/neo/Core/StorageKey.cs#L46

Which prefixes the length of the key:
https://github.com/neo-project/neo/blob/115a402478c00aaaa6f3ada671f14af69e0219cf/neo/IO/Helper.cs#L190

I think we can safely construct and then serialize a StorageKey instead to ensure they match?

Edit: Actually, the length prefix messes up the whole implementation - one way to make it work is by specifying key length, so the keys iterated on are constrained to a single length and must be known.

**Comment by ixje** [comment]
For what it's worth, in `neo-python` the `ScriptHash` + `prefix` concatenation is workable, we just had to fix Storage Put/Get/Delete calls because they were creating a key that was not prefix searchable (e.g. ScriptHash + murmur_hash(key) -> convert to bigint then get `bytes` as key).

**Comment by RavenXce** [comment]
Since the keys in the db change does that mean that nodes need to re-build storage on upgrade?

The other solution to this is to change how Put/Get/Delete works as well, but I thought that would be more complicated.

**Comment by ixje** [comment]
Yes for `neo-python` the user will have to rebuild storage. There was no way around it because previously the following 2 `Put` calls in a smart contract
```python
    Put(ctx, 'my_prefixA', 1)
    Put(ctx, 'my_prefixB', 2)
```
would generate the following DB keys:
```
b'^\xbe\xe4\xf4\x00'
b'\xaa.\xd5t'
```
and as can be seen, that would never reasonable be prefix searchable.

**Comment by RavenXce** [comment]
I guess thats a possible solution here too. 

I've tested and can confirm the issue is due to the key prefix as mentioned in OP. Manually prefixing an additional key length in addition to the prefix allows keys with that length and prefix to be returned.
