### ISSUE TITLE
"NotValidBefore" transaction attribute type

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#1992]
**Do you have any solution you want to propose?**
This attribute makes transaction invalid before certain height. It has uint32 data inside which is the block height starting from which the transaction is considered to be valid. It can be seen as the opposite of ValidUntilBlock, using both allows to have a window of valid block numbers that this transaction could be accepted into. Transactions with this attribute are not accepted into mempool before specified block is persisted.

It can be used to create some transactions in advance with a guarantee that they won't be accepted until specified block, that property will be used for signature collection service (#1573).

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Ledger
- P2P (TCP)

**Comment by roman-khimov** [comment]
A prototype of that is implemented in nspcc-dev/neo-go#1496, it's quite simple attribute.

**Comment by erikzhang** [comment]
Nodes are not obliged to keep transactions that cannot be verified immediately in the memory pool.

**Comment by roman-khimov** [comment]
And they won't keep them, an ordinary node receiving transaction with NVB height more than the current height just drops it as invalid.

**Comment by vncoelho** [comment]
Is this closed?
