### ISSUE TITLE
Contract deployment price coefficient and minimum value

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2001]
**Summary or problem description**
A lot of effort went into reducing system fees on Neo 3, one of which is contract creation and upgrade fee. There were various discussions around that topic, but the last actual change to that was made by #771 and even that originally intended to have a bit different approach (100/10 values). So at the moment we charge for storage size of contract's code and manifest, which is fair, there should be that proportion, but at the same time I think we have two problems with it:
 * contracts is not just about storage, their effect is much broader and maintaining them on-chain is a bit harder than just storing some bytes
 * it's not hard to deploy thousands of contracts with minimal GAS cost to doing so, one/two bytes contracts that do nothing are considered to be perfectly valid for the chain

At the same time having a limited set of contracts can be beneficial for the network as it allows for some additional optimizations.

**Do you have any solution you want to propose?**
Although contract deployment shouldn't cost a fortune, there should be some reasonable barrier to doing so, therefore I want to propose two changes:
 * apply a coefficient to current pricing (like 3), so that the price would be a little higher than now
 * more importantly, add some minimum policy value for these fees (30-50-100, I don't have any particular number of choice here) to prevent deploying useless contracts at scale

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Network Policy
- Other: Economic model

**Comment by Tommo-L** [comment]
We worked hard to reduce the cost on Neo3. As a result, the cost of deployment contract remains high.

Storage fees are not cheap. 

1Kb = 1 GAS ~ 1.5$， 
1Mb = 1024 GAS ~ 1536 $
1Gb  = 1 048 576 GAS ~ 1 572 864 $

For me, I think we add a deployment contract base fee ( = 1GAS) is enough.

**Comment by roman-khimov** [comment]
Well, cheap/expensive is opinionated, but one thing I'd really like to see is only real useful contracts being deployed. Neo 2 has around 200 contracts in its active set and that makes it easy to cache them in any way avoiding going to the DB in many cases. Of course we'd like to have more contracts on Neo 3, but what I wouldn't like is tens of thousands of useless contracts which is quite easy to get now. With the current pricing model typical contracts (which is in tens of KBs and never more than 576 KB (technically even 100K because of transaction's limitations) would cost tens of GAS, probably the minimum value should be around that.

**Comment by Tommo-L** [comment]
I think this will solve this issue.  https://github.com/neo-project/neo/issues/1187  https://github.com/neo-project/neo/issues/1486
