### ISSUE TITLE
Increase ContractManifest.MaxLength

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2002]
**Summary or problem description**
I've looked at calls to "Contract.Create" and "Contract.Update" for preview3 testnet (up to block 278513) and counted 18 of them. Specifically, I was interested in manifest sizes and for this set we have the minimum value of 380, average manifest size of 1473,  and the maximum of 3345. What worries me a little is that even for this set we're getting very close to `ContractManifest.MaxLength` which is just 4096 bytes and real complex contracts can easily exceed that.

**Do you have any solution you want to propose?**
Manifest is being paid for on contract creation/update equally to the script itself, so restricting it to such low values is just not necessary, we can make `MaxLength` 64K and forget about it for quite some time.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: Contract manifests

**Comment by shargon** [comment]
Have sense, what do you think @erikzhang?

**Comment by erikzhang** [comment]
Fine.
