### ISSUE TITLE
Chinese code summary and comments (XML Documentation)

### ISSUE THREAD

**Issue by joaocarlosleme** [neo-project/neo#203]
Wouldn't be better to have all code comments (XML Documentation) in English? Or at least English and Chinese?

Overall, there ain't much code documentation/description, but the few available are in Chinese. To better understand the project I'm going back and forth from google translate.

I could look into an auto translate all Chinese into English and make a pull request, but only if you agree to further continue that way.

**Comment by lock9** [comment]
Hello,
Is this still pending?

**Comment by erikzhang** [comment]
I will add more comments in the future.
