### ISSUE TITLE
Update committee in `PostPersist`

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#2053]
**Summary or problem description**
In #2015 consensus `Reset()` was altered to check if committee needs to be updated.
This seems like an internal detail of `NEO` native contract implementation which consensus module should't be bothered with.

**Do you have any solution you want to propose?**
Calculate committee in `PostPersist` (and probably `Initialize` for 0 block).
This way consensus can just use `GetNextBlockValidators`, at it was previously.
Another thing to consider is `HighPriority` transaction attribute. When validating transaction we use old committee value but actual tx execution will use new one. When this is done in `PostPersist`, no such problem exists.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Consensus
- Native contracts

**Comment by Qiao-Jin** [comment]
Putting updating committee membe logic into PostPersist might change current logic:

Plan A. If putting it to the PostPersist of the 21th block, computing next round committee members would take account of transactions in 21th block (Originally it doesn't), or

Plan B.  If putting it to the PostPersist of the 20th block, the next round committee members will be refreshed a block ahead.

Either way will change current logic, even though neither seem to give rise to an error.

**Comment by Qiao-Jin** [comment]
After re-consideration, I think this doesn't work:

Plan A. If putting it to the PostPersist of the 21st block, computing next round committee members would take account of transactions in the 21st block (Originally it doesn't). But before generating 21th block you will never know what transactions it will contains, so field NextConsensus lost its meaning and effect.

Plan B. If putting it to the PostPersist of the 20th block, the next round committee members will be refreshed a block ahead, so we will actually need to recalculate in 19th block... Paradox.

**Comment by fyrchik** [comment]
I agree with the cases you have made.
So we have 2 possible bugs:
1. `NextConsensus` doesn't match committee in a time period between blocks.
2. Transaction is verified using the old value of committee which will change before tx execution.
When updating in `OnPersist` bug 2 happens, when updating in `PostPersist` we have bug 1. While I agree that bug 1 is more severe (it is related to block verification), may be we can fix both?
For example, calculate committee in block 20, but perform actual update in 21-st?

**Comment by Tommo-L** [comment]
> For example, calculate committee in block 20, but perform actual update in 21-st?

Maybe it's ok for now. 😄

**Comment by roman-khimov** [comment]
Propose closing this one. While the problem still exists, any proposed solutions have problems of their own as well, so there is no real improvement there and we have public networks running for quite some time using current logic without any noticeable issues.
