### ISSUE TITLE
Change Native.Deploy

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#2055]
**Summary or problem description**
As I spoke with @ixje , currently we only can deploy native contracts in Genesis block, this can be inconvenient if we had plans to increase the native contracts in a future.

**Do you have any solution you want to propose?**
Send hash in `Neo.Native.Deploy`

**Neo Version**
- Neo 3

**Comment by roman-khimov** [comment]
I think this was done to prevent calling `Neo.Native.Deploy` from transactions (random people shouldn't deploy native contracts), but now it can probably be solved by doing a committee check. And yes, some mechanism to deploy native contracts after the genesis is needed.

**Comment by shargon** [comment]
If random people call this syscall, they will pay gas (`PUSHDATA`) and will get a `FAULT`

**Comment by Tommo-L** [comment]
I prefer to add new native contract in `OnPersist` method.
