### ISSUE TITLE
CheckItemForNotification logic duplicates BinarySerializer for no good reason

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2069]
**Summary or problem description**
`CheckItemForNotification` function that is used by `System.Runtime.Notify` implementation looks very similar to `BinarySerializer.Serialize`, but:
 * size calculated by it would differ from the size of `BinarySerializer.Serialize` output
 * it actually allows for cyclic references, just ignoring them

I think both properties of it are wrong, for generic items we should always take their serialized size as a reference (array of 1024 arrays has a size of zero in `CheckItemForNotification`, it doesn't seem to be correct) and we should not allow cyclic references inside of the item used for notification (it'll break JSONization for applications logs, for example).

**Do you have any solution you want to propose?**
Drop `CheckItemForNotification` and reuse `BinarySerializer.Serialize` in `System.Runtime.Notify`. It already has size limitation which is convenient to use here and it'll reject items with cyclic references.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Interops

**Comment by Tommo-L** [comment]
Maybe it's better to keep it that way. Although the logic is somewhat similar, but the usage scenarios are different.

**Comment by roman-khimov** [comment]
I don't think it's good to:
 * allow cyclic references in notification items
 * treat array of 1024 arrays as having size of 0
 * duplicate code
