### ISSUE TITLE
long type can not convert implicitly to int type for dotnet 5.0

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2078]
**Describe the bug**
update the framework of neo project to net5.0, and reference neo-vm master branch. Build failed.

**To Reproduce**
1. Open the neo-cli and neo project, update the framework to net5.0
2. Build the project.

**Expected behavior**
Build successfully.

**Screenshots**
![1f687c704dc061673e783c56999ef67](https://user-images.githubusercontent.com/34291844/99751561-67c5e300-2b1d-11eb-8cbc-8fd108b2e972.png)

**Platform:**
 - OS: Windows 10 x64
 - Version master

**Comment by superboyiii** [comment]
The same too me. Seems int isn't supported to be converted from long implicitly in .Net 5.0. But recommand to fix this after release of Preview4 to avoid .net SDK conflict.
![image](https://user-images.githubusercontent.com/38493437/99775509-56470000-2b4a-11eb-9670-557d549e2d0d.png)
