### ISSUE TITLE
Questions about calling from native contracts

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#2081]
Hello! While I was implementing NEP-17 support in `neo-go`, some questions arised:

1. Are there any examples of `CallFromNative` where some value is returned?
2. I am concerned with this line https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Native/NativeContract.cs#L127 . Consider `onPayment`: is `Transfer` result pushed to `onPayment` method context stack? Or am I missing something?
3. If 2 is to be fixed via `onComplete` callbacks, shouldn't it be called before stack checks? https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.cs#L124
It seems reasonable to expect, checks should be done with final stack state.
4. When calling `PostTransfer` for NEP-17, `onPayment` is assumed to exist. While it is reasonable, maybe it is better to check for it's existence? E.g. `Oracle` contract doesn't have it and not every contract may want to implement some custom logic. So there may be another bug after #2077 .

**Comment by fyrchik** [comment]
I see (4) is a feature. What about  making `Transfer` consume old GAS value and have a separate `VM.AddGas(100000)` when receiver is a contract?

**Comment by Tommo-L** [comment]
>  my OnPayment method in NEP17 contract is: https://github.com/neo-project/neo/pull/2044#issuecomment-731552964
```csharp
  public static bool OnPayment(UInt160 from, BigInteger amount)
  {            
        return true;
   }
```

@ProDog  BTW, the return type of `OnPayment` is `Void` .   Could try it again?

**Comment by Tommo-L** [comment]
> Consider onPayment: is Transfer result pushed to onPayment method context stack? Or am I missing something?

It seems to be a problem.

**Comment by Tommo-L** [comment]
> What about making Transfer consume old GAS value and have a separate VM.AddGas(100000) when receiver is a contract?

It doesn't feel like it's necessary. When other contracts execute `OnPayment` method, they will be automatically charged.

**Comment by ProDog** [comment]
> @ProDog BTW, the return type of `OnPayment` is `Void` . Could try it again?

Same error🤔.

```C#
public static void OnPayment(UInt160 from, BigInteger amount)
{            
    return;
}
```

**Comment by erikzhang** [comment]
> Consider onPayment: is Transfer result pushed to onPayment method context stack? Or am I missing something?

It should be fixed by #2087

**Comment by Tommo-L** [comment]
Close?

**Comment by fyrchik** [comment]
@Tommo-L wanted to see some examples of native invoke with result. But it isn't used now, so yeah, closed.
