### ISSUE TITLE
Remove MAX_SAFE_INTEGER limitation

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2082]
**Summary or problem description**
Following https://github.com/neo-project/proposals/pull/126/files#r522304412 discussion and https://github.com/nspcc-dev/neofs-node/issues/122#issuecomment-716565100 problem. We use 256-bit integers in VM, but they don't always convert to/from JSON nicely because of MAX_SAFE_INTEGER limitation and this limit is too low, even 100M with 8 decimals can't fit there.

**Do you have any solution you want to propose?**
I see two options:
 * dropping MAX_SAFE_INTEGER limitation, staying with decimal representation and leaving this as a client problem (RFC 7159 _recommends_ to stay within `[-(2⁵³)+1, (2⁵³)-1]`, but JSON technically doesn't impose any hard limit)
 * using hex encoding (either always or when the number doesn't fit), but that may be not very convenient

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by shargon** [comment]
If we remove the limit, it's very possible that we will need a custom json implementation in all languages (like go), isn't it?

**Comment by roman-khimov** [comment]
It's very easy to fix for me while still staying decimal, but I'm not so sure about other client/server implementations. We need to solve this one way or another though.

**Comment by ixje** [comment]
> If we remove the limit, it's very possible that we will need a custom json implementation in all languages (like go), isn't it?

Pretty much everything needs a custom implementation if you want to be strict compliant with how C# works, so that's nothing new for me.

**Comment by roman-khimov** [comment]
This still is a problem, create some NEP-17 token with 16 decimals and try to work with it via RPC, there will be problems doing so.

**Comment by erikzhang** [comment]
> This still is a problem, create some NEP-17 token with 16 decimals and try to work with it via RPC, there will be problems doing so.

The best way is to use string.

**Comment by csmuller** [comment]
> The best way is to use string.

If we use strings for large integers in JSON, I think there will be a problem with `StdLib.JsonDeserialize(...)` in smart contracts because it will deserialize the former integers to strings instead.
