### ISSUE TITLE
onPayment Context Evaluation Stack not empty on unload

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2085]
I'm trying to transfer Nep17 GAS to a contract using neo master branch. In preview 3, transfer info was passed via notifications. post-preview 3, there's now a onPayment contract method that gets called. 

If my contract doesn't have an onPayment method, contract invocation throws in CallContractInternal "Method onPayment Does Not Exist In Contract 0xba518ba007f853a2e8b388d4e9968abe62a3a429'". Is this expected? I thought the onPayment method was optional, but now I'm not sure.

Regardless, if I add an onPayment method to my contract, contract invocation now thows in `ContextUnloaded` method. The return type of the context being unloaded is ReturnTypeConvention.EnsureIsEmpty, but the context.EvaluationStack.Count is 1

**Comment by roman-khimov** [comment]
> If my contract doesn't have an onPayment method, contract invocation throws in CallContractInternal "Method onPayment Does Not Exist In Contract 0xba518ba007f853a2e8b388d4e9968abe62a3a429'". Is this expected?

Yes, it is mandatory for contracts that want to receive tokens (think of it like implicit `IsPayable` flag).

> contract invocation now thows in ContextUnloaded method

This looks like 2/3 from #2081.

**Comment by Tommo-L** [comment]
Related to https://github.com/neo-project/proposals/pull/126#issue-519625130
