### ISSUE TITLE
Block index by range (avoids empty blocks)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#2086]
**Summary or problem description**
This has been discussed some times (https://github.com/neo-project/neo/issues/921) but I think it's a very simple and quite powerful mechanism: reducing the existence of empty blocks (*fundamental for experimental Neo-based networks that don't have much traffic such as Neo MainNet but require frequent and timely block production, as usual*).

**Do you have any solution you want to propose?**
The solution I propose does not offend block finality, and it's quite simple: instead of indexing blocks by a single index number, let's put two numbers (index begin, index end). If two or more consecutive blocks are empty (of transactions), they are merged into a new one, that preserves all useful information (block hash, timestamp and nonce [I forgot if we really have that]).

Workings is quite simple:
1. CN speaker of height H proposes an empty block B (index H), where index H-1 was not empty (with prevBlock hash digest d_{H-1}).
2. other CN validates this empty block, index H (with timestamp t_H and hash digest d_H)
3. CN speaker of height H+1 will again propose an empty block, but it realizes H was also empty
4. CN proposes a compound block with index [begin H, end H+1], with timestamp t_(H+1), digest hash d_(H+1), and (with prevBlock hash digest d_{H-1}, not d_{H}).
5. The compound block also has "attribute" for "timestamp at height H" = t_H, besides its own timestamp (which relates to H+1)
6. Since there was no state-changing computation on H, and all relevant info are also on H+1, nodes can discard block H, and only keep H+1
7. This process continues until: (a) a non-empty block is proposed, so regular block is generated (b) blockchain has already generated consecutive MAX_EMPTY_BLOCKS limit. This limit is not necessary on practice, but it gives me some "peace of mind", to put extra "solidness" on blockchain (maybe every 100 consecutive empty blocks then start a new one??).  

This way, we don't lose block hashes or timestamps (which is absolutely fundamental for timestamp-based systems on real world that rely on blockchain as a source of time!), and save some good space with repeated CN signatures.

Note that we could have very similar behavior if we just **drop CN signatures on consecutive empty blocks** (if block H and H+1 are both empty, we just drop signatures from block H), and I haven't counted the bytes to see which one of both is less costly on practice. Maybe it's worth thinking about it too.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Consensus
- Ledger

**Comment by igormcoelho** [comment]
![image](https://user-images.githubusercontent.com/290989/99864905-eb66ea80-2b84-11eb-988a-19f2eb4a0cce.png)

Visualization of the idea: path above has two consecutive empty blocks, could be a hundred; path below has a compound block that replaces both H and H+1.

**Comment by Tommo-L** [comment]
Good idea, we need a few days to discuss it, after preview4 released.

**Comment by shargon** [comment]
If you have a random method according to the previous blocks values, you can have a fixed seed if we remove the empty blocks.
