### ISSUE TITLE
What happens if someone calls the 'onPayment' method directly?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2108]
Hi. I have a question regarding NEP-17.

We implemented a simple version using the new methods, including the onPayment. However, we noticed that this method is public and can be invoked by anyone. Is this intended? Do I have to add this 'security' layer myself, or does Neo already handles this automatically?

**Comment by roman-khimov** [comment]
I guess it depends on what's done inside of this method. It's supposed that it should check `CallingScriptHash` first of all and only deal with tokens it knows how to deal with then. If that's the case, it shouldn't be a problem, anyone can invoke it, but no one can fake `CallingScriptHash` of some token, so your contract will just reject these invocations.

**Comment by lock9** [comment]
Hmm, that makes sense. Thanks!
