### ISSUE TITLE
Update contract ID after validation in contract create

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#2113]
**Describe the bug**
While creating contract, first new ID is fetched and updated, then manifest checking is done.
https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.Contract.cs#L43

**Expected behavior**
First fully validate manifest, then fetch and update contract ID. This way there will be no gaps in contract IDs.

**Comment by erikzhang** [comment]
If the check fails, the modification on `ID` will be rolled back.

**Comment by shargon** [comment]
Yes, the snapshot will be reverted.
