### ISSUE TITLE
Add system method mapping to the ABI to avoid name conflicts

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2124]
**Summary or problem description**
We are calling hardcoded methods on the smart contracts at system level. For example: '_deploy', 'initialize', 'verify' and 'onPayment'. We may run into a bad situation when we try to add new system methods, since they may be already be implemented on a deployed contract.

**Do you have any solution you want to propose?**
I suggest we have a mapping section on the ABI that maps 'system methods' to 'ABI'. For example:
```
methods: {
  "deploy" : {...}, //Deploy is actually a user created method
  "myDeploy" : {...}, //This is the callback we want the system to call
  "myOnPayment" : {...}
}
systemCallbacks:{
  "deploy" : "myDeploy", //Here we map the deploy callback to the user myDeploy method
  "onPayment" : "myOnPayment"
}

```

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Ledger

**Comment by erikzhang** [comment]
I think they can upgrade the script. Now we won't change the hash of the contract while upgrading.

**Comment by lock9** [comment]
Hi Erik,
If we need to add more callbacks, we can’t demand people to migrate their contracts. 

For example, if we have to add a “onVote” callback, what are we going to do with contracts that already have a method with this name? 
I can think of some options, but I think this is the cleanest one.

**Comment by erikzhang** [comment]
In my opinion, updating abi is the same as updating script. You always have to update one of them.

**Comment by lock9** [comment]
Are you saying that if we release an update with a new callback, we are going to demand that every smart-contract is re-deployed? What is going to happen to already deployed contracts? 🤔
