### ISSUE TITLE
[Feature Request] Add `Neo.Runtime.CheckSignature`

### ISSUE THREAD

**Issue by localhuman** [neo-project/neo#213]
Currently there is no method from a smart contract to check the signature of an arbitrary message, signature, and public key object.

A proposed solution would add `Neo.Runtime.CheckSignature` and `Neo.Runtime.CheckSignatures` to `StateMachine` which would accept a message, signature(s), and public key(s) to be checked.

**Comment by erikzhang** [comment]
@localhuman Is it better to add a new opcode `VERIFY` to check the signature of an arbitrary message?

**Comment by shargon** [comment]
Maybe we can modify `CHECKSIG` and if the first item is an Array, check if his length is 3. Message,PubKey and Signature

**Comment by erikzhang** [comment]
>Maybe we can modify CHECKSIG and if the first item is an Array, check if his length is 3. Message,PubKey and Signature

If we do this, then we have to add two more opcodes `PUSH3` and `PACK` before each `CHECKSIG`. I would prefer to add new opcode for this feature.

**Comment by localhuman** [comment]
Agree that adding a new opcode seems better.  `CHECKSIG` is used a lot and should be kept as simple as possible.

**Comment by shargon** [comment]
Let's do it :)

**Comment by localhuman** [comment]
🎉
