### ISSUE TITLE
Specifying NativeContract ActiveBlockIndex in code will be an issue for privatenets

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2131]
**Summary or problem description**
In #2119, NativeContract got a new abstract property called ActiveBlockIndex. This property specifies when a given contract is valid. However, this value of this property is going to be network dependent. Even between mainnet and testnet, new native contracts will be enabled at different block heights. We need a mechanism to specify ActiveBlockIndex of a contract in protocol configuration

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Native Contracts

**Comment by roman-khimov** [comment]
Maybe we can do that just for new ones, treating the set we already have as always enabled (since block 0).

**Comment by devhawk** [comment]
> Maybe we can do that just for new ones, treating the set we already have as always enabled (since block 0).

Certainly, the ones we have now should always be enabled. However, I do wonder about how updates will be handled. If we want to update one of the native contracts, will there be a specific block where we indicate we want the new behavior to be enabled?
