### ISSUE TITLE
How to push a ContractParameterType of type 'Map' using the script builder?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2143]
Hi, 

Some of our code has broken because we can't push the Map type using the script builder. What should we do to replace it? Map is still a ContractParameterType, but it can't be pushed to a script using the script builder.

Edit: Maybe this is not the reason our code has broken. I checked the latest changes and I noticed that the map was never there. Not sure what happened.

**Comment by erikzhang** [comment]
```
NEWMAP
DUP
PUSH <key>
PUSH <value>
APPEND
```

**Comment by lock9** [comment]
Thanks mate. Any reason we don't have this in the helper class? (Neo/VM/Helper.cs)

**Comment by erikzhang** [comment]
I will create a pr for this tomorrow.

**Comment by lock9** [comment]
You're amazing, thanks man
