### ISSUE TITLE
neo-cli memory leak

### ISSUE THREAD

**Issue by prudnitskiy** [neo-project/neo#216]
I trying to use neo-cli on debian9 using dotnet from official microsoft's repository.

When I start neo, I see that memory usage is continuously grows up to full machine's memory (24Gb in my case). After NEO trying to claim more memory, OOM killing it so process crashed. I tried to update neo-cli to latest release but have no look. Is there any way to fix this issue?

I use production chain, not testnet.

**Comment by erikzhang** [comment]
Can this problem be reproduced? If you can, please specify the steps.

**Comment by prudnitskiy** [comment]
Yep, I tested it double time.

Steps to reproduce:
- install clean debian 8 machine (x86_64) (we are planing to test it on debian 9 and centos 7, I'll add test results here)
- install dotnet
- download stable version of neo (we're tested on 2.7.4.0)
- run neo: `dotnet neo-cli.dll /rpc`
- wait some time

Depends of your RAM it takes about 1 to 5 days before NEO will take all ram and then crashed.

**Comment by erikzhang** [comment]
What if we start it without `/rpc`?

**Comment by prudnitskiy** [comment]
I removed database directory and memory leak has gone - no matter if I use rpc flag or not. I'll be watching on memory consumption in next days.

**Comment by erikzhang** [comment]
> I removed database directory and memory leak has gone - no matter if I use rpc flag or not.

What do you mean by "removed database directory"? Is it a resync of blocks?
