### ISSUE TITLE
What would be the price of Gas after 3.0 Release ? It will go down ? Because of unlimited supply ?

### ISSUE THREAD

**Issue by garrey332** [neo-project/neo#2175]
**Delete this: We would like to use GitHub for bug reports and feature requests only however if you are unable to get support from our team in: our [Discord](https://discord.io/neo) server or in our [offical documentation](https://docs.neo.org/docs/en-us/index.html), feel encouraged to create an issue here on GitHub.**

**Comment by Tommo-L** [comment]
Not sure.

On the one hand, the circulation is not very large at the moment. On the other hand, the inflation rate can be controlled through governance, similar to DAO.

**Comment by erikzhang** [comment]
But don’t forget that there is a fee burning mechanism comes with 3.0.

**Comment by LG55** [comment]
> But don’t forget that there is a fee burning mechanism comes with 3.0.

hello mr Erik, got a question, when 2.0 migrates to 3.0 is it better for Gas price is low? Tx can still be low cost as Gas is divided right? After all GAS is the main thing of NEo ecosystem, most holders hold Neo because of Gas rewards. Soo is it better to have low or high price of Gas at 3.0?? tnx
