### ISSUE TITLE
Investigate using RecyclableMemoryStream for serialization in neo

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2184]
I recently discovered this project from MSFT: https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream. Given how frequently Neo creates memory streams, RecyclableMemoryStream seems like it could reduce overall GC pressure and improve performance

**Comment by erikzhang** [comment]
> ToArray - It looks similar to GetBuffer on the surface, but is actually significantly different. In ToArray the data is always copied into a new array that is exactly the right length for the full contents of the stream. This new buffer is never pooled. Users of this library should consider any call to ToArray to be a bug, as it wipes out many of the benefits of RecyclableMemoryStream completely.

I'm afraid it is not suitable for us, because we always use `ToArray`.
