### ISSUE TITLE
Deploy a development network

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2189]
**Summary or problem description**
It is common for projects that depend on the Neo library to break when Neo is updated. I believe this delays the project, because we detect problems very late in the development cycle. 

**Do you have any solution you want to propose?**
I think we should deploy a development network that should always build against the latest master branches. This way we can detect when the sibling projects break and also test the overall conditions of the network. 
If you guys agree, I can find a way to set up this development network.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: Development process

**Comment by devhawk** [comment]
I created a [monorepo](https://github.com/devhawk/neo-monorepo) that pulls the source of neo, neo-vm, neo-modules, neo-devpack-dotnet and neo-node into a single repo. This lets me detect compile errors early ([example](https://github.com/neo-project/neo-modules/issues/443)). I primarily use it for adapting BCTK to platform changes as soon as they happen (I also often patch the monorepo when there are compile or runtime errors I need fixed to make progress.

We could setup some automation to deploy a small private net from those binaries.
