### ISSUE TITLE
Add Sender to the contractstate

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2197]
Since now the contract script hash depends on the sender, and seems there is no way to query the sender of a deployed contract hash.  

```cs
        public static UInt160 GetContractHash(UInt160 sender, byte[] script)
        {
            using var sb = new ScriptBuilder();
            sb.Emit(OpCode.ABORT);
            sb.EmitPush(sender);
            sb.EmitPush(script);

            return sb.ToArray().ToScriptHash();
        }
```

**Comment by Tommo-L** [comment]
There's no direct correlation between contract and sender.

**Comment by cloud8little** [comment]
> There's no direct correlation between contract and sender.

but we don't have the function to input a specific deployed contract, query the sender of the contract. In fact, if we store the sender when deploying the contract, we can easily implement the feature.

**Comment by shargon** [comment]
> but we don't have the function to input a specific deployed contract, query the sender of the contract. In fact, if we store the sender when deploying the contract, we can easily implement the feature.

This can be done in the log plugin
