### ISSUE TITLE
fix broken link to docker image

### ISSUE THREAD

**Issue by rboyd** [neo-project/neo#22]
https://github.com/AntShares/AntShares/wiki/Bookkeeping-Node-Deployment links to a missing docker image. anyone have current?

**Comment by rboyd** [comment]
odd.. it works now. there is 1 broken image link on the page though under "dotnet run". was it just to show successful output?

https://camo.githubusercontent.com/91cdd7d22b810a4d845525d7900d7034dfb3ad42/68747470733a2f2f7777772e616e746170702e746563682f7374617469632f6877617070312e676966

**Comment by rboyd** [comment]
should we also publish signed checksums of all binary downloads?

**Comment by PeterLinX** [comment]
You can find docker image here(https://pan.baidu.com/s/1jI0TIJW#list/path=%2FDocker). Link in https://github.com/AntShares/AntShares/wiki/Bookkeeping-Node-Deployment is valid.

**Comment by PeterLinX** [comment]
I think signed checksums is necessary. We will add it. Thanks for your suggestions.

**Comment by mhuggins** [comment]
Is there a way to download the docker image without having to download this "Baidu" client?

**Comment by erikzhang** [comment]
Maybe we should upload it to Docker Hub. @PeterLinX

**Comment by jonatanblockchain** [comment]
See #61

**Comment by PeterLinX** [comment]
@jonatanblockchain Great! I will check them.

**Comment by backnight** [comment]
@jonatanblockchain can you reference them on Docker Hub? Thanks for the great work!

**Comment by tareshss** [comment]
you can use mine, base is microsoft/aspnetcore-build (1.19GB) and neo project compiled on it. I will trim it down and write up the docker file.

 `docker pull taresh/neo-cli`

**Comment by nimgnusmik** [comment]
NEO / GAS Web Wallet https://www.neowebwallet.com

**Comment by csggene3** [comment]
Was this a functional solution? Why is this still open? It seems like these boards went very quiet around November. I hope that's not an indication of the project at large. I'm sure it's easy to figure you can sell now and worry about some new project later; just speculating of course but the dates and events correlation suggests it further.

**Comment by jonatanblockchain** [comment]
NEO prívate chain using Docker
https://github.com/CityOfZion/neo-privatenet-docker

Compile NEO smart contracts using Docker.
https://github.com/CityOfZion/neo-compiler-docker
