### ISSUE TITLE
Neo disappeared from Neon wallet no transaction history

### ISSUE THREAD

**Issue by dannyc938** [neo-project/neo#220]
I haven't opened my wallet in about a month. But I had neo in my wallet functioning perfectly until a month ago. I now have no neo, no gas and it shows no transaction history. If I were hacked, I would have anticipated seeing my Neo leaving the wallet...

Please help. I updated to the latest Neon wallet, this hasn't helped. I have also tried to see if my neo would at least show up on https://neotracker.io/wallet/ but this hasn't helped either (last time it was a wallet update issue, but my neo showed on neotracker)

**Comment by dannyc938** [comment]
Thank you, @MorpheusAdministrator !!
I was googling to see if there were any recent issues but only saw those that occurred in Nov - Jan. I'll sign up to the support channel to find out when it gets resolved.

**Comment by Keithsummer** [comment]
Hello guys, 
i need help. 100 NEO was stolen from my Neon Exchange extension wallet on 25 April 2018 :(
It was transferred to AUbTXKgEkfvJi7JEU4grSnjj8JgckJQ7iB and then quickly to AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk. Is there any hope of tracking the hacker and getting back my money? I need it to help my dad's liver cancer treatment. I am devastated :(

**Comment by Keithsummer** [comment]
Neon exchange was not of any help. They literally ignored me for weeks and only a few days ago asked if I was using the correct Neo extension. Of course I was using their extension downloaded from neonexchange.org
I feel completely helpless and I know many people are going to mock me for not storing my NEO in a hardware wallet :(

**Comment by Keithsummer** [comment]
I still don't know how anyone was able to transfer my NEO away so easily. Should Neon exchangebe liable for allowing a wallet so prone to hacking to store everyone's NEO?
If I can't get back my money, at least I hope everyone be very careful with storing your NEO on the Neonexhange wallet extension

**Comment by Keithsummer** [comment]
I was able to find some posts about NEO being stolen by account AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk.
Is there a way to know what wallet address is this? Exchange or another Neon Exchange address or something?

**Comment by Keithsummer** [comment]
My own account is AVMvvwfAHds8P4kuTnSyeV3ir6p11drY8W . I am not asking for any donations. I suppose the hacker will just steal your donation away anyway. You can check my account to see my 100 NEO being transferred to  AUbTXKgEkfvJi7JEU4grSnjj8JgckJQ7iB and then  to AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk

**Comment by Keithsummer** [comment]
Someone please help :(

**Comment by Keithsummer** [comment]
If the hacker of AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk sees this post, please return the 100 NEO to me at AVMvvwfAHds8P4kuTnSyeV3ir6p11drY8W.  I really need the money for my dad's cancer treatment. I beg you. You have more than 900,000 NEO and this 100 NEO means nothing to you, but it affects my family greatly.
