### ISSUE TITLE
Neo Gui Smart Contract token overflow

### ISSUE THREAD

**Issue by Sinepitiss** [neo-project/neo#221]
I want to create a NEP-5 token with a supply of 100'000'000'000 and precision of 8.
That amounts to:
10000000000000000000
ulong max value is:
18446744073709551615
so great ,I can easily make a token with the amount I wish ,I did just that and then I called deploy method that gives all of these tokens to my wallet ,the end result in neo-gui was this:
![image](https://user-images.githubusercontent.com/37311547/39303563-4e69b712-495f-11e8-8ad9-001139a645a0.png) the same value when you try to cast ulong into long and get long overflow.I assume this is the source code resonsible: "public long GetData();" defined in Neo namespace under Fixed8 struct.
Could anyone please fix this issue?I could do that myself ,but I've never contributed to a opensource project and to one like this ,which spans multiple projects and I don't really know the workflow and I assume that this function is used by multiple solutions and so.

Thanks for the attention.

**Comment by erikzhang** [comment]
@Sinepitiss  Can you please provide me the hash of your NEP-5 contract so that I can find the issue?

**Comment by Sinepitiss** [comment]
No,because I made this contract in private network ,but I can provide you with example:
https://github.com/ANDIT-Solutions/NEO-NEP5.1/blob/master/NEP-5.1.cs
only please change **total_amount** variable value to   **100000000000** so that you can reproduce the bug.

**Comment by erikzhang** [comment]
I will try it.

**Comment by Sinepitiss** [comment]
Thanks!
