### ISSUE TITLE
Can't open project on VS

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2214]
**Describe the bug**
I can't open the solution using VS 2019. I never had this problem before. It tries to migrate the project but fails with a strange error message:
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred while restoring NuGet packages: '' is not a valid version string.`				

![image](https://user-images.githubusercontent.com/38396062/104142912-50c4a400-539c-11eb-89a2-f5c4e492eac2.png)
![image](https://user-images.githubusercontent.com/38396062/104142995-94b7a900-539c-11eb-91ab-4006babf49bc.png)

**To Reproduce**
1. Clone the project
2. Try to open the project using Visual Studio

**Expected behavior**

**Screenshots**

**Platform:**
 - OS:  Windows 10 x64
 - Version: Master branch

**Comment by ProDog** [comment]
Neo has been upgraded to .NET 5.0, have you installed the .NET 5.0 SDK?

**Comment by lock9** [comment]
Yes, I have. I can compile it using the command line (`dotnet build`)

**Comment by lock9** [comment]
@ProDog  Fixed after installing AspNet tools from within Visual Studio.
Thanks!
