### ISSUE TITLE
Role of GAS in 3.0 NEO Ecosystem and TXs

### ISSUE THREAD

**Issue by LG55** [neo-project/neo#2217]
Hello everyone i got a question? What will the main role of GAS be in 3.0 Ecosystem?

When 2.0 migrates to 3.0 is it better for Gas price is low? Tx can still be low cost as Gas is divided right? After all GAS is the main thing of NEO ecosystem, most holders hold Neo because of Gas rewards. Soo is it better to have low or high price of Gas at 3.0?? tnx

**Comment by i359** [comment]
NEO price low-> GAS price low->NEO price low

NEO price high-> GAS price high->NEO price high

**Comment by erikzhang** [comment]
We do not discuss prices on Github. I will close it.
