### ISSUE TITLE
Enforce mandatory contract "Name" field

### ISSUE THREAD

**Issue by lllwvlvwlll** [neo-project/neo#2229]
**Summary or problem description**
Currently the platform exposes and optional name field on contract deployment.  This field is *CRITICAL* for end-user platforms which have a human readable component (like explorers, exchanges, and wallets).  We cannot expect users to decipher script hashes when using the ecosystem tooling and this small change has a very minimal workflow impact for a substantial improvement to the tooling experience. 

**Do you have any solution you want to propose?**
Enforce required metadata for smart contracts

**Neo Version**
- [ ] Neo 2
- [X] Neo 3

**Where in the software does this update applies to?**
- Compiler
- CLI
- Network Policy
- VM

**Comment by erikzhang** [comment]
Now we have a `name` field in manifest, and it is not optional.

**Comment by roman-khimov** [comment]
See #2030 also.
