### ISSUE TITLE
Change requested in behavior of Blockchain_GetContract since dynamic invokes implemented

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#223]
Now that dynamic invokes are implemented, there are scenarios where a contract may want to test whether a passed scripthash is a normal address or instead is a smart contract, and change the execution flow accordingly. 

The current behavior of `Blockchain_GetContract` is to return a `false` value in the engine code when the contract cannot be found in storage, which raises a VM fault, making it impossible for the contract to continue.

I propose the behavior of the `GetContract` syscall be changed so that a null value found for a scripthash in contract storage should instead return a `false` value on the EvaluationStack in the VM, while the syscall should return a `true` value in the engine code and thus not raise a VM fault condition. This will allow contract authors using dynamic invokes to make the logical flow control decision "Contract/Not a Contract" and continue execution from there.

**Comment by localhuman** [comment]
Agreed
