### ISSUE TITLE
Contract factory example

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2233]
Hi,
How can I create a contract that creates other contract?
I want to allow my smart-contract to vote, but I want to be able to split their votes into multiple candidates. For that to work, I need to deploy one smart contract per candidate. 

I would like to know the best way to create and deploy these 'child' contracts. Is there any kind of constructor concept or equivalent feature? Is there an example?

**Comment by shargon** [comment]
The problem that you will have is that the hash is based on NefFile and sender, so if you have the NefFile static, you won't be able to deploy multiple contracts with the same file/sender, I think that we can change from sender to TX.Hash

**Comment by erikzhang** [comment]
My solution is that we can change the way of generating contract hash.

First, we can add a `nonce` to nef file. Then the contract hash will be:

```
contract_hash = hash160(ABORT, sender, checksum(nef))
```

**Comment by lock9** [comment]
Will that work Erik? How can we change the nonce before deploying the new contract? 

Can't we add some sort of constructor? We need a way to customize the deployed contract. I know that we can dismiss the need for a constructor if we add the initialization methods ourselves and call it when we deploy the contract.

**Comment by erikzhang** [comment]
> How can we change the nonce before deploying the new contract? (from a smart contract)

Use `NEWBUFFER`, `MEMCPY`, `CAT`, `SUBSTR`.

Or we can add a new method `CreateChild()` in `ContractManagement`?

**Comment by lock9** [comment]
> Use `NEWBUFFER`, `MEMCPY`, `CAT`, `SUBSTR`.


I'm in favor of a more 'developer-friendly' solution. It is too dangerous to change bytes 'manually'. Maybe the second option is better.

**Comment by roman-khimov** [comment]
Maybe we just take the name from the manifest and add it into the hash mix? This will require preparing a number of manifests, but that should be feasible and I think one would like to have these contracts have different names anyway (like NeoFS alphabet contracts, https://github.com/nspcc-dev/neofs-spec/blob/master/02-blockchain/01-governance.md). Though it makes upgrade somewhat more complicated.

Another option could be adding an explicit name parameter to override (and replace) the one we have in the manifest.

**Comment by shargon** [comment]
Why not use the Transaction hash?

**Comment by erikzhang** [comment]
> Why not use the Transaction hash?

Because you can't compute the hash at the compile time.

**Comment by shargon** [comment]
Then we can use a nonce based on the `data` (https://github.com/neo-project/neo/pull/2239).

**Comment by erikzhang** [comment]
> Then we can use a nonce based on the data (#2239).

But there is no standard on the data.

**Comment by shargon** [comment]
Add a new field on `Deploy`?

**Comment by erikzhang** [comment]
Too many fields. What about add `CreateChild()`? It create a cloned contract with different hash.

**Comment by Tommo-L** [comment]
Maybe we can do it like this. 

```
Upload -> Contract Nef file ---- instantiation(+add params to invoke deploy method) --->  Contract A
                            ---- instantiation ----> Contract B
```
