### ISSUE TITLE
Insufficient TestModeGas for register candidate

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2260]
**Describe the bug**
Insufficient TestModeGas for register candidate

How much should we choose now? 20 is not enough for register(need 1000), but we'd like to prevent malicious attack. May be we could make it into settings file? Make it default as 20 but people are able to change it and use at their own risk. 

@shargon  @erikzhang

**Comment by roman-khimov** [comment]
We had a similar problem and decided to leave the default as is (15 for neo-go), when creating registration transaction we just add an appropriate amount of GAS without test-invoking via RPC.

**Comment by superboyiii** [comment]
> We had a similar problem and decided to leave the default as is (15 for neo-go), when creating registration transaction we just add an appropriate amount of GAS without test-invoking via RPC.

I think we could add a param in config.json of neo-cli and using it in engine.run() like what we're doing in RpcServer:
`using ApplicationEngine engine = ApplicationEngine.Run(script, container: tx, gas: settings.MaxGasInvoke);`

**Comment by shargon** [comment]
I think that specific tests should have specific gas
