### ISSUE TITLE
WalletAccount.Label 

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#2264]
https://github.com/neo-project/neo/blob/aaba97844a62d8c01ca48826f0fd3167199e184c/src/neo/Wallets/WalletAccount.cs#L8

It has never been assigned a value, what is it for? Is it a field reserved for the future?

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "address": "NikhQp1aAD1YFCiwknhM5LQQebj4464bCJ",
            "haskey": true,
            "label": null,
            "watchonly": false
        }
    ]
}
```

**Comment by erikzhang** [comment]
Some clients may use it.
