### ISSUE TITLE
invoking TokensOf returns InteropInterface type

### ISSUE THREAD

**Issue by bettybao1209** [neo-project/neo#2270]
Since NFT's `TokensOf` method returns the interface `IIterator`,  the json result just shows the type `InteropInterface` rather than the token info list of the specified account.  Is it ok for that?

**Comment by erikzhang** [comment]
RPC?

**Comment by bettybao1209** [comment]
> RPC?

I invoke the method in cli.

**Comment by erikzhang** [comment]
I think it's normal. Because the result may contain thousands of data. That's why we return `iterator` as the result. If you want to get the entries returned by the `iterator`, you have to make the script by yourself.
