### ISSUE TITLE
HighPriority Tx Parse Error

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2275]
**Describe the bug**
When maketransaction with HighPriority as the attribute, the consensus node show error and stop.

**To Reproduce**
1. Start a CN node. 
2. Make a tx "send neo xxx" with high priority and send by committee accounts.

**Expected behavior**
Transaction is on-chain successfully.

**Screenshots**

![89fd0e901529c36c9df1e26d8bcd877](https://user-images.githubusercontent.com/34291844/106123039-64da1500-6194-11eb-8172-b9174995f1b9.png)

![f69988b5fad8b9d015f4adddd4816f1](https://user-images.githubusercontent.com/34291844/106123056-699ec900-6194-11eb-88aa-e308d3488b44.png)

**Platform:**
 - OS:  Windows 10 x64
 - Version master/preview4

**Comment by gsmachado** [comment]
I can confirm that this issue appears on the following commits of neo-node and neo-modules:

- https://github.com/neo-project/neo-node/tree/4a999ad66d3bc1dcf261a6329fac750caa392813
- https://github.com/neo-project/neo-modules/tree/237ef7d057265723571efde74e54001f68ce969d

**Comment by shargon** [comment]
I will fix it
