### ISSUE TITLE
Inefficient use of GETBLOCKBYINDEX payload in network

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#2279]
**Summary or problem description**
While updating my Wireshark dissector I noticed that NEO-cli during sync always uses the [GetBlockByIndexPayload](https://github.com/neo-project/neo/blob/f503027356d553681aa211afb012b4c314a9f4b8/src/neo/Network/P2P/Payloads/GetBlockByIndexPayload.cs#L10) with a `count` of 1. If you look at the screenshot you'll see that every `GETBLOCKBYINDEX` message comes from the same source address and goes to the same destination address. It seems unnecessary to send so many `GETBLOCKBYINDEX` messages while you could send 1 with a higher `count` field value.

![image](https://user-images.githubusercontent.com/6625537/106254450-0145fb00-6219-11eb-9a05-6e48f73763a6.png)

**Do you have any solution you want to propose?**
The suggestion is to use the `count` field of the `GETBLOCKBYINDEX` payload to reduce network traffic and be more efficient with the resources.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by vncoelho** [comment]
Good analysis @ixje, let's investigate that.

**Comment by Tommo-L** [comment]
This line may optimize it. https://github.com/neo-project/neo/pull/2259/files#diff-e0634b100a5b9f4296315b5e61b8067055b1bf0537b3ffe2d3c970729b13544eR15
