### ISSUE TITLE
I'm running neo-cli (2.7.4.0) and ApplicationLogs are not created!

### ISSUE THREAD

**Issue by c0ax** [neo-project/neo#228]
Hi

I'm running neo-cli using the following commands (on Windows 10) **dotnet neo-cli.dll --log --rpc** but ApplicationLogs aren't created under the main folder.

Will the ApplicationLogs be created after I'm fully synced? (currently I'm synced at block 966255).

I've gotten the rpc element of neo-cli to work but for the life of me I can't figure out how the ApplicationLogs are created!?

If someone could help me out that would be great!

**Comment by bizlevel** [comment]
I have same issues!
No logs no anything, like blind kitty ! (
I'm stuck on some block height and no have logs to see why! 
No logs, no errors - no trouble! )

**Comment by skinderis** [comment]
Yep, guys. How can I bind IP to allow connections from outside docker container?
