### ISSUE TITLE
merkleroot is always 0x00...

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2305]
**Describe the bug**

test latest commit: 11afccb51b15e8974c2bbc913c8ad4c25b5edc80 

![4eaf8452b0a084a80d48b41ff107055](https://user-images.githubusercontent.com/34291844/107142278-a4f58080-6968-11eb-8a63-1b18b3b3b64e.png)

**Comment by erikzhang** [comment]
That is because there is no transaction in the block.
