### ISSUE TITLE
AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk, please return my 100 NEO you took on 25April 2018

### ISSUE THREAD

**Issue by Keithsummer** [neo-project/neo#231]
***If the hacker of AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk sees this post, please return the 100 NEO to me at AVMvvwfAHds8P4kuTnSyeV3ir6p11drY8W. I really need the money for my dad's cancer treatment. I beg you. You have more than 900,000 NEO and this 100 NEO means nothing to you, but it affects my family greatly.***

Background,
100 NEO was stolen from my Neon Exchange extension wallet on 25 April 2018 :(
It was transferred to AUbTXKgEkfvJi7JEU4grSnjj8JgckJQ7iB and then quickly to AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk. I need it to help my dad's liver cancer treatment. I am devastated :(

Neon exchange was not of any help. They literally ignored me for weeks and only a few days ago asked if I was using the correct Neo wallet extension. Of course I was using their extension downloaded from neonexchange.org! I feel completely helpless and I know many people are going to mock me for not storing my NEO in a hardware wallet :(

I still don't know how anyone was able to transfer my NEO away so easily. Should Neon exchange be liable for allowing a wallet so prone to hacking to store everyone's NEO?
If I can't get back my money, at least I hope everyone be very careful with storing your NEO on the Neonexhange wallet extension

I was able to find some posts about NEO being stolen by AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk.
Is there a way to know what wallet address is this? Exchange or another Neon Exchange address or something?

My own account is AVMvvwfAHds8P4kuTnSyeV3ir6p11drY8W . I am not asking for any donations. I suppose the hacker will just steal your donation away anyway since this account is compromised. You can check my account to see my 100 NEO being transferred to AUbTXKgEkfvJi7JEU4grSnjj8JgckJQ7iB and then to AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk

Someone please help :(

**Comment by AshRolls** [comment]
Github is for code issues. Please join #support in discord.
