### ISSUE TITLE
NullReferenceException when starting the node

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2313]
neo: #2310
neo-node: 740
neo-modules: 517

because genesis block generated in PostPersist method, there is an error when Ledger contract get CurrentIndex.

![4e146305d4374ad6b73e0f8291558f0](https://user-images.githubusercontent.com/34291844/107237537-ce460780-6a61-11eb-878c-7c09a2d58a42.png)

![0a6c5c1606c1c5a2bbaa025b5733124](https://user-images.githubusercontent.com/34291844/107237545-d00fcb00-6a61-11eb-9b2e-22befb915629.png)

**Comment by erikzhang** [comment]
It should be fixed by #2298.
