### ISSUE TITLE
Allow `Transfer` to read states

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#2316]
**Describe the bug**
`ReadStates` and `WriteStates` are currently different flags and the latter doesn't imply the former. I think this is a bit misleading, because in most cases we use `WriteStates` read is also needed. This can lead to behavior described here https://github.com/nspcc-dev/neo-go/issues/1725 . 

**Solution**
I can think of two of them:
1. Make `WriteStates` require `ReadStates` (rename `States` to `WriteStates`). `States` is currently not used, so I think it makes sense.
2. Replace `WriteStates` with `States` in `Transfer` and possibly some other methods with callbacks (`deploy` and `update` come to mind immediately).

I prefer first solution.

**To Reproduce**
Try to read storage in `onPayment` method, like here https://github.com/nspcc-dev/neo-go/issues/1725

**Expected behavior**
`onPayment` executes correctly.

**Comment by shargon** [comment]
I like the option 1
