### ISSUE TITLE
NativeContract Invoke Error

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2335]
**Describe the bug**

Register candidate/get committee/ get next validators error.

![ceb319b955632bf72b1a9a45afb5828](https://user-images.githubusercontent.com/34291844/107853460-2f4e5080-6e51-11eb-94ae-c2bb6b4f65c4.png)

![7103b5d3133eb9211273ee4d40abec8](https://user-images.githubusercontent.com/34291844/107853457-2cebf680-6e51-11eb-89f5-75b1624f3647.png)

**Comment by erikzhang** [comment]
It seems it's not the latest version of neo.

**Comment by cloud8little** [comment]
close since it's not neo-core issue. https://github.com/neo-project/neo-node/pull/743#issuecomment-779273846
