### ISSUE TITLE
CreateStandardMultisigAccount interop

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2342]
**Summary or problem description**
There is a `System.Contract.CreateStandardAccount` interop that converts given key into standard script hash, but we can't do the same for multisig accounts which can also be useful. Multisig scripts are much more complex than single-signature scripts, so implementing `CreateMultiSigRedeemScript` in smart contract is time-consuming and error-prone.

The need to calculate proper multisig script hash is relevant for NeoFS governance scheme implementation (#2267) combined with P2P Notary system (#1573), we have all inner ring node keys in the contract, but we need to check for multisig witness of these keys.

The same problem can occur with role management contract which has `GetDesignatedByRole` method returning key array, so the user of this method can get this array but can't easily derive multisig script hash from it.

**Do you have any solution you want to propose?**
Provide `System.Contract.CreateStandardMultisigAccount` interop that will have the same input parameters as `CreateMultiSigRedeemScript` method (number of valid signatures required and a list of keys) and will return script hash to the caller.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- SDK

**Comment by vncoelho** [comment]
Since there is a need for this Native embedded feature I think it is worth implementing.
