### ISSUE TITLE
[Question] Does CalculateNetworkFee(DataCache snapshot, Transaction tx) needs to be inside Wallet? Make network fee calculation more generic.

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#2352]
The call https://github.com/neo-project/neo/blob/d73d190c87eb999c36934c1fe93aaee8c818701a/src/neo/Wallets/Wallet.cs#L356-L421 is currently inside Wallet and this makes it requires a Dummy Wallet on neo-modules RpcServer https://github.com/neo-project/neo-modules/blob/ccc2ff93599c8127ad2d5a2a21f99360d84c79b3/src/RpcServer/RpcServer.Wallet.cs#L124.

What necessarily makes it need an open wallet to make this calculation?

On NEO 2 perhaps yes, due to UTXO calculations regarding size.
However, now, we mostly just use `UInt160[] hashes = tx.GetScriptHashesForVerifying(snapshot);` which are already created and then we get the `VerificationScript` using `GetAccount(hash)?.Contract?.Script;`

I suggested to restructure these functions to a different place on the neo-core and even move them from the Rpc-Wallet, making them more user friendly in a way that `VerificationScripts` can be passed as parameters for a generic calculation.

**Comment by Qiao-Jin** [comment]
I think we still need some features in `Wallet` such as func `GetAccount` for this calculation

**Comment by erikzhang** [comment]
> I think we still need some features in Wallet such as func GetAccount for this calculation

Agree.
