### ISSUE TITLE
Extend supported standards in manifest

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#2355]
**Summary or problem description**
Currently `supportedStandards` field in manifest specifies standards which manifest supports. However, for example, NFT PR https://github.com/neo-project/proposals/pull/130/files actually defines 3 interfaces:
1. Divisible NFT
2. Non-divisible NFT
3. Method for receiving NEP-11 tokens, which can be present in any contract, not only 1 or 2.

**Do you have any solution you want to propose?**
Be more specific (may be change `supportedStandards` to `supportedInterfaces`). Something like `NEP-11/Divisible` or `NEP-11/Payable` etc. This way it is more descriptive and checks can be easily enforced during compilation or contract deployment.

**Neo Version**
- Neo 3

**Comment by roman-khimov** [comment]
Related to #1883. It'd be nice for `SupportedStandards` to have some meaningful interpretation, a contract specifying "NEP-11" there could actually mean of the three interfaces mentioned above (or combination of them), so some kind of convention is needed for various subsets of standards (that should probably also be specified in NEPs, like "contract implementing non-divisible NFT interface SHOULD specify `NEP-11/Non-divisible` in its `SupportedStandards`).

**Comment by erikzhang** [comment]
> Divisible NFT
Non-divisible NFT

They should be checked by calling `decimal()` of the contract.

> Method for receiving NEP-11 tokens

The receiver contract should not add `NEP-11` to its manifest. We can check whether a contract contains the `onNEP11Payment` method to determine whether it supports receiving NEP-11 assets.

**Comment by erikzhang** [comment]
Compilers don't care about `SupportedStandards`. They should use the abi of the contract.

**Comment by roman-khimov** [comment]
I doubt we'll ever solve divisible/non-divisible (at least if we're not replacing NEP-11), but we are much better now with receiver methods defined in NEP-26 and NEP-27, so closing this one.
