### ISSUE TITLE
Will there be support to SQRT and POW?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2357]
Hi.

Our project needs to use the square root function. Is there any plan to add it to Neo or should we just try to implement it directly in our contracts?
Flamingo uses it as well:
https://github.com/flamingo-finance/flamingo-contract-swap/blob/28c4860344b62ef1c29e12d6496703643a4d04bc/Swap/flamingo-contract-swap/FlamingoSwapPair/FlamingoSwapPairContract.Helper.cs#L44

Thanks

**Comment by erikzhang** [comment]
I think we can add them.

**Comment by shargon** [comment]
@erikzhang Like OPCODE?
