### ISSUE TITLE
If a native contract throws an exception, should it bubble up thru the VM code?

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2366]
As I understand it, native contracts are invoked via the System.Contract.CallNative sys call. `CallNativeContract` looks up the native contract by ID and then calls `NativeContract.Invoke` which uses reflection to retrieve the operation name + parameters from the invocation stack. There doesn't appear to be any try/catch blocks in that code path.

If a native contract throws, should it be caught by `CallNativeContract` and converted into a VM exception? As it stands now, a native contract exception appears to bubble up to `ExecutionEngine.ExecuteNext` . Should VM code be able to catch that native contract exception?

**Comment by devhawk** [comment]
I guess the same question applies to all SysCalls, not just System.Contract.CallNative. Should VM code be able to catch exceptions thrown in native contracts or other sys calls? if not, what should the exception handling story be?

**Comment by shargon** [comment]
It will be catched by https://github.com/neo-project/neo-vm/blob/3fb22406ba72a86fb251c763aea72677f9f9baa2/src/neo-vm/ExecutionEngine.cs#L1364-L1369

**Comment by devhawk** [comment]
In my [contract task prototype](https://github.com/devhawk/contract-task-prototype/blob/main/Program.cs), the exception was getting swallowed because I made OnSysCall async void but didn't add try/catch block inside OnSysCall. 

It appears that the expectation is VM contracts should **NOT** be able to catch exceptions thrown by native contracts or other OnSysCall implementations, that exception will cause OnFault to be called (either in OnSysCall or in ExecuteNext). Makes sense.
