### ISSUE TITLE
Send neo/gas to a contract address without onNEP17payment defined successfully

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo#2369]
**Describe the bug**

deploy a contract without onNEP17payment defined and send neo/gas to the contact address immediately so that they are dealt with in one block.

**To Reproduce**
1. Start a CN and NN.
2. Deploy the contract and send neo to the contract address. 
3. make above two tx into one block.
4. send neo to the contract address successfully, which should throw exception.

![df8fc3e836042f8ee5edaec0b2fb398](https://user-images.githubusercontent.com/34291844/109484951-04543580-7abc-11eb-8907-f36f6067b336.png)

**Comment by shargon** [comment]
> If the contract deployment tx and send neo to the contract address tx is in one block, it will not throw exception, and send neo will be successful.

I think that it's the same that send neo to a predicted smart contract address, isn't it?... if the smart contract it's wrong could be like a burn, for me it's something expected

**Comment by erikzhang** [comment]
> make above two tx into one block.

Which is the first one in the block? If the transfer is the first, it should succeed. Otherwise, if the deployment is the first, the transfer should fail.

**Comment by cloud8little** [comment]
> > make above two tx into one block.
> 
> Which is the first one in the block? If the transfer is the first, it should succeed. Otherwise, if the deployment is the first, the transfer should fail.

 `If the transfer is the first, it should succeed. ` why?

**Comment by erikzhang** [comment]
Because the contract is not deployed.

**Comment by shargon** [comment]
It's the same to send to unknown address @cloud8little
