### ISSUE TITLE
Two node can using the same P2P port for start and even sync data.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2380]
**Describe the bug**
I have two chain and two nodes for each. They're using the same Port and WsPort and within different magic. I can start nodeB after nodeA's running. And NodeB can also receive data although no connections showed on Console. There should be port conflict, right?

**To Reproduce**
1. Run Node A for A chain.
2. Make the same Port and WsPort for Node B.
3. Run Node B for B chain.

**Expected behavior**
Node B can run and blocks can be received and increase but no connections and peers are showed on Console.

**Screenshots**
![image](https://user-images.githubusercontent.com/38493437/110296101-e2633180-802c-11eb-825a-04a8c1b590f8.png)

https://user-images.githubusercontent.com/38493437/110296157-f313a780-802c-11eb-9fa1-08d3f127f114.mp4

**Platform:**
 - OS: [e.g. Windows 10 x64]
 - Version [latest]

**Comment by shargon** [comment]
I will take a look

**Comment by superboyiii** [comment]
Set Console log to be true in config.json and see the error but doesn't interrupt block sync.
![image](https://user-images.githubusercontent.com/38493437/110302348-1b52d480-8034-11eb-98e2-b95bd9b1f649.png)

**Comment by shargon** [comment]
if the exception it's captured, it could be the expected behaviour 🤔
