### ISSUE TITLE
Specify safety properties for methods defined in NEPs

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2385]
**Summary or problem description**
We have some method definitions in NEP-11 and NEP-17 using NEP-14 structure. NEP-14 defines `safe` field for methods (see #2120 also), but neither NEP-11 nor NEP-17 specify this field for methods defined there even though actual native implementations of them do have safety defined in manifests (based on required call flags).

**Do you have any solution you want to propose?**
Add `"safe": true` requirement to safe NEP-11 and NEP-17 methods.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: NEPs

**Comment by erikzhang** [comment]
Done.

https://github.com/neo-project/proposals/pull/130/commits/490c8232581f763b0eb4835a8e9f4a0104aabec5
https://github.com/neo-project/proposals/pull/126/commits/a308ae3eabc240e2e837ababdd2314d0f0587bd8
