### ISSUE TITLE
Wallet.CalculateNetworkFee calculating incorrect NetworkFee 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2388]
Attempting to deploy contract via neo-express is failing validation due to insufficient NetworkFee. Wallet.CalculateNetworkFee appears to be calculating the network fee incorrectly. In the scenario below, the CalculateNetworkFee calculates the fee at 1627000 but verification fails because network fee should be 1736000

This seems like an important fix for RC1 #2329 

``` csharp
var tx = wallet.MakeTransaction(neoSystem.StoreView, script, devAccount.ScriptHash, new[] { signer });
var networkFee = devWallet.CalculateNetworkFee(neoSystem.StoreView, tx); // network fee == 1627000
var context = new ContractParametersContext(neoSystem.StoreView, tx);
wallet.Sign(context);
tx.Witnesses = context.GetWitnesses();
var size = tx.Size; // size == 1736
networkFee = devWallet.CalculateNetworkFee(neoSystem.StoreView, tx);  // network fee == 1627000
var verificationContext = new TransactionVerificationContext();
var result = tx.Verify(ProtocolSettings, neoSystem.StoreView, verificationContext); // result == Insufficient Funds
```

**Comment by erikzhang** [comment]
@neo-project/ngd-shanghai Please check it.

**Comment by shargon** [comment]
@devhawk which kind of verification script?

**Comment by superboyiii** [comment]
@devhawk What's the relationship between wallet and devwallet? I guess it's a signer difference which cause the netfee mismatch.

**Comment by cloud8little** [comment]
@devhawk  Could you give more detail on how this transaction looks like?
Not sure whether we have the same scenario, are you trying to deploy a contract with the account who have not enough gas and want to have another wallet which have enough gas as sender? 
I tried with two wallets, devWallet(one account with 11 GAS) and CurrentWallet(2 account with 8.4622785/10.8772326).

CurrentWallet

```
NT2EJfdipEc5ifwksZH2QynVHgShmV7b2j
NEO: 0
GAS: 8.4622785

NeGfNoazya5E6gM6DBahiRnhnAn3sMrYRV
NEO: 0
GAS: 10.8772326
```

devWallet
```
NKzjMjCfsE8C9Pb1YM4hHeDVUuDQFf1sPb
NEO: 0
GAS: 11
```

1. CalculateNetworkFee has strong relationship with the calling wallet. because it will check whether the signer account belongs to the wallet. I guess that is why you got the same result.
2. when tx do verify, its networkfee does not change before wallet.Sign(context) and after.

### Scenario 1: sender and signer belongs to different wallet.
open wallet CurrentWallet, deploy contract with sender=NeGfNoazya5E6gM6DBahiRnhnAn3sMrYRV signer=NT2EJfdipEc5ifwksZH2QynVHgShmV7b2j.

```
deploy TestHash160.nef TestHash160.manifest.json NKzjMjCfsE8C9Pb1YM4hHeDVUuDQFf1sPb NT2EJfdipEc5ifwksZH2QynVHgShmV7b2j

neo> deploy TestHash160.nef TestHash160.manifest.json NKzjMjCfsE8C9Pb1YM4hHeDVUuDQFf1sPb NT2EJfdipEc5ifwksZH2QynVHgShmV7b2j
1st:2041520
1st: Tx.Networkfee 2041520
{"invocation":"DEBGVitQIS\u002Bc3A/0uHdgWH1jEa4BNPXbBD/cz6RwBjemnctKRk0HUMG7tgyVLPBKgVzFRl7SMG2SvuHLITymXwXV","verification":"DCEDH6m11TSuyJ2V5wQg5zqustKm/HsRVlzxyNDYO6OumhNBdHR2qg=="}

{"invocation":"DEDItZzUBaBl\u002BXdYb4N6Znf/8oFMimmZyVYUwa0m65FNxBgezhZ9TtAx3PZJTxXuLuHvC1xdzLtCAne4TDUKrR/t","verification":"DCEDJNxhd91abS27VaXQ3Bvm\u002BL\u002BKHiyj3zJSgfXept9YVnpBdHR2qg=="}

witness varsize: 217
size: 1166
2nd:3133040
tx Netfee: 2041520
result:InsufficientFunds
```

### Scenario 2: sender and signer belongs to the same wallet.
open wallet CurrentWallet, deploy contract with sender=NeGfNoazya5E6gM6DBahiRnhnAn3sMrYRV signer=NT2EJfdipEc5ifwksZH2QynVHgShmV7b2j.

```
neo> deploy TestHash160.nef TestHash160.manifest.json NeGfNoazya5E6gM6DBahiRnhnAn3sMrYRV NT2EJfdipEc5ifwksZH2QynVHgShmV7b2j
1st:950000
1st: Tx.Networkfee 3133040
{"invocation":"DEAPeg1x2WuWw/PCrp1s8D9LwtmSdZZtrxB9LL2w/jzG1lJPfYFzvDKjf8DYH\u002BcOy0sKallVFKuj3c2vr3\u002BGbXTf","verification":"DCEDdZskjbzqXguci5XUPwYlo46yTLS9QXRVq1ux0H22d\u002BBBdHR2qg=="}

{"invocation":"DEDwqJ84\u002Bei/0GXCduN8\u002Bzxz6o/0am/GjgO4z\u002B8iPS4J\u002BJbWxoB6pEyHTmaRzHyy\u002Bb\u002BSFHEhGD\u002Bi3iVRNqP10Z9u","verification":"DCEDJNxhd91abS27VaXQ3Bvm\u002BL\u002BKHiyj3zJSgfXept9YVnpBdHR2qg=="}

witness varsize: 217
size: 1166
2nd:3133040
tx Netfee: 3133040
result:Succeed
```

**Comment by devhawk** [comment]
> @devhawk What's the relationship between wallet and devwallet? I guess it's a signer difference which cause the netfee mismatch.

[ExpressWallet](https://github.com/ngdenterprise/neo-blockchaintoolkit-library/blob/master/src/bctklib-3/models/ExpressWallet.cs)/[ExpressWalletAccount](https://github.com/ngdenterprise/neo-blockchaintoolkit-library/blob/master/src/bctklib-3/models/ExpressWalletAccount.cs) are simple models types for JSON serialization.

[DevWallet](https://github.com/neo-project/neo-express/blob/master/src/neoxp/Models/DevWallet.cs)/[DevWalletAccount](https://github.com/neo-project/neo-express/blob/master/src/neoxp/Models/DevWalletAccount.cs) are subclasses of Wallet/WalletAccount for use in Neo Express - for example, DevWallet/Account don't password protect private keys. 

There is no signing code in DevWallet that isn't inherited from Wallet

**Comment by devhawk** [comment]
> @devhawk which kind of verification script?

whatever ContractParametersContext.GetWitnesses creates

**Comment by devhawk** [comment]
Note, I think the problem is that CreateMultiSigRedeemScript and CreateSignatureRedeemScript have changed since preview 5, so my old neo express files are invalid

**Comment by ZhangTao1596** [comment]
> Note, I think the problem is that CreateMultiSigRedeemScript and CreateSignatureRedeemScript have changed since preview 5, so my old neo express files are invalid

Close?
