### ISSUE TITLE
Allow to start from version N (and enable contracts) in NativeUpdateHistory

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2395]
**Summary or problem description**
`NativeUpdateHistory` setting introduced in #2332 is implemented as an array where we specify activation heights of contract versions, so version 0 is supposed to be activated at `arr[0]` height, version 1 at `arr[1]`, etc. #2361 then allowed to disable contracts if needed by not specifying them in the configuration.

As activation history is specified as an array, it can't start at version 1/2/etc, version 0 can't be avoided. It's not a problem at the moment and it probably won't ever be a problem for mainnet just because it's supposed to be started once at version 0 and then be updated, but suppose that we're at current version 2 of some contract and we're trying to setup a private network, we don't want to use version 0, we want to use current version. We need some syntax for that.

The same problem occurs if we're to run a network without some contract and later we'd like enable version 2 of it.

**Do you have any solution you want to propose?**
It probably can be specified as `[0, 0, 0]` or `[42, 42, 42]`, but that looks a little weird and needs some additional logic to consecutively enable various versions of contract.

We can change this setting to `index: version` map, so that activating version 2 from block 0 would look like `"0": 2`, activating from block 42 like `"42": 2` and regular mainnet config would look like `"0": 0, "42": 1, "100500": 2`.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: native contracts

**Comment by erikzhang** [comment]
I think `[0, 0, 0]` is good.

**Comment by roman-khimov** [comment]
No more opinions on this in a week, so let's settle on `[0, 0, 0]` scheme, current syntax allows for that already.
