### ISSUE TITLE
Notify about role changes

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2410]
**Summary or problem description**
There are cases when external backend software needs to react on role management updates (and #2267 is one of them, we need to track `NeoFSAlphabetNode` role), but at the moment `RoleManagement` contract doesn't notify about role changes.

**Do you have any solution you want to propose?**
Add a notification to `designateAsRole` method:
```
{
  "name": "designation",
  "parameters": [
    {
      "name": "block", // block number
      "type": "Integer"
    },
    {
      "name": "role", // role id
      "type": "Integer"
    },
    {
      "name": "keys", // array of ByteString elements with serialized keys
      "type": "Array"
    },
  ]
}
```

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: RoleManagementContract

**Comment by shargon** [comment]
Maybe `keys` is not needed, you can call the method in order to get it

**Comment by roman-khimov** [comment]
Not critical, true, but a bit more convenient for receiver of this event.
