### ISSUE TITLE
Committee lock for ContractManagement contract

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2427]
**Summary or problem description**
NeoFS chain currently is the same as main Neo chain except for some extensions and governance nuances. It has internal GAS token as well which has no value, but it still regulates who can access the chain and prevents abuse. At the same time active users (like storage node owners) will get this GAS for their operation and as the chain is functionally the same they might as well use it for other things like deploying some new contract and invoking it.

Of course they'll still be limited by the amount of GAS they have, but this chain is special, even though it's public it's not supposed to run any other contracts but NeoFS ones. Therefore it'd be nice to have ability to disable contract deployments on this chain. The same feature can be used in other special-purpose private networks.

**Do you have any solution you want to propose?**
Add `committeeLock` and `committeeUnlock` methods to `ContractManagement` contract. Both can only be invoked by the committee, the first one disables any deployments from non-committee addresses, the second one enables them. This will still allow the committee to deploy, but prevent deployments from regular users.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: ContractManagement contract

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/ebf3f5c7d00ac34b4e6cf39ad4ca74c9e3b1b797/src/neo/SmartContract/Native/ContractManagement.cs#L117

The easiest way is to set the minimum deployment fee to a very high value.

**Comment by roman-khimov** [comment]
For some reason I thought that it has an upper bound limit like most policy values, but it's not and it can be like 1M GAS to deploy easily. Which shouldn't be a problem for committee in this scenario (after initial set of deployments, subsequent ones are very rare), and at the same time we don't expect regular user to ever get this much GAS to even try deploying.

So it should work.
