### ISSUE TITLE
MerkleBlockPlayloads.Create flags check

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#2428]
**Summary or problem description**
`MerkleBlockPlayload`s can be created that can be serialized but not deserialized.

The `Flags` attribute can depend on the transaction count if the tx count is 2 or more
https://github.com/neo-project/neo/blob/ebf3f5c7d00ac34b4e6cf39ad4ca74c9e3b1b797/src/neo/Network/P2P/Payloads/MerkleBlockPayload.cs#L63

however the `MerkleBlockPlayload.Create` function doesn't check for this limit. Should the payload fail to be created if the `flags` size is less than `max(tx count, 1)` ?
https://github.com/neo-project/neo/blob/ebf3f5c7d00ac34b4e6cf39ad4ca74c9e3b1b797/src/neo/Network/P2P/Payloads/MerkleBlockPayload.cs#L47-L48

**Do you have any solution you want to propose?**
validate the flag size 

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by shargon** [comment]
We usually do these checks during deserialization
