### ISSUE TITLE
Link to Discord isn't working any more. And I got banned from Telegram Channel after asking about NeoFS. WTF?!

### ISSUE THREAD

**Issue by GhostTyper** [neo-project/neo#2429]
This Link isn't working: [Discord](https://discord.io/neo).

Also I (@GhostTyper) got banned for nothing after asking about NeoFS from the Telegram channel and I really want to know why, because such a thing never happened to me at all.

**Comment by steven1227** [comment]
Will contact the admin of both Discord and Tele. Be patient and polite Neo Fans @GhostTyper ~

**Comment by GhostTyper** [comment]
@steven1227: The discord link is working, thank you.

I hope, I get unbanned from telegram or at least that some one states me the reason so that I won't run into this issue on discord. XD

**Comment by GhostTyper** [comment]
@steven1227: It seems like I get automatically kicked from this discord after a few minutes. Did I miss some rules to accept or some other thing?

I'm also unbanned on telegram. Thank you.
