### ISSUE TITLE
NEF Magic

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo#2437]
https://github.com/neo-project/neo/blob/8d7ad96ee7d04529589e865d24e0a99954964821/src/neo/SmartContract/NefFile.cs#L33-L36
Dear Neo Team, I am a new developer. I have a question:
What is the meaning of this Magic, which is not the same as Network Magic?

**Comment by erikzhang** [comment]
It is the ASCII code of "NEF3".
