### ISSUE TITLE
Can+t send GAS from NEON wallet 2.6.2

### ISSUE THREAD

**Issue by phantasticalesh** [neo-project/neo#2438]
Hi

is there still a problem with sending GAS from NEON wallet 2.6.2 to Binance? None of the options work. Whichever FEE option I choose I get this error:

Error: Based on the size of this transaction a fee of at least 0.33546000000000004 GAS is required.

I want to transfer 12 GAS and have 13.5

I don't get it

**Comment by steven1227** [comment]
@phantasticalesh Thanks for your question. I would like you to post this issue to [Neon wallet](https://github.com/CityOfZion/neon-wallet) github. I promise they are willing to provide you solution.

**Comment by phantasticalesh** [comment]
Ok, did it
