### ISSUE TITLE
Change class name from CoinReference to TransactionInput

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#245]
Hello,
Sorry for the useless issue, but is there any chance that the CoinReference class could be renamed to TransactionInput? The name in code is "Coin Reference", but every other place that we mention it, we call it a "Transaction Input"
I understand that renaming classes can mess with other people code, so I'm cool if you guys want to close this.
Note: If this is accepted, I think we should also change the name of UnspentCoinState to UnspentTransactionState.

**Comment by erikzhang** [comment]
It's been renamed from `TransactionInput` to `CoinReference`, and now you're asking me change back ...

**Comment by lock9** [comment]
Sorry Erik, I didn't know that! If you think the correct name is CoinReference, please keep it. I'm just pointing it because I'm reviewing the code and the documentation and looks like it would make more sense to call it TransactionInput or "TransactionReference" (something in between). 
Maybe it's the documentation that should be changed?
Please keep it the way you consider correct!
