### ISSUE TITLE
Add all signers to the Transaction when serializing with ToStackItem

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo#2460]
**Summary or problem description**
I was looking for a way to fetch the transaction signers in a contract invocation. I thought I could get them from the `Transaction` returned by `Runtime.GetScriptContainer()`, but that `Transaction` object only contains the hash of the sender, not of any other signers. Checking `Transaction.ToStackItem()` shows that the signers are explicitly left out of the returned stack item.

What's the reason for this.

**Do you have any solution you want to propose?**

Add all signers to the stack item returned from `Transaction.ToStackItem()`.

**Neo Version**
Neo N3 RC2

**Comment by erikzhang** [comment]
Why do you need to fetch the signers? I think we should use `CheckWitness`.

**Comment by erikzhang** [comment]
Fixed by #2685
