### ISSUE TITLE
Recovery Neon.Setup.0.0.7.Windows

### ISSUE THREAD

**Issue by bsa1jat** [neo-project/neo#2462]
I setup a wallet in 2017 using the windows install below on an old computer:

Neon.Setup.0.0.7.Windows

I was able to trace the wallet address from an exchange that sent funds to the NEO wallet.

The credentials i had saved locally was for neowallet.com and a password, but I'm not sure how this password can help me access the funds.

my ledger was used to connect at that time but when I load my ledger(s) now none reflect the public address above that contains the funds.

I've tried to sync the ledgers to the old app below (pic) and the new app https://neonwallet.com/

I'm able to access funds on my ledgers after firmware updates for other coins so I dont feel its a ledger/seed issue.

Any suggestions?  Thank you

Screenshot at April 20th 2021 - 10.02.29 am.png

**Comment by neocactus3** [comment]
Hey sounds like headache - hopefully you'll be able to recover your Neo. I'd suggest asking on support on discord and the Neo Telegram.

**Comment by PaschaC420** [comment]
# @

**Comment by PaschaC420** [comment]
##2460

**Comment by bsa1jat** [comment]
Thank you, what is the support contact/link details for who I should ask?  I prefer github but can use telegram

**Comment by bsa1jat** [comment]
Thank you
