### ISSUE TITLE
Neon.Setup.0.0.7.Windows  Recovery

### ISSUE THREAD

**Issue by bsa1jat** [neo-project/neo#2463]
I setup a wallet in 2017 using the windows install below on an old computer:

Neon.Setup.0.0.7.Windows

I was able to trace the wallet address from an exchange that sent funds to the NEO wallet.

The credentials i had saved locally was for neowallet.com and a password, but I'm not sure how this password can help me access the funds.

my ledger was used to connect at that time but when I load my ledger(s) now none reflect the public address above that contains the funds.

I've tried to sync the ledgers to the old app below (pic) and the new app https://neonwallet.com/

I'm able to access funds on my ledgers after firmware updates for other coins so I dont feel its a ledger/seed issue.

Any suggestions? Thank you

**Comment by neocactus3** [comment]
Hey @bsa1jat,

No this isn't support. This is a workspace for Neo Devs. Here are better places for support:

Discord: https://discord.gg/Ap6Gurzc
Reddit: https://www.reddit.com/r/NEO/
