### ISSUE TITLE
Replace by Fee - Additional selection for Consensus Nodes

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#2466]
Recently, we have been seen congestion on Binance Smart Chain, which has a similar consensus mechanism of Neo.
There,users can Replace by Fee similarly to Ethereum wei price.

In the absence of such mechanism on Neo (replacing by fees), I suggest:

* That Consensus Nodes propose solutions a % of txs (5-10%) with lower fees **Only IF** mempool has passed a **threeshold**  of transactions.

That mechanism would enable transactions that were sent with lower fees to be processed.

The new transactions will follows higher prices because users will be aware that system is suffering congestion.

**Comment by roman-khimov** [comment]
> In the absence of such mechanism on Neo (replacing by fees)

It can be implemented with #1991.
