### ISSUE TITLE
Add Base58CheckEncode/Base58CheckDecode to the StdLib native contract

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#2467]
**Summary or problem description**
The StdLib native contract includes base58 Encode/Decode but not Base58CheckEncode/Base58CheckDecode. Base58 without the checksum doesn't provide a lot of advantage over the existing base64 encode/decode functions. It would be way more useful to include Base58CheckEncode/Base58CheckDecode so that contracts could convert between scripthashes and addresses for Neo2 and N3 (and other chains that also use Base58Check addresses).

**Do you have any solution you want to propose?**
Include Base58CheckEncode/Base58CheckDecode in the StdLib native contract.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Other: Native contracts

**Comment by PaschaC420** [comment]
[](url)
