### ISSUE TITLE
Add Event to Oracle to support  automated smart contract

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2473]
Oracle can not only provide the data feed; it can also be used to provide events from the real world. Such as deferred transactions to make the smart contract more automated. For example, transactions like `Buy some neo when the price of neo is below 100 USD`  or `Send 10 neo to Alice when the Block Height is over 7,372,612` are impossible to be executed automatically for the smart contract because the only way to activate smart contract is by sending transactions. Therefore, the user must send a transaction himself when the price of neo is below $100, the statement `if` or `when` can only be checked by the user. But with Oracle, the user could send such deferred transactions and register events to Oracle. When Oracle notices that the required condition is met, it then triggers the transaction automatically.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- SDK
- Oracle

**Comment by shargon** [comment]
User must pay for this work, in the past I proposed something similar https://github.com/neo-project/neo/issues/672 but it was agreed to do it on the client.

**Comment by Liaojinghui** [comment]
> User must pay for this work, in the past I proposed something similar #672 but it was agreed to do it on the client.

I think doing it on the client is a different thing. Having events supported can make smart contract more automated. Since we already have Oracle, we can empower neo smart contract with it.

**Comment by vncoelho** [comment]
Agree @Liaojinghui

**Comment by Liaojinghui** [comment]
> Agree @Liaojinghui

Hi, vncoelho, do you know how could i get the event of a new Block in the plugin?
