### ISSUE TITLE
Vote method should clear storage when voteTo is null

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo#2485]
**Describe the bug**
Call `get accountstate` after `unvote`, find that the storage of my last vote still exsits.
![image](https://user-images.githubusercontent.com/43694095/119763898-feb39380-bee2-11eb-9da6-ef926870ec9f.png)
If the neo balance of this address changes, the storage will change, too.
![image](https://user-images.githubusercontent.com/43694095/119764237-9e712180-bee3-11eb-8452-6b60aab90733.png)

**Expected behavior**
The storage should be cleared when voteTo is null.

**Comment by shargon** [comment]
> The storage should be cleared when voteTo is null.

neo-node should check if it's null before parse it
