### ISSUE TITLE
neo cli couldn't start from docker image

### ISSUE THREAD

**Issue by gitloverr** [neo-project/neo#2489]
hi everyone,

I would like to start a neo full node on linux os. I'm trying to up it  via your docker image like that:
 > https://github.com/neo-project/neo-node/#build-into-docker

I changed the **content of config.json** with **config.test.json** for start the **neo test network** 

I installed docker image and then start it like this cmd:

**`docker run -d -p 0.0.0.0:20332:20332 -p 20333:20333 -p 0.0.0.0:20334:20334 --name=neo-cli-testnet neo-cli`**

but the image stopped immediately. why?

how can I up it?

thank you

**Comment by Ashuaidehao** [comment]
The docker build steps are outdated. Neo3 node requires [LevelDBStore Plugin](https://github.com/neo-project/neo-modules/releases/download/v3.0.0-rc3/LevelDBStore.zip) to start. So we need put the plugin into the directory manually. Here an example, please try to use this **Dockerfile** to build the image:

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS Build

COPY neo-cli /neo-cli
COPY Neo.ConsoleService /Neo.ConsoleService
COPY NuGet.Config /neo-cli

WORKDIR /neo-cli
RUN dotnet restore && dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS Final
RUN apt-get update && apt-get install -y \
  screen \
  wget \
  unzip \
  libleveldb-dev \
  sqlite3
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /neo-cli
COPY  --from=Build /app .

RUN wget https://github.com/neo-project/neo-modules/releases/download/v3.0.0-rc3/LevelDBStore.zip
RUN unzip LevelDBStore.zip

ENTRYPOINT ["screen","-DmS","node","dotnet","neo-cli.dll"]
```

**Comment by gitloverr** [comment]
hi @Ashuaidehao  thank you, that's work!
