### ISSUE TITLE
Hard code in ApplicationEngine about consumed gas fee causes bugs when make transaction

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2492]
**Describe the bug**
Hard code in ApplicationEngine about consumed gas fee causes bugs when making transaction. 
1. https://github.com/neo-project/neo/blob/1366e7a54c6681124914e02da3051da0dc188d60/src/neo/SmartContract/ApplicationEngine.cs#L135
When snapshot is null here, `exec_fee_factor` will choose `DefaultExecFeeFactor`, however `VerifyStateIndependent` in Transaction.cs doesn't need snapshot which can make snapshot be null. If committees decrease the amount of  `exec_fee_factor`, it will finally cause `GasConsumed`(using DefaultExecFeeFactor) > calculated `gas_amount` in `AddGas` and casuse `insufficient GAS`.
https://github.com/neo-project/neo/blob/master/src/neo/Network/P2P/Payloads/Transaction.cs#L384
https://github.com/neo-project/neo/blob/1366e7a54c6681124914e02da3051da0dc188d60/src/neo/SmartContract/ApplicationEngine.cs#L143

2. If committees increase the amount of  `exec_fee_factor` to 200, then other bugs can appear.
Such like https://github.com/neo-project/neo/blob/1366e7a54c6681124914e02da3051da0dc188d60/src/neo/Network/P2P/Payloads/ExtensiblePayload.cs#L124
it can cause consensus failed because not enough gas for execution of VerifyWitnesses.
It can also cause `GetBalance` failed. 
https://github.com/neo-project/neo/blob/1366e7a54c6681124914e02da3051da0dc188d60/src/neo/Wallets/Wallet.cs#L255

**To Reproduce**
Vote for `ExecFeeFactor` as 6 in Policy contract and make any transaction.
Vote for `ExecFeeFactor` as 200 in Policy contract and consensus crashed.

**Comment by roman-khimov** [comment]
> VerifyStateIndependent in Transaction.cs doesn't need snapshot which can make snapshot be null.

#2107

> consensus failed because not enough gas for execution of VerifyWitnesses.

This just needs to take exec fee factor into account.

**Comment by shargon** [comment]
> Vote for ExecFeeFactor as 200 in Policy contract and consensus crashed.

Could you copy the crash?

**Comment by superboyiii** [comment]
> > Vote for ExecFeeFactor as 200 in Policy contract and consensus crashed.
> 
> Could you copy the crash?

I haven't saved that snapshot, but it can be easily replay on privateNet by setting `exec_fee_factor` to 200 or 20. https://github.com/neo-project/neo/pull/2493 can fix this.
