### ISSUE TITLE
calculatenetworkfee returns insufficient GAS amount

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo#2495]
**Describe the bug**
Calling the RPC `calculatenetworkfee` returns an insufficient GAS amount that makes the transaction get rejected with -500 "InsufficientFunds" error. This only happens when a smart contract is required to be a transaction signer, e.g., when withdrawing tokens from a contract. 

**To Reproduce**
1. Deploy a simple contract that contains an owner account, an `onPayment` method, and a `verify` method that does a check witness with the owner account.
2. Fund the contract with NEO and GAS.
3. Build a transaction that withdraws NEO from the contract. As far as I know, the transaction needs to have two signers, the contract owner and the contract itself. Additionally, we need to attach a witness for the owner (holding just the verification script) and a witness for the contract (empty verification and invocation script).
The signers and witness  parts of the transaction will look similar to this:
```javascript
 "signers": [
    {
      "account": "69ecca587293047be4c59159bf8bc399985c160d",
      "scopes": ["Global"]
    },
    {
      "account": "7bc4b07f91ba097d83163a73327e1ad284eb918f",
      "scopes": ["Global"]
    }
  ],
  "attributes": [],
  "script": "DA5hIE5FTyB0cmFuc2ZlchEMFA0WXJiZw4u/WZHF5HsEk3JYyuxpDBSPkeuE0hp+MnM6FoN9CbqRf7DEexTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I=",
  "witnesses": [
    {
      "invocation": "",
      "verification": "DCEDOk0FGwS3/AIw0rGq7f1ahL4nmlNhpzWNtmWteFd4fxtBVuezJw==" // verification script
    },
    { 
      "invocation": "", 
      "verification": "" 
    }
  ],
```
4. Serialize the transaction, use the `calculatenetworkfee` RPC to fetch the networkfee, and set the returned value on the transaction.
5. Sign the transaction with the contract owner, adding the signature to the invocation script of the owner's witness.
6. Send the transaction to a Neo node.
7. The transaction gets rejected because of insufficient funds, i.e., not enough GAS on the transaction.

If you then manually add a bit more network fee to the transaction and try to send it again (first sign again), the transaction will be successful. 

**Expected behavior**
The RPC `calculatenetworkfee` should return the exact network fee needed to successfully propagate a transaction.

**Other Info**
I used neow3j SDK to produce the transaction. Neow3j SDK relies on the `calculatenetworkfee` RPC of a node because it  doesn't bring any VM or node information with it.

I know we should have tested this a while ago, once [this](https://github.com/neo-project/neo/issues/2371) issue was closed, but, we only came back to it now. Also, I still have hopes that this issue is an error from my side. Perhaps someone can enlighten me about the error of my ways.

**Platform:**
 - OS: MacOS 11.4
 - Version: Neo N3 RC2 release

**Comment by superboyiii** [comment]
@csmuller I tried to send asset from a contract via owner, the TX showed the same networkFee as what RPC `calculatenetworkfee ` returns. Here's my contract:
```
using Neo;
using Neo.SmartContract;
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Native;
using Neo.SmartContract.Framework.Services;
using System;
using System.Numerics;

namespace TestNetFee
{
    [ContractPermission("*")]
    [ManifestExtra("Author", "Neo")]
    [ManifestExtra("Email", "dev@neo.org")]
    [ManifestExtra("Description", "This is a contract example")]
    public class TestNetFee : SmartContract
    {
        public static event Action<UInt160, UInt160, BigInteger> UnlockEvent;
        //TODO: Replace it with your own address.
        [InitialValue("NLKpYEDmyGMWQVeqcoyZr9Lyo8P5Mrozba", ContractParameterType.Hash160)]
        static readonly UInt160 Owner = default;

        private static readonly StorageMap assetMap = new StorageMap(Storage.CurrentContext, "asset");

        private static bool IsOwner() => Runtime.CheckWitness(Owner);

        // When this contract address is included in the transaction signature,
        // this method will be triggered as a VerificationTrigger to verify that the signature is correct.
        // For example, this method needs to be called when withdrawing token from the contract.
        public static bool Verify() => IsOwner();

        // TODO: Replace it with your methods.

        // check payable
        public static bool GetPaymentStatus() => ((BigInteger)assetMap.Get("enable")).Equals(1);

        // enable payment
        public static void EnablePayment()
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            assetMap.Put("enable", 1);
        }

        // disable payment
        public static void DisablePayment()
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            assetMap.Put("enable", 0);
        }


        public static void OnNEP17Payment(UInt160 from, BigInteger amount, object data)
        {
            if (GetPaymentStatus())
            {
                return;
            }
            else
            {
                throw new Exception("Payment is disable on this contract!");
            }
        }

        public static bool Unlock(UInt160 toAssetHash, UInt160 toAddress, BigInteger amount)
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            var Params = new object[] { Runtime.ExecutingScriptHash, toAddress, amount, null };
            // transfer asset from proxy contract to toAddress
            Contract.Call(toAssetHash, "transfer", CallFlags.All, Params);
            UnlockEvent(toAssetHash, toAddress, amount);
            return true;
        }

        public static void _deploy(object data, bool update)
        {
            if (update) return;

            // It will be executed during deploy
            Storage.Put(Storage.CurrentContext, "Hello", "World");
        }

        public static void Update(ByteString nefFile, string manifest)
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            ContractManagement.Update(nefFile, manifest, null);
        }

        public static void Destroy()
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            ContractManagement.Destroy();
        }
    }
}

```
I invoked `unlock` method to do this. Could you tell me how does Neow3j SDK get `FeePerByte`? I recently reduced `FeePerByte` to 200 in RC3 testnet. Maybe it's the reason of this issue.

**Comment by csmuller** [comment]
This is a bit of a different use case you present here. You're calling the contract and the contract then initializes the transfer. But, my example initializes the transfer in the transaction itself. Did you try that as well?

Anyway, I will reproduce your example and report the results.

The neow3j SDK does not use `FeePerByte`. We removed any local fee calculations from the SDK since the `calculatenetworkfee` RPC was added.

**Comment by bettybao1209** [comment]
![image](https://user-images.githubusercontent.com/12050350/120977947-841e2a00-c7a6-11eb-94cb-10703fd278f4.png)
![image](https://user-images.githubusercontent.com/12050350/120977972-8c766500-c7a6-11eb-8126-ea6e0ec1a55e.png)

Maybe it is caused by the fact that the witness_script != null （but witness_script.Length == 0）, so it won't add the gas consumed for verify.

**Comment by superboyiii** [comment]
Yes, I can display this issue now and when I fixed this, the calculate result becomes the same.
![image](https://user-images.githubusercontent.com/38493437/120981714-871b1980-c7aa-11eb-833c-343263172665.png)

**Comment by csmuller** [comment]
Cool! Yes, that should solve it.
