### ISSUE TITLE
Different network fee calculation for transaction with a contract signer that has a `verify` method with parameters.

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo#2501]
**Describe the bug**

The scenario is as follows:
- I have a deployed contract with a `verify` method that takes an integer as a parameter. The contract owns GAS.
- I want to withdraw GAS from the contract, thus, I have to create a transaction that has the contract as a signer.
- AFAIK the dotnet node wants the parameter for the contract's `verify` method in the invocation script of the contract's transaction witness. The invocation script I attach to the transaction simply pushes an integer of value 1 in order that the `verify` method returns true (see contract below).
- I also attach a normal account signer to pay for the transaction fees.
- I fetch the system and network fee for the transaction from a Neo node (dotnet or Go) 

Depending on which node I use I get a different network fee and a different result/response of the transaction. Below is the contract deployed on N3 testnet (0x0031db7a58e8d2899e76be0edf21eabc7c7c2eca), and the two transactions that try to withdraw GAS from the contract. The first one used a dotnet node and the second one a Go node to retrieve fees and propagate the transaction. As you can see, the network fees of the two transactions are not the same, nor are the responses.

```java
@ManifestExtra(key = "author", value = "AxLabs")
@Permission(contract = "*", methods = "*")
@Trust("*")
public class ExampleContract {

    static Event2Args<Hash160, Integer> event;

    @OnVerification
    public static boolean verify(int i) {
        return i == 1;
    }

    @OnNEP17Payment
    public static void receiveTokens(Hash160 sender, int amount, Object input) {
        event.fire(sender, amount);
    }

}
```

Transaction sent to dotnet node:
```javascript
{
  "hash": "3c05b249f6cdfff57559ea279569e4ce44c666e13239102009ef93aa84ae4824",
  "size": 268,
  "version": 0,
  "nonce": 2367109054,
  "sender": "61026e3cbbad072f1697f0cdc1832a71aae7c66c",
  "sysfee": "5977750",
  "netfee": "1036520",
  "validuntilblock": 158024,
  "signers": [
    {
      "account": "61026e3cbbad072f1697f0cdc1832a71aae7c66c",
      "scopes": "Global"
    },
    {
      "account": "0031db7a58e8d2899e76be0edf21eabc7c7c2eca",
      "scopes": "Global"
    }
  ],
  "attributes": [],
  "script": "CxEMFGzG56pxKoPBzfCXFi8Hrbs8bgJhDBTKLnx8vOoh3w6+dp6J0uhYetsxABTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I=",
  "witnesses": [
    {
      "invocation": "DEC6AL6h8y0mjrvGIGeNjwyPb1LMuAnVTV9a63fQ3JFxCxIHh5PK+u9oZM0JwbvGKcK4seIBPGN1NOGs02LpQQLn",
      "verification": "DCEC5cZbufVMclvTMd9PcLrFZMLgBJwBi/Tbmw1o7PMAqYxBVuezJw=="
    },
    { "invocation": "EQ==", "verification": "" }
  ]
}
```
Transaction fails with error "-500, InsufficientFunds", which indicates that the network fee on the transaction is incorrect.

Transaction sent to NeoGo node:
```javascript
{
  "hash": "cf11484c63d6db02accbbaf1461c0fb400ba84cec93ab508147d787589dfcf13",
  "size": 268,
  "version": 0,
  "nonce": 2924905073,
  "sender": "61026e3cbbad072f1697f0cdc1832a71aae7c66c",
  "sysfee": "5977750",
  "netfee": "1039310",
  "validuntilblock": 157983,
  "signers": [
    {
      "account": "61026e3cbbad072f1697f0cdc1832a71aae7c66c",
      "scopes": "Global"
    },
    {
      "account": "0031db7a58e8d2899e76be0edf21eabc7c7c2eca",
      "scopes": "Global"
    }
  ],
  "attributes": [],
  "script": "CxEMFGzG56pxKoPBzfCXFi8Hrbs8bgJhDBTKLnx8vOoh3w6+dp6J0uhYetsxABTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I=",
  "witnesses": [
    {
      "invocation": "DEAtUqQj7efdojoTVxq590qiKqghfkTAJXXDHKuBOG9hvtu/0ShHSzpTeCmaYP+4mA6bHFPd43oRIUOo254Nj0h0",
      "verification": "DCEC5cZbufVMclvTMd9PcLrFZMLgBJwBi/Tbmw1o7PMAqYxBVuezJw=="
    },
    { "invocation": "EQ==", "verification": "" }
  ]
}
```
Transaction is valid, but the return value is `false` which indicates that calling the `verify` method was not successful.

**Expected behavior**

Network fees returned by `calculatenetworkfee` RPC for a transaction should be equal independent of which node is queried.
Additionally, I would expect the transaction to be successful but it isn't in both cases.

**Platform:**
 - OS: MacOS 11.4
 - Version: Neo N3 RC3
 
 @superboyiii @roman-khimov

**Comment by gsmachado** [comment]
So, in summary, there are two distinct problems in this issue...

1. The tx result should be successful, but it isn't on both;
2. Network fees returned by `calculatenetworkfee` should be the same on both neo-node implementations, but it isn't on both.

**Comment by csmuller** [comment]
Ofc, i might use the invocation script in the contract's witness wrongly. In that case please enlighten me.

**Comment by AnnaShaleva** [comment]
@csmuller, given the mentioned transaction script, you're trying to transfer NEO from the contract's account, see the opcodes dump:
```
NEO-GO-VM > loadbase64 CxEMFGzG56pxKoPBzfCXFi8Hrbs8bgJhDBTKLnx8vOoh3w6+dp6J0uhYetsxABTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I=
READY: loaded 86 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE       PARAMETER                                   
0        PUSHNULL                                                 <<
1        PUSH1                                                    
2        PUSHDATA1    6cc6e7aa712a83c1cdf097162f07adbb3c6e0261    
24       PUSHDATA1    ca2e7c7cbcea21df0ebe769e89d2e8587adb3100    
46       PUSH4                                                    
47       PACK                                                     
48       PUSH15                                                   
49       PUSHDATA1    7472616e73666572 ("transfer")               
59       PUSHDATA1    f563ea40bc283d4d0e05c48ea305b3f2a07340ef    
81       SYSCALL      System.Contract.Call (627d5b52)      
```
Here `f563ea40bc283d4d0e05c48ea305b3f2a07340ef` is the NEO contract hash.

The `0x0031db7a58e8d2899e76be0edf21eabc7c7c2eca` contract doesn't own NEO, there's GAS only on its balance:
```
curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getnep17transfers", "params": ["0x0031db7a58e8d2899e76be0edf21eabc7c7c2eca"] }' rpc1t.n3.nspcc.ru:20332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   507  100   389  100   118   1005    304 --:--:-- --:--:-- --:--:--  1310
{
   "result" : {
      "received" : [
         {
            "transferaddress" : "NVq8SdaVYZ38QnGFV3ViDdFPubm21KG1An",
            "blockindex" : 152216,
            "assethash" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
            "timestamp" : 1623758863615,
            "txhash" : "0xca4a24e8ce51fe03ca3293fde322198f9ea17b1626e75fa582527dedcd8e8db3",
            "amount" : "100000000",
            "transfernotifyindex" : 0
         }
      ],
      "address" : "NeM1NRqCqanuVX12nrtirHJb3yAGTbh9fV",
      "sent" : []
   },
   "id" : 1,
   "jsonrpc" : "2.0"
}
```

As a result, the transaction sent to the Go node passes verification, but the NEO transfer fails due to insufficient funds => we can see `false` on stack. This behaviour is expected and network fee calculated by the Go node is enough to correctly process the transaction.

The behaviour of the C# node needs to be investigated.

**Comment by csmuller** [comment]
@AnnaShaleva Thanks for pointing that out. I messed that up.
I tested again with an actual GAS transfer. You're right, the transfer is successful with the GoNode 🥳 

The issue with the C# node remains the same.

**Comment by AnnaShaleva** [comment]
Likely, the reason for insufficient network fee calculated by the C# node is [this line](https://github.com/neo-project/neo/blob/master/src/neo/Wallets/Wallet.cs#L568) of Wallet's `CalculateNetworkFee` method:
```
 var md = contract.Manifest.Abi.GetMethod("verify", 0);
```

Here to calculate network fee for the contract-based witness we're searching for `verify` method with `0` arguments, while `-1` is used in `VerifyWitness` method during real verification (see [link](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Helper.cs#L314)). This results in failing test verification => smaller network fee.

Thus, to fix this issue I'd suggest to preserve the same pattern for `CalculateNetworkFee`, i.e. use
```
 var md = contract.Manifest.Abi.GetMethod("verify", -1);
```
instead of
```
 var md = contract.Manifest.Abi.GetMethod("verify", 0);
```
