### ISSUE TITLE
Contract.Manifest is Struct, not string

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo#2503]
**Describe the bug**
Native.StdLib.StringSplit(contract.Manifest, ",") will  `FAULT`, because the 'Manifest' acquired in the contract is the `Struct`, not `string`.

**To Reproduce**
contract:
```C#
        public static ByteString TestSplit()
        {
            var contract = Neo.SmartContract.Framework.Native.ContractManagement.GetContract(contractHash);
            var splitStr = Neo.SmartContract.Framework.Native.StdLib.StringSplit(contract.Manifest, ",");
            return splitStr[0];
        }
```

invoke:
```
neo> invoke 0x6326bf39d112aca030ca4da56179454944b32cce testSplit
Invoking script with: 'wh8MCXRlc3RTcGxpdAwUziyzRElFeWGlTcowoKwS0Tm/JmNBYn1bUg=='
VM State: FAULT
Gas Consumed: 0.0394656
Result Stack: []
Error: Specified cast is not valid.
```

**Expected behavior**
`Neo.SmartContract.Framework.Services.Contract.Manifest`'s type is `string`, so the 'Manifest' acquired in the contract should be `string`.

**Platform:**
 - OS: [Windows 10 x64]
 - Version [rc3]

**Comment by cloud8little** [comment]
duplicate with https://github.com/neo-project/neo-devpack-dotnet/issues/641
