### ISSUE TITLE
(Master-2.x)Turn gas generation to 0 per block when N3 mainnet launch.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#2507]
**Summary or problem description**
Currently, we still generate GAS on Neo Legacy for 5 per block. And when N3 mainnet launch, totalSupply of Neo will be locked into Proxy contract and will never unlock unless N2 Neo are migrated to N3 via Poly Network. However, because of the different GAS distribution mechanism in Legacy and N3, we can't ensure the Circulating Supply of N3 GAS = totalSupply - N2 GAS. People in Legacy  get GAS due to how much NEO you have but in N3 due to if you vote correctly and how much in the vote pool of CN.

**Do you have any solution you want to propose?**
Make a hard fork height which is about the Mainnet Launch Time and turn gas generation to 0 per block at that height.

**Neo Version**
- Neo 2

**Comment by roman-khimov** [comment]
I think changing Legacy is a bad idea. It breaks the network, breaks users assumptions of how the network works and ultimately breaks trust. Regular NEO hodler expects things to work the way they're now and then after migration the way they're in N3 world. We can meet this expectation with appropriate transition contracts.

I expect that we'll have a contract on Legacy network that will receive NEO/GAS UTXOs from users (let's call it LTC, legacy transitioning contract) and a contract on N3 network (N3TC) that initially will get all NEO/GAS from the genesis block and then allow to withdraw NEO/GAS deposited to LTC.

Legacy network will generate GAS the way it is now, for every holder. When holder sends its NEO to LTC it becomes NEO holder and technically could claim GAS, but it MUST NOT do it, this way all NEO sent to LTC effectively stop generating GAS on Legacy network.

N3TC on the other hand will hold N3 NEO and receive GAS from holding it. We SHOULD also make it vote for some CN to receive (most of) voter GAS (though it needs to be tested first to see the exact consequences, like #2364). GasToken contract will call `onNEP17Payment` in N3TC and N3TC MUST burn this GAS because that's the GAS from undistributed NEO still circulating on Legacy network. Then user withdraws its NEO from N3TC and holds/votes normally.

This way we'll have not-yet-transitioned NEO on Legacy network that will generate GAS according to Legacy rules and already-transitioned NEO on N3 network that will follow N3 rules. Transitioned Legacy NEO is locked in LTC that will never claim and nontransitioned N3 NEO is locked in N3TC that burns all GAS generated. I think it all should work.

Of course voting in N3TC will affect validators list and make some node have a lot of votes. But eventually I'd expect most NEO to be withdrawn from it and we can unvote when it holds less than 30-50%% of total supply. Some NEO will stay in N3TC forever (blackholed on Legacy or people not caring), so be it. But regular users should be incentivized to move to N3, I know there are some plans for it, but we should also calculate the amount of GAS generated for NEO owner/voter in Legacy and N3, if N3 wins it wins and people will move.

**Comment by superboyiii** [comment]
> I think changing Legacy is a bad idea. It breaks the network, breaks users assumptions of how the network works and ultimately breaks trust. Regular NEO hodler expects things to work the way they're now and then after migration the way they're in N3 world. We can meet this expectation with appropriate transition contracts.
> 
> I expect that we'll have a contract on Legacy network that will receive NEO/GAS UTXOs from users (let's call it LTC, legacy transitioning contract) and a contract on N3 network (N3TC) that initially will get all NEO/GAS from the genesis block and then allow to withdraw NEO/GAS deposited to LTC.
> 
> Legacy network will generate GAS the way it is now, for every holder. When holder sends his NEO to LTC it becomes NEO holder and technically could claim GAS, but it MUST NOT do it, this way all NEO sent to LTC effectively stop generating GAS on Legacy network.
> 
> N3TC on the other hand will hold N3 NEO and receive GAS from holding it. We SHOULD also make it vote for some CN to receive (most of) voter GAS (though it needs to be tested first to see the exact consequences, like #2364). GasToken contract will call `onNEP17Payment` in N3TC and N3TC MUST burn this GAS because that's the GAS from undistributed NEO still circulating on Legacy network. Then user withdraws its NEO from N3TC and holds/votes normally.
> 
> This way we'll have not-yet-transitioned NEO on Legacy network that will generate GAS according to Legacy rules and already-transitioned NEO on N3 network that will follow N3 rules. Transitioned Legacy NEO is locked in LTC that will never claim and nontransitioned N3 NEO is locked in N3TC that burns all GAS generated. I think it all should work.
> 
> Of course voting in N3TC will affect validators list and make some node have a lot of votes. But eventually I'd expect most NEO to be withdrawn from it and we can unvote when it holds less than 30-50%% of total supply. Some NEO will stay in N3TC forever (blackholed on Legacy or people not caring), so be it. But regular users should be incentivized to move to N3, I know there are some plans for it, but we should also calculate the amount of GAS generated for NEO owner/voter in Legacy and N3, if N3 wins it wins and people will move.

The problem is that N3TC can only vote for one CN, and someone could migrate some NEO to vote and earn most gas in one CN vote pool. And how to explain to the others that NF is using N2 holders' uncrosschain NEO to vote for their own CN? This could make thing more complex and negative. From myside, stop generation GAS on Legacy is a good way to encourage holder to migrate asset to N3. On the other hands, if we don't stop generation GAS on N2, it also unclear for exchange to handle.

**Comment by roman-khimov** [comment]
> N3TC can only vote for one CN

Meet NeoFS alphabet contracts, NEO can be distributed among 7 or 21 contracts to vote for standby validators (committee) initially. We trust them anyway and it can make transition to proper voting more gradual.

> stop generation GAS on Legacy is a good way to encourage holder to migrate asset to N3

Well, it's as encouraging as kicking in a butt which is effective short-term, but raises some questions long-term.

**Comment by superboyiii** [comment]
> > N3TC can only vote for one CN
> 
> Meet NeoFS alphabet contracts, NEO can be distributed among 7 or 21 contracts to vote for standby validators (committee) initially. We trust them anyway and it can make transition to proper voting more gradual.
> 
> > stop generation GAS on Legacy is a good way to encourage holder to migrate asset to N3
> 
> Well, it's as encouraging as kicking in a butt which is effective short-term, but raises some questions long-term.

What's the long-term questions? It's expected to get more GAS rewards in N3 due to our ecnomic model.

**Comment by roman-khimov** [comment]
In general people don't like to be pushed around and forced to do anything. They also don't like changing the rules while playing. Of course N3 by its nature forces everyone to move and changes some core parameters, but we should make this transition as smooth as possible. Incentivize the move, but don't cut people off of GAS they think they deserve in Legacy. Start the new network, but let the old one stay available for as long as there is a need for it.

For long-term project success people should see Neo as reliable and predictable network. What kind of predictability could people expect if the next Legacy release is to completely break the economic model behind it? What kind of reliability could developers (spending their time and effort, building projects they want to succeed) expect if the next release can change any core principles of the network? Technical superiority is not enough on its own, if I were considering a network for my dApp I'd be interested in how project is managed, what's the process for protocol changes, how backward compatibility is maintained. How a change like this answers these questions?

I think we can and should avoid doing it.

**Comment by lllwvlvwlll** [comment]
Breaking GAS generation in Neo Legacy is not a viable business decision. It will ruin our reputation and the trust the community has placed in us. 

It would be better to use something like an inflationary scalar instead since we know what the generation rate is. We can devalue the gas as it transfers to account for that.

**Comment by vncoelho** [comment]
I think it is a plausible idea and simple, @superboyiii, this direction looks good to me.

**Comment by igormcoelho** [comment]
The idea is interesting @superboyiii , although it could be a little too drastic, as @lllwvlvwlll  mentioned... afterall, there are still applications running on Legacy Neo. I feel that some compensation mechanism could co-exist, specially after migration begins. As long as no NEO can be held on both Legacy and N3, to possibly generate GAS on double, it's more a matter of some temporary exceeding of expected total supply (that could be fixed later by burning, for example). It's an interesting discussion.

**Comment by shargon** [comment]
If we are not going to take into account future neo transfers after that height, why worry about gas?

**Comment by ioannistsil** [comment]
i think you need to explain to all neo community how you will handle the migration so won't be any black dots.

**Comment by deanragnarok** [comment]
I completely agree with @roman-khimov and @lllwvlvwlll. Turning GAS generation to 0 on Neo Legacy is a non-starter as far options go.  This may seem like a technical / logistical issue, but it has very real emotional / financial / trust issues attached to it as well that need to be factored in as part of the decision.

I also agree with Roman's outline of how this should play out in reality. GAS generated in the LTC contract should never be claimed. Any GAS generated in the N3TC contract should be burned. There will be a period of uncertainly with supply fluctuation, but I think it is a short term issue. We will look back at in a few years a trivial. 

The voting piece is a little bit tricky. If we're going to have a "default council" as [described here](https://neo.org/blog/details/4232), voting from the N3TC wallet would break this right away as it would instantly exceed 20%

To be honest, I'm not really concerned about people migrating, voting right away, and getting an inflated GAS generation rate. Has anyone ever seen a scenario in the crypto space where, if an opportunity to make easy money came up, it wasn't immediately pounced upon by tons of people right away? The very nature of this behaviour will likely cause the situation to solve itself very quickly as the more people that try and jump in while the GAS generation is at its highest, the quicker it will come down to a more level playing field. This in itself will incentivise quick migration to N3.

To those who do briefly get an amazing GAS rate, congratulations to them for being one of the earliest N3 adopters and voting participants.

**Comment by superboyiii** [comment]
> i think you need to explain to all neo community how you will handle the migration so won't be any black dots.
> also giving some kind of airdrop for those who swap legacy to N3 is a good idea
> add a time frame for legacy gas generation

The official proxy contract will open source on github and when someone locks his Legacy NEO or GAS and cross to N3's proxy contract, it's like a burn on N2 and no one could release these assets and at the same time N3 proxy will release the same number. We have state root both on N2 and N3 to ensure consistency and security. Poly Network is also reliable since more than $6 Billion assets (including Neo) has been crosschained on it. We've made a brief guide for that: https://github.com/neo-ngd/CrossChainExample/blob/main/migration_EN.md Wish you know more about it.

**Comment by superboyiii** [comment]
@roman-khimov @deanragnarok @shargon @lllwvlvwlll  We've made a more gentle plan which is to stop Neo Legacy GAS generation at a certain height (i.e. 800W, can be confirmed later) to ensure the generated GAS on Legacy can be calculated so that exchange can go on lising N3 GAS. Thus, we can make a buffer for N2 users or projects to migrate smoothly. At the same time, most of N3's GAS will be locked in proxy contract since NEO will be there (the same to burn) and wait for Legacy's NEO to crosschain to N3 to generate other new GAS.
I know people have their different benefits from their sides (holders, exchanges, players...), we can't make it meet everyone's benefit, but we're trying to figure out where the middle ground is. We have to know the fact that Legacy will be off some day(may be in 2 years), and exchange will accept 2 kind of GAS from Legacy and N3, if we don't close GAS generation on Legacy, the inflation (10 gas per block in sum on two chains per block) will do nothing good even for holders on Legacy as well. Neo official will make a webpage to let people migrate very easily (like the experience of swap on flamingo). Exchange will support two chains' assets so people can deposit Legacy's GAS and withdraw N3's GAS easily. But firstly, we have to move on together. Wish you could know this.
