### ISSUE TITLE
Is it safe to assume that methods with an underscore ( _ ) are private and are only accessible from Native Contracts?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2508]
Hi,
We have the "_deploy" method. Looking at the Neo code, it seems that methods with an underscore prefix can't be called (ApplicationEngine.Contract, line 64). Do I need to add 'extra logic' to protect this method from being called by another party, or is it safe to assume that it will only be called once, by the contract manager?

**Comment by erikzhang** [comment]
It won't be called by other contract.
