### ISSUE TITLE
Add Ledger.GetNetwork native method

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#2513]
**Summary or problem description**
Sometimes it is useful for a contract to be able to determine which network it is running on so the developer doesn't have to maintain two versions in case some function should be disabled on MainNet and vice-versa.

Currently the common method to do this is to get a specific block by height and check its timestamp and match it to the known timestamp for that block on the desired network, but this is not as elegant a solution as it could be, and could cause mistakes that may not be easily spotted since the block timestamps will look similar except for the last N numbers.

**Do you have any solution you want to propose?**
Add a method `GetNetwork` to the native Ledger contract which returns the current network magic number.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Native contracts

**Comment by Liaojinghui** [comment]
Agree, I also think it is important to add an interface to get the VM version.

**Comment by erikzhang** [comment]
Different networks may have different native contracts, so I think it should be added as a syscall.
