### ISSUE TITLE
Publish information about invalid transactions on EventStream

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2538]
For debugging purposes in NeoExpress/Visual DevTracker it would be very useful to get information about *why* a transaction verification fails. TOday, when submitting a transaction via `sendrawtransaction` fails we only get that the transaction was `Invalid` without any additional information. More information about why the transaction is invalid makes it easier for the developer to diagnose the issue.

**Comment by shargon** [comment]
![image](https://user-images.githubusercontent.com/3167973/126061339-065105b3-2932-46aa-b040-0d9d4ced4491.png)

But do you have the reason, isn't it?

**Comment by devhawk** [comment]
"Invalid" isn't enough information to debug the problem. Transactions can be invalid for multiple reasons
