### ISSUE TITLE
Create a `neo-core` project that has no dependency

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2547]
**Summary or problem description**
It is weird that project `neo` depends on `neo-vm` and both contains a `crypto` lib which make the system structure layers unclear.

**Do you have any solution you want to propose?**
Move the parts in `neo` and `neo-vm` that do not depend on any other project into a new project `neo-core`.

![image](https://user-images.githubusercontent.com/10189511/126025663-02154502-3025-4403-aa4f-aeab82d46d8b.png)

**Neo Version**
- Neo 3

**Comment by Liaojinghui** [comment]
![image](https://user-images.githubusercontent.com/10189511/127451048-f835592c-9530-470d-a104-7284ebfe3f52.png)

**Comment by devhawk** [comment]
very similar to #1865

**Comment by Liaojinghui** [comment]
[Liaojinghui/neo-core](https://github.com/Liaojinghui/neo-core)

**Comment by devhawk** [comment]
Are we not considering this anymore?

**Comment by gsmachado** [comment]
> Are we not considering this anymore?

Are we not considering this anymore? [2]

**Comment by devhawk** [comment]
I don't think we need this issue and #1865, but AFAIK there's no traction on #1865 either.
