### ISSUE TITLE
For N3,from private key to address,which step is error?thx!

### ISSUE THREAD

**Issue by i359** [neo-project/neo#2556]
Step 01.The private key:1a7648bc484b3d9ed9e2226d223a6193d64e5e1fcacd97868adec665fe12b924
Step 02.Private key to WIF:Kx79detFdAHhsRHCnXoJv1cBNqgM45K1iEtcPugh9vH1bTB71AEC
Step 03.Private key to the public key:02d498644edf299f3cb8817c635e15baacd311501222885c434e48f37d62035d68
Step 04.Address script:0c2102d498644edf299f3cb8817c635e15baacd311501222885c434e48f37d62035d6841747476aa
Step 05.SHA256:cff26e8cad8eb4ae6d02a10d061f4144d349a95f4f833fcad7b2c6c5d7bcde53
Step 06.RIPEMD160:cac4c54fa0648de135bbaeeb6baf9b63ad5da553
Step 07.Add the version number:35cac4c54fa0648de135bbaeeb6baf9b63ad5da553
Step 08.SHA256:edaf052b948de5518cb961f62be4afeef600f06ec9c3fb772bb96137aa805fde
Step 09.SHA256:90f5ef9568107d5d043737477a0ab7c0b592ef100000c98558ae84b1ba0db6b7
Step 10.35+HX+checksum:35cac4c54fa0648de135bbaeeb6baf9b63ad5da55390f5ef95
Step 11.address:NeQ7QNouUxnidnat4YNr9j2ejmWKRig43E

but right address is NcNutvAqzexziRGXov6tgn96jtSaByEaBy for WIF:Kx79detFdAHhsRHCnXoJv1cBNqgM45K1iEtcPugh9vH1bTB71AEC,which step is error? thx!

**Comment by i359** [comment]
@erikzhang ，Thank you for your reply.

The script is OK:
1.Copy WIF:Kx79detFdAHhsRHCnXoJv1cBNqgM45K1iEtcPugh9vH1bTB71AEC to https://neo.org/converter/index,get the public key:02d498644edf299f3cb8817c635e15baacd311501222885c434e48f37d62035d68
2.The script is "0c21" +public key+ "41747476aa"=0c2102d498644edf299f3cb8817c635e15baacd311501222885c434e48f37d62035d6841747476aa


![account_address_script_checksign](https://user-images.githubusercontent.com/43022140/127839031-8d933767-7206-41a2-bb46-ce28afb2ca44.png)
![A](https://user-images.githubusercontent.com/43022140/127839080-3fd2a67e-36f4-429a-ad7b-48c64ccf2cd7.JPG)

**Comment by erikzhang** [comment]
`747476aa` is not the correct syscall hash.

It's not `Neo.Crypto.CheckSig` but `System.Crypto.CheckSig`.

**Comment by i359** [comment]
@erikzhang ，Thanks for your clarify.

if "Neo.Crypto.CheckSig".hash2int= 2859889780=0x747476aa
then "System.Crypto.CheckSig".hash2int=   ?     =    ?

**Comment by erikzhang** [comment]
666101590

**Comment by i359** [comment]
@erikzhang , it works, thanks!
