### ISSUE TITLE
Asset Id

### ISSUE THREAD

**Issue by thomsonimjd** [neo-project/neo#256]
I create an address in jsonrpc using getnewaddres method, the same way how can I get asset id for an address to send/check balance.

**Comment by igormcoelho** [comment]
Perhaps a little late, but it's important to write this down for future visitors...
NEO assetid : `c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b`
GAS assetid: `602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7`
Sometimes they appear reversed... please try to see if it works :)
