### ISSUE TITLE
Ledger.GetTransaction() can't get current transaction

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo#2568]
I used method `Ledger.GetTransaction()` in the smart contract, and I expect it to return **true** when **pre-execution**, and **false** when I **actually execution** it.

Contract code
```c#
public static bool t1()
{
    return Ledger.GetTransaction(((Transaction)Runtime.ScriptContainer).Hash) == null;
}
```

Invokefunction（**pre-execution**）
request
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "invokefunction",
    "params": [
        "0xd2448d18052d5732f7da35d5d31e6ef47e664508",
        "t1",
        [],
        [
            {
                "account": "0x4578060c29f4c03f1e16c84312429d991952c94c",
                "scopes": "CalledByEntry",
                "allowedcontracts": [],
                "allowedgroups": []
            }
        ]
    ]
}
```
response
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "wh8MAnQxDBQIRWZ+9G4e09U12vcyVy0FGI1E0kFifVtS",
        "state": "HALT",
        "gasconsumed": "4718760",
        "exception": null,
        "stack": [
            {
                "type": "Boolean",
                "value": true
            }
        ],
        "tx": "ANaI8RGoAEgAAAAAAPjrEQAAAAAAlhoAAAFMyVIZmZ1CEkPIFh4/wPQpDAZ4RQEAIcIfDAJ0MQwUCEVmfvRuHtPVNdr3MlctBRiNRNJBYn1bUgFCDEBB6QBbnLMUY/Vw4MDHdRClOeYy02quh/S3f7PNq5pOud8EkCWIVq+4w39RRbbr5wCpWGhc5IiG2eQRSHFANngqKAwhAnuOhIl9zf58vffm17ad227dYyPL5zLqaN0rPUSoDoDwQVbnsyc="
    }
}
```
Then I sent the transaction and got the transaction log: (**actually execution**)
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "txid": "0x5490875a4a161f457de2de8553af13b089fd36e8092b7fe199d85c13651f5ea0",
        "executions": [
            {
                "trigger": "Application",
                "vmstate": "HALT",
                "exception": null,
                "gasconsumed": "4718760",
                "stack": [
                    {
                        "type": "Boolean",
                        "value": true
                    }
                ],
                "notifications": []
            }
        ]
    }
}
```

So, Ledger.GetTransaction can't get current transaction?

**Comment by RichardBelsum** [comment]
I can get the transaction in the previous blocks, such as: 

```c#
public static bool t2(UInt256 tx)
{
    return Ledger.GetTransaction(tx) == null;
}
```

![image](https://user-images.githubusercontent.com/82148280/128992590-5f50c948-d65d-4b70-9932-ed2e44d6d7bb.png)

**Comment by roman-khimov** [comment]
> So, Ledger.GetTransaction can't get current transaction?

Yes. As well as any other transaction from the same block, they're not traceable.
https://github.com/neo-project/neo/blob/a4d2eddbee049bbe3d5d9552e11181d294af929e/src/neo/SmartContract/Native/LedgerContract.cs#L54-L59
Which actually allows for some interesting optimizations.

**Comment by RichardBelsum** [comment]
Thanks for @ZhangTao1596 for finding the cause of the bug.

First, the modification of the `Prefix_CurrentBlock` value is done in the `postPersist` phase.

![image](https://user-images.githubusercontent.com/6295602/128995102-76b0fa79-9198-4bc3-8b26-cff7ed85355a.png)

Then `CurrentIndex` actually gets the Index of the **previous block**
![image](https://user-images.githubusercontent.com/6295602/128994977-8878d83a-d767-4eba-bbab-04e522d00b43.png)

Then, `IsTraceableBlock` return false.
![image](https://user-images.githubusercontent.com/6295602/128994871-dc536c4c-1533-4ac6-8362-d6b0f7907bcf.png)

Then, `GetTransactionForContract` return null.
![image](https://user-images.githubusercontent.com/6295602/128994732-a8b26423-f1aa-4aba-bb9b-c14b776ec89b.png)

**Comment by Liaojinghui** [comment]
I think you can find the answer in your code, you were asking transactions from the `Ledger` while your transaction was not in the `Ledger`, it was still persisting.

**Comment by RichardBelsum** [comment]
So, it's by design, not bug?

**Comment by Liaojinghui** [comment]
> So, it's by design, not bug?

At least you can not get persisting transactions in a `Ledger`. The `Ledger` should only contain persisted transactions.

**Comment by shargon** [comment]
> I think you can find the answer in your code, you were asking your transaction from the Ledger while your transaction was not in the Ledger, it was still persisting.

Agree

**Comment by erikzhang** [comment]
```c#
Transaction current_tx = (Transaction)Runtime.ScriptContainer;
```

**Comment by RichardBelsum** [comment]
There may be some misunderstanding. I want to use GetTransaction() to determine whether the currently executing smart contract is a **pre-execution** or actually execution.

**Comment by RichardBelsum** [comment]
Because the paths of pre-execution and actual execution may not match [(1)](#1), and now I can't use Gas.Refuel. So I want to increase the pre-execution fee by determining whether the contract is pre-executed or not.

<p name="1">1:</p>
```c#
var index = Storage.Get(Storage.CurrentContainer,"index");

if(index % 2 == 0)
{
    //Some of the codes that consume GAS
}

Storage.Put(Storage.CurrentContainer,"index", index + 1);
```

**Comment by RichardBelsum** [comment]
Any updates? I think it's a bug, do you agree?

**Comment by Liaojinghui** [comment]
> Any updates? I think it's a bug, do you agree?

Why do you think it is a bug?

**Comment by RichardBelsum** [comment]
> > Any updates? I think it's a bug, do you agree?
> 
> Why do you think it is a bug?

As long as the transaction is on the chain, it should be traceable

**Comment by Qiao-Jin** [comment]
> Because the paths of pre-execution and actual execution may not match

The execution path of actual execution surely can be different from pre-execution and cannot be controlled, depending on balance, constrained condition within script logic, etc. I'm not clear what's its relationship to the feature you want.

**Comment by RichardBelsum** [comment]
I want to determine in the contract whether the code is being pre-executed, and if so, add some code to increase the fee to avoid the actual execution fee being insufficient @Qiao-Jin

**Comment by Liaojinghui** [comment]
- transactions in execution is not on the chain, on the chain means on the ledger 
- Qiao-Jin answers well.
- contract does not handle fees. 
- pre-execution could consume (not really consumes) more gas, it could also consume (not really consumes) less gas, we can not know.

**Comment by roman-khimov** [comment]
You can add some GAS to system fee when you're creating a transaction, contract itself shouldn't even try to do estimations of this kind. And it shouldn't differentiate between on-chain and test executions in general, otherwise what's use of test execution? It's not just about GAS, I'd also like to see exactly what happens when I do something with the contract, if the contract decides to change its behavior on-chain I'd say this contract is cheating me.

**Comment by RichardBelsum** [comment]
When you in pre-execution, you are always the first transaction, which is not the case when you actually execute. The person in front of you will modify the storage, causing you to have a different execution path and different fees.

I can write code to add systemfee, but normal users can only call the contract with a wallet(like NeoLine/O3), they don't support adding systemfee

**Comment by RichardBelsum** [comment]
I could write it that way before, but now I need a new way to replace Gas.Refuel.

```C#
Gas.Refuel((Transaction)Runtime.ScriptContainer).Sender, 1000000);

var index = Storage.Get(Storage.CurrentContainer,"index");
if(index % 2 == 0)
{
    //Some of the codes that consume GAS
}
Storage.Put(Storage.CurrentContainer,"index", index + 1);
```

**Comment by roman-khimov** [comment]
> When you in pre-execution, you are always the first transaction, which is not the case when you actually execute. The person in front of you will modify the storage, causing you to have a different execution path and different fees.

True, but
 * it's not often that it happens
 * in a system that we have it's solved by additional system fee that is being added by entity generating transaction

Think of it the other way around, if your contract always burns additional GAS (not needed for its logic) then users always pay this additional GAS for nothing. They might be upset by this too.

But there was a proposal to return unspent system fee to senders which could technically allow to always safely add some GAS (#1536), maybe that could be something to consider long-term. While for now we have what we have.

**Comment by RichardBelsum** [comment]
Assuming that pre-execution requires 2GAS and the actual execution has a 20% chance of requiring 2.01GAS, I would rather add 0.01 GAS to each transaction, otherwise I would lose 2GAS because the contract execution would fail due to sufficient fees.

**Comment by Liaojinghui** [comment]
> Assuming that pre-execution requires 2GAS and the actual execution has a 20% chance of requiring 2.01GAS, I would rather add 0.01 GAS to each transaction, otherwise I would lose 2GAS because the contract execution would fail due to sufficient fees.
> 
> The wallet(Neo-cli/Neo3-GUI/NeoLine/O3/Neon) used by the user can't add systemfee, so I can only add systemfee to the pre-execution of the contract.

Then you can open an issue for that. I agree with you that wallet should allow users to pay more gas.

**Comment by erikzhang** [comment]
Add a `maxExecFee` field for each method in ABI or manifest?

**Comment by RichardBelsum** [comment]
> Add a `maxExecFee` field for each method in ABI or manifest?

However, the committee can dynamically adjust the fee factor.

**Comment by roman-khimov** [comment]
> Add a `maxExecFee` field for each method in ABI or manifest?

I doubt it's viable. What is the max cost of GAS `transfer`?

**Comment by RichardBelsum** [comment]
> Add a `maxExecFee` field for each method in ABI or manifest?

Such a function, no maxExecFee too.

```c#
public static bool Airdrop(BigInteger amount)
{
    for (int i = 0; i < amount; i++)
    {
        ……
        Mint(tokenId, tokenState);
    }
    return true;
}
```

**Comment by roman-khimov** [comment]
NOBUG here.
