### ISSUE TITLE
Calling `StdLib.JsonSerialize` on a contract manifest returns error "Specified cast is not valid."

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo#2571]
**Describe the bug**

Calling `StdLib.JsonSerialize` on a contract manifest returns error "Specified cast is not valid."

**To Reproduce**

- Create, compile, deploy the following contract:
  ```c# 
    public class ExampleContract : SmartContract
    {

        public static object method()
        {
            Contract c = ContractManagement.GetContract(NEO.Hash);
            return StdLib.JsonDeserialize(c.Manifest);
        }
    }
  ```
- Run neo-express: `neoxp reset -f && neoxp run`
- Deploy the contract: `neoxp contract deploy bin/sc/ExampleContract.nef genesis`
- Invoke the method:
  - Create an invoke file: 
    ```json
    [
        {
            "contract": "ExampleContract",
            "operation": "method",
            "args": []
        }
    ]
    ```
  - Run `neoxp contract invoke invoke.json genesis`

**Expected behavior**
As mentioned in [this](https://github.com/neo-project/neo/pull/2240#issuecomment-762091427) PR's discussion, it should be easy to replace the contract name in a manifest with a new name by, e.g., using `StdLib.jsonSerialze`. 

**Platform:**
 - OS: MacOS 11.4
 - Version nccs 3.0.2, neoxp 3.0.5

**Comment by irshadnilam** [comment]
To add to this, 
without having an ability to change the manifest name, it is difficult to create a factory contract in NEO.

**Comment by roman-khimov** [comment]
`c.Manifest` is not a string since #2254, that's why it fails. At the same time if we're talking about factories why do need to take manifest from `GetContract`, why factory doesn't have it stored internally?

**Comment by csmuller** [comment]
Great, thanks @roman-khimov. We missed that change.
@shargon, The dotnet devpack needs this update as well, AFAIK.
