### ISSUE TITLE
Add CopyRight and LICENSE declaration to each file of the source code

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2574]
**Summary or problem description**
As one of the most successful Blockchain projects. The neo is open-sourced under the MIT license, it has a LICENSE file in the main directory. However, neo projects lack the copyright and license notice in the source code files, which is actually very important for an open-source project.

**Do you have any solution you want to propose?**
Drafts

```C#
/*
 * Copyright (C) 2014-2021 NEO GLOBAL DEVELOPMENT.
 * Author: xxxxxx <xxxx@neo.org>
 * 
 * Distributed under the MIT software license, see the accompanying
 * file LICENSE in the main directory or http://www.opensource.org/licenses/mit-license.php 
 * for more details.
 * 
 * Redistribution and use in source and binary forms with or without
 * modifications are permitted.
 */
```

```C#
/*
 * Copyright (C) 2014-2021 Neo Core Developers.
 * Author: xxxxxx <xxxx@neo.org>
 * 
 * Distributed under the MIT software license, see the accompanying
 * file LICENSE in the main directory or http://www.opensource.org/licenses/mit-license.php 
 * for more details.
 * 
 * Redistribution and use in source and binary forms with or without
 * modifications are permitted.
 */
```

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- Consensus
- CLI
- Plugins
- Ledger
- Network Policy
- P2P (TCP)
- RPC (HTTP)
- SDK
- VM
- Other:

**Comment by erikzhang** [comment]
```
 * Copyright (C) 2014-2021 Neo Core Developers.
```
Do we have to update all the source files every year?

**Comment by Liaojinghui** [comment]
@erikzhang No, you don't have to update it every year. This is used to declare to others who use this file (who don't use the whole project) that he can use this code for free, but if any problem happens, it has nothing to do with neo.

**Comment by erikzhang** [comment]
PR?
