### ISSUE TITLE
Smart advertising

### ISSUE THREAD

**Issue by bebrahimi891** [neo-project/neo#2584]
[Smart Advertising File.pdf](https://github.com/neo-project/neo/files/7025158/Smart.Advertising.File.pdf)

Hi, I am Bashir Ebrahimi from Iran. I came up with an idea for blockchain and smart contracts, this idea can be very effective and can be easily implemented for many jobs in the world and anywhere in the world. I have studied and experienced blockchains and cryptocurrencies for years to come up with this idea, now this idea is my dream and can even increase the value of your company. In return for implementing this important idea and project, I want to partner with each other and enjoy the benefits of a partnership with a lifetime contract, because implementing this project will always be profitable and efficient. And that for each stadium or team in which the advertisement is done, a token or a special Cryptocurrency is produced and paid to the companies that provide the advertisement by proving the shares, and thus the income, quality and number of advertisements. Increases and also the desired currency becomes valuable. With the implementation of this project, billboards will no longer be limited to one ad, and each billboard can be assigned to one ad from one company, thus giving more ads to the places where the ads are displayed, as well as increasing their income and thus fame. And the speed of introducing companies increases and their income also increases. This idea is very valuable and can save even sports clubs from bankruptcy in this situation of coronavirus and other cases and increase their income and even boost many businesses and companies and other businesses.
I wanted to name this idea smart advertising, because smart advertising not only on digital billboards in stadiums and other places, but everywhere and everywhere in the world, including social networks. And media will also be playable and executable. Smart advertising can be both revenue-generating. These ideas or advertisements can be in the form of a token or a special currency to be traded with.

By implementing this idea, it is possible to expand advertisements everywhere and everywhere, except for digital billboards on sites and everywhere, automatically and online, and this will help to generate more revenue and introduce advertisers, as well as to all displays. Advertisers also generate high revenue, which means increasing the value of blockchain and the value of businesses and their revenue and unlimited economies around the world.
And that for each stadium or team in which the advertisement is done, a token or a special Cryptocurrency is produced and paid to the companies that provide the advertisement by proving the shares, and thus the income, quality and number of advertisements. Increases and also the desired currency becomes valuable. With the implementation of this project, billboards will no longer be limited to one ad, and each billboard can be assigned to one ad from one company, thus giving more ads to the places where the ads are displayed, as well as increasing their income and thus fame. And the speed of introducing companies increases and their income also increases.

Smart advertising based on the black chain platform 
Today, we know that advertising plays an important role in the revenue of  
large companies as well as sports clubs and stadiums, and given the  
increasing spread of digital currencies. We want to use these two large  
and lucrative components of today's world together. In Black chain and  
digital currencies, there is something called a smart contract, which will  
be done instantly, without intermediaries and at no extra cost, by paying  
for digital currencies. But the main idea is that if we can turn the  
advertising contracts of the billboards of stadiums and sports halls into  
smart contracts, we can get more and better advertising with higher  
income rate and quality and up-to-date for stadiums, sports clubs and even  
other organs. And make media in which advertising is done and replace  
smart contracts with traditional and old version contracts and eliminate  
hassles and intermediary ones. This idea can increase the prosperity of the  
cryptocurrency market and also contribute to the prosperity and quality of  
advertising and revenue of the world's largest companies. In smart  
contracts, on the same day that the sports game is to be played, companies  
can send their advertisements via these smart contracts in the day of the  
sports games and allocate these advertisements to the same stadium, and  
the advertisements which are displayed systematically in the stadium  
billboards, will be based on quality, time and cost. 
Smart advertising based on the black chain platform 
Regarding and following the previous text and message that was discussed before  
that smart contracts are executed in the block chain, here I am going to describe  
some points of the contract. Smart contracts can be executed online, instantly and  
anywhere in the world, without spending time and moving from one place to another  
to close a contract. In these contracts, the provisions are quite clear, understandable  
and visible, and the customer can register and execute these contracts instantly and  
instantly anywhere in the world with full knowledge of its provisions, including the text of the contract, how to execute the contract, cost and income, and other  
provisions without spending time and place transition and even exorbitant costs. As  
we mentioned in the previous text, we want to integrate the two major components  
of today's business world, advertising and block chain, using smart contracts. In this  
way that we have to create an intermediary as a site on a block chain platform, in  
which by defining smart contracts and paying digital currencies, everything that can  
be advertised online, such as billboards of stadiums and halls in sports competitions  
all over the world, media subtitles and everything that needs to be advertised around  
the world on this site. In this site, a program or report of live sports competitions or  
any place where online advertising is done, will be placed on the site, and companies  
and everything that needs advertising in the world, can be spent without time and  
movement by seeing the complete program of online advertising. Place and by  
simultaneously selecting several sports competitions or channels or media or  
whatever is displayed in the ads, the ads are presented where they want and the ads  
are systematically and automatically by signing a smart contract related to where his  
ads will be displayed where he wants to be paid for with digital currencies, the type  
of payment and cost of which are also intelligently defined in the contract. This plan  
has many advantages, including: requesting advertising simultaneously to several  
parts of the world, faster and instant introduction of advertising products and  
everything that needs advertising. This plan gives more ads to the places where the 
ads are done, because with the implementation of smart contracts, the demand for  
ads increases immediately because what is needed to be advertised, is no longer  
needed months, days or weeks ago to advertise from one place to another and to  
conclusion their advertising contract or spending extra time and money will increase  
their revenue. This site can be used as an advertising exchange on the Black chain  
platform. These contracts should be defined and designed in such a way that  
advertisements based on cost, time and quality and the number of times the  
advertisements are repeated are displayed automatically and systematically at the  
place where the advertisement takes place. Type of plan: Advertising on the Black 
chain platform.  
Applications: Advertising around the world, instantly and simultaneously in  
different places, introducing more companies and their products and everything that  
needs advertising. More advertising and more revenue will go to the places where  
the advertising takes place. Reduce costs and time and relocation for those who want  
to advertise, and many other uses that will be more tangible and understandable later on, as they are advertised simultaneously in places that have millions of viewers.  
Because in many places today, such as stadiums, gyms, and sports teams, their  
revenue comes from advertising. This plan can help them earn more and more money  
quickly, and this site or platform that we want to design and provide these two  
components, connects the big and lucrative business world. 

https://t.me/Bebrahimi891
https://twitter.com/ebrahimibashir3?s=09
My gmail : bebrahimi891@gmail.com

Sincerely 
Bashir Ebrahimi 
The owner of the above mentioned idea about smart advertising
**Summary or problem description**
A summary of the problem you want to solve or metric you want to improve

**Do you have any solution you want to propose?**
A clear and concise description of what you expect with this change.

**Neo Version**
- Neo 2
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- Consensus
- CLI
- Plugins
- Ledger
- Network Policy
- P2P (TCP)
- RPC (HTTP)
- SDK
- VM
- Other:

**Comment by Liaojinghui** [comment]
No offend, do you mind making it shorter? or explain your idea in a few words?

**Comment by bebrahimi891** [comment]
> No offend, do you mind making it shorter? or explain your idea in a few words?

Okay, Should I open a new issue?

**Comment by bebrahimi891** [comment]
> No offend, do you mind making it shorter? or explain your idea in a few words?

The contents of the PDF are summarized and complete and the main topic, which I resent in the form of a new issue.

**Comment by diskooooo** [comment]
Not a good idea to open PDF's by random people.
