### ISSUE TITLE
Is the 'verify' method not being called anymore?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2587]
Hi. 

I don't know if this has changed, if it is a bug, or if it was always like that:
But when if I try to withdraw funds from a smart-contract, shouldn't it call the 'verify' method? Is this working properly? My colleague is unable to make it work.
The tests are being done using neo-express, but I believe this is not the reason why it doesn't work. 

Thanks

**Comment by erikzhang** [comment]
A contract can transfer assets owned by itself to others without the need to execute the `verify` method.

**Comment by lock9** [comment]
Sorry, I didn't make it clear: 
I sent funds (NEO/GAS) to a contract. I want to withdraw it. It was supposed to call the verify method for that, right?

**Comment by erikzhang** [comment]
No. You sent funds to a contract, then they belong to this contract. When it sends them back to you, it doesn't need to call `verify`.

**Comment by lock9** [comment]
Could you clarify when the verify method is called? 
How does the Neo know if I can withdraw funds on behalf of 'my_contract'?

**Comment by erikzhang** [comment]
> send neo my_contract my_wallet amount

In this case, you need to call `verify`.

If it's the case that you call the `refund` method of the contract, and then the contract calls `transfer` method of the neo contract, than the `verify` method does not need to be called.

**Comment by lock9** [comment]
> > send neo my_contract my_wallet amount
> 
> In this case, you need to call `verify`.

What do you mean by this? Do I need to manually invoke the verify method? Sorry if the questions are stupid, I'm confused.

What I expected was:
If I do `send neo 'my_contract' 'my_wallet' 'amount`, I was expecting that the Neo contract would invoke the `verify` method on `my_contract`. Is this correct?

**Comment by erikzhang** [comment]
> Is this correct?

Yes.

**Comment by lock9** [comment]
Ok. So, maybe there is a bug. I'll do some testing on the testnet to see if the problem is there. I'll leave this open while I investigate.

**Comment by lock9** [comment]
I'll close this. If it happens to be a bug, I'll open another issue. Thanks.

**Comment by roman-khimov** [comment]
> > > send neo my_contract my_wallet amount
> > 
> > 
> > In this case, you need to call `verify`.
> 
> What do you mean by this? Do I need to manually invoke the verify method? Sorry if the questions are stupid, I'm confused.

You need to attach a witness for a contract, that is you add an additional signer to your transaction that has contract's hash (and appropriate scope) and then for this signer you add a witness with zero-length verification script (this is where `verify` will actually be called automatically by the system) and whatever your contracts needs (or not) in invocation script.

**Comment by lock9** [comment]
Just tested it using neo-cli and the testnet, and everything is working as expected. Something broke elsewhere. Thanks.
