### ISSUE TITLE
How do I know how many assets are being transfered during the 'verify' callback?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2588]
Hi,

The ´verify´ method doesn't use any parameters. What is the best / recommended way that I can securely obtain the amount that the user is trying to transfer from a contract? In other words, how can I get the parameters of the ´transfer´ invocation that triggered the ´verify´ method on my smart-contract?

Thanks

**Comment by roman-khimov** [comment]
> The ´verify´ method doesn't use any parameters

It can have parameters if you need, nothing forbids/prevents that.

> What is the best / recommended way that I can securely obtain the amount that the user is trying to transfer from a contract?

The problem though is that your `verify` parameters and `transfer` parameters are completely different unrelated things, so you can only get `transfer` parameters if you're to very carefully parse `tx.Script` in `verify`. Related: #2577.

**Comment by lock9** [comment]
Thanks @roman-khimov .
I guess that the best path is to have a custom 'withdraw' method on the smart-contract.
