### ISSUE TITLE
Add `Require` function call to smart contract

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2600]
**Summary or problem description**
In a lot of cases, we need to check the validity of the parameters and values, if they fail the check, we will set the transaction to `FAULT` directly, this involves tons of `if` statements and `throw new exception` statements. It annoys to write the same logic and same code again and again. If we could add a function call `Require` to replace `if(fail) throw new exception`, things would be much easier and more elegant for contract developers. 

**Do you have any solution you want to propose?**
Add a `Require` function call:

```C#
        /// <summary>
        /// If the condition `istrue` does not hold,
        /// then the transaction throw exception
        /// making transaction `FAULT`
        /// </summary>
        /// <param name="isTrue">true condition, has to be true to run</param>
        /// <param name="msg">Transaction FAULT reason</param>
        internal static void Require(bool isTrue, string msg = "Invalid") { if (!isTrue) throw new Exception(msg); }
```

Sample:
```C#
     private static void OwnerOnly() => Require(Verify(), "Authorization failed.");
```

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- SDK

**Comment by erikzhang** [comment]
```
private static void OwnerOnly() => if (!Verify()) throw new Exception("Authorization failed.");
```

**Comment by erikzhang** [comment]
If you want to FAULT the execution, you can use `ExecutionEngine.Assert()`.

```c#
private static void OwnerOnly() => ExecutionEngine.Assert(Verify());
```

**Comment by Liaojinghui** [comment]
> ```cs
>  ExecutionEngine.Assert
> ```

I also want the error message.~

**Comment by erikzhang** [comment]
> I also want the error message.~

We can't pass a message to `Assert`.

**Comment by Liaojinghui** [comment]
> We can't pass a message to `Assert`.
then can we have a `require` here? i think require would be more useful.

**Comment by shargon** [comment]
My vote is for add message to `Assert`

**Comment by Liaojinghui** [comment]
> My vote is for add message to `Assert`

I am fine with either, just need the error message.

**Comment by shargon** [comment]
Closed by https://github.com/neo-project/neo-devpack-dotnet/pull/692
