### ISSUE TITLE
Tag V2.5.0 not compile in linux

### ISSUE THREAD

**Issue by djaramillo021** [neo-project/neo#261]
/usr/share/dotnet/sdk/2.1.300/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/XXXXX/neo.csproj]

**Comment by jsolman** [comment]
You should be building for netcoreapp2.0 or netstandard2.0 if you are building for Linux. It's easy enough to change the csproj files for that. Is this issue to add logic to csproj files so that modifications aren't necessary for building on Linux?
