### ISSUE TITLE
Compressed ECPoint might severely reduce offline sync speed

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#2614]
**Summary or problem description**

Below is the dotTrace performance result when running a single node synchronizing offline. It can be observed that in such circumstances time is mostly spent upon deserializing compressed ECPoints during block persisting. This actually severely reduces offline node sync speed.

![image](https://user-images.githubusercontent.com/43407364/137889244-8c30bc23-fe3e-4010-be52-379f7d8ce10a.png)

And a comparison between compressed & umcompressed data of the same point, when decoded by func DecodePoint for 100000 times:

Type | Time
-- | --
Compressed | 10.3s
Umcompressed | 0.304s

Tremendous difference between 2 situations is noticeable.

**Do you have any solution you want to propose?**

Use  **uncompressed** data of ECPoints instead.

**Neo Version**
- Neo 3

**Comment by shargon** [comment]
Take a look to https://github.com/neo-project/neo/issues/1321
