### ISSUE TITLE
Storage.Delete should return true or false

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#2618]
**Summary or problem description**
`Storage.Delete` should return `true` or `false`, sometimes the smart contract need to check if a key exists for validation, and after it, you will delete it, if we return the delete result, we can avoid some storage searches.

**Do you have any solution you want to propose?**
Return true or false in  Storage.Delete`.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- Core

**Comment by devhawk** [comment]
Changing the name of the method is a breaking change. Adding a return value to an existing void return method seems reasonable

**Comment by erikzhang** [comment]
Won't it break the old contracts?

**Comment by shargon** [comment]
> Won't it break the old contracts?

We will need versioning in the furute, we can avoid it with a new method, but we will need it

**Comment by roman-khimov** [comment]
But how is it more efficient? LevelDB or BoltDB do not return this status from their delete functions (only error if any), so to get this additional data we'd have to check for existence in `Storage.Delete` implementation anyway, but that's what contract can do already by itself if it needs to (and paying appropriate GAS cost along the way). Am I missing something?

**Comment by shargon** [comment]
I think that you are right @roman-khimov except if is stored already in the cache, so I will close it
