### ISSUE TITLE
BigDecimal(decimal) constructor not working as expected

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2640]
Shouldn't a and b below be the same

``` csharp
BigDecimal a = new(5.5M);
BigDecimal b = new(5.5M, 1);
var same = a.Value == b.Value; // false
```

**Comment by Liaojinghui** [comment]
> 

Does neo support any type of decimal?

**Comment by Liaojinghui** [comment]
Does neo even support any type of decimals?

**Comment by shargon** [comment]
No, is not the same, without argument, it take the decimals from the value, with argument (1), it take the decimals from the argument, so it's not the same I think.

```
BigDecimal a = new(5.5M);
BigDecimal b = new(55M, 1);
var same = a.Value == b.Value; // must be true
```

**Comment by devhawk** [comment]
@shargon, I just copied and pasted your code into one of the UT_BigDecimal tests and same was false

**Comment by Liaojinghui** [comment]
```C#
BigDecimal a = new(55M, 1); // .Value 550
BigDecimal c = new BigDecimal(5.5M,1 ); // .Value 55
BigDecimal b = new BigDecimal(5.5M); // .Value 5
```
