### ISSUE TITLE
Is it possible to replace a transaction on the memory pool only increasing the network fee?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2643]
Hi,

Is it possible to replace a transaction that I had sent previously, with another one, with a higher fee? 

Use case: I've sent a transaction, but due to changes in the 'prices', I want my transaction to be the first in the block. Is it possible to replace an existing transaction with another one with a higher network fee?

Thanks.

**Comment by shargon** [comment]
No, it's not possible 

https://github.com/neo-project/neo/issues/1502

**Comment by roman-khimov** [comment]
"Conflicts" extension can make it possible, #1991.

**Comment by roman-khimov** [comment]
"Conflicts" is a part of the protocol now, so I consider this issue to be solved.
