### ISSUE TITLE
Add ` bool Reset();` method to `iterator` interface

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2644]
**Summary or problem description**
Looks like `iterator` misses the `reset` method while the official `IEnumerator` contains 

```C#
    bool MoveNext();
    void Reset();
```

And we might need it here #2637 

**Do you have any solution you want to propose?**
Add a new method to `iterator` to reset the iterator position.

```C#
void Reset();
```

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Neo Core

**Comment by shargon** [comment]
It will need to do the same query

**Comment by Liaojinghui** [comment]
> It will need to do the same query

```C#
        public void Reset()=>  enumerator.Reset();
```
