### ISSUE TITLE
ContractManagement.Deploy results in Wrong Magic

### ISSUE THREAD

**Issue by SkyKarma** [neo-project/neo#2651]
Trying to call ContractManagement.Deploy from inside my contract, which results in a "Error: Wrong magic"

The NEF file is approx 3.5KB before base64 encoding it,
I have saved the NEF file as a base64 encoded string inside my contract, and i build up the manifest from inside my contract,

What am i missing ?

![image](https://user-images.githubusercontent.com/90191292/149755526-39d1a923-919b-425d-9915-a6ceaafdc198.png)

**Comment by SkyKarma** [comment]
I can deploy from within the neo-cli, but i can not deploy from within my contract

![image](https://user-images.githubusercontent.com/90191292/149756125-72176d2d-f2cd-438a-8c83-b5d58ee320e2.png)

**Comment by SkyKarma** [comment]
Have also tried to upload it using Neon-js like such

![image](https://user-images.githubusercontent.com/90191292/149788135-039b5816-c870-4aa3-b3fc-7ff7de5f24c4.png)

But when trying to deploy it now, the error seems to be "ip not found....."
![image](https://user-images.githubusercontent.com/90191292/149788297-f5ab37dd-62ad-4b94-856a-6f802a3eaa95.png)

**Comment by shargon** [comment]
Seems a base64 or truncate error, did you checked the content?

**Comment by SkyKarma** [comment]
I was able to get back the exact same data which i passed in to the contract, but if its exactly identical to the NEP file which i encoded, i am not sure, i did not try to convert it back to a NEF file and open it...

**Comment by SkyKarma** [comment]
I just tried deploy a new contract, which i wanted to use the NEF file from,
![image](https://user-images.githubusercontent.com/90191292/149795082-c82854c0-735b-404d-af45-238e754e91d4.png)

and in my other contract call it like such:

![image](https://user-images.githubusercontent.com/90191292/149795389-b5539d9e-ad5e-454f-9c92-504799735783.png)

But when i call it through the neo-cli this is what shows up,

![image](https://user-images.githubusercontent.com/90191292/149795485-a8596d78-069b-4735-9051-0fa2a491a363.png)

ip not found with strict mode...

**Comment by kokahunter** [comment]
There are probably many ways to implement a contract factory. I found rentfuse's implementation very neat. Hope it helps: https://github.com/rentfuse-labs/rentfuse-contracts-neo/blob/main/contracts/ProxyNftFactory/src/ProxyNftFactoryContract.cs#L85-L93
