### ISSUE TITLE
oracle service vulnerability: local infomation leak

### ISSUE THREAD

**Issue by vang1ong7ang** [neo-project/neo#2662]
the following way of avoiding local access is not enough:

https://github.com/neo-project/neo-modules/blob/32aacc468ad43600817daabbec834e715017d962/src/OracleService/Protocols/OracleHttpsProtocol.cs#L41-L46

```C#
           if (!Settings.Default.AllowPrivateHost)
            {
                IPHostEntry entry = await Dns.GetHostEntryAsync(uri.Host);
                if (entry.IsInternal())
                    return (OracleResponseCode.Forbidden, null);
            }
```

since a remote server is able to return a redirect response whose target is <https://local-address/x>.

**Comment by vang1ong7ang** [comment]
possible response:

```
HTTP/1.1 302 Found
Server Cowboy
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Location: https://127.0.0.1:8888/
Content-Length: 45
<a href=" ">Found</a >.

```

**Comment by shargon** [comment]
Yes, you are right, I will try to find if it's possible to fix it without removing the forwarding. Give me some hours

**Comment by shargon** [comment]
I can't transfer the issue to neo-modules, could you create a new one in the right repository @vang1ong7ang ?

**Comment by vang1ong7ang** [comment]
@shargon sure
