### ISSUE TITLE
Set maximum number of system calls to prevent Resource Metering Attacks

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2672]
**Summary or problem description**

Appearently we still have some issues in the system that could be leveraged to DOS the network. And it is hard to locate and address all of them for now.

**Do you have any solution you want to propose?**
Set a limitation to the maximum numbers of call allowed for each system call or any function for each `transaction`.

For example, each transaction can call 'balanceof' at most 10 times.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Consensus
- VM

**Comment by roman-khimov** [comment]
Every system call costs something, so I don't think it's a problem in general, more calls -> more GAS cost -> MaxBlockSystemFee limit and attacker will run out of GAS quickly. You also don't know how many calls will be made in general, contracts call each other, they have some logic, they can be updated, this limit will just break some useful cases.

**Comment by Liaojinghui** [comment]
> Every system call costs something, so I don't think it's a problem in general, more calls -> more GAS cost -> MaxBlockSystemFee limit and attacker will run out of GAS quickly. You also don't know how many calls will be made in general, contracts call each other, they have some logic, they can be updated, this limit will just break some useful cases.

I totally agree, we should not set any limit to the system calls if there is no problem, unfortunately, it is not the case. We need time to do a thourough research on the system, before that, we should be able to prevent new DOS attacks as much as we can.
