### ISSUE TITLE
Version Control on Transacitons

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2675]
**Summary or problem description**
Since neo N3 support smart contract update, I think it is necessary for users to know which contract version are they calling. 

**Do you have any solution you want to propose?**
And user should be able to set the Transaciton be valid only to specific version.

something like `assert(version ==3)`

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- SDK

**Comment by roman-khimov** [comment]
We call contracts either via `System.Contract.Call` or `CALLT`. It's pretty trivial to add `System.Contract.CallWithVersion` as an alternative for people that want/need it, but I'm not so sure about `CALLT`, token specification is a part of NEF.

**Comment by dusmart** [comment]
There is some GAS-expensive way for this purpose now.
```
ExecutionEngine.Assert(ContractManagement.GetContract(Hash).UpdateCounter == 3, "invalid version");
```
