### ISSUE TITLE
Exception during P2P payload decompress

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo#2681]
**Describe the bug**
During decoding message with a compressed payload an exception is thrown if it is less than 4 bytes.

It should be checked in neo-go, please close the issue if this is an expected behaviour here (may be there is some outer try/catch)/

**(Optional) Additional context**
Issue in neo-go https://github.com/nspcc-dev/neo-go/pull/2409

**Comment by erikzhang** [comment]
A compressed payload cannot be less than 4 bytes, because the first 4 bytes are the number of bytes of the original data.

**Comment by fyrchik** [comment]
> A compressed payload cannot be less than 4 bytes

A _valid_ compressed payload cannot, surely. But network packets come from an untrusted source, so we may receive invalid one.

**Comment by Liaojinghui** [comment]
`BinaryPrimitives.ReadInt32LittleEndian` will throw exception if the payload is less than 4 bytes:

```
        // Exceptions:
        //   T:System.ArgumentOutOfRangeException:
        //     source is too small to contain an System.Int32.
        public static int ReadInt32LittleEndian(ReadOnlySpan<byte> source);
```
I don't think we need to take any special care about this exception.

**Comment by Liaojinghui** [comment]
just checked message decompress operations, exceptions are catched.

**Comment by fyrchik** [comment]
@Liaojinghui thank you! Closing the issue then.
