### ISSUE TITLE
GetCandidates is prone to Denial of Service

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#2683]
If there are 1024 or more candidates registered and the smart contract call `GetCandidates` a denial of service will occur.

https://github.com/neo-project/neo/blob/2a64c1cc809d1ff4b3a573c7c22bffbbf69a738b/src/neo/SmartContract/Native/NeoToken.cs#L340

**Comment by Liaojinghui** [comment]
A lot of issues are caused by this `ToArray()`, is that possible to add a maximum size limit to it?

**Comment by shargon** [comment]
We should limit the return to the first X candidates

**Comment by ixje** [comment]
> We should limit the return to the first X candidates

Isn't the point of this method that you can get ALL candidates. Perhaps we need a `GetCandidatesCount()` and add a `start_position` and `count` (with an upper limit) to `GetCandidates`. 

Alternatively, change the way registration works so you can limit the max stored candidates. E.g. You can register as candidate, you then have `t` time to collect sufficient votes to get in the top `1024` (assuming the top is filled). If you fail to make the top, your registration will be removed.

**Comment by Liaojinghui** [comment]
If we can limit the maximum size of toarray(), then or problems caused with toarray will be solved and prevented. If we just do `find one solve one`, it might be endless.

**Comment by roman-khimov** [comment]
> Perhaps we need a GetCandidatesCount() and add a start_position and count (with an upper limit) to GetCandidates.

`System.Iterator.Next`? If we're changing this API of course which is a bit weird with mainnet running.

**Comment by ixje** [comment]
I guess it comes down to being able to update native contracts to begin with.

**Comment by devhawk** [comment]
> > Perhaps we need a GetCandidatesCount() and add a start_position and count (with an upper limit) to GetCandidates.
> 
> `System.Iterator.Next`? If we're changing this API of course which is a bit weird with mainnet running.

Updating GetCandidates to return an iterator would not solve the problem entirely. RpcServer only returns the first `RpcServerSettings.MaxIteratorResultItems` values from the iterator and provides no mechanism for the caller to specify how many results to return or to skip. Using an iterator would effectively limit the caller to getting the first 'MaxIteratorResultItems` which defaults to 100.

More info in https://github.com/neo-project/neo-modules/issues/629 and https://github.com/neo-project/neo-devpack-dotnet/issues/647

**Comment by shargon** [comment]
I made a possible solution for it, please check it https://github.com/neo-project/neo/pull/2686

**Comment by erikzhang** [comment]
I think returning an iterator is the best solution.

**Comment by devhawk** [comment]
> I think returning an iterator is the best solution.

Agree 100%, as long as we provide a mechanism for RpcClient to iterator to access the full iterated collection, not just first `MaxIteratorResultItems`

**Comment by shargon** [comment]
> I think returning an iterator is the best solution.

New syscall?

**Comment by shargon** [comment]
> I think returning an iterator is the best solution.

New syscall?

**Comment by devhawk** [comment]
> `MaxIteratorResultItems` is configurable. And we can solve the RPC issue in the future.

Not by the caller

**Comment by shargon** [comment]
> I think returning an iterator is the best solution.

For the new syscall is ok, but for the previous one, just limit?

**Comment by erikzhang** [comment]
> but for the previous one, just limit?

Both are fine for me, limit it, or wait until it exceeds 2048 items to automatically throw an exception.
