### ISSUE TITLE
How to convert address to Hash160

### ISSUE THREAD

**Issue by penuel-leo** [neo-project/neo#269]
Hi, I use the invoke function method to debug, according to the document [http://docs.neo.org/en-us/exchange/v2.7.3.html](http://docs.neo.org/en-us/exchange/v2.7.3.html). 
The documentation point out that the parameters need to convert the address to the Hash160 type. How do you convert each other in java? (and How do you convert ByteArray types and String each other?)

**Comment by penuel-leo** [comment]
who can help me?😭

**Comment by shargon** [comment]
I java i don't know, but in c# you can take this example, maybe is the same

https://github.com/phantasma-io/PhantasmaNeo/blob/c47d42a719e8ad7eac010f2210afad3826816a70/PhantasmaContract/Contract.cs#L721

**Comment by Cobb-Chang** [comment]
> who can help me?😭

1. base58decode(address) eg: base58decode(AJgypEEMZUXiHSj6qMMHPEFeu5fUcQm7QM) -> 171ffb723601fe7bf5e78b9ec6f6c79d69e317b9c71f124c12
2. slice the result: 1ffb723601fe7bf5e78b9ec6f6c79d69e317b9c7
3. reversed the code by one bytes: c7b917e3699dc7f6c69e8be7f57bfe013672fb1f
get hash160
