### ISSUE TITLE
`GetTransactionSigners` method of native Ledger should check for transaction traceability

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo#2698]
**Describe the bug**
`GetTransactionSigners` method of native Ledger contract introduced by #2685 doesn't check whether transaction is traceable.

**To Reproduce**
See the method implementation:
https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/SmartContract/Native/LedgerContract.cs#L245-L249

**Expected behavior**
`GetTransactionSigners` should check whether the transaction is traceable, like any other transaction-related method:
https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/SmartContract/Native/LedgerContract.cs#L263

**Platform:**
 - Version: neo 3.2.1

**Comment by shargon** [comment]
Closed by https://github.com/neo-project/neo/pull/2703
