### ISSUE TITLE
Missing docs/code for creating multisig transaction

### ISSUE THREAD

**Issue by arkoc** [neo-project/neo#270]
There is no documented way of programmatically creating multisig transaction. Also I didn't found any code that creates multisig transaction.

Is there any code or documentation that is describing process of creating multisig transaction ?

**Comment by igormcoelho** [comment]
It's not a complete reference, but you can use:
https://medium.com/neoresearch/understanding-multisig-on-neo-df9c9c1403b1
https://neoresearch.io/smacco/

**Comment by vncoelho** [comment]
@arkoc, we also created some script for javascript.
Recently, neon-js has been updated and a guideline has been created there: https://github.com/CityOfZion/neon-js/blob/c16d635f2b8f8034148c56d5a3118419df528ca4/docs/guides/basic/multi.md
