### ISSUE TITLE
Add MAX_SIZE to CompoundType

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2702]
**Summary or problem description**
Currently we only count the number of items allowed in the CompoundType, this allows `security researchers` to construct `stackitem` that can explode in size during execution from a few kilobytes to one gigabytes, and causes DOS attack. For example, https://github.com/neo-project/neo/issues/2663 https://github.com/neo-project/neo/issues/2528 .

**Do you have any solution you want to propose?**
Set a maximum size for CompoundType.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- VM

**Comment by shargon** [comment]
We already have a 2048 items limit, I think that reduce compound to, for example, 512, won't make any difference because you could have one inside the other

**Comment by Liaojinghui** [comment]
Count wont stop you from having 2048 references that all refer to the same 2MB object.
