### ISSUE TITLE
Can't perform full sync from offline file

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#2704]
**Describe the bug**
Using this offline file provided by NGD https://packet.azureedge.net/neochain/n3mainnet/full/0-1439200/80831B7841445D6C954C24F09D22F59A/chain.0.acc.zip (over at https://sync.ngd.network) and `neo-cli 3.2.1`, syncing hangs indefinitely, then when restarting under a debugger I get this error
![image](https://user-images.githubusercontent.com/6625537/165097982-8b5e1497-ee8e-4934-b5f5-a4ad18a55067.png)

`block.Index` seems to say `1369191` whereas `currentHeight` is at `1349186`. Somehow they're out of sync.

I tried 2 times now from scratch. Anyone else that _can_ sync the whole file?

**Expected behavior**
I expect syncing to complete up to height `1439200`  (as is the max block count in that offline chain according to the website)

**Platform:**
 - OS: Ubuntu 20.04
 - Version neo-cli 3.2.1

**Comment by cloud8little** [comment]
@ixje  the office sync package is for the old testnet, and since 3.2.1 has changed its seed node to testnet #2 (which is seed1t5~seed5t5.neo.org vs. the previous testnet seed node seed1t4.neo.org~seed5t4.neo.org); they are different chain now.

**Comment by ixje** [comment]
@cloud8little I'm trying to syncing mainnet not testnet. Afaik mainnet should not be affected, right?

**Comment by ixje** [comment]
Oddly enough syncing straight from the network does work.

**Comment by ixje** [comment]
thanks works. The testnet chain however seems to be broken as well.
