### ISSUE TITLE
Is the conversion of transaction signer to stackitem implemented as intended?

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo#2705]
### Problem description

#2685 introduces new `GetTransactionSigners` method to native Ledger. Take a look at the way how each signer is converted to stackitem: the first array item is the serialized binary representation of the Signer itself:
https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/Network/P2P/Payloads/Signer.cs#L187-L191

The binary representation is followed by a set of Signer's fields serialized to stackitem separately:
https://github.com/neo-project/neo/blob/ed68274e7dec2622468d3bc67df6e0f2913d903b/src/neo/Network/P2P/Payloads/Signer.cs#L192-L197

So the first stackitem (binary Signer's representation) looks weird and redundant a bit. We have all other Signer's data available at the same stackitem, so why do we need its serialized binary representation?

### The question

Do we need the Signer's binary representation to be included in its stackitem representation? If so, could you, please, explain, why?

**Comment by shargon** [comment]
Agree, the first version only wanted the binary, now it's not required

**Comment by roman-khimov** [comment]
To me it's just duplicating for no good reason, interpreting these bytes is time-consuming and error-prone activity that is easily avoided by using proper stack item representation (which we already have anyway).

**Comment by erikzhang** [comment]
In some cases, we can use a single `EQUAL` instruction to determine whether it is the signer we want without traversing every field of it.

**Comment by roman-khimov** [comment]
Doesn't seem to be a useful scenario to me.
:rocket:: drop binary (merge  #2708)
:tada: keep binary (close #2708)
