### ISSUE TITLE
When was this new TransactionType released onto the network? `TransactionType.StateTransaction`

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/neo#271]
Yesterday, I found a problem in my version of `neo-lux` and was wondering if you've seen this and know what it is/how it happened?

Context: It was near line 434 in  `Transaction.Unserialize()` (in `neo-lux`).  A `System.NotImplementedException: Message=The method or operation is not implemented.` exception.

On the blockchain there appears to be a Tx with a new `TransactionType.StateTransaction` in block 239486 (7th Tx) on mainnet - that was first used on or before June 15, 2018:
https://neoscan.io/transaction/ccf1404325a601ce7a33291f196bab2c9d4e80581736bfdb5a2325c7aa74427e

@erikzhang Is `TransactionType.StateTransaction` something new or has it always been there?

Michael

**Comment by mwherman2000** [comment]
`TransactionType.StateTransaction` doesn't appear in the online docs: 
http://docs.neo.org/en-US/sc/reference/fw/dotnet/neo/Transaction/Type.html

**Comment by mwherman2000** [comment]
@Relfos

**Comment by mwherman2000** [comment]
@erikzhang What is the process for community developers to learn/be informed of breaking changes made in the NEO Core?

**Comment by erikzhang** [comment]
The specification can be found here: https://github.com/neo-project/specification

I will complete it in the next few months.
