### ISSUE TITLE
Cannot catch exceptions from syscalls

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo#2717]
When doing calls with the `SYSCALL` opcode that can return an exception, i'm not able to catch those exceptions in my contract. They are not a `CatchableException` and thus behave like `ABORT` or `ASSERT`. Maybe that was the actual goal of the implementation but I think it would be more intuitive to be able to catch syscall exceptions. 
Example:

```java
try {
    return Account.createStandardAccount(pubKey);
} catch (Exception e) {
    return Hash160.zero();
}
```

**Comment by roman-khimov** [comment]
> Account.createStandardAccount(pubKey)

This will only fail if `pubKey` is not really a public key. Why do want to catch this?

**Comment by shargon** [comment]
We can use `IsValid`

**Comment by devhawk** [comment]
I don't think we should blanket statement enable all syscall exceptions to be caught. I'd be OK with CreateStandardAccount exceptions being catchable, though in this case the exception is thrown in methods called by CreateStandardAccount so we'd have to transform the exception in CreateStandardAccount like this:

``` cs
internal protected static UInt160 CreateStandardAccount(ECPoint pubKey)
{
    try
    {
        return Contract.CreateSignatureRedeemScript(pubKey).ToScriptHash();
    }
    catch (Exception ex)
    {
        throw new CatchableException(ex.Message);
    }
}
```

**Comment by csmuller** [comment]
I followed the comments on the corresponding PR. I get your security concerns. Will close this issue.
