### ISSUE TITLE
TransactionState.FromStackItem throws when state not available

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#2721]
#2591 was the first PR merged after Neo 3.1 shipped. This PR added a `public VMState State;` field to `TransactionState`. However, the `TransactionState.FromStackItem` method does not take into account that the State field will not be present for any transactions that were recorded before 3.2 ships. So any 3.2 code that attempts to retrieve a TransactionState that was recorded during 3.1 or earlier will throw. 

This will affect any method that calls `LedgerContract.GetTransactionState`

**Comment by devhawk** [comment]
Note, this is likely *NOT* an issue if we do a full resync for 3.2 (which may be required for other reasons). However, the existing error message (index out of range) is not going to be helpful for an operator who runs into this issue.

**Comment by shargon** [comment]
I think that we should resync
