### ISSUE TITLE
segmentation fault on exit (NEO-CLI 2.7.5.0)

### ISSUE THREAD

**Issue by wy** [neo-project/neo#273]
ubuntu 16. Plenty of RAM, storage etc.

When I try and exit (using command exit), it hangs for a while and then finally either complains segment fault or dumps a list of chain files and then says core dumped.

```
neo> show state
Height: 0/2048025/2048026, Nodes: 0
neo> exit
Segmentation fault (core dumped)
```

Have reproduced three times now on different VMs.

**Comment by shargon** [comment]
What version of dotnet did you use?

**Comment by wy** [comment]
2.1

See the exact script run below

#!/bin/bash
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-runtime-2.1 --yes
sudo apt-get install dotnet-sdk-2.1 --yes
sudo apt-get install unzip --yes
dotnet new console -o hwapp
cd hwapp
dotnet restore
dotnet run > helloworld.log 2>&1
cd ../
wget https://github.com/neo-project/neo-cli/releases/download/v2.7.5/neo-cli-linux-x64.zip && unzip neo-cli-linux-x64.zip
sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev --yes
cd neo-cli

wget http://static.neo.org/client/chain.acc.zip
dotnet neo-cli.dll --rpc --log

**Comment by wy** [comment]
I am closing this issue as 2.7.6 seems to have fixed it and all is well.

Thanks
