### ISSUE TITLE
Snapshot isolation might be broken if contract calls itself via System.Contract.Call

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo#2746]
**Describe the bug**
I was not able to build current master from the source code, thus I'm not sure whether this bug really exists, so please, correct me if I'm wrong.

The bug is related to the #2729. Let the contract call itself via `System.Contract.Call`. It's not the common situation, but it's possible. Then new execution context *whith the same script* will be created and pushed to the istack. Contract can perform storage changes and emit notifications. After the call is processed, the execution context should be unloaded, but it has the same script as the parent context. Thus, storage changes and notification counter changes won't be persisted due to https://github.com/neo-project/neo/blob/03fd443d622067204e1a9ddd44d145a1feaf58ed/src/neo/SmartContract/ApplicationEngine.cs#L264 and storage changes will be lost.

**To Reproduce**
I wrote a test in Golang to show the idea:
```
func TestSnapshotIsolation(t *testing.T) {
	bc, acc := chain.NewSingle(t)
	e := neotest.NewExecutor(t, bc, acc, acc)

	// Contract A calls method of self and throws if storage changes made by Do are unavailable after call to it.
	srcA := `package contractA
		import (
			"github.com/nspcc-dev/neo-go/pkg/interop/contract"
			"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
			"github.com/nspcc-dev/neo-go/pkg/interop/storage"
		)
		var key = []byte("key")
		func Test() {
			contract.Call(runtime.GetExecutingScriptHash(), "callMyselfAndCheck", contract.All)
		}
		func CallMyselfAndCheck() {
			contract.Call(runtime.GetExecutingScriptHash(), "do", contract.All)
			c := storage.GetContext()
			val := storage.Get(c, key)
			if val == nil {
				panic("changes from previous context were not persisted")
			}
		}
		func Do() {
			c := storage.GetContext()
			storage.Put(c, key, []byte("value"))
		}`
	ctrA := neotest.CompileSource(t, acc.ScriptHash(), strings.NewReader(srcA), &compiler.Options{
		NoEventsCheck:      true,
		NoPermissionsCheck: true,
		Name:               "contractA",
		Permissions:        []manifest.Permission{{Methods: manifest.WildStrings{Value: nil}}},
	})
	e.DeployContract(t, ctrA, nil)

	ctrInvoker := e.NewInvoker(ctrA.Hash, e.Committee)
	ctrInvoker.Invoke(t, stackitem.Null{}, "test")
}
```

If the bug exists, then this test will fail on
```
if val == nil {
   panic("changes from previous context were not persisted")
}
```

**Expected behavior**
When the contract calls itself via `System.Contract.Call`, changes made in the newly-created context should be persisted (or discarded) as for any other call to `System.Contract.Call`.

**Platform:**
 - Version:  /Neo:3.1.0.1/

**Comment by erikzhang** [comment]
Although the content of the two `Script`s is the same, they are still two different instances. Equality comparison of objects in C# is by reference by default, so there is no problem.

**Comment by roman-khimov** [comment]
So it's not possible for contract to invoke itself via `System.Contract.Call`?

**Comment by erikzhang** [comment]
> So it's not possible for contract to invoke itself via System.Contract.Call?

It's possible, but it shouldn't cause any problems.

**Comment by AnnaShaleva** [comment]
> they are still two different instances

Thank you for clarification, I've completely overlooked it.
