### ISSUE TITLE
Add vote related notifications

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#2752]
**Summary or problem description**
Voting is quite important for the chain, but there are no notifications broadcasted that we can easily listen to or request. It happens infrequent enough that it will have little impact on the overall performance or applicationlog storage size that I think it is reasonable to add. 

There's only a couple of ways currently to figure out if a vote happened in a block
1. disassemble the script searching for code that performs a vote
2. ask for the list of candidates in the next block and diff it against a previous snapshot
3. call `getAccountState` on all known addresses

As you can see they get increasingly worse.

**Do you have any solution you want to propose?**
Add the following 3 notifications
1. Candidate registered
2. Candidate unregistered
3. Vote casted

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Ledger

**Comment by dusmart** [comment]
kkkkkk, another hard fork is needed

**Comment by ixje** [comment]
> One questions for your scene. Will you count A's voting after these 4 steps? In the implementation for now, it will lose the voting information after step 3. And the notification can't help you too much.
> 
> 1. address A get some NEO from other place
> 2. A vote to a candidate
> 3. A transfer all his NEO to other address
> 4. address A get some NEO from other palce

Once a candidate has voted we can track the vote notifications as well as `transfer` notifications for NeoToken and combine these 2 to know when balance has shifted and thus a vote.

> Plus, could you please show that where could we use the voting result?

This is up to the end user. One use case is tracking a single wallet's voting behaviour over time. Another is tracking the network's voting behaviour and committee changes over time. I've done an internal hackathon about a year ago which did exactly that. In other words, trackers like [dora.coz.io](https://dora.coz.io/) can use this information to build statistics pages to provide network insights to end users which can help them decide who to vote on among other things.

**Comment by ixje** [comment]
@dusmart @roman-khimov you two have shown activity in this issue. Can you please add your vote on your preferred implementation direction here https://github.com/neo-project/neo/pull/2754#discussion_r880621045
thanks
