### ISSUE TITLE
test Neo and Gas

### ISSUE THREAD

**Issue by yura-sutnuk** [neo-project/neo#277]
i requested several test coin, created contract address from 2 public key (my own and 1 that i take by email), maked rebuild index but balance is still 0. I do something wrong?

**Comment by jonatanblockchain** [comment]
neo-gui or neo-cli must be full sync

**Comment by yura-sutnuk** [comment]
![image](https://user-images.githubusercontent.com/32939180/41770931-42bda8e4-761c-11e8-85dd-f402320f329a.png)
the 2 number are the same so it looks like full sync

**Comment by jonatanblockchain** [comment]
No, three number must be equal.

**Comment by yura-sutnuk** [comment]
I downloaded archive chain.acc.test.zip, rename to chain.acc.zip and put into neo directory. The 2-d and 3-th number go up fast but first after rebuilding index go up slow (after one hour it is only 150000)
