### ISSUE TITLE
Strange logic about the default seed node

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo#2772]
When I built the private net, I removed the SeedList from config.json and it still connects to the seed node on startup

![image](https://user-images.githubusercontent.com/82148280/173798333-0331ecad-a552-42e5-8f63-16c93ca67b04.png)

![image](https://user-images.githubusercontent.com/82148280/173798274-4b2aa044-fb85-4a95-86d6-5ee4b9894e3e.png)

**Comment by dusmart** [comment]
Changing the network id to your own id will disable this happening.

IMO, other nodes may have stored your address in their memory. That's why other nodes could reach you.

**Comment by shargon** [comment]
If it's empty it will take the defaults one

**Comment by erikzhang** [comment]
If you remove `SeedList`, it will take the default ones. But if you pass an empty array `[]`, the seed list will be empty.

**Comment by ixje** [comment]
> If you remove `SeedList`, it will take the default ones. But if you pass an empty array `[]`, the seed list will be empty.

That's not how it really works

https://user-images.githubusercontent.com/6625537/174960340-c132e562-2d59-4347-b33b-333aae9ced0b.mov

**Comment by shargon** [comment]
It seems that empty array returns false in `section.Exists()`...
