### ISSUE TITLE
Add an Opcode to call contact of specific version

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2775]
**Summary or problem description**
Since neo allows smart contract to update themselves, it is risky for users to call these functions without knowing which contract version they are using.

**Do you have any solution you want to propose?**
Add a new `call` opcode enabling users to specify the contract version, if the contact version is not correct, then the transaction should fault directly.

**Opcode**: `CALL_V`
**Structure**:  PUSHDATA1| 0x14| contract address|DUP|PUSHINT32| (4 bytes) version| CALL_V

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- VM

**Comment by shargon** [comment]
You can't do it because maybe the contract fixed a bug and store the information in a different format. The project can use a proxy

**Comment by Liaojinghui** [comment]
> You can't do it because maybe the contract fixed a bug and store the information in a different format. The project can use a proxy

Adding the opcode can not solve the problem or we can not add this Opcode?

**Comment by roman-khimov** [comment]
> You can't do it because maybe the contract fixed a bug and store the information in a different format.

But what's the problem? The call will just fail and that's it. I'm not sure we need this, but it can be done.
