### ISSUE TITLE
Create a new type of "Storage Paid" contracts

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#279]
Currently, deploy cost is high, but user has the benefit of 10 GAS limit afterwards. NEP5 contracts are the most common type, and they are not supposed to hit this 10 GAS limit in any way. I believe a cheaper option  “Storage Paid” contract may be proposed (perhaps 200~300 GAS to deploy), also allowing Storage, but **the increasing Storage.Put costs cannot go in 10 GAS quota** (they must be payed). This could be a good option for NEP5 contracts, which has very limited Storage scenario (and users can be responsible and pay a little bit for it, in limited situations, that can also be cheaper in this kind of contract). If combined with ([Storage.Delete free proposal](https://github.com/neo-project/neo/issues/278)), transfers between NEP5 registered users will be free (no extra storage), and users only will pay for registering new "addresses" (that actually increase storage). 
If combined with smart techniques in verification phase, the contract itself may be able to "subsidize" the fees to their users (continuing to be free), at the risks and the logic of the contract designer.

**Comment by vncoelho** [comment]
Gud gud veri gud, it could motivated rising and emerging projects.

**Comment by erikzhang** [comment]
The pricing structure will be adjusted in NEO 3.0, please wait for the new white paper.

**Comment by igormcoelho** [comment]
@erikzhang waiting forward to see the new WP.

**Comment by mwherman2000** [comment]
@erikzhang Is this white paper the same as the yellow paper? ...or different?

**Comment by hal0x2328** [comment]
I don't understand the reasoning for this proposal - @igormcoelho do you mean to suggest that if someone purchases a NEP-5 token on an exchange and then withdraws it to their wallet (which did not have any tokens before), they should be charged 1 GAS as a system fee on top of the exchange's withdrawal fee? I can't imagine any token project thinking this would be beneficial to their long-term token price just to shave off a few hundred GAS on deployment up front.

People already complain about exchange withdrawal fees that are just a few dollars, but exchange fees, unlike system fees, can be continually adjusted to account for price increases. Once you start offloading system fees onto users, as the GAS price increases, use of the the "storage paid" contracts will grind to a halt as the price of 1 GAS might exceed the value of whatever token they were purchasing.

**Comment by igormcoelho** [comment]
hal I imagine they would really be charged, but at a fraction of a gas, not one gas (currently the cost is already a fraction of KB),because they are really spending storage space. But lets wait to see Neo 3.0, it may come with interesting stuff.

**Comment by mwherman2000** [comment]
@hal0x2328 @igormcoelho I agree with Hal.  If the vision for the NEO platform to be no more than a crypto/ICO platform, charge huge amounts for strorage.  

On the otherhand, the NEO platform's Purpose, Goals, Objectives and Drivers are to be the #1 blockchain for distributed enterprise applications, storage costs have to be reduced to negligible ...or, at least, at or below AWS/Azure/Google cloud storage costs.

**Comment by mwherman2000** [comment]
RE: But lets wait to see Neo 3.0, it may come with interesting stuff.

Why wait?  ...if NEO is truly an open, transparent, community-based, collaboration-based project, why can't the open discussion continue now (through to resolution)?  #nomorewalledingateddiscussions

CC: @dahongfei @PeterLinX @lerider and @erikzhang

**Comment by igormcoelho** [comment]
I didn't mean to stop the discussions Michael, this is an open community. Particularly, I have put my opinion, and I'm interested to see what Erik and Peter have to say, but they seem to be focused on writting a consistent document that will organize the missing pieces of the environment (what Erik is now calling Neo 3.0), that's why I will have to wait. 
But I see your point, I don't mean NEO is only meant for NEP5, but I'm just trying to propose something that may cost a little bit to the user, in order to avoid bad and uninteresting behavior for the network (such as constantly changing addresses, for no reason), and to be much more costly for projects that are solely based on large amounts of storage (that may not be cost efficient for the network). And I agree with you that costs must be negligible, we can achieve that with more nodes and more infrastructure, but that's why Storage.Put costs must not be same as current ones, it's currently expensive for my proposal to be viable.

**Comment by erikzhang** [comment]
See #286

**Comment by jmseigneur** [comment]
Cancelling the free smart contract execution would be a major pricing change that would endanger the viability of projects that have planned to use NEO base on its initial pricing model. As @mwherman2000 underlines, small storage and light execution pricing should remain very low compared to other systems. For example, 10 first GAS free has been one reason that [Reputaction](https://medium.com/@reputaction/decentralized-application-dapp-platform-selection-c7790ea74bce) selected NEO over other platforms. It doesn't give a good signal to drastically change pricing model from one version to another. Uncertainty in the stability of the pricing model will scare away a number of projects.

**Comment by hal0x2328** [comment]
@jmseigneur You should add your comment to #286 for visibility

**Comment by igormcoelho** [comment]
@jmseigneur its better to discuss on the other thread. I may not have been very clear but Im the biggest defender of 10 gas policy, thats why I love Neo (besides tps). I'll prepare some slides to defend my point, storage only should be paid.
