### ISSUE TITLE
Add debug map URL to the NEF?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2797]
**Summary or problem description**
We have the URL for the source code, but we have to compile it to be able to debug it. If we had the access to the debug map file, we could pull and debug a contract without having to compile it.  
Flamingo example: I can get the NEF script from the blockchain, and the source code from GitHub, but I cannot 'easily deploy and debug flamingo locally'. To be able to debug it, we need the debug map. If it is 'accessible', we could download the files and debug the contract without compiling it first.  Considering that we have multiple programming languages, this is a big deal. We should not rely on developers to install Go, Java, C#, and Python to debug their smart contract dependencies.

I can also accept that the URL for the source code should point to a repository, and we could use that to get the debug map, however, that is not common (nobody does it).  We have to choose between usability and storage efficiency (or somehow make people store the debug map files on github)

**Do you have any solution you want to propose?**
Add the URL for the debugger map file inside the NEF.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- Ledger
- SDK

**Comment by roman-khimov** [comment]
1. Debug-enabled NEFs can differ from production ones.
2. I doubt adding yet another URL to NEF is appropriate, if people want to publish debug info, they can do it already.
3. Last time I tried there was an issue with relative paths to source code in the debugger (https://github.com/nspcc-dev/neo-go/commit/f5d5019b7085d13aabc6897112ace5ebc407ed0a), debug info can have limited usability because of that.

**Comment by devhawk** [comment]
We can produce debug info for debug and release contract builds. Release Optimization can reduce debug experience quality, but the basic concept still applies

**Comment by lock9** [comment]
@devhawk Where and how do you think we could store the debug map?

**Comment by devhawk** [comment]
Doesn't onegate have a service for hosting contract source? Debug info could be saved there too

**Comment by lock9** [comment]
Why would you need a hosting service for contract sources ? 🤔
