### ISSUE TITLE
Nested neo blocks are deleted on 2nd save

### ISSUE THREAD

**Issue by rene-haefliger** [neo-project/neo#2798]
**Describe the bug**
When nested elements are edited, all elements inside the neo-block are deleted. E.g. Accoreon block and associated accordion items.

**To Reproduce**
1. Create a Neo Field with a blocktype on first level
2. Create a blocktype not available on first level
3. Allow the sub blocktype in the first level blocktype
4. Add Content on both levels
5. Save
6. Edit sub blocktypes
7. Save

**Behavior**
Sub blocktypes are deleted

**Expected behavior**
Changes should be saved

Neo Version 3.2.2
Craft Version 4.2.0.1

**Comment by lock9** [comment]
Hi @rene-haefliger . I think you are in the wrong repository.

**Comment by rene-haefliger** [comment]
Oh, sorry :) Weniger arbeit für euch, demfall :) Gruss aus Luzern
