### ISSUE TITLE
Migration costs should be cheaper (half price?)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#280]
In my opinion, Migration is very useful for fixing bugs, so it should be cheaper than a regular deploy (but still expensive to not create frankstein lifelong contracts). Is it reasonable to propose half the price on migrations?

**Comment by igormcoelho** [comment]
Do you have any thoughts on this @shargon ?

**Comment by vncoelho** [comment]
I also agree, Igor.

It would be hard to really count with the goodwill of everyone.
On the other hand, Aigor, could have a rule, if Migrate with an AVM with lower size than the previous one.

Because the AVM could now be something very very complex and people just keep selling their previous SC ownerships. :dagger: 
HAuehauehauhueaea

**Comment by igormcoelho** [comment]
Yeah, that's true Vitor... but if it's a NEP5 for example, no one will trust a contract with a general migration scheme (it could be very easy for the owner to steal any kind of tokens). So, in general migration assumes trusts and risk, which can be smaller than the risk of bugs (the main intention of migration I believe).

**Comment by vncoelho** [comment]
That is right.

There could be other mechanisms for thinking about these cases in which Migration was done improperly.

**Comment by erikzhang** [comment]
The pricing structure will be adjusted in NEO 3.0, please wait for the new white paper.

**Comment by shargon** [comment]
Could be cheaper, but like this 

`var dif=(OldContractSize-NewContractSize)`

This ensure that you don't create a contract with few bytes, and then you use migration for fill the contract

**Comment by erikzhang** [comment]
See #286
