### ISSUE TITLE
Unupgradable Contact

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2801]
**Summary or problem description**
Currently contracts on neo N3 can update themselves, though this makes it convenience for contact developers to patch the contract, it arises concerns to the contract users since the contract logic may change while they invoke the contract.

**Do you have any solution you want to propose?**
Enable contact to set itself as unupgradable.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- SDK

**Comment by Liaojinghui** [comment]
https://github.com/neo-project/neo/issues/2775

**Comment by roman-khimov** [comment]
Maybe this can left for explorers/external services to detect and show. The upgrade could be only done by the contract itself, so any contract that doesn't have a call to `update` of `ContractManagement` in its code is unupgradable.
