### ISSUE TITLE
Refactoring code for stability and TPS

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#282]

**Comment by erikzhang** [comment]
> Stability with carved and precise 15s, coming back to that minor insights at #268.
Soon we gonna come back to a compiling and working version there.

Can you make it merged after #288 ?

**Comment by vncoelho** [comment]
Yes, with pleasure, should I already start to compile and try the refactoring or wait a little more?

**Comment by erikzhang** [comment]
> Yes, with pleasure, should I already start to compile and try the refactoring or wait a little more?

Please wait a little more.

**Comment by vncoelho** [comment]
Take your time, @erikzhang. This refactoring sounds like done by 10 people. :dagger: A lot of nice work.

**Comment by AshRolls** [comment]
Stability requires the code for neo 3.0 to have comprehensive unit test coverage, integration tests, and a defined release pipeline process.

**Comment by yanfaruiec** [comment]
数字资产交易所开发，有需要的朋友请加我微信，我们是交易所开发公司
