### ISSUE TITLE
Cannot get signers of current transaction

### ISSUE THREAD

**Issue by merl111** [neo-project/neo#2825]
**Describe the bug**
The native `Ledger` contract has a method called `GetTransactionSigners`, which should return a `Singer[]`, for the current executing transaction it returns `null` though. I am not sure if that's on purpose or not, if it is on purpose, maybe we can expose the signers also on the transaction I can get from `Runtime.ScriptContainer`.

**To Reproduce**
```cs
using System;
using System.Numerics;
using Neo;
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Native;
using Neo.SmartContract.Framework.Services;

namespace GhostMarket.Exchange;

public class TestContract : SmartContract
{
    public static bool GetSigners()
    {
        var tx = (Transaction)Runtime.ScriptContainer;
        var signers = Ledger.GetTransactionSigners(tx.Hash);
        if (signers == null)
        {
            // for demonstration purposes only
            throw new Exception("signers array is null");
        }


        return true;
    }
}
```

**Expected behavior**
Above example contract should not throw the exception, but return true.

**Platform:**
 -  Linux x64
 - Neo.Smartcontract.Framework 3.4.0
 - Neo Express 3.4.18+f8b893e693

**Comment by roman-khimov** [comment]
That's the same behavior as #2568, it's an intended one for the native Ledger contract. But I agree that this creates some interface asymmetry, it can be solved with another `Runtime` syscall.

**Comment by shargon** [comment]
We can fix it with the `ScriptContainer`
