### ISSUE TITLE
Node allows to deploy contract that can never be invoked/retrieved from storage

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2829]
**Describe the bug**
This transaction:
https://dora.coz.io/transaction/neo3/mainnet/0x154f30d743c97d22fb17c5d363040ac4c9d351a1068b77b3ca6a71f91dfdcfc1

deploys (updates, but this is irrelevant) a contract with a huge manifest (605 methods). It's saved correctly in the ContractManagement state, but it's impossible to get this contract's state:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 5, "method": "getcontractstate", "params": ["6f1837723768f27a6f6a14452977e3e0e264f2cc"] }' http://seed4.neo.org:10332 
{"jsonrpc":"2.0","id":5,"error":{"code":-32602,"message":"Invalid params"}}
```
or invoke it:
```
$ ./bin/neo-go contract testinvokefunction -r http://seed4.neo.org:10332 6f1837723768f27a6f6a14452977e3e0e264f2cc a0
Warning: FAULT VM state returned from the RPC node: One of the identified items was in an invalid format.
```

**Expected behavior**
Either we have a contract that can be interacted with or the deployment should have failed.

**Platform:**
 - OS: any
 - Version: 3.4.0

**(Optional) Additional context**
Contract's manifest has too many elements when it's converted to stack item, this is not checked during conversion/saving, but when it's retrieved from the storage deserialization fails because of the number of elements. I'd say 0x154f30d743c97d22fb17c5d363040ac4c9d351a1068b77b3ca6a71f91dfdcfc1 transaction should have failed and this manifest should've been rejected. Refs. nspcc-dev/neo-go#2801.

**Comment by vncoelho** [comment]
Good report, @roman-khimov.

**Comment by Liaojinghui** [comment]
why allowing developer deploy a crrupted contract is a problem here? Non-security related format checking could be done off-line, as long as it does not DOS the whole system, i think its fine.

**Comment by roman-khimov** [comment]
https://dora.coz.io/ has stopped at exactly block 2506873, probably related.

**Comment by superboyiii** [comment]
Maybe we should check decoding first before updating in `ContractManagement`? It's good to solve this but it also need a hard fork.

**Comment by shargon** [comment]
> It's good to solve this but it also need a hard fork.

We can use the height as a version

**Comment by superboyiii** [comment]
> We can use the height as a version

It's good, but not convenient to remember what it's for.

**Comment by merl111** [comment]
> why allowing developer deploy a crrupted contract is a problem here? Non-security related format checking could be done offline, as long as it does not DOS the whole system, i think its fine.

It cannot be done offline, if the `ContractState` cannot be deserialized you can never call `NativeContract.ContractManagement.ListContracts` again, since it would just fail because it hit's max stack size during the deserialization process.

**Comment by shargon** [comment]
We have two possibilities:

- I think it was not possible to call this contract, so we can make this transaction fail, the gas will be the same and the contract will not be there anymore.
- Allow more elements in `ContractState` deserialization and avoid future problems.
