### ISSUE TITLE
New API for NeoContract: System.Runtime.Platform

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#283]
Gets the platform on which the contract is running.

For example:
- On Neo, it returns `"NEO"`.
- On Ontology, it returns `"Ontology"`.

**Comment by shargon** [comment]
What should return this API? Will be a deterministic result?

**Comment by vncoelho** [comment]
I think I got it.
If it is my private chain, returns "Babylon", for example.
And then, I, sporadically, publish some state of my blockchain in the Neo Original Public one.

**Comment by igormcoelho** [comment]
Will Neo come with interchain communication using a similar resource Erik? This way one platform could declare its "trusted" buddies, and perform Neo opcodes "outside" in a trusted fashion.
