### ISSUE TITLE
Updated contract cannot be retrieved

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#2845]
**Describe the bug**
Mainnet block `2506873` updates a contract with the hash `0x6f1837723768f27a6f6a14452977e3e0e264f2cc` that cannot be retrieved 
- through the `getcontractstate` RPC command
- through the `getcontract` function of the `ContractManagement` contract

The reason being is that during retrieval the contract state will be parsed using
https://github.com/neo-project/neo/blob/a84d6ec7d1a359a18d10dc2703d8cd7c82a19d95/src/Neo/SmartContract/BinarySerializer.cs#L68
which will hit the stack size limit

![image](https://user-images.githubusercontent.com/6625537/216564354-0fd1cc30-ea5d-4e45-82fe-bdc4b7dc8430.png)

**To Reproduce**
1. have a mainnet node synced to at least block `2506874` (or use neo-express with the `contract download` command)
2. request the contract state over RPC
   ```
    {
      "jsonrpc": "2.0",
      "id": 1,
      "method": "getcontractstate",
      "params": [
        "0x6f1837723768f27a6f6a14452977e3e0e264f2cc"
      ]
    }
   ```

alternatively use the stateservice to request the contract state and pass the return value into the Deserialize function linked above

**Expected behavior**
deserialization to work and a Contract state is returned

**Platform:**
 - Version neo-cli 3.5.0

**Comment by roman-khimov** [comment]
Duplicates #2829. Unfortunately it didn't get enough attention.

**Comment by ixje** [comment]
will close in favour of the existing one
