### ISSUE TITLE
Calling Smart Contracts

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2846]
Can someone give me an example on how to call a Smart Contract in a dapp Console app?

**Comment by Liaojinghui** [comment]
Hope this can help you: https://docs.neo.org/docs/en-us/node/cli/cli.html

**Comment by cschuchardt88** [comment]
I figured it out, had to the RPC server or use custom neo plugin

**Comment by NamanMohnani** [comment]
Can I work on this issue ? I am an aspiring blockchain developer and I am trying to contribute to open source to increase my knowledge about web3 and blockchain.

**Comment by NamanMohnani** [comment]
Alright, thank you for answering @vncoelho
