### ISSUE TITLE
Add a method to get the length of a String

### ISSUE THREAD

**Issue by luc10921** [neo-project/neo#2851]
**Summary or problem description**
When trying to get the size of a String, you get the number of bytes.
Example:
```csharp
        public static int[] Test()
        {
            string a = "A";
            string tilde = "ã";
            string duck = "🦆";

            int[] sizes = { a.Length, tilde.Length, duck.Length };

            return sizes;    // It returns 1, 2 and 4
        }
```

**Do you have any solution you want to propose?**
Add a `StringLength` method on the StdLib smart contract

Reference:
https://github.com/neo-project/neo-vm/issues/437

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- StdLib Smart Contract

**Comment by Liaojinghui** [comment]
@NamanMohnani You can take a look at this pr here https://github.com/neo-project/neo/pull/2854
