### ISSUE TITLE
ApplicationEngine.Notify blottleneck

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2852]
**Summary or problem description**
ApplicationEngine.Notify bottlenecks with blocks with multiple transactions. Doing any work in this event will cuz the import block to slow down to a crawing hault.

**Do you have any solution you want to propose?**
Thread out the events or the processing with the ApplicationEngine class

**Neo Version**
- Neo 3.0.5

**Where in the software does this update applies to?**
- NEO.dll dotnet
- class Neo.SmartContract.ApplicationEngine

```C#
var NeoSystem = new NeoSystem(_protocolSettings, Settings.Default.Storage.Engine, String.Format(Settings.Default.Storage.Path, _protocolSettings.Network.ToString("X8")));

ApplicationEngine.Notify += DoWork;

private void DoWork(object sender, NotifyEventArgs e)
        {
            while(true)
            {
                Thread.Sleep(10000);
            }
        }
```

**Comment by Liaojinghui** [comment]
Neo version 3.5 or 3.0.5?

**Comment by cschuchardt88** [comment]
3.5

**Comment by vncoelho** [comment]
Thanks @cschuchardt88 for the report.
Where you using an adapted node or RpcClient, something like that?

**Comment by cschuchardt88** [comment]
Im working on my a project where I have create my own node cli. You can think of it as Neo-cli as a ASP.NET Core application. It up and running and its great, until i start hooking on events. The reason being, there is no Sub/Pub service for contract events in the C# "neo-cli" RPC like on the GO version(so i hear). Please also note this is with 34+ transactions on single block. yes i know that crypto can take time. But NeoSystem is processing thousands of blocks at a time on import.

Just using NeoSystem Class and other classes of Neo. Now believe me when I say been through the code of NEO. I know it like the back of my hand. Anyways I believe the "onPersist" and "PostPersist" functions are fine. They seem to finish fast enough. I believe the lag is somewhere in Akka (i dont know that technology) somewhere something is locking up threads, maybe the import block, callbacks? Because everything else halts. 

Please note that around 200k-320k (block indexes) there are blocks with transaction of 1k or more for 1 NEO or something.

**Comment by cschuchardt88** [comment]
this is related to resync processing, no need to have open.
