### ISSUE TITLE
Using Transaction Nonce to indicate transaction order.

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo#2861]
**Summary or problem description**
Currently, the nonce filed in the transaction is of no actual use. Maybe we can use it to indicate user transaction orders. This would be useful for anti-MEV services or other transaction order-sensitive applications.

**Do you have any solution you want to propose?**
Make nonce an increment field and update the Consensus to order transactions (of the same user) by nonces.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Consensus

**Comment by Liaojinghui** [comment]
@roman-khimov So, is deterministic transactions order worth a discussion?

**Comment by roman-khimov** [comment]
Even though that discussion had happened quite some time ago I doubt a lot has changed. Nonce is useful as it is now, it's just it has zero relation to E-letter chain transaction nonce. Notice also that `same user` is also a bit of vague concept for Neo with transactions having multiple signers.

Even if we'd like to do it, I don't think we can introduce this behavior into existing networks without a new transaction format, at least not without a new attribute for it. I'd try `DependsOn` route (https://github.com/neo-project/neo/issues/1502#issuecomment-611550437) if we really want to have deterministic order for a single signer (notice that `Conflicts` is almost there in #2818). Other than that I'd just enjoy the possibility of sending a lot of _independent_ transactions.

**Comment by cschuchardt88** [comment]
I think what he is saying, is to have `IStore` keys to be order seekable. That would be nice, their by timestamp or nonce but some kind of order other than random SHA256 hash
