### ISSUE TITLE
Feature manifest and permission system for NeoContract

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#287]
# Abstract

When a smart contract is deployed, it must explicitly declare the features and permissions it will use. When it is running, it will be limited by its declared list of features and permissions, and cannot make any behavior beyond the scope of the list.

# Specification

### Manifest

A complete manifest is described by a json file:

```json
{
  "groups": {},
  "features": {},
  "abi": {},
  "permissions": [],
  "trusts": [],
  "safemethods": []
}
```

### Groups

A group represents a set of mutually trusted contracts. A contract will trust and allow any contract in the same group to invoke it, and the user interface will not give any warnings.

A group is identified by a public key and must be accompanied by a signature for the contract hash to prove that the contract is indeed included in the group.

```json
{
  "pubkey": "028e92a0f582bd3517497eff1a9beb41821991b8589bfcba20c2f40746f5c170a1",
  "signature": "f6dbce908e291f5d8a81450292a3674f48ef8079306d613b3783dc263287704a0ef48f47679aa12b7d5e598fdb52d63ca7566afbe0e239437191d05698837e3b"
}
```

Where `pubkey` represents the public key of the group and `signature` is the signature of the contract hash.

### Features

The `features` field describes what features are available for the contract.

```json
{
  "storage": true,
  "payable": true
}
```

The `storage` field is a boolean value indicating whether the contract has a storage. The value `true` means that it has, and `false` means not.

The `payable` field is a boolean value indicating whether the contract accepts transfers. The value `true` means that it accepts, and `false` means not.

### ABI

For technical details of ABI, please refer to [NEP-3: NeoContract ABI](https://github.com/neo-project/proposals/blob/master/nep-3.mediawiki).

### Permission

The `permissions` field is an array containing a set of `Permission` objects. It describes which contracts may be invoked and which methods are called.

The definition of the `Permission` object is as follows:

```json
{
  "contract": "hash | group | *",
  "methods": [] | "*"
}
```

The `contract` field indicates the contract to be invoked. It can be a hash of a contract, a public key of a group, or a wildcard `*`.

If it specifies a hash of a contract, then the contract will be invoked; If it specifies a public key of a group, then any contract in this group will be invoked; If it specifies a wildcard `*`, then any contract will be invoked.

The `methods` field is an array containing a set of methods to be called. It can also be assigned with a wildcard `*`. If it is a wildcard `*`, then it means that any method can be called.

If a contract invokes a contract or method that is not declared in the manifest at runtime, the invocation will fail.

### Trusts

The `trusts` field is an array containing a set of contract hashes or group public keys. It can also be assigned with a wildcard `*`. If it is a wildcard `*`, then it means that it trusts any contract.

If a contract is trusted, the user interface will not give any warnings when called by the contract.

### Safemethods

The `safemethods` field is an array containing a set of method names. It can also be assigned with a wildcard `*`. If it is a wildcard `*`, then it means that all methods of the contract are safe.

If a method is marked as safe, the user interface will not give any warnings when it is called by any other contract.

## New APIs

1. System.Contract.Create

   ```c#
   ContractState Create(byte[] script, string manifest)
   ```

   Create a new contract with the specified `script` and `manifest`. If some fields in the `manifest` are not provided, the default value will be used. The default manifest is as follows:

   ```json
   {
     "group": null,
     "features": {
       "storage": false,
       "payable": false
     },
     "abi": null,
     "permissions": [
       {
         "contract": "*",
         "methods": "*"
       }
     ],
     "trusts": "*",
     "safemethods": "*"
   }
   ```

1. System.Contract.Update

   ```c#
   ContractState Update(byte[] script, string manifest)
   ```

   The script or manifest of the contract will be updated by the parameters. Both the parameters `script` and `manifest` can be `null`. If `script` is `null`, the script of the contract will not be updated, and the script hash will not be changed. If `manifest` is `null`, the manifest of the contract will not be updated. If both `script` and `manifest` are `null`, nothing will be changed then. If `manifest` is not `null`, only the fields that exist in this parameter will be updated, and fields that do not exist in the parameter will retain the old values.

# Backwards Compatibility

For old contracts, we can create manifests for them easily. Here's an example:

```json
{
  "group": null,
  "features": {
    "storage": true,
    "payable": false
  },
  "abi": null,
  "permissions": [
    {
      "contract": "*",
      "methods": "*"
    }
  ],
  "trusts": "*",
  "safemethods": "*"
}
```

**Comment by vncoelho** [comment]
If you saying, should be right...aheuahueaea :dagger: 
I did not get it yet.

**Comment by igormcoelho** [comment]
This is genious one @erikzhang ! This solves the issue of hardcoding OWNER address and simplifies everything with extra security (I'm assuming scripthash 0xceab719b8baa2310f232ee0d277c061704541cfb is the only one allowed to invoke, right?). How will this be submitted to the network, together with the avm deploy? Could it be updated later with a call other than Migration?

**Comment by erikzhang** [comment]
> Could it be updated later with a call other than Migration?

Yes, it should be updated later.

**Comment by erikzhang** [comment]
> Is this "dynamic" in storage a plan for price variation after storage overloading?

Correct.

**Comment by erikzhang** [comment]
I have a new idea. A contract can declare which contracts and methods it will invoke. For example:

```json
{
  "features": {
    "storage": {
      "size": 500,
      "dynamic": true
    },
    "payable": true
  },
  "permissions": [
    {
      "hash": "0xceab719b8baa2310f232ee0d277c061704541cfb",
      "methods": [ "transfer", "balanceOf" ]
    }
  ]
}
```

This manifest restricts the contract to only invoke the contract with a hash of `0xceab719b8baa2310f232ee0d277c061704541cfb` and can only call its `transfer` and `balanceOf` methods.

It can also declare that it will call all methods of the contract:

```json
{
  "permissions": [
    {
      "hash": "0xceab719b8baa2310f232ee0d277c061704541cfb",
      "methods": "*"
    }
  ]
}
```

For dynamic invocations, you can declare like this:

```json
{
  "permissions": [
    {
      "hash": "*",
      "methods": "*"
    }
  ]
}
```

You can also restrict the methods to be called in dynamic invocations:

```json
{
  "permissions": [
    {
      "hash": "*",
      "methods": [ "name", "symbol", "decimals" ]
    }
  ]
}
```

You can also add special records:

```json
{
  "permissions": [
    {
      "hash": "*",
      "methods": [ "name", "symbol", "decimals" ]
    },
    {
      "hash": "0xceab719b8baa2310f232ee0d277c061704541cfb",
      "methods": [ "transfer", "balanceOf" ]
    }
  ]
}
```

A contract can also be declared without permission:

```json
{
  "permissions": []
}
```

In this case, the contract can only call itself.

**Comment by vncoelho** [comment]
Sounds great, @erikzhang.
In #346 you commented about "allow developers modify the ABI of the contract".
How about these set of permissions? 
Block explores could track any change in these permissions and ABI's.

**Comment by igormcoelho** [comment]
Erik, thats a very good idea! And in fact, that could allow us to implement NEP-7 right now... 
in the spirit of nep10:
```
{
   "supportedStandards" : [ "NEP-5", "NEP-7", ... ]
}
```
that would automatically allow nep5 methods internally, and also nep7 behavior with VerifR ApplR... older contracts will automatically receive general permissions and disallow nep7, so it wont break chain.

**Comment by erikzhang** [comment]
@vncoelho @igormcoelho @shargon 
I updated the specification of this proposal.

**Comment by vncoelho** [comment]
O.o, It seems you were inspired. I like the complete and precise description.
I saw the ABI and the UpdateManifest API.

**Comment by igormcoelho** [comment]
Sounds very flexible and general, I'm sure you have many good things in mind Erik. Regarding safemethods, that implies not all abi methods will be safe, right? So what is exactly a "safe" method (does not throw exceptions, does not overwrite storage...)? Regarding the "supportedStandards" or "supportedTriggers", do you think that's reasonable to include in the specification? That would also help to know in advance how that contract behaves, and perhaps even "verification contracts" could have this manifest optionally, so all softwares would know in advance if it's a Standard Account, MultiSig, Timelock... by the way, we are writting a nice specification for Smart Accounts on Neo (https://github.com/NeoResearch/smacco), to make it easier for everyone to write a simple JSON and it automatically generates/compiles in C# code ;) 

SMACCO example (simple account):
```json
{
    "standard": "smacco-1.0",
    "input_type" : "single",
    "pubkey_list" : ["036245f426b4522e8a2901be6ccc1f71e37dc376726cc6665d80c5997e240568fb"],
    "rule" : {
      "rule_type": "ALLOW_IF",
      "condition" : {
        "condition_type" : "CHECKSIG"
      }
    }
  }
```

SMACCO MultiSig 2/3:
```json
{
    "standard": "smacco-1.0",
    "input_type" : "array",
    "pubkey_list" : ["036245f426b4522e8a2901be6ccc1f71e37dc376726cc6665d80c5997e240568fb",
      "0303897394935bb5418b1c1c4cf35513e276c6bd313ddd1330f113ec3dc34fbd0d", "02e2baf21e36df2007189d05b9e682f4192a101dcdf07eed7d6313625a930874b4"],
    "rule" : {
      "rule_type": "ALLOW_IF",
      "condition" : {
        "condition_type" : "CHECKMULTISIG",
        "minimum_required" : "2"
      },
    }
  }
```

SMACCO Timelock: 
```json
{
    "standard": "smacco-1.0",
    "input_type" : "single",
    "pubkey_list" : ["036245f426b4522e8a2901be6ccc1f71e37dc376726cc6665d80c5997e240568fb"],
    "rules" : [
      {
        "rule_type": "DENY_IF",
        "condition" : {
          "condition_type" : "TIMESTAMP_LESS",
          "timestamp" : "1536896190",
        },
      },
      {
        "rule_type": "ALLOW_IF",
        "condition" : {
          "condition_type" : "CHECKSIG"
        },
      },
    ]
  }
```

So if SMACCO becomes a NEP-XXX, and there is some space in Manifest for some kind of "NEP payload", we could specify exactly what the account contract is about.

**Comment by erikzhang** [comment]
> So what is exactly a "safe" method (does not throw exceptions, does not overwrite storage...)?

For example, for a NEP-5 contract, `transfer` is not safe, because if other contracts call `transfer`, the user's assets can be transferred away.

But `balanceOf` is safe because it only queries the balance and does not change the storage state.

**Comment by igormcoelho** [comment]
Ok then, just to make sure I understood correctly. Safe methods should not spend coins (which makes sense), but also should not change storage perhaps? In my head, the safest thing was not to be able to change anything on the contract.

**Comment by erikzhang** [comment]
> Ok then, just to make sure I understood correctly. Safe methods should not spend coins (which makes sense), but also should not change storage perhaps? In my head, the safest thing was not to be able to change anything on the contract.

Perfectly correct.

**Comment by RavenXce** [comment]
This concept sounds nice especially `permissions`.

Regarding `permission` vs `trust`, can I clarify that `permissions` is a VM level safeguard for dynamic invocations (so the whitelisting is done in manifest rather than at SC level), while `trusts` is simply a client concern?

Wouldn't it be hard for a client to detect what contract will be calling what other contract for dynamic invocations?

> Where pubkey represents the public key of the group and signature is the signature of the contract hash.
Btw, is a signature of a non-prefixed message of just the contract hash safe enough?

**Comment by igormcoelho** [comment]
Very good Erik! I believe we should start adopting this as soon as possible. That will make clear for everyone the intentions of every contract developer.  <3

**Comment by igormcoelho** [comment]
Just clarify one important complementation to contract specific witness. Like you said, suppose a user wants to transfer tokens, a warning is issued because it's not a safe method. So, user can decide to sign just a single invocation and not just leave an open check for the contract, to reuse signature if it wants to. Perhaps I'm misunderstanding something, do you think that proposal is not needed?

**Comment by jsolman** [comment]
> For old contracts, we can create manifests for them easily. Here's an example:

Old contracts need to still be payable when this is implemented. The example given should have `payable: true`

**Comment by vncoelho** [comment]
@jsolman, you are flying high...ahauahaha
I think we should go in this direction.

@erikzhang, should we start a draft of the implementation, who will make the honors? ;D
You and Igor are good for the first designs...ahauahah

**Comment by jsolman** [comment]
Lets get an answer for whether at least some nested permissions are supported before beginning implementation. Such permissions would restrict what other contracts and methods a contract called from another contract may call.

1. Example that allows calling any other contract's `transfer` and `balanceOf` methods, but does not allow the contracts it invokes to be able to invoke another contract method:

```
"permissions": [
    {
      "contract": "*",
      "methods": [ "transfer", "balanceOf" ],
      "dynamicCalls": [{ // since no nested methods are allowed to be called this section could be omitted
        "contract": "*',
        "methods": []
      }]
    }
  ]
```

2. Example that allows a call to a specific contract for only the method `directAllowedMethod`', and then allows the nested contract to call `nestedAllowedMethod`:

```
"permissions": [
    {
      "contract": "{{InsertSomeSpecificContractHashHere}}",
      "methods": [ "directAllowedMethod" ],
      "dynamicCalls": [{ // this seciton is required since a nested method is allowed
        "contract": "*',
        "methods": ["nestedAllowedMethod"]
        // no further nested calls allowed since no further nested "dynamicCalls" object key
      }]
    }
  ]
```

Note: In this second example the directly called contract cannot call nestedAllowedMethod, but the contract it invokes can.

3. Consider call chain A -> B.AllowedBMethod() -> C.AllowedCMethod() -> D.(any contract balanceOf method)(). In this example, Allow A to call B's `AllowedBMethod`, B to call C's `AllowedCMethod`, C to call any contracts' `balanceOf` method.

```
"permissions": [
    {
      "contract": "{{B_CONTRACT_HASH}}",
      "methods": [ "AllowedBMethod" ],
      "dynamicCalls": [{
        "contract": "{{C_CONTRACT_HASH}}',
        "methods": ["AllowedCMethod"],
        "dynamicCalls": [{
          "contract": "*",
          "methods":["balanceOf"]
          // no further nested calls allowed since no further nested "dynamicCalls" object key
        }]
      }]
    }
  ]
```

**Comment by jsolman** [comment]
Is one of the driving reasons for adding support for this feature to be able to execute contracts in parallel, since it will be possible to know the call chains of two contract invocations will not call a common contract that could modify storage and thus have a potential for thread safety issues?

It seems to me that the potential for contract execution parallelism is the main benefit I see to implementing this. From a permission perspective all the desired permissions can be coded in the contract already without the need for this.

> If a contract is trusted, the user interface will not give any warnings when called by the contract.

Is this only meant to be for a user interface. Does it actually block calls from non-trusted contracts to such methods?

> If a method is marked as safe, the user interface will not give any warnings when it is called by any other contract.

Nothing would actually be able to enforce that client implementations actually do anything to notify the user if they are calling a non-safe method.

**Comment by jsolman** [comment]
IMHO it is probably less work to implement #544 before implementing this and supports the majority of the use cases needed by clients to protect users.

Also for the purpose of parallel contract execution, consider this idea: #546

**Comment by igormcoelho** [comment]
@jsolman we specifically discussed this two level permission system here: https://github.com/neo-project/neo/issues/446#issuecomment-437277334
But I didnt see any move for porting the solution to this feature manifest, which is a nice proposal you made. Let's wait for Erik to update this proposal here with latest ideas (he always gets many), so we can actually see whats still missing on the framework, or not.

**Comment by jsolman** [comment]
@erikzhang
Who has permission to update the manifest for an existing contract, does that support have to be programmed into the contract being updated?

Also, maybe to allow use of wildcards for a contract in a permission statement should cost more to deploy since it inhibits the ability to parallelise that contract.

**Comment by erikzhang** [comment]
> Who has permission to update the manifest for an existing contract, does that support have to be programmed into the contract being updated?

The one who has the permission to update the contract will have the permission to update the manifest. Just use the new API that I proposed:

```c#
ContractState Update(byte[] script, string manifest)
```

**Comment by jsolman** [comment]
> If it specifies a wildcard `*`, then any contract will be invoked.

This should cost more in some fashion, since it would require contract byte code analysis to have a chance to run in parallel.

**Comment by erikzhang** [comment]
> Lets get an answer for whether at least some nested permissions are supported before beginning implementation. Such permissions would restrict what other contracts and methods a contract called from another contract may call.
> 
> 1. Example that allows calling any other contract's `transfer` and `balanceOf` methods, but does not allow the contracts it invokes to be able to invoke another contract method:
> 
> ```
> "permissions": [
>     {
>       "contract": "*",
>       "methods": [ "transfer", "balanceOf" ],
>       "dynamicCalls": [{ // since no nested methods are allowed to be called this section could be omitted
>         "contract": "*',
>         "methods": []
>       }]
>     }
>   ]
> ```
> 
> 1. Example that allows a call to a specific contract for only the method `directAllowedMethod`', and then allows the nested contract to call `nestedAllowedMethod`:
> 
> ```
> "permissions": [
>     {
>       "contract": "{{InsertSomeSpecificContractHashHere}}",
>       "methods": [ "directAllowedMethod" ],
>       "dynamicCalls": [{ // this seciton is required since a nested method is allowed
>         "contract": "*',
>         "methods": ["nestedAllowedMethod"]
>         // no further nested calls allowed since no further nested "dynamicCalls" object key
>       }]
>     }
>   ]
> ```
> 
> Note: In this second example the directly called contract cannot call nestedAllowedMethod, but the contract it invokes can.
> 
> 1. Consider call chain A -> B.AllowedBMethod() -> C.AllowedCMethod() -> D.(any contract balanceOf method)(). In this example, Allow A to call B's `AllowedBMethod`, B to call C's `AllowedCMethod`, C to call any contracts' `balanceOf` method.
> 
> ```
> "permissions": [
>     {
>       "contract": "{{B_CONTRACT_HASH}}",
>       "methods": [ "AllowedBMethod" ],
>       "dynamicCalls": [{
>         "contract": "{{C_CONTRACT_HASH}}',
>         "methods": ["AllowedCMethod"],
>         "dynamicCalls": [{
>           "contract": "*",
>           "methods":["balanceOf"]
>           // no further nested calls allowed since no further nested "dynamicCalls" object key
>         }]
>       }]
>     }
>   ]
> ```

@jsolman I think the nested permissions is too complex. We can calculate the list of permissions for the entire call chain and then warn the user.

**Comment by shargon** [comment]
"trusts" and "safemethods" could not be defined in "permissions" ?

**Comment by erikzhang** [comment]
`permissions` is an array. Maybe we can add a new top level object to contains all of them.

**Comment by shargon** [comment]
I think, if you want to allow a "trust" contract, just add it in this array the hash and * as methods, isn't it? Why we need `trusts` and `safemethods` ?

**Comment by shargon** [comment]
And in the case of wildcard. as @jsolman said, it could break the parallel execution, we need to avoid circular dependencies, people will use wildcard in to many cases, i think

**Comment by erikzhang** [comment]
`permissions` is an array of contracts or methods that "I" need to call. If "I" called a contract that not be included in "my" permissions list, "I" will fail in runtime.

`trusts` is an array of contract that can call "me" without UI warnings display.

**Comment by shargon** [comment]
Ok! now i understand it better :P 
And `safemethods` are (ussually) the read only methods right?

**Comment by erikzhang** [comment]
Yes.
