### ISSUE TITLE
Native CryptoLib's `Bls12381Equal` method is unnecessary?

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo#2871]
**Summary or problem description**
`Bls12381Equal` method of native CryptoLib contract compares two BLS12-381 points:
https://github.com/neo-project/neo/blob/535aa2057b6ddddb90b2009ef47f8ba16fd3d036/src/Neo/SmartContract/Native/CryptoLib.BLS12_381.cs#L51-L63

However, these points are always wrapped into `InteropInterface` on stack, thus, they can be compared using `EQUAL` opcode and basic equality rules for interop interfaces: https://github.com/neo-project/neo-vm/blob/5b0a39811b34abacab1273f3ee5a9a9f7e52ac7b/src/Neo.VM/Types/InteropInterface.cs#L38. All BLS12-381 point implementations override Equals method (e.g. GT point: https://github.com/neo-project/Neo.Cryptography.BLS12_381/blob/844bc3a4f7d8ba2c545ace90ca124f8ada4c8d29/src/Neo.Cryptography.BLS12_381/Gt.cs#L38, etc). These overriden Equals methods perform the same thing that native CryptoLib's `Bls12381Equal` does except that `Bls12381Equal` throws an exception on wrong InteropInterface underlying object type.

**Question**
Is there any recommendation on what's preferable to use: native CryptoLib's `Bls12381Equal` or basic equality check via `EQUAL` opcode? Is the `Bls12381Equal` needed to be presented in the CryptoLib's API when we have `EQUAL` opcode?

**Comment by doubiliu** [comment]
I think keep it for now and consider it later. The current version is a stable version.

**Comment by roman-khimov** [comment]
We couldn't remove it later if it's to be introduced in 3.6. It's not a critical thing, but we better understand the reason for its existence if `EQUAL` works the same way, costs less GAS and is somewhat more intuitive (`point1 == point2` vs. `cryptolib.bls12381Equal(point1, point2)`).

**Comment by AnnaShaleva** [comment]
As I've mentioned earlier, the only thing that differs (AFAIU) is that `cryptolib.bls12381Equal` throws an exception in case of any inppropriate point type whereas `EQUAL` just returns `false` in this case.

**Comment by doubiliu** [comment]
I talked with @erikzhang about this , and he wanted to keep it.
