### ISSUE TITLE
Accessing IStore locking up

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2872]
Is there any reason why doing 
```
var store = NeoSystem.LoadStore(Path)
```
Than accessing the store with multi-threads, Will cause the NeoSystem to stop processing blocks and keep disconnecting remote nodes?

Keep in mind i'm accessing the store in ApplicationEngine commit events as well as fetching data from another thread.

**Comment by cschuchardt88** [comment]
Well it's confirmed that creating another store and only using "TryGet" function will make NeoSystem start disconnecting remote nodes and at some point stop processing blocks.

#### Any special way to create or access another created store?

I think been dealing with this for hours. Can't find a solution. Please help!

**Comment by cschuchardt88** [comment]
I spent 18 hours dealing with this, and figured it out. It has to do with the Reference to UInt160.Zero when you use ISerializable. The Serializer uses the same reference with IEnumerable. For Example if you have a class something like this
```CSharp
class MyClass1
        {
            public UInt160 Bug1 { get; set; } = UInt160.Zero; // use new UInt160()
            public UInt256 Bug2 { get; set; } = UInt256.Zero; // use new UInt256()
        }

        class MyClass2 : MyClass1, ISerializable
        {
            public int Size =>
                UInt160.Length +
                UInt256.Length;

            public void Deserialize(ref MemoryReader reader)
            {
                Bug1 = reader.ReadSerializable<UInt160>();
                Bug2 = reader.ReadSerializable<UInt256>();
            }

            public void Serialize(BinaryWriter writer)
            {
                writer.Write(Bug1);
                writer.Write(Bug2);
            }
        }
```

had something to do with Initializing of the Class, the reference to UInt160.Zero or UInt256.Zero. In order to fix u need to do use "new UInt160())"

This is for "f1" variable
![image](https://github.com/neo-project/neo/assets/8141309/76b9b588-e00c-4f46-8412-654edf8f0b1b)

This is for "f2" variable
![image](https://github.com/neo-project/neo/assets/8141309/2998197b-0a20-47cb-b75c-b16f20362b47)

When u try to access "f1" variable again u get the newest Serialize UInt160
![image](https://github.com/neo-project/neo/assets/8141309/38291e60-e805-4506-a05a-242e23f1de10)

This is make the whole NeoSystem unstable and not processing Blocks.

**Comment by shargon** [comment]
Maybe you are creating two stores to the same path?
