### ISSUE TITLE
Get Truly Random number

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2889]
**Summary or problem description**
Using/Hashing Nonce as a seed for a new random number is not ideal. It can be predicted. And you don't get huge numbers, defeats the purpose of using BigInteger. yes Nonce uses Random. but that uses system time as a seed, and since timestamp is on the block that number can be predicted as well. Also using Murmur128 is bad and can be reversed. 

Also anyone can set the transaction Nonce to whatever they want

https://github.com/neo-project/neo/blob/d63eb1da7a99e7459a647dc3355145f5cccc6d74/src/Neo/Wallets/Wallet.cs#L561

[Wikipedia MurmurHash](https://en.wikipedia.org/wiki/MurmurHash)

> Unlike [cryptographic hash functions](https://en.wikipedia.org/wiki/Cryptographic_hash_function), it is not specifically designed to be difficult to reverse by an adversary, making it unsuitable for cryptographic purposes.

**Do you have any solution you want to propose?**
Update The GetRandom to  use a truly random number for BigInteger
https://github.com/neo-project/neo/blob/d63eb1da7a99e7459a647dc3355145f5cccc6d74/src/Neo/SmartContract/ApplicationEngine.Runtime.cs#L304

to

```csharp
Buffer = new BigInteger(RandomNumberGenerator.GetBytes(32), isUnsigned: true).ToByteArray();
```

**Where in the software does this update applies to?**
- Neo library

**Comment by roman-khimov** [comment]
It can't work this way, different nodes would get different numbers and different execution results for the same input resulting in different state.

**Comment by cschuchardt88** [comment]
maybe remove this functionally all together and add a native contract on the blockchain to do random numbers for example in #2888 would that work?

**Comment by Liaojinghui** [comment]
No, that will be precalculatable, attackers does not even need to predict. Current random solution is temporary, we are working on a BLS solution.https://github.com/neo-project/neo/pull/2749 https://github.com/neo-project/neo/pull/2477 https://github.com/neo-project/neo/issues/2456 https://github.com/neo-project/neo-modules/issues/637

**Comment by cschuchardt88** [comment]
@Liaojinghui the sounds of it, they are still going to use nonce but with BLS. But you can still make transaction manually and set the nonce to lets say "ZERO". Wouldn't that defeat the purpose or GetRandom. Users are expecting something made by a random number generator with a decent random algorithm?

**Comment by cschuchardt88** [comment]
@Liaojinghui In new or old implementation? at least it called nonceData, look like it uses the hash with nonce to make a ulong

https://github.com/neo-project/neo/blob/d63eb1da7a99e7459a647dc3355145f5cccc6d74/src/Neo/SmartContract/ApplicationEngine.cs#L167

https://github.com/neo-project/neo/blob/d63eb1da7a99e7459a647dc3355145f5cccc6d74/src/Neo/SmartContract/ApplicationEngine.cs#L172

**Comment by Liaojinghui** [comment]
Its not related to the transaction nonce. random number is sort of related to the tranaction hash, not nonce.
