### ISSUE TITLE
Allow WitnessRules to allow max depth for json

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2904]
**Summary or problem description**
See https://github.com/neo-project/neo/issues/2950 for more details

**Do you have any solution you want to propose?**
Allow FromJson method to allow max depth. What this depth is, who knows.

**Neo Version**
- Neo 3.7.0

**Where in the software does this update applies to?**
- CLI

**Comment by cschuchardt88** [comment]
Also we may want to check to see if `transaction` are effected for `ISerializable`?

Bottom line, witness conditions should have some kind of limit/max depth.

**Comment by roman-khimov** [comment]
Isn't it fixed by #2951?
