### ISSUE TITLE
ContractTransaction和InvocationTransaction有什么区别

### ISSUE THREAD

**Issue by guotie** [neo-project/neo#291]
如题

**Comment by PeterLinX** [comment]
@guotie 
ContractTx is designed to transfer global asset, InvocationTx is designed to transfer contract asset. Also, you can transfer global asset by using Invocation. More info please check the docs.(docs.neo.org)
ContractTx实现了全局资产的转账，InvocationTx实现了合约资产的转账，同时，你也可以使用InvocationTx实现全局资产的转账。更多信息请参考文档（docs.neo.org）

**Comment by guotie** [comment]
thanks.
