### ISSUE TITLE
Neo v3.6.2 plan

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2914]
**Summary or problem description**
~We have a number of known issues that need to be addressed before rolling 3.6 into mainnet (and to have properly functioning testnet). #2910 only has a part of the problem and we need some place to track all the other ones.~
3.6 is running on the mainnet, but it has a number of issues that better be fixed soon.

**Do you have any solution you want to propose?**
~We need a 3.6.1 and I'd say we need it this week.~ `master` currently contains additional changes from #2905, but we need to concentrate on stabilizing the set we have in 3.6.0, so the proposal is to merge the respective PRs into master (as they're now), then branch off of 4e9314d6b33fb8158e4f2527f889a9cbe7377a73 (and corresponding v3.6.0 commits elsewhere, like in modules) and cherry-pick required changes there.

**Modules 3.6.1**
Since neo-project/neo-modules#829 has affected users seriously, neo-modules 3.6.1 were released without corresponding core/cli releases, this version has fixed:
 - https://github.com/neo-project/neo-modules/pull/821
 - https://github.com/neo-project/neo-modules/pull/822 (wasn't intended to, but this one is included)
 - https://github.com/neo-project/neo-modules/issues/829

**v3.6.2**
Given the modules situtation, the next release for every component should be 3.6.2.

Mandatory issues to fix:
 - #2899
 - #2907
 - neo-project/neo#2950
 - ~neo-project/neo-modules#829~ (fixed in modules 3.6.1)

Discussion:
 - ~#2910~ (irrelevant after the mainnet upgrade)
 - ~#2894~ (not worth the delay and resync after the mainnet upgrade)

Related PRs:
- #2948
 - #2901
 - #2913
 - #2916
 - #2951
 - neo-project/neo-modules#828
 - #2912 and neo-project/neo-modules#827
 - ~neo-project/neo-modules#830~ (released with modules 3.6.1)
 - https://github.com/neo-project/neo/pull/2920
 - https://github.com/neo-project/neo-node/pull/903
 - neo-project/neo-modules#838
 - neo-project/neo-vm#514
 - neo-project/neo#2939

Suggestions/opinions/alternatives are welcome. I'll add some comments below to keep these lists clean.

**Comment by roman-khimov** [comment]
The "mandatory" list above is as conservative as it could be, following the "have resynchronization fun" paradigm. It's not final and my proposal is to extend it with:
 * hardfork dependency for things that _change_ behavior, that is NeoToken.UnclaimedGAS and NeoToken.GetAccountState from #2841
 * a simple storage scheme fix for #2894 since we have to resynchronize anyway (it's not critical, but it's very very simple at the same time)

**Comment by steven1227** [comment]
Fully agree on this one.

**Comment by roman-khimov** [comment]
Mainnet is at 3.6 now, which makes 3.6-specific part of #2910 irrelevant (not the underlying problem, of course), removed from the list.

**Comment by roman-khimov** [comment]
Retracting #2894 (unsafe wrt state change, not worth any delay). Let's at least push the main set out the door.

**Comment by roman-khimov** [comment]
Added neo-project/neo-modules#829/neo-project/neo-modules#830

**Comment by roman-khimov** [comment]
Updated in accordance with https://github.com/neo-project/neo-modules/releases/tag/v3.6.1

**Comment by shargon** [comment]
Added https://github.com/neo-project/neo/pull/2920

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo-node/pull/903, Please

**Comment by AnnaShaleva** [comment]
Let's consider the https://github.com/neo-project/neo-modules/pull/838, please. It's related to https://github.com/neo-project/neo-modules/issues/822.

**Comment by roman-khimov** [comment]
Added neo-project/neo-vm#514, can be replaced if doesn't fit for some reason, but the issue needs to be fixed.

**Comment by AnnaShaleva** [comment]
https://github.com/neo-project/neo/pull/2939 should also be added.

**Comment by roman-khimov** [comment]
> #2939 should also be added.

Sure.

**Comment by shargon** [comment]
#2942 should be added in 3.6 2

**Comment by roman-khimov** [comment]
But why? We can deliver the set of changes from the list in a patch release and then deal with these extensions. The idea was to have a quick release fixing the most critical problems. Otherwise I'd say 3.6.2 is in trouble, we're risking destabilizing it with too many changes.

**Comment by shargon** [comment]
> But why? We can deliver the set of changes from the list in a patch release and then deal with these extensions. The idea was to have a quick release fixing the most critical problems. Otherwise I'd say 3.6.2 is in trouble, we're risking destabilizing it with too many changes.

We currently merged some changes that affects hardforks with native contracts, but agree that currently there aren't use it, so we can focus on this, and prioritize it for the next release.

**Comment by shargon** [comment]
@superboyiii Ready to fly

**Comment by Liaojinghui** [comment]
Propose to close this issue since version 3.6.2 is released.

**Comment by shargon** [comment]
Released 3.6.2

**Comment by roman-khimov** [comment]
Huh. I'd do it after I see something in https://github.com/neo-project/neo-node/releases, but OK and it'll be easier with #2944.
