### ISSUE TITLE
Hide NativeUpdateHistory behind hardforks

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo#2915]
**Summary or problem description**
We have `NativeUpdateHistory` mechanism since #2332, but we've never used it. It's not easy to configure it (can be a big table) and it only allows to handle native contract updates. Still, it's directly exposed to node's configuration.

We have hardfork mechanism since #2712 (and funny names for them since #2749). This one is much easier to handle, can adjust any logic and is used quite successfully (can be used even more as #2910 suggests).

**Do you have any solution you want to propose?**
Remove `NativeUpdateHistory` from the node configuration (that's a must to me, it's just confusing now) and maybe use it internally in conjunction with the hardfork mechanism (deploying/updating contracts when some hardfork happens).

**Where in the software does this update applies to?**
- Ledger
- Interops
- Native Contracts

**Comment by shargon** [comment]
But with native update history you can allow a native contract only from block X, with HF you can change the logic, but not the ability to call this native contract

**Comment by roman-khimov** [comment]
The idea is to have it implicitly configured via hardforks. Let's say hardfork X introduces a new contract C, so if we have a configuration with HF_X at H we can generate appropriate NUH that has no contract C at 0, but deploys it at H.

**Comment by roman-khimov** [comment]
The issue is about configuration simplification, the mechanism to update/deploy native contracts has to be present behind the scenes of course. It just needs to be tied to hardfork configuration.

**Comment by vncoelho** [comment]
> NUH that has no contract C at 0, but deploys it at 
What is NUH. I agree with the Scenario. But since I mentioned the recent issue I see this is a version. 

I think that a good feature of the history is the ability to call the previous contract and resync with the past versions, as @shargon mentioned above.
