### ISSUE TITLE
Add JSONPath to StdLib

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2929]
**Summary or problem description**
I think we can benefit a lot from adding `JSONPath` to native contract.

**Do you have any solution you want to propose?**
Add `JSONPath` to `StdLib` the same implementation that is being used in oracle service.

**Neo Version**
- Neo 3.7.0

**Where in the software does this update applies to?**
- CLI

**Comment by Liaojinghui** [comment]
kinda same as regex, not likely will be added to the core.

**Comment by cschuchardt88** [comment]
I do understand the CPU fee thing tho... Can't a contract work just by burning gas and you just put a limit set by the user on the amount of gas?

**Comment by Liaojinghui** [comment]
fees are evaluated by Opcode of neo virtual machines. but complex operations like regex and jsonpath need native methods that can not measured by Opcode. Thus, it is hard for us to precisely set a limit to that.
