### ISSUE TITLE
Using Graphics Card Acceleration

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo#2931]
Is it possible to use graphics card acceleration to speed up offline synchronization?

**Comment by cschuchardt88** [comment]
No the operation is done synchronously and needs to be in order to verify the state of blockchain. Now some things could be sped up like processing the number of transaction in a block for example.

**Comment by chenzhitong** [comment]
I sync offline on a 20-core CPU and it takes 8 hours with less than 30% CPU usage, I think this sync can be speeded up @cschuchardt88

**Comment by RichardBelsum** [comment]
I sync offline on a 20-core CPU and it takes 8 hours with less than 30% CPU usage, I think this sync can be speeded up @cschuchardt88 @Liaojinghui
