### ISSUE TITLE
Error: ip not found with strict mode (Parameter 'ip') | Neo C#

### ISSUE THREAD

**Issue by gabrielantonyxaviour** [neo-project/neo#2936]
**Describe the bug**
I am not trying to deploy a contract from a contract through C# code in Neo using ContractManagement.Deploy function but I am running into this error. I have set the manifest of the contract to be deployed and it's scriptHash before sending the transaction to deploy it. 
To get the manifest, run this command 
`invoke 0x6319361ca66a5b1f0afc7bad289825b87e7d18be getManifest null NL2UNxotZZ3zmTYN8bSuhKDHnceYRnj6NR NL2UNxotZZ3zmTYN8bSuhKDHnceYRnj6NR`.

To view the entire code repository, 
https://github.com/NFTGramOrg/contracts/blob/main/contracts/NFTAccountRegistry/NFTAccountRegistryContract.cs#L157

Contract Deployment
https://testnet.neotube.io/contract/0x6319361ca66a5b1f0afc7bad289825b87e7d18be

**To Reproduce**
1. Open NeoCLI and run this command 
`invoke 0x6319361ca66a5b1f0afc7bad289825b87e7d18be createAccount [{"type":"Hash160","value":"0x9778bcf3c6194081b2f700454793dd0681ec74ca"},{"type":"ByteArray","value":"AQ=="}] <your_address> <your_address>`

**Expected behavior**
A deployed contract returning the scriptHash of the deployment.

**Screenshots**
![image](https://github.com/neo-project/neo/assets/79229998/7cd78a41-cc43-4ab8-919f-3587d4ae0434)
![image](https://github.com/neo-project/neo/assets/79229998/fd99abd0-8786-4344-b109-fad59c603a26)

**Platform:**
 - OS: Windows 11 Pro x64
 - Version neo-cli 3.6

**Comment by shargon** [comment]
You should review your manifest file, the call looks good to me
