### ISSUE TITLE
Is the `end` parameter necessary?

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo#2957]
https://github.com/neo-project/neo/blob/6df83952d01b6c9486814f677fe42a2922ce3ee1/src/Neo/SmartContract/Native/NeoToken.cs#L174C4-L174C4

```C#
var expectEnd = Ledger.CurrentIndex(snapshot) + 1;
if (expectEnd != end) throw new ArgumentOutOfRangeException(nameof(end));
```
The `end` can only be `Ledger.CurrentIndex(snapshot) + 1`, but it still an external argument at get `UnclaimedGas`.

https://github.com/neo-project/neo/blob/6df83952d01b6c9486814f677fe42a2922ce3ee1/src/Neo/SmartContract/Native/NeoToken.cs#L337C86-L337C86

**Comment by Liaojinghui** [comment]
Looks like unnecessary, but i would choice to leave it that way.

**Comment by Liaojinghui** [comment]
Will close this issue since we will not do anything about it.

**Comment by roman-khimov** [comment]
This was discussed in #2841 and #2900. It's kept for compatibility. We can introduce an additional `unclaimedGas/1`, but I doubt it's a priority for now.
