### ISSUE TITLE
Create a Pull Request Template

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2960]
**Summary or problem description**
We must ensure that PRs clearly describe the problem being solved and the solution.
Related: https://github.com/neo-project/neo/issues/2955

**Do you have any solution you want to propose?**
Use a PR template to ensure PRs have the required information before being evaluated by the team.

**Comment by Liaojinghui** [comment]
please take a look at the draft. we have suspended adding new prs before we create the monorepo, but we can discuss it here:
```markdown
# Pull Request Template

## Problem Statement
<!-- Briefly describe the problem this PR is aiming to solve. -->

## Solution Description
<!-- Clearly and concisely describe the solution you're proposing. -->

## Dependencies
<!-- List any PRs or external factors this PR depends on, if any. -->

## Impact on the Ecosystem
<!-- Discuss how this PR will affect the broader ecosystem. Will it require changes from other developers? -->

## Instructions for Reviewers
<!-- Provide any special instructions or things reviewers should keep in mind while reviewing the code. -->

### Testing Guidelines
<!-- If applicable, provide guidelines on how to test the changes made by this PR. -->

### Checklist
<!-- Reviewers can use this section as a checklist while reviewing the PR. -->
- [ ] Code follows project's coding standards
- [ ] Proper comments/documentation included
- [ ] Impact on the ecosystem is clearly understood and documented
- [ ] All tests pass (if applicable)

## Additional Notes
<!-- Include any additional information that might be helpful for reviewers or future references. -->

## Screenshots or Demo (if applicable)
<!-- If your changes have a visual component or affect the UI, include screenshots or a short demo video. -->
```

**Comment by cschuchardt88** [comment]
We should also update `.editorconfig` to help with these code standards. That's what the file is for. Copy and pasting the File header for example is annoying. In `neo-express` we are using https://github.com/neo-project/neo-express/blob/master/.editorconfig

**Comment by roman-khimov** [comment]
It can be an org-wide template, btw. Just needs to be placed into `.github` repo.

**Comment by Liaojinghui** [comment]
> It can be an org-wide template, btw. Just needs to be placed into `.github` repo.

Yep, i think @roman-khimov can add them directly when you create the monorepo.
