### ISSUE TITLE
Transactions Doesnt work

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2961]
**Describe the bug**
When I send a transaction with a special script with `PushInt32` it crashes VM, but when I send on the network. It doesn't register and take the GAS. Doesn't get added to a block even tho it should be.

**To Reproduce**
Send a signed valid transaction with script
`Av6VWB8RY48Lq9oWJnUDJya70r+Y+OKdaaWvxpTTg/ZtiBEMFHJER2Cvl1YJCEOdyKCSuwdX+RuVDBRyREdgr5dWCQhDncigkrsHV/kblRPAHwwIdHJhbnNmZXIMFM924ovQBixKR47jVWEBExnzz6TSQWJ9W1JA`

```csharp
using var sb = new ScriptBuilder();
sb.Emit(OpCode.PUSHINT32, UInt256.Parse("0x6df683d394c6afa5699de2f898bfd2bb262703752616daab0b8f63111f5895fe").ToArray());
sb.Emit(OpCode.NEWBUFFER);
sb.EmitDynamicCall(NativeContract.GAS.Hash, "transfer", CallFlags.All, _account.ScriptHash, _account.ScriptHash, 1);
sb.Emit(OpCode.RET);

Transaction tx = new()
{
    Version = 0,
    Nonce = (uint)Random.Shared.Next(int.MaxValue),
    Script = sb.ToArray(), 
    SystemFee = 0_09456903,
    NetworkFee = 0_00543097,
    ValidUntilBlock = NativeContract.Ledger.CurrentIndex(_ns.StoreView) + _ns.Settings.MaxValidUntilBlockIncrement,
    Signers = new[] { new Signer() { Account = _account.ScriptHash, Scopes = WitnessScope.Global } },
    Attributes = Array.Empty<TransactionAttribute>(),
};

tx.Witnesses = new[]
{
    new Witness()
    {
        InvocationScript = new byte[] { ((byte)OpCode.PUSHDATA1), 64 }.Concat(tx.Sign(_account.GetKey(), _ns.Settings.Network)).ToArray(),
        VerificationScript = Contract.CreateSignatureContract(_account.GetKey().PublicKey).Script.ToArray(),
    }
};
_ns.LocalNode.Tell(new SendDirectly { Inventory = tx });
```

**Expected behavior**
If should add a valid signed transaction to a block.

**Platform:**
 - Version 3.6.0

**(Optional) Additional context**

```
   at Neo.VM.ExecutionEngine.ExecuteStoreToSlot(Slot slot, Int32 index)
   at Neo.VM.ExecutionEngine.ExecuteInstruction(Instruction instruction)
   at Neo.VM.ExecutionEngine.ExecuteNext()
```

```
   at Neo.VM.ExecutionEngine.ExecuteStoreToSlot(Slot slot, Int32 index) in Neo.VM\ExecutionEngine.cs:line 2036
   at Neo.VM.ExecutionEngine.ExecuteInstruction(Instruction instruction) in Neo.VM\ExecutionEngine.cs:line 825
   at Neo.VM.ExecutionEngine.ExecuteNext() in Neo.VM\ExecutionEngine.cs:line 2011
```

**Comment by roman-khimov** [comment]
This script fails the correctness check (#2263/#733/#2030) and therefore can't be included in a block.
```
NEO-GO-VM > loadbase64 Av6VWB8RY48Lq9oWJnUDJya70r+Y+OKdaaWvxpTTg/ZtiBEMFHJER2Cvl1YJCEOdyKCSuwdX+RuVDBRyREdgr5dWCQhDncigkrsHV/kblRPAHwwIdHJhbnNmZXIMFM924ovQBixKR47jVWEBExnzz6TSQWJ9W1JA
READY: loaded 120 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE         PARAMETER
0        PUSHINT32      525899262 (fe95581f)    <<
5        PUSH1          
6        STSFLD3        
7        Opcode(143)    ERROR: incorrect opcode Opcode(143)

NEO-GO-VM 0 > run
Error: at instruction 6 (STSFLD3): runtime error: index out of range [3] with length 0
```

**Comment by cschuchardt88** [comment]
Ya but this for the Transaction script. Shouldn't it still be added to block? And have it crash on the blockchain? As FAULT?

I haven't had this problem with other invalid opcodes when adding to transaction script. Normally they just crash in vm on the blockchain. If I'm sending valid signed transaction.

**Comment by lock9** [comment]
How is it possible that the transaction is not included in the block but the fees are charged anyway? Is that even possible?

**Comment by roman-khimov** [comment]
It won't be added into block (and no fees will be deducted), that's why I'm referencing #2263, it went beyond #733/#2030 and added checks for _all_ scripts, including transaction entry scripts. So, it works as intended.

**Comment by cschuchardt88** [comment]
@roman-khimov thx for information.
