### ISSUE TITLE
Add Logs for CallFlags.ReadOnly

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2963]
**Summary or problem description**
Currently you can not emit logs (`Runtime.Log`) with `[Safe]` (`CallFlags.ReadOnly`). I don't understand the reason behind it. However we should allow this to come through. One good reason is for debugging. Would hate to have to remove `[Safe]` from all my contract's; just to debug something and than remember to add it back after testing or debugging.

**Neo Version**
- Neo 3.6.0

**Where in the software does this update applies to?**
- Compiler
- CLI
- VM

**Comment by Liaojinghui** [comment]
I would suggest to add `debug feature` for contracts, such that we can have tools enabled in the testnet but disabled for the mainnet.

**Comment by shargon** [comment]
The logs checks for storage permissions and safe does not have this permission.

**Comment by roman-khimov** [comment]
This was discussed once upon a time in #2783.

**Comment by Liaojinghui** [comment]
> This was discussed once upon a time in #2783.

 This one i remember.

**Comment by shargon** [comment]
We can close this if is solved, now you can use assert with message in `Safe` methods.

**Comment by lock9** [comment]
@shargon how can we solve this issue here:
https://github.com/neo-project/neo-express/issues/309

We need to be able to view the logs. Any alternative?

**Comment by cschuchardt88** [comment]
@lock9 
PR https://github.com/neo-project/neo-modules/pull/842

**Comment by lock9** [comment]
So, we don't need this? Or the log feature won't work on safe methods? 🤔

**Comment by cschuchardt88** [comment]
Won't work on safe methods, Unless you use 

```csharp
ExecutionEngine.Assert(true, "Hello World!");
```

Is what they are arguing. However this shouldn't be the case.


@shargon so _above_ code emits `Runtime.Log`?

**Comment by shargon** [comment]
No, it will fault the execution, and the message will be in the fault Exception.

**Comment by cschuchardt88** [comment]
Well can we have this than?
>I would suggest to add debug feature for contracts, such that we can have tools enabled in the testnet but disabled for the mainnet. But need to be carefully designed to ensure behavior consistancy cross networks.

Its is impossible to debug `[Safe]` contracts. `neo-express` has same behavior. Which lies the problem.

**Comment by shargon** [comment]
I think that neo-express show the exception if it happens

**Comment by cschuchardt88** [comment]
Yes but we still have this issue https://github.com/neo-project/neo-express/issues/309, which is my reason behind doing this issue.

**Comment by lock9** [comment]
What alternatives do we have to return the logs @shargon ? It's only for development mode. Can we do this in a less intrusive way? like using a plugin?

**Comment by shargon** [comment]
No logs alternative in Safe mode...

**Comment by cschuchardt88** [comment]
@shargon one thing you can do is create a custom `ApplicationEngineProvider` and do it that way. And `blockchain-toolkit-library` has one or is it `neo-express`; i forget which one.

**Comment by shargon** [comment]
Why use a different one in neo-express, it will show you things that can't be replicated in the real network.

**Comment by cschuchardt88** [comment]
Well i don't want to allow `logs` in `neo-express` because when they deploy to mainnet or testnet with `log` in `safe` methods will error.

**Comment by lock9** [comment]
> No logs alternative in Safe mode...

Why do you want to make me cry?

I worry that it can be intrusive to update the contract manifest to remove safe from methods. 

>Well i don't want to allow logs in neo-express because when they deploy to mainnet or testnet with log in safe methods will error.

Afaik, compilers work on debug and release mode. We could update the manifest to make it non-safe if they compile it in debug mode. I'm not sure if this is the best solution but it would work

**Comment by cschuchardt88** [comment]
You can alway create a `neo-express` xunit test. But it does require `C#`.

**Comment by lock9** [comment]
This will need to be handled by the compilers / tools. I think we can close this issue.

**Comment by Jim8y** [comment]
Close this issue since we will not implement this.

**Comment by cschuchardt88** [comment]
@Jim8y we did implement it.

**Comment by cschuchardt88** [comment]
@Jim8y This was implemented. `RPC` emits `LogEventArgs` in `ApplicationLog` plugin.
