### ISSUE TITLE
.editorconfig file header

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2964]
**Summary or problem description**
Can you add `file_header_template ` to the `.editorconfig` file. it's annoying to have to remember to copy and paste the header for each `*.cs` file. It slows me down and I'm sure others too.

**Do you have any solution you want to propose?**
```ini
file_header_template = Copyright (C) 2015-2023 The Neo Project.\n\n{fileName} file belongs to neo-project and is free\nsoftware distributed under the MIT software license, see the\naccompanying file LICENSE in the main directory of the\nrepository or http://www.opensource.org/licenses/mit-license.php\nfor more details.\n\nRedistribution and use in source and binary forms with or without\nmodifications are permitted.
```

**Where in the software does this update applies to?**
- CLI
- Plugins
- VM

**Comment by Liaojinghui** [comment]
Not now, after the mono please

**Comment by Jim8y** [comment]
close as finished
