### ISSUE TITLE
NativeContract prices inconsistent with mainnet/testnet

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#2966]
**Summary or problem description**
See https://github.com/neo-project/neo-express/issues/332

**Do you have any solution you want to propose?**
Update these native contracts with current prices of mainnet/testnet to be consistent for privatenets by default.

```
neoxp policy get
             GasPerBlock: 500000000 (5 GAS)
    MinimumDeploymentFee: 1000000000 (10 GAS)
CandidateRegistrationFee: 100000000000 (1000 GAS)
        OracleRequestFee: 50000000 (0.5 GAS)
       NetworkFeePerByte: 1000 (0.00001 GAS)
        StorageFeeFactor: 100000
      ExecutionFeeFactor: 30
```

```
neoxp policy get -r TestNet
             GasPerBlock: 500000000 (5 GAS)
    MinimumDeploymentFee: 1000000000 (10 GAS)
CandidateRegistrationFee: 100000000000 (1000 GAS)
        OracleRequestFee: 10000000 (0.1 GAS)
       NetworkFeePerByte: 100 (0.000001 GAS)
        StorageFeeFactor: 10000
      ExecutionFeeFactor: 3
```

```
neoxp policy get -r MainNet
             GasPerBlock: 500000000 (5 GAS)
    MinimumDeploymentFee: 1000000000 (10 GAS)
CandidateRegistrationFee: 100000000000 (1000 GAS)
        OracleRequestFee: 10000000 (0.1 GAS)
       NetworkFeePerByte: 100 (0.000001 GAS)
        StorageFeeFactor: 10000
      ExecutionFeeFactor: 3
```

**Neo Version**
- Neo 3.6.0

**Where in the software does this update applies to?**
- CLI

**Comment by superboyiii** [comment]
The Neo Community Councils reduced some of these fees by multi-signature voting both on testnet and mainnet. They can be set. For example: see https://github.com/neo-project/neo/blob/1ae6a13f8a269d8aecbf0f686330d56db72accfc/src/Neo/SmartContract/Native/PolicyContract.cs#L150
NeoExpress is a local privatenet, so all params will be default value. But of course, these params can be set as well by councils' multi-signautre.

**Comment by cschuchardt88** [comment]
@superboyiii 
true, But shouldn't it be consistent now since prices haven't changed for sometime? Otherwise its extra work to have to invoke VMs. Plus `neo-cli` node does this as well, on private networks.

**Comment by superboyiii** [comment]
> @superboyiii true, But shouldn't it be consistent now since prices haven't changed for sometime? Otherwise its extra work to have to invoke VMs. Plus `neo-cli` node does this as well, on private networks.

Hmn... that means native blockchain is invoking external exchanges' price and which exchange or api is credible？Seems no way to do this, so it's still in blockchain world, but if the price of GAS has violent fluctuations, the councils may modify these again.

**Comment by lock9** [comment]
Hello @cschuchardt88 ,
I believe this is not necessary. It's easier for Neo Express to use the sync command during setup.

**Comment by cschuchardt88** [comment]
@lock9 https://github.com/neo-project/neo-express/pull/335
