### ISSUE TITLE
Adding Voter Registration Period

### ISSUE THREAD

**Issue by toghrulmaharram** [neo-project/neo#297]
**Problem**
The currently proposed implementation forces the nodes to look through the transaction history of the NEO voted with to make sure that those NEO were not being double-voted with during the same voting period.

**Solution**
The problem could be circumvented with a modified voting transaction type and an introduction of a voter registration period. Assuming that the voting is going to be held every `n blocks`, the platform could hardcode block deadlines which would let the nodes exclude the voting transactions that include NEO added to the wallet address after the expiration of the deadline for a given voting period. The aforementioned implementation would require an introduction of a new command - `gettransactionindex`, which would return a block `index` after receiving a `txid` parameter. The voting transaction type will also have to be modified to include a TxOut to the voter's wallet address and could be added to the mempool.

**Comment by Edgegasm** [comment]
I like it. Gives people plenty of time to register their votes for the next round, and ensures that nodes can easily exclude votes submitted past the deadline.

Question: Should we have a mechanism in place for snap elections?

**Comment by toghrulmaharramov** [comment]
@Edgegasm Should be compatible with snap elections, though I'm not a big fan of holding snap elections in general.

**Comment by shargon** [comment]
Lock neo until finish the vote?

**Comment by lock9** [comment]
@shargon I'm afraid people are not willing to lock their neo. What is the team opinion about this? 
@toghrulmaharramov Thank you for all your good suggestions. You write things in a very clear way, this helps a lot.

We need to rethink this using our new native contracts. Any ideas?

**Comment by vncoelho** [comment]
@toghrulmaharramov is children of babylon, an important NEO contributor of the old times.

**Comment by lock9** [comment]
My 2 cents: 
Close it.
Reasons: 
- It's too old
- It's not relevant anymore
- I don't think locking the Neo is going to make them happy or solve governance issues

**Comment by roman-khimov** [comment]
Not relevant for N3, yes.
