### ISSUE TITLE
Add templates to the .github repository inside the Neo organization

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#2975]
**Summary or problem description**
Some projects are missing the PR and Issue templates. 

**Do you have any solution you want to propose?**
Use the .github repository inside this organization and add the templates to it. Originally suggested by @roman-khimov (I think?).

Related to #2960 and https://github.com/neo-project/neo-express/issues/295

Here is one being used by NSPCC:
https://github.com/nspcc-dev/.github

I was unable to find the official docs. I found a post in a blog about it:
https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/

**Comment by roman-khimov** [comment]
Like https://github.com/neo-project/.github?

**Comment by lock9** [comment]
Lol, really? Why I can't find it in the list of repositories 😂

**Comment by Liaojinghui** [comment]
> Lol, really? Why I can't find it in the list of repositories 😂

Wow, I tought roman was giving an example,,,,,,its a REAL repo,,,,,

**Comment by shargon** [comment]
Done #3081

**Comment by cschuchardt88** [comment]
You guys didn't know that? 😮‍💨

**Comment by shargon** [comment]
Lol, I miss "in the organization" hahaha, my fault
