### ISSUE TITLE
NEO2.7.5的源码放上来呀，捂着不发，是准备？

### ISSUE THREAD

**Issue by sctxm** [neo-project/neo#298]

**Comment by erikzhang** [comment]
The latest version is 2.7.6, and you can get that version of the code in the master branch.

**Comment by sctxm** [comment]
Thanks, I try again.

**Comment by sctxm** [comment]
Hi. The EvaluationStack in Neo.SmartContract.ApplicationEngine is not defined. Unable to compile after downloading the source code!
