### ISSUE TITLE
Simulate and evaluate how number of consensus nodes can be used to improve performance and security

### ISSUE THREAD

**Issue by lerider** [neo-project/neo#30]
Issue background:
We want to avoid non-honest consortiums to gain majority as consensus nodes, which could be a bit tricky if the threshold for being a consensus node is the weighted average of mid-50 %. 

We want NEO consortium to control the consensus nodes, and if number of total consensus node is set after voting (all nominees above weighted average of mid-50%), then it can be tricky for NEO consortium to know how many nominees they should spread out their votes on.

To investigate:
1. If total number of consensus nodes is decided after voting, is there a risk for smaller consortiums to gain majority consensus nodes if NEO consortium spread out on too few nominees?

2. If shareholders decide total number of consensus nodes before voting instead, would that make it easier for NEO consortium to guarantee that they have 2/3 of consensus nodes?

3. If the answer on question 2 is yes, would that reduce number of iterations needed to reach consensus and speed up the block generation?

4. If the answer on question 2 and 3 is yes, would it be an advantage or disadvantage for the NEO consortium to have an algorithm that decides number of votes that would guarantee a seat as consensus node? 
For example 150 000 votes, then he is guaranteed a seat and can't be voted on again. This way the number of seats can't be manipulated by attacks and major share holders know how to split their votes

**Comment by lerider** [comment]
[simulation files.zip](https://github.com/neo-project/neo/files/1156035/simulation.files.zip)

**Comment by lerider** [comment]
[sim_output.zip](https://github.com/neo-project/neo/files/1157901/sim_output.zip)

**Comment by erikzhang** [comment]
Hi, can you port this issue to https://github.com/neo-project/proposals as a NEP(NEO Enhancement Proposal)?
