### ISSUE TITLE
Remove APPCALL and invoke contracts through SYSCALL

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#301]
Currently, the contract invocation is done through the appcall instruction (and the corresponding stack isolation instruction), and NeoVM will directly look for the target contract. This is very unreasonable for NeoVM, because the list of smart contracts on the blockchain should not be directly visible to NeoVM.
We need to create a new API to invoke contracts in a SYSCALL and discard the original APPCALL instructions.
If we do this, there will be two additional benefits:
- We do not need to do extra work to implement stack isolation, because invoking a new contract in SYSCALL will start a new virtual machine.
- We can easily implement a new type of smart contract: native contracts. The native contract is not run in a virtual machine, it is a contract built into the block chain code. But they can expose their script hashes to other contracts so that other contracts can invoke them. In a SYSCALL it is easy to determine whether the contract being invoked is a normal contract or a native contract, and use the right environment to start it. This is not done with the original APPCALL.
One scenario for native contracts is that in the future we can use the native contract to implement **neo** and **gas** (or all global assets) as NEP-5 tokens so that we can use a unified approach to sending and receiving assets in smart contracts.

To implement this proposal, we need to:
- Remove the opcodes `APPCALL` and `TAILCALL`
- Remove the stack isolation opcodes
- Add new SYSCALL: `System.Contract.Invoke`
- Start a new VM in `System.Contract.Invoke` so that we do not need stack isolation any more
- The new `System.Contract.Invoke` will no longer support static invocations, because the restrictions on dynamic invocations will be implemented by the feature manifest.

**Comment by ThomasLobker** [comment]
> One scenario for native contracts is that in the future we can use the native contract to implement neo and gas (or all global assets) as NEP-5 tokens so that we can use a unified approach to sending and receiving assets in smart contracts.

In contrast to NEP-5, system assets are UTXO based. In my opinion UTXO is more scalable and more robust than the NEP-5 account/balance model and we should definitely keep this.

**Comment by erikzhang** [comment]
> In contrast to NEP-5, system assets are UTXO based. In my opinion UTXO is more scalable and more robust than the NEP-5 account/balance model and we should definitely keep this.

In fact we can implement UTXO in contracts as well.

**Comment by erikzhang** [comment]
> I don't like this solution. Create a new VM could be more expensive. And every contract have at less 2 VM

How much performance loss is caused by starting multiple VMs, it requires testing. If the test results find that it does seriously affect performance, we can also let the new SYSCALL imitate the original APPCALL behavior and load the script in the same VM.

**Comment by shargon** [comment]
Can be closed?
