### ISSUE TITLE
Native Contract

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#303]
The native contract is not run in a virtual machine, it is a contract built into the block chain code. But they can expose their script hashes to other contracts so that other contracts can invoke them.

Each native contract contains only one instruction:
```
SYSCALL Neo.Native.XXX
```
where `Neo.Native.XXX` is a SYSCALL that actually implements the functionality of this native contract.

The script hash of the native contract can be calculated from the instruction above. And even if the contract functions are upgraded, the hash of the native contract will not change.

One scenario for native contracts is that in the future we can use the native contract to implement **neo** and **gas** (or all global assets) as NEP-5 tokens so that we can use a unified approach to sending and receiving assets in smart contracts.

**Comment by igormcoelho** [comment]
I fully agree that Native contracts will be the future, and mainly important ones such as NEP-5 NEO/GAS. Erik, I got to think that it would be nice if all contracts had an unique identifying name, so even after migrations, this name would never change! Using this feature, we could provide `SYSCALL_BY_NAME  contract_name`, that would work for both interpreted and native contracts. This way, we could invoke NEP-5 NEO operations just like that:  PUSH origin, PUSH destination, PUSH value, SYSCALL NEO. So, the scripthash won't be necessary, and its purpose will be kept intact as representing the hash of the script. Like you said, the Native contract will change the code, but the name will be kept the same. I believe this has two advantages:
1) Current contracts in the network could have the name set as the equivalent scripthash bytearray (so SYSCALL and SYSCALL_BY_NAME would have the same behavior, and could even be the same operation)
2) Migration will enforce contract name from now on, so people will be desincentived to create general purpose contracts, only specific ones, for other people to use their contracts in a SYSCALL using fixed names. Migration will only help fixing bugs, and keeping backwards compatibility, what is good.

In the future, it would also be nice to allow people to submit new code, and even consensus codes could be changed this way... they run a general code that requires enough signatures to change the native codes to a new one, in an autonomous way.

**Comment by vncoelho** [comment]
@erikzhang, while @igormcoelho has been in favor of `op_eval` there has been an urge for specific designed cryptographic accounts.

1. I see the the first point as an important point to the Neo ecosystem because it will proportionate us specific use cases. In particular, we need this for some of our applications.
1. The second point is related to quantum security and the possibility of each of us to choose the way in want to have our account address encrypted.

**Comment by lightszero** [comment]
@igormcoelho 
as eric said.
not Neo.Native.OpName => scripthash.
but  hash(asm[syscall Neo.Native.OpName])=>scripthash.

**Comment by igormcoelho** [comment]
@lightszero we need to clarify this, I don't think he meant `hash(asm[syscall Neo.Native.OpName])=>scripthash`, but yes: `hash(Neo.Native.OpName) => scripthash` :smile: 

Anyway, we need to clarify another thing:
We do:
`SYSCALL Neo.Native.OpName`
or
`APPCALL hash`
?

APPCALL makes more sense to me, since it behaves as a `contract`, not as a `function`.

@erikzhang help us :)

**Comment by lightszero** [comment]
@igormcoelho 
ASM【SYSCALL Neo.Native.XXX】  will not be changed
use syscall in implement

when user use it，still use “appcall hash”

**Comment by igormcoelho** [comment]
Ok, so if I understood correctly, both will execute the exact same thing:
`SYSCALL Neo.Native.XXX`
and
`APPCALL scripthash(SYSCALL Neo.Native.XXX)`

**Comment by Tommo-L** [comment]
Sorry, I don't quite understand the difference between the native contract and the interoperable services if only `neo` and `gas` token to use it.   Is it possible for developer to submit the native contract?

**Comment by erikzhang** [comment]
> Is it possible for developer to submit the native contract?

No.
