### ISSUE TITLE
System_Runtime_CurrentSigners `LInq` ArgumentNullException in ApplicationEngine

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3034]
**Describe the bug**

**`Please review and look/read carefully!!!`**

When invoking `ApplicationEngine.System_Runtime_CurrentSigners` in transaction script you get `System.Linq.ThrowHelper.ThrowArgumentNullException`. This goes for anywhere I _believe_.  As you _see below_ `AllowedContracts`, `AllowedGroups` and `Rules` is **NOT** initialized that all. Initializing these arrays _(global variables)_ will fix the problem _(`Array.Empty<>()`)_. Plus i dont think `{Name = "ArgumentNullException" FullName = "System.ArgumentNullException"}`, `{"Value cannot be null. (Parameter 'source')"}` is very helpful with debugging, for what is going on. I even supplied the transaction on this one.

### Public Class Signer
```csharp
public UInt160[] AllowedContracts;
public ECPoint[] AllowedGroups;
public WitnessRule[] Rules;
```

```csharp
VM.Types.StackItem IInteroperable.ToStackItem(ReferenceCounter referenceCounter)
{
    return new VM.Types.Array(referenceCounter, new VM.Types.StackItem[]
    {
        Account.ToArray(),
        (byte)Scopes,
        new VM.Types.Array(referenceCounter, AllowedContracts.Select(u => new VM.Types.ByteString(u.ToArray()))), // crash
        new VM.Types.Array(referenceCounter, AllowedGroups.Select(u => new VM.Types.ByteString(u.ToArray()))), // crash
        new VM.Types.Array(referenceCounter, Rules.Select(u => u.ToStackItem(referenceCounter))) // crash
    });
}
```

**To Reproduce**
```csharp
using var sb = new ScriptBuilder();
sb.EmitSysCall(ApplicationEngine.System_Runtime_CurrentSigners);

Transaction tx = new()
{
    Version = 0,
    Nonce = 0,
    Script = sb.ToArray(),
    SystemFee = 0_07417998L,
    NetworkFee = 0_00138652L,
    ValidUntilBlock = NativeContract.Ledger.CurrentIndex(neoSystem.StoreView) + neoSystem.Settings.MaxValidUntilBlockIncrement,
    Signers = new[]
    {
        new Signer() { Account = UInt160.Parse("0x889ca095e38a790d6c15ff78ec06175077b448ff"), Scopes = WitnessScope.CalledByEntry },
    },
    Attributes = Array.Empty<TransactionAttribute>(),
};

tx.Witnesses = new[]
{
    new Witness()
    {
        InvocationScript = new byte[] { ((byte)OpCode.PUSHDATA1), 0x40 /* 64 */ }.Concat(tx.Sign(ppk, ProtocolSettings.Default.Network)).ToArray(),
        VerificationScript = Contract.CreateSignatureContract(ppk.PublicKey).Script,
    },
};

using var engine = ApplicationEngine.Run(sb.ToArray(), neoSystem.StoreView, tx, settings: neoSystem.Settings, gas: 0_07417998L);

Console.WriteLine(engine.State);
```

**Expected behavior**
Return empty array

**Screenshots**

**Platform:**
 - OS: Win 11
 - Version 3.6.2

**(Optional) Additional context**
### CALL STACK
```
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Neo.Network.P2P.Payloads.Signer.Neo.SmartContract.IInteroperable.ToStackItem(ReferenceCounter referenceCounter)
   at Neo.SmartContract.ApplicationEngine.Convert(Object value)
   at Neo.SmartContract.ApplicationEngine.<Convert>b__95_0(Object p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Neo.VM.Types.Array..ctor(ReferenceCounter referenceCounter, IEnumerable`1 items)
   at Neo.SmartContract.ApplicationEngine.Convert(Object value)
   at Neo.SmartContract.ApplicationEngine.OnSysCall(InteropDescriptor descriptor)
   at Neo.SmartContract.ApplicationEngine.OnSysCall(UInt32 method)
   at Neo.VM.ExecutionEngine.ExecuteInstruction(Instruction instruction)
   at **Neo.VM.ExecutionEngine.ExecuteNext()**
```

**Comment by roman-khimov** [comment]
IIUC this never happens for real (deserialized) transactions, so not that big of an issue:
https://github.com/neo-project/neo/blob/30ac705e518524897dfe6932b3089901587879ab/src/Neo/Network/P2P/Payloads/Signer.cs#L75-L83

But maybe worth fixing for tests.

**Comment by cschuchardt88** [comment]
But what would happen if some sent a dynamic script calling it in a valid transaction. I'll try it now and see if it crashes the network....

**Comment by vncoelho** [comment]
@cschuchardt88, congratulations for the recent finding and dedication to the project.

I saw your comment but later you deleted it. It was about a dynamic script.
Were you able to verify something related to that?

**Comment by cschuchardt88** [comment]
No, all the information is in the 1st comment. It just crashes the `vm`.

**Comment by shargon** [comment]
It will be solved changing neo to nullable

**Comment by cschuchardt88** [comment]
What is the problem is. If you call `syscall` `CurrentSigners`. It fails in dynamic scripts. Because the transaction isn't being deserialized soon enough even though you are passing in a transaction.

**Comment by cschuchardt88** [comment]
@shargon @Jim8y 

This needs to be fixed take for example:
```
neo> invoke 0x598afeea6a97e87f69d10d55047f459cf6917656 test
Invoking script with: 'wh8MBWRyYWluDBRWdpH2nEV/BFUN0Wl/6Jdq6v6KWUFifVtS'
VM State: FAULT
Gas Consumed: 0.0098655
Result Stack: []
Error: Value cannot be null. (Parameter 'source')
```
```csharp
[DisplayName(nameof(TestContract))]
[ContractPermission("*", "*")]
public class TestContract : SmartContract
{
    [Syscall("System.Runtime.CurrentSigners")]
    public static extern Signer[] GetSigners();


    public static void Test()
    {
        try
        {
            var signers = GetSigners();
        }
        catch
        {
        }
    }
}
```

**Comment by vncoelho** [comment]
> @shargon @Jim8y 
> 
> This needs to be fixed take for example:
> ```
> neo> invoke 0x598afeea6a97e87f69d10d55047f459cf6917656 test
> Invoking script with: 'wh8MBWRyYWluDBRWdpH2nEV/BFUN0Wl/6Jdq6v6KWUFifVtS'
> VM State: FAULT
> Gas Consumed: 0.0098655
> Result Stack: []
> Error: Value cannot be null. (Parameter 'source')
> ```
> ```csharp
> [DisplayName(nameof(TestContract))]
> [ContractPermission("*", "*")]
> public class TestContract : SmartContract
> {
>     [Syscall("System.Runtime.CurrentSigners")]
>     public static extern Signer[] GetSigners();
> 
> 
>     public static void Test()
>     {
>         try
>         {
>             var signers = GetSigners();
>         }
>         catch
>         {
>         }
>     }
> }
> ```

If this tx @cschuchardt88  is failing, perhaps it need a HF.

**Comment by cschuchardt88** [comment]
@vncoelho 

No its just the `Transaction` isn't getting passed as a parameter to the `ApplicationEngine` only the `script` is or `Signers` are `null`; for invoking contract methods in the `CLI`.

**Comment by vncoelho** [comment]
> @vncoelho 
> 
> No its just the `Transaction` isn't getting passed as a parameter to the `ApplicationEngine` only the `script` is or `Signers` are `null`; for invoking contract methods in the `CLI`.

I see, I will reproduce here.
