### ISSUE TITLE
Can't use commands that need to open wallet via JSON-RPC

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#305]
Can't use commands that need to open wallet via JSON-RPC, like `getbalance`、`dumpprivkey`.
I guess because there is no value given to "wallet" in the following code.

https://github.com/neo-project/neo/blob/18be40a79585a41b19ac14cdb21d382576b5f9e6/neo/Network/RPC/RpcServer.cs#L35-L39

https://github.com/neo-project/neo/blob/18be40a79585a41b19ac14cdb21d382576b5f9e6/neo/NeoSystem.cs#L57-L61

**Comment by f27d** [comment]
This works in neo-cli because of the extension

https://github.com/neo-project/neo-cli/blob/ed2e1a25be070c7fd9bc2998df3d6e1081b28b1e/neo-cli/Network/RPC/RpcServerWithWallet.cs
which extends Rpcserver.

**Comment by daiduongtruong** [comment]
Ý ý như khi ở iii uh you go lj you going b please clarify
Hi I'm at bi in full g vpk

On Mon, Jul 9, 2018, 7:47 PM f27d <notifications@github.com> wrote:xplllew
it on GitHub
<https://github.com/neo-project/neo/issues/305#issuecomment-403452122>, or mute
the thread

**Comment by wy** [comment]
Can this be closed now @erikzhang with your fix?
