### ISSUE TITLE
Neo.Cli Publish missing target framework

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3052]
There is no Target Framework property on the new migrated Neo.Cli folder.
In this sense I could be done manually `dotnet publish -c Release -f net7.0`

Or should we just use `dotnet build` ?

**Comment by vncoelho** [comment]
Maybe add something like the Neo.VM `<TargetFrameworks>netstandard2.1;net7.0</TargetFrameworks>`

**Comment by cschuchardt88** [comment]
`Directory.Build.props` does this for us. run `dotnet` cli on the solution file or in `root` directory of repo.

**Comment by vncoelho** [comment]
I tried and got the same error

**Comment by vncoelho** [comment]
I am using a dockerfile

```
WORKDIR /opt/neoLib/src/Neo.CLI
RUN dotnet publish -c Release -f net7.0
WORKDIR /
```

**Comment by cschuchardt88** [comment]
But that error is normal, because of the way we configured the `Directory.Build.props`. You have to put the target framework, in that case because we support `dotnet standard 2.1` and `dotnet 7.0`.

```
The current project targets multiple frameworks, you must specify the framework for the published application.
```
You can do `publish` like you been.

**OR**

In the root i do:
```
> dotnet build .\src\neo.cli\neo.cli.csproj --output ./bin
```

**Comment by cschuchardt88** [comment]
Also you have look at #3018 for publishing

**Comment by vncoelho** [comment]
Sure, thus everything is correct and expected. Thanks,
