### ISSUE TITLE
Block halt at 4131754 for reworks from snapshot

### ISSUE THREAD

**Issue by jun0tpyrc** [neo-project/neo#3053]
using the usual full snapshot to rework for nodes multiple times , things seem still stuck at block 4131754

vesrion: ghcr.io/axlabs/neo3-privatenet-docker/neo-cli-with-plugins:neo-node-3.6.2

**Comment by cschuchardt88** [comment]
unknown without configurations, node height, and other information. Please go into detail. Have you tried the github for the image?

**Comment by jun0tpyrc** [comment]
after reaching the specific heights 
it looks nodes are keep doing something like
```
2024/01/04-01:43:57.671741 140383501207360 Recovering log #648005
2024/01/04-01:43:57.685742 140383501207360 Level-0 table #648829: started
2024/01/04-01:43:57.704626 140383501207360 Level-0 table #648829: 1016901 bytes OK
2024/01/04-01:43:57.712526 140383501207360 Delete type=0 #648005
2024/01/04-01:43:57.712687 140383501207360 Delete type=3 #2


2024/01/04-01:46:33.117038 140383423801088 Compacting 1@0 + 3@1 files
2024/01/04-01:46:33.137360 140383423801088 Generated table #648831@0: 3802 keys, 735698 bytes
2024/01/04-01:46:33.145200 140383423801088 Generated table #648832@0: 258 keys, 71799 bytes
2024/01/04-01:46:33.150052 140383423801088 Generated table #648833@0: 240 keys, 66633 bytes
2024/01/04-01:46:33.154370 140383423801088 Generated table #648834@0: 219 keys, 60265 bytes
2024/01/04-01:46:33.157882 140383423801088 Generated table #648835@0: 133 keys, 29128 bytes
2024/01/04-01:46:33.157955 140383423801088 Compacted 1@0 + 3@1 files => 963523 bytes
2024/01/04-01:46:33.159269 140383423801088 compacted to: files[ 0 5 80 557 1144 0 0 ]
2024/01/04-01:46:33.161742 140383423801088 Delete type=2 #648009
2024/01/04-01:46:33.162059 140383423801088 Delete type=2 #648829
2024/01/04-01:46:33.162449 140383423801088 Delete type=2 #648008
2024/01/04-01:46:33.162618 140383423801088 Delete type=2 #648010

```
but even for days it cannot move even 1 more block from

**Comment by jun0tpyrc** [comment]
if i set logger print to console
```

neo> ERROR [01:50:01.751]        Operation is not valid due to the current state of the object.

```
could see this sometimes

**Comment by cschuchardt88** [comment]
What output is that? Also can you show your `config.json` _(remove any wallet information you maybe have before doing so)_ and run command `show state` in the `neo` cli. Which `chain.0.acc.zip` are you using?

**Comment by jun0tpyrc** [comment]
on multiple nodes 
```
block: 4131754/4131754  connected: 0  unconnected: 0
```


  "blockHeight": 4131754,
  "blockHash": "0xd7e111c2cb75c99568e4da3a90fc8d8b83e4079f74374cdd2d3e2c4a8639d7b2",
https://neo3.neotube.io/block/4131754
(seems still valid)


configs
```
{
  "ApplicationConfiguration": {
    "Logger": {
      "Path": "Logs",
      "ConsoleOutput": true,
      "Active": true
    },
    "Storage": {
      "Engine": "LevelDBStore",
      "Path": "/data/Data_LevelDB_{0}"
    },
    "P2P": {
      "Port": 10333,
      "WsPort": 10334,
      "MinDesiredConnections": 10,
      "MaxConnections": 40,
      "MaxConnectionsPerAddress": 3
    },
    "UnlockWallet": {
      "Path": "",
      "Password": "",
      "IsActive": false
    }
  },
  "ProtocolConfiguration": {
    "Network": 860833102,
    "AddressVersion": 53,
    "MillisecondsPerBlock": 15000,
    "MaxTransactionsPerBlock": 512,
    "MemoryPoolMaxTransactions": 50000,
    "MaxTraceableBlocks": 2102400,
    "Hardforks": {
      "HF_Aspidochelone": 1730000,
      "HF_Basilisk": 4120000
    },
    "InitialGasDistribution": 5200000000000000,
    "ValidatorsCount": 7,
    "StandbyCommittee": [
      "03b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c",
      "02df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e895093",
      "03b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a",
      "02ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba554",
      "024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d",
      "02aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e",
      "02486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a70",
      "023a36c72844610b4d34d1968662424011bf783ca9d984efa19a20babf5582f3fe",
      "03708b860c1de5d87f5b151a12c2a99feebd2e8b315ee8e7cf8aa19692a9e18379",
      "03c6aa6e12638b36e88adc1ccdceac4db9929575c3e03576c617c49cce7114a050",
      "03204223f8c86b8cd5c89ef12e4f0dbb314172e9241e30c9ef2293790793537cf0",
      "02a62c915cf19c7f19a50ec217e79fac2439bbaad658493de0c7d8ffa92ab0aa62",
      "03409f31f0d66bdc2f70a9730b66fe186658f84a8018204db01c106edc36553cd0",
      "0288342b141c30dc8ffcde0204929bb46aed5756b41ef4a56778d15ada8f0c6654",
      "020f2887f41474cfeb11fd262e982051c1541418137c02a0f4961af911045de639",
      "0222038884bbd1d8ff109ed3bdef3542e768eef76c1247aea8bc8171f532928c30",
      "03d281b42002647f0113f36c7b8efb30db66078dfaaa9ab3ff76d043a98d512fde",
      "02504acbc1f4b3bdad1d86d6e1a08603771db135a73e61c9d565ae06a1938cd2ad",
      "0226933336f1b75baa42d42b71d9091508b638046d19abd67f4e119bf64a7cfb4d",
      "03cdcea66032b82f5c30450e381e5295cae85c5e6943af716cc6b646352a6067dc",
      "02cd5a5547119e24feaa7c2a0f37b8c9366216bab7054de0065c9be42084003c8a"
    ],
    "SeedList": [
      "seed1.neo.org:10333",
      "seed2.neo.org:10333",
      "seed3.neo.org:10333",
      "seed4.neo.org:10333",
      "seed5.neo.org:10333"
    ]
  }
}
```

seem we have a p2p problem ?!

**Comment by jun0tpyrc** [comment]
ref the same network setup worked before  && we already have  P2P via TCP | 10333 open to the world (0.0.0.0)

**Comment by jun0tpyrc** [comment]
`chain.0.acc.zip ` was from https://sync.ngd.network/  , actually tried a few times in different day - still same problem so might not be corruption on some specifice dates

**Comment by cschuchardt88** [comment]
Are you able to connect to `seed1.neo.org` on port `10333` in `docker` vm? and ping `seed1.neo.org`? Port `10333` doesn't need to be forwarded, **ONLY* if you peers to connect to you.

Also did you download `N3 Mainnet`?

**Comment by jun0tpyrc** [comment]
connection should work on seed node's p2p port (ping does not but sounds doesn't matter?)
```
nc -vvvv seed1.neo.org  10333
Ncat: Version 7.50 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /usr/share/ncat/ca-bundle.crt.
NCAT DEBUG: Unable to load trusted CA certificates from /usr/share/ncat/ca-bundle.crt: error:02001002:system library:fopen:No such file or directory
libnsock nsi_new2(): nsi_new (IOD #1)
libnsock msevent_new(): msevent_new (IOD #1) (EID #8)
libnsock nsock_connect_tcp(): TCP connection requested to 20.55.44.83:10333 (IOD #1) EID 8
libnsock nsp_add_event(): NSE #8: Adding event
libnsock nsock_loop(): nsock_loop() started (no timeout). 1 events pending
libnsock nsock_trace_handler_callback(): Callback: CONNECT SUCCESS for EID 8 [20.55.44.83:10333]
Ncat: Connected to 20.55.44.83:10333.
```

**Comment by jun0tpyrc** [comment]
sounds similar to https://github.com/neo-project/neo-node/issues/873

**Comment by cschuchardt88** [comment]
Are you using `windows` on docker? if so you or if you downloaded `chain.0.acc.zip` than transferred to `docker`vm 

You need to do:
![image](https://github.com/neo-project/neo/assets/8141309/0309837e-7ed3-478b-a3c2-c3357e23f2ba)

Also can you remove or delete `chain.0.acc.zip` from `docker` vm. If above doesn't work or apply.

**Comment by jun0tpyrc** [comment]
> Are you using `windows` on docker? if so you or if you downloaded `chain.0.acc.zip` than transferred to `docker`vm
> 
> You need to do: ![image](https://private-user-images.githubusercontent.com/8141309/294087902-0309837e-7ed3-478b-a3c2-c3357e23f2ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDM4NDIsIm5iZiI6MTcwNDM0MzU0MiwicGF0aCI6Ii84MTQxMzA5LzI5NDA4NzkwMi0wMzA5ODM3ZS03ZWQzLTQ3OGItYTNjMi1jMzM1N2UyM2YyYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMDQ0NTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFhYmFiY2M5M2Y4ZGRiODMyODA5MDNlZTQ2OWY5ODQ3YzFmZTk2NTI1ZGEyZjlkYjE5ODliODM3MWY1YmY4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZChX9-AFPU-4Vjk57IO8EeIvjYRIuZ3zvT2q2DUyLxw)
> 
> Also can you remove or delete `chain.0.acc.zip` from `docker` vm. If above doesn't work or apply.

using linux docker , also tried on different instances for  both 1)removing the chain.0.acc.zip or 2) not removing chain.0.acc.zip at the stuck height then a complete restart of node , both still can't connect anything

**Comment by shargon** [comment]
I understand that is a docker version from axlabs, @gsmachado did you have any issue with this version?

**Comment by cschuchardt88** [comment]
Try extracting the zip or try running _see Below_ in `docker` vm

```
> wget https://packets.azureedge.net/neochain/n3mainnet/full/0-4674748/00340E2CAB675DC2484A2E76EFEF7311/chain.0.acc.zip
> md5sum chain.0.acc.zip
```

Match MD5 to this hash `00340E2CAB675DC2484A2E76EFEF7311`

**Comment by jun0tpyrc** [comment]
> Try extracting the zip or try running _see Below_ in `docker` vm
> 
> ```
> > wget https://packets.azureedge.net/neochain/n3mainnet/full/0-4674748/00340E2CAB675DC2484A2E76EFEF7311/chain.0.acc.zip
> > md5sum chain.0.acc.zip
> ```
> 
> Match MD5 to this hash `00340E2CAB675DC2484A2E76EFEF7311`
> 
> Ref: https://sync.ngd.network/

Using this to rework once more , hash verified (may take some time to get back )

**Comment by jun0tpyrc** [comment]
> Try extracting the zip or try running _see Below_ in `docker` vm
> 
> ```
> > wget https://packets.azureedge.net/neochain/n3mainnet/full/0-4674748/00340E2CAB675DC2484A2E76EFEF7311/chain.0.acc.zip
> > md5sum chain.0.acc.zip
> ```
> 
> Match MD5 to this hash `00340E2CAB675DC2484A2E76EFEF7311`
> 
> Ref: https://sync.ngd.network/

Only this snapshot works , it could sync until up-to-date    -  but not those we got at https://sync.ngd.network ....

**Comment by cschuchardt88** [comment]
So all good now? Safe to close?

**Comment by shargon** [comment]
@neo-project/ngd-shanghai could you review your snapshot?

**Comment by cschuchardt88** [comment]
I think he was missing `hardforks` in the `config.json`
