### ISSUE TITLE
Move devpack repo to neo core repo

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#3054]
**Summary or problem description**
We need smart contract examples be easily seen by new developers, so as @Jim8y suggested in https://github.com/neo-project/neo/pull/3047, it's good to put it into neo-core repo. But a new issue will be there then, smartcontract framework depends on neo-core. If examples are in neo, we can't update framework to the latest version when adding a release tag on neo repo!

**Do you have any solution you want to propose?**
Move devpack into Neo-CLI as well. We can even be able to compile smart contract inside CLI then...

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- Compiler
- CLI

**Comment by vncoelho** [comment]
Everything is being migrated now.
Just archive that repo and migrate its projects and tests.

**Comment by cschuchardt88** [comment]
# **Don't forget about github workflows.**

**Comment by vncoelho** [comment]
> @vncoelho @superboyiii 
> # **Don't forget about github workflows.**

You mean about it becomming to long?

**Comment by cschuchardt88** [comment]
@vncoelho yes migrate too

**Comment by cschuchardt88** [comment]
Rename of course

**Comment by Jim8y** [comment]
We can have new workflows for monoreos.

**Comment by cschuchardt88** [comment]
Yes i know, but so we have the workflow to work with, and can build from , if needed.

**Comment by shargon** [comment]
If we decide to move examples and devpack to this repo, I'm not against to, otherwise this pr must be in examples repository.

**Comment by Jim8y** [comment]
Will not move to the monorepo, use neo-core as submodule to the devpack instead.

**Comment by Jim8y** [comment]
I'll focus on making it work at first, we can discuss where to put it later.
