### ISSUE TITLE
global.json makes specific .NET SDK necessary which causes .NET 7.0.1 can't build projects

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#3056]
**Describe the bug**
Now global.json need a specific .NET SDK, it's not necessary. For now is :
```
{
  "sdk": {
    "version": "7.0.404",
    "rollForward": "latestFeature",
    "allowPrerelease": false
  }
}
```
For me, my .NET SDK is 7.0.1 so I can't build anything. 
**To Reproduce**
Install a lower version of .NET SDK and build any project in Neo.

**Expected behavior**
Any .NET 7+ SDK should work for building projects. This specific version can be basic major version like 7.0. Or we can remove global.json, haven't seen it's been used in workflow.

@cschuchardt88 What's your thought?

**Comment by cschuchardt88** [comment]
Its necessary for github workflow to work correctly

**Comment by superboyiii** [comment]
Fine.
