### ISSUE TITLE
New Runtime APIs

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#306]
We need to add three new Runtime APIs:
- System.Runtime.GetEntryContract
- System.Runtime.GetCallingContract
- System.Runtime.GetExecutingContract

Consider that we have the following invocation chain:
```
A -> B -> C -> D1 -> D2
```
where `A` is the `Script` of an `InvocationTransaction`, `B` and `C` are contracts that be invoked, `D1` and `D2` are two different methods from same contract `D`.

When we call the APIs above in `D2`, we will get:
- `B` from `System.Runtime.GetEntryContract`
- `C` from `System.Runtime.GetCallingContract`
- `D` from `System.Runtime.GetExecutingContract`

**Comment by shargon** [comment]
Is not the same as Hash?

**Comment by vncoelho** [comment]
How about if we call the APIS in C?

**Comment by shargon** [comment]
Should return the hash or the Contract?

**Comment by erikzhang** [comment]
I think we can close this.

**Comment by shargon** [comment]
Maybe is good, if we want to check the manifest from the calling contract or something like that

**Comment by shargon** [comment]
@erikzhang is not enough with this ?
https://github.com/neo-project/neo/blob/087a2f08547d192d332ca445a5a7d0028323bf3e/neo/SmartContract/InteropService.cs#L29-L31

**Comment by lock9** [comment]
@shargon  is it done? if this is done already, we can close this?

**Comment by shargon** [comment]
I don't now if he want to get the contract or the hash

**Comment by lock9** [comment]
Hmm, good question. I think it is the script? 🤔 
@erikzhang  we need you here. What did you have in mind? The script or the scripthash?

**Comment by shargon** [comment]
We can close it, and reopened it if is needed

**Comment by erikzhang** [comment]
We don't need this one if we implement https://github.com/neo-project/neo-vm/pull/158
