### ISSUE TITLE
New API for NeoContract: System.Runtime.GetInvocationCounter

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#307]
The invocation counter records the number of times each contract was invoked in current `InvocationTransaction`.

Consider that we have an `InvocationTransaction` with the following `Script`:
```
APPCALL <A>
APPCALL <B>
APPCALL <B>
APPCALL <C>
```

If we call `System.Runtime.GetInvocationCounter` in each contract, we will get:
- `1` from `APPCALL <A>`
- `1` from the first `APPCALL <B>`
- `2` from the second `APPCALL <B>`
- `1` from `APPCALL <C>`

**Comment by igormcoelho** [comment]
Hi guys, what's the use case for this? Anyway, it's always good to have new tools :)

**Comment by igormcoelho** [comment]
I see this has many potential applications, let's go for it! any updates?
