### ISSUE TITLE
New API for NeoContract: System.Runtime.GetNotifications

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#308]
`System.Runtime.GetNotifications` receives a scripthash as an argument, and returns all notifications from that contract in current `InvocationTransaction`.

Consider that we have an `InvocationTransaction` with the following `Script`:
```
APPCALL <A>
APPCALL <B>
SYSCALL System.Runtime.GetNotifications <A>
```

**Comment by shargon** [comment]
Will be the notification that was sent with `System.Runtime.Notify` right?

**Comment by erikzhang** [comment]
> Will be the notification that was sent with `System.Runtime.Notify` right?

Yes.

**Comment by igormcoelho** [comment]
Oh, I love new things :) but what is a possible application for this? hahahah

**Comment by erikzhang** [comment]
> Oh, I love new things :) but what is a possible application for this? hahahah

Consider a contract to run a decentralized exchange. When a user needs to deposit, he will first transfer some NEP-5 tokens to this contract and then call its `deposit` method. In the `deposit` method, the contract can confirm that the user actually transferred the tokens by calling `System.Runtime.GetNotifications`.

**Comment by dicarlo2** [comment]
@erikzhang Couldn't they just check that the tokens were deposited by querying the smart contract? `System.Runtime.GetNotifications` seems unreliable, at least in the dynamic call case - what happens if the contract incorrectly implements the notifications? I.e. at a high level, notifications are not the source of truth.

**Comment by igormcoelho** [comment]
@erikzhang will any Verification contracts be able to produce (and store) such notifications? That would be amazingly useful!
Will this GetNotifications be able to filter them somehow by some prefix? Or the whole list will be returned? Or the contract will just check if a given notification existed?

**Comment by erikzhang** [comment]
@igormcoelho `System.Runtime.GetNotifications` can get the notifications that sent from the same `InvocationTransaction`.

**Comment by RavenXce** [comment]
Is there a way to check if the invocation faulted?

**Comment by deanpress** [comment]
Why is this in the 3.0 Milestone? Wouldn't this be applicable in e.g. 2.7?

**Comment by erikzhang** [comment]
> Is there a way to check if the invocation faulted?

If the invocation faulted, it will not continue to execute. There is currently no way to recover from an exception.

I have planned to add a mechanism for smart contract exception handling in NEO 3.0. https://github.com/neo-project/neo/issues/310

> Why is this in the 3.0 Milestone? Wouldn't this be applicable in e.g. 2.7?

It can be applicable in 2.x if necessary.

**Comment by RavenXce** [comment]
> If the invocation faulted, it will not continue to execute. There is currently no way to recover from an exception.

So this mean `System.Runtime.GetNotifications` will never have notifications after faulting? In the current version, execution results are not cleared.

**Comment by erikzhang** [comment]
> In the current version, execution results are not cleared, so this notification remains.

https://github.com/neo-project/neo/blob/9cf0d94f0979ea579e6b9d660359e0c49625532b/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.cs#L590-L593

If the invocation faulted, everything will be rolled back.

**Comment by RavenXce** [comment]
Yes that is true, but the notifications are still added to execution results as a copy:

https://github.com/neo-project/neo/blob/9cf0d94f0979ea579e6b9d660359e0c49625532b/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.cs#L601

Just confirming the behavior should not be the same for this API.

**Comment by igormcoelho** [comment]
Scripthash will be included too, right? For that other proposal of Native contracts (https://github.com/neo-project/neo/issues/303), it would be nice to each contract having an unique name (as explained there), and that would be useful here too... so if we are catching a notification from contract named "NEO" regarding a "transfer"... transfer is done, utxo is gone ;)

**Comment by igormcoelho** [comment]
@shargon @erikzhang @vncoelho time to implement this. I was sure it had passed already haha took time to find this here.

**Comment by dicarlo2** [comment]
@igormcoelho @shargon to clarify, this only applies to notifications from the current transaction right? (Sorry if this is an obvious question, I haven't been following NEO 3.0 changes too closely - yet anyways)

**Comment by shargon** [comment]
Yes @dicarlo2 exactly as you said
