### ISSUE TITLE
Implicitly can not use  `JToken.Null` with `JTokens`

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3084]
**Describe the bug**
Cannot implicitly convert type 'Neo.Json.JToken' to 'Neo.Json.JArray', `Neo.Json.JObject` and maybe even more.

**To Reproduce**
```csharp
JArray Params = JArray.Null;
JObject Params = JObject.Null;
```

**Expected behavior**
To be able to use `JToken.Null` with `JToken` objects other than `JToken`

**Screenshots**
![image](https://github.com/neo-project/neo/assets/8141309/4a163ab8-a70f-46cf-913b-84ff10c7f470)

![image](https://github.com/neo-project/neo/assets/8141309/f97bdf99-6c7a-4f71-b900-bcc694babb73)

**Platform:**
 - neo: version 3.6.2

**Comment by cschuchardt88** [comment]
@shargon @Jim8y

**Comment by shargon** [comment]
We can create `JNull` but `JToken.Null` is not compatible with `JArray`

**Comment by cschuchardt88** [comment]
Why not? `JArray` is a `JToken` is it not? This is the exact reason why to use our own custom `JSON` library. Why reinvent the wheel if you can't do it right? That's like you saying you can't use snow tires in the summertime because they were made for the snow.

**Comment by shargon** [comment]
> Why not? `JArray` is a `JToken` is it not? This is the exact reason why to use our own custom `JSON` library. Why reinvent the wheel if you can't do it right? That's like you saying you can't use snow tires in the summertime because they were made for the snow.

Yes but Jarray.Null is null not a Jarray hahaha. I understand you, we can solve it creating JNull

**Comment by shargon** [comment]
> You tell me the differance. `JARRAY`
> 
> ```
> {
>   "Hello": null
> }
> ```
> 
> `JTOKEN`
> 
> ```
> {
>   "Hello": null
> }
> ```

null is null, is not an array

**Comment by cschuchardt88** [comment]
Are they both not a JToken? Clearly they are. Just goes to show that `JTokens` can be `JArrays` and `JArrays` can be `Tokens`.

#### What JTOKEN can be

[**JSON Grammar**](https://datatracker.ietf.org/doc/html/rfc8259#section-2)
```
A JSON text is a sequence of tokens.  The set of tokens includes six
   structural characters, strings, numbers, and three literal names.

   A JSON text is a serialized value.  Note that certain previous
   specifications of JSON constrained a JSON text to be an object or an
   array.  Implementations that generate only objects or arrays where a
   JSON text is called for will be interoperable in the sense that all
   implementations will accept these as conforming JSON texts.

      JSON-text = ws value ws

   These are the six structural characters:

      begin-array     = ws %x5B ws  ; [ left square bracket

      begin-object    = ws %x7B ws  ; { left curly bracket

      end-array       = ws %x5D ws  ; ] right square bracket

      end-object      = ws %x7D ws  ; } right curly bracket

      name-separator  = ws %x3A ws  ; : colon

      value-separator = ws %x2C ws  ; , comma
```
[**Values**](https://datatracker.ietf.org/doc/html/rfc8259#section-3)
```
A JSON value MUST be an object, array, number, or string, or one of
   the following three literal names:

      false
      null
      true

   The literal names MUST be lowercase.  No other literal names are
   allowed.

      value = false / null / true / object / array / number / string

      false = %x66.61.6c.73.65   ; false

      null  = %x6e.75.6c.6c      ; null

      true  = %x74.72.75.65      ; true
```

**Comment by cschuchardt88** [comment]
Should be fixed
