### ISSUE TITLE
Allows NeoVM to support global variables

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#309]
Currently, NeoVM is not supported for global variables. The following code will fail to compile:
```c#
class ContractWithGlobalVariables : SmartContract
{
    private static int a = 1;
    public int Main(int x)
    {
        a += x;
        return a;
    }
}
```

This is because NeoVM is a stack based virtual machine, where there is no place to store global variables. This makes it difficult to compile smart contracts written in high-level languages.

To solve this problem, we need to add a global array for the virtual machine to store all the global variables. And we need to add a new opcode `GLOBAL` which pushes the global array to the evaluation stack. Then we can use `PICKITEM` and `SETITEM` to access the global variables.

**Comment by anthdm** [comment]
In the `neo-go` compiler I handle global variables by passing them in the scope of each function. [link to the code](https://github.com/CityOfZion/neo-go/blob/master/pkg/vm/compiler/codegen.go#L188). Should this not be handled on compiler level?

**Comment by erikzhang** [comment]
This is a solution that handles global variables through the compiler. But if you do, it's hard to support the callback features we're going to add in the future.

**Comment by lock9** [comment]
What if we add a "setup" method, like in unit tests?

(This is just an idea)
`
public void SetUp(object[] variables);
`
When you use a static variable like
 `public static int a = 1`, we would just append this variable to this array.

If you need use this variables, we could use SetUp and use it afterwards?

**Comment by localhuman** [comment]
The `neo-boa` compiler does the same thing as the `neo-go` compiler, and I don't think it is the best solution.  Global variable support would be nice to have.

**Comment by shargon** [comment]
@lightszero what is the state of this issue?

**Comment by igormcoelho** [comment]
`DUPFROMALTSTACKBOTTOM` opcode resolved this issue already on neo-vm.
I'll close this (just devpack adjustments now I guess).

**Comment by erikzhang** [comment]
Has the compiler already implemented support for global static members?

**Comment by igormcoelho** [comment]
From these tests, I suppose that it is working already: https://github.com/neo-project/neo-devpack-dotnet/pull/65/files
