### ISSUE TITLE
Cloned Neo Blockchain 

### ISSUE THREAD

**Issue by DerivProject** [neo-project/neo#3098]
Greetings, I require someone to provide me with a detailed explanation of how to clone the Neo blockchain network and then transform it into my own blockchain network with a complete guide to accessing it.

**Comment by Jim8y** [comment]
https://docs.neo.org/docs/en-us/develop/network/private-chain/solo.html

**Comment by DerivProject** [comment]
In which type of OS can I used Ubuntu or windows using cloned neo Blockchain network and make it as my own Blockchain

**Comment by Jim8y** [comment]
Most latest Ubuntu and windows would work.

**Comment by DerivProject** [comment]
Just tell me one for more better

**Comment by dusmart** [comment]
https://github.com/CityOfZion/neo-privatenet-docker

```
$ docker pull cityofzion/neo-privatenet
$ docker run --rm -d --name neo-privatenet -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336/tcp cityofzion/neo-privatenet
```

**Comment by cschuchardt88** [comment]
Question Answered.
