### ISSUE TITLE
Should the NEP-17/NEP-11 standard mention the verify method?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#3099]
I've noticed that the NEP-17/11 standards inform about the `onNEP17Payment` method, but it doesn't say anything about implementing the  `verify` method. 

First, it seems that we need to inform users that they must implement the `onNEP17Payment`; secondly, If they implement the callback but don't implement the `verify` callback, they cannot withdraw their funds.

I wonder if:
- Should we mention the implementation of the `verify` callback?
- Should we enforce the existence of the `verify` callback?
  - Or even include a `ownerOf`?

**Comment by roman-khimov** [comment]
`verify` has nothing to do with NEP-11/NEP-17. See https://github.com/neo-project/proposals/pull/154.

**Comment by lock9** [comment]
What do you mean? The `verify` is used by the CheckWitness method... right?

If we do `Runtime.CheckWitness(contract)`, it will trigger `contract.verify()`.

**Comment by cschuchardt88** [comment]
`Verify` method is if contract calls itself.

**Comment by lock9** [comment]
It's also called when you set a contract hash as a transaction signer with empty verification and invocation scripts. That is how users can withdraw funds from contracts.
