### ISSUE TITLE
EnrollmentTransaction.cs checking PK

### ISSUE THREAD

**Issue by coranos** [neo-project/neo#31]
in EnrollmentTransaction.cs the publickKey is not checked as part of DeserializeExclusiveData.

in contrast, in RegisterTransaction.cs you do check and throw a FormatException.

compare RegisterTransaction.DeserializeExclusiveData line 70-72
Owner = ECPoint.DeserializeFrom(reader, ECCurve.Secp256r1);
if (Owner.IsInfinity && AssetType != AssetType.SystemShare && AssetType != AssetType.SystemCoin)
throw new FormatException();

to EnrollmentTransaction.DeserializeExclusiveData line 47
PublicKey = ECPoint.DeserializeFrom(reader, ECCurve.Secp256r1);

**Comment by erikzhang** [comment]
As you know EnrollmentTransaction is marked as "Obsolete", it is no longer to be used any more. As an alternative, Validator.Register() in contract API will check the pubkey.
See https://github.com/neo-project/neo/blob/master/neo/SmartContract/StateMachine.cs#L114
