### ISSUE TITLE
Question - Is the multisign contract in the genesis block correct?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#312]
Hello,
I'm reviewing the GenesisBlock for neo-sharp and I noticed that the current genesis method is using this:
 ```csharp
 new TransactionOutput
                        {
                            AssetId = GoverningToken.Hash,
                            Value = GoverningToken.Amount,
                            ScriptHash = Contract.CreateMultiSigRedeemScript(StandbyValidators.Length / 2 + 1, StandbyValidators).ToScriptHash()
                        } 
```

I would like to understand if this is actually correct, or if the correct implementation shouldn't me "2/3 + 1".
For 4 standby validators, the result is the same:
(2 * 4 / 3)  + 1 = 3
(4 / 2)  + 1 = 3

I'm planning to run a NEO private chain, so I just want to be sure that this is correct or need to be fixed (we plan to have more than 4 validators since the beginning).
Thanks.

**Comment by Sinepitiss** [comment]
Well if I understood the genesis block correctly I think it's meant that the initial 100m neo are sent to a multi signature contract which can only be invoked by the majority of standby validators ,thus n/2+1
4/2+1 = 3
5/2+1 = 3
6/2+1 = 4
7/2+1 = 4
8/2+1 = 5
and so on

**Comment by lock9** [comment]
So it's meant to be "more than half", I thought this was related to the fault tolerance of the network.
Thanks!
