### ISSUE TITLE
Load and export storage to json

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#3127]
We need an easy way for testing smart contract in complex scenarios (with flamingo data for example).

Proposed changes:

- [ ] [#3128]
- [ ] [#3129]

**Comment by roman-khimov** [comment]
For the export part you don't need to modify core, everything can be fetched via RPC already, see https://github.com/nspcc-dev/neofs-contract/blob/f083b3a4f24dd93b4ac5f1c41a23ef522304e0a6/cmd/dump/blockchain.go#L88 for example (added as a part of https://github.com/nspcc-dev/neofs-contract/pull/324). We save storage data into CSV though (I think it's enough for the purpose).

Refs. https://github.com/nspcc-dev/neo-go/issues/2406 as well.

**Comment by shargon** [comment]
> For the export part you don't need to modify core, everything can be fetched via RPC already, see https://github.com/nspcc-dev/neofs-contract/blob/f083b3a4f24dd93b4ac5f1c41a23ef522304e0a6/cmd/dump/blockchain.go#L88 for example (added as a part of [nspcc-dev/neofs-contract#324](https://github.com/nspcc-dev/neofs-contract/pull/324)). We save storage data into CSV though (I think it's enough for the purpose).
> 
> Refs. [nspcc-dev/neo-go#2406](https://github.com/nspcc-dev/neo-go/issues/2406) as well.

I added `if #DEBUG` I prefer to make it easy the procedure, RPC require additional software to call it, iteration, truncation, etc.

**Comment by Jim8y** [comment]
More like a plugin job. Can't you add it to the plugin?

**Comment by shargon** [comment]
Maybe we can move the import to the test engine, but the export it's easier for user to be in neo-cli

**Comment by shargon** [comment]
It will me moved to a plugin
