### ISSUE TITLE
Add Support to .NET 8

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#3132]
**Summary or problem description**
It seems that the compiler is not compatible with the latest .NET version (8). It's not possible to update it to make it compatible with .NET 8 because the Neo library doesn't support it.

**Do you have any solution you want to propose?**
Add support to support .NET 8. It's impossible to update only the compiler because it depends on Neo. Jimmy mentioned using .NET Standard, but that will demand more refactoring than just adding support to .NET 8. 

**Where in the software does this update apply to?**
- Compiler
- Other: Core Lib

**Comment by lock9** [comment]
Thanks @cschuchardt88, that seems to be the ideal solution.

Should I create another issue in the devpack repository to update it once this is implemented? (if it's implemented at all).

**Comment by shargon** [comment]
> @Jim8y @shargon if we are do this **DO NOT** remove `net7.0`.
> 
> ### add this line
> ```
> <TargetFrameworks>netstandard2.1;net7.0;net8.0</TargetFrameworks>
> ```

https://github.com/neo-project/neo/issues/3056#issuecomment-1876810482

**Comment by cschuchardt88** [comment]
That comment was for **ONLY** `dotnet` 7.0 latest. Read whole thing 1st.
