### ISSUE TITLE
`neo-cli` No Screen Rendering on Invalid Arguments.

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3135]
**Describe the bug**
when you type invalid arguments on the commandline for `neo-cli.exe`. You get an error message; however, the `CLI` prompt still opens; allowing you to enter commands. When you enter command `show state`; this ends up not rendering the screen and also clears the screen. 

The reason i think it is doing this is because of the command text coloring that, causes the `show state` method to not render correctly.

**To Reproduce**
1. Type command `neo-cli /noverify` in `powershell`
2. Type `show state` in the `neo-cli` prompt

**Expected behavior**
If there is invalid arguments passed in. Than there should be no `neo-cli` command prompt or the arguments should be ignored.

**Screenshots**
![image](https://github.com/neo-project/neo/assets/8141309/7cebcc2d-9fdb-4c8e-88b9-f7bb49675268)
![image](https://github.com/neo-project/neo/assets/8141309/eb7bf3ad-868c-47d8-b323-ea043fc2b5aa)

**Platform:**
 - Version `neo-cli` `3.6.3`

**Comment by cschuchardt88** [comment]
@shargon @Jim8y

**Comment by shargon** [comment]
I will review it likely the next week (working of bug fixes now).
