### ISSUE TITLE
Return unclaimed gas from non-voters to the network pool

### ISSUE THREAD

**Issue by toghrulmaharramov** [neo-project/neo#315]
**Problem**
GAS distribution to the "lost" NEO can potentially drain the GAS supply in a long-term.

**Solution**
The distribution of GAS to the "lost" NEO could be circumvented by enabling GAS distribution only to the voting NEO. At the start of the next voting period, all the unclaimed GAS of non-voting NEO during the current voting period is added back to the GAS pool to be distributed later. The nodes should also limit the number of GAS claims a wallet address is able to make for a given period of time (for example, once per month).

**Comment by toghrulmaharramov** [comment]
#285

**Comment by toghrulmaharramov** [comment]
Correction: I removed the section concerning the prevention of users without the NEO in question from claiming GAS. I realized that it will not work in combination with claim limits.

**Comment by lock9** [comment]
@toghrulmaharramov what if we auto-claim gas when the user votes? This way, we can say that "unclaimed gas is returned to the network pool". What do you think?

**Comment by vncoelho** [comment]
I do not like this for now. I believe that this can be removed from NEO3 milestone. 

Auto-claim will be automatically enabled after transferring NEO on Native NEP 5 contracts for NEO and GAS.

**Comment by lock9** [comment]
There is an "overall desire" of the community of "redistributing 'lost' GAS". 
@neo-project/core  What is your opinion? You wanted to keep this in NEO 3. Are we keeping it?
If we are keeping it, is there anything that should be done prior to this?
