### ISSUE TITLE
Abolish master branch name - migrate to main

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3156]
Current recommended best practices

**Comment by roman-khimov** [comment]
Sorry, I don't see it improving anything, but it does require changing setting and habits. I've even tried some repositories with `main` (huh, try not to try it these days), but always reverted back when it was possible. Not that it's a blocker to me, but an inconvenience that is not justified.

**Comment by Jim8y** [comment]
Close as not going to apply.
