### ISSUE TITLE
[NEO3] Representative Voting

### ISSUE THREAD

**Issue by toghrulmaharramov** [neo-project/neo#316]
**Problem**
The [current implementation](http://docs.neo.org/en-us/node/gui.html#election-and-voting) of the NEO voting mechanism employs a modification of [Satisfaction Approval Voting](https://mpra.ub.uni-muenchen.de/22709/1/MPRA_paper_22709.pdf) in which each selected Consensus Node in a voting transaction receives the total number of committed NEO towards the final vote count instead of splitting the NEO equally amongst each candidate included in the vote. Apart from the issue highlighted [here](https://github.com/neo-project/neo/issues/28), the aforementioned implementation is potentially susceptible, but not limited to the following issues:

- NEO Foundation and exchanges exerting an excessive amount of influence on the election outcome.
- Plutocratic system empowering the wealthy users
- Low voter turnout and additional blockchain clutter during the snap/emergency elections

**Solution**
The proposed solution is to elect the Consensus Nodes via two separate election procedures. First, the Representative elections in which the voters are split into `p` Voter Pools based on the first `a` wallet address bits excluding the prefix are held. Users, who are willing to enrol their candidacy, are required to submit a stake (`n` GAS) and pass the KYC, akin the Consensus Node candidate evaluation procedure. Afterwards, the candidates are randomly assigned to the Voter Pools (via a Verifiable Random Function) with at least one Representative required to be elected per Pool. Second, the Consensus Node elections are held. Each Representative receives the same amount of voting power in the Consensus Node elections to even out the influence distribution. The Representatives are required to submit their votes during a Voting Period. In case the Representative does not submit the vote prior to the deadline, his/her Representative status is automatically revoked and the Representative snap election procedure begins in the particular Voter Pool. 

**Motivation**
The proposal described above solves the issues related to the current voting implementation. Firstly, the voting power of the large stakeholders is suppressed, though not negated. Secondly, due to the Consensus Node elections being held on a more frequent basis, the participation of the entire stakeholder community is rarely required which decreases the problem of low voter turnout and additional blockchain clutter.

**Comment by lerider** [comment]
This is worth evaluating. I do think that the algorithm for number of total consensus node is mitigating this issue quite well, since only weighted mid-50% are evaluated for calculating that number. This is one of these things were it would be interesting to see how it actually turns out in practice before pursuing change.
