### ISSUE TITLE
What would happen if the number of Committee nodes is increased from 21 to 23?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#3165]
Hi,

I would like to know the impact of changing the number of committee nodes from 21 to 23. 

- Would that affect consensus? Would it increase the number of required signatures to mint a block?
- Are there any risks of doing this change?
- Would that affect how much gas is distributed to voters? Or only to elected CNs?

Additional context:
- I believe it's important for the core devs to run a CN. Linkd is also trying to be elected.
- Adding a new member without removing existing ones is impossible. This will lead to internal conflicts.
- I wondered if increasing the number of members from 21 to 23 would allow these 2 new members without removing existing ones.

Thanks.

**Comment by vncoelho** [comment]
This can be done @lock9,
 as a direct consequence of that the GAS generated per committee would decrease, as well as the GAS received by voters.
But this would be minor.

It would be good if each Core Dev run a node, off course, that is important for the Ecosystem.

In principle, the number of validators could remain the same.

If we go in this direction we should implement something to remove rewards from committee members that do not ping the network with their node.

**Comment by lock9** [comment]
Is there any other impact? Could this lead the network to become slower somehow?

**Comment by vncoelho** [comment]
> Is there any other impact? Could this lead the network to become slower somehow?

No change if 7 validators are kept

**Comment by lock9** [comment]
>Why? They had their time, now is time for someone who really cares and work. There are projects that already left neo in the committee, meanwhile core devs are underpaid.

I don't disagree. I'm worried about the conflicts. These people got there somehow and they may still have a lot of influence over Neo / NGD. Maybe the collaborate somehow. That is why I was thinking about a solution without, or with less, conflicts.

Is this configuration 'votable'?

**Comment by shargon** [comment]
The new nodes require also a vote, nothing can ensure that this new committee nodes will go to core devs, so it could be worst, i vote for reduce to 20, and set the core devs in a multisig included in core, they will earn gas, and this account can be rewarded and changed, (also I think that committee should reduce the gas per block at this prices)

**Comment by diskooooo** [comment]
> I would like to know the impact of changing the number of committee nodes from 21 to 23.

And what about the next 2 that want in? And the next 3? And the next 5? 

> First we need the proof of life of a committee, now they can earn gas without run a node

Agreed that committee members need to show a proof of life / proof of work - at least run a node and contribute to the network. It all starts here.

> as well as the GAS received by voters

This means voter APY will decrease? More members to choose from -> less GAS per vote... or do I misinterpret it?

**Comment by Jim8y** [comment]
I dont like the idea of change economy protocols. If we change it, makes people feel neo is not stable.

If we can not get a node for the core-dev, I prefer to add an option in the core for candidates to donate a portion of their income to the core-dev.

**Comment by lock9** [comment]
Hi @Jim8y ,
I think that changes must only be done if they are voted for.
My question is if that would be possible and what the impact would be. I'm not proposing this change. There are unknown risks, and there are other options to achieve a similar result.

>And what about the next 2 that want in? And the next 3? And the next 5?

Exactly. If we increase this number once, then we may need to increase it again and again. More nodes elected means less votes to be elected. This may not be a good thing.

>This means voter APY will decrease? More members to choose from -> less GAS per vote... or do I misinterpret it?

Afaik, there would be no impact for voters. Their reward is diluted if there are more people voting. The rewards for CN that would be reduced.

Guys, I think I have all the answers I was looking for.  I'm going to close it, ok? I don't want it to become a conversation about changing the protocol.

Thanks 🙏

**Comment by roman-khimov** [comment]
If we're to forget about the economics for a moment, this requires protocol modification because currently committee size and validator count are set in the genesis stone and can't be changed. NeoGo has an extension to do exactly that though (CommitteeHistory/ValidatorsHistory in https://github.com/nspcc-dev/neo-go/blob/master/docs/node-configuration.md#protocol-configuration), but for a different reason. This extension can be brought into the mainline (it's relatively simple), but then I doubt any public networks (mainnet/testnet) need to change these parameters for reasons mentioned by @Jim8y.
