### ISSUE TITLE
Add NNS support to native contracts

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#3166]
**Summary or problem description**
1 - Using script hashes are not user friendly since they are hard to memorize. To improve this, we can use NNS. 
2 - Native contracts are called from sdks using imports. If we could use NNS, we could use the same solution for all contracts / dependencies.

**Do you have any solution you want to propose?**
Create domains on NNS that can be used to call native contracts.

**Where in the software does this update applies to?**
- Other: Native Contracts

**Comment by roman-khimov** [comment]
Usually SDKs know native contract hashes exactly. Like to me it's `gas.Hash` (https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.105.1/pkg/interop/native/gas#pkg-constants or https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.105.1/pkg/rpcclient/gas#pkg-variables), whatever that is. And it's known without NNS.

**Comment by lock9** [comment]
The problem is that you need to use different ways to find script hashes. 
I was thinking if we could use the same solution to refer to native and user deployed contracts.

In practice, we don't need to call NNS in runtime, but use it during compilation. 

In other words, I wish that finding contracts are consistent, even if they are native contracts.  They should be able to "refer to" Flamingo the same way they refer the ContractMamagement native contract. 

Maybe instead of multiple domains,  just one using subdomains? Maybe this doesn't need any kind of intervention from the core team.
