### ISSUE TITLE
WitnessRules limitation on Ledger

### ISSUE THREAD

**Issue by NeoDashboard** [neo-project/neo#3181]
Maybe this has already been addressed but I just want to try to bring some awareness on this topic as It doesn't seem to be really well known on the community and know from you if finding a solution to this is in priority backlog or not.

For now there is a limitation and WitnessRules are not implemented on Ledger (sounds It's due to memory limitation on Ledger Nano S). I think @ixje is the guy with the more knowledge about It.

My use case: in case of a adding liquididties/swap on a TOKEN1-TOKEN2 pool using CustomContracts scope the owner of TOKEN2 CONTRACT could drain users TOKEN1 assets if he change the TOKEN2 transfer method. I wanted to use WitnessRules to avoid this but sounds I won't be able for Ledger users.

Of course there are other way to solve this particular use-case but in case It's sure WitnessRules will never be available on Ledger N3 App probably It could be nice to have a note about this on those doc pages:
https://docs.neo.org/docs/en-us/basic/concept/transaction.html
https://neospcc.medium.com/thou-shalt-check-their-witnesses-485d2bf8375d

N3 Ledger App repo: https://github.com/LedgerHQ/app-neo3

**Comment by shargon** [comment]
I think that this question should be moved to https://github.com/LedgerHQ/app-neo3

**Comment by Jim8y** [comment]
close as this issue will not be addressed here.
