### ISSUE TITLE
The release "neo-cli-win-x64.zip" can't run on Windows Server

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#3199]
This problem still exists in 3.6.2 and needs to be fixed
https://github.com/neo-project/neo-node/issues/302

<img width="839" alt="a88fb714129e3c7f70908c1fafdcddd" src="https://github.com/neo-project/neo/assets/6295602/3603d2d2-1475-48f8-844e-15564d5238de">

**There are three solutions:**
1. Copy the libleveldb.dll (511KB) of the neo-gui-2.x and replace it with the original libleveldb.dll (257KB), but this version is older. 
  ![image](https://github.com/neo-project/neo/assets/6295602/afa5b9ca-652f-4b7d-b54b-680c4d76c0ea)
2. Installing [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 (x64)](https://aka.ms/vs/16/release/vc_redist.x64.exe) on Windows Server. It needs to be stated in the Release's Readme.
  ![image](https://github.com/neo-project/neo/assets/6295602/7db3e542-7470-4d48-90f6-85163992d569)
3. Compile an up-to-date version of libleveldb.dll for windows server and package it into neo-cli release.

**Comment by cschuchardt88** [comment]
@chenzhitong try this updated `LevelDBStore` 
[LevelDBStore.zip](https://github.com/neo-project/neo/files/15062334/LevelDBStore.zip)

**Comment by chenzhitong** [comment]
> @chenzhitong try this updated `LevelDBStore` [LevelDBStore.zip](https://github.com/neo-project/neo/files/15062334/LevelDBStore.zip)
> 
> Also you may want to put `libleveldb.dll` in the same directory as `LevelDBStore` plugin. Reason being is `Windows Server` is more strict when it comes to search paths for `libraries`.

It's still not working.

**Comment by cschuchardt88** [comment]
@chenzhitong Have look at https://github.com/neo-project/neo-modules/pull/899 I'm hoping this PR will fix the issues.

This is latest build. from the PR
[libleveldb.zip](https://github.com/neo-project/neo/files/15070813/libleveldb.zip)
[LevelDBStore.zip](https://github.com/neo-project/neo/files/15070816/LevelDBStore.zip)

**Comment by chenzhitong** [comment]
![image](https://github.com/neo-project/neo/assets/6295602/ddd20fcd-b487-4556-8b31-67b54f92e346)

It's still not working.

**Comment by cschuchardt88** [comment]
@chenzhitong ok `vc_redist.x64.exe` is requirement... We all have `vs2022` installed; so i wonder if this as always been a problem.

**Comment by chenzhitong** [comment]
This problem was fixed in neo 2.x, when the neo-cli release used the `libleveldb.dll` (511KB) from neo-gui, which doesn't depend on `vc_redist.x64.exe`. 
In neo 3.1.0 and earlier, this bug does not exist.
In neo 3.2.1, the problem has reappeared, used the `libleveldb.dll` (257KB), Maybe the previous version of  `libleveldb.dll` is out of date. @cschuchardt88

**Comment by cschuchardt88** [comment]
@cschuchardt88 `vc_redist.x64.exe` is required by `libleveldb.dll` because it is compiled with `vs2022`. We can release the `vc++.dll` with `neo-cli` that is required for it work.

**Comment by lock9** [comment]
Hi @chenzhitong,
It's working here. We did a test yesterday on a Windows Server using the latest release. It worked. Can you try again?

**Comment by chenzhitong** [comment]
> Hi @chenzhitong, It's working here. We did a test yesterday on a Windows Server using the latest release. It worked. Can you try again?

![image](https://github.com/neo-project/neo/assets/6295602/6db8bdbc-4fef-409e-ae63-c4b8abb62fb6)

Still not working (without additionally installing vc_redist.x64.exe)

**Comment by chenzhitong** [comment]
Can we package `vc_redist.x64.exe` (24.2MB) into neo-cli to automatically run the installer when the 0x8007007E error occurs.
