### ISSUE TITLE
Transaction negativity check

### ISSUE THREAD

**Issue by coranos** [neo-project/neo#32]
in Transaction, line 346, in the Verify function, the value of output.Value.GetData() could be negative.

The check for negativity is done in RpcServerWithWallet.cs, which is in the neo-cli project, rather than in Transaction.cs in the neo project.

**Comment by erikzhang** [comment]
The negativity check is in TransactionOutput.cs:
https://github.com/neo-project/neo/blob/master/neo/Core/TransactionOutput.cs#L34
