### ISSUE TITLE
The parse method needs to be improved

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#3201]
The parse method needs to be improved. Missing some necessary conversions.

Such as 

- Public key to Neo3 Address

- Public key to script hash

- Private key to public key

- Private key to Neo3 address

- Private key to script hash

- Mnemonic to Neo3 private key

- Mnemonic to Neo3 address

- Little-endian to big-endian

- Big-endian to little-endian

- Smart contract script analysis

![image](https://github.com/neo-project/neo/assets/6295602/efd0f1ba-520f-4122-9ba9-352462d07fe5)

![image](https://github.com/neo-project/neo/assets/6295602/76a5c507-dbc7-4a6b-b07d-5abf02ed1587)

**Comment by chenzhitong** [comment]
`DCECbzTesnBofh/Xng1SofChKkBC7jhVmLxCN1vk\u002B49xa2pBVuezJw==` Such base64 strings cannot be converted

**Comment by chenzhitong** [comment]
I can fix it if you think it needs fixing.

**Comment by shargon** [comment]
> `DCECbzTesnBofh/Xng1SofChKkBC7jhVmLxCN1vk\u002B49xa2pBVuezJw==` Such base64 strings cannot be converted [see](https://github.com/search?q=org%3Aneo-project%20%5Cu002B&type=code)

This is not a valid base64 string, it must be decoded before

**Comment by Jim8y** [comment]
> I can fix it if you think it needs fixing.

do that part that you think should be done. We will review your pr.
