### ISSUE TITLE
Clarification on Pull Requests

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3208]
We all have a different perspective on how `Pull Requests` should be done.

Can we get some clarity? So, we all are the same page.
- How `big` _**is**_ `big`?
  - **How should it be broken up?**
    - **With examples!**
  - **Timeframe of merging?**
  - **Should we wait for a merge to continue to next PR?**
- How should new projects or applications be done?
- How should downstream modules be handled.
  - **Timeframe of merging?**
- What happens if broken up PRs will break `github` `workflows`?
  - **How will merging happen of those PRs?**
  - **How should that PR be handled, that breaks changes?**
- What are the categories of things that need to be broken up in different PRs?
- Why are we merging when, no one is following guidelines or code is not consistent with existing?
- Should there be no merging, if these rules are broken? _example: I'll do in another PR...._ **_Then it never gets done_**.

Solution
___
We need some guidelines and rules; having a timely review with merging, **no more half a year for a merge**; a good review and no more adding code to repo thats looks like someone copied and pasted it from `stackoverflow` or that breaking coding styles that we agreed on.

@shargon @Jim8y @vncoelho @superboyiii we all need to agree on something. I have no problem reviewing miles long PRs. So we need rules I understand that. Let's all agree on something here in this issue.

_Just a note, even super small PR can take months for a merge or a review._

**Comment by cschuchardt88** [comment]
@roman-khimov 

>>How should new projects or applications be done?

>Too broad question.

For example #3103 it's getting pretty big, and will be big. However once ready for testing it wont have all the features.

**Comment by roman-khimov** [comment]
I'm absolutely sure it can be split into logical parts. Take your "features" list and try to think of it in terms of "one feature --- one PR".

**Comment by shargon** [comment]
I am absolutely agree with @roman-khimov, I will try to improve my commits, but one thing is clear, a big pr is hard to review, and something hard to review easily introduce new bugs
