### ISSUE TITLE
Extract TransactionOutput ScriptHash in Genesis from configuration file?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#321]
Hello,

I'm very interested in reducing the barriers to new developers join NEO, and one thing that I often see is that that we currently depend on windows machines to be able to setup a private network.

I was wondering if its possible to get the ScriptHash for the TransactionOutput in the Genesis block from the configuration file. I was thinking about something like an 'optional'  parameter (just override the address if  it's provided).

This way it would be much easier to setup a private network, because we could just use an address that uses a single signature, instead of a multisignature contract.

The other option is to use the container provided by the community, but this options hides too much information from the developer. It helps, but hides some real important information from them.

**Comment by shargon** [comment]
I don't like it @lock9 , do you mean fake the hash of the first block?

**Comment by lock9** [comment]
@shargon I don't like it either. It is because I always suffer to send the original NEO when setting up a private network, doing that we could easily change the initial NEO owners. I'm closing this.
