### ISSUE TITLE
Can't use Runtime.BurnGas

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3212]
**Describe the bug**
Unless there is some limitation on `Runtime.BurnGas`; I can't send a transaction that burn gas in the `Neo-Cli`.

**To Reproduce**
```csharp
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Attributes;
using Neo.SmartContract.Framework.Services;
using System.ComponentModel;

namespace ContractTemplate
{
    [DisplayName(nameof(TestContract))]
    [ContractPermission("*", "*")]
    public class TestContract : SmartContract
    {
        public static void Main()
        {
            Runtime.BurnGas(1000_00000000);
        }
    }
}
```
```
neo> list asset
NS1UwuWV1QM66cd5qUijU49BynLh3A5mFC
NEO: 0
GAS: 1550.0481014

NKwqsQzjiL9FZua7o6ARxaatqri3CxPCTC
NEO: 99999000
GAS: 51999009.1002312

----------------------------------------------------
Total:   NEO:   99999000     GAS:   52000559.1483326

NEO hash: 0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5
GAS hash: 0xd2a4cff31913016155e38e474a2c06d08be276cf

neo> deploy ./sc/DrainContract.nef
Contract hash: 0x75fa99793ece0eda8e7f89a862cc3fd7dc1ee78a
Gas consumed: 10.0106065
Network fee: 0.0172852
Total fee: 10.0278917 GAS
Relay tx? (no|yes): yes
Signed and relayed transaction with hash:
0xd7e51b7abcd0f3636704fc57552abcfcf9dae4d8a7207d23da3cc7084ddd3b7a

neo> invoke 0x75fa99793ece0eda8e7f89a862cc3fd7dc1ee78a main null NKwqsQzjiL9FZua7o6ARxaatqri3CxPCTC NKwqsQzjiL9FZua7o6ARxaatqri3CxPCTC
Invoking script with: 'wh8MBWRyYWluDBSK5x7c1z/MYqiJf47aDs4+eZn6dUFifVtS'
VM State: FAULT
Gas Consumed: 1000.0098676
Result Stack: []
Error: Insufficient GAS.
```

**Expected behavior**
Be able to send transactions in the `neo-cli` that burn gas.

**Platform:**
 - OS: Windows 11
 - Version: 3.6.2

**Comment by shargon** [comment]
Was is wrong computed?

**Comment by cschuchardt88** [comment]
@shargon 
> Was is wrong computed?

haven't looked into it.

Also we dont support contracts with `verify` method that has parameters in `NEP-6` or in `neo-cli`, but `Transaction.CalulateNetworkFee` has it supported. Also `Contract.Create` doesn't either

**Comment by Hecate2** [comment]
This is because, in
https://github.com/neo-project/neo/blob/1d957922a1aec90d0ec852402dc6eca496841ed4/src/Neo/SmartContract/ApplicationEngine.cs#L241-L246
the variable `gas_amount` is actually initiated with TestModeGas, which equals 20_0000_0000.

**Comment by Hecate2** [comment]
Using neo-fairy-test, set `"MaxGasInvoke": 20000,` in the `config.json` of Fairy,
```python
from neo_fairy_client import FairyClient

c = FairyClient(fairy_session='burn_gas')
c.set_gas_balance(1200_0000_0000, 'burn_gas', c.default_fairy_wallet_scripthash)
c.virutal_deploy_from_path('bin/sc/TestContract.nef')
c.invokefunction('main')
```
everything goes well.

**Comment by cschuchardt88** [comment]
@Jim8y @shargon can you we change that to use `GAS` `balance`?

**Comment by vang1ong7ang** [comment]
HAHAHAHAHA I don't know but probably just transfer the GAS to `0xdead0000....` to burn

`BurnGas` is LOLOLOLOL just burn the GAS from the tx sender
