### ISSUE TITLE
[`ApplicationEngine`] Add more `Testability` to `JumpTable`

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3226]
**Summary or problem description**
Most people do not want to have to write their own `SysCall` or `CallT` when creating an `ApplicationEngine` that uses `ApplicationEngine` class as its `base` class. They are `private` and should be `protected` as well as `DefaultJumpTable`.

The following codes shows a work around. So having these `private` dont make sense.

_See following PR #3225 for discussion and full workaround code_
```csharp
public class MyApplicationEngineProvider : IApplicationEngineProvider
{
    public static Action<ExecutionEngine, Instruction> Original_OnCallT { get; private set; };
    public static Action<ExecutionEngine, Instruction> Original_OnSysCall { get; private set; };

    public ApplicationEngine Create(TriggerType trigger, IVerifiable container, DataCache snapshot, Block persistingBlock, ProtocolSettings settings, long gas, IDiagnostic diagnostic, JumpTable jumpTable)
    {
        Original_OnCallT = jumpTable.CallT;
        Original_OnSysCall = jumpTable.Syscall;

        return new MyApplicationEngine(trigger, container, snapshot, persistingBlock, settings, gas, diagnostic, new MyJumpTable());
    }
}
```

**Do you have any solution you want to propose?**
Make the following `protected` for `testability` in `ApplicationEngine.cs`

**Variable(s)**
- _DefaultJumpTable_

**Methods**
- _OnSysCall_
- _OnCallT_

**Where in the software does this update applies to?**
- VM

@shargon @Jim8y @AnnaShaleva

**Comment by shargon** [comment]
Closed by https://github.com/neo-project/neo/pull/3225
