### ISSUE TITLE
checklist of 3.7.x PRs that will cause FORK

### ISSUE THREAD

**Issue by vang1ong7ang** [neo-project/neo#3233]
not seem to have learned from #2910, the new release of neo node (v3.7.x) still has some weaknesses that lead to fork

at least the following PRs are included:

- [x] #3158
- [x] #3209
- [x] #3172 
- [ ] #3130 it okay to ignore this if there's no node running on big-endian machines

risks caused by this situation have been explained in the discussion of #2910, but it is worth emphasizing that:

since the state between the old and new versions differs, any clients (exchanges and explorers included) that upgrade **before** or **after** the consensus upgrading are able to be cheated because there is always a window period in which their ledgers are different.

**Comment by shargon** [comment]
#3130 is for OS machine in `BigEndian`, and previously it doesn't work, so I think no one is affected, because they can't run a node

**Comment by vang1ong7ang** [comment]
since most of items are fixed in #3234, propose to close this issue

**Comment by Jim8y** [comment]
close as complete in #3234
