### ISSUE TITLE
Can't change Bind ip from 0.0.0.0 to 127.0.0.1

### ISSUE THREAD

**Issue by bizlevel** [neo-project/neo#324]
In config.json we have:
```
{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "Chain_{0}",
      "ApplicationLogs": "ApplicationLogs_{0}"
    },
    "P2P": {
      "Port": 10333,
      "WsPort": 10334
    },
    "RPC": {
      "Port": 10332,
      "SslCert": "",
      "SslCertPassword": ""
    },
    "UnlockWallet": {
      "Path": "",
      "Password": "neowalletpass",
      "StartConsensus": false,
      "IsActive": false
    }
  }
}
```

And no here IP port, host or etc. string for changing IP/interface.

In my case - it is no secure to use neo node in 0.0.0.0 interface,
And of course we even do not have any logs about connection to node!
P.S. --logs not work https://github.com/neo-project/neo/issues/228

How to be if i have several IPs ?

I All node use behing nginx and with this node it is impossible.
Please add new config string for that in new release.
Thanks.

**Comment by skinderis** [comment]
@erikzhang one more question that is relative to this issue topic.

Is it possible to add user and password for connections? To be able to connect only using credentials like **curl -u username:userpassword** <...>?

**Comment by erikzhang** [comment]
Yes. There has been an [implementation](https://github.com/neo-project/neo/pull/226).

But we finally intend to implement these features in the plugin.
