### ISSUE TITLE
Create a dockerfile for neo-cli to run and test basic functionalities

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3256]
Now that we have all necessary features in this repo, it is CRUCIAL to build and run a neo-cli client on EVERY commit and PULL REQUEST.

In this sense, as in the past, a good way to do that is to use a dockerfile and a script that initializes the client and test some functionalities such as consensus, wallet, among others.

In the past we have done that using `screen` command.
Thus, the first PRs will go in this direction.

This issue will be further updated to split the task into different parts.

- [x] Create a dockerfile that can build and run a neo-cli (can be dealt aligned with https://github.com/neo-project/neo/issues/3255)
- [x] Improve dockerfile or create a new one
- [ ] Create a folder with scripts that can initialize just run a client and verify if it has been initialized without a crash - use expect https://github.com/neo-project/neo/pull/3318
- [ ] Do some CI with devcontainer in order to ensure local development is working with generic paths

**Comment by vncoelho** [comment]
@cschuchardt88 , I am counting with you on this!

**Comment by vncoelho** [comment]
@cschuchardt88, perhaps that devcontainer CI will be great for now.

Here is the documentation https://github.com/devcontainers/ci

**Comment by vncoelho** [comment]
https://github.com/devcontainers/ci/blob/main/docs/github-action.md

**Comment by cschuchardt88** [comment]
I looked into everything, And read all docs. Its best to go with a `github` `action` `workflow` for this. One `big` reason is we don't have the storage for this.

**Comment by cschuchardt88** [comment]
Completed
