### ISSUE TITLE
Fix broken devcontainer version

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3258]
Devcontainer is running with problems on the current version,

Should be updated to a generic version as described here: https://github.com/devcontainers/images/tree/main/src/dotnet

![image](https://github.com/neo-project/neo/assets/17395762/6bfa8596-acfc-43a3-b589-7d7db80d5620)

**Comment by cschuchardt88** [comment]
Here is the real lists https://mcr.microsoft.com/en-us/product/devcontainers/dotnet/tags
