### ISSUE TITLE
[NEO.CLI] custom plugins won't shown by command `plugins`

### ISSUE THREAD

**Issue by lingyido** [neo-project/neo#3268]
**Describe the bug**
After upgrading to neo v3.7.4, the `plugins` command in neo-cli won't show custom installed plugins.

**To Reproduce**
1. Open the project, install any custom plugin
2. Type 'plugins'

**Expected behavior**
show custom plugin's information

**Screenshots**
<img width="582" alt="Screenshot 2024-05-23 at 13 38 39" src="https://github.com/neo-project/neo/assets/170338962/5ce5e04a-2690-455e-bf44-facbd4f3d362">

**Platform:**
 - Version [e.g. neo-cli 3.7.4]

**(Optional) Additional context**
This should be related to https://github.com/neo-project/neo/pull/3092.

I don't want to hurt someone here. But for NEO's stability, I personally suggest that you should pay more attention to https://github.com/cschuchardt88's PR. IIRC, https://github.com/neo-project/neo-modules/issues/897 also find some bugs introduced by cschuchardt88. He has introduced so many big PRs that changes a lot, especially there are many opening now. Let's move carefully.

**Comment by cschuchardt88** [comment]
That's a good point to bring. In #3092 the already existing code that was updated. Did display other plugins, only the plugins from `github`. We are going to be reworking this anyways. Because after this release plugins will not be at that URL anymore or that repo.

**Comment by shargon** [comment]
```
neo> plugins
[Not Installed]  ApplicationLogs
[Installed]      DBFTPlugin       @3.7.4  Consensus plugin with dBFT algorithm.
[Not Installed]  LevelDBStore
[Not Installed]  MPTTrie
[Not Installed]  OracleService
[Not Installed]  RocksDBStore
[Not Installed]  RpcClient
[Not Installed]  RpcServer
[Not Installed]  SQLiteWallet
[Not Installed]  StatesDumper
[Not Installed]  StateService
[Not Installed]  StorageDumper
[Not Installed]  TokensTracker
```

it works for me, could you give us more information?

**Comment by shargon** [comment]
I have an idea, I will fix it

**Comment by cschuchardt88** [comment]
Its for custom plugins, I'm guessing he has his only plugin that he made. 

https://github.com/neo-project/neo/blob/c8f933810d1f11fc2db4e90b7761c750a73ec22a/src/Neo.CLI/CLI/MainService.Plugins.cs#L231-L237 is the problem.

**Comment by lingyido** [comment]
> The problem is when the plugin list can't be retrieved, because it's wrong configured or a network error., fixed in #3269

I think that @cschuchardt88 fully understood what I problem I faced. I'm not sure if this PR fixed that problem. Apart from official plugins, I have my own plugins.

**Comment by vncoelho** [comment]
I see, @lingyido .

let's re-open in this case.

**Comment by lingyido** [comment]
@cschuchardt88 If you knew and tested that this issue has been fixed, please tell us and close this. I'm not sure that if @shargon get my point.

**Comment by vncoelho** [comment]
I will let you reopen.
