### ISSUE TITLE
[`neo-cli`] Enable any Command-Line Arguments to be used

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3275]
### Describe the bug
Someone has changed the way that `neo-cli`'s command-line works. You pass an argument that doesn't exists than the application throws error. This disables plugins from using `Environment.CommandLine`. 

### For Example _(LevelDbStore)_:
```csharp
if (Environment.CommandLine.Split(' ').Any(p => p == "/repair" || p == "--repair"))
    DB.Repair(Options.Default, path);
```

Now above code will never get triggered.

**Expected behavior**
Allow arguments that don't exist in `neo-cli` to be able to be accepted.

**Platform:**
 - OS: Windows 11
 - Version: `neo-cli` `3.7.4`

@Jim8y @shargon @AnnaShaleva

**Comment by Hecate2** [comment]
I think `Environment.CommandLine` is the command that starts Neo.CLI, instead of the commands written in Neo.CLI. We can have codes like this:
https://github.com/Hecate2/neo-fairy-test/blob/c76fa8d06918caceb37975f752c0a2994a6d846f/FairyPlugin.cs#L59-L60
for plugins to be invoked in Neo.CLI

**Comment by shargon** [comment]
That error comes with `System.CommandLine` maybe we can add an argument like `--extra=repair` in order to use the extra arguments?

**Comment by cschuchardt88** [comment]
> That error comes with `System.CommandLine` maybe we can add an argument like `--extra=repair` in order to use the extra arguments?

I been using `System.CommandLine` for some time _(everyday now)_ it doesn't work like that. You have to mess with the settings.
