### ISSUE TITLE
Use `internal` keyword for all future code.

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3276]
There is a lot of problems with allowing the classes to be `public`. One example is, everything we have now in code. Yes, you can say this is for others to access our blockchain or that it is the `sdk`. However this should be separated from the core code. Reason for, we can make the changes that we need without affecting `3rd parties`. Having a separate dedicated `sdk` just for `3rd parties` to use with `3rd party` features. Allowing all our current code to be `internal` and allow in the application we choose. This way people don't try to use our code and don't have to support something that was intended for internal use anyways.

@Jim8y @shargon @roman-khimov @superboyiii @AnnaShaleva @vncoelho 

Up for discussion.

**Comment by Jim8y** [comment]
agree

**Comment by shargon** [comment]
It's ok for me

**Comment by cschuchardt88** [comment]
Its agreed.
