### ISSUE TITLE
Remove all comments from JSON files

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo#3277]
While trying to parse [config.json](https://github.com/neo-project/neo/blob/master/src/Neo.CLI/config.json) and other config files with JSON tools like [jq](https://jqlang.github.io/jq/), it miserably fails.

The reason: someone thought it would be a good idea to add comments on a JSON file (e.g., [to the config.json of the Neo.CLI](https://github.com/neo-project/neo/blob/master/src/Neo.CLI/config.json#L9-L10), but maybe there are other places too), even if the JSON standard doesn't support any comments.

This makes life harder if developers use proper JSON validation tools. It simply fails.

My suggestion: remove all comments from all JSON-based config files. Please. 🙏 👍

**Comment by Jim8y** [comment]
we know json standard does not support comments. but we need to make the config file clear. and json config file is for neo-cli. other usage  can delete the comments at will.

**Comment by Jim8y** [comment]
we tried to replace it with ymal or xml, but turns out json is still the best solution with the best C# support and minumum change to the core.

**Comment by gsmachado** [comment]
I'm not challenging JSON. We should keep it. It's the best.

My suggestion: document config attributes+values in a markdown file, in the same folder, with all the info about attributes what are their effects, etc.

**Comment by shargon** [comment]
I said that when these comments was introduced, it's not in the standard, agree with remove them
