### ISSUE TITLE
Disimproved Error Message for RPC `getcontractstate`

### ISSUE THREAD

**Issue by mialbu** [neo-project/neo#3280]
**Summary or problem description**
The RPC `getcontractstate` returns an unintuitive error message when providing a script hash without a deployed contract: `Specified method is not supported.`. Previously (e.g., with `3.6.2`), it returned the message `Unknown contract` which is much more intuitive imo.

**Do you have any solution you want to propose?**
Provide a more concise error message in RPC `getcontractstate` when there's no deployed contract for the provided script hash.

**Where in the software does this update applies to?**
- Plugins
- RPC (HTTP)

**Comment by Jim8y** [comment]
<img width="1088" alt="Screenshot 2024-05-27 at 19 34 34" src="https://github.com/neo-project/neo/assets/10189511/f461294e-d97a-4304-adf0-e42bab29bc31">
<img width="869" alt="Screenshot 2024-05-27 at 19 34 47" src="https://github.com/neo-project/neo/assets/10189511/10edd389-b052-4fd7-837c-4fdcac7812fd">

It should be `Unknown contract`

**Comment by Jim8y** [comment]
I see the problem now. Will fix.
