### ISSUE TITLE
[**Support**] `verify` method parameters

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3289]
**Summary or problem description**
Add support for contract `verify` method parameter to used. 

### `NEP-6` states

`script` - is the script code of the contract. This field can be null if the contract has been deployed to the blockchain.

`parameters` - is an array of Parameter objects which describe the details of each parameter of the contract function. For more information about the Parameter object, see the descriptions in [NEP-3: NeoContract ABI](https://github.com/neo-project/proposals/blob/master/nep-3.mediawiki).

**Do you have any solution you want to propose?**
Add To:
1. **neo-cli** - creating transactions for `invoke`, `update`, `NEP-17`
1. **NEP-6** - be able to save parameter values. May need a new NEP proposal

**Where in the software does this update applies to?**
- CLI
- SDK

**Comment by roman-khimov** [comment]
I think it's perfectly supported already, maybe except for the neo-cli.

**Comment by superboyiii** [comment]
I don't understand it clearly... Do you mean supporting for invoking `verify`?

**Comment by lock9** [comment]
I didn't understand it either. What is the relationship between them?

**Comment by cschuchardt88** [comment]
You can pass parameters to a deployed contract's `verify` method. We current have support for this. But not in `neo-cli`.

**Comment by Jim8y** [comment]
> You can pass parameters to a deployed contract's `verify` method. We current have support for this. But not in `neo-cli`.

`verify` does not take parameters.

**Comment by shargon** [comment]
> > You can pass parameters to a deployed contract's `verify` method. We current have support for this. But not in `neo-cli`.
> 
> `verify` does not take parameters.

It could https://github.com/neo-project/neo/blob/fd1edf0ef20e80f2e22f2746d10b404920ca6461/src/Neo/SmartContract/Helper.cs#L335

**Comment by cschuchardt88** [comment]
> `verify` does not take parameters.

@Jim8y 
It does already take parameters. `NEP-6` states that. just need support in `neo-cli`.

**Comment by Jim8y** [comment]
NEP6 is a wallet standard, how come it can define a contract verify method?

**Comment by Jim8y** [comment]
> It could
> 
> https://github.com/neo-project/neo/blob/fd1edf0ef20e80f2e22f2746d10b404920ca6461/src/Neo/SmartContract/Helper.cs#L335

What you mean it could? I dont see anywhere a parameter of verify is used for any purpose. I can not 100% sure, can you please help me confirm that?

**Comment by Jim8y** [comment]
> > > You can pass parameters to a deployed contract's `verify` method. We current have support for this. But not in `neo-cli`.
> > 
> > 
> > `verify` does not take parameters.
> 
> It could
> 
> https://github.com/neo-project/neo/blob/fd1edf0ef20e80f2e22f2746d10b404920ca6461/src/Neo/SmartContract/Helper.cs#L335

Alright then. `-1`

**Comment by lingyido** [comment]
There are too many functions like `NotValidBefore` and `Conflict` as well as complicated `Witness-xxx` related things that NEO provided. Not all of them should be supported by every tool.
Even if we support them, I don't think the wallets and dAPPs as well as explorers would support them. Let the proficients utilize them by writing their own codes.

**Comment by cschuchardt88** [comment]
We don't have an official SDK, so we need to support them.

**Comment by lingyido** [comment]
> We don't have an official SDK

Yes. We have for each popular language. I bet you know https://github.com/neo-project/neo-devpack-dotnet which is for C#.

**Comment by cschuchardt88** [comment]
That's for building contracts `ONLY`. This has no control over node. What we are talking about is functionality for creating an transaction on-chain.

**Comment by lingyido** [comment]
> That's for building contracts `ONLY`. This has no control over node. What we are talking about is functionality for creating an transaction on-chain.

FYI, I know that neoburger build their own transactions that maintains the votes. How did them come this **without a SDK**?  https://github.com/neoburger/TEE

**Comment by lingyido** [comment]
Every possible tx could be built and serialized locally and send to the RpcServer by this method.
https://github.com/neo-project/neo/blob/2fa8f0c91f3814c4a3ac72e6107e8857d22a73e9/src/Plugins/RpcServer/RpcServer.Node.cs#L152-L158

**Comment by cschuchardt88** [comment]
> > That's for building contracts `ONLY`. This has no control over node. What we are talking about is functionality for creating an transaction on-chain.
> 
> FYI, I know that neoburger build their own transactions that maintains the votes. How did them come this **without a SDK**? https://github.com/neoburger/TEE

RCPClient
