### ISSUE TITLE
Congestion on the blockchain with 21 tx block free transactions

### ISSUE THREAD

**Issue by bpetridis** [neo-project/neo#329]
Created this topic to discuss potential stop-gaps that me be on the cards to address the congestion issues that have been negatively affecting the V2.0 block-chain of late. This has caused a lot of disruption especially to switcheo trading. It's not a great look. 

Wanted to open the floor to potential stop gaps that may be implemented for V2.0 whilst we await the longer term release of V3.0.

Let's try keep the comments productive.

**Comment by deanpress** [comment]
One option is for exchanges to introduce a priority GAS fee with user withdrawals so they're most likely included in the next block.

**Comment by saltyskip** [comment]
Yes Network fees are inevitable as the network continues to grow #326 is a proposal for alleviating some of the network fee pain away from users

**Comment by bpetridis** [comment]
Ideas,

- What about increasing the configruable block size from 500 to 1000?

- Making gas contributions mandatory for all trasnactions, even just a derived drop

- horizontal and vertical scaling of nodes

- implementing a detection method for spam transactions so that they are sent to the back of the queue, i know this could imply a form of sensorship, but it's a protective mechanism.

**Comment by jsolman** [comment]
I think eventually switcheo's operations will need to support fees. Congestion causing node issues will be fixed by mempool changes.

**Comment by RavenXce** [comment]
Switcheo already pays 0.001gas for all operations except for transferring out of contract

**Comment by RavenXce** [comment]
Btw we should just close the issue if it's not helpful and there are multiple other issues solving or describing the problem.

**Comment by bpetridis** [comment]
Yeah it's covered all over the place - no point keeping my initial rant open :-)
