### ISSUE TITLE
NEO faucet isn't working

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#3298]
**Describe the bug**
The faucet website isn't working: https://n3t5wish.ngd.network/#/
This faucet is the only one that gives NEO and not only GAS.

**To Reproduce**
1. Open https://n3t5wish.ngd.network/#/
2. Type your address and fill in the captcha / github
3. Click send. It will show a confirmation screen
4. Wait for the tokens to arrive (they won't).

**Expected behavior**
The faucet should send 50 NEO and 50 GAS to the address provided.

**Screenshots**
![Screenshot 2024-06-06 at 15 40 48](https://github.com/neo-project/neo/assets/38396062/07bf7526-90d6-4fea-b889-46f60a9657e1)

**Comment by lingyido** [comment]
It may related to https://github.com/neo-project/neo/issues/3296

**Comment by lock9** [comment]
Now it says "You have exceeded the number of requests allowed in one day. Please apply again tomorrow.". I just checked my transaction history and I can't find this transaction. I'll try again tomorrow

**Comment by lock9** [comment]
Hi. 

I just tested it and it still doesn't work (or the testnet RPC nodes are showing incorrect balances).

**Comment by dusmart** [comment]
@NGDAdmin @superboyiii could you pls take a look? We can not use the faucet, either.

**Comment by cschuchardt88** [comment]
Have you tried the one in `neo` discord (`the bot`)?

**Comment by lock9** [comment]
<img width="937" alt="Screenshot 2024-07-04 at 15 21 45" src="https://github.com/neo-project/neo/assets/38396062/f2c166e2-1bb1-4d70-a97a-9428aedd01b4">

@cschuchardt88 The bot only gives GAS, some users need NEO

**Comment by cschuchardt88** [comment]
@superboyiii need your help

**Comment by cschuchardt88** [comment]
Fixed now.
