### ISSUE TITLE
LevelDBBlockchain.cs  Persist Negativity Check

### ISSUE THREAD

**Issue by coranos** [neo-project/neo#33]
on line 512 in LevelDBBlockchain.cs, in the function Persist, in the case for IssueTransaction, the subtraction is not checked for overflow. this would allow you to issue more aassets than the available assets.

case TransactionType.IssueTransaction
assets.GetAndChange(result.AssetId).Available -= result.Amount;

**Comment by erikzhang** [comment]
The negativity check is in IssueTransaction.cs:
https://github.com/neo-project/neo/blob/master/neo/Core/IssueTransaction.cs#L68
