### ISSUE TITLE
stack size can exceed MaxStackSize

### ISSUE THREAD

**Issue by dusmart** [neo-project/neo#3300]
**Describe the bug**

You can make a large object larger than the limit `MaxStackSize`.

**To Reproduce**

```
invoke 0x179ab5d297fd34ecd48643894242fc3527f42853 bingo [{"type":"Integer","value":2000}]

AdAHEcAfDAViaW5nbwwUUyj0JzX8QkKJQ4bU7DT9l9K1mhdBYn1bUg==
```

**Expected behavior**

FAULT

**Screenshots**

<img width="813" alt="Screenshot 2024-06-07 at 13 06 17" src="https://github.com/neo-project/neo/assets/12573541/35d3f3e5-f8cc-4a3a-89f5-c31daaec836f">

**Platform:**
 - Version 3.7.4

**(Optional) Additional context**

I believe that `Runtime.Notify` should be blamed.

**Comment by dusmart** [comment]
It's very dangerous if someone can combine this with some O(n<sup>2</sup>) DoS attacks like what have been shown by @vang1ong7ang in the past.

**Comment by vang1ong7ang** [comment]
it breaks a fundamental assumption of neovm and it should be fixed soon and published

**Comment by dusmart** [comment]
With my careful construction, it can theoretically generate an array containing at least 10 million data which may cost ~10 hours.

```
invoke 0x179ab5d297fd34ecd48643894242fc3527f42853 maxSize  [{"type":"Integer","value":100000}]

// notice that each iteration will generate 100 new items to the result array
```
