### ISSUE TITLE
Local build fails on master branch at 38cc0e9

### ISSUE THREAD

**Issue by dusmart** [neo-project/neo#3305]
**Describe the bug**

I can not build NEO.CLI on `master` branch while I can on `v3.7.4`.

**To Reproduce**

1. `git clone https://github.com/neo-project/neo`
2. `cd src/Neo.CLI`
3. `dotnet publish -c release`

**Expected behavior**

`neo-cli` is built successfully

**Screenshots**

<img width="1013" alt="Screenshot 2024-06-08 at 12 57 22" src="https://github.com/neo-project/neo/assets/12573541/e6171d64-8a66-433b-945c-f94b17a9eef8">
<img width="1021" alt="Screenshot 2024-06-08 at 12 57 38" src="https://github.com/neo-project/neo/assets/12573541/05470437-4081-4a1b-b272-b1662b91a4ab">

**Platform:**
 - OS: macos-14.5, m1 chip
 - Version master at `38cc0e9`

**(Optional) Additional context**

Why it needs to access the root directory? My expect is to build it under current working directory's bin folder.

**Comment by cschuchardt88** [comment]
I had same problem. Its a `dotnet cli` bug with the property. See #3306

**Comment by cschuchardt88** [comment]
work around is use
```
dotnet build neo.sln --configuration Release
```

Than check `./bin/Neo.CLI`
