### ISSUE TITLE
dotnet publish doesn't work in plugin's project path

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#3344]
**Describe the bug**
dotnet publish doesn't work in plugin's project path. There shouldn't be multi targets in one project path.
![image](https://github.com/neo-project/neo/assets/38493437/cc75cf4e-0a9d-44f9-8934-6795a20b57c4)

**To Reproduce**
1. Go to a plugin's folder path
2. run `dotnet publish`

**Expected behavior**
Publish without any exceptions

**Comment by cschuchardt88** [comment]
This is a not a problem, It says in the message what to do. add `--framework net8.0` we do all the time.

**Comment by cschuchardt88** [comment]
Plus your in the wrong directory.

**Comment by cschuchardt88** [comment]
![image](https://github.com/neo-project/neo/assets/8141309/ca87d64f-d0f9-4402-9201-fc00091b6665)

**Comment by superboyiii** [comment]
> This is a not a problem, It says in the message what to do. add `--framework net8.0` we do all the time. Also this messes with `github` workflows actions.

Why we need to add additional arguments to publish a .NET 8.0 project with .NET 8.0 framework only? I think fix the workflow is more making sense.

**Comment by cschuchardt88** [comment]
> > This is a not a problem, It says in the message what to do. add `--framework net8.0` we do all the time. Also this messes with `github` workflows actions.
> 
> Why we need to add additional arguments to publish a .NET 8.0 project with .NET 8.0 framework only? I think fixing the workflow is more making sense.

It make prefect sense when we work with different `frameworks` like `dotnet` `standard`

**Comment by superboyiii** [comment]
https://github.com/neo-project/neo/pull/3320 does fix this.
