### ISSUE TITLE
Leveldb exception handle

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3356]
**Describe the bug**
Run a setup with 4 nodes running private net

**To Reproduce**
Start nodes and they will crash almost instantaneously

**Error**

```cs
dotnet: ./db/dbformat.cc:16: uint64_t leveldb::PackSequenceAndType(uint64_t, leveldb::ValueType): Assertion `seq <= kMaxSequenceNumber' failed.
```

**Comment by cschuchardt88** [comment]
Need more information.

**Comment by shargon** [comment]
Seems that the data is corrupted, it's a fresh installation?

**Comment by vncoelho** [comment]
fresh with master

**Comment by vncoelho** [comment]
> Seems that the data is corrupted, it's a fresh installation?

probably due to the unhanded exception management feature, but still did not investigate further.
It is easy to reproduce. Just run a node.

**Comment by Hecate2** [comment]
Is it because the 4 nodes are using the same directory for leveldb?

**Comment by cschuchardt88** [comment]
Based off the source code from you error, It look like this Your database is corrupt. try deleting it to see if the problem goes away.

Has to do with `Seeking` with `KeyComparator` source code says
```c
// User key has become shorter physically, but larger logically.
// Tack on the earliest possible number to the shortened user key.
```

**Comment by vncoelho** [comment]
> Based off the source code from you error, It look like this Your database is corrupt. try deleting it to see if the problem goes away.
> 
> Has to do with `Seeking` with `KeyComparator` source code says
> 
> ```c
> // User key has become shorter physically, but larger logically.
> // Tack on the earliest possible number to the shortened user key.
> ```

No @cschuchardt88 , it is a recent introduced problem.

**Comment by Jim8y** [comment]
its because you run too much node in the same machine that all use leveldb. Not a core problem

**Comment by vncoelho** [comment]
> its because you run too many nodes in the same machine that all use leveldb. Not a core problem. This happens every time when you run multiple nodes in the same machine. 

No. This is not true in my Setup.

**Comment by vncoelho** [comment]
Too much complaints and not a real investigation in a simple scenario.
The cause is that we now crash the clients with unhandled exception.

Without minimum tests the neo-cli will be unused until we implement the exception handle and find the BASIC problems.

**Comment by vncoelho** [comment]
https://github.com/neo-project/neo/pull/3366#issuecomment-2197371062

**Comment by Jim8y** [comment]
> Too much complaints and not a real investigation in a simple scenario.

You can say this when you locate the real problem.

We have being working like this for many years, and all of a sudden its all wrong, we all become complainers? And our work are lack of investigation products?

But code are there, pr are there, you were able to test, to review, to comment. We have followed your suggestion to leave it for a while to review. Actually that pr was there for a week before i collected sufficient review approvals. 

> The cause is that we now crash the clients with unhandled exception.

Funny part is we should have crashed with unhandled exception, unless we have set plugins to ignore unhandled exception. I would say that pr have found an issue, if any, instead of introduced an issue.

**Comment by AnnaShaleva** [comment]
> its because you run too many nodes in the same machine that all use leveldb

It was not a problem for me either, I used NeoBench to run 4-nodes and 7-nodes privnet with Dockerized C# nodes, and it was OK.

> i dont have a 4 nodes private net test environment.

I'd suggest you to use NeoBench, but it's not yet updated to use fresh monorepo, we have https://github.com/nspcc-dev/neo-bench/issues/175 for that.

**Comment by vncoelho** [comment]
> > its because you run too many nodes in the same machine that all use leveldb
> 
> It was not a problem for me either, I used NeoBench to run 4-nodes and 7-nodes privnet with Dockerized C# nodes on my single machine, and it was OK.
> 
> > i dont have a 4 nodes private net test environment.
> 
> I'd suggest you to use NeoBench, but it's not yet updated to use fresh monorepo, we have https://github.com/nspcc-dev/neo-bench/issues/175 for that.

Are you using leveldb? Maybe it was rocksdb instead. 

Were your experiments with master branch?
Mine just run now reverting the exception handle crash.

**Comment by cschuchardt88** [comment]
@vncoelho 
Are you sure you didn't run out storage _(disk space)_ on your containers?

**Comment by cschuchardt88** [comment]
Can doing `./neo-cli /repair` or `neo-cli.exe /repair`

**Comment by vncoelho** [comment]
> Try doing `./neo-cli /repair` or `neo-cli.exe /repair`

This is not the case, @cschuchardt88 .

The testing environment is the same for testing with and without the PR being reverted.
The problem is that leveldb probably regenerates from the crash, but the PR that handles exception detects it and then crash the client.

The behavior may not the wrong. But before merging that PR this should had been tested because the problem is simple to be seen.
Can you verify that @superboyiii ?

**Comment by cschuchardt88** [comment]
can you add `--blame-crash` to `dotnet test` to make sure.

**Comment by Jim8y** [comment]
> > its because you run too many nodes in the same machine that all use leveldb
> 
> It was not a problem for me either, I used NeoBench to run 4-nodes and 7-nodes privnet with Dockerized C# nodes on my single machine, and it was OK.
> 
> > i dont have a 4 nodes private net test environment.

i would love to argue, but i am not an expert of leveldb, all i can 

say is now it happened, and apparently a leveldb exception, not related to the core.

**Comment by vncoelho** [comment]
> > > its because you run too many nodes in the same machine that all use leveldb
> > 
> > 
> > It was not a problem for me either, I used NeoBench to run 4-nodes and 7-nodes privnet with Dockerized C# nodes on my single machine, and it was OK.
> > > i dont have a 4 nodes private net test environment.
> 
> i would love to argue, but i am not an expert of leveldb, all i can
> 
> say is now it happened, and apparently a leveldb exception, not related to the core.
> 
> possible reasons could be: platform, os, version, dependencies. i would suggest to try rockdb and memorydb as well.

So, this error without the Exception Handle was good and safe to run a node?
Now, after the PR the node is broken, right?Is it not a core problem?

**Comment by cschuchardt88** [comment]
Just do `repair` on `db`. It's a corruption problem or a harddisk error read. 

#### We need more information on your setup :
1. are you using a `container`?
2. what `version` of `leveldb` you have?
3. what `CI` build you using?
4. What `filesystem`?
5. What `Operating System`?
6. What `CPU` arch?
7. Have you tried `leveldb` `repair?
8. How many `threads` does you `OS` limit?
9. Have you ran `filesystem` repair tool?
10. Does this happen on other setups?
11. What's your node setup?

**Comment by vncoelho** [comment]
I

> It's a corruption problem.
> #### We need more information on your setup :
> 
>     1. are you using a `container`?
> 
>     2. what `version` of `leveldb` you have?
> 
>     3. what `CI` build you using?
> 
>     4. What `filesystem`?
> 
>     5. What `Operating System`?
> 
>     6. What `CPU` arch?
> 
>     7. Have you tried `leveldb` `repair?
> 
>     8. How many `threads` does you `OS` limit?
> 
>     9. Have you ran `filesystem` repair tool?
> 
>     10. Does this happen on other setups?
> 
>     11. What's your node setup?

it is all dockerfile in a container with the amount of threads that is necessary for it to run safe....It can safely run a node on mainnet with the resources it have available.
It is running perfect without the commit I said that should be reverted until fixed.

The problem could be due to some limitation on leveldb safe off course. But that should be handled before the PR was merged.
Furthermore, In my last tests rocksdb was also broken.

Only way to run a node nowdays is memorystore.

**Comment by vncoelho** [comment]
Still crashing. I thought it was solved but my config was with "MemoryStore" instead.

The problem persist even updating all libraries for dotnet during build and run.

RocksDb is also corrupted. But perhaps a difference reason.

**Comment by Jim8y** [comment]
I will setup a multi-nodes on my machine, will check it.

**Comment by gsmachado** [comment]
not entirely related, but see https://github.com/neo-project/neo-express/issues/455

**Comment by cschuchardt88** [comment]
fixed
