### ISSUE TITLE
version error 1.0.0

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#3357]
![image](https://github.com/neo-project/neo/assets/17395762/7b7164b0-3571-4479-9abd-ea4a150c3870)

![image](https://github.com/neo-project/neo/assets/17395762/5fb6a68c-2ac9-40f4-8964-d91d8436542c)

**Comment by cschuchardt88** [comment]
Resolved in `github` workflow actions. No longer maintained in a `Directory.Build.props`
