### ISSUE TITLE
Can't transfer all the nep-5 asset to another address in one transaction by neo-cli2.7.6.1

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#337]
During my test of nep-5, I discovered that I can't transfer all the nep-5 asset in one transaction by neo-cli2.7.6.1. For example, I had 50 DBC in my wallet. When I transfer 50 DBC to another address, it shows "Insufficient funds". But I can transfer less than 50 DBC to another address. This issue can also happen on neo-cli 3.0.0 preview2.
![image](https://user-images.githubusercontent.com/38493437/44085431-25320816-9fec-11e8-9c37-f95fc95699ec.png)
![image](https://user-images.githubusercontent.com/38493437/44085472-400c6398-9fec-11e8-8911-012350da187b.png)

**Comment by Sinepitis** [comment]
Do you have multiple addresses in your wallet?

**Comment by superboyiii** [comment]
@Sinepitis No, just a single address.

**Comment by wy** [comment]
Can you send 49.9 or 49.999? Not sure how many decimal places DBC has? @superboyiii

**Comment by vncoelho** [comment]
Hi @superboyiii, has this been solved?

**Comment by superboyiii** [comment]
@vncoelho Hi, Victor. Not absolutely sure, but it seems never happens again even during my test. Maybe this issue could be closed.
