### ISSUE TITLE
List Plugins Display Showing Wrong Files

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3381]
**Describe the bug**
Once the Plugins are added to this repo. The `plugins` command in the `neo-cli` will display all the files in `latest` release which will include _`see screenshot`_.

**To Reproduce**
#### config.json
```json
"Plugins": {
  "DownloadUrl": "https://api.github.com/repos/neo-project/neo/releases"
}
```

#### Type: `neo> plugins`

**Expected behavior**
Find an efficient way of to filter out filenames that are not plugins.

**Screenshots**
![image](https://github.com/neo-project/neo/assets/8141309/a58062f1-897c-45a5-826b-fff7d87b8ad9)

**Platform:**
 - OS: Windows 11
 - Version 3.7.5

@neo-project/core

**Comment by shargon** [comment]
If this is critical, what category is if we find something... critical?

**Comment by cschuchardt88** [comment]
I think it's critical. Can cause more problems for new user. Don't want them to download the `neo-cli` and try to use it as plugin.

**Comment by Hecate2** [comment]
By the way, is it OK to print some info before the HttpClient starts to visit GitHub? For users with slow Internet, the CLI seems "critically" stuck when `plugins` is executed.
```csharp
        [ConsoleCommand("plugins", Category = "Plugin Commands")]
        private void OnPluginsCommand()
        {
            ConsoleHelper.Info("Getting plugin list from GitHub...");
```
