### ISSUE TITLE
Extend `Designated` native RoleManagement events with old/new public keys

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo#3389]
**Summary or problem description**
Issue migrated from https://github.com/neo-project/neo/issues/3386#issuecomment-2202514326.

`Designation` RoleManagement events include only role and block height, whereas it would be useful for users to track the previous and updated set of designated public keys, exactly like it's done for `CommitteeChanged` events.

**Do you have any solution you want to propose?**
Extend `Designation` event with two arguments: `old` and `new` Arrays of public keys.

**Where in the software does this update applies to?**
- Native contracts

**Comment by cschuchardt88** [comment]
completed
