### ISSUE TITLE
Unique type of transactions

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#339]
In NEO 2.x, we have many different types of transactions:

   - MinerTransaction
   - IssueTransaction
   - ClaimTransaction
   - EnrollmentTransaction
   - RegisterTransaction
   - ContractTransaction
   - StateTransaction
   - PublishTransaction
   - InvocationTransaction

Most of them are obsolete, and the remaining types of transactions can be easily implemented in smart contracts. The only thing we need to keep is `InvocationTransaction`.

**Comment by igormcoelho** [comment]
Fully agreed... the simple the better.

**Comment by shargon** [comment]
Agree too

**Comment by penlite** [comment]
Is it worth keeping MinerTransaction or do all of these things become sub-types of InvocationTransaction? @erikzhang

**Comment by shargon** [comment]
Could be closed @erikzhang ?
