### ISSUE TITLE
Transaction.cs verify, case falthrough.

### ISSUE THREAD

**Issue by coranos** [neo-project/neo#34]
in Transaction.cs line 360, in the function Verify, the case statement for TransactionType.MinerTransaction falls through to TransactionType.ClaimTransaction.

Unless I misunderstood the whitepaper, this is incorrect as MinerTransaction does not issue SystemCoin Assets, so it should fail verification if any SystemCoin assets are issued as part of a MinerTransaction

**Comment by erikzhang** [comment]
There are three ways to gain gas (which is SystemCoin). 

1. system fee
2. network fee
3. block bonus

The ClaimTransaction handles 1st and 3rd, and the MinerTransaction handles 2nd.
