### ISSUE TITLE
Readonly Storage for NeoContract

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#341]
Abstract
========

The readonly storage can be written once by the contract and can no longer be modified.

This is useful for storing data that should not be modified, such as total amount of tokens, digital identity information, and so on.

Specification
=============

Design
------

1. Add `readonly` flag to `StorageItem`. If a `StorageItem` has a `readonly` flag with a value of `true`, then it cannot be modified or deleted. In the other word, it should cause the two APIs, `Storage.Put` and `Storage.Delete`, to fail. But it has no effect on `Storage.Get`.

1. For old contract data, their `readonly` flag should be set to the default value `false` to keep backward compatibility.

1. To write a `readonly` data, you need to call a new API: `Storage.PutEx`. It is similar to `Storage.Put`, but adds a parameter of type `StorageFlags`. If the parameter is set to `StorageFlags.ReadOnly`, then the data written by it will be marked as `readonly`. The readonly data can be read by `Storage.Get`.

1. `Storage.PutEx` costs the same as `Storage.Put`.

1. The data written by `Storage.PutEx`, whose `key` cannot be duplicated with other data, including those written by `Storage.Put`.

1. When `Storage.PutEx` is executed with `StorageFlags.ReadOnly`, if it is found that writable data of the same key already exists, then this data will be marked as `readonly`.

1. Each contract can only store up to 10KB of `readonly` data. If this limit is exceeded, the readonly writing operation will fail.

1. When the contract is upgraded by the `Contract.Migrate` API, all the `readonly` flags of the stored data will be set to `false`. This means that when the contract is upgraded, you will get an opportunity to modify the `readonly` data.

New APIs
--------

1. StorageFlags *(enum)*

   ```c#
   [Flags]
   enum StorageFlags : byte
   {
       None = 0,
       ReadOnly = 0x01
   }
   ```

1. Storage.PutEx *(method)*

   ```c#
   void PutEx(StorageContext context, byte[] key, byte[] value, StorageFlags flags)
   ```

Backwards Compatibility
=======================

For old contract data, their `readonly` flag can be set to the default value `false` easily to keep backward compatibility.

**Comment by igormcoelho** [comment]
Fully agreed!

**Comment by igormcoelho** [comment]
How will it be implemented? GetReadonlyStorageContext?

**Comment by erikzhang** [comment]
Maybe `System.Storage.PutReadonly`.

**Comment by deanpress** [comment]
Will the storage items be separate from writable storage? So you can have a key `abc` in ReadOnly storage + `abc` in writable storage.

**Comment by shargon** [comment]
The read logic should be equal?

**Comment by erikzhang** [comment]
> Will the storage items be separate from writable storage? So you can have a key `abc` in ReadOnly storage + separate `abc` in writable storage.

I don't think that read-only storage should be separated from read-write storage. A unified set of reading and writing methods should be provided.

**Comment by penlite** [comment]
I agree - all you need is some identifier that will cause Storage.Put and Storage.Delete to fail. Whether is separated as @deanpress says or not separated should be implementation detail but invisible at call level.

**Comment by erikzhang** [comment]
@igormcoelho @deanpress @shargon @penlite 
I updated the specification of this proposal.

**Comment by shargon** [comment]
Very useful for `totalSupply` and other variables 👍

**Comment by igormcoelho** [comment]
This one is perfect Erik!! Ready to cook xD

**Comment by igormcoelho** [comment]
Good, I like short names :)

**Comment by shargon** [comment]
`PutConst` maybe

**Comment by erikzhang** [comment]
This is not just about changing the name, it also adds a parameter `flags` to the method and extends the functionality in the future.

**Comment by igormcoelho** [comment]
Shargon, read the goddamn specification xD hahaha I didnt see that flag change too...   ;)  Erik, any "feelings" of possible extensions to the flags, or will just leave open to the future? I agree with the flags and name PutEx anyway.

**Comment by erikzhang** [comment]
Volatile?

**Comment by igormcoelho** [comment]
Exactly that! very good Erik :)

**Comment by shargon** [comment]
PutEx then :)
