### ISSUE TITLE
Add support to verify message without hashing 

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#3418]
**Summary or problem description**
I'm using the following method to verify a signature: `crypto.VerifyWithECDsa(message, publicKey, signature, crypto.Secp256k1Sha256)`
This method will hash the message and check the signature against the message hash. The problem is when we need to verify a payload directly without hashing it (when the data is already hashed). Without this, you can't verify a signature against a transaction hash - you don't have access to the whole transaction, just the hash.

**Do you have any solution you want to propose?**
We need a verify method that verifies the payload without hashing it.

**Where in the software does this update applies to?**
- Compiler
- VM

Edit: Is it possible to retrieve the network magic from a smart contract?

**Comment by Hecate2** [comment]
@lock9 Use `System.Runtime.GetNetwork` to get network magic from smart contract

**Comment by shargon** [comment]
> We need a verify method that verifies the payload without hashing it.

We need to hash it before verify it

**Comment by lock9** [comment]
I found a way to achieve what I needed. This is not required anymore. Thanks
