### ISSUE TITLE
Store contract ABI on the blockchain

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#343]
I believe it's very important to have contract ABI stored on the blockchain.
Best place would be together with RPC call `getcontractstate`, besides returning `parameters`, `returntype`, `name`, ..., `properties`, `description`, then `abi : {}`. It could be empty for current deployed contracts (or they could add info on a future migration).
To implement it, it could be an optional field in `Contract.Create` function... if stack is empty, do not try to get `abi` string parameter.

**Comment by erikzhang** [comment]
Maybe we can add an `abi` method to this NEP, which describes the url of the contract ABI.
https://github.com/neo-project/proposals/pull/46

**Comment by igormcoelho** [comment]
I thought about this Erik... but the problem is that you spend gas on a regular invocation, and this is the kind of thing that should be provided publicly (in fact, using the ABI you will be able to know which methods to invoke.... including this "abi" method). Do you think it's possible to add an optional argument in Contract.Create, verifying if stack is empty?
