### ISSUE TITLE
Add base64UrlDecode to StdLib native contract

### ISSUE THREAD

**Issue by EdgeDLT** [neo-project/neo#3451]
**Summary or problem description**

I need to be able to parse a `base64Url`-encoded string in a smart contract. Currently we have to manually convert it to `base64`  first in order to use `base64Decode`, which is hacky:

```go
output := make([]byte, len(input))
copy(output, input)

for i := 0; i < len(output); i++ {
    if output[i] == '-' {
        output[i] = '+'
    } else if output[i] == '_' {
        output[i] = '/'
    }
}
padding := (4 - (len(output) % 4)) % 4

for i := 0; i < padding; i++ {
    output = append(output, '=')
}

return output
```

It would be preferable to have a `base64UrlDecode` method available in the `StdLib` instead. I don't believe we have a use for `encode`, but I'm sure someone else eventually will, so consider that too.

**Where in the software does this update applies to?**
- Native contract
- SDK

**Comment by cschuchardt88** [comment]
Added to `HF_Echidna`
