### ISSUE TITLE
Remove `MaxStackSize` and reduce `MaxItemSize` and `MaxInvocationStackSize`

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#347]
The limit `MaxStackSize` have a hight computational cost

https://github.com/neo-project/neo/blob/master/neo/SmartContract/ApplicationEngine.cs#L267-L294

and more precisely

https://github.com/neo-project/neo/blob/b5926fe88d25c8aab2028c0ff7acad2c1d982bad/neo/SmartContract/ApplicationEngine.cs#L291

I think that we can remove this check and reduce `MaxInvocationStackSize` to 512 and `MaxItemSize` to 512 * 1024

What do you think @erikzhang ?

**Comment by erikzhang** [comment]
If we do this, how can we prevent memory from being occupied by many 512*1024 size items?

**Comment by shargon** [comment]
If we control the max items in InvocationStack and ItemStacks, we should be able to limit this without sum all
