### ISSUE TITLE
[`Bug`]:  concurrency conflict in `BloomFilter.Add`

### ISSUE THREAD

**Issue by nan01ab** [neo-project/neo#3497]
**Describe the bug**
`Neo.Cryptography.BloomFilter.Add` uses `AsParallel` to set `bits`, but `bits.Set` is not concurrency safe.
```csharp
        public void Add(ReadOnlyMemory<byte> element)
        {
            foreach (uint i in seeds.AsParallel().Select(s => element.Span.Murmur32(s)))
                bits.Set((int)(i % (uint)bits.Length), true);
        }
```
So `Check` may get false even if the element has been `Add`(some bits may not set correctly because of  concurrency conflict), and this does not conform to the semantics of the `BloomFilter`.

`Murmur32` is fast enough, and the element won't be very long, so `AsParallel` isn't necessary here, I think.

**Comment by cschuchardt88** [comment]
The only thing that is `Parallel` is the query. The `foreach` loop isn't.

**Comment by nan01ab** [comment]
> The only thing that is `Parallel` is the query. The `foreach` loop isn't.
> 
> Now if it was `await foreach` that would be different.

Yes
