### ISSUE TITLE
Remove obsolete transaction attributes

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo#3505]
**Summary or problem description**
#3488 marks some of transaction attributes as obsolete.

**Do you have any solution you want to propose?**
Once 3.8.0 is released we need to remove obsolete transaction attributes that were deprecated in #3488.

**Where in the software does this update applies to?**
- P2P (TCP)

**Comment by cschuchardt88** [comment]
#3488 wasn't merged. @AnnaShaleva Can be close this?

**Comment by AnnaShaleva** [comment]
Yes, closing as not planned.
