### ISSUE TITLE
Neoscan and Neotracker not matching funds in limbo for a week.

### ISSUE THREAD

**Issue by boxer252006** [neo-project/neo#351]
I made a transfers from My Neon wallet to my Bitfi wallet.  Neotracker shows the funds as in the Bitfi wallet, neoscan shows the funds as in the Neon Wallet. When I log into Neon I can see the funds in the Neon wallet but any attempted transactions fail.  How can this be resolved? 
![2db6afc7-4e68-4233-be4f-3a94d0654109](https://user-images.githubusercontent.com/42528292/44527914-c8f27800-a6c2-11e8-8df1-bd13e73d9f4b.png)
![5063bbce-3097-4916-bcf7-982e18461a55](https://user-images.githubusercontent.com/42528292/44527915-c98b0e80-a6c2-11e8-9885-aeb136d26428.png)

**Comment by erikzhang** [comment]
Can you provide your TXID (transaction id)?

**Comment by boxer252006** [comment]
224c009af7bc57936cedd9c6b3f6567064b2c60df936e8084b06cafe810bef9e

**Comment by f27d** [comment]
Started looking at this.
https://neotracker.io/block/height/2623809 - 47 txs
https://neoscan.io/block/DFAC69377247DC953A3D479E3A0BEF1F06CE47FFA261A8E7390D6CEFE955FDDB - 17 txs
Size, blockhash and merkle root are all different.

**Comment by wy** [comment]
@erikzhang after reviewing all RPC nodes for this blockhash, it looks like the majority view is that 0xef934051c6732b415de63222790aea4fe78dacb6723cb14a0803c72fe35e836a is the correct blockhash (47 txs including the transfer of the NEO that original poster was expecting).

NEOScan and several other nodes are showing 0xdfac69377247dc953a3d479e3a0bef1f06ce47ffa261a8e7390d6cefe955fddb instead.

I have polled all the RPC nodes that Happynodes sees @PeterLinX.

Here is the gist showing node address versus blockhash for this blockid. @fabwa 

https://gist.github.com/wy/8f08765f66f564f7db8fff4cb8bbff28

@erikzhang is it possible to check what the consensus nodes agree is the right Blockhash?

**Comment by wy** [comment]
https://github.com/CityOfZion/neo-scan/issues/332
This is a known issue @adrienmo for the NEO SCAN node.

We should close this issue and you should wait on 332 in the neo-scan repo @boxer252006 sorry for the inconvenience.

**Comment by boxer252006** [comment]
Hi what does that mean? Is there any sort of idea on timeline for this to be fixed?
