### ISSUE TITLE
`StackItem.GetHashCode` probably shouldn't throw any `Exception`.

### ISSUE THREAD

**Issue by nan01ab** [neo-project/neo#3544]
According to the C# Specification, `GetHashCode()` must have some properties, for example:
> The [GetHashCode()](https://learn.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=net-8.0#system-object-gethashcode) method should not throw exceptions.

So, `StackItem.GetHasoCode` probably shouldn't throw any Exception.

But in current implementation, `StackItem` may throw exceptions in some cases:
* `CompoundType.GetHashCode` throws `NotSupportedException` directly;
* The default implementation of `StackItem.GetHashCode` is to compute the HashCode of `GetSpan`, but `GetSpan` throw an `InvalidCastException` in default.

**Where in the software does this update applies to?**
- VM

**Comment by cschuchardt88** [comment]
I think #3531 fixes that.
