### ISSUE TITLE
Limit the maximum block size to 256 KB

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#359]
In order to prevent the block data from growing too fast, it is necessary to limit the maximum size of each block.

**Comment by decentralisedkev** [comment]
How did you decide on 256KB?

**Comment by wy** [comment]
Is there currently a limit? How do you pick which tx's to drop (based on the priority sorting order) or random?

**Comment by erikzhang** [comment]
There is currently no limit.

**Comment by wy** [comment]
To help with the discussion @erikzhang, @decentralisedkev, I looked at 287 thousand blocks in recent history (June-Aug 2018). Of them, there is only 15 above 256KB (262144 bytes). That's less than 0.0052% of blocks.

**Comment by vncoelho** [comment]
Good data and precise studies.

**Comment by jsolman** [comment]
- Would this be necessary if there were a workable type of throttling for bad actor addresses? 
- As normal usage increases and hardware of nodes and networking improve, shouldn't this value need to increase also? 

I added a comment on the end of issue #357 concerning a potential solution to throttle bad actors for which I've started drafting a NEP.

**Comment by vncoelho** [comment]
@erikzhang, do you still believe that this is necessary?

Maybe with the correct Economic model and the refined verification+application layers we are not going to need to have this limit.

However, since blocks can be faster this can also be a good practice for the P2P decentralization.

**Comment by erikzhang** [comment]
I think we can set the maximum block size in `PolicyContract`.

**Comment by vncoelho** [comment]
Ok, @erikzhang, so, still proceed with this idea, right? 
Remembers me BTC, BCH. aheuaheuahea In our case, from BCH to BTC...

@shargon, @igormcoelho, @jsolman, limit or not limit, this is the question...aheuahuea

**Comment by shargon** [comment]
We must implement the max, is totally needed.
