### ISSUE TITLE
New API for NeoContract: Neo.ClaimTransaction.GetClaims

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo#360]
Returns the claims of the given `ClaimTransaction`.

High level use-case: consider a smart contract that is payable, accepts NEO and holds that NEO on behalf of a user. The user then withdraws the NEO. Using this api, the smart contract could allow the user to claim GAS for the NEO the smart contract was holding for them.

Technical: this API would only ever be used during verification, since a ClaimTransaction cannot result in the Application trigger. During the Verification trigger, the smart contract could, as an example, check that there is exactly one output address and that the claimed inputs correspond to the outputs the output address owns.

**Comment by dicarlo2** [comment]
@erikzhang does this seem reasonable? If so, I might go ahead and implement it in neo-one, I'm working on a few example contracts and this would be very useful for one of them.

**Comment by igormcoelho** [comment]
Its interesting @dicarlo2 but I guess regular verification already allows that.. no ? It just depends on the contract owner to keep a record of claimable addresses and use regular claim transaction I think.

**Comment by dicarlo2** [comment]
@igormcoelho This supports the scenario where the contract does not have an owner and must rely on alternative logic to determine if a claim is valid.

**Comment by dicarlo2** [comment]
It would be good if we could also add `Neo.ClaimTransaction.GetClaimReferences` which returns the outputs the claims refer to.

**Comment by shargon** [comment]
In neo 3, the claim will disappear so i think that we can can close this issue
