### ISSUE TITLE
Display or Disconnect Issue

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo#3602]
**Describe the bug**
This video shows that we are getting disconnected from all clients.
https://github.com/user-attachments/assets/40704ca3-0fd0-4467-95e5-a16e4ed090bf

**Could be**
1. dotnet 9.0
2. new Akka.net version

**Comment by shargon** [comment]
Let's revert net 9

**Comment by Hecate2** [comment]
Got `throw new FormatException()` at `public static NodeCapability DeserializeFrom(ref MemoryReader reader)` at src\Neo\Network\P2P\Capabilities\NodeCapability.cs
Not necessarily from .net 9

**Comment by Hecate2** [comment]
https://github.com/neo-project/neo/pull/3582

**Comment by chenzhitong** [comment]
before https://github.com/neo-project/neo/pull/3582 run correctly
![image](https://github.com/user-attachments/assets/1c56d5cb-cfa2-4def-9c7a-ad0c72a8af56)

after https://github.com/neo-project/neo/pull/3582 failure to run
![image](https://github.com/user-attachments/assets/f516f89b-7dc9-4990-8692-6334c826ed93)

**Comment by chenzhitong** [comment]
I debugged and found that all nodes except the seed node are `NodeCapabilityType.WsServer`

![image](https://github.com/user-attachments/assets/9d1c32fb-8af1-4bd4-8ebb-63ba3400429c)

**Comment by shargon** [comment]
@chenzhitong could you fix it?

**Comment by vncoelho** [comment]
perhaps it is not that they are really using WS server but something related to an if with such capaciblity.
We can check later
