### ISSUE TITLE
New API for NeoContract: Neo.Iterator.Concat

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo#361]
Similar to `Neo.Enumerator.Concat`, it concatenates two iterators.

**Comment by erikzhang** [comment]
What if there are duplicate `Neo.Iterator.Key`s?

**Comment by dicarlo2** [comment]
Should be fine no? We're just running one iterator after another.

**Comment by erikzhang** [comment]
Are we going to allow duplicate keys in iterators?

**Comment by jsolman** [comment]
There isn't anything that will technically cause an issue if it iterates duplicate keys is there?
