### ISSUE TITLE
Allow arrays in Neo.Iterator.Create

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo#362]
`Neo.Iterator.Create` with an array returns an iterator over the values with the index of the value as the key.

**Comment by dicarlo2** [comment]
@erikzhang this is blocking NEO-ONE TypeScript Smart Contracts - are there objections to adding this functionality?

**Comment by igormcoelho** [comment]
Very important feature!

**Comment by dicarlo2** [comment]
Awesome! Thanks @erikzhang!! One step closer to MainNet TypeScript smart contracts :)
