### ISSUE TITLE
All exception for RPC now all return code 500

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#3629]
**Describe the bug**
In current master branch, all exception for RPC now all return code 500. But it should return clear error code case by case.

**To Reproduce**
1. Set up a node by code from `master`. Try any rpc request, type an invalid or unknown parameter. In this example, I tried to getapplicationlogs for an unknown txid
2. Request body:
```
{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["0x3b5641d801f153c15d27f19102a14b495b7f8db905195851b35940343d4f7147"],
  "id": 1
}
```
3. Now you get `500 Internal Server Error`

**Expected behavior**
The response should include:
```
"code": -32602,
        "message": "Invalid params - Unknown transaction/blockhash
```

**Screenshots**
![1734408185195](https://github.com/user-attachments/assets/28f4f703-d5da-428b-859a-857af52d6662)

**Platform:**
All

**Comment by Hecate2** [comment]
https://github.com/neo-project/neo/blob/71aac332ede0c5aea2eb8ad0f101770266755a52/src/Plugins/RpcServer/RpcServer.cs#L314-L328
The exceptions thrown are actually RpcExceptions, but they are not caught.
