### ISSUE TITLE
Structs should be cloned on `Neo.Enumerator.Value` and `Neo.Iterator.Key`

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo#364]
AFAICT structs are supposed to be value types, i.e. copy whenever moved, at least based on this commit: https://github.com/neo-project/neo-vm/commit/ab74c36117ef1afa5ccf80e326655598fd4012d5.

If that's the case, then they need to be cloned when they're accessed from an enumerator/iterator.

**Comment by erikzhang** [comment]
@dicarlo2 Do you think we should revert the commit: neo-project/neo-vm@ab74c36?

**Comment by erikzhang** [comment]
@dicarlo2 Because of its breaking existing contracts, I have revert that commit.

https://github.com/neo-project/neo-vm/commit/ab5f939529eb7527f08b36949269ffd171821f03

**Comment by dicarlo2** [comment]
@erikzhang this issue is also blocking NEO-ONE TypeScript smart contracts for the same reasons as https://github.com/neo-project/neo-vm/issues/63. Can we reopen?
