### ISSUE TITLE
Export contract storage to disk

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#369]
Dear all, is there any tool to export a contract storage or the whole storage to disk (json or binary)?
It would be nice to have a simple standard made for this (similar to the .acc file), even if output file is huge. The idea is to export storage (per contract, or the whole one) and we simply apply a SHA256 over this file to generate a certificate.
We have many other threads thinking on better ways to audit storage/notifications, but I believe this is the simplest way possible to create a general audit and easily unite/fix available blockchain implementations.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-plugins/tree/master/StatesDumper

Is this what you need?

**Comment by igormcoelho** [comment]
That's amazing Erik! So fast! We will learn how to use it here, and start taking measurements.

**Comment by vncoelho** [comment]
O.o, It is impressive.
Exactly this, precisely.

**Comment by igormcoelho** [comment]
```cat dump.json 
[{"key":"31423ccd56db46959de976735133bbc67c22302e4572696b0000000000000000000000000c","value":"00055a68616e67"},{"key":"31423ccd56db46959de976735133bbc67c22302e5475646f0000000000000000000000000c","value":"0003426f6d"}]
```
