### ISSUE TITLE
Installing errors on Ubuntu 16.04: when installing dotnet-dev-1.0.4 getting errors with dotnet-sharedframework-microsoft.netcore.app-1.0.4 & dotnet-sharedframework-microsoft.netcore.app-1.1.1

### ISSUE THREAD

**Issue by eladelrom** [neo-project/neo#370]
Running Ubuntu 16.04, last step produce errors:

`> sudo apt-get install dotnet-dev-1.0.4`

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-dev-1.0.3 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.4 but it is not going to be installed
                    Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.1 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Workaround:**

```
> sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
> sudo apt-get update
```

Then i was able to install dotnet-dev-1.0.4 and went back to:

`> sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'`

**Comment by igormcoelho** [comment]
I strongly suggest that, for NEO and dotnet, you use our image for Ubuntu 18.04: https://github.com/NeoResearch/neocompiler-eco/tree/master/docker-ubuntu-dotnet
It already solves many problems regarding dotnet, and we use it for C# compiler and neo-cli nodes.

**Comment by eladelrom** [comment]
I pasted the complete instructions to set up and get a published DLL from the source code on Ubuntu 16.04: [https://gist.github.com/eladelrom/0025a93927bf5a14fa4f52360cfbf8ab](https://gist.github.com/eladelrom/0025a93927bf5a14fa4f52360cfbf8ab)

**Comment by igormcoelho** [comment]
Oh! Nice tutorial, congratulations! Problem is solved?

**Comment by Mingege-cc** [comment]
@eladelrom dotnet sdk is'nt v2.0 ?

**Comment by vncoelho** [comment]
I believe this problem has been solved. However, fell free to reopen if any doubt is still open.
