### ISSUE TITLE
How to create raw transaction?

### ISSUE THREAD

**Issue by borovik96** [neo-project/neo#377]
Where can I find information about the protocol for transaction schema? 
I found this https://github.com/neo-project/neo/wiki/Network-Protocol document but it is unclear how to build tx.

**Comment by saltyskip** [comment]
I wrote a decent guide here, it is a bit old, but will help you get started

https://steemit.com/neo/@saltyskip/creating-a-light-client-for-neo-a-blockchain-developer-s-gateway-drug

https://github.com/CityOfZion/neo-swift/blob/master/NeoSwift/Account.swift#L115

**Comment by borovik96** [comment]
Anyway, I will need to use https://github.com/CityOfZion/neon-wallet-db or is there another way to get UTXO for an address?

**Comment by saltyskip** [comment]
Yes you need some sort of database that keeps tracks of all the associated UTXO's for a given address.

**Comment by borovik96** [comment]
That is sad, but thanks for reply
