### ISSUE TITLE
Please add getaddr to JSON-RPC

### ISSUE THREAD

**Issue by coranos** [neo-project/neo#39]
Please add the getaddr functionality to JSON-RPC.

I'd like to be able to display a map of all the NEO nodes and their current NEO version by geocoding their IP addresses, but that information is only available via the binary port 10333.

This will also allow me to display and debug network splits and versioning inconsistencies. For example some seeds are currently on 2.0.1 and some on 2.0.0.

I'd love to show the same information, for all nodes, but to do that currently requires me to make a custom neo-cli RPC. (sending getaddr through port 10333 without doing the verack handshake just gives back the version response from neo-cli 2.0.1).

host:seed1.neo.org; label:version; userAgent:/NEO:2.0.0/; port:10333; startHeight:1198745; timestamp:1501323224; services:1; 
host:seed2.neo.org; label:version; userAgent:/NEO:2.0.0/; port:10333; startHeight:1198745; timestamp:1501323225; services:1; 

host:seed3.neo.org; label:version; userAgent:/NEO:2.0.1/; port:10333; startHeight:1198745; timestamp:1501323226; services:1; 
host:seed4.neo.org; label:version; userAgent:/NEO:2.0.1/; port:10333; startHeight:1198326; timestamp:1501323229; services:1; 
host:seed5.neo.org; label:version; userAgent:/NEO:2.0.1/; port:10333; startHeight:1198115; timestamp:1501323237; services:1;

**Comment by erikzhang** [comment]
resolved in #40
