### ISSUE TITLE
RPC test invokes running out of GAS

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#396]
Users in the Discord #support channel have reported instances of Neon token balances not displaying, while NEO/GAS balances were correct. I traced this to an RPC issue in Neo 2.9.0 nodes.

Due to the refactoring that occurred in (#288) `ApplicationEngine.Run` can now be passed the optional `testMode` flag directly, which defaults to false.

However, the `invoke*` RPC calls in RpcServer.cs still call `ApplicationEngine.Run(script)` only, meaning the invocation will *not* run in test mode, and will abort after exceeding 10 GAS in execution time.

The token balance query in Neon requires far more than 10 GAS to execute due to the large number of NEP-5 contracts now deployed on the network. So the FAULT condition in 2.9.0 `invokescript` calls leads to no tokens being displayed.

I believe the `GetInvokeResult` call in RpcServer.cs should pass `testMode=true` to `ApplicationEngine.Run` to return to the previous behavior.

**Comment by jsolman** [comment]
RpcServer still should still have some GAS limit to protect itself from malicious script hogging CPU, but yeah, it should allow more than 10 GAS.

**Comment by jsolman** [comment]
It's up to owners of RPC nodes to allow more than 10 GAS at this point. Nodes default to 10 to protect from long running scripts on public nodes by default.

**Comment by ThomasLobker** [comment]
Would it be an idea to use `getstorage` instead? I think all NEP-5 contracts are using the same key for the user balance, which is the NEO address. It would speed things up, since requests don't have to go through a NeoVM instance.
