### ISSUE TITLE
Consensus sync

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#398]
I see that the conensus sync logic was removed but the log still there, there is something wrong here @erikzhang or with the refactoring was moved this logic to other site?

Before:

https://github.com/neo-project/neo/commit/c64748ecbac3baeb8045b16af0d518398a6ced24#diff-0285c1c12d1d492897a99ffe07f9fed9L226

After:

https://github.com/neo-project/neo/blob/d66281fa898e6aecfcdaba0fc3d9c06cffeee869/neo/Consensus/ConsensusService.cs#L197

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/d66281fa898e6aecfcdaba0fc3d9c06cffeee869/neo/Network/P2P/TaskManager.cs#L136-L147

Now `TaskManager` can handle block synchronization very well.

**Comment by shargon** [comment]
Ok Thanks for the clarification!
