### ISSUE TITLE
Maybe just one node can cause the neo network down? 

### ISSUE THREAD

**Issue by Mingege-cc** [neo-project/neo#403]
#### case 1
If one consensus node continue to send different **ChangeView**(new view number) event to the other consensus nodes, this may cause the system cannot  reach a consensus on **ChangeView**, therefore, no new block can be made.

code in ConsensusService.cs

```cs
 private void OnChangeViewReceived(ConsensusPayload payload, ChangeView message)
{
        Log($"{nameof(OnChangeViewReceived)}: height={payload.BlockIndex} view={message.ViewNumber} index={payload.ValidatorIndex} nv={message.NewViewNumber}");
       if (message.NewViewNumber <= context.ExpectedView[payload.ValidatorIndex])
               return;
       context.ExpectedView[payload.ValidatorIndex] = message.NewViewNumber;
       CheckExpectedView(message.NewViewNumber);
}

private void CheckExpectedView(byte view_number)
 {
        if (context.ViewNumber == view_number) return;
        if (context.ExpectedView.Count(p => p == view_number) >= context.M)
        {
             InitializeConsensus(view_number);
        }
 }
``` 

#### case 2
In my local private network, the **Ontimeout** mechanism  will also cause delays in reaching **ChangeView** consensus.

**Comment by Mingege-cc** [comment]
#### case 3
One node can send **ChangeView** event ( set specific  new_view_number , leads PrimaryIndex = Myindex, which means the node is always Primary node), get different Block signatures and fork the neo network.

**Comment by erikzhang** [comment]
I don't think these "attacks" can be successful.
