### ISSUE TITLE
Handling notifications on a local node

### ISSUE THREAD

**Issue by yasenm** [neo-project/neo#404]
In previous versions of NEO, there was an API to listen for smart contract executions on your local node. For example on NEO v2.7.61 there was the ApplicationExecuted event on LevelDBBlockchain class, which would broadcast information about each execution of a smart contract on the node, including a collection of all Notifications created by Runtime.Notify in the contract execution. This event - ApplicationExecuted is gone now, along with the LevelDBBlockchain class. Does anybody know if there is an alternative way to do this in v2.9?

**Comment by erikzhang** [comment]
`ApplicationExecuted` is not gone:

https://github.com/neo-project/neo/blob/9e3c08f4f411e0a9557a96de6def9bcef1ee6c3f/neo/Ledger/Blockchain.cs#L26

It becomes to a message and will be sent when persisting blocks:

https://github.com/neo-project/neo/blob/9e3c08f4f411e0a9557a96de6def9bcef1ee6c3f/neo/Ledger/Blockchain.cs#L582-L587

You can handle this message. Here is an example:

https://github.com/neo-project/neo-plugins/blob/master/ApplicationLogs/Logger.cs

**Comment by yasenm** [comment]
Thank you for the very fast response. We will dive into it.
