### ISSUE TITLE
Private Chain created by neo-cli2.9.0 isn't able to be connected by other nodes

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#412]
I've found that privatenet created by neo-cli2.9.0 isn't able to be connected by other nodes whether neo-cli or neo-gui.

**Comment by belane** [comment]
Have you tried https://github.com/CityOfZion/neo-privatenet-docker/pull/58 ?

**Comment by superboyiii** [comment]
@belane not yet. Just create it by neo-cli.

![image](https://user-images.githubusercontent.com/38493437/46944551-ec271b80-d0a4-11e8-847c-336440fa837b.png)
![image](https://user-images.githubusercontent.com/38493437/46944560-f34e2980-d0a4-11e8-8906-776e8a9fbf25.png)
![image](https://user-images.githubusercontent.com/38493437/46944567-f8ab7400-d0a4-11e8-8db1-ab9663efa2ea.png)

**Comment by vncoelho** [comment]
@superboyiii, I think that we can close this, right? It should be probably related to an old configuration of max connections.
