### ISSUE TITLE
Transactions should contain the height of the latest block

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo#414]
Transactions should contain the height of the latest block so that we can clear the old transactions from the memory pool after a certain number of blocks. And users can also know how long their transactions will expire if they are not confirmed.

**Comment by igormcoelho** [comment]
Very good idea Erik! I guess this also helps solving this https://github.com/neo-project/neo/issues/371, which is being done to protect users, but it's not mandatory.

**Comment by jsolman** [comment]
I actually think it should be the responsibility of transactions to determine how long they are valid rather than the nodes to impose a max time they are valid. As long as the pool isn’t full and therefore ejecting transactions,  if I want my transaction to stay valid for a week or some long amount of time until it is either confirmed by a CN and makes it into a block or gets ejected due to the max pool size and sorting ejecting it, shouldn’t NEO support that use case?

**Comment by jsolman** [comment]
Why not just make the max pool size smaller and let them naturally drop out due to sort order?

**Comment by belane** [comment]
where would the block number be added, in the remark or in a new field?
Should the hash of the previous block also be included to guarantee that the transaction has been created at the moment?

**Comment by shargon** [comment]
This could be used as nonce, and help with https://github.com/neo-project/neo-gui/issues/252

**Comment by erikzhang** [comment]
> where would the block number be added, in the remark or in a new field?

In new filed I think.

**Comment by igormcoelho** [comment]
> What happens if this field is fake, and people send a value higher than they have? you don't know if this block exists

@shargon, I think we should include block height and block hash. If P2P gets a message with height superior than existing one, it's dropped automatically.

**Comment by igormcoelho** [comment]
@jsolman as soon as we have this height, we establish some limits. What is reasonable in practice? 10 blocks ahead? 100 blocks? 1000 blocks? all of them are possible, but without this height we will never be able to put any limit.

**Comment by jsolman** [comment]
I think the concept of @igormcoelho script solves the problem if sender wants their transaction to expire. Do we want to keep this open?

**Comment by shargon** [comment]
i like your proposal igor :)
