### ISSUE TITLE
getaccountstate function only return two asset

### ISSUE THREAD

**Issue by Cobb-Chang** [neo-project/neo#416]
why this function only return two assets in one account? how can i get whole assets information in an account?

**Comment by Cobb-Chang** [comment]
> This refers to the native Assets NEO and GAS. To get NEP-5 token balances you would need to query the contract directly or use an external API that aggregates all of that balance information

Thanks for your reply.
if there any instruction about above two method?  where i can find it?

**Comment by apisit** [comment]
you can find more info here http://docs.neo.org/en-us/exchange/v2.9.0.html   
Section `Querying User Balance`

**Comment by Cobb-Chang** [comment]
> you can find more info here http://docs.neo.org/en-us/exchange/v2.9.0.html
> Section `Querying User Balance`

Thank you

**Comment by saltyskip** [comment]
@Cobb-Chang can you please close this issue if your question has been answered
