### ISSUE TITLE
how to get the transfers records in one address?

### ISSUE THREAD

**Issue by Cobb-Chang** [neo-project/neo#417]
could you tell me how to get transfer records? where can i find the way? thanks a lot

**Comment by igormcoelho** [comment]
What do you mean by transfers records? Is it Neo or Gas (UTXO asset) or other assets such as NEP-5?
If it's NEP-5 asset/token, we are collecting the whole Neo history in this storage audit project: https://github.com/neoresearch/neo-storage-audit
So here you will find all data regarding NEP-5 past transfers, although not fully organized yet. 
If it's a UTXO asset, you can navigate through a blockchain explorer (neotracker, neoscan,...) and find the past transactions in the history of any address.

**Comment by jseagrave21** [comment]
@Cobb-Chang you can query a neo-python REST server to see all transfer notifications for a specific address for example, `http://108.252.121.18/v1/notifications/addr/<addr>`

**Comment by jsolman** [comment]
Use an explorer or a wallet that supports showing transfers. Neo core does not. Some plugins for Neo core could be written that would provide these services, but since it costs whoever maintains them, they probably won't be in the base RpcServer at any point.
