### ISSUE TITLE
Pay by time on mempool

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#427]
Talking to @vncoelho, one idea came to mind... I think we could establish (network gas) prices for transactions to apply for mempool for a given time. This time can be calculated on timestamp or block height, and can be implemented with or without this feature here: https://github.com/neo-project/neo/issues/414 (because we can simply use scripts to validate transaction expiration times).

Example: Block Height is 1000 now. If I submit a free transaction, it should include an expiration script for at most 3 or 5 blocks (after that, it expires). If I pay 0.00001 GAS, then my transaction can last 10 blocks... 0.00002 for 20 blocks... price increases if I want it to be valid for more time. Long time-to-live pays more, shorter pays less (or zero). It's very easy to implement, what does the community think of it?

Another possibility for nodes is to give priority to tx near expiration, so long term spam tx will be double punished.

**Comment by igormcoelho** [comment]
I think this NEP would help a lot to easily create such transaction detection: https://github.com/neo-project/proposals/pull/67

**Comment by saltyskip** [comment]
Can it not just include an expiration script, and then the wallet provider is the one that determines the appropriate fee give the expiration script?

EG
In wallet user sets 50 blocks time to live, wallet generates the included expiration script, and displays the recommended fee of 0.XXX. This fee is attached, and not extra work is required by the nodes themselves?

Do you have example of such an expiration script btw

**Comment by igormcoelho** [comment]
In fact, the wallet will be responsible for attaching Gas, but P2P nodes will need to verify it anyway. So, the rule must be public. Waiting for advances here: https://github.com/neo-project/neo/pull/443

**Comment by ThomasLobker** [comment]
I like the idea that a transaction has a setting that defines the time to live. But to charge more GAS for a longer time to live goes against the idea that high priority transactions should already be charged more. So if you pay more and you can choose between high priority or high time to live, then anyone would go for high priority.

How about allowing a time to live to be set by the user, without charging him extra fees? Default is 10 blocks, but a user can change this to any number between 1 and 100 for example.

**Comment by belane** [comment]
Agree with @ThomasLobker, it doesn't make much sense to pay for time in the mempool when you have already paid for a priority.

**Comment by jsolman** [comment]
With my latest mempool changes I think this discussion is not important; the mempool will be able to be full all the time with negligible performance impact to nodes and lower fee transactions will drop off naturally
