### ISSUE TITLE
Allow setting an upper limit on connected nodes

### ISSUE THREAD

**Issue by jsolman** [neo-project/neo#431]
Currently nodes running the Neo core don’t really have an easy way (that I am aware of) to limit how many nodes can connect to them. Running a more powerful node (even one without a public DNS entry advertised) will result in potentially more nodes connecting to them from my observation. For purposes of running a custom RpcServer and serving certain data to clients this is not ideal.

**Comment by jibbah777** [comment]
Implement auto-gas claim and/or only distribute when blocks are quiet and/,or limit gas claims to x amount per day dependant on network activity reducing the amount of transactions

**Comment by jsolman** [comment]
This issue is not related at all to a high number of transactions. It is related to a max for a peers number of connected nodes.

**Comment by igormcoelho** [comment]
Good idea @jsolman, I believe it should be easy to implement and leave a configuration entry on client.

**Comment by igormcoelho** [comment]
You mean, a parameter similar to this: https://github.com/neo-project/neo/blob/c401c058c8776f3148aa6b82a4cb13106e482ff0/neo/Network/P2P/Peer.cs#L27
But regarding different addresses?

**Comment by jsolman** [comment]
I've implemented changes.
