### ISSUE TITLE
Neo  coins do not show in wallet while they are in my address

### ISSUE THREAD

**Issue by rdehosson** [neo-project/neo#45]
Today I transferred 10 neo into my neo wallet. However they do not show, while they are in my address.

The receiver address is: AXmAcTbCGJ14ww2E4e2J3LLgryToAFepZQ
Tx is: 916098048af68dad91a32de63a9074768ea244be815628035006fe5b2a4d0b38

I am using the web wallet

**Comment by erikzhang** [comment]
You need to make it full synchronized.
