### ISSUE TITLE
session.Version.StartHeight is often lagged

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#459]
`TaskManager` function private void `RequestTasks(TaskSession session)`  is often informing a very lagged `session.Version.StartHeight`.

This variable directs influence the request of blocks that a node needs: 
Example of log:
`RequestTasks Blockchain.Singleton.Height=93 Blockchain.Singleton.HeaderHeight=93 session.Version.StartHeight=3`

**Comment by vncoelho** [comment]
Command show state is another example

![image](https://user-images.githubusercontent.com/17395762/48280142-e8837c00-e439-11e8-818b-b12a4ac989eb.png)

**Comment by jsolman** [comment]
StartHeight is meant to be the height of the node at the time the session began; however, if a new block is received and blocks were skipped there probably should be some logic to go and request the missing blocks from connected nodes.

**Comment by jsolman** [comment]
If we had a way of ranking connected nodes, we could ask some of the connected nodes with the highest rank.

**Comment by vncoelho** [comment]
I do not think that #464  will really destroy the network, because ask something to a lagged node does not means much because it already delayed...aehauheuaea

But a tool for updating StartHeight would be great as well as ranking the nodes.
Ranking the nodes makes more sense.

But I am not sure if those would be good strategies for decentralized P2P, @jsolman. In the way it is right now it is simply designed as connecting to everybody and asking.
While the other strategy would have a rule and filters for selecting nodes.

**Comment by jsolman** [comment]
I think the main issue with #464 is that when fully synced that code path wasn't meant to be requesting information from all nodes. It probably wouldn't destroy the network, but it wouldn't be optimal. Gating based on the StartHeight restricts the audience once fully synced.

**Comment by vncoelho** [comment]
I agree, @jsolman.

It was a way to promote awareness about the issue, I think most part of the problem have been solved with the last PRs.

We still have some problems. I need to further investigate the P2P disconnection and connection between nodes and how this `StartHeight` is updated.
