### ISSUE TITLE
Revert TriggerType.Application requirements in syscalls

### ISSUE THREAD

**Issue by dicarlo2** [neo-project/neo#465]
The Actor refactor added a new requirement that the trigger type is `TriggerType.Application` to several syscalls:

 - Neo.Contract.Destroy: https://github.com/neo-project/neo/blob/master/neo/SmartContract/StandardService.cs#L588
 - Neo.Storage.Put[Ex]: https://github.com/neo-project/neo/blob/master/neo/SmartContract/StandardService.cs#L601
 - Neo.Storage.Delete: https://github.com/neo-project/neo/blob/master/neo/SmartContract/StandardService.cs#L641
 - Neo.Asset.Create: https://github.com/neo-project/neo/blob/master/neo/SmartContract/NeoService.cs#L494
 - Neo.Asset.Renew: https://github.com/neo-project/neo/blob/master/neo/SmartContract/NeoService.cs#L539
 - Neo.Contract.Create: https://github.com/neo-project/neo/blob/master/neo/SmartContract/NeoService.cs#L660
 - Neo.Contract.Migrate: https://github.com/neo-project/neo/blob/master/neo/SmartContract/NeoService.cs#L702

This is problematic for NEO-ONE TypeScript smart contracts because we abstract away triggers entirely from the user. NEO-ONE smart contracts, instead, simply run the same exact code during the verification trigger as the application trigger. 

Prior to this change, all of these calls were allowed during the Verification trigger, they just had no effect because the storage changes were not committed. As far as I can tell, this should be true after the Actors refactor and it should be safe to just remove these checks.

This is blocking for NEO-ONE TypeScript smart contracts.

**Comment by igormcoelho** [comment]
Interesting point indeed... it looks like Verifications end up here: https://github.com/neo-project/neo/blob/ecb9b15d0cc1241ed8cca4853de50de33861e4c0/neo/SmartContract/Helper.cs#L108
But what happens to Snapshot changes? Are they always dropped? :thinking: 

From a consensus perspective, it looks like it is "born" here https://github.com/neo-project/neo/blob/97bc193786a1c620fdba4ab3d738cc86f26dcc50/neo/Consensus/ConsensusContext.cs#L129 and dropped here only after the whole process is done: https://github.com/neo-project/neo/blob/97bc193786a1c620fdba4ab3d738cc86f26dcc50/neo/Consensus/ConsensusContext.cs#L54 (or after reset new block)

So, I may be wrong, but perhaps any verification could be able to actually create contracts or assets if this is executed. So these changes would be really necessary. Am I missing something?

**Comment by dicarlo2** [comment]
> So, I may be wrong, but perhaps any verification could be able to actually create contracts or assets if this is executed. So these changes would be really necessary. Am I missing something?

I think snapshots need to be "committed" in order for them to change the underlying storage, but I may be mistaken.

> Btw, congratulations for the amazing work with neo-one :)

Thanks!

**Comment by vncoelho** [comment]
@dicarlo2, as pointed out by you in the issue, maybe this can now be closed.
