### ISSUE TITLE
question about getapplicationlog

### ISSUE THREAD

**Issue by bixf** [neo-project/neo#467]
when i use "getapplicationlog" to get the information  about a tx, i get this output:
`"notifications": [
                    {
                        "contract": "0xacbc532904b6b51b5ea6d19b803d78af70e7e6f9",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteArray",
                                    "value": "7472616e73666572"
                                },
                                {
                                    "type": "ByteArray",
                                    "value": "fd8d0f84b8db897d6eebe3e0177ed5c5b47fc322"
                                },
                                {
                                    "type": "ByteArray",
                                    "value": "0908069411353706d16d898201980e847dfabc32"
                                },
                                {
                                    "type": "ByteArray",
                                    "value": "8096980000000000"
                                }
                            ]
                        }
                    }
                ]
`
in the official documentation, “fd8d0f84b8db897d6eebe3e0177ed5c5b47fc322” and "0908069411353706d16d898201980e847dfabc32" are the from and to address. but how can they be transformed to normal addresses? i am using java.

**Comment by vncoelho** [comment]
Hi, @bixf, we probably need to revert this addresses and convert.

![image](https://user-images.githubusercontent.com/17395762/48479245-e9c3f880-e7ed-11e8-83d0-babc17ea461a.png)

Check it out at https://neocompiler.io/#/ecolab tab Conversors.

**Comment by txhsl** [comment]
> but how can they be transformed to normal addresses? i am using java. 

Just like the steps that @vncoelho showed here, convert the ByteArray from `byte[] Hex` to `UInt160  ScriptHash`, then to `string Address`.
And if you need some reference in Java coding, try the [NEO-SDK](https://github.com/neo-ngd/neoj).
