### ISSUE TITLE
crashing when signing signed payload

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#472]
Signing a signed `Consensus Payload` was crashing our experiments until we discover that we were doing something wrong.

However, I think that signing a signed payload should clean the previous signature and works normally.

**Comment by erikzhang** [comment]
Can you show me the code that went wrong?

**Comment by vncoelho** [comment]
Yes, but we already fixed it and I would need to checkout to some code.
However, it was the following case:

* Primary `A` generated a `PrepareRequest Payload` and B has `SignatureSent Flag`
* View changed
* New Speaker `B` was using the same `PrepareRequest Payload` and Signing it again with `SignPayload`: https://github.com/neo-project/neo/blob/40f76d24b5d529d267bcad535a100b4376027703/neo/Consensus/ConsensusContext.cs#L149

It was crashing and returning error.

As you may see, there was a conceptual error and we fixed it by generating a new `PrepareRequest Payload` completely made but with the same transactions (because of the flag `SignatureSent`).

However, the source of the problem may be a little deeper, that is why I thought about opening this issue.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/40f76d24b5d529d267bcad535a100b4376027703/neo/Network/P2P/Payloads/ConsensusPayload.cs#L17

**Comment by vncoelho** [comment]
Maybe yes, Erik, I would need to test again... I will take a try later today.

**Comment by vncoelho** [comment]
Checked, @erikzhang.
I think It was fixed, maybe it was something related to the size of the payload and wrong deserialization of something related to it.

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/48838557-de357c00-ed6f-11e8-867c-a92420220c4b.png)

In this experiment, all Backups tried to signed the Payload given by the Speaker.
Only the Speaker survived, other crashed as mentioned above.

**Comment by jsolman** [comment]
Is this issue relevant to the current code?

**Comment by vncoelho** [comment]
I think that this was an old issue, maybe it is not relevant anymore, let me inspect.
