### ISSUE TITLE
Why are blocks created with only the miner transaction when the mempool has transactions

### ISSUE THREAD

**Issue by jsolman** [neo-project/neo#474]
As an example from block 2994791 to 2995091, 5 of the 7 consensus nodes seem to be generating blocks with only the miner transaction. I haven't looked into why this is, but would like to know the root cause if it is known. What is the root cause? Is a solution to this currently in progress?

**Comment by vncoelho** [comment]
This is something I have been questioning for a long time, Jeff.

Since you detected that 5 of 7 CN maybe they are not communicating with the seed nodes RPC and receiving the TXs beforehand. 

The root cause of this surely impacts other aspects.

**Comment by vncoelho** [comment]
I think that there is not a solution in progress, @jsolman.
#459  and #462 may be related to this.
I also opened an issue in the Akka repository and they tried to help. We detected that the problems were in the Neo constructor.
By removing the lines on PR #469 some errors disappear related to the Akka start after initialization.

I think that by tackling the root causes of this will be quite important.

**Comment by jsolman** [comment]
#487 may have made this unlikely to happen again. 

I've been rewriting the mempool code to be more efficient and not reverify all transactions after each block is persisted, but just the ones that will potentially make it into the next block. I should have a PR out probably in the next 24 hours.I may include something that will make it impossible for fill to get no transactions also with the change, so this won't be possible to happen again.
