### ISSUE TITLE
System.MissingFieldException: Field not found: 'Neo.NeoSystem.ActorSystem'.

### ISSUE THREAD

**Issue by blatechen** [neo-project/neo#476]
anyone help me. I am run neo-cli --rpc, but it error.
I run it in ubuntu os.
this is its error messages.
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingFieldException: Field not found: 'Neo.NeoSystem.ActorSystem'.
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at Neo.Plugins.Plugin.LoadPlugins(NeoSystem system)
at Neo.Shell.MainService.OnStart(String[] args)
at Neo.Services.ConsoleServiceBase.Run(String[] args)
at Neo.Program.Main(String[] args)
Aborted (core dumped)

**Comment by erikzhang** [comment]
Are you using old neo-cli with latest plugins?

**Comment by blatechen** [comment]
> Are you using old neo-cli with latest plugins?

neo-cli version v2.9.2
plugin version v2.9.0
ApplicationLogs
ImportBlocks

**Comment by blatechen** [comment]
> Are you using old neo-cli with latest plugins?

I try download plugin version v2.9.2 and it's can running.
Thank you for your help.
