### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by sctxm** [neo-project/neo#477]
There is no class InteropService in NeoVM 2.3.2, and Neo2.9.2  SmartContract. StandardService cannot be compiled.

**Comment by erikzhang** [comment]
You need to reference NeoVM via nuget:

```
Install-Package Neo.VM -Version 2.3.2
```

The master branch is the latest development branch.

**Comment by sctxm** [comment]
Thank you for your reply. We are using Neo source for development.

**Comment by vncoelho** [comment]
@sctxm, I believe that this issue was solved, right?
Fell free to reopen if you encounter any problem.
