### ISSUE TITLE
Pass ApplicationExecutionResult to IPersistencePlugin

### ISSUE THREAD

**Issue by RavenXce** [neo-project/neo#480]
Can we add pass `execution_results` to the `IPersistencePlugin`s as well here?

https://github.com/neo-project/neo/blob/77ae33547d301d54fa8addc100df341267d72374/neo/Ledger/Blockchain.cs#L505
https://github.com/neo-project/neo/blob/77ae33547d301d54fa8addc100df341267d72374/neo/Ledger/Blockchain.cs#L608

We want to persist the notifications that happened, and don't want to use the async version in `IActorRef`s as we need guaranteed writes (we want to abort persist if our plugin fails).

Alternatively, having a blocking version of the Actor plugins would work too.

**Comment by vncoelho** [comment]
@RavenXce, useful thing, it would be nice to have this notification tool inside neo-cli as @localhuman suggested #352.

Now, considering this `OnPersist` plugin it will probably be easier and simpler.

**Comment by RavenXce** [comment]
@vncoelho since `OnPersist` is blocking and called just before `Commit`, simply throwing when an unrecoverable error occurs (such as persistent failure to connect to a remote db) within the plugin should crash the whole app, aborting persisting of the block. An external supervisor can reboot the node if required.

**Comment by vncoelho** [comment]
I got, it, the external supervisor reboot is the part I thought to be more complex, anyway...

But why a notification plugin should avoid a block to persist if all verification's passed until that moment, would not it be a selective `Block filter plugin`?

**Comment by erikzhang** [comment]
Because it may be that something went wrong, and we don't want to miss this block and resynchronize.
