### ISSUE TITLE
Why every bolck Validator is same? 

### ISSUE THREAD

**Issue by i359** [neo-project/neo#481]
Why every bolck Validator is same? 
always is ANuupE2wgsHYi8VTqSUSoMsyxbJ8P3szu7,thanks!

Pls refer to the below linkage:
https://blolys.com/#/mainnet/blocks

**Comment by igormcoelho** [comment]
I don't know this blockchain explorer, but In fact, Validator must refer to the multi-sig contract formed by all consensus nodes public keys. So, it looks like one, but if you look at miner transaction and block signatures you will see which nodes actually signed each block.

**Comment by i359** [comment]
@igormcoelho ，Thank you for your answer.
