### ISSUE TITLE
neo-cli privatnet isn't able to be connected by external nodes which is on the same machine using the same ip address

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#488]
I find that neo-cli privatnet isn't able to be connected by external nodes which is on the same machine with consensus nodes, using the same ip address. The four consensus nodes is in four cmd, not in docker.

**Comment by steven1227** [comment]
@superboyiii I think It works now when I tried the current version of neo-cli. This issue can be closed

**Comment by shargon** [comment]
If the problem still happens, be free to reopen the issue
