### ISSUE TITLE
Nep-5 transaction isn't able to be transfered if it's contained in one of the outputs within UTXO

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#490]
Nep-5 transaction isn't able to be transfered if it's contained in one of the outputs within UTXO. It could be met when making several outputs in one transaction by neo-gui or other client. In this transaction, UTXO could be successfully transfered but nep-5 failed. However, the txid could be found by "getapplicationlog" API, but nothing is in "notifications" array.
For example, in testnet, this txid could be found "0x0a98d7c3eee14332e9fa9591c17235a84771f3536e8fe199a05def8aea1e9b93".
Actually, 10NEO and 10ONT was sent, but only 10 NEO is transfered successfully.
And in the appcliationlog, it could be seen as:
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "txid": "0x0a98d7c3eee14332e9fa9591c17235a84771f3536e8fe199a05def8aea1e9b93",
        "executions": [
            {
                "trigger": "Application",
                "contract": "0xce8f9032b2e5ac99d5a60873adf980cf1b122b3d",
                "vmstate": "HALT, BREAK",
                "gas_consumed": "0.464",
                "stack": [],
                "notifications": []
            }
        ]
    }
}
```

**Comment by vncoelho** [comment]
Is this still an issue or question for NEO 2.x? If yes, fell free to reopen.

For NEO 3 it will not be an open discussion.
