### ISSUE TITLE
nep-5 smart contract isn't able to be deployed in the privatenet created by neo-cli2.9.2

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#496]
When we created a privatenet within neo-cli2.9.2, we tried to deploy nep-5 contract as usual, but the transaction always unconfirmed by consensus nodes. We've tried most verisons of neo-gui to do it, but got the same failure. Mightbe something wrong in making transaction in neo-cli2.9.2? The contract is always deployed well on neo-cli2.7.6, 2.9.0, 2.9.1.

**Comment by vncoelho** [comment]
Hi @superboyiii, this has been solved in the version that came after 2.9.2.
