### ISSUE TITLE
sendrawtransaction - result: false - how to figure out the reason?

### ISSUE THREAD

**Issue by some-dev** [neo-project/neo#497]
I'm sending raw transaction via json rpc method "sendrawtransaction" but getting result:false without any description.
How to find out the reason of failure?

`
{"id":1,"jsonrpc":"2.0","method":"sendrawtransaction","params":["80000001a2ab4169cc6aa1f1ef0ecc072cdb350ea538873bf90ba1baf8e6f0a48d8b6f490300029b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc540420f0000000000c3f7e466ca5a2377682f28c9168accd5eee04b8c9b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5c0312ca40b000000c3f7e466ca5a2377682f28c9168accd5eee04b8c01414052ba5822d50f879a220963015b1dae8768cfc7374a490839e9775c8bc9c4f28c72047dd1409191f1b85a3167dc077bacddc04227dd7076644811a19e15eede81232102ffbf46e2e49feb4b63d25fa47156c730ae97e10841f77a475132f123ff4234f5ac"]}
`

response

`{"jsonrpc":"2.0","id":1,"result":false}`

**Comment by shargon** [comment]
Usually is because the hash is already known

**Comment by some-dev** [comment]
i tried on another pristine address:
issue still remain.

`POST http://104.40.151.227:30335/ HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 592
Host: 104.40.151.227:30335

{"id":1,"jsonrpc":"2.0","method":"sendrawtransaction","params":["80000001a2ab4169cc6aa1f1ef0ecc072cdb350ea538873bf90ba1baf8e6f0a48d8b6f490500029b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc540420f0000000000c3f7e466ca5a2377682f28c9168accd5eee04b8c9b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5c0312ca40b0000008b11835c963034b98d9fd6c9116e17145d165246014140367776783c2618c7d4196e9f86c16da03e7a9b9082a0f4c08a5f5e2d4126ed0896633562e3b4694a43361ed7f44fd57bfa88938c3a44280b8f3f63bde9d434b6232102d5bb4438d451bb793f283eab937ae49579c52b2e3fac8092865df32e3cccecdaac"]}


{"jsonrpc":"2.0","id":1,"result":false}

Is there are any way to troubleshoot it?

**Comment by some-dev** [comment]
yes its testnet transaction.

**Comment by some-dev** [comment]
We have updated the node
error message become this one:
'{"jsonrpc":"2.0","id":1,"error":{"code":-504,"message":"Block or transaction validation failed."}}'

What could cause the error?

**Comment by shargon** [comment]
I'm synchronizing my testnet, I'll answer you shortly

**Comment by vncoelho** [comment]
Hi @Shargon.

If you want to try with https://neocompiler.io/#/ecolab you go to Configurations and change to `Testnet`

**Comment by shargon** [comment]
I need the chain for Debug the result of `Verify` method

**Comment by vncoelho** [comment]
I see, Shargon, makes sense.

But which kind of transaction is this one? An Invocation or Verification only?
You could try to replicate the invoke if that is the case, there is also a Transaction Build tab.

**Comment by shargon** [comment]
@some-dev  This is your TX

```
{
    {
        "txid": "0x8a4f1d011a4c3551a0a768f195fd278760600f7efa300b74314b3e97af0c9367",
        "size": 262,
        "type": "ContractTransaction",
        "version": 0,
        "attributes":
        [
        ],
        "vin":
        [
            {
                "txid": "0x496f8b8da4f0e6f8baa10bf93b8738a50e35db2c07cc0eeff1a16acc6941aba2",
                "vout": 3
            }
        ],
        "vout":
        [
            {
                "n": 0,
                "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
                "value": "0.01",
                "address": "AZe4NkrBNmxTN9vTYMGiP5Xb2HmUZo4qAR"
            },
            {
                "n": 1,
                "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
                "value": "499.99",
                "address": "AZe4NkrBNmxTN9vTYMGiP5Xb2HmUZo4qAR"
            }
        ],
        "sys_fee": "0",
        "net_fee": "0",
        "scripts":
        [
            {
                "invocation": "4052ba5822d50f879a220963015b1dae8768cfc7374a490839e9775c8bc9c4f28c72047dd1409191f1b85a3167dc077bacddc04227dd7076644811a19e15eede81",
                "verification": "2102ffbf46e2e49feb4b63d25fa47156c730ae97e10841f77a475132f123ff4234f5ac"
            }
        ]
    }
}
```

![image](https://user-images.githubusercontent.com/3167973/50005427-968ac480-ffaa-11e8-8ad0-8e1808e794fa.png)

@some-dev in this tx, you are sending `0.01 (1000000)` as output value for your NEOs, and NEO is indivisible (100000000), so the validation of this TX fail because that

**Comment by some-dev** [comment]
Great thank you.
