### ISSUE TITLE
Have public address, lost private key

### ISSUE THREAD

**Issue by cryptoleb1** [neo-project/neo#50]
https://antchain.xyz/search?q=AavSSqSm2o1Zq2hvYFAwGS8s5MWtQ2LdiN

Hello, I reached out to the dev team via email, tweeted and reached out to fabwa on reddit. While I just reached out, i also wanted to reach out here. 

Here's my situation. When I became an investor originally of anthsares, I stored my coins on the exchange. At the end of June, I downloaded the wallet and create an address. At the time I thought once I sent over my coins from the exchange to my wallet address I would have to resave the wallet file with the old one. i did this, and my coins disappeared (it erased the original file, since I renamed the new wallet file the same name). I hadn't saved the private key and now am unable to access my coins. 

I can verify the transaction occurred under my name through my bittrex account which would match whats on the explorer website above. 

While reading the whitepaper for antshares it states, "For the sake of lost private keys, Antshares has an asset-retrieving mechanism in place, i.e. even if you lose the private key to a certain address, assets within it are still retrievable without helps from a third party."

Please help me get my coins back. I've attached screenshots of my the transfers from my exchange account and then verify this is in fact mine through antchain.xyz.

![bittrex neo transfers](https://user-images.githubusercontent.com/31018682/29292214-4741981a-8114-11e7-939d-60113fc234c6.PNG)

**Comment by cryptoleb1** [comment]
@erikzhang

**Comment by erikzhang** [comment]
Once you lost your private key, there is no chance to recover it. I'm sorry about this.

**Comment by cryptoleb1** [comment]
Mr. Zhang,

I don't understand....on the white paper for both neo and antshares it clearly states for the "sake of lost private keys, Antshares has an asset-retrieving mechanism in place, i.e. even if you lose the private key to a certain address, assets within it are still retrievable without helps from a third party."

**Comment by erikzhang** [comment]
That is a planning mechanism which has not been implemented.

**Comment by cryptoleb1** [comment]
So once this is implemented I'll be able to retrieve my assets...correct? I have the password and address.

**Comment by cryptoleb1** [comment]
I know you are very busy sir, I just want my coins. Any information to provide me a bit of hope is appreciated. I was about to give up and then I read that information on the white paper.

Thank you again.
