### ISSUE TITLE
Suggestion: Add Map parameter type / return type

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#504]
Hello,

We accept Map in the smart contract, even in the storage, but we cannot send maps nor return it.
Is there any chance we could add this feature to NEO?

Thanks

**Comment by shargon** [comment]
You can use `object`, is enough for you?

**Comment by lock9** [comment]
@shargon  maybe. If I use 0710 as input parameters and send something like "register", [Map<string, object>], will it work?

If I return a map, will it be serialised and returned as a byte array or as a utf-8 "string" (map)?

**Comment by igormcoelho** [comment]
It will work. If you use serialize and deserialize this will probably be easier Ricardo... inside methods you can cast from/to map using object, as shargon mentioned. Receiving it from outside world is unecessary if we already have serialization. To be honest, I submit integers directly as bytearray, because afterall, everything is a bytearray :)

**Comment by lock9** [comment]
Is it possible to deserialise this map just by converting it to from hex to utf-8 string? I think that the maps are being serialised like they are in the SC, using a prefix byte to identify the type.
I'll try again here, for some reason it wasn't working when I returned a map, I had to return a  'flat array' instead 🤔

**Comment by shargon** [comment]
I think that the better way is that you return a byte array in your desire format

**Comment by vncoelho** [comment]
Hi @lock9, meu parceiro meu amigo, can this be closed or is it still something that we should consider to be implemented?

**Comment by lock9** [comment]
@vncoelho  this is garbage, I'm closing it!

**Comment by igormcoelho** [comment]
This is important, lets do it.

**Comment by vncoelho** [comment]
I told @lock9 in private if he was sure about the garbage...aheuaheuaea

**Comment by igormcoelho** [comment]
This is very important. Every StackItem on NeoVM should at least have a corresponding item on NEP-3.

**Comment by lock9** [comment]
Hello guys, let me explain:
I think that nodes don't have to return this kind of object because this computation can be done in the client. 
What could be done, is some sort of external deserialized, maybe something outside the SC, meaning that consensus nodes don't have to execute it.

What if this is inserted in the manifest file? I don't know, but I'm against putting this kind of computation "mandatory", because it can be done elsewhere (at client level)

**Comment by lock9** [comment]
Can we move our discussion to #822?

**Comment by shargon** [comment]
Ok @lock9
