### ISSUE TITLE
Limit KnownHashes size

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#509]
Currently, it looks like that the ` HashSet<UInt256> knownHashes` has no size limit.
https://github.com/neo-project/neo/blob/7883e587a9448330d21669ebe748402871da3a50/neo/Network/P2P/TaskManager.cs#L27

In my local experiment it quickly reaches huge sizes.
Maybe it can reach something around 1M+ in MainNet operation.
Is it a problem to the client or it is expected to handle it in a smooth manner?

If we decide to limit it, which kind of representation do you recommend?

**Comment by jsolman** [comment]
False positives are not acceptable for this as it could block transactions erroneously, so a bloom filter is not a good choice. An LRU cache structure could work.

**Comment by shargon** [comment]
The best way is a stored list in the chain

**Comment by jsolman** [comment]
It’s fine if the structure allowed a duplicate because it will check it against leveldb later and see it as a dupicate and reject it. For instance, after a node starts, knownHashes is always empty, and it may receive a hash already in the chain and have to incur a disk read to discover it is already there. So it’s fine if an expiring cache is used here; the whole purpose to have knownHashes here AFAIK is just to improve performance (not waste time when receiving the same hash again).

**Comment by vncoelho** [comment]
I agree, @igor, @shargon, @jeff.
All 3 points are exactly good solutions.

**Comment by jsolman** [comment]
I guess we could use a bloom filter, but if it says it is already there, would need to double check that it really is already there by checking if the blockchain knows about the hash either in the mempool or as a persisted block or in unverified blocks.

**Comment by igormcoelho** [comment]
I agree that Bloom Filter may not be ideal,but we can manage it. Anyway, we can try to find another data structure that is the opposite of BF, because double checking every positive is lots of waste of computing power :)

**Comment by vncoelho** [comment]
That is great, @igormcoelho.
Let's think about it.

A simple idea is just to limit the `KnowHashes` `HashSet` to a given size, because after some minutes old tasks will not arrive anymore.
Since most of the clients are reestarted and, even with the current KnowHashses, they do not consider the whole history of tasks. I believe it is a tool more designed for speed up in normal operation and not for attack/spam cases.

**Comment by vncoelho** [comment]
Well closed, thanks to everyone that investigated and performed benchmarks for finding the most adequated solution.
