### ISSUE TITLE
Consensus optimization: Novel network routing strategies, a trade-off between payloads and communication

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#519]
Part II development already started: https://github.com/igormcoelho/neo/tree/optimized-dbft-part-ii
It is designed on the top of #426.

The first trade-off to be analyzed will be sending all knows signatures along with the payload messages.
     * On `PrepareResponse` sending all known `SignedPayload`
     * On `CommitAgreement` sending all known `FinalSignatures`

The overhead is probably limited to  `N` x `64` bytes in each of these Payloads, where `N` is the number of Consensus nodes.
In this sense:

* for `100` CN we would have 6,4KB extra bytes in each of these two payload messages
* for `1000` CN we would have  64KB extra bytes in each of these two payload messages

**Comment by vncoelho** [comment]
@shargon, that idea you mentioned about compressing the messages could be implemented in this package of Part II, but maybe you want to do it in separate PR.

On the other hand, the advance I see in a big package with precise contributions is that we can take the necessary time for testing the improvements package carefully.

**Comment by vncoelho** [comment]
You are right! It is a simple and efficiency strategy.
Is there any possible negative aspect of this, @shargon?

**Comment by shargon** [comment]
Require update all nodes with a better transport protocol

**Comment by shargon** [comment]
This was my proposal time ago: https://github.com/neo-project/proposals/pull/31

**Comment by vncoelho** [comment]
I just read it, @shargon.
Maybe it is a good idea to write it as a NEP as you are doing because it opens door for future improvements on this compressing strategies.

**Comment by igormcoelho** [comment]
Good idea Vitor! I guess ChangeView should also include known signatures, so it could be forced much faster on nodes that did not receive all messages.

**Comment by lock9** [comment]
@vncoelho is this still relevant?
