### ISSUE TITLE
Ubuntu 16.04 installation

### ISSUE THREAD

**Issue by i3bitcoin** [neo-project/neo#52]
Hi,
Is there any installation guide for ubuntu 16.04?

**Comment by jonatanblockchain** [comment]
Please, don't open more issues. 
https://github.com/neo-project/neo-cli/issues/13

**Comment by i3bitcoin** [comment]
W: GPG error: https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
W: The repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Anyway, after installation, got the same Segmentation failed error (
Ubuntu 16.04
