### ISSUE TITLE
Maybe a copy-paste mistake

### ISSUE THREAD

**Issue by michaely2008** [neo-project/neo#524]
Blockchain.cs,  Line 311, 
"Inventory = block" should be "Inventory = blockToPersist".

**Comment by jsolman** [comment]
You are correct. I will issue a PR to fix it.

**Comment by jsolman** [comment]
Thank you for the report.

**Comment by vncoelho** [comment]
@michaely2008, eagle eyes!
This was an important bug fix that passed throughout our eyes recently. Thanks for fixing this, it surely improved the network instantaneously.
