### ISSUE TITLE
The pressure of network transmission caused by the retransmission of unconfirmed transactions after the receipt of the block

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#539]
收到区块后, 未确认的交易被重新广播造成网络传输的压力。
Blockchain.cs 的 OnPersistCompleted 函数里，会把 MemPool 里还未处理的交易重新验证和广播，这块如果MemPool 里的交易数量多了，会造成网络传输的压力。社区开发者做并发测试，说感觉这块会增加不少网络带宽的负担。请问最初是因为考虑到可能会因为带宽不够而丢包才这样处理的吗？

Translate:
In Blockchain.cs's OnPersistCompleted function, transactions that have not yet been processed in the MemPool are re-validated and broadcast, and if there is a large number of transactions in the MemPool, the pressure on the network transmission will be caused. Community developers do concurrent tests and say it feels like it will add to the burden of a lot of network bandwidth. Did you initially take into account the possibility of losing Bao Cai to deal with it because of insufficient bandwidth?

**Comment by jsolman** [comment]
This I’ll be fixed by #500
