### ISSUE TITLE
public key

### ISSUE THREAD

**Issue by handzio** [neo-project/neo#54]
When I open wallet in NEO-GUI  and view private keys , above there is Address and Public Key in upper window . In bottom window thee are private keys , HEX and WIF .
My question is  - what for is there a Public Key ?
What is its function and how to use this key .
So far this is what I find about .
(4) Public key: Each private key has a matching public key (Note: Public key, and private key information can be viewed by right clicking on the address.)
Thanks for any help .

**Comment by erikzhang** [comment]
You can use your public key to make a multi-sig address.
