### ISSUE TITLE
Create java examples and sort existing examples per language

### ISSUE THREAD

**Issue by jamesglennon** [neo-project/neo#57]

**Comment by jamesglennon** [comment]
I can implement this task, though as I am new to the project I will need a few days ramp-up time, and I can begin the task at the weekend.

**Comment by erikzhang** [comment]
Should I create an "examples-java" repo?

**Comment by jamesglennon** [comment]
Hi Erik, yes I think a separate repo for examples-java would be cleaner, thanks.

One quick question, I am importing the library AntShares.SmartContract.Framework.jar to use the framework services, but I see that some functionality exists in the C# examples that are not contained in the framework jar - for example in AgencyTransaction.cs you are calling a VerifySignature(client, signature), but this verifySignature call does not exist in the framework jar. Should I implement the missing functionality myself in the java examples ?

Forgive my ignorance I am new to the project, thanks :)

**Comment by erikzhang** [comment]
Done.
https://github.com/neo-project/examples-java

**Comment by wy** [comment]
Looks like lots of the new features like Runtime and Enrollment are missing @erikzhang from Java compiler?

**Comment by erikzhang** [comment]
They will be available at https://github.com/neo-project/neo-devpack-java soon.
