### ISSUE TITLE
Implicit token transfers

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#589]
I think that a simple change could allow us to have a smooth migration for Neo 3.0 model, without global assets. The proposal is the following.
Currently, Inputs on Transactions refer to specific past transactions, plus the positional id (2 bytes) and value. Outputs refer to destination account (by scripthash) and the value. Each Input is converted to a CoinReference, which is the same structure as an Output (scripthash + value). Global asset hash is also included on the process (32-bytes). 

I believe that we can prefix data (input tx / global asset id) with zeros, in such a way that we know that it is not a Global Asset, but a Token transfer invocation for an specific NEP format.

For example, consider the following transaction with 1 input and 1 output.
Input transaction reference: `0x00-00-00-00-00-00-00-00-00-00-00-00-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-cc` (12 byte zeros + 20 bytes scripthash)
Input transaction position: `0x00-00` (2 bytes zero - unused for now)
Input value:  12345 (regular value format)
Global Asset id: `0x00-00-00-00-00-00-00-00-00-00-00-(11 bytes zero)-05-(1 byte NEP-05 standard)-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb (20 bytes scripthash)`
Output scripthash: `0xaa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-dd`
Output value: 12345

This means we are doing a NEP-05 transfer from account `aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-cc` to account `0xaa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-dd`, of value 12345. where NEP-05 contract is `ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb`.

So, an implicit script could be executed during the VERIFICATION stage of the transaction (if it throws or fails, transaction will fail):
```
PUSH aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-cc (from)
PUSH aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-bb-aa-dd (to)
PUSH 12345 (value)
PUSH "transfer"
APPCALL ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb-ee-bb
```

Clearly, some situations that usually work could fail, for example, extracting 10 coins from A, 20 from B and sending 30 directly to C (we couldn't translate this into a single "NEP-05 transfer"), but still this brings a possibility for many already deployed applications to keep functioning after global assets get abolished. 

If Neo and Gas get translated to Native Contracts, there are some possibilities for even better compability: 
(a) format equals or similar to NEP-05, the translation could be nearly the same as presented above, including the limitation explained 
(b) a new NEP-X is proposed, that can be used for the translated Native Global Assets, which includes NEP-05 functions and an extra function, called "multitransfer". This multitransfer would accept several inputs and outputs in array formats, and process them simultaneously (example: multitransfer [input1 value1, input2 value2] [output1 value1]). The only rule would be that the sum of input values match the sum of output values, and all inputs are validated witnesses. 

In this case, if option (b) is adopted, nearly all situations currently covered in UTXO model would keep existing, so the breaking changes would only affect contracts that did specific processings on input transaction (such as GetTransaction), which would fail now because "input transaction" would not exist anymore, only an alias to the transfer operations explained above.

**Comment by igormcoelho** [comment]
@erikzhang @vncoelho @jsolman @shargon @localhuman @canesin

**Comment by erikzhang** [comment]
I must first make it clear that an important task of NEO 3.0 is to throw away all the burdens. If you want to preserve compatibility, it will definitely increase the complexity of the system. An overly bloated system is not competitive.

**Comment by igormcoelho** [comment]
I fully agree with you that NEO 3.0 must be simple and throw away all the burdens. This proposal aims only at a possible transition model that could perhaps allow global assets to be migrated, but at some point it is innevitable that new and more efficient contracts are deployed to the network and the old are abandoned.
This reminds me a little bit of the IPv4 vs IPv6 story, because on internet it was not possible to simply stop and migrate to IPv6, so a double-stack model was proposed, to allow smooth transition while not stopping the services at any moment. However, a blockchain is much simpler to handle, and it is actually possible to stop and migrate to another model at some moment of time. If this is the community opinion (the stop and change model), I won't argue against it, because it looks much faster to do. My point here is just to make sure that we are doing that because it's better, not because it's the only possible way to do it.

**Comment by igormcoelho** [comment]
After discussions with core members, I agree that Neo 3.0 should get rid of burdens (including input-output syntax), so I'm closing this in favor of more global discussions regarding transition from Neo 2.0 to Neo 3.0:
https://github.com/neo-project/neo/issues/338
