### ISSUE TITLE
native contract with Depoly

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo#599]
1.make a dotnet DLL as a NativeContract.
2.use mono.cecil to load dll and do a whitelist check( check what function this dll call)
3.use Assembly.Load to load and use reflection to call it

**Comment by erikzhang** [comment]
How do you calculate the price?

**Comment by lightszero** [comment]
about calculate the price,I think that have many way to got it.
1.we can scan DLL and insert some  IL price calculate code in native contract.（i think this is the best way）
2.just use a timeout way.
3.native contract price is a const,only some kind of manager can depoly that.

**Comment by erikzhang** [comment]
> we can scan DLL and insert some IL price calculate code in native contract.

Will the performance loss of scanning and injecting the pricing code be much greater than running NeoVM?

> just use a timeout way.

Using the timeout method can lead to non-determinism. Because different nodes will cause inconsistent results even if they use the same timeout. And the timeout can only be used to calculate the consumption of CPU resources, but not the storage or memory usage.

> native contract price is a const,only some kind of manager can depoly that.

If this is the case, why not embed native contracts into NEO's core code?

**Comment by igormcoelho** [comment]
It would be nice to have some automated way to "natively" deploy a contract. However, I agree with @erikzhang regarding the flaws on the current proposal, such as non-determinism (non-validation of consumed memory could be handled together with CPU, but could also lead to some non-determinism between nodes).
Anyway, congratulations for the efforts on Native Contracts @lightszero, it's a very important step now. Certainly, a good model will emerge from these discussions.

**Comment by igormcoelho** [comment]
@lightszero when you have time, please take a look at this proposal here: https://github.com/neo-project/neo/issues/602
I believe it can be useful to this discussion.

**Comment by shargon** [comment]
The price could one attribute in the method, but like @erikzhang says, why don't put this code inside neo?

**Comment by lightszero** [comment]
only need insert IL price calculate code one time, when depoly dll -> insert and save dll2

when call,it does not to insert again.

**Comment by lightszero** [comment]
i had create a prototype to insert price calc code.

https://github.com/lightszero/IL.Insert

if smart contract use this way  to instead neovm,will be very fast.

**Comment by erikzhang** [comment]
There is a question, how do you run such a contract on a node implemented in other languages?

**Comment by lightszero** [comment]
convert everything to il if we need.

**Comment by igormcoelho** [comment]
Let's close this and focus on PR https://github.com/neo-project/neo/pull/639?

**Comment by shargon** [comment]
Can be closed?
