### ISSUE TITLE
do we have a docker file ?

### ISSUE THREAD

**Issue by 5hanth** [neo-project/neo#61]
I'm trying to run server in daemon mode but there don't seem to be an option. 

Wanted to check if anyone is working on dockerfile. [The links in doc](https://github.com/neo-project/neo/wiki/Bookkeeping-Node-Deployment) were pointing to a [download portal](https://pan.baidu.com/s/1jI0TIJW#list/path=%2FDocker). Would be great if there is a direct link that can be downloaded via wget (docker_image_antsharesdaemon.tar)

**Comment by jonatanblockchain** [comment]
Hi 5hanth ,
I've created docker images, https://github.com/jonatanblockchain/neo-docker
Right now we are testing them.

**Comment by 5hanth** [comment]
do we have an option to run rpc server in daemon mode as of now ?

**Comment by jonatanblockchain** [comment]
Hi 5hanth
I'm trying/testing different switch options, meanwhile you can change these two lines.

EXPOSE 10332 10333
ENTRYPOINT [ "dotnet", "neo-cli.dll", "/rpc" ]

**Comment by erikzhang** [comment]
See #22
