### ISSUE TITLE
create tags to versions

### ISSUE THREAD

**Issue by canesin** [neo-project/neo#612]
Currently is quite hard to know what is the `neo` code running on the `neo-cli` correspondent version, could you guys please tag the versions used here ?

Adding to it, is there a 2.9.5 being tested ? If yes, could you tag it now ? Appears like a good opportunity to start.

**Comment by JustinR1** [comment]
Looks like from #547 , testing should be complete by March 1 by NGD

**Comment by jsolman** [comment]
I agree that it would be great to tag the release versions.

@erikzhang can we start doing this beginning with the 2.9.5 release when it is made?

**Comment by jsolman** [comment]
WI am fairly sure the 2.9.4 release was this Commit:

b1311ba4

**Comment by erikzhang** [comment]
I've created some tags. https://github.com/neo-project/neo/tags

**Comment by igormcoelho** [comment]
Congratulations for these tags Erik, very useful! Perhaps, 2.10 is also a nice name for next release (then  2.11, etc), so we finally clarify that 3.0 is still a future work.

**Comment by vncoelho** [comment]
That is true, @igormcoelho.
@erikzhang, a better name tagging now would be 2.10 instead of 2.9.5.

**Comment by vncoelho** [comment]
@canesin, take a look at https://github.com/neo-project/neo-cli/pull/310

Maybe it would be interesting to include the suggested tested commits in the changelog.

**Comment by vncoelho** [comment]
@canesin, maaa friend, should we close this or there still some improvements that could be done in these tags?

**Comment by gsmachado** [comment]
Guys, in addition, I would like to suggest that for each "tag"/release we could add the following:

* Release description (very short)
* Changelog notes
  * In items, not more than a bunch of key words
  * Adding links to the issues on GitHub, if possible

I know that it's time consuming and not so convenient, but it would absurdly help developers of libraries in the NEO ecosystem (like me). ;-)
