### ISSUE TITLE
RPC Plugins don't have access to current wallet

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#617]
Most of the commands in RpcServer use the local Wallet field, but RPC Plugins don't have access to the wallet

**Comment by shargon** [comment]
Check this comment https://github.com/neo-project/neo/pull/536#issuecomment-453402293
You should be able to access to the `Wallet` using the `System` property, and access to the current `RpcServer`

**Comment by devhawk** [comment]
Thanks @shargon! I'm experimenting with 2.9.4, looks like #536 went in after that.
