### ISSUE TITLE
Move consensus to a plugin

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#619]
@igormcoelho, @shargon, @erikzhang and @jsolman, what do you think about that?

Maybe it is great for portability, because in the future Consensus could be isolated easily and even run in a module in a different language.

**Comment by shargon** [comment]
Mmmm, i don't like the idea very much ... Could be isolated but not in a plugin, i think

**Comment by vncoelho** [comment]
If you prefer isolated let's create it in a different project.
@shargon, do you see an easy path to load a plugin generated in other environment/language?

**Comment by shargon** [comment]
Is not easy job, but why we should use other language for consensus?

**Comment by vncoelho** [comment]
It is not a requirement, it is an idea for ensuring NEO as a template.
If it was designed for accepting any consensus in an isolated environment we could perform, easily, different tests for Consensus ideas that researchers investigate.

In terms of other languages it is just an idea that this layer could run as an isolated module. There is not a currently need for mixing the consensus layer with a code written in a different language.

**Comment by vncoelho** [comment]
But the same applies for the NEO-VM, right @shargon?
It would be great to easily just set a C++ module to execute all VM executions, @igormcoelho.

**Comment by shargon** [comment]
A modular VM (in other language) is easier, but when you need to share the storage, types, p2p, etc... it's more complicated

**Comment by igormcoelho** [comment]
In fact, if neo-project/neo becomes a middleware, it's easy to code Consensus on other languages, and attach them via interprocess communication. On time, it's innevitable and necessary to have multiple implementations of consensus, to guarantee that they won't share common failures. However, it's for the future... perhaps a near future.

**Comment by erikzhang** [comment]
Moving the consensus to the plugin does not help create consensus on other languages. You can load .net standard dll as plugins only.

**Comment by igormcoelho** [comment]
@vncoelho I agree with Erik that neo-plugin is not a feasible way.. separating this part will require much deeper efforts.

**Comment by vncoelho** [comment]
I got it, thanks.

In this sense, what is the best direction?

**Comment by igormcoelho** [comment]
Vitor, in my point of view, this is what happens today, we have Akka for communication, but we have lots of direct accesses between Neo main components:
![image](https://user-images.githubusercontent.com/290989/55114298-4e5a6280-50c0-11e9-8523-f1e571ab3f64.png)

If we change Akka to IPC (Inter-process Communication), like mkfifo or any other techniques, we can do it quickly on shared memory (RAM), but with an overhead of serializing/deserializing between components (another component was proposed here to handle NeoVM service, which is not good for performance):
![image](https://user-images.githubusercontent.com/290989/55114363-7f3a9780-50c0-11e9-99fd-89ac7580088e.png)

Finally, a third option would be to embed NeoVM on each component, keeping IPC between them:
![image](https://user-images.githubusercontent.com/290989/55114426-a5603780-50c0-11e9-8650-bc2899f34a03.png)

This is a major redesign that is only worth when we have all these small components working well in many different languages. Anyway, the best options would be to keep solid single-language projects (like C# neo) in their current format, which is better for performance, and to propose something like that (hybrid projects) in another separated branch. Configurability will come with the lost of some performance.

**Comment by igormcoelho** [comment]
Ok Vitor, I'll close this for now, it's unfeasible for us to follow this path now.
