### ISSUE TITLE
RpcServer calls supporting GraphQL like mechanism to specify fields in the response

### ISSUE THREAD

**Issue by jsolman** [neo-project/neo#623]
It would be great if we could allow more flexibility in querying for just needed fields using something like GraphQL with the RpcServer. One example, based on something @vncoelho wanted, was something to retrieve the timestamps from the `x` block headers starting at a specified block.

**Comment by vncoelho** [comment]
Sounds good, @jsolman.
I saw this repository for dotnet: https://github.com/graphql-dotnet/graphql-dotnet

I am not export in these queries, @shargon has more experience in it.
If @erikzhang also agrees we could set this as a NEO 3.0+ milestone.

**Comment by erikzhang** [comment]
Why not just return everything?

**Comment by jsolman** [comment]
@erikzhang
> Why not just return everything?

500 blocks of just timestamps is much smaller than 500 blocks of everything

**Comment by erikzhang** [comment]
I know. But you still need to read from the storage, right?

**Comment by jsolman** [comment]
> I know. But you still need to read from the storage, right?

Sure, but that does not negate the network bandwidth savings by adding this feature.

**Comment by erikzhang** [comment]
I think we can improve it later. Now we should do some major changes to NEO 3.0.

**Comment by jsolman** [comment]
I agree.

**Comment by rodoufu** [comment]
Do you guys see it as a plugin which the nodes will be able to choose to use or as an independent project like https://neoscan.io/?

Because I can see in both ways, one each node can choose to provide or not the GraphQL implementation for the RPC calls, the `gets` as `view` and the `post` as `mutation`.
But we can also have an endpoint just to make easier to fetch the information.

**Comment by lock9** [comment]
Hi @rodoufu , we 'decided' that we are going to update RPC in the next release, not this one. 
I think that yes, we need all methods, not including plugins.
