### ISSUE TITLE
Official NEO repo ?

### ISSUE THREAD

**Issue by mongakshay** [neo-project/neo#63]
I have been 'watching' this code repo for NEO for past few months, and by looking at the very low volume of commits I am wondering if I am subscribed to the official NEO repo or not ? I have subscribed to other projects as well and comparatively this seems very less active. Can I get pointed to the future road map of NEO ?

**Comment by arjunmantri** [comment]
The last active dev or improvement was weeks ago? What is the next thing NEO devs are working on or just a bubble comparing with ETH as a ETH of China? And will the downward trend continues?

**Comment by localhuman** [comment]
There are many projects in the NEO ecosystem, you can view them all here:
https://github.com/neo-project

This is the current roadmap:
https://github.com/neo-project/proposals

It is unwise to look at the tip of an iceberg and proclaim it to be small.
