### ISSUE TITLE
Each node can only connect to 3 nodes in the local private chain

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo#630]
![image](https://user-images.githubusercontent.com/6295602/54108175-36bf8080-4416-11e9-89a1-4f9569207b82.png)

Each node can only connect to 3 nodes in the local private chain. Therefore, when there are four common nodes, common nodes cannot be connected. If a consensus node is turned off, the common node can be connected.  It is work at 2.8.0, but not work at 2.9.4.

在本地的私链中每个节点只能连接3个节点，所以当4台节点共识时，普通节点无法进行连接。如果关掉一个共识节点，普通节点就可以连接上了。在 2.8 的时候是没问题的，在 2.9.4 的时候不可以。

**Comment by shargon** [comment]
This max is defined here `https://github.com/neo-project/neo/blob/2c21e958bf416423c4afada2390a0cd79f30d7c0/neo/Network/P2P/Peer.cs#L27`

**Comment by erikzhang** [comment]
Yes. We can set this max in Settings.
