### ISSUE TITLE
Group up extension methods by source type and comment them.

### ISSUE THREAD

**Issue by jeremylcarter** [neo-project/neo#64]
There are many extension methods in use by the neo project.

I would like the group them up into individual static classes based on their type. During this process I would also comment the extension methods to explain what they are doing. This will improve the codebase for future development and documentation.

For example:
````cs
internal static BigInteger Mod(this BigInteger x, BigInteger y)
{
	x %= y;
	if (x.Sign < 0)
		x += y;
	return x;
}
````

Would become
````cs
/// <summary>
/// Divides the value of the source BigInteger by the division parameter, and returns the remainder.
/// See: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/modulus-operator
/// </summary>
internal static BigInteger Mod(this BigInteger source, BigInteger division)
{
	source %= division;
	if (source.Sign < 0)
		source += division;
	return source;
}
````

**Comment by jeremylcarter** [comment]
@erikzhang Could you assign this to me if you would like me to carry out the work? Thanks!

**Comment by AshRolls** [comment]
@jeremylcarter these would be useful improvements. We (City of Zion) have improvements of this nature planned for the core, please could you drop into #develop in slack and DM '@ashant' so we can coordinate?

**Comment by yanfaruiec** [comment]
数字资产交易所开发，有需要的朋友请加我微信ruiec2723，我们是交易所开发公司

**Comment by penlite** [comment]
What is the status of this @jeremylcarter, it sounded like a good idea.

**Comment by jeremylcarter** [comment]
Its a great idea but I don't see anyone else trying to improve the quality of incoming code. Why would I slave away at cleaning up the code, documenting it and making it readable when incoming code from other contributors has no comments, does not follow conventions and will require a clean up again. Its a never ending cycle.
