### ISSUE TITLE
High CPU usage by ng-api-server

### ISSUE THREAD

**Issue by BeOleg** [neo-project/neo#648]
Hello.

We are experiencing CPU usage of over than 100% by the process `ng-api-server` (on a box with 64 cores).

Did anyone have anything similar? how to solve this?

![image](https://user-images.githubusercontent.com/3058791/54699230-51da7080-4b39-11e9-9b8e-c47087ec3c43.png)

**Comment by erikzhang** [comment]
100% means one core I think.

**Comment by BeOleg** [comment]
Nah because geth that runs on the same box fails to sync because of having not enough resources (maybe network?).
Why is this project so heavy in general? poorly written?

**Comment by BeOleg** [comment]
Still it is the most CPU intensive amongst all coins including ETH

**Comment by ixje** [comment]
I think this issue can be closed as this is a `neo-python` issue not for the C# version. We're aware and have a solution under test.

**Comment by vncoelho** [comment]
That is true, @ixje. Thanks for remembering and also taking care of that.

**Comment by jsolman** [comment]
I think we should consider though if the Blockchain IDLE message can be improved somehow. I believe it continuously delivers it and this fully utilizing one core all the time.
