### ISSUE TITLE
Issue in calling the contract in c#

### ISSUE THREAD

**Issue by vivekRev** [neo-project/neo#65]
Hey, I have problem in calling the contract which has the parameter of type array. Anybody help me to get out of this.

**Contract.cs**
        public static int Main(string str, int[] arr)
        {
            int a = arr[0];
            int b = arr[1];
            if (str == "add")
            {
                return a + b;
            }
            else
            {
                return a - b;
            }

        }

And I am calling like this in console App.
**Program.cs**
class Program
    {
        static void Main(string[] args)
        {
          
        var engine = new ExecutionEngine(null, Crypto.Default);
            engine.LoadScript(File.ReadAllBytes(@"Path to .avm file"));

            using (ScriptBuilder sb = new ScriptBuilder())
            {

                int[] arr = { 1,2};
                byte[] bytes = arr.Select(x => (byte)x).ToArray();
                sb.EmitPush(bytes);
                sb.EmitPush("add"); 
                engine.LoadScript(sb.ToArray());
            }

            engine.Execute(); // start execution

            var result = engine.EvaluationStack.Peek().GetBigInteger(); // set the return value here
            Console.WriteLine($"Execution result {result}");

   }
}

**Comment by AshRolls** [comment]
Hello, please join #develop channel in the NEO slack for assistance.
