### ISSUE TITLE
MSPerBlock / Block Timestamps in ms

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#651]
Maybe we could think about a plan to move `SecondsPerBlock` to `MSPerBlock`. For long-term, I mean.

We believe that several Private Blockchains will connect to NEO public blockchain via NEOX. Some of them would like to produce blocks even faster than `1s` (in local environments it is currently feasible), which is useful, for example, for IoT micro-applications.

1. One thing would be to allow consensus to produce blocks in terms of milliseconds;
1. Another thing would be to relay the blocks based on unix timestamps that has milliseconds.

A softer change would be to do just 1) and let block timestamps in seconds.

**Comment by erikzhang** [comment]
The problem is `Block.Timestamp`.

**Comment by vncoelho** [comment]
Yes, Erik, this one would cause an avalanche effect ;D ahauaha

Maybe we could just allow the possibility for the consensus.
Some functions as plugins can monitor atomic block times or even a simbolic timestamp in ms.

But this is not a real priority now, it is a good feature that could attract other applications to want to use NEO as a standard.

**Comment by igormcoelho** [comment]
Problem is having a precise clock in microseconds scale.... perhaps centiseconds, or deciseconds are enough brother, but we need to make sure this is achievable first.

**Comment by vncoelho** [comment]
I had forgot we were already discussing it here.
@erikzhang, do you think that it could be included in the milestone for NEO 3.0?

**Comment by vncoelho** [comment]
@erikzhang, can we proceed with this implementation or should we wait a little bit more?

**Comment by igormcoelho** [comment]
This is important for future crosschain techs... if we have a very lightweight local neo, we can do magic in millisecs,interacting with global chain from time to.time only.
