### ISSUE TITLE
Alarm Clock for Neo

### ISSUE THREAD

**Issue by hugbro** [neo-project/neo#660]
Is there any plan to create an alarm clock for Neo Dapps? I mean, to submit transactions automatically from time to time? The transactions costs can be pre-paid by the user.

The consensus node could put the alarm clock on a pre-paid table and automatically execute from given periods, like cron.
Plus, to avoid large periods, the price could be exponential, for example.

By the way, I'm student of @igormcoelho and I'm taking my first steps in the platform. :)

**Comment by erikzhang** [comment]
I think this feature is not suitable for being built into the consensus. It is easy for a third party to create such a service, and they can send transactions periodically via RPC.

**Comment by igormcoelho** [comment]
It is possible to build a similar feature from external dapps, where tx may execute approximately on the expected time. To be precise, I think it must be linked with consensus, but approximate may be good enough for most applications indeed.
So, it's your new project @hugbro , to build this Dapp ;)

**Comment by igormcoelho** [comment]
Ok Hugo, this is more related to a Dapp idea than a Core change, so we will close this.
