### ISSUE TITLE
Use CN idle time to share promising txs for next block - at random

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#662]
Discussing with @KickSeason and @joeqian10, they reported a log in which Nodes 1,2,3,4 received the `PrepReq` on time (differences in terms of ms) but took time to receive the 265 'txs`, thus, they timeout.

In this sense, we thought about a mechanism for CN to share their expected txs that will probably come in the mempool.
This should be done at random.

In this sense, let's say:

Every `x` amount of `ms` (we can base that on the block time) all CN gonna look at their mempool and see the most promising `txs` (let's say 265) that they think that will be inserted in the next block.
In this sense, each of them would broadcast `1/7 * 265 = 38` random txs (only hashes).
This would ensure that CN are more aligned in their interesting, using their iddle time while `Primary Timeout` is not reached.

What do you think, @erikzhang @shargon @igormcoelho @jsolman, is this feasible to share these hashes?

**Comment by erikzhang** [comment]
I don't think this will help us receive the transaction faster. Because when a node receives transactions, it relays them. Re-broadcasting these transactions does not have any effect.

**Comment by vncoelho** [comment]
I agree, @erikzhang.
In general, it would be a workaround. I still think that we need some minor adjustment on the protocolhandler and taskmanger. Let's also investigate that.

Regarding this proposal, maybe this could open other possibilities for the selection of transactions that will compose the next block. Honest `Primaries` would be designed to  cherry-pick the random transactions sent by the other CNs.
