### ISSUE TITLE
Add Consensus version on logs initialize

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#668]
I think it's important to add neo-cli/neo version on consensus initialize log message:

`initialize:   ...  code="neo-cli-2.10.4-bla-bla neo-core-2.10.4-bla-bla..." height=xxxx`

For the past few days/weeks we generated too many logs, and it would be nice to have a record of the specific version used on each node. This can also be useful to perform tests involving different versions or different implementations.

We can discuss how to do that efficiently, and where to get this kind of information from the system.

**Comment by vncoelho** [comment]
It would be nice to print commit as well.

**Comment by eryeer** [comment]
Perhaps we can add a file named "version" in neo/neo-cli projects, and update the version information in version files in each release.

**Comment by igormcoelho** [comment]
As soon as we unify Neo3 solution, this versioning will become much easier.
