### ISSUE TITLE
UTC in ms

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#678]
Life is faster.

I believe that it is a good standard change for NEO 3.0.
Lets ensure that everything will be ready for acting in terms of ms.

**Comment by vncoelho** [comment]
An interesting example for Mainnet could be something crazy we thought some days ago:
* **dBFT shards by replication**

The same CN validators could act in ms in replicated shards coordinated in local enviroments.

CN keepers would have diff registered allowed private keys to operate in local shards,  but they would be the same CN nodes.
In this sense, in local scale everything would be ready. It still do not solve double spending and other sequential problems, but it can surely help.

**Comment by vncoelho** [comment]
@erikzhang, could we add NEO 3.0 milestone for this?

**Comment by erikzhang** [comment]
Is this a duplicate of #651?

**Comment by vncoelho** [comment]
It looks like, I thought that was inside a PR discussion.

Thanks, @erikzhang.
