### ISSUE TITLE
create Storage.MoveKey 

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#682]
Shargon gave a nice idea today, to allow storage key to be renamed. This is much better than Get Delete Put approach, and could possibly be cheap or zero for users (if key size is the same). Ideal for nep-5 tokens

**Comment by erikzhang** [comment]
What's the difference between `MoveKey` and `[Get, Delete, Put]`?

PS: NEP-5 transfer couldn't use `MoveKey` unless you want to transfer all tokens from your account to an empty address.

**Comment by igormcoelho** [comment]
In my opinion, there are two ways to view this. As we talked, it someone adds the same bytes that it deletes, cost could be zero, right? If one uses Get, Delete, Put in this scenario, even when transferring all assets, it would pay:
`Get(Key_size + Value_size) - Delete(Key_size + Value_size) + Put(Key_size + Value_size)`
The only problem with this is the extra `Key_size + Value_size` from the get, that the user would need to pay anyway.
If it used MoveKey(), the cost could possibly be zero (ignoring the get cost).

But I agree this is a rare situation.

**Comment by erikzhang** [comment]
I think the internal implementation of `MoveKey` is just combine `Get, Delete, and Put`. They consume the same amount of computing resources, so users should pay the same price.

**Comment by igormcoelho** [comment]
Ok, in fact this does not solve any global case scenario, so the gains seem to be smaller than I first thought. I'll close this. Feel free to reopen you want @shargon.
