### ISSUE TITLE
transaction stuck(sent NKN from NASH EXTENSION TO GATE.io)

### ISSUE THREAD

**Issue by givemeasigh** [neo-project/neo#687]
Hello, dear community! I sent a coin NKN to the exchange gate.io two days ago and the transaction was frozen for two days. Maybe I did not specify the gas. What can be done in this situation? Help me please!

https://neoscan.io/transaction/f41ee1837e82326cb20b3c7f1fb63a61126886e2c48a406aaaf5cbaf0b12c31b

**Comment by EdgeDLT** [comment]
NKN is no longer a NEO token, it was swapped from NEP-5 (NEO based) to ERC-20 (Ethereum based). [The deadline was March 28th](https://medium.com/nknetwork/final-push-for-nkn-token-swap-f4160f189d2a).

The NKN smart contract is locked, so the NEP-5 tokens can no longer be successfully transferred. All you can do is attempt to reach out to NKN's team and ask them to honour your tokens.

**Comment by EdgeDLT** [comment]
@erikzhang This can be closed.
