### ISSUE TITLE
Cannot transfer NEO from a contract to wallet

### ISSUE THREAD

**Issue by Kagamine** [neo-project/neo#69]
I just following the documentations, generated a transfer body from the first node, and when signing in the second node, neo-gui says: 'The private key that can sign the data is not found'

![image](https://user-images.githubusercontent.com/2216750/30745263-02c58984-9fd8-11e7-9071-1e3f7d4387ff.png)

**Comment by PeterLinX** [comment]
What documentations? Pls try to give us more info.

**Comment by c19** [comment]
this document: http://docs.neo.org/zh-cn/node/private-chain.html
during the transfer from contract address to standard address proceedure.

**Comment by BSathvik** [comment]
Did you resolve the problem ? I have the same problem.

**Comment by yukozh** [comment]
no

**Comment by BSathvik** [comment]
I think I figure out the problem. I didn't repeat the process of creating a multi-sig contract using all 4 wallets. http://docs.neo.org/en-us/node/private-chain.html

<img width="809" alt="screen shot 2018-03-13 at 2 35 20 pm" src="https://user-images.githubusercontent.com/8377116/37365662-1f5f9366-26cc-11e8-848b-4b2f5317ef60.png">
