### ISSUE TITLE
Create GetValidatorsScript interop

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#690]
Currently we use a multisig with secp256r1 to generate the validators script, but it is possible that this changes in the future (for example adopting Schnorr or any different kind of verification). So, it would be nice to have Neo interop call to inform the current ValidatorsScript.

Example:
Neo.Blockchain.GetValidatorsScript => current multisig verification script

**Comment by shargon** [comment]
The best thing we can do is add a flag (enum) in front of each signature that specifies the format, in this way we can be prepared for the future.

0x01 = secp256r1
0x02 = secp256k1
...

**Comment by erikzhang** [comment]
We don't need to add flag in front of each signature. We can add flags in front of public keys except secp256r1. In this way, we can be compatible with old signature scripts and support arbitrary signature algorithms in the future.

**Comment by igormcoelho** [comment]
Good idea with the byte marks. So, are you ok with the new interop? I'll start coding.

**Comment by erikzhang** [comment]
`GetValidatorsScript` or `GetValidatorsScriptHash`? Which is better?

**Comment by igormcoelho** [comment]
In fact we need the full Script in this case.

**Comment by igormcoelho** [comment]
Closing this, perhaps integrate this on native policy contract in the future.
