### ISSUE TITLE
An implementation for fractional gas on system fees

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#692]
As discussed on https://github.com/neo-project/neo/issues/319, and also explained here https://github.com/neo-project/neo/issues/326#issuecomment-410791548 it is feasible to implement fractional (divisible) gas fees (without making Neo divisible) in the following way.

The proposed idea won't change any block format and it is fully backwards compatible, to be implemented as soon as possible.

Currently, only integer system fees are allowed, due to a control on InvocationTransaction. On Blockchain file, the computation of system fees just aggregate the values on transactions, storing that on `SystemFeeAmount` inside Snapshot (which will also be integer). This is needed to be integer, otherwise it will break calculation of redistribution (becoming smaller than Fixed8). So, to allow divisible system fee and to redistribute only integer gas, the proposal is to:
- redistribute the integer part (as usually done)
- store the fractional part and aggregate it on future blocks, until it gets integer

To publicly store this information, the proposal is to deploy a Validators Contract (as discussed  https://github.com/neo-project/neo/issues/686#issuecomment-480470367), and create a storage key on this contract regarding `FractionalSystemFee`.
Example:
- invoketx1 has system_fee = 4 GAS
- invoketx2 has system_fee = 3.7 GAS
- invoketx3 has system_fee = 5.5 GAS
Suppose that contract storage `FractionalSystemFee` has zero GAS, the total system_fee value passed to snapshot will be: floor(0 + 4 + 3.7 + 5.5) = floor(13.2) = 13
The exceeding value of 0.2 will be stored again on `FractionalSystemFee`.

To put this into production, it will be easy, as long as the following steps are done:
1) InvocationTx keeps blocking fractional gas
2) Validators contract is deployed
3) Consensus Nodes are updated to process fractional Gas
4) InvocationTx starts to allow fractional gas

The deployed contract can have this format (using https://github.com/neo-project/neo/issues/690):
```
# standard entrypoint Main(string operation, object[] args)
JMPIF ... # verify if operation is 'storage_write', otherwise user is free to read data using function `storage_read`
# verify authorization to write
GetValidatorsScript
Hash160
Runtime.CheckWitness
# now only CN will execute this part
Storage.Put Global_variable_prefix+args[0]  args[1] # FractionalSystemFee value
```

This way, we can have this feature already on Neo 2.X, and prepare ground for improved fee system on 3.0.

**Comment by erikzhang** [comment]
There is no need to store anything for fractional gas on system fees. We can accept that the total amount of gas is not exactly equal to 100 million. (A small amount of less than 100 million is acceptable.)

**Comment by igormcoelho** [comment]
I get your point @erikzhang , and in fact, there are nice proposals for actually make it explicitly inflationary/deflationary. However, I would prefer to keep the precise amount redistributed, and to adopt another explicit and calculated equation to produce that behavior.
