### ISSUE TITLE
Governance Script for Contract Migration

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#695]
As discussed https://github.com/neo-project/neo/issues/685, I think it would be nice to have contract migration with a clear separation from contract logic. This could allow an easier creation of complex migration logic, such as token voting (for example, to allow migration, we require voting from the majority of token owners).
To not be fully separated from contract, perhaps this could even work as another Trigger: `if (TriggerType == Migration)`, then invoke a previously recorded migration scheme.
I agree that all of this can be coded in the contract, like: `Main(string operation ...){ if operation=="migration" do that...}`, so neo could provide some useful hardcoded schemes like `Neo.Native.NEP5VotingMigration` (that could be the same contract used for Neo network, for example, just changing the used asset NEO -> TKN), which is perhaps not so efficient to do on contract nvm.
This is just a general discussion on the topic, and since Neo 3.0 will bring nice changes, it would be nice to show that migration is possible to be very safe, and as long as it is clear and audited.

**Comment by igormcoelho** [comment]
We could use a similar feature to ammend existing contracts and allow migration for Neo 3.0.

**Comment by KickSeason** [comment]
As I know, We can currently use `Neo.Contract.Update` to migrate contract. 
If we have the `migration` trigger, we need to store the new script and manifest in advance. We need an interop service to prepare the script and manifest.

**Comment by igormcoelho** [comment]
You're right,it should be added earlier,or after, becaise migration governance could simply authorize a manifest and script change, based on hash (not full contents), and after that, a regular Contract.Update would actually do the migration.

This way, other scripts than application could exist on manifest, and migration governance could be immutable, while contract is still mutable.
Related to inheritance proposal too (semi-mutable contracts)
