### ISSUE TITLE
Use cryptographically safe random numbers on nonce for "Neo 3.0 MinerTx"

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#697]
Current nonce is quite weak on MinerTx, and as it should be abolished together will all others (except InvocationTx), it's a good time to drastically increase this entropy with a cryptographically safe random generator (with much larger scale than 4 or 8 bytes, let's take 32 or more). 
All languages have means to take this from the host system (as bindings for /dev/random for example), and it will improve a lot the usability of such numbers.

**Comment by igormcoelho** [comment]
Thanks @coranos for pointint this out: https://github.com/neo-project/neo/issues/195

**Comment by vncoelho** [comment]
I was talking to him offline to create an issue about it, you are fast, brother.

**Comment by coranos** [comment]
Cool. If I get a bug bonus let me know how to collect. It's been a while (nearly 12 months)

**Comment by igormcoelho** [comment]
In fact, this is just an improvement @coranos , as the situation you mentioned is not possible.. MinerTx hash is always verified before submission on block. So even if nonce has been "reused", it's not accepted.
Anyway, it would be nice to have better randomization here.

**Comment by coranos** [comment]
Are you sure? Miner Transactions aren't added to the mempool:
<https://github.com/neo-project/neo/blob/a69b0ce1ea217843e8f16dd37526a75b1fceac01/neo/Ledger/Blockchain.cs#L395>

and I don't see anywhere that the miner transaction's hash is specifically sent to ContainsTransaction. (no instantiation calls the below method that I can find)
<https://github.com/neo-project/neo/blob/a69b0ce1ea217843e8f16dd37526a75b1fceac01/neo/Ledger/Blockchain.cs#L190>

If it's just me not reading the code right, I apologize for the wild goose chase.

**Comment by igormcoelho** [comment]
I guess this is the infinite loop that guarantees that:

https://github.com/neo-project/neo/blob/master/neo/Consensus/ConsensusContext.cs#L367-L384

**Comment by coranos** [comment]
Cool, at least it's fixed. 🔀

**Comment by shargon** [comment]
Agree with this, we should get a hash for the `nonce`

**Comment by vncoelho** [comment]
@shargon and @igormcoelho, maybe it is time to PR this, right? The minertx was already abolished.

Let's create a draft.

**Comment by shargon** [comment]
We don't have minner tx in neo3, so we can close this, feel free to open again if it's necessary
