### ISSUE TITLE
Will verification exist on Neo 3?

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#699]
Just to make sure, verification will keep existing on Neo 3, right? VerificationR and ApplicationR wont be necessary anymore, I guess (but could also be implemented optionally on NEP-5).
Payable flag will keep working for native neo/gas?

**Comment by erikzhang** [comment]
In NEO 3.0, there will be a Simplified Validation Model. It will limit which opcodes or syscalls can be used by the verification script.

**Comment by igormcoelho** [comment]
Makes a lot of sense.
