### ISSUE TITLE
创建项目后，代码报错的问题及解决方案

### ISSUE THREAD

**Issue by l328958741** [neo-project/neo#70]
根据文档（[http://docs.neo.org/zh-cn/sc/getting-started-csharp.html](url)）配置开发环境，在创建项目后，发现代码报错，如下图所示：

![image](https://user-images.githubusercontent.com/21151878/30791281-118bc0e2-a1e4-11e7-898e-27d0b17bb2bd.png)

解决办法：
1、移除**引用**中的**Neo.SmartContract.Framework**重新添加；
2、点击项目，右键添加**引用**，找到**Neo.SmartContract.Framework**并添加；
![image](https://user-images.githubusercontent.com/21151878/30791420-de2caeea-a1e4-11e7-87a1-10c0f373dcec.png)

![image](https://user-images.githubusercontent.com/21151878/30791471-54818e94-a1e5-11e7-9835-76f38e5e2d6c.png)
3、完成后，还剩下一行代码报错；
![image](https://user-images.githubusercontent.com/21151878/30791497-6e64ca7e-a1e5-11e7-9784-51edcac9719f.png)
4、直接把**Framework**删掉即可，代码终于不报错了。
![image](https://user-images.githubusercontent.com/21151878/30791517-8a7f581e-a1e5-11e7-99c1-277d9b964d3a.png)

5、接下来的步骤再继续按照文档走就好了。

**Comment by erikzhang** [comment]
不需要这样，Neo.SmartContract.Framework是通过nuget引用的，只需要在nuget包管理器中还原一下包就可以了。
