### ISSUE TITLE
Extended MultiSig

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#700]
An important kind of multi-sig is currently missing, that's why we propose an Extended MultiSig.
Current MultiSig uses an array of publickeys and a limit number, to pass only if this number of signatures is validated against the pubkeys.
An important change would be to accept an array of _scripthashes_ (instead of pubkeys), so these are also validated against existing witnesses.
This is better in many ways: better privacy for multisig users; more flexibility on individual witnesses (part of the multisig). Using this, we can even compose multisig together, embedded in others (with some practical applications even for consensus algorithms).

So, one proposal is to create a native contract for this: `Neo.Native.CheckMultiSig`.

_Why not change existing NeoVM CHECKMULTISIG?_ 
I believe this opcode can be abolished on Neo 3.0, as previously discussed: https://github.com/neo-project/neo-vm/issues/122
And anyway it would be better suited to the ApplicationEngine (NeoContract), because it depends on the Witness system.

Using the same logic, we can already create: `Neo.Native.CheckSig` (and deprecate opcode CHECKSIG).

**Comment by shargon** [comment]
Like SHA1, SHA256, HASH160, HASH256 i think that this could be Syscalls too

**Comment by igormcoelho** [comment]
The more interop would make NeoVM more flexible for us... less strict (and less opcodes) is much easier to maintain. But we need to clearly define what is "unremovable" from NVM, and leave it there.
Pehaps CHECKSIG and VERIFY will need to stay, so as these basic cryptographic operations, in order to keep minimum compatibility on Neo 3.0. 

But I'm still in favor of a extended multisig, even if it's part of CHECKMULTISIG (perhaps it's already better to start there).

**Comment by igormcoelho** [comment]
Propose again in a different format, in the future.

**Comment by igormcoelho** [comment]
I think the general idea still applies: we should have some "CheckMultiWitness", to complement crypto-specific MultiSig.

Besides `Neo.Crypto.CheckMultisigWithECDsaSecp256r1` and `Neo.Crypto.CheckMultisigWithECDsaSecp256k1`, we could support some `Neo.Crypto.CheckMultiWit`, that receives a *list of scripthashes*, performs `Runtime.CheckWitness` for all of them, and check if they surpass a minimum count.

This general approach can help designing multisig that are easier to compose, even when parties are distant: https://github.com/neo-project/neo/issues/1573
