### ISSUE TITLE
Relational Blockchain

### ISSUE THREAD

**Issue by eaba** [neo-project/neo#701]
Hi, would you consider or are you considering NEO with Relational Blockchain?

**Comment by igormcoelho** [comment]
What is a relational blockchain? :thinking:

**Comment by eaba** [comment]
@igormcoelho here for starter: https://blog.chromapolis.com/what-is-relational-blockchain-and-why-should-you-use-it/

**Comment by AntierServices** [comment]
You can connect with a [[blockchain development company (url=https://antiersolutions.com/cryptocurrency-exchange-development-company)], our forward-thinking insights, rigorous research and one-to-one consulting helps businesses to identify and seize opportunities to tap into an unsurpassed decentralized ecosystem.

**Comment by jsolman** [comment]
@eaba relational databases are not faster than key value stores. Using relationaldb for a blockchain data store may support some app use cases, but speed will not be the driver for it.

**Comment by eaba** [comment]
> Using relationaldb for a blockchain data store may support some app use cases

NEO should make itself configurable for other use cases: >My thinking is that NEO can offer non-relational blockchain as default while anyone interested in a relational blockchain could configure NEO to use that!

**Comment by igormcoelho** [comment]
It's straightforward to use relational db as storage on Neo. Just change DataCache bindings and its done.
However if I understood correctly, the article as a "Blockchain 4.0" movement, where blockchain is actually replaced by a sql database plus integrity checking.. which is very different from the blockchain philosophy I know. If this is the question, I think much deeper debates are necessary.

**Comment by vncoelho** [comment]
I will leave this issue closed given the last reply and answer given by @igormcoelho.

However, fell free to reopen @eaba.
