### ISSUE TITLE
Single-node consensus mode for testing and development

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#703]
There is currently a lot of RAM/CPU overhead required to run a privatenet such as neo-local due to the need for a minimum of four consensus nodes running simultaneously on the same system. Additionally it complicates the configuration due to the need to bind each node's network services to different non-standard ports to avoid conflicts.

It could be highly useful for the Neo core code to support a single-node consensus mode for a lightweight privatenet. Ontology has this feature and it makes setting up a smart contract development environment much simpler and more convenient.

 It would also benefit Neo smart contract workshop events in the amount of time saved with setting up and resolving issues with different user workstations that may not always have the ideal minimum requirements for running 4 full nodes plus the extra tools required for the class.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/3a06f9c0efcc3cc267d380bb945fe7474b1f2243/neo/ProtocolSettings.cs#L13

In theory, the number of consensus nodes can be changed to 1 in the configuration file `protocol.json`. But it still needs to be tested if it works correctly.

**Comment by steven1227** [comment]
Actually for workshops or training, is it possible to provide a simplified chain such as [Ganache](https://github.com/trufflesuite/ganache-core)?. It accepts all incoming transactions immediately and creates one block for each by default.

**Comment by erikzhang** [comment]
> It accepts all incoming transactions immediately and creates one block for each by default.

I think you can adjust the block time in the configuration file to realize this purpose.

**Comment by steven1227** [comment]
> > It accepts all incoming transactions immediately and creates one block for each by default.
> 
> I think you can adjust the block time in the configuration file to realize this purpose.

For such case, it is better to let the single node judge if there are any transactions in the pool, to avoid producing a number of empty blocks.

**Comment by apisit** [comment]
This would be really really good to have. 
We at O3 are building yet another(more reliable) blockchain explorer. everything is bundled into a single binary. no other dependencies. it needs only neo-cli and several plugins. We are planning to make it run locally with private net to help developers with their testing and development pipeline.

**Comment by vncoelho** [comment]
Nice discussion,  I will soon test and implement a draft about this.

**Comment by vncoelho** [comment]
@igormcoelho just reminded me about the the GAS...aehauehuaea
Let's think a little bit more, this will require an adjustment in the formula, otherwise that privatenet will not have enough GAS or we would need to manipulate its transactions.

**Comment by vncoelho** [comment]
A minor modification for allowing single node to produced blocks was make and tested, @hal0x2328.

**Comment by vncoelho** [comment]
Maybe I will create another PR for allowing genesis block to be created for a singlesig address instead of multisig.
What do you think, @erikzhang?

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/56231501-fecedd00-6054-11e9-8bb4-13589844d7ae.png)

7% delay in our initial experiments.

**Comment by vncoelho** [comment]
Maybe I will create another PR for allowing genesis block to be created for a singlesig address instead of multisig.
What do you think, @erikzhang?

**Comment by igormcoelho** [comment]
No need for single sig, multisig works brother.

**Comment by vncoelho** [comment]
Done, brother, you are right!
Sorry.
My mistake when generating the multisig, I had forgot to update the first opcode.

![image](https://user-images.githubusercontent.com/17395762/56232859-1c517600-6058-11e9-9550-63c4bf69610e.png)

**Comment by Qiao-Jin** [comment]
Hi! Could you please also modify the constraints also like "at least 2 validators to create mutisig", etc, to enable assets creation? Thx

**Comment by vncoelho** [comment]
Hi @Qiao-Jin, I believe that we do not have that constraints.
You can create a multisig with a single address.
`5121-AddressPubKey-ae`

**Comment by hal0x2328** [comment]
I think the constraint is actually in neo-cli's argument parsing.
