### ISSUE TITLE
Increase the coefficient of gas calculation to 0.001 when tx size is over 1024 byte

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#708]
Now the coefficient of gas calculation is 0.00001 when tx size is over 1024 byte. It seems doesn't have enough deterrent on spiteful transaction. Let's make a calculation. Now the limit of one transaction size is 102400 byte. It means the inputs of one transaction could achieve several thousands since one UTXO input is 32 byte. We could suppose there's a time that too many 
spiteful transactions in a block which makes the block size as 2 or 3 MB. The evil only need to pay a little more than 20 gas to create big difficulty for main net which makes consensus nodes several minutes to create next block. The extreme situation could be the paralysis of main net. I think the coefficient  of gas calculation should be more so that it could greatly decrease the possibility of this situation. I think 0.001 is a reasonable value for this coefficient. What's your opinion? @erikzhang  @shargon @jsolman @igormcoelho @vncoelho

**Comment by shargon** [comment]
We should have a native smartcontract for allow the CN to share and vote information like this. I agree with you, but maybe is too expensive in the future

**Comment by igormcoelho** [comment]
@shargon 100% agreed. We have discussing a a contract for consensus storage, and its useful in many manners. Time to do that.

**Comment by superboyiii** [comment]
@shargon Maybe we could make two policy. The increased coefficient could be applied on command other than "invoke" "deploy" in neo-cli.

**Comment by erikzhang** [comment]
> Time to do that.

No. We should focus on NEO 3.0.

**Comment by vncoelho** [comment]
For NEO 2.x we should let it as it is right now.

We are currently discussing the pricing for NEO 3.0. There are other issues and PRs open. I believe that we may close this one, @superboyiii. But fell free to reopen.
