### ISSUE TITLE
RpcServer invokefunction reading wrong param

### ISSUE THREAD

**Issue by snowypowers** [neo-project/neo#71]
Have been playing with `invokefunction` and realised that it cannot work with any methods that accepts arguments.

This is an example of the POST i am sending to a v2.3.3 node. It is the `BalanceOf` method shown in the tutorial for SC in neo docs.

```
{"jsonrpc": "2.0", "method": "invokefunction", "params": ["dc675afc61a7c0f7b3d2682bf6e1d8ed865a0e5f", "balanceOf", "5fe459481de7b82f0636542ffe5445072f9357a1261515d6d3173c07c762743b"], "id": 3}
```

Upon closer inspection, it seems like the `invokefunction` case reads the args wrongly. It should be reading _params[2] instead of _params[1]

https://github.com/neo-project/neo/blob/f6b2c8a556b2cad17f1180faabb6a42fcd16a019/neo/Network/RPC/RpcServer.cs#L210
```c#
case "invokefunction":
    {
        UInt160 script_hash = UInt160.Parse(_params[0].AsString());
        string operation = _params[1].AsString();
        // This line should be reading _params[2] instead
        ContractParameter[] args = _params.Count >= 3 ? ((JArray)_params[1]).Select(p => ContractParameter.FromJson(p)).ToArray() : new ContractParameter[0];
        byte[] script;
        using (ScriptBuilder sb = new ScriptBuilder())
        {
            script = sb.EmitAppCall(script_hash, operation, args).ToArray();
        }
        return GetInvokeResult(script);
    }
```

**Comment by snowypowers** [comment]
Looks like the problem is deeper than i thought.

I implemented a simple fix and ran a custom build and ran into this error instead:

![image](https://user-images.githubusercontent.com/9101245/30962237-90a224f4-a47b-11e7-994d-83de578bbaa7.png)

https://github.com/neo-project/neo/blob/f6b2c8a556b2cad17f1180faabb6a42fcd16a019/neo/SmartContract/ContractParameter.cs#L59

The code is trying to rely on the `["type"]` property in order to cast it properly but no where in the JObject code does it assign something to `["type"]`.

A possible solution would be to infer the type at the parsing stage but this "type" will not change when casted which might result in confusion. I would prefer not to rely on this magical property and do a manual cast instead.

**Comment by erikzhang** [comment]
```json
{"jsonrpc": "2.0", "method": "invokefunction", "params": ["dc675afc61a7c0f7b3d2682bf6e1d8ed865a0e5f", "balanceOf", "5fe459481de7b82f0636542ffe5445072f9357a1261515d6d3173c07c762743b"], "id": 3}
```
The third parameter should be an array:
```json
{"jsonrpc": "2.0", "method": "invokefunction", "params": ["dc675afc61a7c0f7b3d2682bf6e1d8ed865a0e5f", "balanceOf", ["5fe459481de7b82f0636542ffe5445072f9357a1261515d6d3173c07c762743b"]], "id": 3}
```

**Comment by snowypowers** [comment]
I have corrected my input with your given input and reading from `_param[2]` will pass. However, the second error where the AsEnum tries to look for the `"type"` still fails because `"type"` is not set at all.

**Comment by erikzhang** [comment]
```json
{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "dc675afc61a7c0f7b3d2682bf6e1d8ed865a0e5f",
    "balanceOf",
    [
      {
        "type": "ByteArray",
        "value": "5fe459481de7b82f0636542ffe5445072f9357a1261515d6d3173c07c762743b"
      }
    ]
  ],
  "id": 3
}
```

**Comment by snowypowers** [comment]
Thanks for clarification erik! Got it working! So the JSON part is not a bug but a mistake on my side. However, I believe that the original issue is still considered a bug. 

Would you like a PR or you can do it yourself (since its a simple fix)?

**Comment by erikzhang** [comment]
PR is okay.
