### ISSUE TITLE
An compliation error has occurrred,when call the method of interface.

### ISSUE THREAD

**Issue by keisuke630** [neo-project/neo#722]
I implemented the interface.
And then,I implemented a method of a class that inherits a smartcontract with its interface type arguments.
I called the method of that interface in this method, A compilation error has occurred(System.Exception:unknown call).
How can i solve this problem?
```
public interface ICustomStorage
    {
        void Put(string key, byte[] value);
    } 

class Administrator : SmartContract
    {
        internal static bool UpdateAdminAddress(ICustomStorage storage, byte[] newAddress)
        {
            if (newAddress.Length != 20)
            {
                Runtime.Log("UpdateAdminAddress failed. newAddress is invalid.");
                return false;
            }
            storage.Put(StorageKeys.ContractAdmin(), newAddress);
            return true;
        }
    }
```

**Comment by erikzhang** [comment]
@lightszero Can you check it?

**Comment by erikzhang** [comment]
@lightszero Does the compiler support `interface` in the contract?

**Comment by erikzhang** [comment]
I think that we don't support `interface`.
