### ISSUE TITLE
MVC in RPC calls

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#726]
I think that we should use MVC for our rpc calls, neo 3 is a good moment for change this

- We can have better error handling 
- We can follow the standards
- The code will be cleaner

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2

**Comment by igormcoelho** [comment]
Since this does not affect Neo Protocol, it's just a technological change, I don't see any issue in putting this forward. The easier to maintain, the better.

**Comment by vncoelho** [comment]
@shargon, is this issue similar to https://github.com/neo-project/neo/issues/623 that @jsolman mentioned?

**Comment by shargon** [comment]
is not the same, this is more about organization and standards. The other is a feature

**Comment by lock9** [comment]
@shargon  can we keep this discussion in #850 / #849  ? And I think you mean "REST" as I mentioned before 😅

**Comment by shargon** [comment]
of course!

**Comment by lock9** [comment]
In this case, I'm closing this issue. See you in #850
