### ISSUE TITLE
Create a new repository for NEO3

### ISSUE THREAD

**Issue by canesin** [neo-project/neo#727]
First: I understand the urge to keep it cozy and just maintain a "master-2.0". But, NEO has not have the best git workflow from start, so same as starting clean chain in NEO3 will be great for the blockchain starting a clean repository with a established workflow will be good for NEO3 development.
 
Second: it is madness to understand what is landing in what. I sometimes get mini heart attacks when I see things merged. Please let's keep NEO2 stable for at least 3 to 5 years in a long term support (LTS) mode with bug fixes only.

Third: With NEO3 we have a great opportunity to not only think of features but developer experience, we could have the NEO3 repository to be base library + cli, in a mono repo format. So that there is less technical debt.

**Comment by lllwvlvwlll** [comment]
From an ecosystem perspective, this also alleviates many of the development constraints.  The core development team would have the ability to implement from scratch with less concern about introducing changes which are completely backwards compatible.  

Understanding every Usecase (both business and technical) and considering them for breaking changes is a very complicated component of the Neo 3.0 development path.  Maintaining an LTS version would help with many of these difficulties.

**Comment by igormcoelho** [comment]
I won't oppose in having a separate repository for this, if it pleases communities and business around Neo. Perhaps github.com/neo-project/neo3 ?
If that's the direction, we could indeed have a neo3/core, neo3/plugins folder and also neo3/cli. So it becomes a single project complete package solution.

**Comment by shargon** [comment]
I am agree with you, we should try to focus on neo 3 and don't touch neo 2 (just if is necessary), maybe the use of other repository is a good start.

**Comment by canesin** [comment]
@igormcoelho that is exactly what I have dream with the 3rd point! I think all we need now is @erikzhang! Erik, imagine core, cli and plugins living in a NEO3 repository, no more chasing tags. No more Fabio annoying you to do so. <3 only win.

**Comment by igormcoelho** [comment]
I think there are two things here... one thing is to decide on a new repository, which will reset basically everything from scratch, including followers, stars, everything. 
Another thing is to unite the main three or four projects together (core/plugins/cli/vm), what could be done even for branch version 2.0 as well as 3.0 (and 4.0 so on).
In my opinion, NeoVM could rest as a separate project, as it is meant to be fully independent from Neo. The rest two (cli and plugins) could be merged with neo, even for 2.0 version, in order to provide unified versioning between these "packages".
So, we could have two versions: neo (cli) 2.10.X + vm (2.X). If we freeze features, only bugfixes will follow and numbering will be quite stable for 2.0 family.
On the other hand, a `master-2.0` is a good strategy to keeping us free to work on 3.0 (on pure `master`), while 2.0 is maintained quite stable (as community seems to wish).

So, in my opinion, there are two questions here:
Q1) create a brand new repository just for neo3? (and about neo4, 5, ...)
Q2) unify projects plugins and cli into neo? (possibly vm too, although I'd prefer not to)

**Comment by vncoelho** [comment]
Let's leave neo-vm alone, as you suggested, @igormcoelho.
I think that sounds plausible for ensuring neo-vm as a standard.

I believe that either Q1) or Q2) should be applied as soon as possible.
What do you prefer @erikzhang  and @shargon?

Let's just consider that NEO 4.0 and other version will come, thus, many repositories might obviously be not the best choice.

From my perspective, Q2) is enough, if we have a strong README presenting NEO 3.0 and reporting previous versions.

**Comment by canesin** [comment]
If we go with Q2 and not Q1 I think that it should be done now, in NEO2 also, so that 2.10.2 is cut on this new integrated repository. Will also make much easier to port bug fixes from cli and plugins for a while.

**Comment by igormcoelho** [comment]
Another very quick way to do this is by using git submodules... this could easily take content from those projects to here, and keep them united after that. It could be another plan to do it, without any bigger impacts right now.

**Comment by canesin** [comment]
Please don't use submodules, it becomes a mess.

**Comment by igormcoelho** [comment]
I agree, a permanent solution is better. The faster we merge git histories into a unified project, the better.

**Comment by vncoelho** [comment]
@canesin, we had a talk this afternoon and another option that came was: Q3) to leave the current repo as official master of NEO 3 and create another repo NEO2.
This makes for sense to me.

**Comment by shargon** [comment]
Related to https://github.com/neo-project/neo/issues/330

**Comment by gsmachado** [comment]
I like the idea mentioned by @vncoelho: creating a repo for NEO2 and leave the `neo-project/neo` for NEO3 development.
In my humble opinion, it's very key that we keep NEO2 to a very stable mode. We should switch NEO2 to a "maintenance/stable mode" -- meaning: just solving bugs, enhancing current features... and no additional features on it!
That's my 2 cents. :-)

**Comment by vncoelho** [comment]
In fact, that was @shargon's idea during our afternoon meeting...ahauahah

**Comment by erikzhang** [comment]
So, what's the difference it and this idea: creating a new branch for NEO2 and leave the `master` branch for NEO3 development?

**Comment by vncoelho** [comment]
I really do know, @erikzhang.
In my opnion the difference is the README and a precise explanation.
We also need more explicit link of commits instead of nugets, commits are the true link and history.

**Comment by igormcoelho** [comment]
One difference is the issue tracking, readme, releases (with bugfixes), and the transparency that only a master branch has. Creating a neo2 looks nice to me now, and we could focus on bugfixes easily and unification from other projects.

**Comment by vncoelho** [comment]
In principle, @neo-project/core agrees in not opening a new repository.

The current infrastructure is basic divided as described below:

* [neo](https://github.com/neo-project/neo) - core implementation
* [neo-cli](https://github.com/neo-project/neo-cli) - In the future another community may be the maintainer of it
* [neo-plugins](https://github.com/neo-project/neo-plugins) - Additional non-essential features
* [neo-vm](https://github.com/neo-project/neo-vm) - An independent project that makes the neo-vm flexible for being ported to other Blockchain structures

In this sense, the plan is to keep the current infrastructure, but each time improve the UT of each of them.

The idea is to close this issue for avoiding loosing the focus of the current development.
However, thanks for the nice insight @canesin, this discussion was healthy and good for planning the future directions.

**Comment by lllwvlvwlll** [comment]
What is the justification for maintaining 2 diverging projects in the same repo?  There are a number of issues with this and I fail to see any benefits short of comparing how much has changed between neo2 and neo3 (This has limited value because there is no intention of merging).  

As we move towards true releases for neo3.x; we are going to enter into a organizational nightmare where we are interleaving two completely independent project releases at alternating versions.

**Comment by lock9** [comment]
Hi @neo-project/core,  I would like to reopen this issue, this is the most upvoted issue in our repository and it got several votes from core developers too. Maybe it wasn't discussed properly? 

I understand we are not creating a new repository for Neo 3, but there is a middle term that I believe most people has some agreement, that is to unify it into a single solution.

![image](https://user-images.githubusercontent.com/38396062/65562740-d3162400-df1d-11e9-8303-c31d5ab90b97.png)

What I believe has been accepted by the majority of community developers and core developers:

> First: I understand the urge to keep it cozy and just maintain a "master-2.0". But, NEO has not have the best git workflow from start, so same as starting clean chain in NEO3 will be great for the blockchain ~starting a clean repository with a established workflow will be good for NEO3 development~.
> 
> Second: it is madness to understand what is landing in what. I sometimes get mini heart attacks when I see things merged. Please let's keep NEO2 stable for at least 3 to 5 years in a long term support (LTS) mode with bug fixes only.
> 
> Third: With NEO3 we have a great opportunity to not only think of features but developer experience, we could have the NEO3 repository to be base library + cli, in a mono repo format. So that there is less technical debt.

Why can't this be implemented if this is the most upvoted suggestion we have? 
How many votes do we need to accept something?

**Comment by vncoelho** [comment]
I agree, Ricardo. But it was intensively discussed by Core developers at that time, both in private and on our monthly meeting. Even Canesin was aware since we called them by phone.

My last comment was made in an agreement and during our monthly meeting, that is exactly why I mentioned that Core devs did not agree.

However, discussions are always open.
I believe people still need to better understand the current structure and branches.

**Comment by lock9** [comment]
People won't stop to understand anything, they will just leave the project. We have a migration coming and there is absolutely no reason to believe that these people and projects can't migrate to a different chain.

We are ignoring what the community members are asking for without clear arguments. Why? What was the decision process? Who voted in favor and who voted against? 
There is no evidence that this would harm the project, but the opposite.

**Comment by EdgeDLT** [comment]
Sorry for chiming in late, but I would like to see this issue re-opened and discussed further. I have talked to quite a few developers outside the NEO community who have complained about how confusing the current setup is. I try explain as best I can, but doing so in one-on-one conversations is not exactly a scalable solution 😜 

I also noticed that @igormcoelho already suggested what seems to be a good compromise?

> In my opinion, NeoVM could rest as a separate project, as it is meant to be fully independent from Neo.

It seems this is the main issue, now that the VM is decoupled, right? So can we not use a single repository for all others, and just keep NeoVM separate?

That seems to be the best way to keep everyone happy, and it would sure make my life easier when trying to get Ethereum and other blockchain project developers interested in what we are doing here 😄

**Comment by igormcoelho** [comment]
This is not an autocracy @lock9, if you think this was not enough discussed, let's re-open and hope for another solution.

**Comment by lock9** [comment]
I think the agreed solution was:
- Single repository for Neo 3
  - Use this repository for Neo 3, merge projects into a single solution
  - Use different repositories for Neo 2 only (except VM);
  - One *solution* using *project references* (except VM)
- VM in a different repository

Note: Neo is a library, this is a change proposed not to satisfy "engineering" needs, but the usability of it, allowing new people to join Neo and build their products on top of it.
