### ISSUE TITLE
Storage return different value on neo-cli-2.10.2preview3

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#732]
I finished the test of neo-cli2.10.2preview3 on mainnet, find some storage returned different value. I've made a comparison of 1000 recently active addresses which are making nep-5 transactions and get the balance of these.And I find more than 10 difference among that. Here is one of them:
{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "c9c0fc5a2b66a29d6b14601e752e6e1a445e088d",
    "balanceOf",
    [
      {
        "type": "Hash160",
        "value": "7422120a42a2a0d311bfb3bbe69674e6fc5c6250"
      }
    ]
  ],
  "id": 3
}
![image](https://user-images.githubusercontent.com/38493437/57564628-71777200-73e1-11e9-8332-278c88182e2d.png)
![image](https://user-images.githubusercontent.com/38493437/57564633-776d5300-73e1-11e9-9d7b-efddb615b02f.png)

seed9 is on neo-cli2.9.4 and the other is on neo-cli2.10.2preview3.

Then I made a comparison of storage on mainnet. Still some of them has the difference. For example, at the height of block":3600005".

![image](https://user-images.githubusercontent.com/38493437/57564668-15611d80-73e2-11e9-95df-211981eaa45f.png)

[{"block":3600005,"size":7,"storage":[{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e63657357946e243147625f0003c39682cd74698c19eed6150000000004","value":"00668203001432e125258b7db0a0dffde5bd03b2b859253538ab020575c6b07b0700209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc50205ae968b8c0c00148d085e441a6e2e751e60146b9da2662b5afcc0c90206e088f6930c1e00"},{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba36f6666657273301b870078ff86daf82500bc7bf1997cd3b5f714d7691c8b3e5b5200b7ca03bfe565000000000000000000000a","value":"00a58109001457946e243147625f03c39682cd74698c19eed61500148d085e441a6e2e751e60146b9da2662b5afcc0c90006c0345e5bd30000209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5000562c9dfe4000006c0345e5bd300001432e125258b7db0a0dffde5bd03b2b859253538ab0000002465326631316263392d616566662d343137312d626365322d30373639613130343733363300"},{"state":"Deleted","key":"0ffd83cc1e61bd749ecbb9f998d754860e2288940ffe750ffe756253270652d52e7f565f00de093673022e4f975b17501c45dfe5cd005d3341b4d9fb000000000000000000000a"},{"state":"Changed","key":"0ffd83cc1e61bd749ecbb9f998d754860e228894e50655049f86aef7493a59fd0378210600d99dd3649b7cffdaa674beae0f930ebe006085af9093e5fe56b34a5c220ccdcf6e00fc336fc50000000000000000000000000c","value":"000589614b820100"},{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e636573ed9028669dc2d246001c9e15e7c39e918f3099b4b20000000004","value":"001f82010014b3a766ac60afa2990d9251db08138fd1facf07ed0205b8011a091900"},{"state":"Deleted","key":"b3a766ac60afa2990d9251db08138fd1facf07eded9028669dc2d2461c9e15e7c39e918f003099b4b20000000000000000000000000c"},{"state":"Changed","key":"b3a766ac60afa2990d9251db08138fd1facf07edd4c357a466cf12e8167b00a440f78270005dcf2ba30000000000000000000000000c","value":"00069f40bf5c2a2900"}]}]

[{"block":3600005,"size":7,"storage":[{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e63657357946e243147625f0003c39682cd74698c19eed6150000000004","value":"00668203001432e125258b7db0a0dffde5bd03b2b859253538ab020575c6b07b0700209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc50205ae968b8c0c00148d085e441a6e2e751e60146b9da2662b5afcc0c9020660f628b3202000"},{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba36f6666657273301b870078ff86daf82500bc7bf1997cd3b5f714d7691c8b3e5b5200b7ca03bfe565000000000000000000000a","value":"00a58109001457946e243147625f03c39682cd74698c19eed61500148d085e441a6e2e751e60146b9da2662b5afcc0c90006c0345e5bd30000209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5000562c9dfe4000006c0345e5bd300001432e125258b7db0a0dffde5bd03b2b859253538ab0000002465326631316263392d616566662d343137312d626365322d30373639613130343733363300"},{"state":"Deleted","key":"0ffd83cc1e61bd749ecbb9f998d754860e2288940ffe750ffe756253270652d52e7f565f00de093673022e4f975b17501c45dfe5cd005d3341b4d9fb000000000000000000000a"},{"state":"Changed","key":"0ffd83cc1e61bd749ecbb9f998d754860e228894e50655049f86aef7493a59fd0378210600d99dd3649b7cffdaa674beae0f930ebe006085af9093e5fe56b34a5c220ccdcf6e00fc336fc50000000000000000000000000c","value":"000589614b820100"},{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e636573ed9028669dc2d246001c9e15e7c39e918f3099b4b20000000004","value":"001f82010014b3a766ac60afa2990d9251db08138fd1facf07ed0205b8011a091900"},{"state":"Deleted","key":"b3a766ac60afa2990d9251db08138fd1facf07eded9028669dc2d2461c9e15e7c39e918f003099b4b20000000000000000000000000c"},{"state":"Changed","key":"b3a766ac60afa2990d9251db08138fd1facf07edd4c357a466cf12e8167b00a440f78270005dcf2ba30000000000000000000000000c","value":"00069f40bf5c2a2900"}]}]

The first one is from 2.10.2preview3, the second one is from 2.9.4 which is the correct.
It should be because of [138](https://github.com/neo-project/neo-vm/pull/138)'s change since I also returned to [140](https://github.com/neo-project/neo-vm/pull/140) which get the correct result. And I also returned to [138](https://github.com/neo-project/neo-vm/pull/138), it gets the same wrong result.
@shargon @vncoelho

**Comment by erikzhang** [comment]
@neo-project/core If anyone can confirm this issue, we must revert neo-project/neo-vm#138

**Comment by shargon** [comment]
The first one is on block 3600005 ?

**Comment by superboyiii** [comment]
No, many blocks. I just choose one of them to make comparison to confirm the difference of storage value.

**Comment by shargon** [comment]
Could you give me the first one, is easier for debug purpose.

**Comment by superboyiii** [comment]
Sure. Let me try.

**Comment by superboyiii** [comment]
@erikzhang @shargon After several hours' comparison, I find the first difference which is on the height of 3534243. Seems the pull#138 version has some missing of state at storage. Here's the difference.
![image](https://user-images.githubusercontent.com/38493437/57571023-520d3300-743b-11e9-887e-f53deaa4de4f.png)
![image](https://user-images.githubusercontent.com/38493437/57571027-605b4f00-743b-11e9-9b6b-0d6ee4a9aab0.png)

[{"block":3534243,"size":10,"storage":[{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e6365730a22b53c379eceba007f93ea19be90e51ced02d2d00000000004","value":"002a820100209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5020400a3e11100"},{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba36465706f736974656433cc91dcfb556e00df1efac7516646b8e5d91b20442097c600a61a32a8bcb89c59a00000000000000007","value":"00010100"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb89162616c616e636593faaa788953e803a10078d3b1303ffbc7a11c9fde32e125258b007db0a0dffde5bd03b2b859253538ab0001"},{"state":"Added","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177696e6793faaa78890053e803a178d3b1303ffbc7a11c9fde3200e125258b7db0a0dffde5bd03b2b85925003538ab000000000000000000000000000d","value":"00210c80cde7e80100000000000000000000000000000000000000000000000000000000"},{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e63657360bf4d32b1937dc80095d4b98863005265a50db3b20000000004","value":"00fd9a01820d00209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc502052371593a22001432e125258b7db0a0dffde5bd03b2b859253538ab02065c87a2a1860b0014ac0968b1cde328a4ca0f87bbc63fc3768a2746710206dff4f2cede0000148558ca14c02f47b85f4a2404f4a53ff7a693d44502053518f662320014f9e6e770af783d809bd1a65e1bb5b6042953bcac02060c433af27e01001471496142de066bd6b7a2d6a166dc47a543d1c0ba0206560fa06aba020014187fc13bec8ff0906c079e7f4cc82767094729130206001444f1f1280014c9d870d7857e956d82290d5df19de3133c10781502064e321869270100140577216c846a8307a297fd08c82f69ccd854ad6f020658b02ac4f5100020e72d286979ee6cb1b7e65dfddfb2e384100b8d148e7758de42e4168b71792c6002056174337e03001437e558ef781b899d61fe204c75761e699bd42ede02059b12b001770014b3a766ac60afa2990d9251db08138fd1facf07ed0205d1f9139c0100148d085e441a6e2e751e60146b9da2662b5afcc0c9020500f2052a0100"},{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba36f6666657273c0ffcc2d14310a6f36e9009b5addbc47a93cc5666d1c7743cc3efc00047ee3af562b000000000000000000000a","value":"00998109001460bf4d32b1937dc895d4b98863005265a50db3b2001432e125258b7db0a0dffde5bd03b2b859253538ab000600f61f1d08010014ac0968b1cde328a4ca0f87bbc63fc3768a27467100050068a20301000600f61f1d0801001432e125258b7db0a0dffde5bd03b2b859253538ab0000002436353236313033362d396462632d343264352d613963322d32343939363838613663663300"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177696e6775125f548500a19130652ac81b3beb16db50d4dff0e7002d286979ee6cb1b7e65dfddfb2e38410000b8d148e7758de42e4168b71792c600001"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177616c5554584f826d009281832917fed0eef62dc3986e7ab828009843b7cadf0433959c2432653b2f000002"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb89162616c616e636580b06f756d8891972b009193d5bbeb91de88f989a932e125258b007db0a0dffde5bd03b2b859253538ab0001"},{"state":"Added","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177696e6780b06f756d008891972b9193d5bbeb91de88f989a93200e125258b7db0a0dffde5bd03b2b85925003538ab000000000000000000000000000d","value":"0021ede50786f40100000000000000000000000000000000000000000000000000000000"}]}]

[{"block":3534243,"size":13,"storage":[{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e6365730a22b53c379eceba007f93ea19be90e51ced02d2d00000000004","value":"002a820100209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5020400a3e11100"},{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba36465706f736974656433cc91dcfb556e00df1efac7516646b8e5d91b20442097c600a61a32a8bcb89c59a00000000000000007","value":"00010100"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb89162616c616e636593faaa788953e803a10078d3b1303ffbc7a11c9fde32e125258b007db0a0dffde5bd03b2b859253538ab0001"},{"state":"Added","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177696e6793faaa78890053e803a178d3b1303ffbc7a11c9fde3200e125258b7db0a0dffde5bd03b2b85925003538ab000000000000000000000000000d","value":"00210c80cde7e80100000000000000000000000000000000000000000000000000000000"},{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e63657360bf4d32b1937dc80095d4b98863005265a50db3b20000000004","value":"00fd9a01820d00209b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc502052371593a22001432e125258b7db0a0dffde5bd03b2b859253538ab02065c87a2a1860b0014ac0968b1cde328a4ca0f87bbc63fc3768a2746710206dff4f2cede0000148558ca14c02f47b85f4a2404f4a53ff7a693d44502053518f662320014f9e6e770af783d809bd1a65e1bb5b6042953bcac02060c433af27e01001471496142de066bd6b7a2d6a166dc47a543d1c0ba0206560fa06aba020014187fc13bec8ff0906c079e7f4cc82767094729130206001444f1f1280014c9d870d7857e956d82290d5df19de3133c10781502064e321869270100140577216c846a8307a297fd08c82f69ccd854ad6f020658b02ac4f5100020e72d286979ee6cb1b7e65dfddfb2e384100b8d148e7758de42e4168b71792c6002056174337e03001437e558ef781b899d61fe204c75761e699bd42ede02059b12b001770014b3a766ac60afa2990d9251db08138fd1facf07ed0205d1f9139c0100148d085e441a6e2e751e60146b9da2662b5afcc0c9020500f2052a0100"},{"state":"Added","key":"d4c357a466cf12e8167b00a440f782705dcf2ba36f6666657273c0ffcc2d14310a6f36e9009b5addbc47a93cc5666d1c7743cc3efc00047ee3af562b000000000000000000000a","value":"00998109001460bf4d32b1937dc895d4b98863005265a50db3b2001432e125258b7db0a0dffde5bd03b2b859253538ab000600f61f1d08010014ac0968b1cde328a4ca0f87bbc63fc3768a27467100050068a20301000600f61f1d0801001432e125258b7db0a0dffde5bd03b2b859253538ab0000002436353236313033362d396462632d343264352d613963322d32343939363838613663663300"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177696e6775125f548500a19130652ac81b3beb16db50d4dff0e7002d286979ee6cb1b7e65dfddfb2e38410000b8d148e7758de42e4168b71792c600001"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177616c5554584f826d009281832917fed0eef62dc3986e7ab828009843b7cadf0433959c2432653b2f000002"},{"state":"Deleted","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb89162616c616e636580b06f756d8891972b009193d5bbeb91de88f989a932e125258b007db0a0dffde5bd03b2b859253538ab0001"},{"state":"Added","key":"26ae7c6c9861ec418468c1f0fdc4a7f2963eb8917769746864726177696e6780b06f756d008891972b9193d5bbeb91de88f989a93200e125258b7db0a0dffde5bd03b2b85925003538ab000000000000000000000000000d","value":"0021ede50786f40100000000000000000000000000000000000000000000000000000000"},{"state":"Changed","key":"d4c357a466cf12e8167b00a440f782705dcf2ba362616c616e6365732fbaa22d64a8c8f500a9940f359cb0cb1dfe49eb2c0000000004","value":"001d820100148d085e441a6e2e751e60146b9da2662b5afcc0c90203089e7600"},{"state":"Changed","key":"8d085e441a6e2e751e60146b9da2662b5afcc0c942616c616e63655072656669785f00d400c357a466cf12e8167b00a440f782705d00cf2ba3000000000000000000000000000d","value":"0005e5860ef03d00"},{"state":"Added","key":"8d085e441a6e2e751e60146b9da2662b5afcc0c942616c616e63655072656669785f002f00baa22d64a8c8f5a9940f359cb0cb1dfe0049eb2c000000000000000000000000000d","value":"00068023bce88e0000"}]}]

The smaller one is from pull#134 version and the other is from 2.10.2preview3

**Comment by shargon** [comment]
So we should revert the #134 for neo2?

**Comment by superboyiii** [comment]
Should be, I think.

**Comment by shargon** [comment]
Is fixed?

**Comment by superboyiii** [comment]
Yes. Close.
