### ISSUE TITLE
Reduce tx hash size for Neo 3

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#734]
This may be a crazy idea. Why do we need 32 bytes for a tx hash size? Isn't a smaller number, like 16 not enough?
To cut parts of it, we could enforce clients to hash with a given.number of zeroes, since the genesis. Block hashes could still br big to not give extra work to consensus.
Do you think its unsafe to use Hash160 instead of Hash256 and cut more four zeroes manually (pow-like)? Block headers would be half...

**Comment by shargon** [comment]
Less size, more collisions...

**Comment by igormcoelho** [comment]
Do we know of any hash256 colision?

**Comment by shargon** [comment]
Not **today** 😂

**Comment by vncoelho** [comment]
What would you say if you see a colision of 16 bytes?

**Comment by shargon** [comment]
Maybe we can save a counter, when we persist a new block, we can assign an index from these transactions, and store only the indexes (BigInteger) and we will save a lot of space without reduce the hash length

**Comment by igormcoelho** [comment]
I mean, my plan was not to SUBSTR the Hash, but to force people to calculate tx hashes that start with many zeroes.
Leave it for Neo 4 xD
