### ISSUE TITLE
Do we need an official forum? 

### ISSUE THREAD

**Issue by Grace-Gui** [neo-project/neo#735]
It has been discussed often whether we should have an official forum. There are many benefits of having it, such as discussions can be divided into different modules, and the questions discussed can be better recorded without repeating answers from time to from and so on. However, setting up a forum may have duplicate functions with other existing channels and require additional maintenance. 

Is it necessary to set up a forum? If so, how can we design the forum and maintain it?

**Comment by shargon** [comment]
Like you said, a forum have a lot of benefits, but maybe we need to define a only way for centralize this kind of questions, or discord, or forum, not both.

**Comment by Grace-Gui** [comment]
I think different platforms have different functions. There should be a main access while the others can remain as supplementary. I agree with you that we can guide similar needs to a unified platform for better discussion.

**Comment by steven1227** [comment]
Forum is better. For the question/discussion on discord, it still can be discussed on discord as it is a real time chat tool. Then when people ask questions on discord, we can use some bot to find similar question on forum and refer to them

**Comment by EdgeDLT** [comment]
I've advocated having a NEO forum for a long time. Discord and Reddit are great for discussion but the impermanence of posts is a problem and results in a lot of wasted repetition of information. 

Having a forum would allow us to maintain useful content such as FAQs, troubleshooting steps, and make it easier for people to search for specific information. 

The only downside as you mentioned is that they tend to take a lot more effort to maintain. Perhaps it would be better to encourage the development of a community-operated NEO forum rather than an official one.

**Comment by Bayalu** [comment]
Forum is an ideal, where one can find all the information one is looking for. whether it is a price and trading topic, monthly Dev update/ development, marketing, related projects etc...

**Comment by steven1227** [comment]
@EdgeDLT  Agree. Looks like developers and communities prefer there can be a forum. Then the only issue we have now is deciding who can maintain this.

**Comment by Grace-Gui** [comment]
> I've advocated having a NEO forum for a long time. 

Hi Edge, long ago I think some community members even designed a forum prototype. Do you have any good suggestions on the section design? I think a good design may also help the maintenance issue.

**Comment by EdgeDLT** [comment]
There are advantages to having lots of sections for organization, but it may be better to keep it simple. Something like this?:

**General**
- Announcements
- NEO Discussion
- Project Discussion
- Resources (FAQ, Links etc)

**Technical**
- NEO Core (Consensus, NeoVM, economic models, voting etc)
- Smart Contracts (ideally needs a way to tag posts by language)
- Resources (Quick start guides, reward/bounty program information etc)

**Support**
- Troubleshooting FAQ 
- Request Help

**Comment by Grace-Gui** [comment]
I think simple design is good. It can be easier to maintain and make the discussion more focused. Maybe add "Event" in General session. And change "NEO Core" to "NEO Core & NEP". I think this part can be a brainstorm on forum and then moved to GitHub, since GitHub may be a better place for those discussion.

**Comment by lock9** [comment]
Hello people, what is the current situation of this issue? Are we building this forum?
@Grace-Gui do you need help?

**Comment by Grace-Gui** [comment]
After some discussion, we decide to postpone the plan of the forum. We'd like to reorg all the current different platforms, including docs page, discord and website for people to scan info more easily. Besides, we'll enrich our FAQ library.  If the above measures are not enough, we will build a forum then.
