### ISSUE TITLE
Incorrect GAS balance from "getaccountstate" of JSON-RPC API

### ISSUE THREAD

**Issue by rockacola** [neo-project/neo#74]
The output of `getaccountstate` appears to have provide imprecise value for GAS with decimals.

Examples:
- Transfer 0.00012 GAS between testnet wallets: https://neoscan-testnet.io/transaction/745d4b7ace43d28ad5712bf61a7d0304836af21fa7ca5035958591d907ffc808
- The GAS balance of wallet `AVUfegS354LWRoBuCzuKjGCYkT3tnpFFTD` should now be `2999.99988`, down from `3000`.
- Notice that the blockchain explorer is stating that wallet `AVUfegS354LWRoBuCzuKjGCYkT3tnpFFTD` has `3000`, which is incorrect.
- Obtain account balance details directly using JSON-RPC also provide incorrect GAS balance:
```
result: {
  version: 0,
  script_hash: '0x8751c9a9aad30f4bed5569eab42c53b7d6ac5096',
  frozen: false,
  votes: [],
  balances:
    [{
        asset: '0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b',
        value: '598'
      },
      {
        asset: '0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7',
        value: '3000'
      }
    ]
}
```

**Comment by Ray-77** [comment]
I did all the things exactly as you said , but finally found the "getaccountstate" of JSON-RPC API is correct , as shown below :
![1](https://user-images.githubusercontent.com/17636881/31371809-85736b76-adc5-11e7-9727-c190eabd5c97.png)
By the way , I've also  get the state of your account AVUfegS354LWRoBuCzuKjGCYkT3tnpFFTD , as shown below , I want to know if it's correct :
![2](https://user-images.githubusercontent.com/17636881/31371881-e5e98a6c-adc5-11e7-9188-5290927df7ae.png)

**Comment by rockacola** [comment]
Attempt to replicate the concern, but seeing slightly different result:

* Fund a new wallet `AZ2BG1o6sUfggw1yajc7sVrfxZWLb79HxB` on testnet with 2 NEO and 2 GAS:
  * https://neoscan-testnet.io/address/AZ2BG1o6sUfggw1yajc7sVrfxZWLb79HxB

* Use `neon-js` to transfer `0.00013 GAS`  with `neon.doSendAsset()` method.
  * https://neoscan-testnet.io/transaction/12f2894b45a9673a107a8adb694340791d66082b51ed8b1923a119d6bd0b1351
  * Obtained response: `{ jsonrpc: '2.0', id: 4, result: true }`

* Direct JSON-RPC request to obtain account balance:
  * `GET http://seed1.neo.org:20332?jsonrpc=2.0&method=getaccountstate&params=['AZ2BG1o6sUfggw1yajc7sVrfxZWLb79HxB']&id=0`
  * Obtained response:
```json
{
  "jsonrpc":"2.0",
  "id":0,
  "result":{
    "version":0,
    "script_hash":"0xa72cda1aeee2b01f8f3ad2c1053cda3af1a92ebd",
    "frozen":false,
    "votes":[

    ],
    "balances":[
      {
        "asset":"0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
        "value":"2"
      },
      {
        "asset":"0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
        "value":"1.99987001"
      }
    ]
  }
}
```

* Noticed the balance of GAS (`0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7`) expected to be `1.99987`, but actually gets `1.99987001`.

**Comment by snowypowers** [comment]
hi @rockacola I did some testing on my side too regarding this issue.

For the example you raised, the RPC result was correct as the transaction actually sent `0.0001299` gas instead of your intended `0.00013` gas. I believe this error would lie on `neon-js` side rather than RPC side. 

I have done some testing with `neon-js` on my side and have not encountered any cases where neon sends out a different amt. These are my test cases:

```
Sent 0.00001234
a3e111c7efe93926540a05385859eeb5a301efcf18982ace552b8c7596142436
Sent 0.00004321
f7d2c255b03c35f96c119d2d6e7ac674f5eff632a8cf841dfde3b54f7c03060a
Sent 0.00043
5fef0424bbb9de422258cbb892fc528c63cfbf4b27364d4ae3db6ffbd2e9a9b2
Sent 0.00013
ffde0f3c4872d1719083b1d3e1bde20f0f602d50201294f9ec5764ec8cfbe1e2
```

I am using latest `dev` of `neon-js` tho so maybe the next update will squash these issues.

**Comment by erikzhang** [comment]
https://github.com/CityOfZion/neon-js/issues/22
