### ISSUE TITLE
Funds getting transferred to another wallet automatically

### ISSUE THREAD

**Issue by pdkproitf** [neo-project/neo#748]
The problem happens in 2018 but it still exists till now.

Neo asset automatically transfers to the same another address just a few moments after the address funded.

The transaction:
https://neoscan-testnet.io/transaction/ec82286d69f224c13ac31efeb2308df37d7790d09a112035dd159ee6d669f83f

Anyone know why?
https://github.com/neo-project/neo/issues/178

**Comment by fabwa** [comment]
There are bots looking for open RPC nodes with opened wallets that transfer funds out. Whitelist IPs if you need to use RPC for some reason. https://docs.neo.org/en-us/node/cli/latest-version/api.html

**Comment by pdkproitf** [comment]
Yep, I guessed so. I already whitelist IPs. 
But don't know why people do that?
Thank you @fabwa
