### ISSUE TITLE
NEO3 should use a different nuget package name.

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo#756]
Neo3.x and 2.x is very different for now.

Neo 2 is use NEO for nuget packageName
like NEO NEO.VM

how about NEO3  use NEO3 for nuget package name.

like NEO3   NEO3.VM

**Comment by vncoelho** [comment]
These nugets are another planet to me, @lightszero....aehauehauea
But I agree with you, even without using it. But this discussion I leave to you! :dagger: 

I think that the best standard is to follow commits and report the hashes of all packages during releases.

**Comment by erikzhang** [comment]
But the packages have version number, right?
Neo 2.10.2
Neo 3.0.0

**Comment by lightszero** [comment]
I think neo3 is another branch ,it is not a update for neo2,different package name will be more clear.

**Comment by vncoelho** [comment]
Hi @lightszero,
As I said, I am not familiar with nugets, thus, fell free to do not consider my comment. But I think that versions are enough.
I think that, as it is right now, we give more emphasis in the notion that we are under continuous improvements.

**Comment by erikzhang** [comment]
After NEO 3.0 MainNet, NEO 2.0 will no longer be developed. If we use different package name, the old name (which is a good name) is wasted.

**Comment by lightszero** [comment]
got it
