### ISSUE TITLE
Moving voting to the mempool layer - Lightning Voting in the Native Contract

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#757]
closes #300 
closes https://github.com/neo-project/proposals/pull/82

NEO holders should be able to modify validators during block creation.
In this sense, the proposed mechanism allows voting to happen in an upper layer, namely, in the mempool.
This was an insight with a discussing with @jsolman.

I believe that we could try to implement this for NEO3 while doing the Native Contract for Voting. What do you think @igormcoelho?

**Comment by erikzhang** [comment]
In mempool, how do you solve the consistency problem?

**Comment by vncoelho** [comment]
What is the current feasibility of this, @erikzhang?
I do not see a simple way of counting the votes in the mempool, that is not really scalable.

On the other hand, we could do it in a third party service and just publish `newvalidators` as a single transaction.

If the block has a valid `newvalidators`, then, current consensus should be the one described after this transaction is included.
How to process this information while processing other information of the block?

**Comment by vncoelho** [comment]
I was just going to ask what you asked, @erikzhang.

Maybe the new validators can publish this block with a single transaction that calls this function (`newvalidators`) of the Native Contract.

* This block should have a simple transaction (for simplicity and avoiding inconsistencies)

In this sense, the new set of validators just would need a third party website to accumulate the valid votes and then publishing the transaction.

**Comment by vncoelho** [comment]
In fact, this is a hypothetical scenario in which `f` nodes are lost. Not something that we should really worry. aheuahuea

But it would be interesting to say that the NEO protocol can handle that by the power of voting.
I believe it can be done in a simple manner, we just need to think a little bit more.

**Comment by erikzhang** [comment]
I think this is not feasible. The matter of replacing the consensus nodes itself requires consensus.

**Comment by vncoelho** [comment]
I agree and disagree.
Consensus are chosen by NEO holders, which is a matter of signing their voting intention. Philosophically, it is an offline process (that is why we picked lighting as a name, copying BTC Lightning Network).

But I agree that it is not easy exceptions to be handled. But the power of that would remain....

**Comment by erikzhang** [comment]
In the simplest case, everyone modifies the configuration file and chooses a new set of consensus nodes. (nodes that have not modified the configuration file will fork out)

**Comment by vncoelho** [comment]
Ok, @erikzhang.
Just bypass it. But the current configuration file should have a set of consensus nodes that matches the majority voters.
For example, the first block published by this set of consensus should have this signatures.

However, consider this solution could probably be an eternal debate with old "offchain" transactions modifying the validators and forking.

**Comment by erikzhang** [comment]
Vote in mempool, if everyone is online, and every nodes are connected with each other, and every messages are sent to every nodes well, then it is feasible. Otherwise, different nodes will see different transactions in mempool, and get different consensus nodes, and fork.

**Comment by vncoelho** [comment]
That is true, @erikzhang.
Let's keep this in mind. I will keep this in mind. Thanks for the insight, my friend.
