### ISSUE TITLE
Cant Send/ Save my NEO to another Wallet or Claim GAS on NEO Tracker and NEON-Wallet

### ISSUE THREAD

**Issue by topgun881991** [neo-project/neo#767]
Hi,
I´m new on github and have this old sending NEO/ claiming GAS issue since today.

Issue on NEON Wallet:
If I try to claim GAS I receive: "Error calculating claimable GAS: Block or transaction allready exists and cannot be send repeatedly", but I haven`t receive the GAS-reward.
If I try to send my Neo out I receive: "Transaction failed: Block or transaction validation failed"

Issue on NEO Tracker:
If I try to claim GAS I receive at Point 2. Wait for confirmation of transfer: "Claiming all GAS failed: Something went wrong. trying to refreshing the page or going back to where you were.. Please try again or refreshing the page." 
I've tried this several times without succes.
If I try to Send my NEO out to save it on another Wallet, I receive a Transfer - failed - message and "Error: Unknown error"

Do anyone have a solution for this issue. My NEO and GAS seems to be frozen. 
I´m not rich and losing 9 NEO hurts a lot for me.

**Comment by jseagrave21** [comment]
@topgun881991 if you compare the node heights at http://monitor.cityofzion.io/ to the latest block on Neoscan [here](https://neoscan.io/blocks/1), [at the time of writing] you can see that Neoscan is a couple thousand blocks behind and will need to be resynced.

Neon wallet is a light wallet and uses Neoscan to get information about the Neo blockchain. So, you can either use a full node wallet or wait for Neoscan to resync before using Neon wallet. 

You can read this [article](https://www.reddit.com/r/NEO/comments/akzyke/neo_blocks_explorers_and_forks/?utm_medium=android_app&utm_source=share) about a similar older issue for more information.

Also, as I understand it, these issues should not occur after v2.10.2 is released and applied to mainnet nodes.

**Comment by topgun881991** [comment]
@jess

**Comment by topgun881991** [comment]
@jseagrave21 thanks a lot for your fast answer and your explaination.
After NEO Tracker is trying to fix the issue, it was possible to me to claim GAS at the NEON-Wallet. 
I was just in fear that I lost my NEO, but now I'm a little bit more relaxed after reading the article and understanding the issue a little bit more. Thx for your support and kind regards from Germany!
