### ISSUE TITLE
NEP5 inherit/extends from Native standard

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#772]
It would be incredibly safe for users if they manage to deploy some token contract that inherits from Native NEP5. 
It could be something declared in the manifest, for example, "inheritsFrom" : "NEP5scripthash" (or done manually, or even as part of Contract.Create informing parent hashes). The expected result for a "transfer" operation is: before invoking my contract, first invoke NEP5scripthash "transfer" with the given parameters,then invoke my operations.
We could also do this manually if a native implementation is provided. For example:

Main (op , args )
if op == "transfer", invoke "super::transfer" with my own storage.

This would make it much safer and fast to develop contracts on Neo. Whats your thoughts ?

**Comment by erikzhang** [comment]
Very interesting.

**Comment by shargon** [comment]
Is a good feature, but instead of with native contracts, with syscalls maybe

**Comment by igormcoelho** [comment]
> Is a good feature, but instead of with native contracts, maybe with syscalls

I think that any hash can be provided as the "parent hash" (or multiple parents). If native, it will be like you said, syscall +name... anyway, it could be any deployed contract (even not  native).
