### ISSUE TITLE
Is there any safe way to generate and manage NEO wallet as offline?

### ISSUE THREAD

**Issue by pdkproitf** [neo-project/neo#773]
I need to generate multi neo account. It's not a safe way to go when trying to call Neo node as `getnewaddress` of RPC and let a NEO node manage there wallet.

Is there any way to help handle this case. 
EX: In ETH or BTC there is a library named `MoneyTree` which simulate HdWallet.

**Comment by erikzhang** [comment]
You can use `neo-cli`. https://github.com/neo-project/neo-cli

https://github.com/neo-project/neo-cli/blob/6c68d5d868344917e999dd9305d26551a21097a6/neo-cli/Shell/MainService.cs#L559

There's a command: `create address [n=1]`

You can type `help` for more information.

**Comment by pdkproitf** [comment]
@erikzhang thanks for your answer.
But I think to manage addresses and the private key in the neo node is not a safe way to go.
it is easy to attacked and leak the private key.

**Comment by erikzhang** [comment]
If you don't open RPC module, it is safe to manage wallet.

**Comment by pdkproitf** [comment]
I'm building an exchange and I need to generate neo account for user dynamically. 
There are so many cryptocurrencies is integrated on our exchange. 
The Neo-cli is the full node gateway that we used to connect with the NEO blockchain.
So it had to be exposed RPC.

**Comment by erikzhang** [comment]
You can use an offline PC to create the addresses, and then copy the wallet file to the server.

**Comment by pdkproitf** [comment]
yep, I did think about that.  But it's to manually and potential for many problems.

**Comment by erikzhang** [comment]
Any suggestion?

**Comment by pdkproitf** [comment]
I'm trying to find a dynamically way to handle it.
I appreciate your help @erikzhang.

**Comment by RavenXce** [comment]
Won't simply using an offline seed with and BIP-32 work? You only need to expose an extended public key: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#unsecure-money-receiver-nmih0

**Comment by pdkproitf** [comment]
@RavenXce Thank you. I'll try it.

**Comment by pdkproitf** [comment]
@RavenXce is there any way to generate root key from mnemonic like [iancoleman](https://iancoleman.io/bip39/#english)?

**Comment by fabwa** [comment]
You can also use this javascript library for offline generation: https://github.com/snowypowers/ansy

**Comment by RavenXce** [comment]
> @RavenXce is there any way to generate root key from mnemonic like [iancoleman](https://iancoleman.io/bip39/#english)?

Yes. Just generate the appropriate keys, ideally with the correct key path:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

Derive the account scripts and addresses from either private or public keys using something like neon-js:
https://github.com/CityOfZion/neon-js

**Comment by pdkproitf** [comment]
I did with some custom from HdWallet. Thank for all support.
