### ISSUE TITLE
The same private key returns different address in neo-cli-3.0

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#776]
The same private key returns different address in neo-cli-3.0 which means neo-cli 3.0 isn't able to open old wallet created by neo-cli2.0 (db3&json).

![image](https://user-images.githubusercontent.com/38493437/58312259-83bfca00-7e3d-11e9-849d-20eb3661883e.png)

**Comment by erikzhang** [comment]
Yes. It is by design.

**Comment by superboyiii** [comment]
Seems could bring big problem when migration balance from address 2.0 to address 3.0. There might be a better solution.

**Comment by shargon** [comment]
The opcodes change, so the address change too.

**Comment by vncoelho** [comment]
@shargon, addresses can be kept if an additional mechanism transforms the old opcode to syscall in the ApplicationLayer.

**Comment by erikzhang** [comment]
I have a solution that is compatible with the old address. Please wait for my PR.

**Comment by igormcoelho** [comment]
Don't worry @superboyiii it will be made compatible :)

**Comment by vncoelho** [comment]
Go, master Yoda Jedi. :+1: 
![image](https://user-images.githubusercontent.com/17395762/58375081-6ebc6700-7f21-11e9-9125-891be49a2510.png)

We gonna wait for the PR.
![image](https://user-images.githubusercontent.com/17395762/58375088-80057380-7f21-11e9-90ca-d113f3c474f5.png)

**Comment by shargon** [comment]
Is solved?

**Comment by lock9** [comment]
@shargon I think Erik is preparing a fix for this. Do you need help @erikzhang ?

**Comment by lock9** [comment]
@neo-project/core  don't we need this for preview1? Won't this cause confusion if we release something before 'fixing' this?
