### ISSUE TITLE
NEP10 inside ContractManifest.Abi

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#779]
The proposal is simple, I think that we can move the logic of `supportedStandards` to `Contract Manifest`, more concretely, inside the Abi

**Comment by vncoelho** [comment]
I agree, @shargon.

**Comment by igormcoelho** [comment]
I agree @shargon, as long as other contracts could onchain access a contractabi (`GetContract hash` + `GetContractAbi`).

**Comment by erikzhang** [comment]
Didn't understand.

**Comment by shargon** [comment]
I think that should be good if we add `supported Standards` method inside `Abi` properties

**Comment by erikzhang** [comment]
You can read ABI, but it's hard for a contract to analyze the JSON file to get the `supportedStandards`.

**Comment by igormcoelho** [comment]
ABI and JSON could be `InteropInterface`, so they have simple methods to access information... also serialization and deserialization.

**Comment by erikzhang** [comment]
We need JSON API in smart contract.

**Comment by lock9** [comment]
@shargon  agreed.
@neo-project/core  what is your opinion?

**Comment by shargon** [comment]
It's ready to implement?

**Comment by Tommo-L** [comment]
@shargon  ping?

**Comment by shargon** [comment]
Can someone help me amending https://github.com/neo-project/proposals/blob/master/nep-10.mediawiki ?

**Comment by Tommo-L** [comment]
Both nep-10 and nep-14?

**Comment by shargon** [comment]
Yes

**Comment by Tommo-L** [comment]
We'll update them this week.
