### ISSUE TITLE
use sendRawTranscation , how to get txid??

### ISSUE THREAD

**Issue by Cren700** [neo-project/neo#795]
use sendRawTranscation , how to get txid?? This 's return only result: true, have not txid. What should i do to get this txid?

**Comment by ixje** [comment]
not really convenient but the TX id is:
```
sha256(sha256(data)).reverse()
```
where `reverse()` should operate on a uint8. So if the output of the SHA hashing would e.g. be `123456`, then `reverse()` would create `563412`.

**Comment by shargon** [comment]
Fixed here: https://github.com/neo-project/neo/pull/796
