### ISSUE TITLE
Use prevhashes field instead of prevhash on Block (Neo 3.0)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#797]
I think that, on Neo 3.0, we need to replace `prevhash` (that points to previous block), to a hash field called `prevhashes`(or `prevblocks`), that points to the  **root of a tree of hashes** that implicitly refers to **all previous blocks**.
In terms of space, it's the same (32-bytes). In terms of capability, this is amazing change, because it allows anyone to prove that a given block existed on a specific time in the past (even without showing block contents), and right now, one block only guarantees the existence of the last (and you have to do a linear search on the past to prove something existed). And using this, you can also prove that a given transaction existed in the past. It's a simple and powerful change (in my opinion, it paves the way to a strong NeoX standard for strong independent network secure information exchanges).

**Comment by shargon** [comment]
Is not the same as https://github.com/neo-project/neo/blob/918d1e46d76fdd60943e05ec3705d4665da10a0d/neo/Network/P2P/Payloads/BlockBase.cs#L16 ?

**Comment by igormcoelho** [comment]
In fact no Shargon... MerkleRoot is in fact an internal tree of ordered transaction hashes. This hash only represents this.
I'm proposing another hash to represent a tree of ordered blocks (or a hashed key-value tree of past blocks). This will allow us to prove that a given block existed in the past, while still occupying the same space on block header. Same space, much better benefits. We could do this on practice by creating another MerkleTree of past block hashes, in the order they appeared. Do you think it's a lot of space and processing, like millions of blocks in a hash tree?
Another option I imagined is to keep track of latest thousands of blocks only, organizing them in "epoches" perhaps.
