### ISSUE TITLE
Allow SC result and input to be serialised/deserialised outside the transaction execution

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#822]
I mentioned in #504  that it would be good for developers to have a map return type, however, this does not need to happen at the transaction level.
We can always work with byte arrays and have a separate "converter" to transform it into higher level objects. These conversions can be done in parallel since they don't need to access the storage or the current state.
We could do this for input and for output, allowing our SC to support 'typed object' parameters and return types.
What are your opinions? Not sure how to implement it yet.

Edit: I understand that it will consume CPU and the node should be paid for it, however, this computation can be done by other threads or 'even other nodes' if we want to, due to the fact it doesn't depend on the current state.

**Comment by igormcoelho** [comment]
Ricardo, we already have a Map on VM level... so if you return a Map (or object) on C#, there's a chance that your map is already being returned :) So, we really need to update ABI types for Neo 3, including Map officially.

**Comment by lock9** [comment]
I understand that for maps, ok, but maybe in the future, we could allow typed classes if the developer can upload serializer/deserializer for his classes.
I saw a lot - and I really mean a lot - of people having issues or spending a lot of time with the persistence layer, counting bytes and facing the strangest bugs you can imagine.

If we allow the developer to submit his serializer/deserializer we can work with objects and make our smart contracts more readable and user-friendly

**Comment by erikzhang** [comment]
We have `Any` in ABI.

https://github.com/neo-project/proposals/blob/master/nep-3.mediawiki#parametertype

https://github.com/neo-project/neo/blob/354563d0e191c1b107da17c37f85dfea0f49e031/neo/SmartContract/ContractParameterType.cs#L19

**Comment by lock9** [comment]
Hi Erik,
I understand, but this is doesn't help developers. We can't infer the data structure, making it very hard to maintain. This would also help developers to integrate with smart contracts, because now we have an interface for them to "use".

I will close this issue because I think #829 can be used to solve this problem.
