### ISSUE TITLE
Garbage Collect empty storage keys (Neo 3)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#824]
I think a very nice policy for Neo is to automatically garbage-collect empty keys.

Example:
```cs
Storage.Put("x", 10);
Storage.Put("x", Storage.Get("x") - 10);
```
This is used a lot on NEP-5 tokens, and usually we have to put an extra if, because if key is not empty (or zero-valued), we call `Storage.Delete`. It could be done automatically, which is more simple for users, and more efficient for the network (no empty keys recorded, and they take space).

Note that, one slight change may be necessary (proposed on neo-vm project): we must ensure that BigInteger format is always expressed in its _most compressed format_... meaning that BigInteger(0) will now be expressed as an empty array (not "0x00"). This is easier to understand and more space efficient (and automatically help us with this garbage collection).

**Comment by igormcoelho** [comment]
See: https://github.com/neo-project/neo-vm/issues/170

**Comment by igormcoelho** [comment]
This could also be useful for: https://github.com/neo-project/neo/issues/814, to prevent unnecessary `Storage.Destroy` operations on NEP-5.

**Comment by igormcoelho** [comment]
Implementation is simple: every time we do a `Put` (or `PutEx`), if value is an empty array, we call `Storage.Delete` automatically.

**Comment by shargon** [comment]
Then we can't do this https://github.com/neo-project/neo-vm/issues/170 :)

**Comment by erikzhang** [comment]
You should explicitly call `Storage.Delete`. An empty bytes is also a type of data that can be stored.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/fe3ab048213e36e8d40589d8ffe3176c7b63cb4d/neo/SmartContract/InteropService.cs#L473

For `Storage.Get`, if the key does not exist, it returns an empty bytes.

So, for `Storage.Put`, if the value is an empty bytes, we can just remove the entry.

This seems quite reasonable.

**Comment by igormcoelho** [comment]
> Then we can't do this neo-project/neo-vm#170 :)

In fact, it's the opposite @shargon , we need that! I'll show you on the tests there... it's all connected ;)
