### ISSUE TITLE
Should invalid contract parameter types cause failure? 

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#827]
I'm currently performing an audit of `neo-python` vs `neo-cli 2.10.2` and on testnet block `846536` I see a difference in Interop behaviour. Specifically, the syscall `Neo.Contract.Create` does not seem to care about invalid `ContractParameterType`'s.

https://github.com/neo-project/neo/blob/1e2c6c67795eed64c9266ec4292621f58a99e44f/neo/SmartContract/NeoService.cs#L664-L666

For the specific block the `parameter_list` line pops a stackitem of type `ByteArray` with a value of `{ 7, 10 }` (note these are base 10 not 16). And the `return_type` line pops a stackitem of type `Integer` with a value of `10`. 

I'm assuming the intention was to have the return type be `Array` which is `0x10` (or `16` in base 10) and instead they pushed a decimal 10. `neo-python` throws an exception because it's an invalid `ContractParameterType`, should `neo-cli` do the same?

**Comment by igormcoelho** [comment]
This looks correct to me @ixje.

Example (classic entrypoint String 0x07 and Array 0x10, returning an Array 0x10):
PUSHBYTES2 0710
PUSHBYTES1 10

This will be processed correctly... as String, Array and a return Array.
Every possible option would work, even if you push number 16 (equivalent to 0x10):

PUSHBYTES2 0710
PUSH16

**Comment by ixje** [comment]
Yeah so we have 2 choices
1. be more strict and fail on invalid parameters
2. remove specifying them as we don't use it anyways

**Comment by igormcoelho** [comment]
For existing Neo2 I don't know what's the best path... but for Neo3, we have ABI working in more details, with connection to smart contract and also with the Manifest System.. so I think it should be strict on Neo3.

**Comment by igormcoelho** [comment]
Any reason why this was closed @ixje ? I think it's a good idea for Neo 3... it makes contracts safer in my opinion.
