### ISSUE TITLE
Change NextConsensus field to CurrentConsensus field (Neo 3)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#833]
Right now, the voting that occur in a given block is only valid for the following block, and it is stored in `NextConsensus` field. However, it would be better if the voting happened _in the block itself_, thus affecting a `CurrentConsensus` field.

Example:
- Regular case: speaker proposes block A, that includes no voting tx in it. So, the voting count is kept intact, and CurrentConsensus of this block will be the same of the previous block.
- Voting case: speaker proposes block B, that includes some voting tx in it, changing some consensus nodes. Since this node is already the speaker of this _new consensus_, it considers itself valid and starts the process normally.

What could happen? Speaker could not be part of the current consensus, but it has some tx in its mempool that demonstrate it has now enough votes to be at consensus, and it is the designated speaker of that consensus, so it starts the process. However, due to some timing situation and change view, a backup assumes with different tx in mempool, where that node is not speaker anymore... so we need to deal with that.

Advantages: currently, if `f+1` nodes permanently fail, network will be stuck forever, unless we hard-fork it. This solution gives us a chance to fix the network in that scenario.

Hardfork possibilities: we need to prevent situations where different mempool voting tx gets completely different groups to get working on the same block height, thus provoking an actual hardfork (different from the "spork" situations, where no actual fork happens). This can only happen if some node, with lots of Neo, votes simultaneously in different nodes, to cause that fork _intentionally_. What's the solution to this? I think that nodes that perform this "double-voting" (which is actually a "double-spending" of votes causing "different networks") could have their votes invalidated in such situation, as it could be possible to _prove_ that those votes where both signed by it, in the same period of time, and we can do it using cross-chain capabilities that are supposed to exist on Neo3. 

There are possibly some other solutions to this, any opinions on it? The point is: `NextConsensus` is a static decision which is very good to keep everything very stable, but gives us few possibilities of "legally" fixing things without any forced hardfork, in a eventual catastrophic event.

**Comment by vncoelho** [comment]
Agree.

@jsolman, what do you think? This is aligned with the Voting on mempool.

**Comment by Tommo-L** [comment]
It seems that the introduction of `CurrentConsensus` will cause more problems.  
How about extending the `NextConseneus` script by adding `k` standby validators. The `k` standby validators will not join the consensus process, only when they find more than f+1 CNs permanently failed.

**Comment by igormcoelho** [comment]
> It seems that the introduction of CurrentConsensus will cause more problems.

Which problems do you see @Tommo-L ? Indeed it makes block-chain "less rigid" (or "less connected"), but I couldn't see many issues... advantages are great too.
