### ISSUE TITLE
Change Block CurrentTimestamp to PrevTimestamp (Neo 3)

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#839]
I think one nice we can do on Neo 3 is change the concept of Current Timestamp to Previous Block Timestamp. The reason is the following.

Right now, any bizantine node can try to force timestamp to go up (not completely, but enough to cause strange situations), and the other nodes have no "power" (and enough information) to prevent that... since this info comes already in block header, nodes need it to validate the block itself, so they are "forced" to accept the time, if it's within a somewhat reasonable (but large) interval (because clocks may drift a considerable amount of time).

However, if we consider the concept of _Previous Block Timestamp_, one nice thing will happen. When a node proposes a block, it will take the time from each CN that signed the last dbft messages (in last round), and take the _median_ (not average, as it is affected and median cannot be), to propose it. On the other hand, nodes will be able to validate this information in a much more rigid time interval than done now, as they also have much more information to decide that. The precision to drop invalid times won't be minutes, but seconds. In terms of smart contract programming, nothing will really change, as any contract can still get `PrevTimestamp + SecondsPerBlock` as the "current time", which is a reasonable approximation of current time. Logic can also be changed in a way that only depends on `PrevTimestamp`, as this is a slight time drift from current time, and it is deterministic.

This would also allow us to use this information on next dbft round to keep clocks better adjusted to reality, thus possibly achieving a nearly strict block time generation. In terms of GAS, we could also use PrevTimestamp to distribute it, as time will be better checked than now, but I guess this is another proposal pehaps.

**Comment by vncoelho** [comment]
I agree, I believe it is worth discussing and investigating.

**Comment by lock9** [comment]
@igormcoelho  hi Igor, I didn't really understand what you meant with:

> However, if we consider the concept of Previous Block Timestamp, one nice thing will happen. When a node proposes a block, it will take the time from each CN that signed the last dbft messages (in last round), and take the median (not average, as it is affected and median cannot be), to propose it. On the other hand, nodes will be able to validate this information in a much more rigid time interval than done now, as they also have much more information to decide that. 

If I understand right, we are going to request nodes "what time is it", but can this really be trusted? 
We probably need UDP for this, since TCP can 'waste time' with message retransmission.
We also measure latency between nodes. Is this possible? To calculate the latency between nodes? 🤔

**Comment by igormcoelho** [comment]
I mean, local time on node (time it received). Original sent time is hard to get and difficult to trust.

**Comment by lock9** [comment]
Sorry, I still don't understand this change @igormcoelho 😅  Maybe if you recreate this issue using the new issue template, this will help us to identify the issue? I can't understand the impacts and the proposed solution

**Comment by igormcoelho** [comment]
Will close this and re-open in the future... idea is to propose a Precise Byzantine Time Protocol.

**Comment by igormcoelho** [comment]
I'll re-open as problem doesn't seems to be solved already.

**Comment by igormcoelho** [comment]
Some recent improvements in time were made, such as https://github.com/neo-project/neo/issues/1959, by promoting local time calculation to the earliest point block is known, however, there is still a inherent uncertainty on relying on single node timers. 
We argue that it's easy and possible to fix this, by trusting on the time provided by the **median** of all nodes, meaning that it's one of the 2f+1 honest nodes. 

We also argue that timestamp is an important  **service** provided by Neo Blockchain, and if timing cannot be considered reliable, the proper approach would be to remove timestamp from blocks. So, instead of removing it, we can make it more reliable, as several real-world applications depend on it (timelock contracts, decentralized certificates, etc).
Another application is for consensus itself, since every synchronous or quasi-synchonous consensus will always rely on time. If random time values are considered, consensus would never work, so like it or not, we depend on a **more-or-less precise** time (and we can easily offer this, by simple changes).

Although we expect some deviation in times for every possible clock, we argue that **honest nodes** should make efforts to make their times as close as possible **to the real time**, and the punishment for not doing so can result in block rejection during consensus. This allows reducing current upper bound on time to virtually zero. 

Proposal is to allow first round consensus (view 0) to consider past round consensus messages to infer the correct time of previous block, as a median, that provides the time of an honest node, regardless of any single-node attack. After change views, time strategy can be removed, as fallback mechanism, if one expects that catastrophic events may require "time adjustments" in the blockchain.

**Comment by igormcoelho** [comment]
Closing in favor of https://github.com/neo-project/neo/issues/2018, which is described in new Issue format.
