### ISSUE TITLE
Add timestamp or nounce to transaction

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo#860]
Currently, there is no field in transaction can be used to distinguish two similar InvocationTransactions except adding remark attributes. 

For example, I want to transfer 5 CGAS from A to B repeatedly.  Without unique field in InvocationTransaction, this kind of InvocationTransactions are always the same. Unless we add a unique remark attribute to them. But I assume remark attribute is not designed for this purpose. 

Therefore, should we add a unique field to InvocationTransaction, such as timestamp or nounce, in order to disgingush such InvocationTransactions ?

**Comment by shargon** [comment]
Was solved on neo3, on neo2 the unique way is using Remarks, as you said

**Comment by wanglongfei88** [comment]
> Was solved on neo3, on neo2 the unique way is using Remarks, as you said

That is great. Shargon
