### ISSUE TITLE
Can't transfer from neo tracker 

### ISSUE THREAD

**Issue by justincampbell73** [neo-project/neo#873]
I'm trying to transfer my one neo from neo tracker to o3 wallet and it's not letting me send it or claim gas, it let me send all my other tokens but not neo or gas what is going on ? My wallet address is AFtkX8QfUWmGb3A7zunG11hxAFjjGKskwr

**Comment by steven1227** [comment]
@afragapane @Alex DiCarlo this is might be the neo-one node problem?

**Comment by justincampbell73** [comment]
I ended up getting my neo off it but can't get my gas off it

**Comment by EdgeDLT** [comment]
You can just log in to the O3 wallet using the same details you use for Neotracker. Funds are on the blockchain, not 'inside' a wallet so there's essentially no difference.

**Comment by lock9** [comment]
@justincampbell73 Hi, did you solve your problem?

**Comment by justincampbell73** [comment]
No but it's not much in there not enough to worry about I was just moving everything into one wallet 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:00 PM, Ricardo Prado<notifications@github.com> wrote:   
@justincampbell73 Hi, did you solve your problem?

**Comment by justincampbell73** [comment]
I tried to get my gas out I couldn't do it no matter what I did I got my neo and everything else out though 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:00 PM, Ricardo Prado<notifications@github.com> wrote:   
@justincampbell73 Hi, did you solve your problem?

**Comment by lock9** [comment]
In this case, may I close your issue? You can try to use another wallet?

**Comment by justincampbell73** [comment]
Ok but I still think it's something that would need to be fixed because it don't really store much faith in the network when people that can remove things, for me it don't matter because it's not even one gas but it still don't look good 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:22 PM, Ricardo Prado<notifications@github.com> wrote:   
In this case, may I close your issue? You can try to use another wallet?

**Comment by lock9** [comment]
Hi @justincampbell73 , I understand, but the network is working fine. Did you try to update the wallet you are using? Did you try to use neon wallet?

**Comment by justincampbell73** [comment]
I was trying to to send through neon wallet online couldn't do it then I used my private key to do it through o3 wallet and it didn't work either 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:34 PM, Ricardo Prado<notifications@github.com> wrote:   
Hi @justincampbell73 , I understand, but the network is working fine. Did you try to update the wallet you are using? Did you try to use neon wallet?

**Comment by lock9** [comment]
You are trying to transfer 0.20 gas and it is not working? Do you get an error message?

**Comment by lock9** [comment]
I just checked and gas transfers are working fine:
https://neoscan.io/transaction/f73a2429fdb6ad658d7c6e5a622c9afc2e97bbca54870066ae2ddf2e679d22f5

It is probably something in your wallet. Do you have an error message so we can help you?

**Comment by justincampbell73** [comment]
Yes, is there a minimum amount for the transfer maybe that's why its not working. I'll try again 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:38 PM, Ricardo Prado<notifications@github.com> wrote:   
You are trying to transfer 0.20 gas and it is not working? Do you get an error message?

**Comment by justincampbell73** [comment]
Yes I got an error saying Transaction failed, something went wrong with your transaction please check the network and try again 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:40 PM, Justin Campbell<justincampbell73@yahoo.com.au> wrote:   Yes, is there a minimum amount for the transfer maybe that's why its not working. I'll try again 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 8, 2019 at 4:38 PM, Ricardo Prado<notifications@github.com> wrote:   
You are trying to transfer 0.20 gas and it is not working? Do you get an error message?

**Comment by lock9** [comment]
@justincampbell73 this error happens in what software? The network is working fine, it is probably something else. Is there a chance you have firewall issues? We need "non-http" ports to communicate with the blockchain.

**Comment by lock9** [comment]
@justincampbell73 hello, how are you doing? Could you try to transfer it using the neon wallet? https://neonwallet.com
This is the wallet that I use and it is working fine here. Let me know the results.

**Comment by jsolman** [comment]
Have him try to send smaller amounts at a time. If the gas is in too many pieces it will need to have a gas fee included to send the transaction. If he is trying to send all the gas it will fail due to not having enough left to pay the fee.

**Comment by lock9** [comment]
@justincampbell73  you should listen to @jsolman, he is probably right

**Comment by justincampbell73** [comment]
I've tried everything it isn't working. I just tried 0.1 gas didn't work. It's not enough to worry about so I don't really care but it is making me think what will happen when I try to move stuff from my other wallet 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 12:50 PM, Ricardo Prado<notifications@github.com> wrote:   
@justincampbell73 you should listen to @jsolman, he is probably right

**Comment by lock9** [comment]
@justincampbell73  Could you try sending 0.03?

**Comment by justincampbell73** [comment]
Just tried it, it didn't work either 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 1:14 PM, Ricardo Prado<notifications@github.com> wrote:   
@justincampbell73 Could you try sending 0.03?

**Comment by justincampbell73** [comment]
Maybe I'll try moving one gas into that wallet and try moving it all back in 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 1:18 PM, Justin Campbell<justincampbell73@yahoo.com.au> wrote:   Just tried it, it didn't work either 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 1:14 PM, Ricardo Prado<notifications@github.com> wrote:   
@justincampbell73 Could you try sending 0.03?

**Comment by justincampbell73** [comment]
Well that sucks, I moved one ontology gas into the old wallet and sent it back to the new wallet no problem, then I sent the little bit of neo gas I had in the new wallet to the old wallet to put with it and tried to send it back and same thing didn't work again so I don't know what's going on but there is something wrong with that old wallet, it was doing it with everything that was in it but I managed to get it out of there after a few tries but the neo gas just won't budge 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 1:23 PM, Justin Campbell<justincampbell73@yahoo.com.au> wrote:   Maybe I'll try moving one gas into that wallet and try moving it all back in 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 1:18 PM, Justin Campbell<justincampbell73@yahoo.com.au> wrote:   Just tried it, it didn't work either 

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 11, 2019 at 1:14 PM, Ricardo Prado<notifications@github.com> wrote:   
@justincampbell73 Could you try sending 0.03?

**Comment by jsolman** [comment]
Use this neoscan API to see your gas UTXOs: https://neoscan.io/docs/index.html#api-v1-get-3

If you claimed gas very frequently a lot of times at some point on that address it can leave you with many very small utxo amounts. Verify that isn’t the case using the above API.

**Comment by lock9** [comment]
@jsolman  do you think this can be considered a bug? Should fix? I suppose this will be fixed in neo 3 due to the fact we won't have utxo anymore. Could you confirm?
Thanks

**Comment by justincampbell73** [comment]
My other wallet is working fine. My old wallet can't remove the gas no matter what I do 

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 13, 2019 at 5:21 PM, Ricardo Prado<notifications@github.com> wrote:   
@jsolman do you think this can be considered a bug? Should fix? I suppose this will be fixed in neo 3 due to the fact we won't have utxo anymore. Could you confirm?
Thanks

**Comment by lock9** [comment]
@justincampbell73 I'm afraid this issue won't be resolved in neo 2, only in neo 3 :(
I'm going to close this because, unfortunately, this won't be fixed.
I will send you the 0.2 GAS you have stuck.

And thanks for reporting, this is, in fact, an unexpected error.

**Comment by vncoelho** [comment]
You have to many UTXOs @justincampbell73.

![image](https://user-images.githubusercontent.com/17395762/61244205-12571600-a720-11e9-8237-cb137d3548a4.png)


You can transfer one by one here at neocompiler (it is not safe for mainnet, but since the amount is not so big...But, please change the privatekey after it).

* Access https://neocompiler.io/#!/ecolab/wallet
* Go to Register new account
* Copy your public key
* Go to https://neocompiler.io/#!/ecolab/transaction
* Insert 21 + your_public_key + ac at "Create TX: Withdraw UTXO Assets from Contract " Verification script
* Select Asset = GAS

Click em 1 UTXO and transfer it one by one

It is not easy, but it is a funny task for you! :)

Otherwise, there may be a possible way to push to networks_fees via O3 wallet. But something like 0.01 and it might be enough.

**Comment by vncoelho** [comment]
@justincampbell73, download O3 wallet via https://o3.network and try to use or privatekey or encryptedkey to log in your wallet.

After that, send the funds attaching the amount of networks fees aforementioned and report the results.

**Comment by lock9** [comment]
I'm going to leave this closed because it won't be fixed, however, we are keeping the support open for you @justincampbell73. I hope this solves your problem, otherwise, I will just send you 0.2 gas instead :(

**Comment by vncoelho** [comment]
No free GAS, @justincampbell73, the knowledge worth more...aehauheuaea

**Comment by dicarlo2** [comment]
FWIW, we're working on resolving this relatively transparently for the user, with a fallback page for the more difficult cases. With that said, it's a bit lower priority than resyncing neotracker in order to fix the data consistency issues, so it'll likely be a few more weeks before we have a solid fix in place.

@steven1227

**Comment by justincampbell73** [comment]
Ok 

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 16, 2019 at 9:54 PM, Alex DiCarlo<notifications@github.com> wrote:   
FWIW, we're working on resolving this relatively transparently for the user, with a fallback page for the more difficult cases. With that said, it's a bit lower priority than resyncing neotracker in order to fix the data consistency issues, so it'll likely be a few more weeks before we have a solid fix in place.

@steven1227
