### ISSUE TITLE
Unable to withdraw from SC that has optional "params object[] args" in Main

### ISSUE THREAD

**Issue by birmas** [neo-project/neo#88]
The below contract will not allow you to withdraw NEO/GAS that have been deposited into it. The withdraw will work if Main is defined as Main(string operation)

```
namespace Neo.SmartContract
{
    public class Contract1 : Framework.SmartContract
    {
        public static Object Main(string operation, params object[] args)
        {
            return true;
        }
    }
}
```
Deploying contract with parameter "05"
<img width="409" alt="2017-10-23_16h15_07" src="https://user-images.githubusercontent.com/5135115/31873318-2d749028-b80e-11e7-97eb-acc739b348ae.png">

Adding a contract address with parameter "00". Attempting to withdraw from this contract address results in an "unconfirmed" transaction.
<img width="444" alt="2017-10-23_16h18_05" src="https://user-images.githubusercontent.com/5135115/31873322-321db618-b80e-11e7-9e67-55b18ece9bc3.png">

Adding a contract address with parameter "0010". Attempting to withdraw from this contract address results in an "incomplete" transaction. Attempting to sign this transaction (same as you would do for multisig) does not result in a "broadcast" button appearing.
<img width="447" alt="2017-10-23_16h22_09" src="https://user-images.githubusercontent.com/5135115/31873393-9ded5e2a-b80e-11e7-9704-15e5dd275efb.png">

<img width="387" alt="2017-10-23_16h24_06" src="https://user-images.githubusercontent.com/5135115/31873405-bad2af9a-b80e-11e7-95fd-9df6da84c222.png">

```
{"type":"Neo.Core.ContractTransaction","hex":"80000002100ed1d32f3084399deae52c4f27cf6296558f653ed458fcbe9549cd69a693120000100ed1d32f3084399deae52c4f27cf6296558f653ed458fcbe9549cd69a693120100019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc50011102401000000df2a1c93f5dc1fd3461371a7f5e40fa77d424afe","items":{"0xebba60c5d8e49ce5f92c3bf940f4050b603cc184":{"script":"53c56b6c766b00527ac46c766b51527ac461516c766b52527ac46203006c766b52c3616c7566","parameters":[{"type":"Signature","value":"5fa0319c4e27f6b3af9e0f465c52d2da60b5c87ede10b256c6f46d2bc6bbacf745b071b4ac4a8dc4842f181ac8e0b2fb832c81f4e920d2d250be69926ad60580"},{"type":"Array"}]},"0xfe4a427da70fe4f5a7711346d31fdcf5931c2adf":{"script":"21023c644ef85317bb0a4e0ce15adac77bf349ca869ba365d4e0b69ebe43b23ba1bdac","parameters":[{"type":"Signature","value":"4adb6b4c0033f7cd3d2618b95689bf319a7ad89d9eceb5211fdd5d7e136b723909dd0fd41d1239136e80381f33e0b01bcacf1f042ae27fd6994302f4c77ddd19"}]}}}
```

@erikzhang please let me know if I can provide any further information. This SC was deployed to a private net.

**Comment by birmas** [comment]
Additionally, I was attempting to debug the issue last night and the reason the second example (0010) doesn't work is that '10' parameter ends up being null which prevents ContractParametersContext.Completed from being flagged as true. I'm not sure what the intention of this code is so was hesitant to make changes without posting an issue first.

```
                return ContextItems.Values.All(p => p != null && p.Parameters.All(q => q.Value != null));
```

**Comment by birmas** [comment]
The "unconfirmed" transaction is caused by Neo.VM.ExecutionEngine throwing an exception in ExecuteOp while parsing OpCode.ROLL. Specifically in The Remove() call: EvaluationStack.Push(EvaluationStack.Remove(n));

I'm not sure whether or not the contract address should be defined as 0010 and be signed or be defined as 00 and have some kind of exception in the execution.

**Comment by tanZiWen** [comment]
First, if you only want to test smart contract 'withdraw' function, it is unnecessary to deploy smart contract to blockchain.
Second, your parameter list can try use 0001.
![wechatimg4](https://user-images.githubusercontent.com/8327633/31929391-73ec9f3e-b861-11e7-892b-cb3419759385.jpeg)
Third, If there are any signature is not complete, you should copy the incomplete signature content
, and signature the content.
![wechatimg2](https://user-images.githubusercontent.com/8327633/31929281-0e7b00b4-b861-11e7-8e23-f6aff6734a28.jpeg)
Fourth, Before you broadcast your transaction, you should fill in your parameter. Otherwise, you can not find broadcast button.
![wechatimg5](https://user-images.githubusercontent.com/8327633/31929553-1f9edd56-b862-11e7-9d2f-879b23f0f5e0.jpeg)

Hope can help you!

**Comment by birmas** [comment]
Thanks @tanZiWen - adding the placeholder to the transaction to initiate broadcast was the piece of information I was missing.

I'll close the issue request as there a work around.

**Comment by spytron** [comment]
@birmas can you pls explain how did you do that..
