### ISSUE TITLE
AssetDescriptor constructor throwing ArgumentException

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo#881]
When constructing an AssetDescriptor from NativeContract.NEO.Hash or NativeContract.GAS.Hash, the generated script faults and the constructor throws. I wrote tests for UT_NeoToken and UT_GasToken to validate there is an issue. 

``` csharp
[TestMethod]
public void Check_AssetDescription()
{
    // the following line throws ArgumentException even though
    // the argument is correct to the best of my knowledge
    var descriptor = new Wallets.AssetDescriptor(NativeContract.NEO.Hash);
    descriptor.AssetId.Should().Be(NativeContract.NEO.Hash);
    descriptor.AssetName.Should().Be("NEO");
    descriptor.Decimals.Should().Be(0);
}
```

**Comment by vncoelho** [comment]
It is very good when you find the problem with a UT, @devhawk.
If that proceeds let's PR that.
It is great to hear that you are already testing these native contracts.

**Comment by shargon** [comment]
Good find @devhawk , will be fixed on https://github.com/neo-project/neo/pull/882
