### ISSUE TITLE
"OutOfMemoryException" occurs and neo-cli crashes.

### ISSUE THREAD

**Issue by skashitam** [neo-project/neo#888]
I am using neo-cli v2.10.1.
I tried to deploy SmartContract to a test net from neo-cli,
"OutOfMemoryException" occurs and neo-cli crashes.

What causes "OutOfMemoryException" to occur?
Is there anything I can do?

**Comment by shargon** [comment]
Could you provide more information? like the complete error output

**Comment by skashitam** [comment]
I share the content of the error log

```
System.OutOfMemoryException
Insufficient memory to continue the execution of the program.
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.Append(Char value, Int32 repeatCount)
   at System.Text.StringBuilder.Append(Char value)
   at Neo.Services.ConsoleServiceBase.ParseCommandLineString(TextReader reader)
   at Neo.Services.ConsoleServiceBase.ParseCommandLine(String line)
   at Neo.Services.ConsoleServiceBase.RunConsole()
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
```

**Comment by shargon** [comment]
which command did you executed?

**Comment by skashitam** [comment]
I ran the deploy command.

`deploy Test.avm 0710 05 true false false "TokenName" "1" "author" "test@test.com" "description"`

**Comment by shargon** [comment]
Could you upload your test.avm?

**Comment by skashitam** [comment]
I can not upload avm.
Because I made it at work, I can not publish it.

What were you going to check using the avm file?
I will provide you with the necessary information.

**Comment by vncoelho** [comment]
I suggest to change to the latest versions.
For example, some weeks ago we fixed a memory leak on TCP IP tasks manager, thus, better to follow masters.

**Comment by vncoelho** [comment]
Now I got the out of memory, what is the size of the avm? Is there any loop in some part of it? whauahajauj

**Comment by skashitam** [comment]
@vncoelho 
Thank you for your reply.

I will try neo-cli v2.10.2.
The size of avm I'm trying to deploy is 32kb.

There are also places where loop processing is used.
Are there any problems with using loops?

**Comment by shargon** [comment]
I only ask for the avm because is important to replicate the issue, if you want to publish it on testnet, it will be public too.

**Comment by lock9** [comment]
@skashitam  your AVM will be public if deployed. If you provide us the AVM we can reproduce the error.

**Comment by lock9** [comment]
Hi @skashitam, how is your project going? Did you manage to make it work? Is it still crashing? Are you compiling with the official compiler?
Since neo-cli is crashing, I'm sure it is a bug, but I can't say for sure if the problem is in the AVM or in neo-cli.

**Comment by lock9** [comment]
I have to close this due to lack of activity 😢 
@skashitam  please feel free to create a new issue if the problem persists.
Thanks!

**Comment by vncoelho** [comment]
I think it is important to track this.

@skashitam, can you give more details on the size of the AVM and how to reproduce this problem?
Please, reopen this issue as soon as you reply.

**Comment by lock9** [comment]
@vncoelho  yes it is important, but without the AVM there is nothing we can do :(
