### ISSUE TITLE
Script header for multiple virtual machines

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#889]
I think that we could add a preffix in all scripts for identify the virtual machine to be used (0x00=neovm).
Now we could have only neo-vm, but in the future we could add `WebAssembly` or other if we thought that it could be usefull, one extra byte could helps a lot of in the future.

**Comment by igormcoelho** [comment]
Just an opinion: I think that neovm is an inherent part of Neo protocol... regarding webassembly, we could "easily" compile it for neovm. We already did some studies on this, we think its possible, although it wont be our direction this year... finish other things first.

**Comment by shargon** [comment]
I don't want to add webassembly support yet, only the header for allow it in the future without troubles

**Comment by lock9** [comment]
I think that use this is a good idea. Today we only run NVM code, but in the future we can have other scripts. This will be a developer decision

**Comment by erikzhang** [comment]
Adding header is good. We can add a 4-bytes header.

**Comment by erikzhang** [comment]
Or we can add a complicated header. Including fields such as `Magic`, `Version`, `Compiler`, etc.

**Comment by shargon** [comment]
Maybe we can add this header inside the manifest.

**Comment by lock9** [comment]
I think a complete header is better 👍

**Comment by igormcoelho** [comment]
I'm totally in favor of:

>   Or we can add a complicated header. Including fields such as Magic, Version, Compiler, etc. @erikzhang

First bytes of nvm could indicate the Magic and Version, perhaps the compiled language devpack (C#/Python/etc) and some more specific devpack versioning.
We could do that in, perhaps, 4 bytes.
1 byte magic
1 byte version
2 bytes language + compiler/devpack version (1 nibble gives 16 languages, + 2k versions)

It may not be enough for languages and devpacks, so in this case, 8 bytes would be better.
1 byte magic
1 byte version
2 bytes language (ASCII char  'py', 'c#', or 'cs', 'js', etc)
2 bytes compiler + devpack identification (max 64k).

**Comment by erikzhang** [comment]
We need 4 or 8 byte for magic.

**Comment by igormcoelho** [comment]
Perfect. I saw now on the PR, it's good  0xNEF3 magic.

**Comment by igormcoelho** [comment]
Version will be 0x03 or 0x01 ?

**Comment by lock9** [comment]
@igormcoelho I think we need the compiler version too.
- We need core because of the syscalls versioning;
- We need vm because it is how the script is run;
- We need the compiler because it generated the opcodes used by the vm

What if we have 4 bytes for each?
