### ISSUE TITLE
rename Trigger to ExecutionMode

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#894]
Many people are still confused by the name Trigger, so perhaps Neo3 could call it ExecutionMode. What do you think?

**Comment by shargon** [comment]
I think that is a good idea

**Comment by lock9** [comment]
I agree too. I think that ExecutionMode makes more sense

**Comment by vncoelho** [comment]
agreed too.

**Comment by igormcoelho** [comment]
@erikzhang do you think this change is harmful to the whitepaper or any ecosystem perspective? if not, we can proceed soon in applying this fix.

**Comment by erikzhang** [comment]
I think `Trigger` is more accurate. For example, in the future we add "Timer" as a new trigger?

**Comment by igormcoelho** [comment]
Well.. so Trigger may indeed become a timer trigger at some point hahaha if scope is not closed yet, so we better keep the name and let things flow.

**Comment by vncoelho** [comment]
ahauheshahau, keep Triggering.

**Comment by lock9** [comment]
If we have a new Timer Trigger, we can create a "Scheduled" execution mode. 
For the user (Smart Contract developer), it is not a trigger, it is a context. Could we reconsider closing this?
