### ISSUE TITLE
Create consensus message pool

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#909]
[From](https://github.com/neo-project/neo/issues/817#issuecomment-510083869) @jsolman  and @shargon in #817:

Create a message pool for consensus messages. Use it to filter the forwarded messages.

"@jsolman 
We should cache the consensus messages on the CN nodes in case they arrive out of order. Other nodes should cache also for a time and drop duplicates and prevent storms of consensus messages.

 @shargon
Yes, we can have a consensus message pool

 @jsolman
Also, any consensus message from a height less than the current block can just be dropped immediately and not forwarded. This alone will probably fix the issue."

**Comment by shargon** [comment]
@jsolman we already remove older consensus messages in verification

https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/ConsensusPayload.cs#L122-L127

**Comment by vncoelho** [comment]
I believe that older messages are already dropped and this should be handle by TaskManager and ProtocolHandler caches.

What we could do is to cache on-top payloads, as suggested in https://github.com/neo-project/neo/issues/788

**Comment by shargon** [comment]
but this verification could be made before, when was received without create more akka messages

**Comment by jsolman** [comment]
> @jsolman we already drop older consensus messages in verification

Yes, it should happen earlier and test to ensure they are not forwarded, but we need to be keeping future consensus messages also that we can’t use yet due to not having yet changed view or still being on the previous block.

**Comment by lock9** [comment]
I will close this in favor of #788. The solution is not identical but the problem is the same.
