### ISSUE TITLE
[bug] not accepting InteropInterface as contract return type

### ISSUE THREAD

**Issue by ixje** [neo-project/neo#910]
I'm looking at testnet block `1701573` and noticed that neo-cli's VM execution fails due to a supposedly invalid contract return type in the `Neo.Contract.Create` syscall, specifically the line below.

https://github.com/neo-project/neo/blob/5ca7e02085d1391849752ab569ed7ef0085c53ce/neo/SmartContract/NeoService.cs#L666

The interesting part is that when we inspect the item being popped from the `EvalutionStack` we get a `ByteArray` type with the value `0xF0`. This actually _is_  a valid type 
https://github.com/neo-project/neo/blob/5ca7e02085d1391849752ab569ed7ef0085c53ce/neo/SmartContract/ContractParameterType.cs#L17

However, because we next call `GetBigInteger()` the value turns into `-16` and that cannot be casted to a `byte` and we get an exception `FAULT`ing the VM.

Perhaps we should not call `GetBigInteger()` but call `GetByteArray()` instead and simply take the first byte as the return type?

**Comment by erikzhang** [comment]
We expect `0x00f0` for `ContractParameterType.InteropInterface`.

**Comment by ixje** [comment]
Uhh?! 
Can you explain where the additional `0x00` comes from in `0x00f0`?

**Comment by erikzhang** [comment]
In NeoVM, there is no `byte`. The only number type is `BigInteger`, and it is `signed`. So `0xf0` is `-16`, and `0x00f0` is `240`.

**Comment by ixje** [comment]
The good old signed type 🤷‍♂ 
My expectation was that the smart contract script would be composed such that there is a `ByteArray` with 1 byte that we can grab as the return type.
