### ISSUE TITLE
Unit test Fail when running UT_Culture and UT_RemoteNode together

### ISSUE THREAD

**Issue by eryeer** [neo-project/neo#922]
We encountered a strange bug. We were able to successfully run all the unit tests yesterday, but today unit test result is failed when  running `UT_RemoteNode `and `UT_Culture` together on some computers (and some other computers can run successfully). Recently this part of code seems to have not been modified. The problem is akka error.
<img width="255" alt="bug" src="https://user-images.githubusercontent.com/28225570/61264903-bf816b00-a7c0-11e9-9190-df48439e6a96.png">

When running `RemoteNode_Test_Accept_IfSameMagic` method alone, the result is success.
<img width="242" alt="2" src="https://user-images.githubusercontent.com/28225570/61265052-5cdc9f00-a7c1-11e9-9449-42e1807ec5fc.png">

When running  `All_Tests_Cultures` method alone, the result is failed.
<img width="250" alt="3" src="https://user-images.githubusercontent.com/28225570/61265139-ad53fc80-a7c1-11e9-861e-99ae88ae95f1.png">

**Comment by lock9** [comment]
I think we have a mailbox issue. I don't understand the changes Erik made to make the mailbox work. Can you disable these tests?

**Comment by eryeer** [comment]
OK, let's disable them first.

**Comment by igormcoelho** [comment]
I'll try to understand this too, it's fundamental for my understanding of other Akka/TestKit features.. this is supposed to work properly. :thinking:

**Comment by lock9** [comment]
@igormcoelho  Maybe we should reset the akka system during test initialization? Not sure, I think it is something with the mailbox, I can't be sure.
The problem is: I proposed this PR with some different modifications that the team didn't like much (like the usage of a factory), however, that was the recommended way of doing. I don't have idea of what could be done to replace it :(

**Comment by igormcoelho** [comment]
We need to understand the real cause first. 

* First, we need to make sure every `TestKit` instance is independent. It should be.

* Second, if it's not independent, by nature, then we should find a way of completely serializing all unit tests.

* Third, if it's supposed to be independent (as I think), but it's not being completely independent, it means some things are shared, that shouldn't. And I suspect one of the shared things (that shouldn't) is precisely the mailbox. We pass a string on the real ActorSystem, and perhaps we shouldn't reuse same string for mailbox on dummy ActorSystem (TestKit). 

Perhaps we need to change a few things on the code, perhaps controlling this string in a single place is enough to avoid problems. Let's see.

**Comment by igormcoelho** [comment]
It's systematically failing here, and systematically passing when I repeat it (only it)

![image](https://user-images.githubusercontent.com/290989/61490245-e091b980-a982-11e9-9337-3b4f9a3b8446.png)

![image](https://user-images.githubusercontent.com/290989/61490271-eb4c4e80-a982-11e9-92a9-69c8f0f7a5f7.png)

**Comment by igormcoelho** [comment]
Looks like it's building Connection twice :thinking: 
```
Failed   RemoteNode_Test_Accept_IfSameMagic_2
Error Message:
 Test method Neo.UnitTests.UT_RemoteNode.RemoteNode_Test_Accept_IfSameMagic_2 threw exception: 
Xunit.Sdk.TrueException: Failed: Expected a message of type Akka.IO.Tcp+Write, but received {Akka.IO.Tcp+Close} (type Akka.IO.Tcp+Close) instead  from TestActor[akka://test/user/$$j]
Expected: True
Actual:   False
Stack Trace:
    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 95
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`2 assert, String hint, Boolean shouldLog)
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nullable`1 timeout, Action`1 msgAssert, Action`1 senderAssert, String hint)
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`1 msgAssert, String hint)
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Nullable`1 duration, String hint)
   at Neo.UnitTests.UT_RemoteNode.RemoteNode_Test_Accept_IfSameMagic_2() in /home/imcoelho/git-reps/neo-tests/docker-configure-neo/neo-core/neo.UnitTests/UT_RemoteNode.cs:line 110

Standard Output Messages:
 Started build Connection!
 Crazy TCP!!
 Finished build Connection!
 Started build RemoteNode!
 Finished build RemoteNode! Will send data!
 Aqui!!!!
 Started build Connection!
 Crazy TCP!!
 Finished build Connection!
 Started build RemoteNode!
 Finished build RemoteNode! Will send data!
 [ERROR][18/07/2019 22:04:03][Thread 0004][akka://test/user/$$j] Object reference not set to an instance of an object.
 Cause: System.NullReferenceException: Object reference not set to an instance of an object.
    at Neo.Network.P2P.RemoteNode.<>c__DisplayClass39_0.<OnVersionPayload>b__1(RemoteNode p) in /home/imcoelho/git-reps/neo-tests/docker-configure-neo/neo-core/neo/Network/P2P/RemoteNode.cs:line 217
    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
    at Neo.Network.P2P.RemoteNode.OnVersionPayload(VersionPayload version) in /home/imcoelho/git-reps/neo-tests/docker-configure-neo/neo-core/neo/Network/P2P/RemoteNode.cs:line 217
    at Neo.Network.P2P.RemoteNode.OnReceive(Object message) in /home/imcoelho/git-reps/neo-tests/docker-configure-neo/neo-core/neo/Network/P2P/RemoteNode.cs:line 137
    at Akka.Actor.UntypedActor.Receive(Object message)
    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
    at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by lock9** [comment]
@igormcoelho  do you think this may be evidence that we have duplicated messages? Can you check? I'm using my mac right now, I can't run tests 😞

**Comment by igormcoelho** [comment]
Looks like inspecting from `Remote.Address` (in RemoteNode class) causes another Connection to emerge... still looking into it.

**Comment by lock9** [comment]
@igormcoelho  but I still don't understand why this caused the side effects, but I trust you when you say it is the test. Why does it use to work?

**Comment by igormcoelho** [comment]
I'm nearly fixing it in fact... another issue now is that:
```cs
LocalNode.Singleton.RemoteNodes.Values.Where(p => p != this)
```
is not cutting itself I guess...

**Comment by shargon** [comment]
i receive this one

```
Message: Test method Neo.UnitTests.UT_Culture.All_Tests_Cultures threw exception: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.TrueException: Failed: Expected a message of type Akka.IO.Tcp+Write, but received {Akka.IO.Tcp+Close} (type Akka.IO.Tcp+Close) instead  from TestActor[akka://test/user/$$l]
Expected: True
Actual:   False
```

**Comment by shargon** [comment]
We need that ` testBlockchain = TestBlockchain.InitializeMockNeoSystem();` is not shared between classes, I think It is important for parallel tests.

**Comment by igormcoelho** [comment]
after this weekend I think I can propose a good solution for this, definitive one

**Comment by shargon** [comment]
please review this until that https://github.com/neo-project/neo/issues/936

**Comment by vncoelho** [comment]
@igormcoelho, can you please come back with a good solution that has a strategical design?

**Comment by igormcoelho** [comment]
I fully agree, just should be properly fixed, not just workarounds, one after another.
