### ISSUE TITLE
Extend VM.Script to accept Hash

### ISSUE THREAD

**Issue by shargon** [neo-project/neo#940]
Now we compute the hash of the script every time is created a new context, but if you do something like this

```
CALL A
CALL A
CALL A
CALL A
```

4 time will be computed the SHA256+RIPEMD160

If we could change the script by other class in the moment that this is loaded like this

```
override OnNewScript(ref Script script){ } 
```

That could allow us to change it by our `ScriptWithHash` class, and remove all of this logic

https://github.com/neo-project/neo/blob/35d654c940964341f70f74dbe071c39957999ba5/neo/SmartContract/ApplicationEngine.cs#L55-L63

**Comment by lock9** [comment]
@shargon  sorry, but I don't know if I understood it correctly. You mean we should recalculate the script hash after we add more scripts to it?

**Comment by shargon** [comment]
We shouldn't, and now we recalculate it.

**Comment by lock9** [comment]
@shargon  what are the gains of this change? What is the main objective of this change? Improve performance? TPS?

**Comment by shargon** [comment]
if we reduce some hash computations, we will increase the performance

**Comment by lock9** [comment]
@shargon  if you have UT proving this increase in performance, I don't see why it would be rejected (if we have the same results with more performance).

**Comment by igormcoelho** [comment]
I agree, hashes are very expensive... it will matter on benchmarks, once we have them :joy:
