### ISSUE TITLE
Prepare MPT introduction for the community

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#941]
From @igormcoelho  in [#694](https://github.com/neo-project/neo/issues/694#issuecomment-480860206):

> @rodoufu we need to prepare a tutorial on MPT for the whole community understand our proposal. We also need to make sure that issue with "other implementations" is effectively resolved.

Can I suggest using UML for this? 

> The Unified Modeling Language (UML) is a general-purpose, developmental, modeling language in the field of software engineering that is intended to provide a standard way to visualize the design of a system.[1]

I believe UML is the "standard" for this. I'm saying this because I saw your discussion about "how to represent it'.

**Comment by rodoufu** [comment]
Hey @igormcoelho , what do you think about it?
Should be better an introduction using the key and values on the node, to avoid collisions, as the implementation on https://github.com/neo-project/neo-plugins/pull/97 ?

**Comment by rodoufu** [comment]
The main question about "how to represent it" is drawing a simple and meaningful representation to give the proper understanding of how the nodes are related to each other and how they change.
I see how I can use your suggestion to represent the decisions but what I really want to show is the  structure itself, I'm thinking about using a drawing with the nodes.

Another idea is to use the JSON representation, like:

Let's create a tree with the key and value (0x000001, 0x000001):
`["000001","001","001"]`

Now adding a new key and value (0x110002, 0x110002):
`{"0":["00001","001","001"],"1":["10002","1102","1102"]}`

**Comment by lock9** [comment]
@rodoufu  UML is able to represent both static and dynamic visions of the system.
I found this good article here if you want to check (not very deep):
https://creately.com/blog/diagrams/uml-diagram-types-examples/

I think that you can use the `communication diagram` for that particular case.
A `class diagram` could be good to show the basic structure of the MPT.
