### ISSUE TITLE
jsonrpc http error status codes

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo#95]
I've noticed that the RPC server returns a 200 status code even when there is an error. This should instead be something more appropriate like 500.

<img width="331" alt="screen shot 2017-10-29 at 22 28 35" src="https://user-images.githubusercontent.com/1255926/32144736-8aca93aa-bcf8-11e7-9f50-c05b17ddbb9d.png">

<img width="655" alt="screen shot 2017-10-29 at 22 28 40" src="https://user-images.githubusercontent.com/1255926/32144738-8fe6104e-bcf8-11e7-8db6-c3c145b2e9fa.png">

**Comment by erikzhang** [comment]
200 is an HTTP status code. In HTTP level, there is no error, so we return 200.

**Comment by notatestuser** [comment]
Although I could argue that there was an internal server error, hence making a 500 status appropriate

**Comment by PureKrome** [comment]
@notatestuser An `HTTP 500` error is when something _unexpected_ happens on their server. 

In the image above, it looks like something _expected_ happened ... just not a nice 'happy' result. So maybe 500 is the wrong status code but something else more appropriate in the `4xx` range.

like maybe `HTTP 400 Bad Request` ?

**Comment by notatestuser** [comment]
Yeah, something like that would also be fine
