### ISSUE TITLE
NullReferenceException when createAccount using scriptHash

### ISSUE THREAD

**Issue by eryeer** [neo-project/neo#951]
I came across an Exception when testing `CreateAccount(UInt160 scriptHash)` in `Neo.Wallets.SQLite.UserWallet`.

`CreateAccount(UInt160 scriptHash)` will call `AddAccount(UserWalletAccount account, bool is_import)` method but line126 `Address db_address = ctx.Addresses.FirstOrDefault(p => p.ScriptHash == account.Contract.ScriptHash.ToArray());`  in `Neo.Wallets.SQLite.UserWallet` will throw a NullReferenceException because account.Contract is null.

I think we need to add a nullable check before line126 .
![image](https://user-images.githubusercontent.com/28225570/61780795-c437c600-ae35-11e9-9182-e0fa5bcca35e.png)

**Comment by shargon** [comment]
Could you share with me this Unit test file?

**Comment by eryeer** [comment]
Please take a look at `TestCreateAccountByScriptHash` method in this file [https://github.com/eryeer/neoUT/blob/ut/neo.UnitTests/Wallets/SQLite/UT_UserWallet.cs](https://github.com/eryeer/neoUT/blob/ut/neo.UnitTests/Wallets/SQLite/UT_UserWallet.cs)

**Comment by Tommo-L** [comment]
https://github.com/eryeer/neoUT/blob/ut_bug/neo.UnitTests/Wallets/SQLite/UT_UserWallet.cs#L102-L107

**Comment by shargon** [comment]
Take a look at this pr:

https://github.com/eryeer/neoUT/pull/10

**Comment by eryeer** [comment]
Nick work @shargon ! Now I can close this.
