### ISSUE TITLE
A possible bug in Neo.Wallets.Import::Import(X509Certificate2 cert)

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#955]
Function code as follows:
```csharp
public virtual WalletAccount Import(X509Certificate2 cert)
{
    byte[] privateKey;
    using (ECDsa ecdsa = cert.GetECDsaPrivateKey())
    {
        privateKey = ecdsa.ExportParameters(true).D;
    }
    WalletAccount account = CreateAccount(privateKey);
    Array.Clear(privateKey, 0, privateKey.Length);
    return account;
}
```
where func ECDsa.ExportParameters(Boolean) is not supported in net framework 2.0.

Actually an exception occurs upon testing a p12 certificate:
```
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: "The requested operation is not supported."
at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
at System.Security.Cryptography.ECDsaCng.ExportParameters(Boolean includePrivateParameters)    at Neo.Wallets.Wallet.Import(X509Certificate2 cert) in C:\Repos\neoUT\neo\Wallets\Wallet.cs:line 188
at Neo.UnitTests.Wallets.UT_Wallet.TestImport3()
```

My conclusion after searching on net:
1. Func ExportParameters is not supported on NetStandard2.0
2. X509Certificate2 doesn't support private key in NetStandard2.0

Possible sulutions:
Import third party libraries such as Bouncy Castle (as it seems impossible to change framework), etc...

**Comment by shargon** [comment]
We should use Bouncy Castle, yes

**Comment by erikzhang** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsaprivatekey?view=netstandard-2.0

> .NET Standard
2.1 Preview 2.0 1.6 1.4

It is supported by .NET Standard 2.0.

**Comment by erikzhang** [comment]
> We should use Bouncy Castle, yes

The problem of Bouncy Castle is that it is ported from Java, and it uses the `BigInteger` that it implements instead of the one that comes with .NET. This has made it difficult for us to use it in practice.

**Comment by Qiao-Jin** [comment]
> https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.ecdsacertificateextensions.getecdsaprivatekey?view=netstandard-2.0
> 
> > .NET Standard
> > 2.1 Preview 2.0 1.6 1.4
> 
> It is supported by .NET Standard 2.0.

![image](https://user-images.githubusercontent.com/43407364/61860953-72f30980-aefd-11e9-9e3e-7ca6fe92a88c.png)

It shows in VS that Func `ExportParameters(bool includePrivateParameters)` is not available in NetStandard2.0. This function works well if `includePrivateParameters `is set to false (only public key exported), but throws exception otherwise(private key cannot be exported).

**Comment by lock9** [comment]
@Qiao-Jin can you help me to reproduce this error? Is this something we need to fix? If this happens only in UT, we could rename this issue. What is your opinion @Qiao-Jin ?

**Comment by Qiao-Jin** [comment]
> @Qiao-Jin can you help me to reproduce this error? Is this something we need to fix? If this happens only in UT, we could rename this issue. What is your opinion @Qiao-Jin ?

Please refer to this test case:
https://github.com/eryeer/neoUT/blob/919ddb60807a134e70ff5b4da824ef404fb9d3c3/neo.UnitTests/Wallets/UT_Wallet.cs#L264-L270

where file 11.p12 is a keypair file created with KeyStore Explorer.

**Comment by erikzhang** [comment]
Is your 11.p12 file an ECDSA certificate?

**Comment by Qiao-Jin** [comment]
> Is your 11.p12 file an ECDSA certificate? The RSA certificate is not supported.
Yes, this is an ECDSA-signatured certificate.
![image](https://user-images.githubusercontent.com/43407364/62443086-84a1a000-b78c-11e9-9451-b72a2b592f7b.png)
