### ISSUE TITLE
Create a 'github project template' and use it in all active projects. 

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#964]
Hello,

We need a way to make our repository look "more homogeneous". Use the same tags, add description, logo, etc.
We need one project "as template" to be used to guide other projects.
Dev-pack is an urgent case: https://github.com/neo-project/neo-devpack-dotnet

**Comment by shargon** [comment]
Agree

**Comment by rodoufu** [comment]
Do you think we should create a default for libraries to use?
I guess for DI it is a yes, but what about some other very used stuff like mocking?

I can see that neo project uses Moq, but, as far as I can tell, no other testing project is using a mock library so it may be a good time to define it.
https://github.com/neo-project/neo/blob/master/neo.UnitTests/neo.UnitTests.csproj
