### ISSUE TITLE
Use RocksDB?

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#966]
Should we use RocksDB instead of LevelDB?

**Comment by shargon** [comment]
RocksDb https://github.com/facebook/rocksdb/wiki/Features-Not-in-LevelDB

**Comment by lock9** [comment]
@shargon  is there any security or consistency problem we could have by using that?

**Comment by erikzhang** [comment]
Is there a .NET Standard library for RocksDB?

**Comment by shargon** [comment]
This nuget is for dotnet https://github.com/warrenfalk/rocksdb-sharp

**Comment by shargon** [comment]
> @shargon is there any security or consistency problem we could have by using that?

No, and maybe is better because now we are using rocksdb in mac, this unify all the storage layer

**Comment by Tommo-L** [comment]
There is a inconsistency bug before leveldb 1.22,  https://github.com/google/leveldb/issues/320. 
 But it has been fixed in rocksdb long long ago.

**Comment by shargon** [comment]
it is already decided? @neo-project/core

**Comment by erikzhang** [comment]
Not yet.

**Comment by igormcoelho** [comment]
For me, if it's safe to use natively on nugets, it's better than current one (easier to use and test). So I agree. 
Many changes are expected on this DB "migration"? During these changes, it would be nice to leave things more flexible, so that on the future, it becomes even easier to change that (mainly to support memory-only databases).

**Comment by lightszero** [comment]
Rocksdb is developed base on leveldb,so it is very easy to use it for NEO.

**Comment by shargon** [comment]
Take into account that rocksDb only works on x64 computers

**Comment by vncoelho** [comment]
@jsolman, what is your opinion?

**Comment by jsolman** [comment]
There is nothing wrong with using LevelDB as long as using the release that fixes the compaction bug mentioned earlier.

**Comment by lock9** [comment]
It looks like the majority of people are either in favor of this or at least "not against". 
I like this because it will allow me to run neo-cli in MacOS

**Comment by Qiao-Jin** [comment]
Some leveldb bugs might probably occur in NEO like https://github.com/google/leveldb/issues/320, but don't exist in ricksdb.
Rocksdb also provides better write efficiency & functionalities.
Moreover, rocksdb's API is very similiar to leveldb, which makes it convinient to transfer from leveldb to rocksdb.
I have tried the following experiment in Neo system:
1. Directly convert .ldb files to .sst ones by modifying file extension.
2. Use rocksdb's library in Native.cs funtions instead of leveldb's.
Node can be started without any problem.

**Comment by Qiao-Jin** [comment]
Using rocksdb might also be a solution for this issue as I commented: https://github.com/neo-project/neo/issues/597#issuecomment-519766426

**Comment by lock9** [comment]
@neo-project/core  we don't have a voting system in place yet, but it seems that we have a large majority of people that vote for RockDB. Can I move this to 'ready to implement'?

**Comment by shargon** [comment]
Rocksdb works only on x64, maybe we should be able to work with both of them, and switch by configuration

**Comment by lock9** [comment]
@shargon  maybe this is a good option to keep compatibility. 
@neo-project/core  Can we move this forward? I think we have sufficient votes and a solution with backward compatibility

**Comment by lock9** [comment]
@neo-project/core  Can we move this to ready-to-implement? This solves a lot of problems. Thanks.

**Comment by shargon** [comment]
I think that we should use column families intead of prefixes, what do you think @neo-project/core 
https://github.com/facebook/rocksdb/wiki/Column-Families#targetText=Each%20key-value%20pair%20in,to%20logically%20partition%20the%20database.

**Comment by shargon** [comment]
The last comment is from 7 days ago

> @neo-project/core Can we move this to ready-to-implement? This solves a lot of problems. Thanks.

And there are no more opinions until my pull request 😕

**Comment by shargon** [comment]
Now it's switchable https://github.com/neo-project/neo-cli/pull/451

**Comment by shargon** [comment]
I think that column families could help to save space, 1 byte per entry, and also, will save a lot of concatenations

**Comment by erikzhang** [comment]
Can we use RocksDb on x64 and LevelDb on x86?

**Comment by shargon** [comment]
Yes, we can change by config, or made LevelDB mandatory on x86.

Configuration: default -> RocksDB

if the system is x86 -> use LevelDB mandatory

**Comment by shargon** [comment]
Some benchmarks
https://www.influxdata.com/blog/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/

**Comment by vncoelho** [comment]
I saw this benchmark before, it is the only one I really found in favor of rocksdb, I saw other discussions in favor of leveldb but without tests.

But this benchmark is not very well experimentally designed, Shargon, I usually do not consider this as the final answer, that is why I am still not convinced that it is really more efficient for our case. However, I have faith it will.

**Comment by erikzhang** [comment]
I have another option: FASTER. https://github.com/microsoft/FASTER

> FASTER is a concurrent key-value store + cache that is designed for point lookups and heavy updates. FASTER supports data larger than memory, by leveraging fast external storage. It also supports consistent recovery using a new checkpointing technique that lets applications trade-off performance for commit latency.

Detailed analysis of C# FASTER performance: https://github.com/Microsoft/FASTER/wiki/Performance-of-FASTER-in-C%23

FASTER is implemented in two languages: C# and C++.

> The performance of the C# and C++ versions of FASTER are very similar.

@neo-project/core Let's consider it.

**Comment by shargon** [comment]
I considered it in the past and i think that @PeterLinX discarded it after his research. But I will review it again, maybe now is better!

**Comment by lightszero** [comment]
why not try to build a x86 version rocksdb？
