### ISSUE TITLE
A conflict comes out in NEO3 if an external node make transaction via a wallet which is opened by consensus node at the same time

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#970]
A conflict comes out in NEO3 if an external node makes transaction via a wallet which is opened by consensus node at the same time. Consensus node shows "An item with the same key has already been added.", like this:
![image](https://user-images.githubusercontent.com/38493437/62187127-fd72b780-b39a-11e9-93f9-f06eef51311b.png)
In external node, the tx was created successfully. They're using the same wallet 1.json. The 100 million NEO is need to be claimed from that wallet.
![image](https://user-images.githubusercontent.com/38493437/62187166-15e2d200-b39b-11e9-8c3f-109d89328152.png)

**Comment by shargon** [comment]
How could be repeated the hash in mempool? I understand that the error was thrown here

https://github.com/neo-project/neo/blob/cd994894acce73a871dccdf2ba6c2f0d598ec1b8/neo/Consensus/ConsensusContext.cs#L218

**Comment by superboyiii** [comment]
@shargon Yes, you're right. There're two same transactions in the dictionary when ConsensusPayload MakePrepareRequest().
![image](https://user-images.githubusercontent.com/38493437/62262258-9ca2b800-b44a-11e9-8bb4-004da604204d.png)

**Comment by superboyiii** [comment]
Seems it's a matter of SimplePolicy. Now I removed it, cli works. I will close this PR since SimplePolicy was already removed.
