### ISSUE TITLE
Update code to use custom Exception sub-classes

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#975]
Hello,

Any chance we can use custom Exception sub-classes to make errors handling more "accurate"? For instance, we may want to have different messages and different behavior for different exceptions.

Also, I was unable to catch exceptions in our UT. The exceptions don't seem to be released to the UT. I believe this is related to AKKA. Do you guys know how to get an exception when it occurs inside an Actor?

Tasks:
- [ ] Create sub-classes
- [ ] Update code to use these sub-classes and emit more error information (specially in RPC)

**Comment by shargon** [comment]
Yes please, also we should avoid in some cases the exceptions, throw exceptions are expensive

**Comment by MorganDream** [comment]
Voting for this suggestion. Cannot get exactly what goes wrong when sending rpc request.

**Comment by lock9** [comment]
@neo-project/core can I consider this ready to implement? I think we have enough votes? Thanks

**Comment by shargon** [comment]
Yes for me

**Comment by rodoufu** [comment]
Yes @lock9,  that may be related to Akka, as you can see in the documentation https://doc.akka.io/docs/akka/2.5/actors.html#actors-and-exceptions
When an actor processing a message throws an exception, this message gets lost, so for dealing with errors inside the Akka system we need to treat our exceptions or use some error codes to handle it which is far faster, as @shargon already said.
> Yes please, also we should avoid in some cases the exceptions, throw exceptions are expensive

What kind of exceptions were you trying to catch?

**Comment by lock9** [comment]
@rodoufu  I'm trying to force some exceptions in some tests, but I can't make it work :(
