### ISSUE TITLE
EventHandler declaration changes break neo-gui-developer event log

### ISSUE THREAD

**Issue by hal0x2328** [neo-project/neo#98]
The change in the declaration from `public static EventHandler` to `public EventHandler`for `Log` and `Notify` events in 
https://github.com/neo-project/neo/commit/4e4afce5d7b9c29d2bb70ec4de6d14a5a4fcda3c#diff-f1186f61e236326ea439a6fc0213f471 breaks the Event Log tab's functionality in neo-gui-developer. 

It doesn't look like there is a way to add an event handler from the top-level form class if these event handlers are not declared static in StateReader.cs. 

I noticed that the blockchain block notification handler is still declared static, so is there a particular reason only these two declarations were changed, or is there a workaround for adding event handlers from the top level? (I've tried using the singleton method of access but it doesn't seem to work, possibly because of the way that StateMachine.cs instantiates the StateReader class when the ApplicationEngine is started - only `Notify` events added by the StateMachine class' handler seem to fire).

**Comment by birmas** [comment]
Second this - have had to work around by declaring those members as static again which is not ideal.

**Comment by erikzhang** [comment]
1. Add handler to StateReader.Default.Notify, for verification.
1. Add handler to Blockchain.Notify, for application.
1. Add handler to StateMachine object in https://github.com/neo-project/neo/blob/master/neo/SmartContract/ApplicationEngine.cs#L265, for test.
