### ISSUE TITLE
Rename class of `OrderedDictionary.cs`

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo#981]
@shargon, I believe that this class should be something like `NEOOrderedDictionary`, it is making confusion with the use on `FifoSet`. 

What do you think?

**Comment by shargon** [comment]
I prefer FifoSet, NEOO sounds weir to me xD

**Comment by vncoelho** [comment]
@shargon, I am not understanding, because the `OrderedDictionary.cs` should not be used on the `FifoSet`, you created that for the JObject.

**Comment by shargon** [comment]
I remember to discuss the use of `OrderedDictionary` with @jsolman in the past, and he convinced me.

**Comment by vncoelho** [comment]
I mean, @shargon, NEO 2.x is not using the `reimplemention`, it is using the one form `System.Collectins.Specialized`, while NEO 3.x is probably using one you created.
Better to have this more clear

**Comment by igormcoelho** [comment]
Isn't it from C# core? https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary?view=netframework-4.8

**Comment by vncoelho** [comment]
One is, the other one was added in a recent PR: https://github.com/neo-project/neo/blob/master/neo/IO/Caching/OrderedDictionary.cs

**Comment by lock9** [comment]
Hello,
My opinion is that I don't think we should add "NEO" prefix to any class since this does not 'enrich' the class description. We could change its name but with something with more 'semantic value'

**Comment by lock9** [comment]
@neo-project/core  are we implementing this? Should we close it? @vncoelho  what is your opinion, do you still want to change this?

**Comment by shargon** [comment]
I think that is not needed

**Comment by vncoelho** [comment]
Still needed I think, it is confusing after the insertion of FifoSet.

**Comment by erikzhang** [comment]
It's a generic version of .NET `OrderedDictionary`. I don't think it should be renamed.

**Comment by vncoelho** [comment]
@erikzhang, a name hidding seams have been introduced here: https://github.com/neo-project/neo/blob/34faf4ed8029203595d767a7840826adc789d71e/neo/IO/Caching/OrderedDictionary.cs

I know about the generic version of .NET `OrderedDictionary`, which is different than this one I just referenced above.

In some parts of the code we use .NET and in the other uses we use NEO.IO.Caching.OrderedDictionary

**Comment by lock9** [comment]
What if we call "CachedOrderedDictionary"?

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/66249944-ce1d5580-e711-11e9-942f-9f11052ae3b1.png)

It use is only on `Io.Json` `JObject` for `public IDictionary<string, JObject> Properties`.

Is there any other use in mind for this class? @shargon

**Comment by shargon** [comment]
Only there
