### ISSUE TITLE
Function GetRegisteredValidators fails to work

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo#985]
When I'm testing func NeoToken::GetRegisteredValidators & NeoToken::RegisterValidator, I saw that registered validator cannot be got by GetRegisteredValidators.

I looked into the code and find that this is due to a code defect in DataCache::Find(byte[] key_prefix = null). Buggy code is shown below:

```csharp
lock (dictionary)
{
    cached = dictionary.
                    Where(p => p.Value.State != TrackState.Deleted && (key_prefix == null || p.Key.ToArray().Take(key_prefix.Length).SequenceEqual(key_prefix)))
                    .Select(p =>
                    (
                        KeyBytes: p.Key.ToArray(),
                        p.Key,
                        p.Value.Item
                    ))
                    .OrderBy(p => p.KeyBytes, ByteArrayComparer.Default)
                    .ToArray();
}
```

Here `p.Key.ToArray()` will convert the whole StorageKey to byte array instead of StorageKey.Key. A fix should be necessary.

**Comment by erikzhang** [comment]
This has nothing to do with `StorageKey`. This is `DataCache`.

**Comment by Qiao-Jin** [comment]
https://github.com/eryeer/neoUT/blob/7e6c50b2e787cdbfc1344da273b83046ad184ca5/neo.UnitTests/SmartContract/Native/Tokens/UT_NeoToken.cs#L316-L328

This test registers a validator and tries to find it, but failed.

**Comment by lock9** [comment]
@Qiao-Jin Hello! Could you rename your issue to something "more informative"? It is because with a better title, it is easier to find it later.
Thanks
