### ISSUE TITLE
Create class for PublicKey and Signature

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/neo#989]
Not all of us are superhumans like Erik, so I propose to create simple classes PublicKey and Signature, for the rest of us, poor human beings :joy:

Really, I still have many difficulties in understanding the usage of ECPoint, ECCurve, ECField, etc, just to handle a simple publickey. I often forget too which is the correct size of a signature for Neo secp256r1 (64 bytes, right?).
I think that, in the end, these classes are useful and necessary to represent the basic concepts of PublicKey and Signature on Neo. Signature is just a 64-bytearray today (because we are using secp256r1), but who knows tomorrow? Same for PublicKey, it's hard for me to simply handle it as a bytearray in compressed (33-bytes) or uncompressed format (which I don't know the size now...)

I think that this simplifies many things, and makes it much easier to handle this two fundamental concepts during the whole project.

**Comment by igormcoelho** [comment]
This will already help on some doubts I have now, during the implementation of Scoped Witnesses too (that's why I'm already starting to implement a PR, before further discussions, sorry for that, but I need it :joy:).
If someone wants to do it, very quickly, feel free to open another PR and I'll close mine. My intention is to use in next days, if possible.

**Comment by shargon** [comment]
In which case are you confusing?

**Comment by igormcoelho** [comment]
The point is that ECPoint is not a public key... and byte[] is not a signature. We are missing the semantics. There are many advantages in having specific classes in this case, such as:
- corretness of serialization. it won't be possible to exist signatures with less or more than 64 bytes. Same for ECPoint... we don't even have a standard for serializing public keys on Neo, and it's important to have one, even for SDK devpack (we are supposed to allow receiving those as parameters, on NEP3 ABI)
- correctness of comparison. Comparing bytearrays can be tricky sometimes... a simple Equals between Signatures or Pubkeys will guarantee that its correct
- much easier to understand. If we pass Signature and PublicKey to other methods, everybody will be able to directly understand its meaning. When you pass an ECPoint, it doesn't mean it's a publickey, because it depends on which curve are you talking about. Neo cryptography is based on secp256r1, so we _deserve_ to have classes for that.

**Comment by vncoelho** [comment]
I agree with Igor, I think that it will become more readable and flexible.
I prefer to split and create a simple class or, at least, a `struct`. But I do not know the best design for C#.

**Comment by lock9** [comment]
I think this is a good idea, but in any case, could you create a class diagram to try to show us how these new classes would work?

**Comment by shargon** [comment]
If is more readable, Is good to me

**Comment by lock9** [comment]
I counted 3 votes, so I'm moving this to design.

**Comment by igormcoelho** [comment]
Agree to do this, but like Erik said, this is a major refactor. I would prefer to do this when we have Schnorr sigs proposal.

**Comment by lock9** [comment]
@igormcoelho  where did he say that this is a major refactor? 
Isn't this just a cosmetic refactor?
