### ISSUE TITLE
About neo upgraded to dotnetcore2.0 can not be synchronized

### ISSUE THREAD

**Issue by xflytang** [neo-project/neo#99]
neo upgraded to dotnetcore2.0 can not be synchronized

**Comment by xflytang** [comment]
TcpRemoteNode.cs 
In ReceiveMessageAsync，SendMessageAsync function, donetcore1.0 Creates an awaitable task that asynchronously yields back to the current context when awaited. but donetcore12.0 not create, So need to add "Task.Yield()"

`                 await Task.Yield(); 
`  
`  
                 return await Message.DeserializeFromAsync(stream, source.Token);
`

`    
                 await Task.Yield();
`  
`  
                 await stream.WriteAsync(buffer, 0, buffer.Length, source.Token);
`

**Comment by erikzhang** [comment]
fixed in b88846ea997ba3fe8d4a58bf2dbd0f970d4a2e8f
