### ISSUE TITLE
Add TTL property to Transactions and add DefaultTransactionTTL and MaxTransactionTTL values in Network Policy

### ISSUE THREAD

**Issue by lock9** [neo-project/neo#995]
Hello,
I think we could add a 'time to live' property in each transaction, measured in blocks. I think 1 byte is enough for this. I don't know if this value should be stored in the blockchain, I don't see any reasons to store it.

We could allow a small value for free transactions (like 3 blocks) and allow larger values only for transactions with a priority fee attached.
This can help us to predict which transaction can be dropped from the mempool, while also allowing developers to know when to check for the confirmed transaction (and when to resend it).

**Comment by shargon** [comment]
We have now `ValidUntilBlock`

**Comment by lock9** [comment]
Thanks @shargon, I will look for it. Is this something new in NEO 3? I don't remember this property from NEO 2 🤔

**Comment by lock9** [comment]
@shargon  I found it here: #765, however, I didn't see where we configure the maximum values or limit free transactions.
If you guys think that PR is enough, we can close this one.

**Comment by shargon** [comment]
Is only on neo3

**Comment by lock9** [comment]
@shargon  but do you think it is complete / enough? Can we close this then?

**Comment by shargon** [comment]
but you mention, free transactions, and there are no free tx in neo3...

**Comment by lock9** [comment]
haha @shargon sorry, I completely forgot about that. 
I will close this, it is already implemented.
