### ISSUE TITLE
Genesis gas isn't able to be transfered because of VM excution failure

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo#999]
Genesis gas isn't able to be transfered because of VM excution failure.
![image](https://user-images.githubusercontent.com/38493437/62445662-58d5e880-b793-11e9-98d3-05bc959bf331.png)
![image](https://user-images.githubusercontent.com/38493437/62445693-6f7c3f80-b793-11e9-9fd5-f2bcafd5c8c6.png)

**Comment by shargon** [comment]
Not my case ...

![image](https://user-images.githubusercontent.com/3167973/62467187-6c814f00-b793-11e9-9841-319cccc542da.png)

![image](https://user-images.githubusercontent.com/3167973/62467214-7d31c500-b793-11e9-96a1-6d21491cd3f6.png)

**Comment by erikzhang** [comment]
@superboyiii Did you modify the code? I found that your output is different from ours. (list asset)

**Comment by erikzhang** [comment]
I tested it locally and found no problems.

```
NEO-CLI Version: 2.10.1

neo> open wallet m.json
password: *******
neo> list asset
NEO: 100000000
GAS: 30000000
neo> send gas AUBpcbQG6ebfdKrTCbRaZXQQxo7D9YB4o3 1000
password: *******
TXID: 0xfc56658ca5dd3cc2efcfb38defe27b73acc51573a6e8dca6b0972fc67ddaf0fd
neo>
```

**Comment by shargon** [comment]
My tests was with only one validator, @superboyiii could you provide the steps for reproduce this behaviour?

**Comment by superboyiii** [comment]
@shargon @erikzhang  Yes, the first time for transaction is always successful but no more than twice. All will be failed! 
![image](https://user-images.githubusercontent.com/38493437/62508565-b3764f80-b83a-11e9-8601-1357ee80df4a.png)

**Comment by superboyiii** [comment]
Print more details of balance.
![image](https://user-images.githubusercontent.com/38493437/62520444-2f36c300-b860-11e9-9917-60ee5fbb9ae1.png)
